package eu.europa.ec.budg.abac.legal_entity.service.es.async.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-06T14:19:46.385+02:00
 * Generated source version: 3.1.12
 */
@WebServiceClient(name = "LegalEntity",
        //wsdlLocation = "file:/C:/Users/lviverof/Documents/test2/src/main/java/BUDG_LegalEntity_ES_Async_2.wsdl",
        wsdlLocation = "http://wlts0275.cc.cec.eu.int:1043/wifi4eu-financial/wsdl/BBUDG_LegalEntity_ES_Async_2.wsdl",
        //wsdlLocation = "http://localhost:7001/wifi4eu-financial/wsdl/BUDG_LegalEntity_ES_Async_2.wsdl",
        targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_entity/service/es/async/v1")
public class LegalEntity extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.ec.europa.eu/budg/abac/legal_entity/service/es/async/v1", "LegalEntity");
    public final static QName LegalEntitySOAP = new QName("http://www.ec.europa.eu/budg/abac/legal_entity/service/es/async/v1", "LegalEntitySOAP");

    static {
        URL url = null;
        try {
            //url = new URL("file:/C:/Users/lviverof/Documents/test2/src/main/java/BUDG_LegalEntity_ES_Async_2.wsdl");
            url = new URL("http://wlts0275.cc.cec.eu.int:1043/wifi4eu-financial/wsdl/BUDG_LegalEntity_ES_Async_2.wsdl");
            //url = new URL("http://localhost:7001/wifi4eu-financial/wsdl/BUDG_LegalEntity_ES_Async_2.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LegalEntity.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "BUDG_LegalEntity_ES_Async_2.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LegalEntity(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LegalEntity(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LegalEntity() {
        super(WSDL_LOCATION, SERVICE);
    }

    public LegalEntity(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LegalEntity(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LegalEntity(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     * @return returns LegalEntityPort
     */
    @WebEndpoint(name = "LegalEntitySOAP")
    public LegalEntityPort getLegalEntitySOAP() {
        return super.getPort(LegalEntitySOAP, LegalEntityPort.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns LegalEntityPort
     */
    @WebEndpoint(name = "LegalEntitySOAP")
    public LegalEntityPort getLegalEntitySOAP(WebServiceFeature... features) {
        return super.getPort(LegalEntitySOAP, LegalEntityPort.class, features);
    }

}
