package eu.europa.ec.budg.abac.legal_commitment.service.es.async.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-15T07:29:25.985+02:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "LegalCommitment", 
                  //wsdlLocation = "file:/C:/Users/lviverof/Documents/test2/src/main/java/BUDG_LegalCommitment_ES_Async_1.wsdl",
                  wsdlLocation = "http://wlts0275.cc.cec.eu.int:1043/wifi4eu-financial/wsdl/BUDG_LegalCommitment_ES_Async_1.wsdl",
                  //wsdlLocation = "http://localhost:7001/wifi4eu-financial/wsdl/BUDG_LegalCommitment_ES_Async_1.wsdl",
                  targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/async/v1") 
public class LegalCommitment extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/async/v1", "LegalCommitment");
    public final static QName LegalCommitment = new QName("http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/async/v1", "LegalCommitment");
    static {
        URL url = null;
        try {
            //url = new URL("file:/C:/Users/lviverof/Documents/test2/src/main/java/BUDG_LegalCommitment_ES_Async_1.wsdl");
            url = new URL("http://wlts0275.cc.cec.eu.int:1043/wifi4eu-financial/wsdl/BUDG_LegalCommitment_ES_Async_1.wsdl");
            //url = new URL("http://localhost:7001/wifi4eu-financial/wsdl/BUDG_LegalCommitment_ES_Async_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LegalCommitment.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "BUDG_LegalCommitment_ES_Async_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LegalCommitment(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LegalCommitment(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LegalCommitment() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public LegalCommitment(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LegalCommitment(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LegalCommitment(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns LegalCommitmentPort
     */
    @WebEndpoint(name = "LegalCommitment")
    public LegalCommitmentPort getLegalCommitment() {
        return super.getPort(LegalCommitment, LegalCommitmentPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LegalCommitmentPort
     */
    @WebEndpoint(name = "LegalCommitment")
    public LegalCommitmentPort getLegalCommitment(WebServiceFeature... features) {
        return super.getPort(LegalCommitment, LegalCommitmentPort.class, features);
    }

}
