<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ec.europa.eu/budg/abac/reason_payment_time_limit_not_applicable/service/es/sync/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:rptlna="http://www.ec.europa.eu/budg/abac/reason_payment_time_limit_not_applicable/v1" xmlns:fault="http://www.ec.europa.eu/budg/abac/messagefault/v1" name="ReasonPaymentTimeLimitNotApplicable" targetNamespace="http://www.ec.europa.eu/budg/abac/reason_payment_time_limit_not_applicable/service/es/sync/v1">
	<wsdl:import location="FaultMessage.wsdl" namespace="http://www.ec.europa.eu/budg/abac/messagefault/v1"/>
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.ec.europa.eu/budg/abac/reason_payment_time_limit_not_applicable/v1" schemaLocation="xsd/timelimit/BUDG_ReasonPaymentTimeLimitNotApplicable_Find_1.xsd">
    	</xsd:import>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="ReasonPaymentTimeLimitNotApplicableFindRequest">
		<wsdl:part name="parameters" element="rptlna:ReasonPaymentTimeLimitNotApplicableFindRequest"/>
	</wsdl:message>
	<wsdl:message name="ReasonPaymentTimeLimitNotApplicableFindResponse">
		<wsdl:part name="parameters" element="rptlna:ReasonPaymentTimeLimitNotApplicableFindResponse"/>
	</wsdl:message>
	<wsdl:portType name="ReasonPaymentTimeLimitNotApplicablePort">
		<wsdl:operation name="find">
			<wsdl:input message="tns:ReasonPaymentTimeLimitNotApplicableFindRequest"/>
			<wsdl:output message="tns:ReasonPaymentTimeLimitNotApplicableFindResponse"/>
			<wsdl:fault name="Fault" message="fault:FaultMessage"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="ReasonPaymentTimeLimitNotApplicableSOAP" type="tns:ReasonPaymentTimeLimitNotApplicablePort">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="find">
			<soap:operation soapAction="http://www.ec.europa.eu/budg/abac/reason_payment_time_limit_not_applicable/service/es/sync/find/v1"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="Fault"><soap:fault name="Fault" use="literal"/></wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ReasonPaymentTimeLimitNotApplicable">
		<wsdl:port name="ReasonPaymentTimeLimitNotApplicableSOAP" binding="tns:ReasonPaymentTimeLimitNotApplicableSOAP">
			<!--<soap:address location="http://localhost:7001/abac/service/ReasonPaymentTimeLimitNotApplicable/v1"/>-->
			<soap:address location="https://intragate.test.ec.europa.eu/webpaxanwtst_nt_pub/abac/service/ReasonPaymentTimeLimitNotApplicable/v1"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
