<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:src="http://www.ec.europa.eu/budg/abac/guarantee/v1" xmlns:get="http://www.ec.europa.eu/budg/abac/guarantee/v1" xmlns:tns="http://www.ec.europa.eu/budg/abac/guarantee/service/es/sync/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fault="http://www.ec.europa.eu/budg/abac/messagefault/v1" name="Guarantee" targetNamespace="http://www.ec.europa.eu/budg/abac/guarantee/service/es/sync/v1">
	<wsdl:import namespace="http://www.ec.europa.eu/budg/abac/messagefault/v1" location="FaultMessage.wsdl"/>
	<wsdl:types>
		<xsd:schema targetNamespace="http://www.ec.europa.eu/budg/abac/guarantee/v1">
			<xsd:include schemaLocation="xsd/guarantee/BUDG_Guarantee_Get_1.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="GuaranteeGetRequest">
		<wsdl:part name="request" element="get:GuaranteeGetRequest"/>
	</wsdl:message>
	<wsdl:message name="GuaranteeGetResponse">
		<wsdl:part name="response" element="get:GuaranteeGetResponse"/>
	</wsdl:message>
	<wsdl:portType name="GuaranteePort">
		<wsdl:operation name="get">
			<wsdl:input message="tns:GuaranteeGetRequest"/>
			<wsdl:output message="tns:GuaranteeGetResponse"/>
			<wsdl:fault name="Fault" message="fault:FaultMessage"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="GuaranteeSOAP" type="tns:GuaranteePort">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="get">
			<soap:operation soapAction="http://www.ec.europa.eu/budg/abac/guarantee/service/es/sync/get/v1"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="Fault"><soap:fault name="Fault" use="literal"/></wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="Guarantee">
		<wsdl:port name="GuaranteeSOAP" binding="tns:GuaranteeSOAP">
			<!--<soap:address location="http://localhost:7001/abac/service/Guarantee/v1"/>-->
			<soap:address location="https://intragate.test.ec.europa.eu/webpaxanwtst_nt_pub/abac/service/Guarantee/v1"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
