<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ec.europa.eu/budg/abac/business_area/service/es/sync/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fnd="http://www.ec.europa.eu/budg/abac/business_area/v1" xmlns:fault="http://www.ec.europa.eu/budg/abac/messagefault/v1" name="BusinessArea" targetNamespace="http://www.ec.europa.eu/budg/abac/business_area/service/es/sync/v1">
	<wsdl:import location="FaultMessage.wsdl" namespace="http://www.ec.europa.eu/budg/abac/messagefault/v1"/>
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.ec.europa.eu/budg/abac/business_area/v1" schemaLocation="xsd/businessarea/BUDG_BusinessArea_Find_1.xsd">
    	</xsd:import>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="BusinessAreaFindRequest">
		<wsdl:part name="parameters" element="fnd:BusinessAreaFindRequest"/>
	</wsdl:message>
	<wsdl:message name="BusinessAreaFindResponse">
		<wsdl:part name="parameters" element="fnd:BusinessAreaFindResponse"/>
	</wsdl:message>
	<wsdl:portType name="BusinessAreaPort">
		<wsdl:operation name="find">
			<wsdl:input message="tns:BusinessAreaFindRequest"/>
			<wsdl:output message="tns:BusinessAreaFindResponse"/>
			<wsdl:fault name="Fault" message="fault:FaultMessage"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="BusinessAreaSOAP" type="tns:BusinessAreaPort">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="find">
			<soap:operation soapAction="http://www.ec.europa.eu/budg/abac/business_area/service/es/sync/find/v1"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="Fault"><soap:fault name="Fault" use="literal"/></wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="BusinessArea">
		<wsdl:port name="BusinessAreaSOAP" binding="tns:BusinessAreaSOAP">
			<!--<soap:address location="http://localhost:7001/abac/service/BusinessArea/v1"/>-->
			<soap:address location="https://intragate.test.ec.europa.eu/webpaxanwtst_nt_pub/abac/service/BusinessArea/v1"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
