<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:src="http://www.ec.europa.eu/budg/abac/legal_commitment/v1" xmlns:get="http://www.ec.europa.eu/budg/abac/legal_commitment/v1" xmlns:tns="http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/sync/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fault="http://www.ec.europa.eu/budg/abac/messagefault/v1" name="LegalCommitment" targetNamespace="http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/sync/v1">
	<wsdl:import namespace="http://www.ec.europa.eu/budg/abac/messagefault/v1" location="FaultMessage.wsdl"/>
	<wsdl:types>
		<xsd:schema targetNamespace="http://www.ec.europa.eu/budg/abac/legal_commitment/v1">
			<xsd:include schemaLocation="xsd/legalcommitment/BUDG_LegalCommitment_GetPaymentDeductionModes_1.xsd"/>
		</xsd:schema>
	
	</wsdl:types>
	<wsdl:message name="LegalCommitmentGetPaymentDeductionModesRequest">
		<wsdl:part name="request" element="src:LegalCommitmentGetPaymentDeductionModesRequest"/>
	</wsdl:message>
	<wsdl:message name="LegalCommitmentGetPaymentDeductionModesResponse">
		<wsdl:part name="response" element="src:LegalCommitmentGetPaymentDeductionModesResponse"/>
	</wsdl:message>
	<wsdl:portType name="LegalCommitmentPort">
		<wsdl:operation name="get_payment_deduction_modes">
			<wsdl:input message="tns:LegalCommitmentGetPaymentDeductionModesRequest"/>
			<wsdl:output message="tns:LegalCommitmentGetPaymentDeductionModesResponse"/>
			<wsdl:fault name="Fault" message="fault:FaultMessage"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="LegalCommitmentSOAP" type="tns:LegalCommitmentPort">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="get_payment_deduction_modes">
			<soap:operation soapAction="http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/sync/get_payment_deduction_modes/v1"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="Fault"><soap:fault name="Fault" use="literal"/></wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="LegalCommitment">
		<wsdl:port name="LegalCommitment" binding="tns:LegalCommitmentSOAP">
			<!--<soap:address location="http://localhost:7001/abac/service/LegalCommitment/v1"/>-->
			<soap:address location="https://intragate.test.ec.europa.eu/webpaxanwtst_nt_pub/abac/service/LegalCommitment/v1"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
