<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:tns="http://www.ec.europa.eu/budg/abac/commitment_appropriation/service/es/sync/v1" 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xmlns:src="http://www.ec.europa.eu/budg/abac/appropriation/v1" 
xmlns:fault="http://www.ec.europa.eu/budg/abac/messagefault/v1" 
name="CommitmentAppropriation" targetNamespace="http://www.ec.europa.eu/budg/abac/commitment_appropriation/service/es/sync/v1">
	<wsdl:import location="FaultMessage.wsdl" namespace="http://www.ec.europa.eu/budg/abac/messagefault/v1"/>
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.ec.europa.eu/budg/abac/appropriation/v1" schemaLocation="xsd/appropriation/BUDG_Appropriation_Search_1.xsd">
    	</xsd:import>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="CommitmentAppropriationSearchRequest">
		<wsdl:part name="parameters" element="src:CommitmentAppropriationSearchRequest"/>
	</wsdl:message>
	<wsdl:message name="CommitmentAppropriationSearchResponse">
		<wsdl:part name="parameters" element="src:CommitmentAppropriationSearchResponse"/>
	</wsdl:message>
	<wsdl:portType name="CommitmentAppropriationPort">
		<wsdl:operation name="search">
			<wsdl:input message="tns:CommitmentAppropriationSearchRequest"/>
			<wsdl:output message="tns:CommitmentAppropriationSearchResponse"/>
			<wsdl:fault name="Fault" message="fault:FaultMessage"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="CommitmentAppropriationSOAP" type="tns:CommitmentAppropriationPort">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="search">
			<soap:operation soapAction="http://www.ec.europa.eu/budg/abac/commitment_appropriation/service/es/sync/search/v1"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="Fault"><soap:fault name="Fault" use="literal"/></wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="CommitmentAppropriation">
		<wsdl:port name="CommitmentAppropriationSOAP" binding="tns:CommitmentAppropriationSOAP">
			<!--<soap:address location="http://localhost:7001/abac/service/CommitmentAppropriation/v1"/>-->
			<soap:address location="https://intragate.test.ec.europa.eu/webpaxanwtst_nt_pub/abac/service/CommitmentAppropriation/v1"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
