<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ec.europa.eu/budg/abac/recovery_context_detected_by/service/es/sync/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fnd="http://www.ec.europa.eu/budg/abac/recovery_context_detected_by/v1" xmlns:fault="http://www.ec.europa.eu/budg/abac/messagefault/v1" name="RecoveryContextDetectedBy" targetNamespace="http://www.ec.europa.eu/budg/abac/recovery_context_detected_by/service/es/sync/v1">
	<wsdl:import location="FaultMessage.wsdl" namespace="http://www.ec.europa.eu/budg/abac/messagefault/v1"/>
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.ec.europa.eu/budg/abac/recovery_context_detected_by/v1" schemaLocation="xsd/recoverycontext/BUDG_RecoveryContextDetectedBy_Find_1.xsd">
    	</xsd:import>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="RecoveryContextDetectedByFindRequest">
		<wsdl:part name="parameters" element="fnd:RecoveryContextDetectedByFindRequest"/>
	</wsdl:message>
	<wsdl:message name="RecoveryContextDetectedByFindResponse">
		<wsdl:part name="parameters" element="fnd:RecoveryContextDetectedByFindResponse"/>
	</wsdl:message>
	<wsdl:portType name="RecoveryContextDetectedByPort">
		<wsdl:operation name="find">
			<wsdl:input message="tns:RecoveryContextDetectedByFindRequest"/>
			<wsdl:output message="tns:RecoveryContextDetectedByFindResponse"/>
			<wsdl:fault name="Fault" message="fault:FaultMessage"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="RecoveryContextDetectedBySOAP" type="tns:RecoveryContextDetectedByPort">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="find">
			<soap:operation soapAction="http://www.ec.europa.eu/budg/abac/recovery_context_detected_by/service/es/sync/find/v1"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="Fault"><soap:fault name="Fault" use="literal"/></wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="RecoveryContextDetectedBy">
		<wsdl:port name="RecoveryContextDetectedBySOAP" binding="tns:RecoveryContextDetectedBySOAP">
			<!--<soap:address location="http://localhost:7001/abac/service/RecoveryContextDetectedBy/v1"/>-->
			<soap:address location="https://intragate.test.ec.europa.eu/webpaxanwtst_nt_pub/abac/service/RecoveryContextDetectedBy/v1"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
