<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ec.europa.eu/budg/abac/messagefault/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msg="http://www.ec.europa.eu/budg/abac/message/v1" name="MessageFault" targetNamespace="http://www.ec.europa.eu/budg/abac/messagefault/v1">
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.ec.europa.eu/budg/abac/message/v1" schemaLocation="xsd/message/BUDG_Message_1.xsd"></xsd:import>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="FaultMessage">
		<wsdl:part name="parameters" element="msg:MessageFault"/>
	</wsdl:message>
</wsdl:definitions>
