INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","00019","no","Andrijaševci","Andrijaševci","4122","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","00027","no","Antunovac","Antunovac","3704","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","00035","no","Babina Greda","Babina Greda","3585","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","00043","no","Bakar","Bakar","1470","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","00051","no","Bale - Valle","Bale - Valle","1129","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","00060","no","Barban","Barban","2715","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04D","00078","no","Barilović","Barilović","2938","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","00086","no","Baška","Baška","1668","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","00094","no","Baška Voda","Baška Voda","2728","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","00108","no","Bebrina","Bebrina","3244","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","00116","no","Bedekovčina","Bedekovčina","8079","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","00124","no","Bednja","Bednja","3977","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","00132","no","Beli Manastir","Beli Manastir","8034","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","00159","no","Belica","Belica","3189","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","00167","no","Belišće","Belišće","6493","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","00175","no","Benkovac","Benkovac","2863","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","00183","no","Berek","Berek","1448","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","00191","no","Beretinec","Beretinec","2179","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","00205","no","Bibinje","Bibinje","4019","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","00213","no","Bilje","Bilje","5657","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","00221","no","Biograd Na Moru","Biograd Na Moru","5495","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","00230","no","Bizovac","Bizovac","4502","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","00248","no","Bjelovar","Bjelovar","40443","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR037","00256","no","Blato","Blato","3583","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","00264","no","Bogdanovci","Bogdanovci","1957","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","00272","no","Bol","Bol","1645","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","00299","no","Borovo","Borovo","5133","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04D","00302","no","Bosiljevo","Bosiljevo","1289","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","00329","no","Bošnjaci","Bošnjaci","3869","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","00337","no","Brckovljani","Brckovljani","6857","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","00345","no","Brdovec","Brdovec","11143","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR049","00353","no","Brestovac","Brestovac","3752","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","00361","no","Breznica","Breznica","2200","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR032","00370","no","Brinje","Brinje","3261","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","00388","no","Brod Moravice","Brod Moravice","865","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","00396","no","Brodski Stupnik","Brodski Stupnik","3033","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","00400","no","Brtonigla - Verteneglio","Brtonigla - Verteneglio","1607","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","00418","no","Budinščina","Budinščina","2520","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","00434","no","Buzet","Buzet","1666","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","00442","no","Cerna","Cerna","4616","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","00469","no","Cernik","Cernik","3621","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","00477","no","Cerovlje","Cerovlje","1671","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","00485","no","Cestica","Cestica","5811","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04D","00493","no","Cetingrad","Cetingrad","2027","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","00507","no","Cista Provo","Cista Provo","2377","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR034","00515","no","Civljane","Civljane","240","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","00523","no","Cres","Cres","2281","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","00531","no","Crikvenica","Crikvenica","6880","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR048","00540","no","Crnac","Crnac","1467","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","00558","no","Čabar","Čabar","414","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR048","00566","no","Čačinci","Čačinci","2775","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR048","00574","no","Čađavica","Čađavica","1997","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR049","00582","no","Čaglin","Čaglin","2691","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","00604","no","Čakovec","Čakovec","15185","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","00612","no","Čavle","Čavle","7215","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","00639","no","Čazma","Čazma","8095","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","00647","no","Čeminac","Čeminac","2903","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","00655","no","Čepin","Čepin","11571","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","00663","no","Darda","Darda","6934","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","00671","no","Daruvar","Daruvar","11612","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","00680","no","Davor","Davor","3004","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","00698","no","Delnice","Delnice","4351","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","00701","no","Desinić","Desinić","2915","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","00710","no","Dežanovac","Dežanovac","2671","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","00728","no","Dicmo","Dicmo","2820","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","00744","no","Dobrinj","Dobrinj","2023","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","00752","no","Domašinec","Domašinec","2264","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","00779","no","Brela","Brela","1643","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","00787","no","Donja Dubrava","Donja Dubrava","1932","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","00795","no","Donja Stubica","Donja Stubica","2202","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","00809","no","Donja Voća","Donja Voća","2455","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","00817","no","Donji Andrijevci","Donji Andrijevci","3684","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","00825","no","Donji Kraljevec","Donji Kraljevec","4671","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04E","00833","no","Donji Kukuruzari","Donji Kukuruzari","1645","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR032","00841","no","Donji Lapac","Donji Lapac","2200","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","00850","no","Martijanec","Martijanec","3834","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","00868","no","Donji Miholjac","Donji Miholjac","6226","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","00876","no","Muć","Muć","3835","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","00884","no","Proložac","Proložac","3796","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","00892","no","Donji Vidovec","Donji Vidovec","1403","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04D","00906","no","Draganić","Draganić","2628","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","00914","no","Draž","Draž","2763","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","00922","no","Drenovci","Drenovci","5109","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","00949","no","Drenje","Drenje","2698","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR034","00957","no","Drniš","Drniš","3136","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","00965","no","Drnje","Drnje","1865","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","00973","no","Dubrava","Dubrava","5246","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR037","00981","no","Dubrovnik","Dubrovnik","28113","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04D","00990","no","Duga Resa","Duga Resa","5989","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","01007","no","Dugi Rat","Dugi Rat","7091","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","01015","no","Dugo Selo","Dugo Selo","17466","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04E","01023","no","Dvor","Dvor","5803","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","01031","no","Đakovo","Đakovo","19508","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","01040","no","Đelekovec","Đelekovec","1527","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","01058","no","Đulovac","Đulovac","3199","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","01066","no","Đurđenovac","Đurđenovac","6743","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","01074","no","Đurđevac","Đurđevac","6378","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","01082","no","Đurmanec","Đurmanec","4226","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","01104","no","Erdut","Erdut","7372","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","01112","no","Ernestinovo","Ernestinovo","2186","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR034","01139","no","Ervenik","Ervenik","1204","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","01147","no","Farkaševac","Farkaševac","1913","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","01155","no","Ferdinandovac","Ferdinandovac","1732","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","01163","no","Feričanci","Feričanci","2144","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","01171","no","Fužine","Fužine","1595","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","01180","no","Garčin","Garčin","4779","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","01198","no","Garešnica","Garešnica","10466","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04D","01201","no","Generalski Stol","Generalski Stol","2642","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04E","01210","no","Glina","Glina","4667","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","01228","no","Gola","Gola","2416","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","01236","no","Goričan","Goričan","2851","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","01244","no","Gorjani","Gorjani","1587","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","01252","no","Gornja Stubica","Gornja Stubica","5237","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","01279","no","Gornji Bogićevci","Gornji Bogićevci","1931","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","01295","no","Gornji Kneginec","Gornji Kneginec","5359","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR032","01309","no","Gospić","Gospić","6561","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","01317","no","Gračac","Gračac","5033","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","01325","no","Gračišće","Gračišće","1408","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR041","01333","no","Grad Zagreb","Grad Zagreb","792875","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","01341","no","Gradac","Gradac","3308","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","01350","no","Gradec","Gradec","3697","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR048","01368","no","Gradina","Gradina","3825","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","01376","no","Gradište","Gradište","2769","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","01384","no","Grožnjan - Grisignana","Grožnjan - Grisignana","733","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","01392","no","Grubišno Polje","Grubišno Polje","6431","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","01406","no","Gundinci","Gundinci","2018","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","01414","no","Gunja","Gunja","3707","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","01449","no","Hercegovac","Hercegovac","2367","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","01457","no","Hlebine","Hlebine","1302","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","01465","no","Hrašćina","Hrašćina","1603","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","01481","no","Hrvace","Hrvace","3653","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04E","01490","no","Hrvatska Dubica","Hrvatska Dubica","2073","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04E","01503","no","Hrvatska Kostajnica","Hrvatska Kostajnica","2130","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","01511","no","Breznički Hum","Breznički Hum","1337","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","01520","no","Hum Na Sutli","Hum Na Sutli","5034","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","01538","no","Hvar","Hvar","3738","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","01546","no","Ilok","Ilok","5036","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","01554","no","Imotski","Imotski","4836","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","01562","no","Ivanec","Ivanec","5252","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","01589","no","Ivanić-Grad","Ivanić-Grad","14544","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","01597","no","Ivankovo","Ivankovo","7977","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","01619","no","Ivanska","Ivanska","2927","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","01635","no","Jakovlje","Jakovlje","3939","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR049","01643","no","Jakšić","Jakšić","4020","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","01651","no","Jalžabet","Jalžabet","3606","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","01660","no","Jarmina","Jarmina","2435","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","01678","no","Jasenice","Jasenice","1402","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04E","01686","no","Jasenovac","Jasenovac","2002","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","01694","no","Jastrebarsko","Jastrebarsko","15897","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","01708","no","Jelenje","Jelenje","5321","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","01716","no","Jelsa","Jelsa","3560","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04D","01724","no","Josipdol","Josipdol","3702","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","01732","no","Kali","Kali","1656","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","01759","no","Kanfanar","Kanfanar","1538","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","01767","no","Kapela","Kapela","2973","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR049","01775","no","Kaptol","Kaptol","3449","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR032","01783","no","Karlobag","Karlobag","923","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04D","01791","no","Karlovac","Karlovac","46827","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","01805","no","Kastav","Kastav","10445","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","01813","no","Kaštela","Kaštela","38474","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR034","01830","no","Kijevo","Kijevo","405","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR034","01848","no","Kistanje","Kistanje","3537","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","01856","no","Klakar","Klakar","2321","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","01864","no","Klana","Klana","1978","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","01872","no","Klanjec","Klanjec","565","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","01899","no","Klenovnik","Klenovnik","2015","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","01902","no","Klinča Sela","Klinča Sela","5242","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","01929","no","Klis","Klis","4739","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","01937","no","Kloštar Ivanić","Kloštar Ivanić","6081","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","01945","no","Kloštar Podravski","Kloštar Podravski","3303","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","01953","no","Kneževi Vinogradi","Kneževi Vinogradi","4560","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR034","01961","no","Knin","Knin","10493","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","01970","no","Komiža","Komiža","1375","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR037","01988","no","Konavle","Konavle","8571","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","01996","no","Končanica","Končanica","2349","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","02003","no","Konjščina","Konjščina","3987","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","02011","no","Koprivnica","Koprivnica","23896","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","02020","no","Koprivnički Bregi","Koprivnički Bregi","2403","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","02038","no","Koprivnički Ivanec","Koprivnički Ivanec","2110","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR037","02046","no","Korčula","Korčula","2839","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","02054","no","Koška","Koška","3992","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","02062","no","Kotoriba","Kotoriba","3232","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","02089","no","Kraljevec Na Sutli","Kraljevec Na Sutli","1723","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","02097","no","Kraljevica","Kraljevica","2797","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","02119","no","Krapina","Krapina","4482","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","02127","no","Krapinske Toplice","Krapinske Toplice","5358","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","02135","no","Križ","Križ","6962","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","02143","no","Križevci","Križevci","11219","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","02151","no","Krk","Krk","3662","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04D","02160","no","Krnjak","Krnjak","2019","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","02178","no","Kršan","Kršan","2958","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR037","02194","no","Kula Norinska","Kula Norinska","1776","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04E","02208","no","Kutina","Kutina","13773","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR049","02216","no","Kutjevo","Kutjevo","2399","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","02224","no","Labin","Labin","6884","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","02232","no","Lanišće","Lanišće","327","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04D","02259","no","Lasinja","Lasinja","1672","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR037","02267","no","Lastovo","Lastovo","792","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","02275","no","Legrad","Legrad","2185","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04E","02283","no","Lekenik","Lekenik","6043","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","02291","no","Lepoglava","Lepoglava","4164","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","02305","no","Levanjska Varoš","Levanjska Varoš","1196","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR049","02313","no","Lipik","Lipik","2257","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04E","02321","no","Lipovljani","Lipovljani","3466","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","02348","no","Lišane Ostrovičke","Lišane Ostrovičke","714","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","02356","no","Ližnjan - Lisignano","Ližnjan - Lisignano","3916","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","02364","no","Lobor","Lobor","3217","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","02372","no","Lokve","Lokve","1047","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","02399","no","Lovas","Lovas","1217","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR032","02402","no","Lovinac","Lovinac","1017","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","02429","no","Lovran","Lovran","4056","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","02437","no","Lovreć","Lovreć","1712","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","02445","no","Ludbreg","Ludbreg","3594","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR048","02453","no","Lukač","Lukač","3646","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","02461","no","Lupoglav","Lupoglav","935","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","02470","no","Ljubešćica","Ljubešćica","1859","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","02488","no","Mače","Mače","2542","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","02496","no","Makarska","Makarska","13504","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","02500","no","Mala Subotica","Mala Subotica","5463","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","02518","no","Mali Bukovec","Mali Bukovec","2215","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","02526","no","Mali Lošinj","Mali Lošinj","5990","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","02534","no","Malinska-Dubašnica","Malinska-Dubašnica","3142","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","02542","no","Marčana","Marčana","4260","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","02569","no","Marija Bistrica","Marija Bistrica","5954","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","02577","no","Marijanci","Marijanci","2402","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","02585","no","Marina","Marina","4597","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04E","02593","no","Martinska Ves","Martinska Ves","3501","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","02607","no","Maruševec","Maruševec","6379","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","02615","no","Matulji","Matulji","11274","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","02631","no","Medulin","Medulin","6552","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR037","02640","no","Metković","Metković","15056","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","02658","no","Mihovljan","Mihovljan","1949","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR048","02666","no","Mikleuš","Mikleuš","1419","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","02674","no","Milna","Milna","1009","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR037","02682","no","Mljet","Mljet","1081","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","02704","no","Molve","Molve","2194","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","02712","no","Podravska Moslavina","Podravska Moslavina","1186","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","02739","no","Mošćenička Draga","Mošćenička Draga","1536","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","02747","no","Motovun - Montona","Motovun - Montona","1001","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","02755","no","Mrkopalj","Mrkopalj","1208","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","02763","no","Mursko-Središće","Mursko-Središće","3465","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","02780","no","Našice","Našice","7894","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","02798","no","Nedelišće","Nedelišće","12028","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","02801","no","Nerežišća","Nerežišća","864","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04D","02810","no","Netretić","Netretić","2860","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","02828","no","Nin","Nin","1151","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR048","02836","no","Nova Bukovica","Nova Bukovica","1776","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","02844","no","Nova Gradiška","Nova Gradiška","14196","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","02852","no","Nova Kapela","Nova Kapela","4202","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","02879","no","Nova Rača","Nova Rača","3434","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR032","02887","no","Novalja","Novalja","3672","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","02895","no","Novi Marof","Novi Marof","1936","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","02909","no","Novi Vinodolski","Novi Vinodolski","3998","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","02917","no","Novigrad-Cittanova","Novigrad-Cittanova","4345","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","02925","no","Novigrad Podravski","Novigrad Podravski","2862","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04E","02933","no","Novska","Novska","7046","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","02941","no","Nuštar","Nuštar","5772","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","02950","no","Nijemci","Nijemci","4715","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","02976","no","Ogulin","Ogulin","8216","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04D","02984","no","Promina","Promina","1109","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR034","02986","no","Obrovac","Obrovac","985","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","02992","no","Okučani","Okučani","3433","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","03000","no","Omiš","Omiš","6387","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","03018","no","Omišalj","Omišalj","2987","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","03026","no","Opatija","Opatija","6624","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","03034","no","Oprisavci","Oprisavci","2514","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","03042","no","Oprtalj - Portole","Oprtalj - Portole","862","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR037","03069","no","Opuzen","Opuzen","2732","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR048","03077","no","Orahovica","Orahovica","3904","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR037","03085","no","Orebić","Orebić","4101","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","03093","no","Oriovac","Oriovac","5819","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR034","03107","no","Biskupija","Biskupija","1696","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","03115","no","Oroslavje","Oroslavje","3363","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","03123","no","Osijek","Osijek","83496","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR032","03131","no","Otočac","Otočac","4203","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","03140","no","Otok","Otok","5468","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04D","03158","no","Ozalj","Ozalj","1194","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","03166","no","Pag","Pag","2942","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","03174","no","Pakoštane","Pakoštane","4170","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR049","03182","no","Pakrac","Pakrac","4852","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","03204","no","Pašman","Pašman","2095","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","03212","no","Pazin","Pazin","4382","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR032","03239","no","Perušić","Perušić","2631","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","03247","no","Peteranec","Peteranec","2681","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","03255","no","Petlovac","Petlovac","2407","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","03263","no","Petrijanec","Petrijanec","4825","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","03271","no","Petrijevci","Petrijevci","2870","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04E","03280","no","Petrinja","Petrinja","15480","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","03298","no","Petrovsko","Petrovsko","2659","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","03301","no","Pićan","Pićan","1820","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","03310","no","Pisarovina","Pisarovina","3678","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR048","03328","no","Pitomača","Pitomača","10049","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04D","03336","no","Plaški","Plaški","2076","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR049","03344","no","Pleternica","Pleternica","3443","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR037","03352","no","Ploče","Ploče","5871","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","03379","no","Podbablje","Podbablje","4709","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","03387","no","Podcrkavlje","Podcrkavlje","2573","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","03395","no","Podgora","Podgora","2514","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","03409","no","Podgorač","Podgorač","2894","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","03417","no","Podstrana","Podstrana","9103","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","03425","no","Podturen","Podturen","3937","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR037","03433","no","Pojezerje","Pojezerje","993","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","03441","no","Polača","Polača","1464","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","03450","no","Poličnik","Poličnik","4448","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","03468","no","Popovac","Popovac","2094","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04E","03476","no","Popovača","Popovača","11952","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","03484","no","Poreč - Parenzo","Poreč - Parenzo","9684","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","03492","no","Posedarje","Posedarje","3613","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","03506","no","Postira","Postira","1554","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR049","03514","no","Požega","Požega","19565","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","03522","no","Pregrada","Pregrada","1839","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","03549","no","Preko","Preko","3853","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","03557","no","Prelog","Prelog","4333","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","03565","no","Preseka","Preseka","1438","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR034","03573","no","Primošten","Primošten","2817","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","03581","no","Pučišća","Pučišća","2189","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","03590","no","Pula - Pola","Pula - Pola","57191","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","03603","no","Punat","Punat","1953","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","03611","no","Punitovci","Punitovci","1800","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","03620","no","Pušća","Pušća","2690","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","03638","no","Rab","Rab","417","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","03646","no","Radoboj","Radoboj","3400","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04D","03654","no","Rakovica","Rakovica","2401","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","03662","no","Rasinja","Rasinja","3271","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","03689","no","Raša","Raša","3197","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","03697","no","Ravna Gora","Ravna Gora","2439","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","03719","no","Ražanac","Ražanac","2900","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","03727","no","Rešetari","Rešetari","4752","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","03735","no","Rijeka","Rijeka","127498","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","03743","no","Rovinj","Rovinj","12913","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","03751","no","Rovišće","Rovišće","4875","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","03760","no","Rugvica","Rugvica","7846","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR034","03778","no","Ružić","Ružić","1589","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04D","03786","no","Saborsko","Saborsko","645","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","03794","no","Sali","Sali","1688","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","03808","no","Samobor","Samobor","37607","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","03816","no","Satnica Đakovačka","Satnica Đakovačka","2179","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","03824","no","Seget","Seget","4863","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","03832","no","Selca","Selca","1804","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","03859","no","Selnica","Selnica","2992","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","03867","no","Semeljci","Semeljci","4405","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR032","03875","no","Senj","Senj","4822","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","03883","no","Sibinj","Sibinj","6860","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","03905","no","Sirač","Sirač","2178","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","03913","no","Sisak","Sisak","33049","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04E","03930","no","Skrad","Skrad","1054","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","03956","no","Slatina","Slatina","10152","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR034","03964","no","Slavonski Brod","Slavonski Brod","59507","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR048","03972","no","Slavonski Šamac","Slavonski Šamac","2142","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","03981","no","Sinj","Sinj","11448","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","03984","no","Skradin","Skradin","592","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR037","03999","no","Slivno","Slivno","1997","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04D","04006","no","Slunj","Slunj","1653","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR037","04022","no","Smokvica","Smokvica","918","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","04057","no","Sokolovac","Sokolovac","3452","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","04065","no","Solin","Solin","20080","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR048","04073","no","Sopje","Sopje","2313","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","04090","no","Split","Split","165893","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","04103","no","Sračinec","Sračinec","4835","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","04111","no","Stankovci","Stankovci","1981","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","04120","no","Stara Gradiška","Stara Gradiška","1346","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","04138","no","Stari Grad","Stari Grad","1792","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","04146","no","Stari Jankovci","Stari Jankovci","4404","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","04154","no","Stari Mikanovci","Stari Mikanovci","2945","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","04162","no","Starigrad","Starigrad","1875","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","04189","no","Staro Petrovo Selo","Staro Petrovo Selo","5143","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR037","04197","no","Ston","Ston","2410","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","04219","no","Strizivojna","Strizivojna","2515","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","04227","no","Stubičke Toplice","Stubičke Toplice","2814","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","04235","no","Sućuraj","Sućuraj","463","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR048","04243","no","Suhopolje","Suhopolje","6646","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","04251","no","Sukošan","Sukošan","4586","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04E","04260","no","Sunja","Sunja","5745","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","04278","no","Supetar","Supetar","3223","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","04286","no","Sveti Filip I Jakov","Sveti Filip I Jakov","4426","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","04294","no","Sveti Ivan Zelina","Sveti Ivan Zelina","15990","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","04308","no","Sveti Križ Začretje","Sveti Križ Začretje","6150","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","04316","no","Sveti Lovreč","Sveti Lovreč","1017","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","04324","no","Sveta Nedelja","Sveta Nedelja","2980","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","04332","no","Sveti Petar U Šumi","Sveti Petar U Šumi","1067","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","04359","no","Svetvinčenat","Svetvinčenat","2183","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","04367","no","Sveta Nedelja","Sveta Nedelja","18032","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","04375","no","Sveti Đurđ","Sveti Đurđ","3803","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","04383","no","Sveti Ilija","Sveti Ilija","3495","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","04391","no","Sveti Ivan Žabno","Sveti Ivan Žabno","5204","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","04405","no","Sveti Juraj Na Bregu","Sveti Juraj Na Bregu","5112","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","04413","no","Sveti Martin Na Muri","Sveti Martin Na Muri","2629","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","04421","no","Sveti Petar Orehovec","Sveti Petar Orehovec","4583","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","04430","no","Šestanovac","Šestanovac","1917","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR034","04448","no","Šibenik","Šibenik","34242","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","04456","no","Škabrnja","Škabrnja","1788","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","04472","no","Šolta","Šolta","1675","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR048","04499","no","Špišić Bukovica","Špišić Bukovica","4222","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","04502","no","Štefanje","Štefanje","2020","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","04529","no","Štrigova","Štrigova","2769","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","04537","no","Tinjan","Tinjan","1672","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR034","04545","no","Tisno","Tisno","3041","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR032","04553","no","Plitvička Jezera","Plitvička Jezera","4358","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","04561","no","Tompojevci","Tompojevci","1561","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04E","04570","no","Topusko","Topusko","2934","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","04588","no","Tordinci","Tordinci","2047","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","04596","no","Tovarnik","Tovarnik","2792","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","04600","no","Trilj","Trilj","2110","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","04618","no","Trnava","Trnava","1600","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","04626","no","Trnovec Bartolovečki","Trnovec Bartolovečki","6889","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","04634","no","Trogir","Trogir","10818","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","04642","no","Trpinja","Trpinja","5680","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","04669","no","Tuhelj","Tuhelj","2099","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR032","04677","no","Udbina","Udbina","1909","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","04685","no","Umag","Umag","7093","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR034","04693","no","Unešić","Unešić","1685","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","04715","no","Valpovo","Valpovo","7396","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","04723","no","Varaždin","Varaždin","38746","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","04731","no","Varaždinske Toplice","Varaždinske Toplice","1763","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR037","04740","no","Vela Luka","Vela Luka","4130","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR049","04758","no","Velika","Velika","5605","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","04766","no","Velika Kopanica","Velika Kopanica","3286","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04E","04774","no","Velika Ludina","Velika Ludina","2636","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","04782","no","Velika Pisanica","Velika Pisanica","1774","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","04804","no","Veliki Grđevac","Veliki Grđevac","2827","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","04812","no","Veliko Trgovišće","Veliko Trgovišće","4867","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","04839","no","Veliko Trojstvo","Veliko Trojstvo","2731","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","04847","no","Vidovec","Vidovec","5423","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","04855","no","Viljevo","Viljevo","2072","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","04863","no","Vinica","Vinica","3396","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","04871","no","Vinkovci","Vinkovci","31961","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","04880","no","Vinodolska Općina","Vinodolska Općina","3548","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","04898","no","Vir","Vir","3032","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","04901","no","Virje","Virje","4586","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR048","04910","no","Virovitica","Virovitica","14663","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","04928","no","Vis","Vis","1660","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","04936","no","Visoko","Visoko","1511","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","04944","no","Viškovci","Viškovci","1902","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","04952","no","Viškovo","Viškovo","14495","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","04979","no","Višnjan - Visignano","Višnjan - Visignano","2266","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","04987","no","Vižinada - Visinada","Vižinada - Visinada","1155","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR048","04995","no","Voćin","Voćin","2341","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR034","05002","no","Vodice","Vodice","6696","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","05029","no","Vodnjan - Dignano","Vodnjan - Dignano","3645","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04D","05037","no","Vojnić","Vojnić","4503","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","05045","no","Vratišinec","Vratišinec","1996","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","05053","no","Vrbanja","Vrbanja","3938","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","05061","no","Vrbje","Vrbje","2209","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","05070","no","Vrbnik","Vrbnik","1270","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","05088","no","Vrbovec","Vrbovec","14802","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","05096","no","Vrbovsko","Vrbovsko","1647","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04E","05100","no","Gvozd","Gvozd","3008","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","05118","no","Vrgorac","Vrgorac","2048","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR032","05126","no","Vrhovine","Vrhovine","1403","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","05134","no","Vrlika","Vrlika","819","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","05142","no","Vrpolje","Vrpolje","3511","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","05169","no","Vrsar - Orsera","Vrsar - Orsera","2152","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","05177","no","Vuka","Vuka","1184","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","05185","no","Vukovar","Vukovar","26716","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","05193","no","Zabok","Zabok","2701","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","05207","no","Zadar","Zadar","70674","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","05215","no","Zagorska Sela","Zagorska Sela","999","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","05223","no","Zagvozd","Zagvozd","1184","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR037","05231","no","Zažablje","Zažablje","738","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR048","05240","no","Zdenci","Zdenci","1885","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","05258","no","Zemunik Donji","Zemunik Donji","2051","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","05266","no","Zlatar","Zlatar","6096","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","05274","no","Zlatar Bistrica","Zlatar Bistrica","2581","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","05282","no","Zmijavci","Zmijavci","2080","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04D","05304","no","Žakanje","Žakanje","1911","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","05312","no","Žminj","Žminj","3470","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","05339","no","Krašić","Krašić","2665","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","05347","no","Županja","Županja","12115","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","05355","no","Otok","Otok","4720","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","05363","no","Rakovec","Rakovec","1256","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","05371","no","Novigrad","Novigrad","2373","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","05380","no","Kostrena","Kostrena","4179","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","05398","no","Marija Gorica","Marija Gorica","2251","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","05401","no","Žumberak","Žumberak","872","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","05410","no","Velika Gorica","Velika Gorica","63511","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","05428","no","Orle","Orle","1967","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","05435","no","Zaprešić","Zaprešić","25226","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","05444","no","Pokupsko","Pokupsko","2223","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","05452","no","Kravarsko","Kravarsko","1982","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","05479","no","Bistra","Bistra","6621","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","05487","no","Luka","Luka","1351","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","05495","no","Dubravica","Dubravica","1442","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","05509","no","Bedenica","Bedenica","1426","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR042","05517","no","Stupnik","Stupnik","3714","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","05525","no","Jesenje","Jesenje","1551","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","05533","no","Kumrovec","Kumrovec","1593","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR043","05541","no","Novi Golubovec","Novi Golubovec","1004","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04E","05550","no","Majur","Majur","1192","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04D","05568","no","Ribnik","Ribnik","477","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04D","05576","no","Tounj","Tounj","1145","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR044","05584","no","Veliki Bukovec","Veliki Bukovec","1457","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","05592","no","Kalinovac","Kalinovac","1601","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","05606","no","Kalnik","Kalnik","1361","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","05614","no","Novo Virje","Novo Virje","1218","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","05622","no","Severin","Severin","879","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","05649","no","Šandrovac","Šandrovac","1775","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","05657","no","Velika Trnovitica","Velika Trnovitica","1373","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR047","05665","no","Zrinski Topolovac","Zrinski Topolovac","896","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","05673","no","Bukovlje","Bukovlje","3098","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","05681","no","Dragalić","Dragalić","1345","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","05690","no","Gornja Vrba","Gornja Vrba","2518","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04A","05703","no","Sikirevci","Sikirevci","2470","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","05711","no","Galovac","Galovac","1238","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","05720","no","Kukljica","Kukljica","726","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","05738","no","Povljana","Povljana","785","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","05746","no","Privlaka","Privlaka","2228","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","05754","no","Tkon","Tkon","753","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","05762","no","Donja Motičina","Donja Motičina","1647","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","05789","no","Magadenovac","Magadenovac","1928","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","05797","no","Vladislavci","Vladislavci","1888","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR034","05819","no","Pirovac","Pirovac","1878","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR034","05827","no","Rogoznica","Rogoznica","2300","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","05835","no","Privlaka","Privlaka","2962","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","05843","no","Vođinci","Vođinci","1957","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","05851","no","Dugopolje","Dugopolje","3465","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","05860","no","Lećevica","Lećevica","588","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","05878","no","Lokvičići","Lokvičići","866","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","05886","no","Okrug","Okrug","3458","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","05894","no","Prgomet","Prgomet","689","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","05908","no","Primorski Dolac","Primorski Dolac","773","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","05916","no","Runovići","Runovići","2442","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","05924","no","Sutivan","Sutivan","826","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","05932","no","Tučepi","Tučepi","1918","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR035","05959","no","Zadvarje","Zadvarje","289","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","05967","no","Karojba","Karojba","1442","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","05975","no","Kaštelir-Labinci - Castelliere-S. Domenica","Kaštelir-Labinci - Castelliere-S. Domenica","1459","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR037","05983","no","Dubrovačko Primorje","Dubrovačko Primorje","2161","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR037","05991","no","Janjina","Janjina","551","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR037","06009","no","Lumbarda","Lumbarda","1224","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR037","06017","no","Trpanj","Trpanj","727","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR037","06025","no","Župa Dubrovačka","Župa Dubrovačka","8460","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","06033","no","Dekanovec","Dekanovec","854","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","06041","no","Gornji Mihaljevec","Gornji Mihaljevec","1917","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","06050","no","Orehovica","Orehovica","2723","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","06068","no","Strahoninec","Strahoninec","2696","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","06076","no","Sveta Marija","Sveta Marija","2337","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","06084","no","Šenkovec","Šenkovec","2898","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","06092","no","Jagodnjak","Jagodnjak","2040","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","06106","no","Markušica","Markušica","2576","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","06122","no","Negoslavci","Negoslavci","1472","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04B","06149","no","Šodolovci","Šodolovci","1678","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","06165","no","Podravske Sesvete","Podravske Sesvete","1628","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR034","06173","no","Murter - Kornati","Murter - Kornati","2047","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR045","06181","no","Gornja Rijeka","Gornja Rijeka","1781","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","06190","no","Fažana - Fasana","Fažana - Fasana","3569","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR046","06203","no","Pribislavec","Pribislavec","3130","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR034","06211","no","Bilice","Bilice","2312","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","06220","no","Kolan","Kolan","821","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04D","06238","no","Kamanje","Kamanje","903","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR031","06246","no","Lopar","Lopar","1247","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR033","06254","no","Vrsi","Vrsi","2020","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR034","06262","no","Tribunj","Tribunj","1526","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR04C","06289","no","Štitar","Štitar","2108","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","06297","no","Funtana - Fontane","Funtana - Fontane","924","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","06319","no","Tar-Vabriga - Torre-Abrega","Tar-Vabriga - Torre-Abrega","1996","0"); 
INSERT INTO `wifi4eu`.`laus` (`country_code`, `nuts3`, `lau2`, `_change`, `name1`, `name2`, `pop`, `area`) VALUES ("HR","HR036","006912","no","Buje ","Buje ","2624","0");
