package eu.europa.ec.budg.abac.budgetary_commitment_level2.service.es.sync.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-07-28T12:43:19.701+02:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "BudgetaryCommitmentLevel2", 
                  //wsdlLocation = "file:/C:/Users/lviverof/Desktop/backup/WSDL_XSD_73_Rev_32423/BUDG_BudgetaryCommitmentLevel2_ES_Sync_1.wsdl",
                  //wsdlLocation = "http://wlts0275.cc.cec.eu.int:1043/wifi4eu-financial/wsdl/BUDG_BudgetaryCommitmentLevel2_ES_Sync_1.wsdl",
                  wsdlLocation = "http://localhost:7001/wifi4eu-financial/wsdl/BUDG_BudgetaryCommitmentLevel2_ES_Sync_1.wsdl",
                  targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/sync/v1") 
public class BudgetaryCommitmentLevel2 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/sync/v1", "BudgetaryCommitmentLevel2");
    public final static QName BudgetaryCommitmentLevel2SOAP = new QName("http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/sync/v1", "BudgetaryCommitmentLevel2SOAP");
    static {
        URL url = null;
        try {
            //url = new URL("file:/C:/Users/lviverof/Desktop/backup/WSDL_XSD_73_Rev_32423/BUDG_BudgetaryCommitmentLevel2_ES_Sync_1.wsdl");
            //url = new URL("http://wlts0275.cc.cec.eu.int:1043/wifi4eu-financial/wsdl/BUDG_BudgetaryCommitmentLevel2_ES_Sync_1.wsdl");
            url = new URL("http://localhost:7001/wifi4eu-financial/wsdl/BUDG_BudgetaryCommitmentLevel2_ES_Sync_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BudgetaryCommitmentLevel2.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "BUDG_BudgetaryCommitmentLevel2_ES_Sync_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BudgetaryCommitmentLevel2(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BudgetaryCommitmentLevel2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BudgetaryCommitmentLevel2() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BudgetaryCommitmentLevel2(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BudgetaryCommitmentLevel2(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BudgetaryCommitmentLevel2(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns BudgetaryCommitmentLevel2Port
     */
    @WebEndpoint(name = "BudgetaryCommitmentLevel2SOAP")
    public BudgetaryCommitmentLevel2Port getBudgetaryCommitmentLevel2SOAP() {
        return super.getPort(BudgetaryCommitmentLevel2SOAP, BudgetaryCommitmentLevel2Port.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BudgetaryCommitmentLevel2Port
     */
    @WebEndpoint(name = "BudgetaryCommitmentLevel2SOAP")
    public BudgetaryCommitmentLevel2Port getBudgetaryCommitmentLevel2SOAP(WebServiceFeature... features) {
        return super.getPort(BudgetaryCommitmentLevel2SOAP, BudgetaryCommitmentLevel2Port.class, features);
    }

}
