package eu.europa.ec.budg.abac.legal_commitment.service.es.async.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-15T07:29:25.945+02:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/async/v1", name = "LegalCommitmentPort")
@XmlSeeAlso({eu.europa.ec.budg.abac.organisational_group.v1.ObjectFactory.class, eu.europa.ec.budg.abac.payment_deduction_mode.v1.ObjectFactory.class, eu.europa.ec.budg.abac.supporting_document.v1.ObjectFactory.class, eu.europa.ec.budg.abac.workflow.v1.ObjectFactory.class, eu.europa.ec.budg.abac.ares_document.v1.ObjectFactory.class, eu.europa.ec.budg.abac.br.v1.ObjectFactory.class, eu.europa.ec.budg.abac.central_reference.v1.ObjectFactory.class, eu.europa.ec.budg.abac.complex_type.v1.ObjectFactory.class, eu.europa.ec.budg.abac.abac_object.v1.ObjectFactory.class, eu.europa.ec.budg.abac.organisation.v1.ObjectFactory.class, eu.europa.ec.budg.abac.message.v1.ObjectFactory.class, eu.europa.ec.budg.abac.responsible_user.v1.ObjectFactory.class, eu.europa.ec.budg.abac.external_criteria.v1.ObjectFactory.class, eu.europa.ec.budg.abac.scanned_document.v1.ObjectFactory.class, eu.europa.ec.budg.abac.external_criteria_type.v1.ObjectFactory.class, eu.europa.ec.budg.abac.legal_commitment.v1.ObjectFactory.class, eu.europa.ec.budg.abac.workflow_object.v1.ObjectFactory.class, eu.europa.ec.budg.abac.currency.v1.ObjectFactory.class, eu.europa.ec.budg.abac.external_criteria_code.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LegalCommitmentPort {

    @WebMethod(operationName = "modify_responsible_users", action = "http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/async/modify_responsible_user/v1")
    @WebResult(name = "LegalCommitmentModifyResponsibleUsersResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1", partName = "parameters")
    public eu.europa.ec.budg.abac.message.v1.BusinessRuleMessageResponseType modifyResponsibleUsers(
        @WebParam(partName = "parameters", name = "LegalCommitmentModifyResponsibleUsersRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1")
        eu.europa.ec.budg.abac.legal_commitment.v1.LegalCommitmentModifyResponsibleUsersRequestType parameters
    ) throws eu.europa.ec.budg.abac.messagefault.v1.FaultMessage;

    @WebMethod(operationName = "modify_base", action = "http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/async/cancel_current_amendment/v1")
    @WebResult(name = "LegalCommitmentModifyBaseResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1", partName = "parameters")
    public eu.europa.ec.budg.abac.message.v1.BusinessRuleMessageResponseType modifyBase(
        @WebParam(partName = "parameters", name = "LegalCommitmentModifyBaseRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1")
        eu.europa.ec.budg.abac.legal_commitment.v1.LegalCommitmentModifyBaseRequestType parameters
    ) throws eu.europa.ec.budg.abac.messagefault.v1.FaultMessage;

    @WebMethod(operationName = "add_supporting_document_folder", action = "http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/async/add_supporting_document_folder/v1")
    @WebResult(name = "LegalCommitmentAddSupportingDocumentFolderResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1", partName = "parameters")
    public eu.europa.ec.budg.abac.message.v1.BusinessRuleMessageResponseType addSupportingDocumentFolder(
        @WebParam(partName = "parameters", name = "LegalCommitmentAddSupportingDocumentFolderRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1")
        eu.europa.ec.budg.abac.legal_commitment.v1.LegalCommitmentAddSupportingDocumentFolderRequestType parameters
    ) throws eu.europa.ec.budg.abac.messagefault.v1.FaultMessage;

    @WebMethod(operationName = "create_base", action = "http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/async/create_base/v1")
    @WebResult(name = "LegalCommitmentCreateBaseResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1", partName = "parameters")
    public eu.europa.ec.budg.abac.message.v1.BusinessRuleMessageResponseType createBase(
        @WebParam(partName = "parameters", name = "LegalCommitmentCreateBaseRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1")
        eu.europa.ec.budg.abac.legal_commitment.v1.LegalCommitmentCreateBaseRequestType parameters
    ) throws eu.europa.ec.budg.abac.messagefault.v1.FaultMessage;

    @WebMethod(operationName = "modify_responsible_organisation", action = "http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/async/modify_responsible_organisation/v1")
    @WebResult(name = "LegalCommitmentModifyResponsibleOrganisationResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1", partName = "parameters")
    public eu.europa.ec.budg.abac.message.v1.BusinessRuleMessageResponseType modifyResponsibleOrganisation(
        @WebParam(partName = "parameters", name = "LegalCommitmentModifyResponsibleOrganisationRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1")
        eu.europa.ec.budg.abac.legal_commitment.v1.LegalCommitmentModifyResponsibleOrganisationRequestType parameters
    ) throws eu.europa.ec.budg.abac.messagefault.v1.FaultMessage;

    @WebMethod(operationName = "delete_commitment_link", action = "http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/async/delete_commitment_link/v1")
    @WebResult(name = "LegalCommitmentDeleteCommitmentLinkResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1", partName = "parameters")
    public eu.europa.ec.budg.abac.message.v1.BusinessRuleMessageResponseType deleteCommitmentLink(
        @WebParam(partName = "parameters", name = "LegalCommitmentDeleteCommitmentLinkRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1")
        eu.europa.ec.budg.abac.legal_commitment.v1.LegalCommitmentDeleteCommitmentLinkRequestType parameters
    ) throws eu.europa.ec.budg.abac.messagefault.v1.FaultMessage;

    @WebMethod(operationName = "create_responsible_user", action = "http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/async/create_responsible_user/v1")
    @WebResult(name = "LegalCommitmentCreateResponsibleUserResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1", partName = "parameters")
    public eu.europa.ec.budg.abac.message.v1.BusinessRuleMessageResponseType createResponsibleUser(
        @WebParam(partName = "parameters", name = "LegalCommitmentCreateResponsibleUserRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1")
        eu.europa.ec.budg.abac.legal_commitment.v1.LegalCommitmentCreateResponsibleUserRequestType parameters
    ) throws eu.europa.ec.budg.abac.messagefault.v1.FaultMessage;

    @WebMethod(operationName = "add_scanned_document", action = "http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/async/add_scanned_document/v1")
    @WebResult(name = "LegalCommitmentAddScannedDocumentResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1", partName = "parameters")
    public eu.europa.ec.budg.abac.message.v1.BusinessRuleMessageResponseType addScannedDocument(
        @WebParam(partName = "parameters", name = "LegalCommitmentAddScannedDocumentRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1")
        eu.europa.ec.budg.abac.legal_commitment.v1.LegalCommitmentAddScannedDocumentRequestType parameters
    ) throws eu.europa.ec.budg.abac.messagefault.v1.FaultMessage;

    @WebMethod(operationName = "create_commitment_link", action = "http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/async/create_commitment_link/v1")
    @WebResult(name = "LegalCommitmentCreateCommitmentLinkResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1", partName = "parameters")
    public eu.europa.ec.budg.abac.message.v1.BusinessRuleMessageResponseType createCommitmentLink(
        @WebParam(partName = "parameters", name = "LegalCommitmentCreateCommitmentLinkRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1")
        eu.europa.ec.budg.abac.legal_commitment.v1.LegalCommitmentCreateCommitmentLinkRequestType parameters
    ) throws eu.europa.ec.budg.abac.messagefault.v1.FaultMessage;

    @WebMethod(operationName = "add_ares_document", action = "http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/async/add_ares_document/v1")
    @WebResult(name = "LegalCommitmentAddAresDocumentResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1", partName = "parameters")
    public eu.europa.ec.budg.abac.message.v1.BusinessRuleMessageResponseType addAresDocument(
        @WebParam(partName = "parameters", name = "LegalCommitmentAddAresDocumentRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1")
        eu.europa.ec.budg.abac.legal_commitment.v1.LegalCommitmentAddAresDocumentRequestType parameters
    ) throws eu.europa.ec.budg.abac.messagefault.v1.FaultMessage;

    @WebMethod(operationName = "cancel_current_amendment", action = "http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/async/cancel_current_amendment/v1")
    @WebResult(name = "LegalCommitmentCancelCurrentAmendmentResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1", partName = "parameters")
    public eu.europa.ec.budg.abac.message.v1.BusinessRuleMessageResponseType cancelCurrentAmendment(
        @WebParam(partName = "parameters", name = "LegalCommitmentCancelCurrentAmendmentRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1")
        eu.europa.ec.budg.abac.legal_commitment.v1.LegalCommitmentCancelCurrentAmendmentRequestType parameters
    ) throws eu.europa.ec.budg.abac.messagefault.v1.FaultMessage;

    @WebMethod(operationName = "add_supporting_document", action = "http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/async/add_supporting_document/v1")
    @WebResult(name = "LegalCommitmentAddSupportingDocumentResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1", partName = "parameters")
    public eu.europa.ec.budg.abac.message.v1.BusinessRuleMessageResponseType addSupportingDocument(
        @WebParam(partName = "parameters", name = "LegalCommitmentAddSupportingDocumentRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1")
        eu.europa.ec.budg.abac.legal_commitment.v1.LegalCommitmentAddSupportingDocumentRequestType parameters
    ) throws eu.europa.ec.budg.abac.messagefault.v1.FaultMessage;

    @WebMethod(operationName = "create_payment_time_limit", action = "http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/async/create_payment_time_limit/v1")
    @WebResult(name = "LegalCommitmentCreatePaymentTimeLimitResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1", partName = "parameters")
    public eu.europa.ec.budg.abac.message.v1.BusinessRuleMessageResponseType createPaymentTimeLimit(
        @WebParam(partName = "parameters", name = "LegalCommitmentCreatePaymentTimeLimitRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1")
        eu.europa.ec.budg.abac.legal_commitment.v1.LegalCommitmentCreatePaymentTimeLimitRequestType parameters
    ) throws eu.europa.ec.budg.abac.messagefault.v1.FaultMessage;

    @WebMethod(operationName = "give_visa", action = "http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/async/give_visa/v1")
    @WebResult(name = "LegalCommitmentGiveVisaResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1", partName = "parameters")
    public eu.europa.ec.budg.abac.message.v1.BusinessRuleMessageResponseType giveVisa(
        @WebParam(partName = "parameters", name = "LegalCommitmentGiveVisaRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1")
        eu.europa.ec.budg.abac.legal_commitment.v1.LegalCommitmentGiveVisaRequestType parameters
    ) throws eu.europa.ec.budg.abac.messagefault.v1.FaultMessage;

    @WebMethod(action = "http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/async/amend/v1")
    @WebResult(name = "LegalCommitmentAmendResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1", partName = "parameters")
    public eu.europa.ec.budg.abac.message.v1.BusinessRuleMessageResponseType amend(
        @WebParam(partName = "parameters", name = "LegalCommitmentAmendRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1")
        eu.europa.ec.budg.abac.legal_commitment.v1.LegalCommitmentAmendRequestType parameters
    ) throws eu.europa.ec.budg.abac.messagefault.v1.FaultMessage;

    @WebMethod(action = "http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/async/correct/v1")
    @WebResult(name = "LegalCommitmentCorrectResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1", partName = "parameters")
    public eu.europa.ec.budg.abac.message.v1.BusinessRuleMessageResponseType correct(
        @WebParam(partName = "parameters", name = "LegalCommitmentCorrectRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1")
        eu.europa.ec.budg.abac.legal_commitment.v1.LegalCommitmentCorrectRequestType parameters
    ) throws eu.europa.ec.budg.abac.messagefault.v1.FaultMessage;

    @WebMethod(operationName = "create_contract_reference", action = "http://www.ec.europa.eu/budg/abac/legal_commitment/service/es/async/create_contract_reference/v1")
    @WebResult(name = "LegalCommitmentCreateContractReferenceResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1", partName = "parameters")
    public eu.europa.ec.budg.abac.message.v1.BusinessRuleMessageResponseType createContractReference(
        @WebParam(partName = "parameters", name = "LegalCommitmentCreateContractReferenceRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_commitment/v1")
        eu.europa.ec.budg.abac.legal_commitment.v1.LegalCommitmentCreateContractReferenceRequestType parameters
    ) throws eu.europa.ec.budg.abac.messagefault.v1.FaultMessage;
}
