INSERT INTO organizations (id, name, country) VALUES ('0',N'Национално сдружение на общините в Република България- National Association of the Municipalities in Republic of Bulgaria',N'BG');
INSERT INTO organizations (id, name, country) VALUES ('1',N'Регионална асоциация на общини “Тракия” - The regional association of municipalities "Trakia"',N'BG');
INSERT INTO organizations (id, name, country) VALUES ('2',N'Регионално сдружение на общини “Марица” - Regional Municipalities Association "Maritza"',N'BG');
INSERT INTO organizations (id, name, country) VALUES ('3',N'Сдружение на югозападните общини - Association of South-Western Municipalities (ASWM)',N'BG');
INSERT INTO organizations (id, name, country) VALUES ('4',N'Регионално сдружение на общини “Янтра” - Regional Municipalities Association “Yantra”',N'BG');
INSERT INTO organizations (id, name, country) VALUES ('5',N'Регионално сдружение на общини “Хебър” - Association of Municipalities of the South Central Region "Heber"',N'BG');
INSERT INTO organizations (id, name, country) VALUES ('6',N'Асоциация на родопските общини - Association of Rhodope Municipalities',N'BG');
INSERT INTO organizations (id, name, country) VALUES ('7',N'Асоциация на българските черноморски общини - Union of the Bulgarian Black Sea Local Authorities',N'BG');
INSERT INTO organizations (id, name, country) VALUES ('8',N'Асоциация на дунавските общини “Дунав” - Association of Danube River Municipalities "Danube"',N'BG');
INSERT INTO organizations (id, name, country) VALUES ('9',N'Регионално сдружение на общини “Централна Стара планина” - Regional Association of Municipalities "Central Stara Planina"',N'BG');
INSERT INTO organizations (id, name, country) VALUES ('10',N'Union of Cyprus Municipalities - Ένωση Δήμων Κύπρου',N'CY');
INSERT INTO organizations (id, name, country) VALUES ('11',N'Union of Cyprus Communities - Ένωση Κοινοτήτων Κύπρου',N'CY');
INSERT INTO organizations (id, name, country) VALUES ('12',N'Paphos District Development Agency (ANETPA) - Αναπτυξιακή Εταιρεία Πάφου Αφροδίτη (ΑΝ.ΕΤ.Π.Α)',N'CY');
INSERT INTO organizations (id, name, country) VALUES ('13',N'Larnaca District Development Agency (ANETEL) - Αναπτυξιακή Εταιρεία Επαρχιών Λάρνακας και Αμμοχώστου (ΑΝΕΤΕΛ)',N'CY');
INSERT INTO organizations (id, name, country) VALUES ('14',N'Limassol District Development Agency (ANELEM) - Αναπτυξιακή Εταιρεία Λεμεσού (ΑΝΕΛΕΜ)',N'CY');
INSERT INTO organizations (id, name, country) VALUES ('15',N'Nicosia Development Agency (ANEL) - Αναπτυξιακή Εταιρεία Λευκωσίας (ΑΝΕΛ)',N'CY');
INSERT INTO organizations (id, name, country) VALUES ('16',N'Troodos Development Company - Αναπτυξιακή Εταιρεία Τροόδους (ΑΝΕΤ)',N'CY');
INSERT INTO organizations (id, name, country) VALUES ('17',N'Gemeindeverbände',N'DE');
INSERT INTO organizations (id, name, country) VALUES ('18',N'Landkreise and Kreise',N'DE');
INSERT INTO organizations (id, name, country) VALUES ('19',N'Comarcas de la Comunidad Autónoma de Cataluña',N'ES');
INSERT INTO organizations (id, name, country) VALUES ('20',N'Comarcas de la Comunidad Autónoma de Aragón',N'ES');
INSERT INTO organizations (id, name, country) VALUES ('21',N'Comarca del Bierzo en la Comunidad Autónoma de Castilla y León',N'ES');
INSERT INTO organizations (id, name, country) VALUES ('22',N'Cuadrillas en el País Vasco',N'ES');
INSERT INTO organizations (id, name, country) VALUES ('23',N'Mancomunidades de municipios',N'ES');
INSERT INTO organizations (id, name, country) VALUES ('24',N'Diputaciones Provinciales',N'ES');
INSERT INTO organizations (id, name, country) VALUES ('25',N'Carlow',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('26',N'Dublin City',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('27',N'South Dublin',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('28',N'Fingal',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('29',N'Dún Laoighaire - Rathdown',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('30',N'Kildare',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('31',N'Kilkenny',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('32',N'Laois',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('33',N'Longford',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('34',N'Louth',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('35',N'Meath',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('36',N'Offaly',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('37',N'Westmeath',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('38',N'Wexford',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('39',N'Wicklow',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('40',N'Clare',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('41',N'Cork City',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('42',N'Cork County',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('43',N'Kerry',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('44',N'Limerick City and County',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('45',N'Tipperary',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('46',N'Waterford City and County',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('47',N'Galway City',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('48',N'Galway County',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('49',N'Leitrim',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('50',N'Mayo',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('51',N'Roscommon',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('52',N'Sligo',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('53',N'Cavan',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('54',N'Donegal',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('55',N'Monaghan',N'IE');
INSERT INTO organizations (id, name, country) VALUES ('56',N'Unione di Comuni',N'IT');
INSERT INTO organizations (id, name, country) VALUES ('57',N'Comunità Montana',N'IT');
INSERT INTO organizations (id, name, country) VALUES ('58',N'Lietuvos kurortų asociacija',N'LT');
INSERT INTO organizations (id, name, country) VALUES ('59',N'Lietuvos savivaldybių asociacija',N'LT');
INSERT INTO organizations (id, name, country) VALUES ('60',N'Syndicat des Villes et Communes Luxembourgeoises',N'LU');
INSERT INTO organizations (id, name, country) VALUES ('61',N'Latvijas Pašvaldību savienība',N'LV');
INSERT INTO organizations (id, name, country) VALUES ('62',N'Latvijas Lielo pilsētu asociācija',N'LV');
INSERT INTO organizations (id, name, country) VALUES ('63',N'Local Councils Association',N'MT');
INSERT INTO organizations (id, name, country) VALUES ('64',N'National Association for Local Council and Regional Executive Secretaries',N'MT');
INSERT INTO organizations (id, name, country) VALUES ('65',N'Regional Committees',N'MT');
INSERT INTO organizations (id, name, country) VALUES ('66',N'Vereniging van Nederlandse Gemeenten (VNG)',N'NL');
INSERT INTO organizations (id, name, country) VALUES ('67',N'Openbare lichamen',N'NL');
INSERT INTO organizations (id, name, country) VALUES ('68',N'Kommunalt foretak',N'NO');
INSERT INTO organizations (id, name, country) VALUES ('69',N'Vertskommunesamarbeid',N'NO');
INSERT INTO organizations (id, name, country) VALUES ('70',N'Samkommune',N'NO');
INSERT INTO organizations (id, name, country) VALUES ('71',N'Interkommunalt selskap',N'NO');
INSERT INTO organizations (id, name, country) VALUES ('72',N'Interkommunalt og interfylkeskommunalt samarbeid',N'NO');
INSERT INTO organizations (id, name, country) VALUES ('73',N'Kommunesektorens organisasjon - KS',N'NO');
INSERT INTO organizations (id, name, country) VALUES ('74',N'Fylkeskommune',N'NO');
INSERT INTO organizations (id, name, country) VALUES ('75',N'Municipal associations (in accordance with Article 84 of the Act of 8 March 1990 on municipal self-government) "Stowarzyszenia gmin"',N'PL');
INSERT INTO organizations (id, name, country) VALUES ('76',N'Skupnost občin Slovenije',N'SI');
INSERT INTO organizations (id, name, country) VALUES ('77',N'Združenje občin Slovenije',N'SI');
INSERT INTO organizations (id, name, country) VALUES ('78',N'Združenie obcí',N'SK');
INSERT INTO organizations (id, name, country) VALUES ('79',N'Combined Authorities',N'UK');
INSERT INTO organizations (id, name, country) VALUES ('80',N'Local Enterprise Partnership (LEP)',N'UK');
