-- INSERT IS LAUS (added new name fields)
UPDATE laus SET name_national=N'Akrahreppur', name_latin=N'Akrahreppur', abac_name=N'Akrahreppur', display_name=N'Akrahreppur' WHERE id=69185;
UPDATE laus SET name_national=N'Akraneskaupstaður', name_latin=N'Akranes', abac_name=N'Akraneskaupstadur', display_name=N'Akraneskaupstaður' WHERE id=69160;
UPDATE laus SET name_national=N'Akureyrarkaupstaður', name_latin=N'Akureyri', abac_name=N'Akureyrarkaupstadur', display_name=N'Akureyrarkaupstaður' WHERE id=69186;
UPDATE laus SET name_national=N'Árneshreppur', name_latin=N'Arneshreppur', abac_name=N'Arneshreppur', display_name=N'Árneshreppur' WHERE id=69176;
UPDATE laus SET name_national=N'Ásahreppur', name_latin=N'Asahreppur', abac_name=N'Asahreppur', display_name=N'Ásahreppur' WHERE id=69212;
UPDATE laus SET name_national=N'Bláskógabyggð', name_latin=N'Blaskogabyggd', abac_name=N'Blaskogabyggd', display_name=N'Bláskógabyggð' WHERE id=69220;
UPDATE laus SET name_national=N'Blönduósbær', name_latin=N'Blonduossbaer', abac_name=N'Blonduosbaer', display_name=N'Blönduósbær' WHERE id=69181;
UPDATE laus SET name_national=N'Bolungarvíkurkaupstaður', name_latin=N'Bolungarvik', abac_name=N'Bolungarvikurkaupstadur', display_name=N'Bolungarvíkurkaupstaður' WHERE id=69170;
UPDATE laus SET name_national=N'Borgarbyggð', name_latin=N'Borgarbyggd', abac_name=N'Borgarbyggd', display_name=N'Borgarbyggð' WHERE id=69163;
UPDATE laus SET name_national=N'Borgarfjarðarhreppur', name_latin=N'Borgarfjardarhreppur', abac_name=N'Borgarfjardarhreppur', display_name=N'Borgarfjarðarhreppur' WHERE id=69203;
UPDATE laus SET name_national=N'Breiðdalshreppur', name_latin=N'Breiddalshreppur', abac_name=N'Breiddalshreppur', display_name=N'Breiðdalshreppur' WHERE id=69204;
UPDATE laus SET name_national=N'Dalabyggð', name_latin=N'Dalabyggd', abac_name=N'Dalabyggd', display_name=N'Dalabyggð' WHERE id=69169;
UPDATE laus SET name_national=N'Dalvíkurbyggð', name_latin=N'Dalvikurbyggd', abac_name=N'Dalvikurbyggd', display_name=N'Dalvíkurbyggð' WHERE id=69189;
UPDATE laus SET name_national=N'Djúpavogshreppur', name_latin=N'Djupavogshreppur', abac_name=N'Djupavogshreppur', display_name=N'Djúpavogshreppur' WHERE id=69205;
UPDATE laus SET name_national=N'Eyja- og Miklaholtshreppur', name_latin=N'Eyja- og Miklaholtshreppur', abac_name=N'Eyja- og Miklaholtshreppur', display_name=N'Eyja- og Miklaholtshreppur' WHERE id=69167;
UPDATE laus SET name_national=N'Eyjafjarðarsveit', name_latin=N'Eyjafjardarsveit', abac_name=N'Eyjafjardarsveit', display_name=N'Eyjafjarðarsveit' WHERE id=69190;
UPDATE laus SET name_national=N'Fjallabyggð', name_latin=N'Fjallabyggd', abac_name=N'Fjallabyggd', display_name=N'Fjallabyggð' WHERE id=69188;
UPDATE laus SET name_national=N'Fjarðabyggð', name_latin=N'Fjardabyggd', abac_name=N'Fjardabyggd', display_name=N'Fjarðabyggð' WHERE id=69200;
UPDATE laus SET name_national=N'Fljótsdalshérað', name_latin=N'Fljotsdalsherad', abac_name=N'Fljotsdalsherad', display_name=N'Fljótsdalshérað' WHERE id=69206;
UPDATE laus SET name_national=N'Fljótsdalshreppur', name_latin=N'Fljotsdalshreppur', abac_name=N'Fljotsdalshreppur', display_name=N'Fljótsdalshreppur' WHERE id=69202;
UPDATE laus SET name_national=N'Flóahreppur', name_latin=N'Floahreppur', abac_name=N'Floahreppur', display_name=N'Flóahreppur' WHERE id=69221;
UPDATE laus SET name_national=N'Garðabær', name_latin=N'Gardabaer', abac_name=N'Gardabaer', display_name=N'Garðabær' WHERE id=69151;
UPDATE laus SET name_national=N'Grímsnes- og Grafningshreppur', name_latin=N'Grimsnes- og Grafningshreppur', abac_name=N'Grimsnes- og Grafningshreppur', display_name=N'Grímsnes- og Grafningshreppur' WHERE id=69218;
UPDATE laus SET name_national=N'Grindavíkurbær', name_latin=N'Grindavikurbaer', abac_name=N'Grindavikurbaer', display_name=N'Grindavíkurbær' WHERE id=69156;
UPDATE laus SET name_national=N'Grundarfjarðarbær', name_latin=N'Grundarfjardarbaer', abac_name=N'Grundarfjardarbaer', display_name=N'Grundarfjarðarbær' WHERE id=69164;
UPDATE laus SET name_national=N'Grýtubakkahreppur', name_latin=N'Grytubakkahreppur', abac_name=N'Grytubakkahreppur', display_name=N'Grýtubakkahreppur' WHERE id=69193;
UPDATE laus SET name_national=N'Hafnarfjarðarkaupstaður', name_latin=N'Hafnarfjordur', abac_name=N'Hafnarfjardarkaupstadur', display_name=N'Hafnarfjarðarkaupstaður' WHERE id=69152;
UPDATE laus SET name_national=N'Helgafellssveit', name_latin=N'Helgafellssveit', abac_name=N'Helgafellssveit', display_name=N'Helgafellssveit' WHERE id=69165;
UPDATE laus SET name_national=N'Hörgársveit', name_latin=N'Horgarsveit', abac_name=N'Horgarsveit', display_name=N'Hörgársveit' WHERE id=69191;
UPDATE laus SET name_national=N'Hrunamannahreppur', name_latin=N'Hrunamannahreppur', abac_name=N'Hrunamannahreppur', display_name=N'Hrunamannahreppur' WHERE id=69215;
UPDATE laus SET name_national=N'Húnaþing vestra', name_latin=N'Hunathing vestra', abac_name=N'Hunathing vestra', display_name=N'Húnaþing vestra' WHERE id=69180;
UPDATE laus SET name_national=N'Húnavatnshreppur', name_latin=N'Hunavatnshreppur', abac_name=N'Hunavatnshreppur', display_name=N'Húnavatnshreppur' WHERE id=69184;
UPDATE laus SET name_national=N'Hvalfjarðarsveit', name_latin=N'Hvalfjardarsveit', abac_name=N'Hvalfjardarsveit', display_name=N'Hvalfjarðarsveit' WHERE id=69162;
UPDATE laus SET name_national=N'Hveragerðisbær', name_latin=N'Hveragerdi', abac_name=N'Hveragerdisbaer', display_name=N'Hveragerðisbær' WHERE id=69216;
UPDATE laus SET name_national=N'Ísafjarðarbær', name_latin=N'Isafjardarbaer', abac_name=N'Isafjardarbaer', display_name=N'Ísafjarðarbær' WHERE id=69171;
UPDATE laus SET name_national=N'Kaldrananeshreppur', name_latin=N'Kaldrananeshreppur', abac_name=N'Kaldrananeshreppur', display_name=N'Kaldrananeshreppur' WHERE id=69177;
UPDATE laus SET name_national=N'Kjósarhreppur', name_latin=N'Kjosarhreppur', abac_name=N'Kjosarhreppur', display_name=N'Kjósarhreppur' WHERE id=69154;
UPDATE laus SET name_national=N'Kópavogsbær', name_latin=N'Kopavogur', abac_name=N'Kopavogsbaer', display_name=N'Kópavogsbær' WHERE id=69149;
UPDATE laus SET name_national=N'Langanesbyggð', name_latin=N'Langanesbyggd', abac_name=N'Langanesbyggd', display_name=N'Langanesbyggð' WHERE id=69198;
UPDATE laus SET name_national=N'Mosfellsbær', name_latin=N'Mosfellsbaer', abac_name=N'Mosfellsbaer', display_name=N'Mosfellsbær' WHERE id=69153;
UPDATE laus SET name_national=N'Mýrdalshreppur', name_latin=N'Myrdalshreppur', abac_name=N'Myrdalshreppur', display_name=N'Mýrdalshreppur' WHERE id=69210;
UPDATE laus SET name_national=N'Norðurþing', name_latin=N'Nordurthing', abac_name=N'Nordurthing', display_name=N'Norðurþing' WHERE id=69187;
UPDATE laus SET name_national=N'Rangárþing eystra', name_latin=N'Rangarthing eystra', abac_name=N'Rangarthing eystra', display_name=N'Rangárþing eystra' WHERE id=69213;
UPDATE laus SET name_national=N'Rangárþing ytra', name_latin=N'Rangarthing ytra', abac_name=N'Rangarthing ytra', display_name=N'Rangárþing ytra' WHERE id=69214;
UPDATE laus SET name_national=N'Reykhólahreppur', name_latin=N'Reykholahreppur', abac_name=N'Reykholahreppur', display_name=N'Reykhólahreppur' WHERE id=69172;
UPDATE laus SET name_national=N'Reykjanesbær', name_latin=N'Reykjanesbaer', abac_name=N'Reykjanesbaer', display_name=N'Reykjanesbær' WHERE id=69155;
UPDATE laus SET name_national=N'Reykjavíkurborg', name_latin=N'Reykjavik', abac_name=N'Reykjavikurborg', display_name=N'Reykjavíkurborg' WHERE id=69148;
UPDATE laus SET name_national=N'Sandgerðisbær', name_latin=N'Sandgerdi', abac_name=N'Sandgerdisbaer', display_name=N'Sandgerðisbær' WHERE id=69157;
UPDATE laus SET name_national=N'Seltjarnarneskaupstaður', name_latin=N'Seltjarnarnes', abac_name=N'Seltjarnarneskaupstadur', display_name=N'Seltjarnarneskaupstaður' WHERE id=69150;
UPDATE laus SET name_national=N'Seyðisfjarðarkaupstaður', name_latin=N'Seydisfjordur', abac_name=N'Seydisfjardarkaupstadur', display_name=N'Seyðisfjarðarkaupstaður' WHERE id=69199;
UPDATE laus SET name_national=N'Skaftárhreppur', name_latin=N'Skaftarhreppur', abac_name=N'Skaftarhreppur', display_name=N'Skaftárhreppur' WHERE id=69211;
UPDATE laus SET name_national=N'Skagabyggð', name_latin=N'Skagabyggd', abac_name=N'Skagabyggd', display_name=N'Skagabyggð' WHERE id=69183;
UPDATE laus SET name_national=N'Skeiða- og Gnúpverjahreppur', name_latin=N'Skeida- og Gnupverjahreppur', abac_name=N'Skeida- og Gnupverjahreppur', display_name=N'Skeiða- og Gnúpverjahreppur' WHERE id=69219;
UPDATE laus SET name_national=N'Skorradalshreppur', name_latin=N'Skorradalshreppur', abac_name=N'Skorradalshreppur', display_name=N'Skorradalshreppur' WHERE id=69161;
UPDATE laus SET name_national=N'Skútustaðahreppur', name_latin=N'Skutustadahreppur', abac_name=N'Skutustadahreppur', display_name=N'Skútustaðahreppur' WHERE id=69194;
UPDATE laus SET name_national=N'Snæfellsbær', name_latin=N'Snaefellsbaer', abac_name=N'Snaefellsbaer', display_name=N'Snæfellsbær' WHERE id=69168;
UPDATE laus SET name_national=N'Strandabyggð', name_latin=N'Strandabyggd', abac_name=N'Strandabyggd', display_name=N'Strandabyggð' WHERE id=69178;
UPDATE laus SET name_national=N'Stykkishólmsbær', name_latin=N'Stykkisholmur', abac_name=N'Stykkisholmsbaer', display_name=N'Stykkishólmsbær' WHERE id=69166;
UPDATE laus SET name_national=N'Súðavíkurhreppur', name_latin=N'Sudavikurhreppur', abac_name=N'Sudavikurhreppur', display_name=N'Súðavíkurhreppur' WHERE id=69175;
UPDATE laus SET name_national=N'Svalbarðshreppur', name_latin=N'Svalbardshreppur', abac_name=N'Svalbardshreppur', display_name=N'Svalbarðshreppur' WHERE id=69197;
UPDATE laus SET name_national=N'Svalbarðsstrandarhreppur', name_latin=N'Svalbardsstrandarhreppur', abac_name=N'Svalbardsstrandarhreppur', display_name=N'Svalbarðsstrandarhreppur' WHERE id=69192;
UPDATE laus SET name_national=N'Sveitarfélagið Árborg', name_latin=N'Sveitarfelagid Arborg', abac_name=N'Sveitarfelagid Arborg', display_name=N'Sveitarfélagið Árborg' WHERE id=69209;
UPDATE laus SET name_national=N'Sveitarfélagið Garður', name_latin=N'Sveitarfelagid Gardur', abac_name=N'Sveitarfelagid Gardur', display_name=N'Sveitarfélagið Garður' WHERE id=69158;
UPDATE laus SET name_national=N'Sveitarfélagið Hornafjörður', name_latin=N'Sveitarfelagid Hornafjordur', abac_name=N'Sveitarfelagid Hornafjordur', display_name=N'Sveitarfélagið Hornafjörður' WHERE id=69207;
UPDATE laus SET name_national=N'Sveitarfélagið Ölfus', name_latin=N'Sveitarfelagid Olfus', abac_name=N'Sveitarfelagid Olfus', display_name=N'Sveitarfélagið Ölfus' WHERE id=69217;
UPDATE laus SET name_national=N'Sveitarfélagið Skagafjörður', name_latin=N'Sveitarfelagid Skagafjordur', abac_name=N'Sveitarfelagid Skagafjordur', display_name=N'Sveitarfélagið Skagafjörður' WHERE id=69179;
UPDATE laus SET name_national=N'Sveitarfélagið Skagaströnd', name_latin=N'Sveitarfelagid Skagastrond', abac_name=N'Sveitarfelagid Skagastrond', display_name=N'Sveitarfélagið Skagaströnd' WHERE id=69182;
UPDATE laus SET name_national=N'Sveitarfélagið Vogar', name_latin=N'Sveitarfelagid Vogar', abac_name=N'Sveitarfelagid Vogar', display_name=N'Sveitarfélagið Vogar' WHERE id=69159;
UPDATE laus SET name_national=N'Tálknafjarðarhreppur', name_latin=N'Talknafjardarhreppur', abac_name=N'Talknafjardarhreppur', display_name=N'Tálknafjarðarhreppur' WHERE id=69173;
UPDATE laus SET name_national=N'Þingeyjarsveit', name_latin=N'Thingeyjarsveit', abac_name=N'Thingeyjarsveit', display_name=N'Þingeyjarsveit' WHERE id=69196;
UPDATE laus SET name_national=N'Tjörneshreppur', name_latin=N'Tjorneshreppur', abac_name=N'Tjorneshreppur', display_name=N'Tjörneshreppur' WHERE id=69195;
UPDATE laus SET name_national=N'Vestmannaeyjabær', name_latin=N'Vestmannaeyjar', abac_name=N'Vestmannaeyjabaer', display_name=N'Vestmannaeyjabær' WHERE id=69208;
UPDATE laus SET name_national=N'Vesturbyggð', name_latin=N'Vesturbyggd', abac_name=N'Vesturbyggd', display_name=N'Vesturbyggð' WHERE id=69174;
UPDATE laus SET name_national=N'Vopnafjarðarhreppur', name_latin=N'Vopnafjardarhreppur', abac_name=N'Vopnafjardarhreppur', display_name=N'Vopnafjarðarhreppur' WHERE id=69201;
--74

--select nuts3, lau1, name_national, name_latin, abac_name, display_name, id 
--from laus where country_code = 'IS' order by name1 asc