 -- SQL (names)
UPDATE laus SET name_national=N'Aberdeen City', name_latin=N'Aberdeen City', abac_name=N'Aberdeen City', display_name=N'Aberdeen City' WHERE id=87720;
UPDATE laus SET name_national=N'Aberdeenshire', name_latin=N'Aberdeenshire', abac_name=N'Aberdeenshire', display_name=N'Aberdeenshire' WHERE id=87721;
UPDATE laus SET name_national=N'Adur', name_latin=N'Adur', abac_name=N'Adur', display_name=N'Adur' WHERE id=87722;
UPDATE laus SET name_national=N'Allerdale', name_latin=N'Allerdale', abac_name=N'Allerdale', display_name=N'Allerdale' WHERE id=87723;
UPDATE laus SET name_national=N'Amber Valley', name_latin=N'Amber Valley', abac_name=N'Amber Valley', display_name=N'Amber Valley' WHERE id=87724;
UPDATE laus SET name_national=N'Angus', name_latin=N'Angus', abac_name=N'Angus', display_name=N'Angus' WHERE id=87725;
UPDATE laus SET name_national=N'Antrim and Newtownabbey', name_latin=N'Antrim and Newtownabbey', abac_name=N'Antrim and Newtownabbey', display_name=N'Antrim and Newtownabbey' WHERE id=87726;
UPDATE laus SET name_national=N'Ards and North Down', name_latin=N'Ards and North Down', abac_name=N'Ards and North Down', display_name=N'Ards and North Down' WHERE id=87727;
UPDATE laus SET name_national=N'Argyll and Bute Islands', name_latin=N'Argyll and Bute Islands', abac_name=N'Argyll and Bute Islands', display_name=N'Argyll and Bute Islands' WHERE id=87728;
UPDATE laus SET name_national=N'Argyll and Bute Mainland', name_latin=N'Argyll and Bute Mainland', abac_name=N'Argyll and Bute Mainland', display_name=N'Argyll and Bute Mainland' WHERE id=87729;
UPDATE laus SET name_national=N'Armagh City, Banbridge and Craigavon', name_latin=N'Armagh City, Banbridge and Craigavon', abac_name=N'Armagh City, Banbridge and Craigavon', display_name=N'Armagh City, Banbridge and Craigavon' WHERE id=87730;
UPDATE laus SET name_national=N'Arran and Cumbrae', name_latin=N'Arran and Cumbrae', abac_name=N'Arran and Cumbrae', display_name=N'Arran and Cumbrae' WHERE id=87731;
UPDATE laus SET name_national=N'Arun', name_latin=N'Arun', abac_name=N'Arun', display_name=N'Arun' WHERE id=87732;
UPDATE laus SET name_national=N'Ashfield', name_latin=N'Ashfield', abac_name=N'Ashfield', display_name=N'Ashfield' WHERE id=87733;
UPDATE laus SET name_national=N'Ashford', name_latin=N'Ashford', abac_name=N'Ashford', display_name=N'Ashford' WHERE id=87734;
UPDATE laus SET name_national=N'Aylesbury Vale', name_latin=N'Aylesbury Vale', abac_name=N'Aylesbury Vale', display_name=N'Aylesbury Vale' WHERE id=87735;
UPDATE laus SET name_national=N'Babergh', name_latin=N'Babergh', abac_name=N'Babergh', display_name=N'Babergh' WHERE id=87736;
UPDATE laus SET name_national=N'Badenoch and Strathspey', name_latin=N'Badenoch and Strathspey', abac_name=N'Badenoch and Strathspey', display_name=N'Badenoch and Strathspey' WHERE id=87737;
UPDATE laus SET name_national=N'Barking and Dagenham', name_latin=N'Barking and Dagenham', abac_name=N'Barking and Dagenham', display_name=N'Barking and Dagenham' WHERE id=87738;
UPDATE laus SET name_national=N'Barnet', name_latin=N'Barnet', abac_name=N'Barnet', display_name=N'Barnet' WHERE id=87739;
UPDATE laus SET name_national=N'Barnsley', name_latin=N'Barnsley', abac_name=N'Barnsley', display_name=N'Barnsley' WHERE id=87740;
UPDATE laus SET name_national=N'Barrow-in-Furness', name_latin=N'Barrow-in-Furness', abac_name=N'Barrow-in-Furness', display_name=N'Barrow-in-Furness' WHERE id=87741;
UPDATE laus SET name_national=N'Basildon', name_latin=N'Basildon', abac_name=N'Basildon', display_name=N'Basildon' WHERE id=87742;
UPDATE laus SET name_national=N'Basingstoke and Deane', name_latin=N'Basingstoke and Deane', abac_name=N'Basingstoke and Deane', display_name=N'Basingstoke and Deane' WHERE id=87743;
UPDATE laus SET name_national=N'Bassetlaw', name_latin=N'Bassetlaw', abac_name=N'Bassetlaw', display_name=N'Bassetlaw' WHERE id=87744;
UPDATE laus SET name_national=N'Bath and North East Somerset', name_latin=N'Bath and North East Somerset', abac_name=N'Bath and North East Somerset', display_name=N'Bath and North East Somerset' WHERE id=87745;
UPDATE laus SET name_national=N'Bedford', name_latin=N'Bedford', abac_name=N'Bedford', display_name=N'Bedford' WHERE id=87746;
UPDATE laus SET name_national=N'Belfast', name_latin=N'Belfast', abac_name=N'Belfast', display_name=N'Belfast' WHERE id=87747;
UPDATE laus SET name_national=N'Bexley', name_latin=N'Bexley', abac_name=N'Bexley', display_name=N'Bexley' WHERE id=87748;
UPDATE laus SET name_national=N'Birmingham', name_latin=N'Birmingham', abac_name=N'Birmingham', display_name=N'Birmingham' WHERE id=87749;
UPDATE laus SET name_national=N'Blaby', name_latin=N'Blaby', abac_name=N'Blaby', display_name=N'Blaby' WHERE id=87750;
UPDATE laus SET name_national=N'Blackburn with Darwen', name_latin=N'Blackburn with Darwen', abac_name=N'Blackburn with Darwen', display_name=N'Blackburn with Darwen' WHERE id=87751;
UPDATE laus SET name_national=N'Blackpool', name_latin=N'Blackpool', abac_name=N'Blackpool', display_name=N'Blackpool' WHERE id=87752;
UPDATE laus SET name_national=N'Blaenau Gwent - Blaenau Gwent', name_latin=N'Blaenau Gwent - Blaenau Gwent', abac_name=N'Blaenau Gwent - Blaenau Gwent', display_name=N'Blaenau Gwent - Blaenau Gwent' WHERE id=87753;
UPDATE laus SET name_national=N'Bolsover', name_latin=N'Bolsover', abac_name=N'Bolsover', display_name=N'Bolsover' WHERE id=87754;
UPDATE laus SET name_national=N'Bolton', name_latin=N'Bolton', abac_name=N'Bolton', display_name=N'Bolton' WHERE id=87755;
UPDATE laus SET name_national=N'Boston', name_latin=N'Boston', abac_name=N'Boston', display_name=N'Boston' WHERE id=87756;
UPDATE laus SET name_national=N'Bournemouth', name_latin=N'Bournemouth', abac_name=N'Bournemouth', display_name=N'Bournemouth' WHERE id=87757;
UPDATE laus SET name_national=N'Bracknell Forest', name_latin=N'Bracknell Forest', abac_name=N'Bracknell Forest', display_name=N'Bracknell Forest' WHERE id=87758;
UPDATE laus SET name_national=N'Bradford', name_latin=N'Bradford', abac_name=N'Bradford', display_name=N'Bradford' WHERE id=87759;
UPDATE laus SET name_national=N'Braintree', name_latin=N'Braintree', abac_name=N'Braintree', display_name=N'Braintree' WHERE id=87760;
UPDATE laus SET name_national=N'Breckland', name_latin=N'Breckland', abac_name=N'Breckland', display_name=N'Breckland' WHERE id=87761;
UPDATE laus SET name_national=N'Brent', name_latin=N'Brent', abac_name=N'Brent', display_name=N'Brent' WHERE id=87762;
UPDATE laus SET name_national=N'Brentwood', name_latin=N'Brentwood', abac_name=N'Brentwood', display_name=N'Brentwood' WHERE id=87763;
UPDATE laus SET name_national=N'Bridgend - Pen-y-bont ar Ogwr', name_latin=N'Bridgend - Pen-y-bont ar Ogwr', abac_name=N'Bridgend - Pen-y-bont ar Ogwr', display_name=N'Bridgend - Pen-y-bont ar Ogwr' WHERE id=87764;
UPDATE laus SET name_national=N'Brighton and Hove', name_latin=N'Brighton and Hove', abac_name=N'Brighton and Hove', display_name=N'Brighton and Hove' WHERE id=87765;
UPDATE laus SET name_national=N'Bristol, City of', name_latin=N'Bristol, City of', abac_name=N'Bristol, City of', display_name=N'Bristol, City of' WHERE id=87766;
UPDATE laus SET name_national=N'Broadland', name_latin=N'Broadland', abac_name=N'Broadland', display_name=N'Broadland' WHERE id=87767;
UPDATE laus SET name_national=N'Bromley', name_latin=N'Bromley', abac_name=N'Bromley', display_name=N'Bromley' WHERE id=87768;
UPDATE laus SET name_national=N'Bromsgrove', name_latin=N'Bromsgrove', abac_name=N'Bromsgrove', display_name=N'Bromsgrove' WHERE id=87769;
UPDATE laus SET name_national=N'Broxbourne', name_latin=N'Broxbourne', abac_name=N'Broxbourne', display_name=N'Broxbourne' WHERE id=87770;
UPDATE laus SET name_national=N'Broxtowe', name_latin=N'Broxtowe', abac_name=N'Broxtowe', display_name=N'Broxtowe' WHERE id=87771;
UPDATE laus SET name_national=N'Burnley', name_latin=N'Burnley', abac_name=N'Burnley', display_name=N'Burnley' WHERE id=87772;
UPDATE laus SET name_national=N'Bury', name_latin=N'Bury', abac_name=N'Bury', display_name=N'Bury' WHERE id=87773;
UPDATE laus SET name_national=N'Caerphilly - Caerffili', name_latin=N'Caerphilly - Caerffili', abac_name=N'Caerphilly - Caerffili', display_name=N'Caerphilly - Caerffili' WHERE id=87774;
UPDATE laus SET name_national=N'Caithness and Sutherland', name_latin=N'Caithness and Sutherland', abac_name=N'Caithness and Sutherland', display_name=N'Caithness and Sutherland' WHERE id=87775;
UPDATE laus SET name_national=N'Calderdale', name_latin=N'Calderdale', abac_name=N'Calderdale', display_name=N'Calderdale' WHERE id=87776;
UPDATE laus SET name_national=N'Cambridge', name_latin=N'Cambridge', abac_name=N'Cambridge', display_name=N'Cambridge' WHERE id=87777;
UPDATE laus SET name_national=N'Camden', name_latin=N'Camden', abac_name=N'Camden', display_name=N'Camden' WHERE id=87778;
UPDATE laus SET name_national=N'Cannock Chase', name_latin=N'Cannock Chase', abac_name=N'Cannock Chase', display_name=N'Cannock Chase' WHERE id=87779;
UPDATE laus SET name_national=N'Canterbury', name_latin=N'Canterbury', abac_name=N'Canterbury', display_name=N'Canterbury' WHERE id=87780;
UPDATE laus SET name_national=N'Cardiff - Caerdydd', name_latin=N'Cardiff - Caerdydd', abac_name=N'Cardiff - Caerdydd', display_name=N'Cardiff - Caerdydd' WHERE id=87781;
UPDATE laus SET name_national=N'Carlisle', name_latin=N'Carlisle', abac_name=N'Carlisle', display_name=N'Carlisle' WHERE id=87782;
UPDATE laus SET name_national=N'Carmarthenshire - Sir Gaerfyrddin', name_latin=N'Carmarthenshire - Sir Gaerfyrddin', abac_name=N'Carmarthenshire - Sir Gaerfyrddin', display_name=N'Carmarthenshire - Sir Gaerfyrddin' WHERE id=87783;
UPDATE laus SET name_national=N'Castle Point', name_latin=N'Castle Point', abac_name=N'Castle Point', display_name=N'Castle Point' WHERE id=87784;
UPDATE laus SET name_national=N'Causeway Coast and Glens', name_latin=N'Causeway Coast and Glens', abac_name=N'Causeway Coast and Glens', display_name=N'Causeway Coast and Glens' WHERE id=87785;
UPDATE laus SET name_national=N'Central Bedfordshire', name_latin=N'Central Bedfordshire', abac_name=N'Central Bedfordshire', display_name=N'Central Bedfordshire' WHERE id=87786;
UPDATE laus SET name_national=N'Ceredigion - Ceredigion', name_latin=N'Ceredigion - Ceredigion', abac_name=N'Ceredigion - Ceredigion', display_name=N'Ceredigion - Ceredigion' WHERE id=87787;
UPDATE laus SET name_national=N'Charnwood', name_latin=N'Charnwood', abac_name=N'Charnwood', display_name=N'Charnwood' WHERE id=87788;
UPDATE laus SET name_national=N'Chelmsford', name_latin=N'Chelmsford', abac_name=N'Chelmsford', display_name=N'Chelmsford' WHERE id=87789;
UPDATE laus SET name_national=N'Cheltenham', name_latin=N'Cheltenham', abac_name=N'Cheltenham', display_name=N'Cheltenham' WHERE id=87790;
UPDATE laus SET name_national=N'Cherwell', name_latin=N'Cherwell', abac_name=N'Cherwell', display_name=N'Cherwell' WHERE id=87791;
UPDATE laus SET name_national=N'Cheshire East', name_latin=N'Cheshire East', abac_name=N'Cheshire East', display_name=N'Cheshire East' WHERE id=87792;
UPDATE laus SET name_national=N'Cheshire West and Chester', name_latin=N'Cheshire West and Chester', abac_name=N'Cheshire West and Chester', display_name=N'Cheshire West and Chester' WHERE id=87793;
UPDATE laus SET name_national=N'Chesterfield', name_latin=N'Chesterfield', abac_name=N'Chesterfield', display_name=N'Chesterfield' WHERE id=87794;
UPDATE laus SET name_national=N'Chichester', name_latin=N'Chichester', abac_name=N'Chichester', display_name=N'Chichester' WHERE id=87795;
UPDATE laus SET name_national=N'Chiltern', name_latin=N'Chiltern', abac_name=N'Chiltern', display_name=N'Chiltern' WHERE id=87796;
UPDATE laus SET name_national=N'Chorley', name_latin=N'Chorley', abac_name=N'Chorley', display_name=N'Chorley' WHERE id=87797;
UPDATE laus SET name_national=N'Christchurch', name_latin=N'Christchurch', abac_name=N'Christchurch', display_name=N'Christchurch' WHERE id=87798;
UPDATE laus SET name_national=N'City of Edinburgh', name_latin=N'City of Edinburgh', abac_name=N'City of Edinburgh', display_name=N'City of Edinburgh' WHERE id=87799;
UPDATE laus SET name_national=N'City of London', name_latin=N'City of London', abac_name=N'City of London', display_name=N'City of London' WHERE id=87800;
UPDATE laus SET name_national=N'Clackmannanshire', name_latin=N'Clackmannanshire', abac_name=N'Clackmannanshire', display_name=N'Clackmannanshire' WHERE id=87801;
UPDATE laus SET name_national=N'Colchester', name_latin=N'Colchester', abac_name=N'Colchester', display_name=N'Colchester' WHERE id=87802;
UPDATE laus SET name_national=N'Conwy - Conwy', name_latin=N'Conwy - Conwy', abac_name=N'Conwy - Conwy', display_name=N'Conwy - Conwy' WHERE id=87803;
UPDATE laus SET name_national=N'Copeland', name_latin=N'Copeland', abac_name=N'Copeland', display_name=N'Copeland' WHERE id=87804;
UPDATE laus SET name_national=N'Corby', name_latin=N'Corby', abac_name=N'Corby', display_name=N'Corby' WHERE id=87805;
UPDATE laus SET name_national=N'Cornwall', name_latin=N'Cornwall', abac_name=N'Cornwall', display_name=N'Cornwall' WHERE id=87806;
UPDATE laus SET name_national=N'Cotswold', name_latin=N'Cotswold', abac_name=N'Cotswold', display_name=N'Cotswold' WHERE id=87807;
UPDATE laus SET name_national=N'County Durham', name_latin=N'County Durham', abac_name=N'County Durham', display_name=N'County Durham' WHERE id=87808;
UPDATE laus SET name_national=N'Coventry', name_latin=N'Coventry', abac_name=N'Coventry', display_name=N'Coventry' WHERE id=87809;
UPDATE laus SET name_national=N'Craven', name_latin=N'Craven', abac_name=N'Craven', display_name=N'Craven' WHERE id=87810;
UPDATE laus SET name_national=N'Crawley', name_latin=N'Crawley', abac_name=N'Crawley', display_name=N'Crawley' WHERE id=87811;
UPDATE laus SET name_national=N'Croydon', name_latin=N'Croydon', abac_name=N'Croydon', display_name=N'Croydon' WHERE id=87812;
UPDATE laus SET name_national=N'Dacorum', name_latin=N'Dacorum', abac_name=N'Dacorum', display_name=N'Dacorum' WHERE id=87813;
UPDATE laus SET name_national=N'Darlington', name_latin=N'Darlington', abac_name=N'Darlington', display_name=N'Darlington' WHERE id=87814;
UPDATE laus SET name_national=N'Dartford', name_latin=N'Dartford', abac_name=N'Dartford', display_name=N'Dartford' WHERE id=87815;
UPDATE laus SET name_national=N'Daventry', name_latin=N'Daventry', abac_name=N'Daventry', display_name=N'Daventry' WHERE id=87816;
UPDATE laus SET name_national=N'Denbighshire - Sir Ddinbych', name_latin=N'Denbighshire - Sir Ddinbych', abac_name=N'Denbighshire - Sir Ddinbych', display_name=N'Denbighshire - Sir Ddinbych' WHERE id=87817;
UPDATE laus SET name_national=N'Derby', name_latin=N'Derby', abac_name=N'Derby', display_name=N'Derby' WHERE id=87818;
UPDATE laus SET name_national=N'Derbyshire Dales', name_latin=N'Derbyshire Dales', abac_name=N'Derbyshire Dales', display_name=N'Derbyshire Dales' WHERE id=87819;
UPDATE laus SET name_national=N'Derry City and Strabane', name_latin=N'Derry City and Strabane', abac_name=N'Derry City and Strabane', display_name=N'Derry City and Strabane' WHERE id=87820;
UPDATE laus SET name_national=N'Doncaster', name_latin=N'Doncaster', abac_name=N'Doncaster', display_name=N'Doncaster' WHERE id=87821;
UPDATE laus SET name_national=N'Dover', name_latin=N'Dover', abac_name=N'Dover', display_name=N'Dover' WHERE id=87822;
UPDATE laus SET name_national=N'Dudley', name_latin=N'Dudley', abac_name=N'Dudley', display_name=N'Dudley' WHERE id=87823;
UPDATE laus SET name_national=N'Dumfries and Galloway', name_latin=N'Dumfries and Galloway', abac_name=N'Dumfries and Galloway', display_name=N'Dumfries and Galloway' WHERE id=87824;
UPDATE laus SET name_national=N'Dundee City', name_latin=N'Dundee City', abac_name=N'Dundee City', display_name=N'Dundee City' WHERE id=87825;
UPDATE laus SET name_national=N'Ealing', name_latin=N'Ealing', abac_name=N'Ealing', display_name=N'Ealing' WHERE id=87826;
UPDATE laus SET name_national=N'East Ayrshire', name_latin=N'East Ayrshire', abac_name=N'East Ayrshire', display_name=N'East Ayrshire' WHERE id=87827;
UPDATE laus SET name_national=N'East Cambridgeshire', name_latin=N'East Cambridgeshire', abac_name=N'East Cambridgeshire', display_name=N'East Cambridgeshire' WHERE id=87828;
UPDATE laus SET name_national=N'East Devon', name_latin=N'East Devon', abac_name=N'East Devon', display_name=N'East Devon' WHERE id=87829;
UPDATE laus SET name_national=N'East Dorset', name_latin=N'East Dorset', abac_name=N'East Dorset', display_name=N'East Dorset' WHERE id=87830;
UPDATE laus SET name_national=N'East Dunbartonshire', name_latin=N'East Dunbartonshire', abac_name=N'East Dunbartonshire', display_name=N'East Dunbartonshire' WHERE id=87831;
UPDATE laus SET name_national=N'East Hampshire', name_latin=N'East Hampshire', abac_name=N'East Hampshire', display_name=N'East Hampshire' WHERE id=87832;
UPDATE laus SET name_national=N'East Hertfordshire', name_latin=N'East Hertfordshire', abac_name=N'East Hertfordshire', display_name=N'East Hertfordshire' WHERE id=87833;
UPDATE laus SET name_national=N'East Lindsey', name_latin=N'East Lindsey', abac_name=N'East Lindsey', display_name=N'East Lindsey' WHERE id=87834;
UPDATE laus SET name_national=N'East Lothian', name_latin=N'East Lothian', abac_name=N'East Lothian', display_name=N'East Lothian' WHERE id=87835;
UPDATE laus SET name_national=N'East Northamptonshire', name_latin=N'East Northamptonshire', abac_name=N'East Northamptonshire', display_name=N'East Northamptonshire' WHERE id=87836;
UPDATE laus SET name_national=N'East Renfrewshire', name_latin=N'East Renfrewshire', abac_name=N'East Renfrewshire', display_name=N'East Renfrewshire' WHERE id=87837;
UPDATE laus SET name_national=N'East Riding of Yorkshire', name_latin=N'East Riding of Yorkshire', abac_name=N'East Riding of Yorkshire', display_name=N'East Riding of Yorkshire' WHERE id=87838;
UPDATE laus SET name_national=N'East Staffordshire', name_latin=N'East Staffordshire', abac_name=N'East Staffordshire', display_name=N'East Staffordshire' WHERE id=87839;
UPDATE laus SET name_national=N'Eastbourne', name_latin=N'Eastbourne', abac_name=N'Eastbourne', display_name=N'Eastbourne' WHERE id=87840;
UPDATE laus SET name_national=N'Eastleigh', name_latin=N'Eastleigh', abac_name=N'Eastleigh', display_name=N'Eastleigh' WHERE id=87841;
UPDATE laus SET name_national=N'Eden', name_latin=N'Eden', abac_name=N'Eden', display_name=N'Eden' WHERE id=87842;
UPDATE laus SET name_national=N'Elmbridge', name_latin=N'Elmbridge', abac_name=N'Elmbridge', display_name=N'Elmbridge' WHERE id=87843;
UPDATE laus SET name_national=N'Enfield', name_latin=N'Enfield', abac_name=N'Enfield', display_name=N'Enfield' WHERE id=87844;
UPDATE laus SET name_national=N'Epping Forest', name_latin=N'Epping Forest', abac_name=N'Epping Forest', display_name=N'Epping Forest' WHERE id=87845;
UPDATE laus SET name_national=N'Epsom and Ewell', name_latin=N'Epsom and Ewell', abac_name=N'Epsom and Ewell', display_name=N'Epsom and Ewell' WHERE id=87846;
UPDATE laus SET name_national=N'Erewash', name_latin=N'Erewash', abac_name=N'Erewash', display_name=N'Erewash' WHERE id=87847;
UPDATE laus SET name_national=N'Exeter', name_latin=N'Exeter', abac_name=N'Exeter', display_name=N'Exeter' WHERE id=87848;
UPDATE laus SET name_national=N'Falkirk', name_latin=N'Falkirk', abac_name=N'Falkirk', display_name=N'Falkirk' WHERE id=87849;
UPDATE laus SET name_national=N'Fareham', name_latin=N'Fareham', abac_name=N'Fareham', display_name=N'Fareham' WHERE id=87850;
UPDATE laus SET name_national=N'Fenland', name_latin=N'Fenland', abac_name=N'Fenland', display_name=N'Fenland' WHERE id=87851;
UPDATE laus SET name_national=N'Fermanagh and Omagh', name_latin=N'Fermanagh and Omagh', abac_name=N'Fermanagh and Omagh', display_name=N'Fermanagh and Omagh' WHERE id=87852;
UPDATE laus SET name_national=N'Fife', name_latin=N'Fife', abac_name=N'Fife', display_name=N'Fife' WHERE id=87853;
UPDATE laus SET name_national=N'Flintshire - Sir y Fflint', name_latin=N'Flintshire - Sir y Fflint', abac_name=N'Flintshire - Sir y Fflint', display_name=N'Flintshire - Sir y Fflint' WHERE id=87854;
UPDATE laus SET name_national=N'Forest Heath', name_latin=N'Forest Heath', abac_name=N'Forest Heath', display_name=N'Forest Heath' WHERE id=87855;
UPDATE laus SET name_national=N'Forest of Dean', name_latin=N'Forest of Dean', abac_name=N'Forest of Dean', display_name=N'Forest of Dean' WHERE id=87856;
UPDATE laus SET name_national=N'Fylde', name_latin=N'Fylde', abac_name=N'Fylde', display_name=N'Fylde' WHERE id=87857;
UPDATE laus SET name_national=N'Gateshead', name_latin=N'Gateshead', abac_name=N'Gateshead', display_name=N'Gateshead' WHERE id=87858;
UPDATE laus SET name_national=N'Gedling', name_latin=N'Gedling', abac_name=N'Gedling', display_name=N'Gedling' WHERE id=87859;
UPDATE laus SET name_national=N'Glasgow City', name_latin=N'Glasgow City', abac_name=N'Glasgow City', display_name=N'Glasgow City' WHERE id=87860;
UPDATE laus SET name_national=N'Gloucester', name_latin=N'Gloucester', abac_name=N'Gloucester', display_name=N'Gloucester' WHERE id=87861;
UPDATE laus SET name_national=N'Gosport', name_latin=N'Gosport', abac_name=N'Gosport', display_name=N'Gosport' WHERE id=87862;
UPDATE laus SET name_national=N'Gravesham', name_latin=N'Gravesham', abac_name=N'Gravesham', display_name=N'Gravesham' WHERE id=87863;
UPDATE laus SET name_national=N'Great Yarmouth', name_latin=N'Great Yarmouth', abac_name=N'Great Yarmouth', display_name=N'Great Yarmouth' WHERE id=87864;
UPDATE laus SET name_national=N'Greenwich', name_latin=N'Greenwich', abac_name=N'Greenwich', display_name=N'Greenwich' WHERE id=87865;
UPDATE laus SET name_national=N'Guildford', name_latin=N'Guildford', abac_name=N'Guildford', display_name=N'Guildford' WHERE id=87866;
UPDATE laus SET name_national=N'Gwynedd - Gwynedd', name_latin=N'Gwynedd - Gwynedd', abac_name=N'Gwynedd - Gwynedd', display_name=N'Gwynedd - Gwynedd' WHERE id=87867;
UPDATE laus SET name_national=N'Hackney', name_latin=N'Hackney', abac_name=N'Hackney', display_name=N'Hackney' WHERE id=87868;
UPDATE laus SET name_national=N'Halton', name_latin=N'Halton', abac_name=N'Halton', display_name=N'Halton' WHERE id=87869;
UPDATE laus SET name_national=N'Hambleton', name_latin=N'Hambleton', abac_name=N'Hambleton', display_name=N'Hambleton' WHERE id=87870;
UPDATE laus SET name_national=N'Hammersmith and Fulham', name_latin=N'Hammersmith and Fulham', abac_name=N'Hammersmith and Fulham', display_name=N'Hammersmith and Fulham' WHERE id=87871;
UPDATE laus SET name_national=N'Harborough', name_latin=N'Harborough', abac_name=N'Harborough', display_name=N'Harborough' WHERE id=87872;
UPDATE laus SET name_national=N'Haringey', name_latin=N'Haringey', abac_name=N'Haringey', display_name=N'Haringey' WHERE id=87873;
UPDATE laus SET name_national=N'Harlow', name_latin=N'Harlow', abac_name=N'Harlow', display_name=N'Harlow' WHERE id=87874;
UPDATE laus SET name_national=N'Harrogate', name_latin=N'Harrogate', abac_name=N'Harrogate', display_name=N'Harrogate' WHERE id=87875;
UPDATE laus SET name_national=N'Harrow', name_latin=N'Harrow', abac_name=N'Harrow', display_name=N'Harrow' WHERE id=87876;
UPDATE laus SET name_national=N'Hart', name_latin=N'Hart', abac_name=N'Hart', display_name=N'Hart' WHERE id=87877;
UPDATE laus SET name_national=N'Hartlepool', name_latin=N'Hartlepool', abac_name=N'Hartlepool', display_name=N'Hartlepool' WHERE id=87878;
UPDATE laus SET name_national=N'Hastings', name_latin=N'Hastings', abac_name=N'Hastings', display_name=N'Hastings' WHERE id=87879;
UPDATE laus SET name_national=N'Havant', name_latin=N'Havant', abac_name=N'Havant', display_name=N'Havant' WHERE id=87880;
UPDATE laus SET name_national=N'Havering', name_latin=N'Havering', abac_name=N'Havering', display_name=N'Havering' WHERE id=87881;
UPDATE laus SET name_national=N'Helensburgh and Lomond', name_latin=N'Helensburgh and Lomond', abac_name=N'Helensburgh and Lomond', display_name=N'Helensburgh and Lomond' WHERE id=87882;
UPDATE laus SET name_national=N'Herefordshire, County of', name_latin=N'Herefordshire, County of', abac_name=N'Herefordshire, County of', display_name=N'Herefordshire, County of' WHERE id=87883;
UPDATE laus SET name_national=N'Hertsmere', name_latin=N'Hertsmere', abac_name=N'Hertsmere', display_name=N'Hertsmere' WHERE id=87884;
UPDATE laus SET name_national=N'High Peak', name_latin=N'High Peak', abac_name=N'High Peak', display_name=N'High Peak' WHERE id=87885;
UPDATE laus SET name_national=N'Hillingdon', name_latin=N'Hillingdon', abac_name=N'Hillingdon', display_name=N'Hillingdon' WHERE id=87886;
UPDATE laus SET name_national=N'Hinckley and Bosworth', name_latin=N'Hinckley and Bosworth', abac_name=N'Hinckley and Bosworth', display_name=N'Hinckley and Bosworth' WHERE id=87887;
UPDATE laus SET name_national=N'Horsham', name_latin=N'Horsham', abac_name=N'Horsham', display_name=N'Horsham' WHERE id=87888;
UPDATE laus SET name_national=N'Hounslow', name_latin=N'Hounslow', abac_name=N'Hounslow', display_name=N'Hounslow' WHERE id=87889;
UPDATE laus SET name_national=N'Huntingdonshire', name_latin=N'Huntingdonshire', abac_name=N'Huntingdonshire', display_name=N'Huntingdonshire' WHERE id=87890;
UPDATE laus SET name_national=N'Hyndburn', name_latin=N'Hyndburn', abac_name=N'Hyndburn', display_name=N'Hyndburn' WHERE id=87891;
UPDATE laus SET name_national=N'Inverclyde', name_latin=N'Inverclyde', abac_name=N'Inverclyde', display_name=N'Inverclyde' WHERE id=87892;
UPDATE laus SET name_national=N'Inverness and Nairn', name_latin=N'Inverness and Nairn', abac_name=N'Inverness and Nairn', display_name=N'Inverness and Nairn' WHERE id=87893;
UPDATE laus SET name_national=N'Ipswich', name_latin=N'Ipswich', abac_name=N'Ipswich', display_name=N'Ipswich' WHERE id=87894;
UPDATE laus SET name_national=N'Isle of Anglesey - Ynys Môn', name_latin=N'Isle of Anglesey - Ynys Môn', abac_name=N'Isle of Anglesey - Ynys Mon', display_name=N'Isle of Anglesey - Ynys Môn' WHERE id=87895;
UPDATE laus SET name_national=N'Isle of Wight', name_latin=N'Isle of Wight', abac_name=N'Isle of Wight', display_name=N'Isle of Wight' WHERE id=87896;
UPDATE laus SET name_national=N'Isles of Scilly', name_latin=N'Isles of Scilly', abac_name=N'Isles of Scilly', display_name=N'Isles of Scilly' WHERE id=87897;
UPDATE laus SET name_national=N'Islington', name_latin=N'Islington', abac_name=N'Islington', display_name=N'Islington' WHERE id=87898;
UPDATE laus SET name_national=N'Kensington and Chelsea', name_latin=N'Kensington and Chelsea', abac_name=N'Kensington and Chelsea', display_name=N'Kensington and Chelsea' WHERE id=87899;
UPDATE laus SET name_national=N'Kettering', name_latin=N'Kettering', abac_name=N'Kettering', display_name=N'Kettering' WHERE id=87900;
UPDATE laus SET name_national=N'King''s Lynn and West Norfolk', name_latin=N'King''s Lynn and West Norfolk', abac_name=N'King''s Lynn and West Norfolk', display_name=N'King''s Lynn and West Norfolk' WHERE id=87901;
UPDATE laus SET name_national=N'Kingston upon Hull, City of', name_latin=N'Kingston upon Hull, City of', abac_name=N'Kingston upon Hull, City of', display_name=N'Kingston upon Hull, City of' WHERE id=87902;
UPDATE laus SET name_national=N'Kingston upon Thames', name_latin=N'Kingston upon Thames', abac_name=N'Kingston upon Thames', display_name=N'Kingston upon Thames' WHERE id=87903;
UPDATE laus SET name_national=N'Kirklees', name_latin=N'Kirklees', abac_name=N'Kirklees', display_name=N'Kirklees' WHERE id=87904;
UPDATE laus SET name_national=N'Knowsley', name_latin=N'Knowsley', abac_name=N'Knowsley', display_name=N'Knowsley' WHERE id=87905;
UPDATE laus SET name_national=N'Lambeth', name_latin=N'Lambeth', abac_name=N'Lambeth', display_name=N'Lambeth' WHERE id=87906;
UPDATE laus SET name_national=N'Lancaster', name_latin=N'Lancaster', abac_name=N'Lancaster', display_name=N'Lancaster' WHERE id=87907;
UPDATE laus SET name_national=N'Leeds', name_latin=N'Leeds', abac_name=N'Leeds', display_name=N'Leeds' WHERE id=87908;
UPDATE laus SET name_national=N'Leicester', name_latin=N'Leicester', abac_name=N'Leicester', display_name=N'Leicester' WHERE id=87909;
UPDATE laus SET name_national=N'Lewes', name_latin=N'Lewes', abac_name=N'Lewes', display_name=N'Lewes' WHERE id=87910;
UPDATE laus SET name_national=N'Lewisham', name_latin=N'Lewisham', abac_name=N'Lewisham', display_name=N'Lewisham' WHERE id=87911;
UPDATE laus SET name_national=N'Lichfield', name_latin=N'Lichfield', abac_name=N'Lichfield', display_name=N'Lichfield' WHERE id=87912;
UPDATE laus SET name_national=N'Lincoln', name_latin=N'Lincoln', abac_name=N'Lincoln', display_name=N'Lincoln' WHERE id=87913;
UPDATE laus SET name_national=N'Lisburn and Castlereagh', name_latin=N'Lisburn and Castlereagh', abac_name=N'Lisburn and Castlereagh', display_name=N'Lisburn and Castlereagh' WHERE id=87914;
UPDATE laus SET name_national=N'Liverpool', name_latin=N'Liverpool', abac_name=N'Liverpool', display_name=N'Liverpool' WHERE id=87915;
UPDATE laus SET name_national=N'Lochaber', name_latin=N'Lochaber', abac_name=N'Lochaber', display_name=N'Lochaber' WHERE id=87916;
UPDATE laus SET name_national=N'Luton', name_latin=N'Luton', abac_name=N'Luton', display_name=N'Luton' WHERE id=87917;
UPDATE laus SET name_national=N'Maidstone', name_latin=N'Maidstone', abac_name=N'Maidstone', display_name=N'Maidstone' WHERE id=87918;
UPDATE laus SET name_national=N'Maldon', name_latin=N'Maldon', abac_name=N'Maldon', display_name=N'Maldon' WHERE id=87919;
UPDATE laus SET name_national=N'Malvern Hills', name_latin=N'Malvern Hills', abac_name=N'Malvern Hills', display_name=N'Malvern Hills' WHERE id=87920;
UPDATE laus SET name_national=N'Manchester', name_latin=N'Manchester', abac_name=N'Manchester', display_name=N'Manchester' WHERE id=87921;
UPDATE laus SET name_national=N'Mansfield', name_latin=N'Mansfield', abac_name=N'Mansfield', display_name=N'Mansfield' WHERE id=87922;
UPDATE laus SET name_national=N'Medway', name_latin=N'Medway', abac_name=N'Medway', display_name=N'Medway' WHERE id=87923;
UPDATE laus SET name_national=N'Melton', name_latin=N'Melton', abac_name=N'Melton', display_name=N'Melton' WHERE id=87924;
UPDATE laus SET name_national=N'Mendip', name_latin=N'Mendip', abac_name=N'Mendip', display_name=N'Mendip' WHERE id=87925;
UPDATE laus SET name_national=N'Merthyr Tydfil - Merthyr Tudful', name_latin=N'Merthyr Tydfil - Merthyr Tudful', abac_name=N'Merthyr Tydfil - Merthyr Tudful', display_name=N'Merthyr Tydfil - Merthyr Tudful' WHERE id=87926;
UPDATE laus SET name_national=N'Merton', name_latin=N'Merton', abac_name=N'Merton', display_name=N'Merton' WHERE id=87927;
UPDATE laus SET name_national=N'Mid and East Antrim', name_latin=N'Mid and East Antrim', abac_name=N'Mid and East Antrim', display_name=N'Mid and East Antrim' WHERE id=87928;
UPDATE laus SET name_national=N'Mid Devon', name_latin=N'Mid Devon', abac_name=N'Mid Devon', display_name=N'Mid Devon' WHERE id=87929;
UPDATE laus SET name_national=N'Mid Suffolk', name_latin=N'Mid Suffolk', abac_name=N'Mid Suffolk', display_name=N'Mid Suffolk' WHERE id=87930;
UPDATE laus SET name_national=N'Mid Sussex', name_latin=N'Mid Sussex', abac_name=N'Mid Sussex', display_name=N'Mid Sussex' WHERE id=87931;
UPDATE laus SET name_national=N'Mid Ulster', name_latin=N'Mid Ulster', abac_name=N'Mid Ulster', display_name=N'Mid Ulster' WHERE id=87932;
UPDATE laus SET name_national=N'Middlesbrough', name_latin=N'Middlesbrough', abac_name=N'Middlesbrough', display_name=N'Middlesbrough' WHERE id=87933;
UPDATE laus SET name_national=N'Midlothian', name_latin=N'Midlothian', abac_name=N'Midlothian', display_name=N'Midlothian' WHERE id=87934;
UPDATE laus SET name_national=N'Milton Keynes', name_latin=N'Milton Keynes', abac_name=N'Milton Keynes', display_name=N'Milton Keynes' WHERE id=87935;
UPDATE laus SET name_national=N'Mole Valley', name_latin=N'Mole Valley', abac_name=N'Mole Valley', display_name=N'Mole Valley' WHERE id=87936;
UPDATE laus SET name_national=N'Monmouthshire - Sir Fynwy', name_latin=N'Monmouthshire - Sir Fynwy', abac_name=N'Monmouthshire - Sir Fynwy', display_name=N'Monmouthshire - Sir Fynwy' WHERE id=87937;
UPDATE laus SET name_national=N'Na h-Eileanan Siar', name_latin=N'Na h-Eileanan Siar', abac_name=N'Na h-Eileanan Siar', display_name=N'Na h-Eileanan Siar' WHERE id=87938;
UPDATE laus SET name_national=N'Neath Port Talbot - Castell-nedd Port Talbot', name_latin=N'Neath Port Talbot - Castell-nedd Port Talbot', abac_name=N'Neath Port Talbot - Castell-nedd Port Talbot', display_name=N'Neath Port Talbot - Castell-nedd Port Talbot' WHERE id=87939;
UPDATE laus SET name_national=N'New Forest', name_latin=N'New Forest', abac_name=N'New Forest', display_name=N'New Forest' WHERE id=87940;
UPDATE laus SET name_national=N'Newark and Sherwood', name_latin=N'Newark and Sherwood', abac_name=N'Newark and Sherwood', display_name=N'Newark and Sherwood' WHERE id=87941;
UPDATE laus SET name_national=N'Newcastle upon Tyne', name_latin=N'Newcastle upon Tyne', abac_name=N'Newcastle upon Tyne', display_name=N'Newcastle upon Tyne' WHERE id=87942;
UPDATE laus SET name_national=N'Newcastle-under-Lyme', name_latin=N'Newcastle-under-Lyme', abac_name=N'Newcastle-under-Lyme', display_name=N'Newcastle-under-Lyme' WHERE id=87943;
UPDATE laus SET name_national=N'Newham', name_latin=N'Newham', abac_name=N'Newham', display_name=N'Newham' WHERE id=87944;
UPDATE laus SET name_national=N'Newport - Casnewydd', name_latin=N'Newport - Casnewydd', abac_name=N'Newport - Casnewydd', display_name=N'Newport - Casnewydd' WHERE id=87945;
UPDATE laus SET name_national=N'Newry, Mourne and Down', name_latin=N'Newry, Mourne and Down', abac_name=N'Newry, Mourne and Down', display_name=N'Newry, Mourne and Down' WHERE id=87946;
UPDATE laus SET name_national=N'North Ayrshire mainland', name_latin=N'North Ayrshire mainland', abac_name=N'North Ayrshire mainland', display_name=N'North Ayrshire mainland' WHERE id=87947;
UPDATE laus SET name_national=N'North Devon', name_latin=N'North Devon', abac_name=N'North Devon', display_name=N'North Devon' WHERE id=87948;
UPDATE laus SET name_national=N'North Dorset', name_latin=N'North Dorset', abac_name=N'North Dorset', display_name=N'North Dorset' WHERE id=87949;
UPDATE laus SET name_national=N'North East Derbyshire', name_latin=N'North East Derbyshire', abac_name=N'North East Derbyshire', display_name=N'North East Derbyshire' WHERE id=87950;
UPDATE laus SET name_national=N'North East Lincolnshire', name_latin=N'North East Lincolnshire', abac_name=N'North East Lincolnshire', display_name=N'North East Lincolnshire' WHERE id=87951;
UPDATE laus SET name_national=N'North East Moray', name_latin=N'North East Moray', abac_name=N'North East Moray', display_name=N'North East Moray' WHERE id=87952;
UPDATE laus SET name_national=N'North Hertfordshire', name_latin=N'North Hertfordshire', abac_name=N'North Hertfordshire', display_name=N'North Hertfordshire' WHERE id=87953;
UPDATE laus SET name_national=N'North Kesteven', name_latin=N'North Kesteven', abac_name=N'North Kesteven', display_name=N'North Kesteven' WHERE id=87954;
UPDATE laus SET name_national=N'North Lanarkshire', name_latin=N'North Lanarkshire', abac_name=N'North Lanarkshire', display_name=N'North Lanarkshire' WHERE id=87955;
UPDATE laus SET name_national=N'North Lincolnshire', name_latin=N'North Lincolnshire', abac_name=N'North Lincolnshire', display_name=N'North Lincolnshire' WHERE id=87956;
UPDATE laus SET name_national=N'North Norfolk', name_latin=N'North Norfolk', abac_name=N'North Norfolk', display_name=N'North Norfolk' WHERE id=87957;
UPDATE laus SET name_national=N'North Somerset', name_latin=N'North Somerset', abac_name=N'North Somerset', display_name=N'North Somerset' WHERE id=87958;
UPDATE laus SET name_national=N'North Tyneside', name_latin=N'North Tyneside', abac_name=N'North Tyneside', display_name=N'North Tyneside' WHERE id=87959;
UPDATE laus SET name_national=N'North Warwickshire', name_latin=N'North Warwickshire', abac_name=N'North Warwickshire', display_name=N'North Warwickshire' WHERE id=87960;
UPDATE laus SET name_national=N'North West Leicestershire', name_latin=N'North West Leicestershire', abac_name=N'North West Leicestershire', display_name=N'North West Leicestershire' WHERE id=87961;
UPDATE laus SET name_national=N'Northampton', name_latin=N'Northampton', abac_name=N'Northampton', display_name=N'Northampton' WHERE id=87962;
UPDATE laus SET name_national=N'Northumberland', name_latin=N'Northumberland', abac_name=N'Northumberland', display_name=N'Northumberland' WHERE id=87963;
UPDATE laus SET name_national=N'Norwich', name_latin=N'Norwich', abac_name=N'Norwich', display_name=N'Norwich' WHERE id=87964;
UPDATE laus SET name_national=N'Nottingham', name_latin=N'Nottingham', abac_name=N'Nottingham', display_name=N'Nottingham' WHERE id=87965;
UPDATE laus SET name_national=N'Nuneaton and Bedworth', name_latin=N'Nuneaton and Bedworth', abac_name=N'Nuneaton and Bedworth', display_name=N'Nuneaton and Bedworth' WHERE id=87966;
UPDATE laus SET name_national=N'Oadby and Wigston', name_latin=N'Oadby and Wigston', abac_name=N'Oadby and Wigston', display_name=N'Oadby and Wigston' WHERE id=87967;
UPDATE laus SET name_national=N'Oldham', name_latin=N'Oldham', abac_name=N'Oldham', display_name=N'Oldham' WHERE id=87968;
UPDATE laus SET name_national=N'Orkney Islands', name_latin=N'Orkney Islands', abac_name=N'Orkney Islands', display_name=N'Orkney Islands' WHERE id=87969;
UPDATE laus SET name_national=N'Oxford', name_latin=N'Oxford', abac_name=N'Oxford', display_name=N'Oxford' WHERE id=87970;
UPDATE laus SET name_national=N'Pembrokeshire - Sir Benfro', name_latin=N'Pembrokeshire - Sir Benfro', abac_name=N'Pembrokeshire - Sir Benfro', display_name=N'Pembrokeshire - Sir Benfro' WHERE id=87971;
UPDATE laus SET name_national=N'Pendle', name_latin=N'Pendle', abac_name=N'Pendle', display_name=N'Pendle' WHERE id=87972;
UPDATE laus SET name_national=N'Perth and Kinross', name_latin=N'Perth and Kinross', abac_name=N'Perth and Kinross', display_name=N'Perth and Kinross' WHERE id=87973;
UPDATE laus SET name_national=N'Peterborough', name_latin=N'Peterborough', abac_name=N'Peterborough', display_name=N'Peterborough' WHERE id=87974;
UPDATE laus SET name_national=N'Plymouth', name_latin=N'Plymouth', abac_name=N'Plymouth', display_name=N'Plymouth' WHERE id=87975;
UPDATE laus SET name_national=N'Poole', name_latin=N'Poole', abac_name=N'Poole', display_name=N'Poole' WHERE id=87976;
UPDATE laus SET name_national=N'Portsmouth', name_latin=N'Portsmouth', abac_name=N'Portsmouth', display_name=N'Portsmouth' WHERE id=87977;
UPDATE laus SET name_national=N'Powys - Powys', name_latin=N'Powys - Powys', abac_name=N'Powys - Powys', display_name=N'Powys - Powys' WHERE id=87978;
UPDATE laus SET name_national=N'Preston', name_latin=N'Preston', abac_name=N'Preston', display_name=N'Preston' WHERE id=87979;
UPDATE laus SET name_national=N'Purbeck', name_latin=N'Purbeck', abac_name=N'Purbeck', display_name=N'Purbeck' WHERE id=87980;
UPDATE laus SET name_national=N'Reading', name_latin=N'Reading', abac_name=N'Reading', display_name=N'Reading' WHERE id=87981;
UPDATE laus SET name_national=N'Redbridge', name_latin=N'Redbridge', abac_name=N'Redbridge', display_name=N'Redbridge' WHERE id=87982;
UPDATE laus SET name_national=N'Redcar and Cleveland', name_latin=N'Redcar and Cleveland', abac_name=N'Redcar and Cleveland', display_name=N'Redcar and Cleveland' WHERE id=87983;
UPDATE laus SET name_national=N'Redditch', name_latin=N'Redditch', abac_name=N'Redditch', display_name=N'Redditch' WHERE id=87984;
UPDATE laus SET name_national=N'Reigate and Banstead', name_latin=N'Reigate and Banstead', abac_name=N'Reigate and Banstead', display_name=N'Reigate and Banstead' WHERE id=87985;
UPDATE laus SET name_national=N'Renfrewshire', name_latin=N'Renfrewshire', abac_name=N'Renfrewshire', display_name=N'Renfrewshire' WHERE id=87986;
UPDATE laus SET name_national=N'Rhondda Cynon Taf - Rhondda Cynon Taf', name_latin=N'Rhondda Cynon Taf - Rhondda Cynon Taf', abac_name=N'Rhondda Cynon Taf - Rhondda Cynon Taf', display_name=N'Rhondda Cynon Taf - Rhondda Cynon Taf' WHERE id=87987;
UPDATE laus SET name_national=N'Ribble Valley', name_latin=N'Ribble Valley', abac_name=N'Ribble Valley', display_name=N'Ribble Valley' WHERE id=87988;
UPDATE laus SET name_national=N'Richmond upon Thames', name_latin=N'Richmond upon Thames', abac_name=N'Richmond upon Thames', display_name=N'Richmond upon Thames' WHERE id=87989;
UPDATE laus SET name_national=N'Richmondshire', name_latin=N'Richmondshire', abac_name=N'Richmondshire', display_name=N'Richmondshire' WHERE id=87990;
UPDATE laus SET name_national=N'Rochdale', name_latin=N'Rochdale', abac_name=N'Rochdale', display_name=N'Rochdale' WHERE id=87991;
UPDATE laus SET name_national=N'Rochford', name_latin=N'Rochford', abac_name=N'Rochford', display_name=N'Rochford' WHERE id=87992;
UPDATE laus SET name_national=N'Ross and Cromarty', name_latin=N'Ross and Cromarty', abac_name=N'Ross and Cromarty', display_name=N'Ross and Cromarty' WHERE id=87993;
UPDATE laus SET name_national=N'Rossendale', name_latin=N'Rossendale', abac_name=N'Rossendale', display_name=N'Rossendale' WHERE id=87994;
UPDATE laus SET name_national=N'Rother', name_latin=N'Rother', abac_name=N'Rother', display_name=N'Rother' WHERE id=87995;
UPDATE laus SET name_national=N'Rotherham', name_latin=N'Rotherham', abac_name=N'Rotherham', display_name=N'Rotherham' WHERE id=87996;
UPDATE laus SET name_national=N'Rugby', name_latin=N'Rugby', abac_name=N'Rugby', display_name=N'Rugby' WHERE id=87997;
UPDATE laus SET name_national=N'Runnymede', name_latin=N'Runnymede', abac_name=N'Runnymede', display_name=N'Runnymede' WHERE id=87998;
UPDATE laus SET name_national=N'Rushcliffe', name_latin=N'Rushcliffe', abac_name=N'Rushcliffe', display_name=N'Rushcliffe' WHERE id=87999;
UPDATE laus SET name_national=N'Rushmoor', name_latin=N'Rushmoor', abac_name=N'Rushmoor', display_name=N'Rushmoor' WHERE id=88000;
UPDATE laus SET name_national=N'Rutland', name_latin=N'Rutland', abac_name=N'Rutland', display_name=N'Rutland' WHERE id=88001;
UPDATE laus SET name_national=N'Ryedale', name_latin=N'Ryedale', abac_name=N'Ryedale', display_name=N'Ryedale' WHERE id=88002;
UPDATE laus SET name_national=N'Salford', name_latin=N'Salford', abac_name=N'Salford', display_name=N'Salford' WHERE id=88003;
UPDATE laus SET name_national=N'Sandwell', name_latin=N'Sandwell', abac_name=N'Sandwell', display_name=N'Sandwell' WHERE id=88004;
UPDATE laus SET name_national=N'Scarborough', name_latin=N'Scarborough', abac_name=N'Scarborough', display_name=N'Scarborough' WHERE id=88005;
UPDATE laus SET name_national=N'Scottish Borders', name_latin=N'Scottish Borders', abac_name=N'Scottish Borders', display_name=N'Scottish Borders' WHERE id=88006;
UPDATE laus SET name_national=N'Sedgemoor', name_latin=N'Sedgemoor', abac_name=N'Sedgemoor', display_name=N'Sedgemoor' WHERE id=88007;
UPDATE laus SET name_national=N'Sefton', name_latin=N'Sefton', abac_name=N'Sefton', display_name=N'Sefton' WHERE id=88008;
UPDATE laus SET name_national=N'Selby', name_latin=N'Selby', abac_name=N'Selby', display_name=N'Selby' WHERE id=88009;
UPDATE laus SET name_national=N'Sevenoaks', name_latin=N'Sevenoaks', abac_name=N'Sevenoaks', display_name=N'Sevenoaks' WHERE id=88010;
UPDATE laus SET name_national=N'Sheffield', name_latin=N'Sheffield', abac_name=N'Sheffield', display_name=N'Sheffield' WHERE id=88011;
UPDATE laus SET name_national=N'Shepway', name_latin=N'Shepway', abac_name=N'Shepway', display_name=N'Shepway' WHERE id=88012;
UPDATE laus SET name_national=N'Shetland Islands', name_latin=N'Shetland Islands', abac_name=N'Shetland Islands', display_name=N'Shetland Islands' WHERE id=88013;
UPDATE laus SET name_national=N'Shropshire', name_latin=N'Shropshire', abac_name=N'Shropshire', display_name=N'Shropshire' WHERE id=88014;
UPDATE laus SET name_national=N'Skye and Lochalsh', name_latin=N'Skye and Lochalsh', abac_name=N'Skye and Lochalsh', display_name=N'Skye and Lochalsh' WHERE id=88015;
UPDATE laus SET name_national=N'Slough', name_latin=N'Slough', abac_name=N'Slough', display_name=N'Slough' WHERE id=88016;
UPDATE laus SET name_national=N'Solihull', name_latin=N'Solihull', abac_name=N'Solihull', display_name=N'Solihull' WHERE id=88017;
UPDATE laus SET name_national=N'South Ayrshire', name_latin=N'South Ayrshire', abac_name=N'South Ayrshire', display_name=N'South Ayrshire' WHERE id=88018;
UPDATE laus SET name_national=N'South Bucks', name_latin=N'South Bucks', abac_name=N'South Bucks', display_name=N'South Bucks' WHERE id=88019;
UPDATE laus SET name_national=N'South Cambridgeshire', name_latin=N'South Cambridgeshire', abac_name=N'South Cambridgeshire', display_name=N'South Cambridgeshire' WHERE id=88020;
UPDATE laus SET name_national=N'South Derbyshire', name_latin=N'South Derbyshire', abac_name=N'South Derbyshire', display_name=N'South Derbyshire' WHERE id=88021;
UPDATE laus SET name_national=N'South Gloucestershire', name_latin=N'South Gloucestershire', abac_name=N'South Gloucestershire', display_name=N'South Gloucestershire' WHERE id=88022;
UPDATE laus SET name_national=N'South Hams', name_latin=N'South Hams', abac_name=N'South Hams', display_name=N'South Hams' WHERE id=88023;
UPDATE laus SET name_national=N'South Holland', name_latin=N'South Holland', abac_name=N'South Holland', display_name=N'South Holland' WHERE id=88024;
UPDATE laus SET name_national=N'South Kesteven', name_latin=N'South Kesteven', abac_name=N'South Kesteven', display_name=N'South Kesteven' WHERE id=88025;
UPDATE laus SET name_national=N'South Lakeland', name_latin=N'South Lakeland', abac_name=N'South Lakeland', display_name=N'South Lakeland' WHERE id=88026;
UPDATE laus SET name_national=N'South Lanarkshire', name_latin=N'South Lanarkshire', abac_name=N'South Lanarkshire', display_name=N'South Lanarkshire' WHERE id=88027;
UPDATE laus SET name_national=N'South Norfolk', name_latin=N'South Norfolk', abac_name=N'South Norfolk', display_name=N'South Norfolk' WHERE id=88028;
UPDATE laus SET name_national=N'South Northamptonshire', name_latin=N'South Northamptonshire', abac_name=N'South Northamptonshire', display_name=N'South Northamptonshire' WHERE id=88029;
UPDATE laus SET name_national=N'South Oxfordshire', name_latin=N'South Oxfordshire', abac_name=N'South Oxfordshire', display_name=N'South Oxfordshire' WHERE id=88030;
UPDATE laus SET name_national=N'South Ribble', name_latin=N'South Ribble', abac_name=N'South Ribble', display_name=N'South Ribble' WHERE id=88031;
UPDATE laus SET name_national=N'South Somerset', name_latin=N'South Somerset', abac_name=N'South Somerset', display_name=N'South Somerset' WHERE id=88032;
UPDATE laus SET name_national=N'South Staffordshire', name_latin=N'South Staffordshire', abac_name=N'South Staffordshire', display_name=N'South Staffordshire' WHERE id=88033;
UPDATE laus SET name_national=N'South Tyneside', name_latin=N'South Tyneside', abac_name=N'South Tyneside', display_name=N'South Tyneside' WHERE id=88034;
UPDATE laus SET name_national=N'Southampton', name_latin=N'Southampton', abac_name=N'Southampton', display_name=N'Southampton' WHERE id=88035;
UPDATE laus SET name_national=N'Southend-on-Sea', name_latin=N'Southend-on-Sea', abac_name=N'Southend-on-Sea', display_name=N'Southend-on-Sea' WHERE id=88036;
UPDATE laus SET name_national=N'Southwark', name_latin=N'Southwark', abac_name=N'Southwark', display_name=N'Southwark' WHERE id=88037;
UPDATE laus SET name_national=N'Spelthorne', name_latin=N'Spelthorne', abac_name=N'Spelthorne', display_name=N'Spelthorne' WHERE id=88038;
UPDATE laus SET name_national=N'St Albans', name_latin=N'St Albans', abac_name=N'St Albans', display_name=N'St Albans' WHERE id=88039;
UPDATE laus SET name_national=N'St Edmundsbury', name_latin=N'St Edmundsbury', abac_name=N'St Edmundsbury', display_name=N'St Edmundsbury' WHERE id=88040;
UPDATE laus SET name_national=N'St. Helens', name_latin=N'St. Helens', abac_name=N'St. Helens', display_name=N'St. Helens' WHERE id=88041;
UPDATE laus SET name_national=N'Stafford', name_latin=N'Stafford', abac_name=N'Stafford', display_name=N'Stafford' WHERE id=88042;
UPDATE laus SET name_national=N'Staffordshire Moorlands', name_latin=N'Staffordshire Moorlands', abac_name=N'Staffordshire Moorlands', display_name=N'Staffordshire Moorlands' WHERE id=88043;
UPDATE laus SET name_national=N'Stevenage', name_latin=N'Stevenage', abac_name=N'Stevenage', display_name=N'Stevenage' WHERE id=88044;
UPDATE laus SET name_national=N'Stirling', name_latin=N'Stirling', abac_name=N'Stirling', display_name=N'Stirling' WHERE id=88045;
UPDATE laus SET name_national=N'Stockport', name_latin=N'Stockport', abac_name=N'Stockport', display_name=N'Stockport' WHERE id=88046;
UPDATE laus SET name_national=N'Stockton-on-Tees', name_latin=N'Stockton-on-Tees', abac_name=N'Stockton-on-Tees', display_name=N'Stockton-on-Tees' WHERE id=88047;
UPDATE laus SET name_national=N'Stoke-on-Trent', name_latin=N'Stoke-on-Trent', abac_name=N'Stoke-on-Trent', display_name=N'Stoke-on-Trent' WHERE id=88048;
UPDATE laus SET name_national=N'Stratford-on-Avon', name_latin=N'Stratford-on-Avon', abac_name=N'Stratford-on-Avon', display_name=N'Stratford-on-Avon' WHERE id=88049;
UPDATE laus SET name_national=N'Stroud', name_latin=N'Stroud', abac_name=N'Stroud', display_name=N'Stroud' WHERE id=88050;
UPDATE laus SET name_national=N'Suffolk Coastal', name_latin=N'Suffolk Coastal', abac_name=N'Suffolk Coastal', display_name=N'Suffolk Coastal' WHERE id=88051;
UPDATE laus SET name_national=N'Sunderland', name_latin=N'Sunderland', abac_name=N'Sunderland', display_name=N'Sunderland' WHERE id=88052;
UPDATE laus SET name_national=N'Surrey Heath', name_latin=N'Surrey Heath', abac_name=N'Surrey Heath', display_name=N'Surrey Heath' WHERE id=88053;
UPDATE laus SET name_national=N'Sutton', name_latin=N'Sutton', abac_name=N'Sutton', display_name=N'Sutton' WHERE id=88054;
UPDATE laus SET name_national=N'Swale', name_latin=N'Swale', abac_name=N'Swale', display_name=N'Swale' WHERE id=88055;
UPDATE laus SET name_national=N'Swansea - Abertawe', name_latin=N'Swansea - Abertawe', abac_name=N'Swansea - Abertawe', display_name=N'Swansea - Abertawe' WHERE id=88056;
UPDATE laus SET name_national=N'Swindon', name_latin=N'Swindon', abac_name=N'Swindon', display_name=N'Swindon' WHERE id=88057;
UPDATE laus SET name_national=N'Tameside', name_latin=N'Tameside', abac_name=N'Tameside', display_name=N'Tameside' WHERE id=88058;
UPDATE laus SET name_national=N'Tamworth', name_latin=N'Tamworth', abac_name=N'Tamworth', display_name=N'Tamworth' WHERE id=88059;
UPDATE laus SET name_national=N'Tandridge', name_latin=N'Tandridge', abac_name=N'Tandridge', display_name=N'Tandridge' WHERE id=88060;
UPDATE laus SET name_national=N'Taunton Deane', name_latin=N'Taunton Deane', abac_name=N'Taunton Deane', display_name=N'Taunton Deane' WHERE id=88061;
UPDATE laus SET name_national=N'Teignbridge', name_latin=N'Teignbridge', abac_name=N'Teignbridge', display_name=N'Teignbridge' WHERE id=88062;
UPDATE laus SET name_national=N'Telford and Wrekin', name_latin=N'Telford and Wrekin', abac_name=N'Telford and Wrekin', display_name=N'Telford and Wrekin' WHERE id=88063;
UPDATE laus SET name_national=N'Tendring', name_latin=N'Tendring', abac_name=N'Tendring', display_name=N'Tendring' WHERE id=88064;
UPDATE laus SET name_national=N'Test Valley', name_latin=N'Test Valley', abac_name=N'Test Valley', display_name=N'Test Valley' WHERE id=88065;
UPDATE laus SET name_national=N'Tewkesbury', name_latin=N'Tewkesbury', abac_name=N'Tewkesbury', display_name=N'Tewkesbury' WHERE id=88066;
UPDATE laus SET name_national=N'Thanet', name_latin=N'Thanet', abac_name=N'Thanet', display_name=N'Thanet' WHERE id=88067;
UPDATE laus SET name_national=N'Three Rivers', name_latin=N'Three Rivers', abac_name=N'Three Rivers', display_name=N'Three Rivers' WHERE id=88068;
UPDATE laus SET name_national=N'Thurrock', name_latin=N'Thurrock', abac_name=N'Thurrock', display_name=N'Thurrock' WHERE id=88069;
UPDATE laus SET name_national=N'Tonbridge and Malling', name_latin=N'Tonbridge and Malling', abac_name=N'Tonbridge and Malling', display_name=N'Tonbridge and Malling' WHERE id=88070;
UPDATE laus SET name_national=N'Torbay', name_latin=N'Torbay', abac_name=N'Torbay', display_name=N'Torbay' WHERE id=88071;
UPDATE laus SET name_national=N'Torfaen - Torfaen', name_latin=N'Torfaen - Torfaen', abac_name=N'Torfaen - Torfaen', display_name=N'Torfaen - Torfaen' WHERE id=88072;
UPDATE laus SET name_national=N'Torridge', name_latin=N'Torridge', abac_name=N'Torridge', display_name=N'Torridge' WHERE id=88073;
UPDATE laus SET name_national=N'Tower Hamlets', name_latin=N'Tower Hamlets', abac_name=N'Tower Hamlets', display_name=N'Tower Hamlets' WHERE id=88074;
UPDATE laus SET name_national=N'Trafford', name_latin=N'Trafford', abac_name=N'Trafford', display_name=N'Trafford' WHERE id=88075;
UPDATE laus SET name_national=N'Tunbridge Wells', name_latin=N'Tunbridge Wells', abac_name=N'Tunbridge Wells', display_name=N'Tunbridge Wells' WHERE id=88076;
UPDATE laus SET name_national=N'Uttlesford', name_latin=N'Uttlesford', abac_name=N'Uttlesford', display_name=N'Uttlesford' WHERE id=88077;
UPDATE laus SET name_national=N'Vale of Glamorgan - Bro Morgannwg', name_latin=N'Vale of Glamorgan - Bro Morgannwg', abac_name=N'Vale of Glamorgan - Bro Morgannwg', display_name=N'Vale of Glamorgan - Bro Morgannwg' WHERE id=88078;
UPDATE laus SET name_national=N'Vale of White Horse', name_latin=N'Vale of White Horse', abac_name=N'Vale of White Horse', display_name=N'Vale of White Horse' WHERE id=88079;
UPDATE laus SET name_national=N'Wakefield', name_latin=N'Wakefield', abac_name=N'Wakefield', display_name=N'Wakefield' WHERE id=88080;
UPDATE laus SET name_national=N'Walsall', name_latin=N'Walsall', abac_name=N'Walsall', display_name=N'Walsall' WHERE id=88081;
UPDATE laus SET name_national=N'Waltham Forest', name_latin=N'Waltham Forest', abac_name=N'Waltham Forest', display_name=N'Waltham Forest' WHERE id=88082;
UPDATE laus SET name_national=N'Wandsworth', name_latin=N'Wandsworth', abac_name=N'Wandsworth', display_name=N'Wandsworth' WHERE id=88083;
UPDATE laus SET name_national=N'Warrington', name_latin=N'Warrington', abac_name=N'Warrington', display_name=N'Warrington' WHERE id=88084;
UPDATE laus SET name_national=N'Warwick', name_latin=N'Warwick', abac_name=N'Warwick', display_name=N'Warwick' WHERE id=88085;
UPDATE laus SET name_national=N'Watford', name_latin=N'Watford', abac_name=N'Watford', display_name=N'Watford' WHERE id=88086;
UPDATE laus SET name_national=N'Waveney', name_latin=N'Waveney', abac_name=N'Waveney', display_name=N'Waveney' WHERE id=88087;
UPDATE laus SET name_national=N'Waverley', name_latin=N'Waverley', abac_name=N'Waverley', display_name=N'Waverley' WHERE id=88088;
UPDATE laus SET name_national=N'Wealden', name_latin=N'Wealden', abac_name=N'Wealden', display_name=N'Wealden' WHERE id=88089;
UPDATE laus SET name_national=N'Wellingborough', name_latin=N'Wellingborough', abac_name=N'Wellingborough', display_name=N'Wellingborough' WHERE id=88090;
UPDATE laus SET name_national=N'Welwyn Hatfield', name_latin=N'Welwyn Hatfield', abac_name=N'Welwyn Hatfield', display_name=N'Welwyn Hatfield' WHERE id=88091;
UPDATE laus SET name_national=N'West Berkshire', name_latin=N'West Berkshire', abac_name=N'West Berkshire', display_name=N'West Berkshire' WHERE id=88092;
UPDATE laus SET name_national=N'West Devon', name_latin=N'West Devon', abac_name=N'West Devon', display_name=N'West Devon' WHERE id=88093;
UPDATE laus SET name_national=N'West Dorset', name_latin=N'West Dorset', abac_name=N'West Dorset', display_name=N'West Dorset' WHERE id=88094;
UPDATE laus SET name_national=N'West Dunbartonshire', name_latin=N'West Dunbartonshire', abac_name=N'West Dunbartonshire', display_name=N'West Dunbartonshire' WHERE id=88095;
UPDATE laus SET name_national=N'West Lancashire', name_latin=N'West Lancashire', abac_name=N'West Lancashire', display_name=N'West Lancashire' WHERE id=88096;
UPDATE laus SET name_national=N'West Lindsey', name_latin=N'West Lindsey', abac_name=N'West Lindsey', display_name=N'West Lindsey' WHERE id=88097;
UPDATE laus SET name_national=N'West Lothian', name_latin=N'West Lothian', abac_name=N'West Lothian', display_name=N'West Lothian' WHERE id=88098;
UPDATE laus SET name_national=N'West Moray', name_latin=N'West Moray', abac_name=N'West Moray', display_name=N'West Moray' WHERE id=88099;
UPDATE laus SET name_national=N'West Oxfordshire', name_latin=N'West Oxfordshire', abac_name=N'West Oxfordshire', display_name=N'West Oxfordshire' WHERE id=88100;
UPDATE laus SET name_national=N'West Somerset', name_latin=N'West Somerset', abac_name=N'West Somerset', display_name=N'West Somerset' WHERE id=88101;
UPDATE laus SET name_national=N'Westminster', name_latin=N'Westminster', abac_name=N'Westminster', display_name=N'Westminster' WHERE id=88102;
UPDATE laus SET name_national=N'Weymouth and Portland', name_latin=N'Weymouth and Portland', abac_name=N'Weymouth and Portland', display_name=N'Weymouth and Portland' WHERE id=88103;
UPDATE laus SET name_national=N'Wigan', name_latin=N'Wigan', abac_name=N'Wigan', display_name=N'Wigan' WHERE id=88104;
UPDATE laus SET name_national=N'Wiltshire', name_latin=N'Wiltshire', abac_name=N'Wiltshire', display_name=N'Wiltshire' WHERE id=88105;
UPDATE laus SET name_national=N'Winchester', name_latin=N'Winchester', abac_name=N'Winchester', display_name=N'Winchester' WHERE id=88106;
UPDATE laus SET name_national=N'Windsor and Maidenhead', name_latin=N'Windsor and Maidenhead', abac_name=N'Windsor and Maidenhead', display_name=N'Windsor and Maidenhead' WHERE id=88107;
UPDATE laus SET name_national=N'Wirral', name_latin=N'Wirral', abac_name=N'Wirral', display_name=N'Wirral' WHERE id=88108;
UPDATE laus SET name_national=N'Woking', name_latin=N'Woking', abac_name=N'Woking', display_name=N'Woking' WHERE id=88109;
UPDATE laus SET name_national=N'Wokingham', name_latin=N'Wokingham', abac_name=N'Wokingham', display_name=N'Wokingham' WHERE id=88110;
UPDATE laus SET name_national=N'Wolverhampton', name_latin=N'Wolverhampton', abac_name=N'Wolverhampton', display_name=N'Wolverhampton' WHERE id=88111;
UPDATE laus SET name_national=N'Worcester', name_latin=N'Worcester', abac_name=N'Worcester', display_name=N'Worcester' WHERE id=88112;
UPDATE laus SET name_national=N'Worthing', name_latin=N'Worthing', abac_name=N'Worthing', display_name=N'Worthing' WHERE id=88113;
UPDATE laus SET name_national=N'Wrexham - Wrecsam', name_latin=N'Wrexham - Wrecsam', abac_name=N'Wrexham - Wrecsam', display_name=N'Wrexham - Wrecsam' WHERE id=88114;
UPDATE laus SET name_national=N'Wychavon', name_latin=N'Wychavon', abac_name=N'Wychavon', display_name=N'Wychavon' WHERE id=88115;
UPDATE laus SET name_national=N'Wycombe', name_latin=N'Wycombe', abac_name=N'Wycombe', display_name=N'Wycombe' WHERE id=88116;
UPDATE laus SET name_national=N'Wyre', name_latin=N'Wyre', abac_name=N'Wyre', display_name=N'Wyre' WHERE id=88117;
UPDATE laus SET name_national=N'Wyre Forest', name_latin=N'Wyre Forest', abac_name=N'Wyre Forest', display_name=N'Wyre Forest' WHERE id=88118;
UPDATE laus SET name_national=N'York', name_latin=N'York', abac_name=N'York', display_name=N'York' WHERE id=88119;
--400


--select nuts3, lau1, name_national, name_latin, abac_name, display_name, id 
--from laus where country_code = 'UK' order by name1 asc


--UK
DECLARE  @uk varchar(3);
SET @uk = 'UK';
DECLARE  @countryCode nvarchar(255);
SET @countryCode = (select top 1 _order from nuts where country_code=@uk);

insert into nuts (code, label, level, country_code, _order, sorting) values ('UKM71', 'Angus and Dundee City', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKM72', 'Clackmannanshire and Fife', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKM73', 'East Lothian and Midlothian', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKM75', 'Edinburgh, City of', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKM76', 'Falkirk', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKM77', 'Perth & Kinross and Stirling', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKM78', 'West Lothian', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKM81', 'East Dunbartonshire, West Dunbartonshire and Helensburgh & Lomond', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKM82', 'Glasgow City', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKM83', 'Inverclyde, East Renfrewshire and Renfrewshire', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKM84', 'North Lanarkshire', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKM91', 'Scottish Borders', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKM92', 'Dumfries & Galloway', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKM93', 'East Ayrshire and North Ayrshire mainland', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKM94', 'South Ayrshire', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKM95', 'South Lanarkshire', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKN06', 'Belfast', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKN07', 'Armagh City, Banbridge and Craigavon', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKN08', 'Newry, Mourne and Down', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKN09', 'Ards and North Down ', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKN10', 'Derry City and Strabane', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKN11', 'Mid Ulster', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKN12', 'Causeway Coast and Glens            ', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKN13', 'Antrim and Newtownabbey', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKN14', 'Lisburn and Castlereagh', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKN15', 'Mid and East Antrim', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));
insert into nuts (code, label, level, country_code, _order, sorting) values ('UKN16', 'Fermanagh and Omagh', 3, @uk, @countryCode, (select top 1 sorting +1 from nuts order by sorting desc));

