-- INSERT EL LAUS (added new name fields)
UPDATE laus SET name_national=N'ΑΓΙΟ ΟΡΟΣ (ΑΥΤΟΔΙΟΙΚΗΤΟ)', name_latin=N'Aghio Oros', abac_name=N'AGIO OROS (AUTODIOIKETO)', display_name=N'ΑΓΙΟ ΟΡΟΣ (ΑΥΤΟΔΙΟΙΚΗΤΟ)-Aghio Oros' WHERE id=21383;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΒΔΗΡΩΝ', name_latin=N'Municipality of Avdira', abac_name=N'DEMOS ABDERON', display_name=N'ΔΗΜΟΣ ΑΒΔΗΡΩΝ-Municipality of Avdira' WHERE id=21077;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΓΑΘΟΝΗΣΙΟΥ', name_latin=N'Municipality of Agathonissi', abac_name=N'DEMOS AGAThONESIOU', display_name=N'ΔΗΜΟΣ ΑΓΑΘΟΝΗΣΙΟΥ-Municipality of Agathonissi' WHERE id=21333;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΓΙΑΣ', name_latin=N'Municipality of Aghia', abac_name=N'DEMOS AGIAS', display_name=N'ΔΗΜΟΣ ΑΓΙΑΣ-Municipality of Aghia' WHERE id=21149;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΓΙΑΣ ΒΑΡΒΑΡΑΣ', name_latin=N'Municipality of Aghia Varvara', abac_name=N'DEMOS AGIAS BARBARAS', display_name=N'ΔΗΜΟΣ ΑΓΙΑΣ ΒΑΡΒΑΡΑΣ-Municipality of Aghia Varvara' WHERE id=21271;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΓΙΑΣ ΠΑΡΑΣΚΕΥΗΣ', name_latin=N'Municipality of Aghia Paraskevi', abac_name=N'DEMOS AGIAS PARASKEUES', display_name=N'ΔΗΜΟΣ ΑΓΙΑΣ ΠΑΡΑΣΚΕΥΗΣ-Municipality of Aghia Paraskevi' WHERE id=21259;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΓΙΟΥ ΒΑΣΙΛΕΙΟΥ', name_latin=N'Municipality of Aghios Vassilios', abac_name=N'DEMOS AGIOU BASILEIOU', display_name=N'ΔΗΜΟΣ ΑΓΙΟΥ ΒΑΣΙΛΕΙΟΥ-Municipality of Aghios Vassilios' WHERE id=21372;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΓΙΟΥ ΔΗΜΗΤΡΙΟΥ', name_latin=N'Municipality of Aghios Dimitrios', abac_name=N'DEMOS AGIOU DEMETRIOU', display_name=N'ΔΗΜΟΣ ΑΓΙΟΥ ΔΗΜΗΤΡΙΟΥ-Municipality of Aghios Dimitrios' WHERE id=21278;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΓΙΟΥ ΕΥΣΤΡΑΤΙΟΥ', name_latin=N'Municipality of Aghios Efstratios', abac_name=N'DEMOS AGIOU EUSTRATIOU', display_name=N'ΔΗΜΟΣ ΑΓΙΟΥ ΕΥΣΤΡΑΤΙΟΥ-Municipality of Aghios Efstratios' WHERE id=21320;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΓΙΟΥ ΝΙΚΟΛΑΟΥ', name_latin=N'Municipality of Aghios Nikolaos', abac_name=N'DEMOS AGIOU NIKOLAOU', display_name=N'ΔΗΜΟΣ ΑΓΙΟΥ ΝΙΚΟΛΑΟΥ-Municipality of Aghios Nikolaos' WHERE id=21367;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΓΙΩΝ ΑΝΑΡΓΥΡΩΝ - ΚΑΜΑΤΕΡΟΥ', name_latin=N'Municipality of Aghii Anargyri - Kamatero', abac_name=N'DEMOS AGION ANARGURON - KAMATEROU', display_name=N'ΔΗΜΟΣ ΑΓΙΩΝ ΑΝΑΡΓΥΡΩΝ - ΚΑΜΑΤΕΡΟΥ-Municipality of Aghii Anargyri - Kamatero' WHERE id=21272;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΓΚΙΣΤΡΙΟΥ', name_latin=N'Municipality of Agistri', abac_name=N'DEMOS AGKISTRIOU', display_name=N'ΔΗΜΟΣ ΑΓΚΙΣΤΡΙΟΥ-Municipality of Agistri' WHERE id=21310;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΓΡΑΦΩΝ', name_latin=N'Municipality of Agrafa', abac_name=N'DEMOS AGRAPhON', display_name=N'ΔΗΜΟΣ ΑΓΡΑΦΩΝ-Municipality of Agrafa' WHERE id=21195;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΓΡΙΝΙΟΥ', name_latin=N'Municipality of Agrinio', abac_name=N'DEMOS AGRINIOU', display_name=N'ΔΗΜΟΣ ΑΓΡΙΝΙΟΥ-Municipality of Agrinio' WHERE id=21212;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΘΗΝΑΙΩΝ', name_latin=N'Municipality of Athens', abac_name=N'DEMOS AThENAION', display_name=N'ΔΗΜΟΣ ΑΘΗΝΑΙΩΝ-Municipality of Athens' WHERE id=21250;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΙΓΑΛΕΩ', name_latin=N'Municipality of Aegaleo', abac_name=N'DEMOS AIGALEO', display_name=N'ΔΗΜΟΣ ΑΙΓΑΛΕΩ-Municipality of Aegaleo' WHERE id=21273;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΙΓΙΑΛΕΙΑΣ', name_latin=N'Municipality of Aegialia', abac_name=N'DEMOS AIGIALEIAS', display_name=N'ΔΗΜΟΣ ΑΙΓΙΑΛΕΙΑΣ-Municipality of Aegialia' WHERE id=21206;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΙΓΙΝΑΣ', name_latin=N'Municipality of Aegina', abac_name=N'DEMOS AIGINAS', display_name=N'ΔΗΜΟΣ ΑΙΓΙΝΑΣ-Municipality of Aegina' WHERE id=21311;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΚΤΙΟΥ - ΒΟΝΙΤΣΑΣ', name_latin=N'Municipality of Aktio - Vonitsa', abac_name=N'DEMOS AKTIOU - BONITSAS', display_name=N'ΔΗΜΟΣ ΑΚΤΙΟΥ - ΒΟΝΙΤΣΑΣ-Municipality of Aktio - Vonitsa' WHERE id=21211;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΛΕΞΑΝΔΡΕΙΑΣ', name_latin=N'Municipality of Alexandria', abac_name=N'DEMOS ALEKsANDREIAS', display_name=N'ΔΗΜΟΣ ΑΛΕΞΑΝΔΡΕΙΑΣ-Municipality of Alexandria' WHERE id=21095;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΛΕΞΑΝΔΡΟΥΠΟΛΗΣ', name_latin=N'Municipality of Alexandroupoli', abac_name=N'DEMOS ALEKsANDROUPOLES', display_name=N'ΔΗΜΟΣ ΑΛΕΞΑΝΔΡΟΥΠΟΛΗΣ-Municipality of Alexandroupoli' WHERE id=21067;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΛΙΑΡΤΟΥ-ΘΕΣΠΙΕΩΝ', name_latin=N'Municipality of Aliartos - Thespies', abac_name=N'DEMOS ALIARTOU-ThESPIEON', display_name=N'ΔΗΜΟΣ ΑΛΙΑΡΤΟΥ-ΘΕΣΠΙΕΩΝ-Municipality of Aliartos - Thespies' WHERE id=21181;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΛΙΜΟΥ', name_latin=N'Municipality of Alimos', abac_name=N'DEMOS ALIMOU', display_name=N'ΔΗΜΟΣ ΑΛΙΜΟΥ-Municipality of Alimos' WHERE id=21279;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΛΜΥΡΟΥ', name_latin=N'Municipality of Almyros', abac_name=N'DEMOS ALMUROU', display_name=N'ΔΗΜΟΣ ΑΛΜΥΡΟΥ-Municipality of Almyros' WHERE id=21162;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΛΜΩΠΙΑΣ', name_latin=N'Municipality of Almopia', abac_name=N'DEMOS ALMOPIAS', display_name=N'ΔΗΜΟΣ ΑΛΜΩΠΙΑΣ-Municipality of Almopia' WHERE id=21100;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΛΟΝΝΗΣΟΥ', name_latin=N'Municipality of Alonnissos', abac_name=N'DEMOS ALONNESOU', display_name=N'ΔΗΜΟΣ ΑΛΟΝΝΗΣΟΥ-Municipality of Alonnissos' WHERE id=21167;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΜΑΡΙΟΥ', name_latin=N'Municipality of Amari', abac_name=N'DEMOS AMARIOU', display_name=N'ΔΗΜΟΣ ΑΜΑΡΙΟΥ-Municipality of Amari' WHERE id=21373;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΜΑΡΟΥΣΙΟΥ', name_latin=N'Municipality of Amaroussio', abac_name=N'DEMOS AMAROUSIOU', display_name=N'ΔΗΜΟΣ ΑΜΑΡΟΥΣΙΟΥ-Municipality of Amaroussio' WHERE id=21258;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΜΟΡΓΟΥ', name_latin=N'Municipality of Amorgos', abac_name=N'DEMOS AMORGOU', display_name=N'ΔΗΜΟΣ ΑΜΟΡΓΟΥ-Municipality of Amorgos' WHERE id=21349;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΜΠΕΛΟΚΗΠΩΝ - ΜΕΝΕΜΕΝΗΣ', name_latin=N'Municipality of Abelokipi - Menemeni', abac_name=N'DEMOS AMPELOKEPON - MENEMENES', display_name=N'ΔΗΜΟΣ ΑΜΠΕΛΟΚΗΠΩΝ - ΜΕΝΕΜΕΝΗΣ-Municipality of Abelokipi - Menemeni' WHERE id=21081;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΜΥΝΤΑΙΟΥ', name_latin=N'Municipality of Amynteo', abac_name=N'DEMOS AMUNTAIOU', display_name=N'ΔΗΜΟΣ ΑΜΥΝΤΑΙΟΥ-Municipality of Amynteo' WHERE id=21128;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΜΦΙΚΛΕΙΑΣ - ΕΛΑΤΕΙΑΣ', name_latin=N'Municipality of Amfiklia - Elatia', abac_name=N'DEMOS AMPhIKLEIAS - ELATEIAS', display_name=N'ΔΗΜΟΣ ΑΜΦΙΚΛΕΙΑΣ - ΕΛΑΤΕΙΑΣ-Municipality of Amfiklia - Elatia' WHERE id=21174;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΜΦΙΛΟΧΙΑΣ', name_latin=N'Municipality of Amfilochia', abac_name=N'DEMOS AMPhILOKhIAS', display_name=N'ΔΗΜΟΣ ΑΜΦΙΛΟΧΙΑΣ-Municipality of Amfilochia' WHERE id=21213;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΜΦΙΠΟΛΗΣ', name_latin=N'Municipality of Amfipoli', abac_name=N'DEMOS AMPhIPOLES', display_name=N'ΔΗΜΟΣ ΑΜΦΙΠΟΛΗΣ-Municipality of Amfipoli' WHERE id=21107;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΝΑΤΟΛΙΚΗΣ ΜΑΝΗΣ', name_latin=N'Municipality of Anatoliki Mani', abac_name=N'DEMOS ANATOLIKES MANES', display_name=N'ΔΗΜΟΣ ΑΝΑΤΟΛΙΚΗΣ ΜΑΝΗΣ-Municipality of Anatoliki Mani' WHERE id=21240;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΝΑΦΗΣ', name_latin=N'Municipality of Anafi', abac_name=N'DEMOS ANAPhES', display_name=N'ΔΗΜΟΣ ΑΝΑΦΗΣ-Municipality of Anafi' WHERE id=21328;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΝΔΡΑΒΙΔΑΣ - ΚΥΛΛΗΝΗΣ', name_latin=N'Municipality of Andravida - Kyllini', abac_name=N'DEMOS ANDRABIDAS - KULLENES', display_name=N'ΔΗΜΟΣ ΑΝΔΡΑΒΙΔΑΣ - ΚΥΛΛΗΝΗΣ-Municipality of Andravida - Kyllini' WHERE id=21219;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΝΔΡΙΤΣΑΙΝΑΣ - ΚΡΕΣΤΕΝΩΝ', name_latin=N'Municipality of Andritsena - Krestena', abac_name=N'DEMOS ANDRITSAINAS - KRESTENON', display_name=N'ΔΗΜΟΣ ΑΝΔΡΙΤΣΑΙΝΑΣ - ΚΡΕΣΤΕΝΩΝ-Municipality of Andritsena - Krestena' WHERE id=21220;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΆΝΔΡΟΥ', name_latin=N'Municipality of Andros', abac_name=N'DEMOS ANDROU', display_name=N'ΔΗΜΟΣ ΆΝΔΡΟΥ-Municipality of Andros' WHERE id=21326;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΝΤΙΠΑΡΟΥ', name_latin=N'Municipality of Antiparos', abac_name=N'DEMOS ANTIPAROU', display_name=N'ΔΗΜΟΣ ΑΝΤΙΠΑΡΟΥ-Municipality of Antiparos' WHERE id=21352;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΝΩΓΕΙΩΝ', name_latin=N'Municipality of Anogia', abac_name=N'DEMOS ANOGEION', display_name=N'ΔΗΜΟΣ ΑΝΩΓΕΙΩΝ-Municipality of Anogia' WHERE id=21374;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΠΟΚΟΡΩΝΟΥ', name_latin=N'Municipality of Apokoronas', abac_name=N'DEMOS APOKORONOU', display_name=N'ΔΗΜΟΣ ΑΠΟΚΟΡΩΝΟΥ-Municipality of Apokoronas' WHERE id=21377;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΡΓΙΘΕΑΣ', name_latin=N'Municipality of Argithea', abac_name=N'DEMOS ARGIThEAS', display_name=N'ΔΗΜΟΣ ΑΡΓΙΘΕΑΣ-Municipality of Argithea' WHERE id=21156;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΆΡΓΟΥΣ - ΜΥΚΗΝΩΝ', name_latin=N'Municipality of Argos - Mykines', abac_name=N'DEMOS ARGOUS - MUKENON', display_name=N'ΔΗΜΟΣ ΆΡΓΟΥΣ - ΜΥΚΗΝΩΝ-Municipality of Argos - Mykines' WHERE id=21230;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΡΓΟΥΣ ΟΡΕΣΤΙΚΟΥ', name_latin=N'Municipality of Arghos Orestiko', abac_name=N'DEMOS ARGOUS ORESTIKOU', display_name=N'ΔΗΜΟΣ ΑΡΓΟΥΣ ΟΡΕΣΤΙΚΟΥ-Municipality of Arghos Orestiko' WHERE id=21126;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΡΙΣΤΟΤΕΛΗ', name_latin=N'Municipality of Aristotelis', abac_name=N'DEMOS ARISTOTELE', display_name=N'ΔΗΜΟΣ ΑΡΙΣΤΟΤΕΛΗ-Municipality of Aristotelis' WHERE id=21114;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΡΡΙΑΝΩΝ', name_latin=N'Municipality of Arriana', abac_name=N'DEMOS ARRIANON', display_name=N'ΔΗΜΟΣ ΑΡΡΙΑΝΩΝ-Municipality of Arriana' WHERE id=21059;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΡΤΑΙΩΝ', name_latin=N'Municipality of Arta', abac_name=N'DEMOS ARTAION', display_name=N'ΔΗΜΟΣ ΑΡΤΑΙΩΝ-Municipality of Arta' WHERE id=21138;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΡΧΑΙΑΣ ΟΛΥΜΠΙΑΣ', name_latin=N'Municipality of Olympia', abac_name=N'DEMOS ARKhAIAS OLUMPIAS', display_name=N'ΔΗΜΟΣ ΑΡΧΑΙΑΣ ΟΛΥΜΠΙΑΣ-Municipality of Olympia' WHERE id=21221;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΡΧΑΝΩΝ - ΑΣΤΕΡΟΥΣΙΩΝ', name_latin=N'Municipality of Archanes - Asteroussii', abac_name=N'DEMOS ARKhANON - ASTEROUSION', display_name=N'ΔΗΜΟΣ ΑΡΧΑΝΩΝ - ΑΣΤΕΡΟΥΣΙΩΝ-Municipality of Archanes - Asteroussii' WHERE id=21360;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΣΠΡΟΠΥΡΓΟΥ', name_latin=N'Municipality of Aspropyrgos', abac_name=N'DEMOS ASPROPURGOU', display_name=N'ΔΗΜΟΣ ΑΣΠΡΟΠΥΡΓΟΥ-Municipality of Aspropyrgos' WHERE id=21299;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΣΤΥΠΑΛΑΙΑΣ', name_latin=N'Municipality of Astypalea', abac_name=N'DEMOS ASTUPALAIAS', display_name=N'ΔΗΜΟΣ ΑΣΤΥΠΑΛΑΙΑΣ-Municipality of Astypalea' WHERE id=21334;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΑΧΑΡΝΩΝ', name_latin=N'Municipality of Acharnes', abac_name=N'DEMOS AKhARNON', display_name=N'ΔΗΜΟΣ ΑΧΑΡΝΩΝ-Municipality of Acharnes' WHERE id=21285;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΒΑΡΗΣ - ΒΟΥΛΑΣ - ΒΟΥΛΙΑΓΜΕΝΗΣ', name_latin=N'Municipality of Vari - Voula - Vouliagmeni', abac_name=N'DEMOS BARES - BOULAS - BOULIAGMENES', display_name=N'ΔΗΜΟΣ ΒΑΡΗΣ - ΒΟΥΛΑΣ - ΒΟΥΛΙΑΓΜΕΝΗΣ-Municipality of Vari - Voula - Vouliagmeni' WHERE id=21286;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΒΕΛΟΥ - ΒΟΧΑΣ', name_latin=N'Municipality of Velo - Vocha', abac_name=N'DEMOS BELOU - BOKhAS', display_name=N'ΔΗΜΟΣ ΒΕΛΟΥ - ΒΟΧΑΣ-Municipality of Velo - Vocha' WHERE id=21234;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΒΕΡΟΙΑΣ', name_latin=N'Municipality of Veria', abac_name=N'DEMOS BEROIAS', display_name=N'ΔΗΜΟΣ ΒΕΡΟΙΑΣ-Municipality of Veria' WHERE id=21094;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΒΙΑΝΝΟΥ', name_latin=N'Municipality of Viannos', abac_name=N'DEMOS BIANNOU', display_name=N'ΔΗΜΟΣ ΒΙΑΝΝΟΥ-Municipality of Viannos' WHERE id=21361;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΒΙΣΑΛΤΙΑΣ', name_latin=N'Municipality of Vissaltia', abac_name=N'DEMOS BISALTIAS', display_name=N'ΔΗΜΟΣ ΒΙΣΑΛΤΙΑΣ-Municipality of Vissaltia' WHERE id=21108;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΒΟΪΟΥ', name_latin=N'Municipality of Voio', abac_name=N'DEMOS BOIOU', display_name=N'ΔΗΜΟΣ ΒΟΪΟΥ-Municipality of Voio' WHERE id=21119;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΒΟΛΒΗΣ', name_latin=N'Municipality of Volvi', abac_name=N'DEMOS BOLBES', display_name=N'ΔΗΜΟΣ ΒΟΛΒΗΣ-Municipality of Volvi' WHERE id=21082;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΒΟΛΟΥ', name_latin=N'Municipality of Volos', abac_name=N'DEMOS BOLOU', display_name=N'ΔΗΜΟΣ ΒΟΛΟΥ-Municipality of Volos' WHERE id=21161;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΒΟΡΕΙΑΣ ΚΥΝΟΥΡΙΑΣ', name_latin=N'Municipality of Voria Kynouria', abac_name=N'DEMOS BOREIAS KUNOURIAS', display_name=N'ΔΗΜΟΣ ΒΟΡΕΙΑΣ ΚΥΝΟΥΡΙΑΣ-Municipality of Voria Kynouria' WHERE id=21225;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΒΟΡΕΙΩΝ ΤΖΟΥΜΕΡΚΩΝ', name_latin=N'Municipality of Voria Tzoumerka', abac_name=N'DEMOS BOREION TZOUMERKON', display_name=N'ΔΗΜΟΣ ΒΟΡΕΙΩΝ ΤΖΟΥΜΕΡΚΩΝ-Municipality of Voria Tzoumerka' WHERE id=21131;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΒΡΙΛΗΣΣΙΩΝ', name_latin=N'Municipality of Vrilissia', abac_name=N'DEMOS BRILESSION', display_name=N'ΔΗΜΟΣ ΒΡΙΛΗΣΣΙΩΝ-Municipality of Vrilissia' WHERE id=21260;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΒΥΡΩΝΟΣ', name_latin=N'Municipality of Vyron', abac_name=N'DEMOS BURONOS', display_name=N'ΔΗΜΟΣ ΒΥΡΩΝΟΣ-Municipality of Vyron' WHERE id=21251;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΓΑΛΑΤΣΙΟΥ', name_latin=N'Municipality of Galatsi', abac_name=N'DEMOS GALATSIOU', display_name=N'ΔΗΜΟΣ ΓΑΛΑΤΣΙΟΥ-Municipality of Galatsi' WHERE id=21252;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΓΑΥΔΟΥ', name_latin=N'Municipality of Gavdos', abac_name=N'DEMOS GAUDOU', display_name=N'ΔΗΜΟΣ ΓΑΥΔΟΥ-Municipality of Gavdos' WHERE id=21378;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΓΕΩΡΓΙΟΥ ΚΑΡΑΪΣΚΑΚΗ', name_latin=N'Municipality of Georgios Karaiskakis', abac_name=N'DEMOS GEORGIOU KARAISKAKE', display_name=N'ΔΗΜΟΣ ΓΕΩΡΓΙΟΥ ΚΑΡΑΪΣΚΑΚΗ-Municipality of Georgios Karaiskakis' WHERE id=21139;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΓΛΥΦΑΔΑΣ', name_latin=N'Municipality of Glyfada', abac_name=N'DEMOS GLUPhADAS', display_name=N'ΔΗΜΟΣ ΓΛΥΦΑΔΑΣ-Municipality of Glyfada' WHERE id=21280;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΓΟΡΤΥΝΑΣ', name_latin=N'Municipality of Gortyna', abac_name=N'DEMOS GORTUNAS', display_name=N'ΔΗΜΟΣ ΓΟΡΤΥΝΑΣ-Municipality of Gortyna' WHERE id=21362;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΓΟΡΤΥΝΙΑΣ', name_latin=N'Municipality of Gortynia', abac_name=N'DEMOS GORTUNIAS', display_name=N'ΔΗΜΟΣ ΓΟΡΤΥΝΙΑΣ-Municipality of Gortynia' WHERE id=21226;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΓΡΕΒΕΝΩΝ', name_latin=N'Municipality of Grevena', abac_name=N'DEMOS GREBENON', display_name=N'ΔΗΜΟΣ ΓΡΕΒΕΝΩΝ-Municipality of Grevena' WHERE id=21122;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΔΑΦΝΗΣ - ΥΜΗΤΤΟΥ', name_latin=N'Municipality of Dafni - Ymittos', abac_name=N'DEMOS DAPhNES - UMETTOU', display_name=N'ΔΗΜΟΣ ΔΑΦΝΗΣ - ΥΜΗΤΤΟΥ-Municipality of Dafni - Ymittos' WHERE id=21253;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΔΕΛΤΑ', name_latin=N'Municipality of Delta', abac_name=N'DEMOS DELTA', display_name=N'ΔΗΜΟΣ ΔΕΛΤΑ-Municipality of Delta' WHERE id=21083;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΔΕΛΦΩΝ', name_latin=N'Municipality of Delfi', abac_name=N'DEMOS DELPhON', display_name=N'ΔΗΜΟΣ ΔΕΛΦΩΝ-Municipality of Delfi' WHERE id=21196;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΔΕΣΚΑΤΗΣ', name_latin=N'Municipality of Deskati', abac_name=N'DEMOS DESKATES', display_name=N'ΔΗΜΟΣ ΔΕΣΚΑΤΗΣ-Municipality of Deskati' WHERE id=21123;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΔΙΔΥΜΟΤΕΙΧΟΥ', name_latin=N'Municipality of Didymoticho', abac_name=N'DEMOS DIDUMOTEIKhOU', display_name=N'ΔΗΜΟΣ ΔΙΔΥΜΟΤΕΙΧΟΥ-Municipality of Didymoticho' WHERE id=21068;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΔΙΟΝΥΣΟΥ', name_latin=N'Municipality of Dionyssos', abac_name=N'DEMOS DIONUSOU', display_name=N'ΔΗΜΟΣ ΔΙΟΝΥΣΟΥ-Municipality of Dionyssos' WHERE id=21287;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΔΙΟΥ - ΟΛΥΜΠΟΥ', name_latin=N'Municipality of Dion - Olympos', abac_name=N'DEMOS DIOU - OLUMPOU', display_name=N'ΔΗΜΟΣ ΔΙΟΥ - ΟΛΥΜΠΟΥ-Municipality of Dion - Olympos' WHERE id=21104;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΔΙΡΦΥΩΝ - ΜΕΣΣΑΠΙΩΝ', name_latin=N'Municipality of Dirfys - Messapia', abac_name=N'DEMOS DIRPhUON - MESSAPION', display_name=N'ΔΗΜΟΣ ΔΙΡΦΥΩΝ - ΜΕΣΣΑΠΙΩΝ-Municipality of Dirfys - Messapia' WHERE id=21187;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΔΙΣΤΟΜΟΥ-ΑΡΑΧΟΒΑΣ - ΑΝΤΙΚΥΡΑΣ', name_latin=N'Municipality of Distomo - Arachova - Antikyra', abac_name=N'DEMOS DISTOMOU-ARAKhOBAS - ANTIKURAS', display_name=N'ΔΗΜΟΣ ΔΙΣΤΟΜΟΥ-ΑΡΑΧΟΒΑΣ - ΑΝΤΙΚΥΡΑΣ-Municipality of Distomo - Arachova - Antikyra' WHERE id=21182;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΔΟΜΟΚΟΥ', name_latin=N'Municipality of Domokos', abac_name=N'DEMOS DOMOKOU', display_name=N'ΔΗΜΟΣ ΔΟΜΟΚΟΥ-Municipality of Domokos' WHERE id=21175;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΔΟΞΑΤΟΥ', name_latin=N'Municipality of Doxato', abac_name=N'DEMOS DOKsATOU', display_name=N'ΔΗΜΟΣ ΔΟΞΑΤΟΥ-Municipality of Doxato' WHERE id=21063;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΔΡΑΜΑΣ', name_latin=N'Municipality of Drama', abac_name=N'DEMOS DRAMAS', display_name=N'ΔΗΜΟΣ ΔΡΑΜΑΣ-Municipality of Drama' WHERE id=21062;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΔΥΤΙΚΗΣ ΑΧΑΙΑΣ', name_latin=N'Municipality of Dytiki Achaia', abac_name=N'DEMOS DUTIKES AKhAIAS', display_name=N'ΔΗΜΟΣ ΔΥΤΙΚΗΣ ΑΧΑΙΑΣ-Municipality of Dytiki Achaia' WHERE id=21207;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΔΥΤΙΚΗΣ ΜΑΝΗΣ', name_latin=N'Municipality of Dytiki Mani', abac_name=N'DEMOS DUTIKES MANES', display_name=N'ΔΗΜΟΣ ΔΥΤΙΚΗΣ ΜΑΝΗΣ-Municipality of Dytiki Mani' WHERE id=21245;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΔΩΔΩΝΗΣ', name_latin=N'Municipality of Dodoni', abac_name=N'DEMOS DODONES', display_name=N'ΔΗΜΟΣ ΔΩΔΩΝΗΣ-Municipality of Dodoni' WHERE id=21132;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΔΩΡΙΔΟΣ', name_latin=N'Municipality of Doris', abac_name=N'DEMOS DORIDOS', display_name=N'ΔΗΜΟΣ ΔΩΡΙΔΟΣ-Municipality of Doris' WHERE id=21197;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΕΔΕΣΣΑΣ', name_latin=N'Municipality of Edessa', abac_name=N'DEMOS EDESSAS', display_name=N'ΔΗΜΟΣ ΕΔΕΣΣΑΣ-Municipality of Edessa' WHERE id=21099;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΕΛΑΣΣΟΝΑΣ', name_latin=N'Municipality of Elassona', abac_name=N'DEMOS ELASSONAS', display_name=N'ΔΗΜΟΣ ΕΛΑΣΣΟΝΑΣ-Municipality of Elassona' WHERE id=21150;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΕΛΑΦΟΝΗΣΟΥ', name_latin=N'Municipality of Elafonissos', abac_name=N'DEMOS ELAPhONESOU', display_name=N'ΔΗΜΟΣ ΕΛΑΦΟΝΗΣΟΥ-Municipality of Elafonissos' WHERE id=21241;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΕΛΕΥΣΙΝΑΣ', name_latin=N'Municipality of Elefsina', abac_name=N'DEMOS ELEUSINAS', display_name=N'ΔΗΜΟΣ ΕΛΕΥΣΙΝΑΣ-Municipality of Elefsina' WHERE id=21298;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΕΛΛΗΝΙΚΟΥ - ΑΡΓΥΡΟΥΠΟΛΗΣ', name_latin=N'Municipality of Elliniko - Argyroupoli', abac_name=N'DEMOS ELLENIKOU - ARGUROUPOLES', display_name=N'ΔΗΜΟΣ ΕΛΛΗΝΙΚΟΥ - ΑΡΓΥΡΟΥΠΟΛΗΣ-Municipality of Elliniko - Argyroupoli' WHERE id=21281;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΕΜΜΑΝΟΥΗΛ ΠΑΠΠΑ', name_latin=N'Municipality of Emmanuel Pappas', abac_name=N'DEMOS EMMANOUEL PAPPA', display_name=N'ΔΗΜΟΣ ΕΜΜΑΝΟΥΗΛ ΠΑΠΠΑ-Municipality of Emmanuel Pappas' WHERE id=21109;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΕΟΡΔΑΙΑΣ', name_latin=N'Municipality of Eordea', abac_name=N'DEMOS EORDAIAS', display_name=N'ΔΗΜΟΣ ΕΟΡΔΑΙΑΣ-Municipality of Eordea' WHERE id=21120;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΕΠΙΔΑΥΡΟΥ', name_latin=N'Municipality of Epidavros', abac_name=N'DEMOS EPIDAUROU', display_name=N'ΔΗΜΟΣ ΕΠΙΔΑΥΡΟΥ-Municipality of Epidavros' WHERE id=21231;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΕΡΕΤΡΙΑΣ', name_latin=N'Municipality of Eretria', abac_name=N'DEMOS ERETRIAS', display_name=N'ΔΗΜΟΣ ΕΡΕΤΡΙΑΣ-Municipality of Eretria' WHERE id=21188;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΕΡΜΙΟΝΙΔΑΣ', name_latin=N'Municipality of Ermionida', abac_name=N'DEMOS ERMIONIDAS', display_name=N'ΔΗΜΟΣ ΕΡΜΙΟΝΙΔΑΣ-Municipality of Ermionida' WHERE id=21232;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΕΡΥΜΑΝΘΟΥ', name_latin=N'Municipality of Erymanthos', abac_name=N'DEMOS ERUMANThOU', display_name=N'ΔΗΜΟΣ ΕΡΥΜΑΝΘΟΥ-Municipality of Erymanthos' WHERE id=21208;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΕΥΡΩΤΑ', name_latin=N'Municipality of Evrotas', abac_name=N'DEMOS EUROTA', display_name=N'ΔΗΜΟΣ ΕΥΡΩΤΑ-Municipality of Evrotas' WHERE id=21242;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΖΑΓΟΡΑΣ - ΜΟΥΡΕΣΙΟΥ', name_latin=N'Municipality of Zagora - Mouressio', abac_name=N'DEMOS ZAGORAS - MOURESIOU', display_name=N'ΔΗΜΟΣ ΖΑΓΟΡΑΣ - ΜΟΥΡΕΣΙΟΥ-Municipality of Zagora - Mouressio' WHERE id=21163;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΖΑΓΟΡΙΟΥ', name_latin=N'Municipality of Zagori', abac_name=N'DEMOS ZAGORIOU', display_name=N'ΔΗΜΟΣ ΖΑΓΟΡΙΟΥ-Municipality of Zagori' WHERE id=21133;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΖΑΚΥΝΘΟΥ', name_latin=N'Municipality of Zakynthos', abac_name=N'DEMOS ZAKUNThOU', display_name=N'ΔΗΜΟΣ ΖΑΚΥΝΘΟΥ-Municipality of Zakynthos' WHERE id=21200;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΖΑΧΑΡΩΣ', name_latin=N'Municipality of Zacharo', abac_name=N'DEMOS ZAKhAROS', display_name=N'ΔΗΜΟΣ ΖΑΧΑΡΩΣ-Municipality of Zacharo' WHERE id=21222;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΖΗΡΟΥ', name_latin=N'Municipality of Ziros', abac_name=N'DEMOS ZEROU', display_name=N'ΔΗΜΟΣ ΖΗΡΟΥ-Municipality of Ziros' WHERE id=21146;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΖΙΤΣΑΣ', name_latin=N'Municipality of Zitsa', abac_name=N'DEMOS ZITSAS', display_name=N'ΔΗΜΟΣ ΖΙΤΣΑΣ-Municipality of Zitsa' WHERE id=21134;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΖΩΓΡΑΦΟΥ', name_latin=N'Municipality of Zografos', abac_name=N'DEMOS ZOGRAPhOU', display_name=N'ΔΗΜΟΣ ΖΩΓΡΑΦΟΥ-Municipality of Zografos' WHERE id=21254;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΗΓΟΥΜΕΝΙΤΣΑΣ', name_latin=N'Municipality of Igoumenitsa', abac_name=N'DEMOS EGOUMENITSAS', display_name=N'ΔΗΜΟΣ ΗΓΟΥΜΕΝΙΤΣΑΣ-Municipality of Igoumenitsa' WHERE id=21142;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΉΛΙΔΑΣ', name_latin=N'Municipality of Ilida', abac_name=N'DEMOS ELIDAS', display_name=N'ΔΗΜΟΣ ΉΛΙΔΑΣ-Municipality of Ilida' WHERE id=21218;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΗΛΙΟΥΠΟΛΕΩΣ', name_latin=N'Municipality of Ilioupoli', abac_name=N'DEMOS ELIOUPOLEOS', display_name=N'ΔΗΜΟΣ ΗΛΙΟΥΠΟΛΕΩΣ-Municipality of Ilioupoli' WHERE id=21255;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΗΡΑΚΛΕΙΑΣ', name_latin=N'Municipality of Iraklia', abac_name=N'DEMOS ERAKLEIAS', display_name=N'ΔΗΜΟΣ ΗΡΑΚΛΕΙΑΣ-Municipality of Iraklia' WHERE id=21110;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΗΡΑΚΛΕΙΟΥ ΑΤΤΙΚΗΣ', name_latin=N'Municipality of Iraklio', abac_name=N'DEMOS ERAKLEIOU ATTIKES', display_name=N'ΔΗΜΟΣ ΗΡΑΚΛΕΙΟΥ ΑΤΤΙΚΗΣ-Municipality of Iraklio' WHERE id=21261;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΗΡΑΚΛΕΙΟΥ ΚΡΗΤΗΣ', name_latin=N'Municipality of Iraklio', abac_name=N'DEMOS ERAKLEIOU KRETES', display_name=N'ΔΗΜΟΣ ΗΡΑΚΛΕΙΟΥ ΚΡΗΤΗΣ-Municipality of Iraklio' WHERE id=21359;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΘΑΣΟΥ', name_latin=N'Municipality of Thassos', abac_name=N'DEMOS ThASOU', display_name=N'ΔΗΜΟΣ ΘΑΣΟΥ-Municipality of Thassos' WHERE id=21072;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΘΕΡΜΑΪΚΟΥ', name_latin=N'Municipality of Thermaikos', abac_name=N'DEMOS ThERMAIKOU', display_name=N'ΔΗΜΟΣ ΘΕΡΜΑΪΚΟΥ-Municipality of Thermaikos' WHERE id=21084;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΘΕΡΜΗΣ', name_latin=N'Municipality of Thermi', abac_name=N'DEMOS ThERMES', display_name=N'ΔΗΜΟΣ ΘΕΡΜΗΣ-Municipality of Thermi' WHERE id=21085;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΘΕΡΜΟΥ', name_latin=N'Municipality of Thermo', abac_name=N'DEMOS ThERMOU', display_name=N'ΔΗΜΟΣ ΘΕΡΜΟΥ-Municipality of Thermo' WHERE id=21214;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΘΕΣΣΑΛΟΝΙΚΗΣ', name_latin=N'Municipality of Thessaloniki', abac_name=N'DEMOS ThESSALONIKES', display_name=N'ΔΗΜΟΣ ΘΕΣΣΑΛΟΝΙΚΗΣ-Municipality of Thessaloniki' WHERE id=21080;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΘΗΒΑΙΩΝ', name_latin=N'Municipality of Thiva', abac_name=N'DEMOS ThEBAION', display_name=N'ΔΗΜΟΣ ΘΗΒΑΙΩΝ-Municipality of Thiva' WHERE id=21183;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΘΗΡΑΣ', name_latin=N'Municipality of Thira', abac_name=N'DEMOS ThERAS', display_name=N'ΔΗΜΟΣ ΘΗΡΑΣ-Municipality of Thira' WHERE id=21327;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΙΑΣΜΟΥ', name_latin=N'Municipality of Iasmos', abac_name=N'DEMOS IASMOU', display_name=N'ΔΗΜΟΣ ΙΑΣΜΟΥ-Municipality of Iasmos' WHERE id=21060;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΙΕΡΑΠΕΤΡΑΣ', name_latin=N'Municipality of Ierapetra', abac_name=N'DEMOS IERAPETRAS', display_name=N'ΔΗΜΟΣ ΙΕΡΑΠΕΤΡΑΣ-Municipality of Ierapetra' WHERE id=21368;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΙΕΡΑΣ ΠΟΛΗΣ ΜΕΣΟΛΟΓΓΙΟΥ', name_latin=N'Municipality of Iera Poli Messologhiou ', abac_name=N'DEMOS IERAS POLES MESOLOGGIOU', display_name=N'ΔΗΜΟΣ ΙΕΡΑΣ ΠΟΛΗΣ ΜΕΣΟΛΟΓΓΙΟΥ-Municipality of Iera Poli Messologhiou ' WHERE id=21210;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΙΗΤΩΝ', name_latin=N'Municipality of Ios', abac_name=N'DEMOS IETON', display_name=N'ΔΗΜΟΣ ΙΗΤΩΝ-Municipality of Ios' WHERE id=21329;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΙΘΑΚΗΣ', name_latin=N'Municipality of Ithaki', abac_name=N'DEMOS IThAKES', display_name=N'ΔΗΜΟΣ ΙΘΑΚΗΣ-Municipality of Ithaki' WHERE id=21201;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΙΚΑΡΙΑΣ', name_latin=N'Municipality of Ikaria', abac_name=N'DEMOS IKARIAS', display_name=N'ΔΗΜΟΣ ΙΚΑΡΙΑΣ-Municipality of Ikaria' WHERE id=21317;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΙΛΙΟΥ', name_latin=N'Municipality of Ilio', abac_name=N'DEMOS ILIOU', display_name=N'ΔΗΜΟΣ ΙΛΙΟΥ-Municipality of Ilio' WHERE id=21274;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΙΣΤΙΑΙΑΣ - ΑΙΔΗΨΟΥ', name_latin=N'Municipality of Istiea - Aedipsos', abac_name=N'DEMOS ISTIAIAS - AIDEPsOU', display_name=N'ΔΗΜΟΣ ΙΣΤΙΑΙΑΣ - ΑΙΔΗΨΟΥ-Municipality of Istiea - Aedipsos' WHERE id=21189;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΙΩΑΝΝΙΤΩΝ', name_latin=N'Municipality of Ioannina', abac_name=N'DEMOS IOANNITON', display_name=N'ΔΗΜΟΣ ΙΩΑΝΝΙΤΩΝ-Municipality of Ioannina' WHERE id=21130;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΑΒΑΛΑΣ', name_latin=N'Municipality of Kavala', abac_name=N'DEMOS KABALAS', display_name=N'ΔΗΜΟΣ ΚΑΒΑΛΑΣ-Municipality of Kavala' WHERE id=21073;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΑΙΣΑΡΙΑΝΗΣ', name_latin=N'Municipality of Kessariani', abac_name=N'DEMOS KAISARIANES', display_name=N'ΔΗΜΟΣ ΚΑΙΣΑΡΙΑΝΗΣ-Municipality of Kessariani' WHERE id=21256;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΑΛΑΒΡΥΤΩΝ', name_latin=N'Municipality of Kalavryta', abac_name=N'DEMOS KALABRUTON', display_name=N'ΔΗΜΟΣ ΚΑΛΑΒΡΥΤΩΝ-Municipality of Kalavryta' WHERE id=21209;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΑΛΑΜΑΡΙΑΣ', name_latin=N'Municipality of Kalamaria', abac_name=N'DEMOS KALAMARIAS', display_name=N'ΔΗΜΟΣ ΚΑΛΑΜΑΡΙΑΣ-Municipality of Kalamaria' WHERE id=21086;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΑΛΑΜΑΤΑΣ', name_latin=N'Municipality of Kalamata', abac_name=N'DEMOS KALAMATAS', display_name=N'ΔΗΜΟΣ ΚΑΛΑΜΑΤΑΣ-Municipality of Kalamata' WHERE id=21244;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΑΛΑΜΠΑΚΑΣ', name_latin=N'Municipality of Kalabaka', abac_name=N'DEMOS KALAMPAKAS', display_name=N'ΔΗΜΟΣ ΚΑΛΑΜΠΑΚΑΣ-Municipality of Kalabaka' WHERE id=21170;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΑΛΛΙΘΕΑΣ', name_latin=N'Municipality of Kallithea', abac_name=N'DEMOS KALLIThEAS', display_name=N'ΔΗΜΟΣ ΚΑΛΛΙΘΕΑΣ-Municipality of Kallithea' WHERE id=21277;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΑΛΥΜΝΙΩΝ', name_latin=N'Municipality of Kalymnos', abac_name=N'DEMOS KALUMNION', display_name=N'ΔΗΜΟΣ ΚΑΛΥΜΝΙΩΝ-Municipality of Kalymnos' WHERE id=21332;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΑΝΤΑΝΟΥ - ΣΕΛΙΝΟΥ', name_latin=N'Municipality of Kandanos - Selinos', abac_name=N'DEMOS KANTANOU - SELINOU', display_name=N'ΔΗΜΟΣ ΚΑΝΤΑΝΟΥ - ΣΕΛΙΝΟΥ-Municipality of Kandanos - Selinos' WHERE id=21379;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΑΡΔΙΤΣΑΣ', name_latin=N'Municipality of Karditsa', abac_name=N'DEMOS KARDITSAS', display_name=N'ΔΗΜΟΣ ΚΑΡΔΙΤΣΑΣ-Municipality of Karditsa' WHERE id=21155;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΑΡΠΑΘΟΥ', name_latin=N'Municipality of Karpathos', abac_name=N'DEMOS KARPAThOU', display_name=N'ΔΗΜΟΣ ΚΑΡΠΑΘΟΥ-Municipality of Karpathos' WHERE id=21338;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΑΡΠΕΝΗΣΙΟΥ', name_latin=N'Municipality of Karpenissi', abac_name=N'DEMOS KARPENESIOU', display_name=N'ΔΗΜΟΣ ΚΑΡΠΕΝΗΣΙΟΥ-Municipality of Karpenissi' WHERE id=21194;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΑΡΥΣΤΟΥ', name_latin=N'Municipality of Karystos', abac_name=N'DEMOS KARUSTOU', display_name=N'ΔΗΜΟΣ ΚΑΡΥΣΤΟΥ-Municipality of Karystos' WHERE id=21190;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΑΣΟΥ', name_latin=N'Municipality of Kassos', abac_name=N'DEMOS KASOU', display_name=N'ΔΗΜΟΣ ΚΑΣΟΥ-Municipality of Kassos' WHERE id=21339;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΑΣΣΑΝΔΡΑΣ', name_latin=N'Municipality of Kassandra', abac_name=N'DEMOS KASSANDRAS', display_name=N'ΔΗΜΟΣ ΚΑΣΣΑΝΔΡΑΣ-Municipality of Kassandra' WHERE id=21115;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΑΣΤΟΡΙΑΣ', name_latin=N'Municipality of Kastoria', abac_name=N'DEMOS KASTORIAS', display_name=N'ΔΗΜΟΣ ΚΑΣΤΟΡΙΑΣ-Municipality of Kastoria' WHERE id=21124;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΑΤΕΡΙΝΗΣ', name_latin=N'Municipality of Katerini', abac_name=N'DEMOS KATERINES', display_name=N'ΔΗΜΟΣ ΚΑΤΕΡΙΝΗΣ-Municipality of Katerini' WHERE id=21103;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΑΤΩ ΝΕΥΡΟΚΟΠΙΟΥ', name_latin=N'Municipality of Kato Nevrokopi', abac_name=N'DEMOS KATO NEUROKOPIOU', display_name=N'ΔΗΜΟΣ ΚΑΤΩ ΝΕΥΡΟΚΟΠΙΟΥ-Municipality of Kato Nevrokopi' WHERE id=21064;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΕΑΣ', name_latin=N'Municipality of Kea ', abac_name=N'DEMOS KEAS', display_name=N'ΔΗΜΟΣ ΚΕΑΣ-Municipality of Kea ' WHERE id=21340;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΕΝΤΡΙΚΩΝ ΤΖΟΥΜΕΡΚΩΝ', name_latin=N'Municipality of Kentrika Tzoumerka', abac_name=N'DEMOS KENTRIKON TZOUMERKON', display_name=N'ΔΗΜΟΣ ΚΕΝΤΡΙΚΩΝ ΤΖΟΥΜΕΡΚΩΝ-Municipality of Kentrika Tzoumerka' WHERE id=21140;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΕΡΑΤΣΙΝΙΟΥ - ΔΡΑΠΕΤΣΩΝΑΣ', name_latin=N'Municipality of Keratsini - Drapetsona', abac_name=N'DEMOS KERATSINIOU - DRAPETSONAS', display_name=N'ΔΗΜΟΣ ΚΕΡΑΤΣΙΝΙΟΥ - ΔΡΑΠΕΤΣΩΝΑΣ-Municipality of Keratsini - Drapetsona' WHERE id=21304;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΕΡΚΥΡΑΣ', name_latin=N'Municipality of Kerkyra', abac_name=N'DEMOS KERKURAS', display_name=N'ΔΗΜΟΣ ΚΕΡΚΥΡΑΣ-Municipality of Kerkyra' WHERE id=21198;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΕΦΑΛΛΟΝΙΑΣ', name_latin=N'Municipality of Kefalonia', abac_name=N'DEMOS KEPhALLONIAS', display_name=N'ΔΗΜΟΣ ΚΕΦΑΛΛΟΝΙΑΣ-Municipality of Kefalonia' WHERE id=21202;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΗΦΙΣΙΑΣ', name_latin=N'Municipality of Kifissia', abac_name=N'DEMOS KEPhISIAS', display_name=N'ΔΗΜΟΣ ΚΗΦΙΣΙΑΣ-Municipality of Kifissia' WHERE id=21262;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΙΛΕΛΕΡ', name_latin=N'Municipality of Kileler', abac_name=N'DEMOS KILELER', display_name=N'ΔΗΜΟΣ ΚΙΛΕΛΕΡ-Municipality of Kileler' WHERE id=21151;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΙΛΚΙΣ', name_latin=N'Municipality of Kilkis', abac_name=N'DEMOS KILKIS', display_name=N'ΔΗΜΟΣ ΚΙΛΚΙΣ-Municipality of Kilkis' WHERE id=21097;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΙΜΩΛΟΥ', name_latin=N'Municipality of Kimolos', abac_name=N'DEMOS KIMOLOU', display_name=N'ΔΗΜΟΣ ΚΙΜΩΛΟΥ-Municipality of Kimolos' WHERE id=21345;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΙΣΣΑΜΟΥ', name_latin=N'Municipality of Kissamos', abac_name=N'DEMOS KISSAMOU', display_name=N'ΔΗΜΟΣ ΚΙΣΣΑΜΟΥ-Municipality of Kissamos' WHERE id=21380;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΟΖΑΝΗΣ', name_latin=N'Municipality of Kozani', abac_name=N'DEMOS KOZANES', display_name=N'ΔΗΜΟΣ ΚΟΖΑΝΗΣ-Municipality of Kozani' WHERE id=21118;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΟΜΟΤΗΝΗΣ', name_latin=N'Municipality of Komotini', abac_name=N'DEMOS KOMOTENES', display_name=N'ΔΗΜΟΣ ΚΟΜΟΤΗΝΗΣ-Municipality of Komotini' WHERE id=21058;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΟΝΙΤΣΑΣ', name_latin=N'Municipality of Konitsa', abac_name=N'DEMOS KONITSAS', display_name=N'ΔΗΜΟΣ ΚΟΝΙΤΣΑΣ-Municipality of Konitsa' WHERE id=21135;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΟΡΔΕΛΙΟΥ - ΕΥΟΣΜΟΥ', name_latin=N'Municipality of Kordelio - Evosmos', abac_name=N'DEMOS KORDELIOU - EUOSMOU', display_name=N'ΔΗΜΟΣ ΚΟΡΔΕΛΙΟΥ - ΕΥΟΣΜΟΥ-Municipality of Kordelio - Evosmos' WHERE id=21087;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΟΡΙΝΘΙΩΝ', name_latin=N'Municipality of Korinthos', abac_name=N'DEMOS KORINThION', display_name=N'ΔΗΜΟΣ ΚΟΡΙΝΘΙΩΝ-Municipality of Korinthos' WHERE id=21233;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΟΡΥΔΑΛΛΟΥ', name_latin=N'Municipality of Korydallos', abac_name=N'DEMOS KORUDALLOU', display_name=N'ΔΗΜΟΣ ΚΟΡΥΔΑΛΛΟΥ-Municipality of Korydallos' WHERE id=21305;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΡΩΠΙΑΣ', name_latin=N'Municipality of Koropi', abac_name=N'DEMOS KROPIAS', display_name=N'ΔΗΜΟΣ ΚΡΩΠΙΑΣ-Municipality of Koropi' WHERE id=21288;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΥΘΗΡΩΝ', name_latin=N'Municipality of Kythira', abac_name=N'DEMOS KUThERON', display_name=N'ΔΗΜΟΣ ΚΥΘΗΡΩΝ-Municipality of Kythira' WHERE id=21312;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΥΘΝΟΥ', name_latin=N'Municipality of Kythnos', abac_name=N'DEMOS KUThNOU', display_name=N'ΔΗΜΟΣ ΚΥΘΝΟΥ-Municipality of Kythnos' WHERE id=21341;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΥΜΗΣ - ΑΛΙΒΕΡΙΟΥ', name_latin=N'Municipality of Kymi - Aliveri', abac_name=N'DEMOS KUMES - ALIBERIOU', display_name=N'ΔΗΜΟΣ ΚΥΜΗΣ - ΑΛΙΒΕΡΙΟΥ-Municipality of Kymi - Aliveri' WHERE id=21191;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΚΩ', name_latin=N'Municipality of Kos', abac_name=N'DEMOS KO', display_name=N'ΔΗΜΟΣ ΚΩ-Municipality of Kos' WHERE id=21342;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΛΑΓΚΑΔΑ', name_latin=N'Municipality of Lagadas', abac_name=N'DEMOS LAGKADA', display_name=N'ΔΗΜΟΣ ΛΑΓΚΑΔΑ-Municipality of Lagadas' WHERE id=21088;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΛΑΜΙΕΩΝ', name_latin=N'Municipality of Lamia', abac_name=N'DEMOS LAMIEON', display_name=N'ΔΗΜΟΣ ΛΑΜΙΕΩΝ-Municipality of Lamia' WHERE id=21173;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΛΑΡΙΣΑΙΩΝ', name_latin=N'Municipality of Larissa', abac_name=N'DEMOS LARISAION', display_name=N'ΔΗΜΟΣ ΛΑΡΙΣΑΙΩΝ-Municipality of Larissa' WHERE id=21148;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΛΑΥΡΕΩΤΙΚΗΣ', name_latin=N'Municipality of Lavrio', abac_name=N'DEMOS LAUREOTIKES', display_name=N'ΔΗΜΟΣ ΛΑΥΡΕΩΤΙΚΗΣ-Municipality of Lavrio' WHERE id=21289;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΛΕΒΑΔΕΩΝ', name_latin=N'Municipality of Levadia', abac_name=N'DEMOS LEBADEON', display_name=N'ΔΗΜΟΣ ΛΕΒΑΔΕΩΝ-Municipality of Levadia' WHERE id=21180;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΛΕΙΨΩΝ', name_latin=N'Municipality of Lipsi', abac_name=N'DEMOS LEIPsON', display_name=N'ΔΗΜΟΣ ΛΕΙΨΩΝ-Municipality of Lipsi' WHERE id=21335;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΛΕΡΟΥ', name_latin=N'Municipality of Leros', abac_name=N'DEMOS LEROU', display_name=N'ΔΗΜΟΣ ΛΕΡΟΥ-Municipality of Leros' WHERE id=21336;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΛΕΣΒΟΥ', name_latin=N'Municipality of Lesvos', abac_name=N'DEMOS LESBOU', display_name=N'ΔΗΜΟΣ ΛΕΣΒΟΥ-Municipality of Lesvos' WHERE id=21316;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΛΕΥΚΑΔΑΣ', name_latin=N'Municipality of Lefkada', abac_name=N'DEMOS LEUKADAS', display_name=N'ΔΗΜΟΣ ΛΕΥΚΑΔΑΣ-Municipality of Lefkada' WHERE id=21203;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΛΗΜΝΟΥ', name_latin=N'Municipality of Limnos', abac_name=N'DEMOS LEMNOU', display_name=N'ΔΗΜΟΣ ΛΗΜΝΟΥ-Municipality of Limnos' WHERE id=21319;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΛΙΜΝΗΣ ΠΛΑΣΤΗΡΑ', name_latin=N'Municipality of Limni Plastira', abac_name=N'DEMOS LIMNES PLASTERA', display_name=N'ΔΗΜΟΣ ΛΙΜΝΗΣ ΠΛΑΣΤΗΡΑ-Municipality of Limni Plastira' WHERE id=21157;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΛΟΚΡΩΝ', name_latin=N'Municipality of Lokri', abac_name=N'DEMOS LOKRON', display_name=N'ΔΗΜΟΣ ΛΟΚΡΩΝ-Municipality of Lokri' WHERE id=21176;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΛΟΥΤΡΑΚΙΟΥ-ΠΕΡΑΧΩΡΑΣ-ΑΓ. ΘΕΟΔΩΡΩΝ', name_latin=N'Municipality of Loutraki - Perachora - Aghii Theodori', abac_name=N'DEMOS LOUTRAKIOU-PERAKhORAS-AG. ThEODORON', display_name=N'ΔΗΜΟΣ ΛΟΥΤΡΑΚΙΟΥ-ΠΕΡΑΧΩΡΑΣ-ΑΓ. ΘΕΟΔΩΡΩΝ-Municipality of Loutraki - Perachora - Aghii Theodori' WHERE id=21235;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΛΥΚΟΒΡΥΣΗΣ - ΠΕΥΚΗΣ', name_latin=N'Municipality of Lykovryssi - Pefki', abac_name=N'DEMOS LUKOBRUSES - PEUKES', display_name=N'ΔΗΜΟΣ ΛΥΚΟΒΡΥΣΗΣ - ΠΕΥΚΗΣ-Municipality of Lykovryssi - Pefki' WHERE id=21263;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΑΚΡΑΚΩΜΗΣ', name_latin=N'Municipality of Makrakomi', abac_name=N'DEMOS MAKRAKOMES', display_name=N'ΔΗΜΟΣ ΜΑΚΡΑΚΩΜΗΣ-Municipality of Makrakomi' WHERE id=21177;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΑΛΕΒΙΖΙΟΥ', name_latin=N'Municipality of Malevizi', abac_name=N'DEMOS MALEBIZIOU', display_name=N'ΔΗΜΟΣ ΜΑΛΕΒΙΖΙΟΥ-Municipality of Malevizi' WHERE id=21363;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΑΝΔΡΑΣ - ΕΙΔΥΛΛΙΑΣ', name_latin=N'Municipality of Mandra - Idyllia', abac_name=N'DEMOS MANDRAS - EIDULLIAS', display_name=N'ΔΗΜΟΣ ΜΑΝΔΡΑΣ - ΕΙΔΥΛΛΙΑΣ-Municipality of Mandra - Idyllia' WHERE id=21300;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΑΝΤΟΥΔΙΟΥ - ΛΙΜΝΗΣ - ΑΓΙΑΣ ΑΝΝΑΣ', name_latin=N'Municipality of Mantoudi - Limni - Aghia Anna', abac_name=N'DEMOS MANTOUDIOU - LIMNES - AGIAS ANNAS', display_name=N'ΔΗΜΟΣ ΜΑΝΤΟΥΔΙΟΥ - ΛΙΜΝΗΣ - ΑΓΙΑΣ ΑΝΝΑΣ-Municipality of Mantoudi - Limni - Aghia Anna' WHERE id=21192;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΑΡΑΘΩΝΟΣ', name_latin=N'Municipality of Marathon', abac_name=N'DEMOS MARAThONOS', display_name=N'ΔΗΜΟΣ ΜΑΡΑΘΩΝΟΣ-Municipality of Marathon' WHERE id=21290;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΑΡΚΟΠΟΥΛΟΥ ΜΕΣΟΓΑΙΑΣ', name_latin=N'Municipality of Markopoulo Messogheas', abac_name=N'DEMOS MARKOPOULOU MESOGAIAS', display_name=N'ΔΗΜΟΣ ΜΑΡΚΟΠΟΥΛΟΥ ΜΕΣΟΓΑΙΑΣ-Municipality of Markopoulo Messogheas' WHERE id=21291;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΑΡΩΝΕΙΑΣ - ΣΑΠΩΝ', name_latin=N'Municipality of Maronia - Sapes', abac_name=N'DEMOS MARONEIAS - SAPON', display_name=N'ΔΗΜΟΣ ΜΑΡΩΝΕΙΑΣ - ΣΑΠΩΝ-Municipality of Maronia - Sapes' WHERE id=21061;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΕΓΑΛΟΠΟΛΗΣ', name_latin=N'Municipality of Megalopoli', abac_name=N'DEMOS MEGALOPOLES', display_name=N'ΔΗΜΟΣ ΜΕΓΑΛΟΠΟΛΗΣ-Municipality of Megalopoli' WHERE id=21227;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΕΓΑΝΗΣΙΟΥ', name_latin=N'Municipality of Meganissi', abac_name=N'DEMOS MEGANESIOU', display_name=N'ΔΗΜΟΣ ΜΕΓΑΝΗΣΙΟΥ-Municipality of Meganissi' WHERE id=21204;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΕΓΑΡΕΩΝ', name_latin=N'Municipality of Megara', abac_name=N'DEMOS MEGAREON', display_name=N'ΔΗΜΟΣ ΜΕΓΑΡΕΩΝ-Municipality of Megara' WHERE id=21301;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΕΓΙΣΤΗΣ', name_latin=N'Municipality of Megisti', abac_name=N'DEMOS MEGISTES', display_name=N'ΔΗΜΟΣ ΜΕΓΙΣΤΗΣ-Municipality of Megisti' WHERE id=21354;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΕΣΣΗΝΗΣ', name_latin=N'Municipality of Messini', abac_name=N'DEMOS MESSENES', display_name=N'ΔΗΜΟΣ ΜΕΣΣΗΝΗΣ-Municipality of Messini' WHERE id=21246;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΕΤΑΜΟΡΦΩΣΕΩΣ', name_latin=N'Municipality of Metamorfossi', abac_name=N'DEMOS METAMORPhOSEOS', display_name=N'ΔΗΜΟΣ ΜΕΤΑΜΟΡΦΩΣΕΩΣ-Municipality of Metamorfossi' WHERE id=21264;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΕΤΣΟΒΟΥ', name_latin=N'Municipality of Metsovo', abac_name=N'DEMOS METSOBOU', display_name=N'ΔΗΜΟΣ ΜΕΤΣΟΒΟΥ-Municipality of Metsovo' WHERE id=21136;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΗΛΟΥ', name_latin=N'Municipality of Milos', abac_name=N'DEMOS MELOU', display_name=N'ΔΗΜΟΣ ΜΗΛΟΥ-Municipality of Milos' WHERE id=21344;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΙΝΩΑ ΠΕΔΙΑΔΑΣ', name_latin=N'Municipality of Minoa Pediadas', abac_name=N'DEMOS MINOA PEDIADAS', display_name=N'ΔΗΜΟΣ ΜΙΝΩΑ ΠΕΔΙΑΔΑΣ-Municipality of Minoa Pediadas' WHERE id=21364;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΟΝΕΜΒΑΣΙΑΣ', name_latin=N'Municipality of Monemvassia', abac_name=N'DEMOS MONEMBASIAS', display_name=N'ΔΗΜΟΣ ΜΟΝΕΜΒΑΣΙΑΣ-Municipality of Monemvassia' WHERE id=21243;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΟΣΧΑΤΟΥ - ΤΑΥΡΟΥ', name_latin=N'Municipality of Moschato - Tavros', abac_name=N'DEMOS MOSKhATOU - TAUROU', display_name=N'ΔΗΜΟΣ ΜΟΣΧΑΤΟΥ - ΤΑΥΡΟΥ-Municipality of Moschato - Tavros' WHERE id=21282;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΟΥΖΑΚΙΟΥ', name_latin=N'Municipality of Mouzaki', abac_name=N'DEMOS MOUZAKIOU', display_name=N'ΔΗΜΟΣ ΜΟΥΖΑΚΙΟΥ-Municipality of Mouzaki' WHERE id=21158;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΥΚΗΣ', name_latin=N'Municipality of Myki', abac_name=N'DEMOS MUKES', display_name=N'ΔΗΜΟΣ ΜΥΚΗΣ-Municipality of Myki' WHERE id=21078;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΥΚΟΝΟΥ', name_latin=N'Municipality of Mykonos', abac_name=N'DEMOS MUKONOU', display_name=N'ΔΗΜΟΣ ΜΥΚΟΝΟΥ-Municipality of Mykonos' WHERE id=21348;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΥΛΟΠΟΤΑΜΟΥ', name_latin=N'Municipality of Mylopotamos', abac_name=N'DEMOS MULOPOTAMOU', display_name=N'ΔΗΜΟΣ ΜΥΛΟΠΟΤΑΜΟΥ-Municipality of Mylopotamos' WHERE id=21375;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΜΩΛΟΥ - ΑΓ. ΚΩΝΣΤΑΝΤΙΝΟΥ', name_latin=N'Municipality of Molos - Aghios Konstantinos', abac_name=N'DEMOS MOLOU - AG. KONSTANTINOU', display_name=N'ΔΗΜΟΣ ΜΩΛΟΥ - ΑΓ. ΚΩΝΣΤΑΝΤΙΝΟΥ-Municipality of Molos - Aghios Konstantinos' WHERE id=21178;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΝΑΞΟΥ & ΜΙΚΡΩΝ ΚΥΚΛΑΔΩΝ', name_latin=N'Municipality of Naxos - Mikres Kyklades', abac_name=N'DEMOS NAKsOU & MIKRON KUKLADON', display_name=N'ΔΗΜΟΣ ΝΑΞΟΥ & ΜΙΚΡΩΝ ΚΥΚΛΑΔΩΝ-Municipality of Naxos - Mikres Kyklades' WHERE id=21350;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΝΑΟΥΣΑΣ', name_latin=N'Municipality of Naoussa', abac_name=N'DEMOS NAOUSAS', display_name=N'ΔΗΜΟΣ ΝΑΟΥΣΑΣ-Municipality of Naoussa' WHERE id=21096;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΝΑΥΠΑΚΤΙΑΣ', name_latin=N'Municipality of Nafpaktia', abac_name=N'DEMOS NAUPAKTIAS', display_name=N'ΔΗΜΟΣ ΝΑΥΠΑΚΤΙΑΣ-Municipality of Nafpaktia' WHERE id=21215;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΝΑΥΠΛΙΕΩΝ', name_latin=N'Municipality of Nafplio', abac_name=N'DEMOS NAUPLIEON', display_name=N'ΔΗΜΟΣ ΝΑΥΠΛΙΕΩΝ-Municipality of Nafplio' WHERE id=21229;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΝΕΑΠΟΛΗΣ - ΣΥΚΕΩΝ', name_latin=N'Municipality of Neapoli - Sykees', abac_name=N'DEMOS NEAPOLES - SUKEON', display_name=N'ΔΗΜΟΣ ΝΕΑΠΟΛΗΣ - ΣΥΚΕΩΝ-Municipality of Neapoli - Sykees' WHERE id=21089;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΝΕΑΣ ΖΙΧΝΗΣ', name_latin=N'Municipality of Nea Zichni', abac_name=N'DEMOS NEAS ZIKhNES', display_name=N'ΔΗΜΟΣ ΝΕΑΣ ΖΙΧΝΗΣ-Municipality of Nea Zichni' WHERE id=21111;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΝΕΑΣ ΙΩΝΙΑΣ', name_latin=N'Municipality of Nea Ionia', abac_name=N'DEMOS NEAS IONIAS', display_name=N'ΔΗΜΟΣ ΝΕΑΣ ΙΩΝΙΑΣ-Municipality of Nea Ionia' WHERE id=21265;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΝΕΑΣ ΠΡΟΠΟΝΤΙΔΑΣ', name_latin=N'Municipality of Nea Propontida', abac_name=N'DEMOS NEAS PROPONTIDAS', display_name=N'ΔΗΜΟΣ ΝΕΑΣ ΠΡΟΠΟΝΤΙΔΑΣ-Municipality of Nea Propontida' WHERE id=21116;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΝΕΑΣ ΣΜΥΡΝΗΣ', name_latin=N'Municipality of Nea Smyrni', abac_name=N'DEMOS NEAS SMURNES', display_name=N'ΔΗΜΟΣ ΝΕΑΣ ΣΜΥΡΝΗΣ-Municipality of Nea Smyrni' WHERE id=21283;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΝΕΑΣ ΦΙΛΑΔΕΛΦΕΙΑΣ - ΝΕΑΣ ΧΑΛΚΗΔΟΝΑΣ', name_latin=N'Municipality of Nea Philadelfia - Nea Chalkidona', abac_name=N'DEMOS NEAS PhILADELPhEIAS - NEAS KhALKEDONAS', display_name=N'ΔΗΜΟΣ ΝΕΑΣ ΦΙΛΑΔΕΛΦΕΙΑΣ - ΝΕΑΣ ΧΑΛΚΗΔΟΝΑΣ-Municipality of Nea Philadelfia - Nea Chalkidona' WHERE id=21257;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΝΕΜΕΑΣ', name_latin=N'Municipality of Nemea', abac_name=N'DEMOS NEMEAS', display_name=N'ΔΗΜΟΣ ΝΕΜΕΑΣ-Municipality of Nemea' WHERE id=21236;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΝΕΣΤΟΡΙΟΥ', name_latin=N'Municipality of Nestorio', abac_name=N'DEMOS NESTORIOU', display_name=N'ΔΗΜΟΣ ΝΕΣΤΟΡΙΟΥ-Municipality of Nestorio' WHERE id=21125;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΝΕΣΤΟΥ', name_latin=N'Municipality of Nestos', abac_name=N'DEMOS NESTOU', display_name=N'ΔΗΜΟΣ ΝΕΣΤΟΥ-Municipality of Nestos' WHERE id=21074;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΝΙΚΑΙΑΣ - ΑΓΙΟΥ ΙΩΑΝΝΗ ΡΕΝΤΗ', name_latin=N'Municipality of Nikea - Aghios Ioannis Rentis', abac_name=N'DEMOS NIKAIAS - AGIOU IOANNE RENTE', display_name=N'ΔΗΜΟΣ ΝΙΚΑΙΑΣ - ΑΓΙΟΥ ΙΩΑΝΝΗ ΡΕΝΤΗ-Municipality of Nikea - Aghios Ioannis Rentis' WHERE id=21306;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΝΙΚΟΛΑΟΥ ΣΚΟΥΦΑ', name_latin=N'Municipality of Nikolaos Skoufas', abac_name=N'DEMOS NIKOLAOU SKOUPhA', display_name=N'ΔΗΜΟΣ ΝΙΚΟΛΑΟΥ ΣΚΟΥΦΑ-Municipality of Nikolaos Skoufas' WHERE id=21141;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΝΙΣΥΡΟΥ', name_latin=N'Municipality of Nissyros', abac_name=N'DEMOS NISUROU', display_name=N'ΔΗΜΟΣ ΝΙΣΥΡΟΥ-Municipality of Nissyros' WHERE id=21343;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΝΟΤΙΑΣ ΚΥΝΟΥΡΙΑΣ', name_latin=N'Municipality of Notia Kynouria', abac_name=N'DEMOS NOTIAS KUNOURIAS', display_name=N'ΔΗΜΟΣ ΝΟΤΙΑΣ ΚΥΝΟΥΡΙΑΣ-Municipality of Notia Kynouria' WHERE id=21228;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΝΟΤΙΟΥ ΠΗΛΙΟΥ', name_latin=N'Municipality of Notio Pelio', abac_name=N'DEMOS NOTIOU PELIOU', display_name=N'ΔΗΜΟΣ ΝΟΤΙΟΥ ΠΗΛΙΟΥ-Municipality of Notio Pelio' WHERE id=21164;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΞΑΝΘΗΣ', name_latin=N'Municipality of Xanthi', abac_name=N'DEMOS KsANThES', display_name=N'ΔΗΜΟΣ ΞΑΝΘΗΣ-Municipality of Xanthi' WHERE id=21076;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΞΗΡΟΜΕΡΟΥ', name_latin=N'Municipality of Xiromero', abac_name=N'DEMOS KsEROMEROU', display_name=N'ΔΗΜΟΣ ΞΗΡΟΜΕΡΟΥ-Municipality of Xiromero' WHERE id=21216;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΞΥΛΟΚΑΣΤΡΟΥ - ΕΥΡΩΣΤΙΝΗΣ', name_latin=N'Municipality of Xylokastro - Evrostina', abac_name=N'DEMOS KsULOKASTROU - EUROSTINES', display_name=N'ΔΗΜΟΣ ΞΥΛΟΚΑΣΤΡΟΥ - ΕΥΡΩΣΤΙΝΗΣ-Municipality of Xylokastro - Evrostina' WHERE id=21237;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΟΙΝΟΥΣΣΩΝ', name_latin=N'Municipality of Inousses', abac_name=N'DEMOS OINOUSSON', display_name=N'ΔΗΜΟΣ ΟΙΝΟΥΣΣΩΝ-Municipality of Inousses' WHERE id=21323;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΟΙΧΑΛΙΑΣ', name_latin=N'Municipality of Ichalia', abac_name=N'DEMOS OIKhALIAS', display_name=N'ΔΗΜΟΣ ΟΙΧΑΛΙΑΣ-Municipality of Ichalia' WHERE id=21247;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΟΡΕΣΤΙΑΔΑΣ', name_latin=N'Municipality of Orestiada', abac_name=N'DEMOS ORESTIADAS', display_name=N'ΔΗΜΟΣ ΟΡΕΣΤΙΑΔΑΣ-Municipality of Orestiada' WHERE id=21069;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΟΡΟΠΕΔΙΟΥ ΛΑΣΙΘΙΟΥ', name_latin=N'Municipality of Oropedio Lassithiou', abac_name=N'DEMOS OROPEDIOU LASIThIOU', display_name=N'ΔΗΜΟΣ ΟΡΟΠΕΔΙΟΥ ΛΑΣΙΘΙΟΥ-Municipality of Oropedio Lassithiou' WHERE id=21369;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΟΡΧΟΜΕΝΟΥ', name_latin=N'Municipality of Orchomenos', abac_name=N'DEMOS ORKhOMENOU', display_name=N'ΔΗΜΟΣ ΟΡΧΟΜΕΝΟΥ-Municipality of Orchomenos' WHERE id=21184;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΑΓΓΑΙΟΥ', name_latin=N'Municipality of Pagheo', abac_name=N'DEMOS PAGGAIOU', display_name=N'ΔΗΜΟΣ ΠΑΓΓΑΙΟΥ-Municipality of Pagheo' WHERE id=21075;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΑΙΑΝΙΑΣ - ΓΛΥΚΩΝ ΝΕΡΩΝ', name_latin=N'Municipality of Peania', abac_name=N'DEMOS PAIANIAS - GLUKON NERON', display_name=N'ΔΗΜΟΣ ΠΑΙΑΝΙΑΣ - ΓΛΥΚΩΝ ΝΕΡΩΝ-Municipality of Peania' WHERE id=21292;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΑΙΟΝΙΑΣ', name_latin=N'Municipality of Peonia', abac_name=N'DEMOS PAIONIAS', display_name=N'ΔΗΜΟΣ ΠΑΙΟΝΙΑΣ-Municipality of Peonia' WHERE id=21098;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΑΛΑΙΟΥ ΦΑΛΗΡΟΥ', name_latin=N'Municipality of Paleo Faliro', abac_name=N'DEMOS PALAIOU PhALEROU', display_name=N'ΔΗΜΟΣ ΠΑΛΑΙΟΥ ΦΑΛΗΡΟΥ-Municipality of Paleo Faliro' WHERE id=21284;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΑΛΑΜΑ', name_latin=N'Municipality of Palamas', abac_name=N'DEMOS PALAMA', display_name=N'ΔΗΜΟΣ ΠΑΛΑΜΑ-Municipality of Palamas' WHERE id=21159;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΑΛΛΗΝΗΣ', name_latin=N'Municipality of Pallini', abac_name=N'DEMOS PALLENES', display_name=N'ΔΗΜΟΣ ΠΑΛΛΗΝΗΣ-Municipality of Pallini' WHERE id=21293;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΑΞΩΝ', name_latin=N'Municipality of Paxi', abac_name=N'DEMOS PAKsON', display_name=N'ΔΗΜΟΣ ΠΑΞΩΝ-Municipality of Paxi' WHERE id=21199;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΑΠΑΓΟΥ - ΧΟΛΑΡΓΟΥ', name_latin=N'Municipality of Papagos - Cholargos', abac_name=N'DEMOS PAPAGOU - KhOLARGOU', display_name=N'ΔΗΜΟΣ ΠΑΠΑΓΟΥ - ΧΟΛΑΡΓΟΥ-Municipality of Papagos - Cholargos' WHERE id=21266;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΑΡΑΝΕΣΤΙΟΥ', name_latin=N'Municipality of Paranesti', abac_name=N'DEMOS PARANESTIOU', display_name=N'ΔΗΜΟΣ ΠΑΡΑΝΕΣΤΙΟΥ-Municipality of Paranesti' WHERE id=21065;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΑΡΓΑΣ', name_latin=N'Municipality of Parga', abac_name=N'DEMOS PARGAS', display_name=N'ΔΗΜΟΣ ΠΑΡΓΑΣ-Municipality of Parga' WHERE id=21147;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΑΡΟΥ', name_latin=N'Municipality of Paros', abac_name=N'DEMOS PAROU', display_name=N'ΔΗΜΟΣ ΠΑΡΟΥ-Municipality of Paros' WHERE id=21351;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΑΤΜΟΥ', name_latin=N'Municipality of Patmos', abac_name=N'DEMOS PATMOU', display_name=N'ΔΗΜΟΣ ΠΑΤΜΟΥ-Municipality of Patmos' WHERE id=21337;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΑΤΡΕΩΝ', name_latin=N'Municipality of Patra', abac_name=N'DEMOS PATREON', display_name=N'ΔΗΜΟΣ ΠΑΤΡΕΩΝ-Municipality of Patra' WHERE id=21205;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΑΥΛΟΥ ΜΕΛΑ', name_latin=N'Municipality of Pavlos Melas', abac_name=N'DEMOS PAULOU MELA', display_name=N'ΔΗΜΟΣ ΠΑΥΛΟΥ ΜΕΛΑ-Municipality of Pavlos Melas' WHERE id=21090;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΕΙΡΑΙΩΣ', name_latin=N'Municipality of Pireas', abac_name=N'DEMOS PEIRAIOS', display_name=N'ΔΗΜΟΣ ΠΕΙΡΑΙΩΣ-Municipality of Pireas' WHERE id=21303;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΕΛΛΑΣ', name_latin=N'Municipality of Pella', abac_name=N'DEMOS PELLAS', display_name=N'ΔΗΜΟΣ ΠΕΛΛΑΣ-Municipality of Pella' WHERE id=21101;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΕΝΤΕΛΗΣ', name_latin=N'Municipality of Penteli', abac_name=N'DEMOS PENTELES', display_name=N'ΔΗΜΟΣ ΠΕΝΤΕΛΗΣ-Municipality of Penteli' WHERE id=21267;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΕΡΑΜΑΤΟΣ', name_latin=N'Municipality of Perama', abac_name=N'DEMOS PERAMATOS', display_name=N'ΔΗΜΟΣ ΠΕΡΑΜΑΤΟΣ-Municipality of Perama' WHERE id=21307;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΕΡΙΣΤΕΡΙΟΥ', name_latin=N'Municipality of Peristeri', abac_name=N'DEMOS PERISTERIOU', display_name=N'ΔΗΜΟΣ ΠΕΡΙΣΤΕΡΙΟΥ-Municipality of Peristeri' WHERE id=21270;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΕΤΡΟΥΠΟΛΕΩΣ', name_latin=N'Municipality of Petroupoli', abac_name=N'DEMOS PETROUPOLEOS', display_name=N'ΔΗΜΟΣ ΠΕΤΡΟΥΠΟΛΕΩΣ-Municipality of Petroupoli' WHERE id=21275;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΗΝΕΙΟΥ', name_latin=N'Municipality of Pinios', abac_name=N'DEMOS PENEIOU', display_name=N'ΔΗΜΟΣ ΠΗΝΕΙΟΥ-Municipality of Pinios' WHERE id=21223;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΛΑΤΑΝΙΑ', name_latin=N'Municipality of Platanias', abac_name=N'DEMOS PLATANIA', display_name=N'ΔΗΜΟΣ ΠΛΑΤΑΝΙΑ-Municipality of Platanias' WHERE id=21381;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΟΛΥΓΥΡΟΥ', name_latin=N'Municipality of Polygyros', abac_name=N'DEMOS POLUGUROU', display_name=N'ΔΗΜΟΣ ΠΟΛΥΓΥΡΟΥ-Municipality of Polygyros' WHERE id=21113;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΟΡΟΥ', name_latin=N'Municipality of Poros', abac_name=N'DEMOS POROU', display_name=N'ΔΗΜΟΣ ΠΟΡΟΥ-Municipality of Poros' WHERE id=21313;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΡΕΒΕΖΑΣ', name_latin=N'Municipality of Preveza', abac_name=N'DEMOS PREBEZAS', display_name=N'ΔΗΜΟΣ ΠΡΕΒΕΖΑΣ-Municipality of Preveza' WHERE id=21145;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΡΕΣΠΩΝ', name_latin=N'Municipality of Prespes', abac_name=N'DEMOS PRESPON', display_name=N'ΔΗΜΟΣ ΠΡΕΣΠΩΝ-Municipality of Prespes' WHERE id=21129;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΡΟΣΟΤΣΑΝΗΣ', name_latin=N'Municipality of Prossotsani', abac_name=N'DEMOS PROSOTSANES', display_name=N'ΔΗΜΟΣ ΠΡΟΣΟΤΣΑΝΗΣ-Municipality of Prossotsani' WHERE id=21066;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΥΔΝΑΣ - ΚΟΛΙΝΔΡΟΥ', name_latin=N'Municipality of Pydna - Kolindros', abac_name=N'DEMOS PUDNAS - KOLINDROU', display_name=N'ΔΗΜΟΣ ΠΥΔΝΑΣ - ΚΟΛΙΝΔΡΟΥ-Municipality of Pydna - Kolindros' WHERE id=21105;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΥΛΑΙΑΣ - ΧΟΡΤΙΑΤΗ', name_latin=N'Municipality of Pylea - Chortiatis', abac_name=N'DEMOS PULAIAS - KhORTIATE', display_name=N'ΔΗΜΟΣ ΠΥΛΑΙΑΣ - ΧΟΡΤΙΑΤΗ-Municipality of Pylea - Chortiatis' WHERE id=21091;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΥΛΗΣ', name_latin=N'Municipality of Pyli', abac_name=N'DEMOS PULES', display_name=N'ΔΗΜΟΣ ΠΥΛΗΣ-Municipality of Pyli' WHERE id=21171;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΥΛΟΥ - ΝΕΣΤΟΡΟΣ', name_latin=N'Municipality of Pylos - Nestor', abac_name=N'DEMOS PULOU - NESTOROS', display_name=N'ΔΗΜΟΣ ΠΥΛΟΥ - ΝΕΣΤΟΡΟΣ-Municipality of Pylos - Nestor' WHERE id=21248;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΥΡΓΟΥ', name_latin=N'Municipality of Pyrgos', abac_name=N'DEMOS PURGOU', display_name=N'ΔΗΜΟΣ ΠΥΡΓΟΥ-Municipality of Pyrgos' WHERE id=21217;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΠΩΓΩΝΙΟΥ', name_latin=N'Municipality of Pogonio', abac_name=N'DEMOS POGONIOU', display_name=N'ΔΗΜΟΣ ΠΩΓΩΝΙΟΥ-Municipality of Pogonio' WHERE id=21137;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΡΑΦΗΝΑΣ - ΠΙΚΕΡΜΙΟΥ', name_latin=N'Municipality of Rafina - Pikermi', abac_name=N'DEMOS RAPhENAS - PIKERMIOU', display_name=N'ΔΗΜΟΣ ΡΑΦΗΝΑΣ - ΠΙΚΕΡΜΙΟΥ-Municipality of Rafina - Pikermi' WHERE id=21294;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΡΕΘΥΜΝΗΣ', name_latin=N'Municipality of Rethymno', abac_name=N'DEMOS REThUMNES', display_name=N'ΔΗΜΟΣ ΡΕΘΥΜΝΗΣ-Municipality of Rethymno' WHERE id=21371;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΡΗΓΑ ΦΕΡΑΙΟΥ', name_latin=N'Municipality of Rigas Fereos', abac_name=N'DEMOS REGA PhERAIOU', display_name=N'ΔΗΜΟΣ ΡΗΓΑ ΦΕΡΑΙΟΥ-Municipality of Rigas Fereos' WHERE id=21165;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΡΟΔΟΥ', name_latin=N'Municipality of Rodos', abac_name=N'DEMOS RODOU', display_name=N'ΔΗΜΟΣ ΡΟΔΟΥ-Municipality of Rodos' WHERE id=21353;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΑΛΑΜΙΝΟΣ', name_latin=N'Municipality of Salamina', abac_name=N'DEMOS SALAMINOS', display_name=N'ΔΗΜΟΣ ΣΑΛΑΜΙΝΟΣ-Municipality of Salamina' WHERE id=21308;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΑΜΟΘΡΑΚΗΣ', name_latin=N'Municipality of Samothraki', abac_name=N'DEMOS SAMOThRAKES', display_name=N'ΔΗΜΟΣ ΣΑΜΟΘΡΑΚΗΣ-Municipality of Samothraki' WHERE id=21070;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΑΜΟΥ', name_latin=N'Municipality of Samos', abac_name=N'DEMOS SAMOU', display_name=N'ΔΗΜΟΣ ΣΑΜΟΥ-Municipality of Samos' WHERE id=21321;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΑΡΩΝΙΚΟΥ', name_latin=N'Municipality of Saronikos', abac_name=N'DEMOS SARONIKOU', display_name=N'ΔΗΜΟΣ ΣΑΡΩΝΙΚΟΥ-Municipality of Saronikos' WHERE id=21295;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΕΡΒΙΩΝ - ΒΕΛΒΕΝΤΟΥ', name_latin=N'Municipality of Servia - Velvendos', abac_name=N'DEMOS SERBION - BELBENTOU', display_name=N'ΔΗΜΟΣ ΣΕΡΒΙΩΝ - ΒΕΛΒΕΝΤΟΥ-Municipality of Servia - Velvendos' WHERE id=21121;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΕΡΙΦΟΥ', name_latin=N'Municipality of Serifos', abac_name=N'DEMOS SERIPhOU', display_name=N'ΔΗΜΟΣ ΣΕΡΙΦΟΥ-Municipality of Serifos' WHERE id=21346;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΕΡΡΩΝ', name_latin=N'Municipality of Serres', abac_name=N'DEMOS SERRON', display_name=N'ΔΗΜΟΣ ΣΕΡΡΩΝ-Municipality of Serres' WHERE id=21106;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΗΤΕΙΑΣ', name_latin=N'Municipality of Sitia', abac_name=N'DEMOS SETEIAS', display_name=N'ΔΗΜΟΣ ΣΗΤΕΙΑΣ-Municipality of Sitia' WHERE id=21370;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΙΘΩΝΙΑΣ', name_latin=N'Municipality of Sithonia', abac_name=N'DEMOS SIThONIAS', display_name=N'ΔΗΜΟΣ ΣΙΘΩΝΙΑΣ-Municipality of Sithonia' WHERE id=21117;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΙΚΙΝΟΥ', name_latin=N'Municipality of Sikinos', abac_name=N'DEMOS SIKINOU', display_name=N'ΔΗΜΟΣ ΣΙΚΙΝΟΥ-Municipality of Sikinos' WHERE id=21330;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΙΚΥΩΝΙΩΝ', name_latin=N'Municipality of Sikyon', abac_name=N'DEMOS SIKUONION', display_name=N'ΔΗΜΟΣ ΣΙΚΥΩΝΙΩΝ-Municipality of Sikyon' WHERE id=21238;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΙΝΤΙΚΗΣ', name_latin=N'Municipality of Sintiki', abac_name=N'DEMOS SINTIKES', display_name=N'ΔΗΜΟΣ ΣΙΝΤΙΚΗΣ-Municipality of Sintiki' WHERE id=21112;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΙΦΝΟΥ', name_latin=N'Municipality of Sifnos', abac_name=N'DEMOS SIPhNOU', display_name=N'ΔΗΜΟΣ ΣΙΦΝΟΥ-Municipality of Sifnos' WHERE id=21347;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΚΙΑΘΟΥ', name_latin=N'Municipality of Skiathos', abac_name=N'DEMOS SKIAThOU', display_name=N'ΔΗΜΟΣ ΣΚΙΑΘΟΥ-Municipality of Skiathos' WHERE id=21166;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΚΟΠΕΛΟΥ', name_latin=N'Municipality of Skopelos', abac_name=N'DEMOS SKOPELOU', display_name=N'ΔΗΜΟΣ ΣΚΟΠΕΛΟΥ-Municipality of Skopelos' WHERE id=21168;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΚΥΔΡΑΣ', name_latin=N'Municipality of Skydra', abac_name=N'DEMOS SKUDRAS', display_name=N'ΔΗΜΟΣ ΣΚΥΔΡΑΣ-Municipality of Skydra' WHERE id=21102;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΚΥΡΟΥ', name_latin=N'Municipality of Skyros', abac_name=N'DEMOS SKUROU', display_name=N'ΔΗΜΟΣ ΣΚΥΡΟΥ-Municipality of Skyros' WHERE id=21193;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΟΥΛΙΟΥ', name_latin=N'Municipality of Souli', abac_name=N'DEMOS SOULIOU', display_name=N'ΔΗΜΟΣ ΣΟΥΛΙΟΥ-Municipality of Souli' WHERE id=21143;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΟΥΦΛΙΟΥ', name_latin=N'Municipality of Soufli', abac_name=N'DEMOS SOUPhLIOU', display_name=N'ΔΗΜΟΣ ΣΟΥΦΛΙΟΥ-Municipality of Soufli' WHERE id=21071;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΟΦΑΔΩΝ', name_latin=N'Municipality of Sofades', abac_name=N'DEMOS SOPhADON', display_name=N'ΔΗΜΟΣ ΣΟΦΑΔΩΝ-Municipality of Sofades' WHERE id=21160;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΠΑΡΤΗΣ', name_latin=N'Municipality of Sparti', abac_name=N'DEMOS SPARTES', display_name=N'ΔΗΜΟΣ ΣΠΑΡΤΗΣ-Municipality of Sparti' WHERE id=21239;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΠΑΤΩΝ - ΑΡΤΕΜΙΔΟΣ', name_latin=N'Municipality of Spata - Artemis', abac_name=N'DEMOS SPATON - ARTEMIDOS', display_name=N'ΔΗΜΟΣ ΣΠΑΤΩΝ - ΑΡΤΕΜΙΔΟΣ-Municipality of Spata - Artemis' WHERE id=21296;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΠΕΤΣΩΝ', name_latin=N'Municipality of Spetses', abac_name=N'DEMOS SPETSON', display_name=N'ΔΗΜΟΣ ΣΠΕΤΣΩΝ-Municipality of Spetses' WHERE id=21314;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΤΥΛΙΔΑΣ', name_latin=N'Municipality of Stylida', abac_name=N'DEMOS STULIDAS', display_name=N'ΔΗΜΟΣ ΣΤΥΛΙΔΑΣ-Municipality of Stylida' WHERE id=21179;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΥΜΗΣ', name_latin=N'Municipality of Symi', abac_name=N'DEMOS SUMES', display_name=N'ΔΗΜΟΣ ΣΥΜΗΣ-Municipality of Symi' WHERE id=21355;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΥΡΟΥ - ΕΡΜΟΥΠΟΛΗΣ', name_latin=N'Municipality of Syros - Ermoupoli', abac_name=N'DEMOS SUROU - ERMOUPOLES', display_name=N'ΔΗΜΟΣ ΣΥΡΟΥ - ΕΡΜΟΥΠΟΛΗΣ-Municipality of Syros - Ermoupoli' WHERE id=21325;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΣΦΑΚΙΩΝ', name_latin=N'Municipality of Sfakia', abac_name=N'DEMOS SPhAKION', display_name=N'ΔΗΜΟΣ ΣΦΑΚΙΩΝ-Municipality of Sfakia' WHERE id=21382;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΤΑΝΑΓΡΑΣ', name_latin=N'Municipality of Tanagra', abac_name=N'DEMOS TANAGRAS', display_name=N'ΔΗΜΟΣ ΤΑΝΑΓΡΑΣ-Municipality of Tanagra' WHERE id=21185;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΤΕΜΠΩΝ', name_latin=N'Municipality of Tempi', abac_name=N'DEMOS TEMPON', display_name=N'ΔΗΜΟΣ ΤΕΜΠΩΝ-Municipality of Tempi' WHERE id=21152;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΤΗΛΟΥ', name_latin=N'Municipality of Tilos', abac_name=N'DEMOS TELOU', display_name=N'ΔΗΜΟΣ ΤΗΛΟΥ-Municipality of Tilos' WHERE id=21356;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΤΗΝΟΥ', name_latin=N'Municipality of Tinos', abac_name=N'DEMOS TENOU', display_name=N'ΔΗΜΟΣ ΤΗΝΟΥ-Municipality of Tinos' WHERE id=21358;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΤΟΠΕΙΡΟΥ', name_latin=N'Municipality of Topiros', abac_name=N'DEMOS TOPEIROU', display_name=N'ΔΗΜΟΣ ΤΟΠΕΙΡΟΥ-Municipality of Topiros' WHERE id=21079;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΤΡΙΚΚΑΙΩΝ', name_latin=N'Municipality of Trikala', abac_name=N'DEMOS TRIKKAION', display_name=N'ΔΗΜΟΣ ΤΡΙΚΚΑΙΩΝ-Municipality of Trikala' WHERE id=21169;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΤΡΙΠΟΛΗΣ', name_latin=N'Municipality of Tripoli', abac_name=N'DEMOS TRIPOLES', display_name=N'ΔΗΜΟΣ ΤΡΙΠΟΛΗΣ-Municipality of Tripoli' WHERE id=21224;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΤΡΙΦΥΛΙΑΣ', name_latin=N'Municipality of Trifylia', abac_name=N'DEMOS TRIPhULIAS', display_name=N'ΔΗΜΟΣ ΤΡΙΦΥΛΙΑΣ-Municipality of Trifylia' WHERE id=21249;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΤΡΟΙΖΗΝΙΑΣ-ΜΕΘΑΝΩΝ', name_latin=N'Municipality of Trizina - Methana', abac_name=N'DEMOS TROIZENIAS-METhANON', display_name=N'ΔΗΜΟΣ ΤΡΟΙΖΗΝΙΑΣ-ΜΕΘΑΝΩΝ-Municipality of Trizina - Methana' WHERE id=21315;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΤΥΡΝΑΒΟΥ', name_latin=N'Municipality of Tyrnavos', abac_name=N'DEMOS TURNABOU', display_name=N'ΔΗΜΟΣ ΤΥΡΝΑΒΟΥ-Municipality of Tyrnavos' WHERE id=21153;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΎΔΡΑΣ', name_latin=N'Municipality of Ydra', abac_name=N'DEMOS UDRAS', display_name=N'ΔΗΜΟΣ ΎΔΡΑΣ-Municipality of Ydra' WHERE id=21309;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΦΑΙΣΤΟΥ', name_latin=N'Municipality of Faistos', abac_name=N'DEMOS PhAISTOU', display_name=N'ΔΗΜΟΣ ΦΑΙΣΤΟΥ-Municipality of Faistos' WHERE id=21365;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΦΑΡΚΑΔΟΝΑΣ', name_latin=N'Municipality of Farkadona', abac_name=N'DEMOS PhARKADONAS', display_name=N'ΔΗΜΟΣ ΦΑΡΚΑΔΟΝΑΣ-Municipality of Farkadona' WHERE id=21172;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΦΑΡΣΑΛΩΝ', name_latin=N'Municipality of Farsala', abac_name=N'DEMOS PhARSALON', display_name=N'ΔΗΜΟΣ ΦΑΡΣΑΛΩΝ-Municipality of Farsala' WHERE id=21154;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΦΙΛΙΑΤΩΝ', name_latin=N'Municipality of Filiates', abac_name=N'DEMOS PhILIATON', display_name=N'ΔΗΜΟΣ ΦΙΛΙΑΤΩΝ-Municipality of Filiates' WHERE id=21144;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΦΙΛΟΘΕΗΣ - ΨΥΧΙΚΟΥ', name_latin=N'Municipality of Filothei - Psychiko', abac_name=N'DEMOS PhILOThEES - PsUKhIKOU', display_name=N'ΔΗΜΟΣ ΦΙΛΟΘΕΗΣ - ΨΥΧΙΚΟΥ-Municipality of Filothei - Psychiko' WHERE id=21268;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΦΛΩΡΙΝΑΣ', name_latin=N'Municipality of Florina', abac_name=N'DEMOS PhLORINAS', display_name=N'ΔΗΜΟΣ ΦΛΩΡΙΝΑΣ-Municipality of Florina' WHERE id=21127;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΦΟΛΕΓΑΝΔΡΟΥ', name_latin=N'Municipality of Folegandros', abac_name=N'DEMOS PhOLEGANDROU', display_name=N'ΔΗΜΟΣ ΦΟΛΕΓΑΝΔΡΟΥ-Municipality of Folegandros' WHERE id=21331;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΦΟΥΡΝΩΝ ΚΟΡΣΕΩΝ', name_latin=N'Municipality of Fourni Korseon', abac_name=N'DEMOS PhOURNON KORSEON', display_name=N'ΔΗΜΟΣ ΦΟΥΡΝΩΝ ΚΟΡΣΕΩΝ-Municipality of Fourni Korseon' WHERE id=21318;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΦΥΛΗΣ', name_latin=N'Municipality of Fyli', abac_name=N'DEMOS PhULES', display_name=N'ΔΗΜΟΣ ΦΥΛΗΣ-Municipality of Fyli' WHERE id=21302;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΧΑΪΔΑΡΙΟΥ', name_latin=N'Municipality of Chaidari', abac_name=N'DEMOS KhAIDARIOU', display_name=N'ΔΗΜΟΣ ΧΑΪΔΑΡΙΟΥ-Municipality of Chaidari' WHERE id=21276;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΧΑΛΑΝΔΡΙΟΥ', name_latin=N'Municipality of Chalandri', abac_name=N'DEMOS KhALANDRIOU', display_name=N'ΔΗΜΟΣ ΧΑΛΑΝΔΡΙΟΥ-Municipality of Chalandri' WHERE id=21269;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΧΑΛΚΗΔΟΝΟΣ', name_latin=N'Municipality of Chalkidona', abac_name=N'DEMOS KhALKEDONOS', display_name=N'ΔΗΜΟΣ ΧΑΛΚΗΔΟΝΟΣ-Municipality of Chalkidona' WHERE id=21092;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΧΑΛΚΗΣ', name_latin=N'Municipality of Chalki', abac_name=N'DEMOS KhALKES', display_name=N'ΔΗΜΟΣ ΧΑΛΚΗΣ-Municipality of Chalki' WHERE id=21357;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΧΑΛΚΙΔΕΩΝ', name_latin=N'Municipality of Chalkida', abac_name=N'DEMOS KhALKIDEON', display_name=N'ΔΗΜΟΣ ΧΑΛΚΙΔΕΩΝ-Municipality of Chalkida' WHERE id=21186;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΧΑΝΙΩΝ', name_latin=N'Municipality of Chania', abac_name=N'DEMOS KhANION', display_name=N'ΔΗΜΟΣ ΧΑΝΙΩΝ-Municipality of Chania' WHERE id=21376;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΧΕΡΣΟΝΗΣΟΥ', name_latin=N'Municipality of Chersonissos', abac_name=N'DEMOS KhERSONESOU', display_name=N'ΔΗΜΟΣ ΧΕΡΣΟΝΗΣΟΥ-Municipality of Chersonissos' WHERE id=21366;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΧΙΟΥ', name_latin=N'Municipality of Chios', abac_name=N'DEMOS KhIOU', display_name=N'ΔΗΜΟΣ ΧΙΟΥ-Municipality of Chios' WHERE id=21322;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΨΑΡΩΝ', name_latin=N'Municipality of Psara', abac_name=N'DEMOS PsARON', display_name=N'ΔΗΜΟΣ ΨΑΡΩΝ-Municipality of Psara' WHERE id=21324;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΩΡΑΙΟΚΑΣΤΡΟΥ', name_latin=N'Municipality of Oreokastro', abac_name=N'DEMOS ORAIOKASTROU', display_name=N'ΔΗΜΟΣ ΩΡΑΙΟΚΑΣΤΡΟΥ-Municipality of Oreokastro' WHERE id=21093;
UPDATE laus SET name_national=N'ΔΗΜΟΣ ΩΡΩΠΟΥ', name_latin=N'Municipality of Oropos', abac_name=N'DEMOS OROPOU', display_name=N'ΔΗΜΟΣ ΩΡΩΠΟΥ-Municipality of Oropos' WHERE id=21297;


--327
--select nuts3, lau1, name_national, name_latin, abac_name, display_name, id 
--from laus where country_code = 'EL' order by name1 asc


update laus set nuts3='EL527' where id=21383;