-- MySQL Script generated by MySQL Workbench
-- Wed Oct 11 14:33:16 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbo`;
-- -----------------------------------------------------
-- Schema dbo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbo`
  DEFAULT CHARACTER SET utf8
  COLLATE utf8_bin;
USE `dbo`;

CREATE TABLE IF NOT EXISTS `dbo`.`SEQUENCE` (
  `SEQ_NAME`  VARCHAR(50) NOT NULL,
  `SEQ_COUNT` NUMERIC(38),
  PRIMARY KEY (`SEQ_NAME`)
);

-- -----------------------------------------------------
-- Table `dbo`.`audit_data_t`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AUDIT_DATA_T` (
  `AUDIT_DATA_ID`    INT(11) NOT NULL,
  `REQUEST_ENDPOINT` VARCHAR(255)
                     COLLATE utf8_bin DEFAULT NULL,
  `REQUEST_METHOD`   VARCHAR(255)
                     COLLATE utf8_bin DEFAULT NULL,
  `REQUEST_BODY`     BLOB,
  `RESPONSE_BODY`    BLOB,
  `USER_ID`          INT(11)          DEFAULT NULL
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8
  COLLATE = utf8_bin;

-- -----------------------------------------------------
-- Table `dbo`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`users` (
  `id`          INT          NOT NULL,
  `treatment`   VARCHAR(45)  NULL,
  `name`        VARCHAR(255) NULL,
  `surname`     VARCHAR(255) NULL,
  `address`     VARCHAR(255) NULL,
  `address_num` VARCHAR(255) NULL,
  `postal_code` VARCHAR(255) NULL,
  `email`       VARCHAR(255) NULL,
  `password`    VARCHAR(255) NULL,
  `create_date` BIGINT       NULL,
  `access_date` BIGINT       NULL,
  `ecas_email`  VARCHAR(255) NULL,
  `ecas_username`  VARCHAR(255) NULL,
  `type`        INT          NULL     DEFAULT NULL,
  `verified`    TINYINT      NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dbo`.`laus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`laus` (
  `id`               INT          NOT NULL,
  `country_code`     VARCHAR(255) NULL,
  `nuts3`            VARCHAR(255) NULL,
  `lau1`             VARCHAR(255) NULL,
  `lau2`             VARCHAR(255) NULL,
  `_change`          VARCHAR(255) NULL,
  `name1`            VARCHAR(255) NULL,
  `name2`            VARCHAR(255) NULL,
  `pop`              VARCHAR(255) NULL,
  `area`             VARCHAR(255) NULL,
  `physical_address` VARCHAR(255) NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dbo`.`municipalities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`municipalities` (
  `id`          INT          NOT NULL,
  `name`        VARCHAR(255) NULL,
  `address`     VARCHAR(255) NULL,
  `address_num` VARCHAR(255) NULL,
  `postal_code` VARCHAR(255) NULL,
  `country`     VARCHAR(255) NULL,
  `lau`         INT          NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_municipalities_laus1_idx` (`lau` ASC),
  CONSTRAINT `fk_municipalities_laus`
  FOREIGN KEY (`lau`)
  REFERENCES `dbo`.`laus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dbo`.`registrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`registrations` (
  `id`           INT          NOT NULL,
  `_user`        INT          NOT NULL,
  `municipality` INT          NOT NULL,
  `role`         VARCHAR(500) NULL,
  `_status`      INT(1)       NOT NULL, --  0=HOLD; 1=KO; 2=OK
  PRIMARY KEY (`id`),
  INDEX `fk_user_idx` (`_user` ASC),
  INDEX `fk_municipality_idx` (`municipality` ASC),
  CONSTRAINT `fk_registrations_users`
  FOREIGN KEY (`_user`)
  REFERENCES `dbo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registrations_municipalities`
  FOREIGN KEY (`municipality`)
  REFERENCES `dbo`.`municipalities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dbo`.`calls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`calls` (
  `id`         INT          NOT NULL,
  `event`      VARCHAR(500) NULL,
  `start_date` BIGINT       NULL,
  `end_date`   BIGINT       NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dbo`.`nuts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`nuts` (
  `id`           INT          NOT NULL,
  `code`         VARCHAR(255) NULL,
  `label`        VARCHAR(255) NULL,
  `level`        INT          NULL,
  `country_code` VARCHAR(255) NULL,
  `_order`       INT          NULL,
  `sorting`      INT          NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dbo`.`threads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`threads` (
  `id`    INT          NOT NULL,
  `title` VARCHAR(255) NULL,
  `reason`   VARCHAR(255) NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`id`)

)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dbo`.`thread_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`thread_messages` (
  `id`          INT        NOT NULL,
  `thread`      INT        NOT NULL,
  `author`      INT        NOT NULL,
  `message`     MEDIUMTEXT NULL,
  `create_date` BIGINT     NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_thread_idx` (`thread` ASC),
  INDEX `fk_author_idx` (`author` ASC),
  CONSTRAINT `fk_thread_messages_threads`
  FOREIGN KEY (`thread`)
  REFERENCES `dbo`.`threads` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_thread_messages_users`
  FOREIGN KEY (`author`)
  REFERENCES `dbo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dbo`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`suppliers` (
  `id`                   INT          NOT NULL,
  `name`                 VARCHAR(255) NULL,
  `address`              VARCHAR(255) NULL,
  `vat`                  VARCHAR(255) NULL,
  `bic`                  VARCHAR(255) NULL,
  `account_number`       VARCHAR(255) NULL,
  `website`              VARCHAR(255) NULL,
  `contact_name`         VARCHAR(255) NULL,
  `contact_surname`      VARCHAR(255) NULL,
  `contact_phone_prefix` VARCHAR(255) NULL,
  `contact_phone_number` VARCHAR(255) NULL,
  `contact_email`        VARCHAR(255) NULL,
  `logo`                 LONGTEXT     NULL,
  `_user`                INT          NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_suppliers_users_idx` (`_user` ASC),
  CONSTRAINT `fk_suppliers_users`
  FOREIGN KEY (`_user`)
  REFERENCES `dbo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_bin;

-- -----------------------------------------------------
-- Table `dbo`.`applications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`applications` (
  `id`              INT     NOT NULL,
  `call_id`         INT     NOT NULL,
  `registration`    INT     NOT NULL,
  `supplier`        INT     NULL,
  `voucher_awarded` TINYINT NULL     DEFAULT 0,
  `date`            BIGINT  NULL,
  `lef_export`      BIGINT  NULL,
  `lef_import`      BIGINT  NULL,
  `lef_status`      INT     NULL     DEFAULT 0,
  `bc_export`       BIGINT  NULL,
  `bc_import`       BIGINT  NULL,
  `bc_status`       INT     NULL     DEFAULT 0,
  `lc_export`       BIGINT  NULL,
  `lc_import`       BIGINT  NULL,
  `lc_status`       INT     NULL     DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_call_idx` (`call_id` ASC),
  INDEX `fk_registration_idx` (`registration` ASC),
  INDEX `fk_applications_supplier_idx` (`supplier` ASC),
  CONSTRAINT `fk_applications_calls`
  FOREIGN KEY (`call_id`)
  REFERENCES `dbo`.`calls` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_applications_registrations`
  FOREIGN KEY (`registration`)
  REFERENCES `dbo`.`registrations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_applications_suppliers`
  FOREIGN KEY (`supplier`)
  REFERENCES `dbo`.`suppliers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dbo`.`mayors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`mayors` (
  `id`           INT          NOT NULL,
  `name`         VARCHAR(255) NULL,
  `surname`      VARCHAR(255) NULL,
  `treatment`    VARCHAR(255) NULL,
  `email`        VARCHAR(255) NULL,
  `municipality` INT          NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mayors_municipalities_idx` (`municipality` ASC),
  CONSTRAINT `fk_mayors_municipalities`
  FOREIGN KEY (`municipality`)
  REFERENCES `dbo`.`municipalities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dbo`.`representations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`representations` (
  `id`           INT NOT NULL,
  `municipality` INT NOT NULL,
  `mayor`        INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_municipality_idx` (`municipality` ASC),
  INDEX `fk_mayor_idx` (`mayor` ASC),
  CONSTRAINT `fk_representations_municipalities`
  FOREIGN KEY (`municipality`)
  REFERENCES `dbo`.`municipalities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_representations_mayors`
  FOREIGN KEY (`mayor`)
  REFERENCES `dbo`.`mayors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dbo`.`access_points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`access_points` (
  `id`            INT          NOT NULL,
  `municipality`  INT          NULL,
  `name`          VARCHAR(255) NULL,
  `product_name`  VARCHAR(255) NULL,
  `model_number`  VARCHAR(255) NULL,
  `serial_number` VARCHAR(255) NULL,
  `indoor`        TINYINT      NULL     DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_municipality_idx` (`municipality` ASC),
  CONSTRAINT `fk_access_points_municipalities`
  FOREIGN KEY (`municipality`)
  REFERENCES `dbo`.`municipalities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dbo`.`supplied_regions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`supplied_regions` (
  `id`       INT NOT NULL,
  `supplier` INT NOT NULL,
  `region`   INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_supplier_regions_supplier_idx` (`supplier` ASC),
  INDEX `fk_supplier_regions_region_idx` (`region` ASC),
  CONSTRAINT `fk_supplier_regions_suppliers`
  FOREIGN KEY (`supplier`)
  REFERENCES `dbo`.`suppliers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_regions_nuts`
  FOREIGN KEY (`region`)
  REFERENCES `dbo`.`nuts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_bin;

-- -----------------------------------------------------
-- Table `dbo`.`helpdesk_issues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`helpdesk_issues` (
  `id`           INT          NOT NULL,
  `from_email`   VARCHAR(255) NULL,
  `assigned_to`  VARCHAR(255) NULL,
  `topic`        VARCHAR(255) NULL,
  `portal`       VARCHAR(255) NULL,
  `member_state` VARCHAR(255) NULL,
  `summary`      MEDIUMTEXT   NULL,
  `create_date`  BIGINT       NULL,
  `_status`      INT          NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_bin;

-- -----------------------------------------------------
-- Table `dbo`.`helpdesk_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`helpdesk_comments` (
  `id`          INT          NOT NULL,
  `issue`       INT          NULL,
  `from_email`  VARCHAR(255) NULL,
  `comment`     MEDIUMTEXT   NULL,
  `create_date` BIGINT       NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_helpdesk_comments_issue_idx` (`issue` ASC),
  CONSTRAINT `fk_helpdesk_comments_issues`
  FOREIGN KEY (`issue`)
  REFERENCES `dbo`.`helpdesk_issues` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_bin;

-- -----------------------------------------------------
-- Table `dbo`.`timelines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`timelines` (
  `id`          INT          NOT NULL,
  `call_id`     INT          NULL,
  `description` VARCHAR(255) NULL,
  `start_date`  BIGINT       NULL,
  `end_date`    BIGINT       NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_timelines_call_id_idx` (`call_id` ASC),
  CONSTRAINT `fk_timelines_call_id`
  FOREIGN KEY (`call_id`)
  REFERENCES `dbo`.`calls` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_bin;

-- -----------------------------------------------------
-- Table `dbo`.`temp_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`temp_tokens` (
  `id`          BIGINT       NOT NULL,
  `token`       VARCHAR(255) NULL,
  `email`       VARCHAR(255) NULL,
  `create_date` BIGINT       NULL,
  `expiry_date` BIGINT       NULL,
  `_user`       INT          NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_temp_tokens_users_idx` (`_user` ASC),
  CONSTRAINT `fk_temp_tokens_users`
  FOREIGN KEY (`_user`)
  REFERENCES `dbo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dbo`.`organizations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`organizations` (
  `id`      INT          NOT NULL,
  `name`    VARCHAR(255) NULL,
  `type`    VARCHAR(255) NULL,
  `country` VARCHAR(255) NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;
INSERT INTO `dbo`.`organizations` (name, type, country)
VALUES ('Everis', 'private', 'ES');

-- -----------------------------------------------------
-- Table `dbo`.`user_threads`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `dbo`.`user_threads` (
  `id` int(11) NOT NULL,
  `user` int(11) NOT NULL,
  `thread` int(11) NOT NULL,
   PRIMARY KEY (`id`)
)

SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
