-- MySQL Script generated by MySQL Workbench
-- Thu Sep 28 12:08:03 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema wifi4eu-new
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wifi4eu-new
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wifi4eu-new` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `wifi4eu-new` ;

-- -----------------------------------------------------
-- Table `wifi4eu-new`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wifi4eu-new`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `surname` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `create_date` BIGINT NULL,
  `access_date` BIGINT NULL,
  `verified` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wifi4eu-new`.`laus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wifi4eu-new`.`laus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country_code` VARCHAR(255) NULL,
  `nuts3` VARCHAR(255) NULL,
  `lau1` VARCHAR(255) NULL,
  `lau2` VARCHAR(255) NULL,
  `_change` VARCHAR(255) NULL,
  `name1` VARCHAR(255) NULL,
  `name2` VARCHAR(255) NULL,
  `pop` INT NULL,
  `area` INT NULL,
  `physical_address` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wifi4eu-new`.`municipalities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wifi4eu-new`.`municipalities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `address` VARCHAR(500) NULL,
  `laus` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_municipalities_laus1_idx` (`laus` ASC),
  CONSTRAINT `fk_municipalities_laus`
    FOREIGN KEY (`laus`)
    REFERENCES `wifi4eu-new`.`laus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wifi4eu-new`.`threads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wifi4eu-new`.`threads` (
  `id` INT NOT NULL,
  `title` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wifi4eu-new`.`registrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wifi4eu-new`.`registrations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` INT NOT NULL,
  `municipality` INT NOT NULL,
  `role` VARCHAR(500) NULL,
  `thread` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_idx` (`user` ASC),
  INDEX `fk_municipality_idx` (`municipality` ASC),
  INDEX `fk_thread_idx` (`thread` ASC),
  CONSTRAINT `fk_registrations_user`
    FOREIGN KEY (`user`)
    REFERENCES `wifi4eu-new`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registrations_municipality`
    FOREIGN KEY (`municipality`)
    REFERENCES `wifi4eu-new`.`municipalities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registrations_thread`
    FOREIGN KEY (`thread`)
    REFERENCES `wifi4eu-new`.`threads` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wifi4eu-new`.`calls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wifi4eu-new`.`calls` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event` VARCHAR(500) NULL,
  `start_date` TIMESTAMP NULL,
  `end_date` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wifi4eu-new`.`nuts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wifi4eu-new`.`nuts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NULL,
  `label` VARCHAR(255) NULL,
  `level` INT NULL,
  `country_code` VARCHAR(255) NULL,
  `_order` INT NULL,
  `sorting` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wifi4eu-new`.`thread_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wifi4eu-new`.`thread_messages` (
  `id` INT NOT NULL,
  `thread` INT NOT NULL,
  `author` INT NOT NULL,
  `message` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_thread_idx` (`thread` ASC),
  INDEX `fk_author_idx` (`author` ASC),
  CONSTRAINT `fk_thread_messages_thread`
    FOREIGN KEY (`thread`)
    REFERENCES `wifi4eu-new`.`threads` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_thread_messages_author`
    FOREIGN KEY (`author`)
    REFERENCES `wifi4eu-new`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wifi4eu-new`.`applications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wifi4eu-new`.`applications` (
  `id` INT NOT NULL,
  `call` INT NOT NULL,
  `registration` INT NOT NULL,
  `supplier` INT NULL,
  `voucher_awarded` TINYINT NULL DEFAULT 0,
  `date` BIGINT NULL,
  `lef_export` BIGINT NULL,
  `lef_import` BIGINT NULL,
  `lef_status` INT NULL DEFAULT 0,
  `bc_export` BIGINT NULL,
  `bc_import` BIGINT NULL,
  `bc_status` INT NULL DEFAULT 0,
  `lc_export` BIGINT NULL,
  `lc_import` BIGINT NULL,
  `lc_status` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_call_idx` (`call` ASC),
  INDEX `fk_registration_idx` (`registration` ASC),
  CONSTRAINT `fk_applications_call`
    FOREIGN KEY (`call`)
    REFERENCES `wifi4eu-new`.`calls` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_applications_registration`
    FOREIGN KEY (`registration`)
    REFERENCES `wifi4eu-new`.`registrations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wifi4eu-new`.`mayors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wifi4eu-new`.`mayors` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `surname` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wifi4eu-new`.`representations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wifi4eu-new`.`representations` (
  `id` INT NOT NULL,
  `municipality` INT NOT NULL,
  `mayor` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_municipality_idx` (`municipality` ASC),
  INDEX `fk_mayor_idx` (`mayor` ASC),
  CONSTRAINT `fk_representations_municipality`
    FOREIGN KEY (`municipality`)
    REFERENCES `wifi4eu-new`.`municipalities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_representations_mayor`
    FOREIGN KEY (`mayor`)
    REFERENCES `wifi4eu-new`.`mayors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wifi4eu-new`.`access_points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wifi4eu-new`.`access_points` (
  `id` INT NOT NULL,
  `municipality` INT NULL,
  `name` VARCHAR(255) NULL,
  `product_name` VARCHAR(255) NULL,
  `model_number` VARCHAR(255) NULL,
  `serial_number` VARCHAR(255) NULL,
  `indoor` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_municipality_idx` (`municipality` ASC),
  CONSTRAINT `fk_access_points_municipality`
    FOREIGN KEY (`municipality`)
    REFERENCES `wifi4eu-new`.`municipalities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
