<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- edited with XMLSpy v2011 rel. 2 sp1 (http://www.altova.com) by - - (European Commission DG BUDGET) -->
<!-- BUDG version 0.06 -->
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tub="http://www.ec.europa.eu/budg/abac/soatube/v1" xmlns:tns="http://www.ec.europa.eu/budg/abac/soatube/service/es/async/v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" name="Soatube" targetNamespace="http://www.ec.europa.eu/budg/abac/soatube/service/es/async/v1">
	<wsdl:types>
		<xsd:schema targetNamespace="http://www.ec.europa.eu/budg/abac/soatube/v1">
			<xsd:include schemaLocation="BUDG_Soatube_Async_1.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="SoatubeRequest">
		<wsdl:part name="request" element="tub:SoatubeRequest"/>
	</wsdl:message>
	<wsdl:portType name="Soatube">
		<wsdl:operation name="Invoke">
			<wsdl:input message="tns:SoatubeRequest"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="SoatubeSOAP" type="tns:Soatube">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="Invoke">
			<soap:operation soapAction="http://www.ec.europa.eu/budg/abac/soatube/service/es/async/invoke/v1"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
</wsdl:definitions>
