
package eu.europa.ec.budg.abac.soatube.service.es.sync.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import eu.europa.ec.budg.abac.soatube.v1.SoatubeRequestType;
import eu.europa.ec.budg.abac.soatube.v1.SoatubeResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Soatube", targetNamespace = "http://www.ec.europa.eu/budg/abac/soatube/service/es/sync/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    eu.europa.ec.budg.abac.message.v1.ObjectFactory.class,
    eu.europa.ec.budg.abac.soatube.v1.ObjectFactory.class,
    eu.europa.ec.budg.abac.br.v1.ObjectFactory.class
})
public interface Soatube {


    /**
     * 
     * @param parameters
     * @return
     *     returns eu.europa.ec.budg.abac.soatube.v1.SoatubeResponseType
     */
    @WebMethod(action = "http://www.ec.europa.eu/budg/abac/soatube/service/es/sync/find/v1")
    @WebResult(name = "SoatubeResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/soatube/v1", partName = "parameters")
    public SoatubeResponseType invoke(
            @WebParam(name = "SoatubeRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/soatube/v1", partName = "parameters")
                    SoatubeRequestType parameters);

}
