
package eu.europa.ec.budg.abac.soatube.service.es.sync.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
//@WebServiceClient(name = "Soatube", targetNamespace = "http://www.ec.europa.eu/budg/abac/soatube/service/es/sync/v1", wsdlLocation = "http://localhost/soatube-1-read/BUDG_Soatube_ES_Sync_1.wsdl")
//@WebServiceClient(name = "Soatube", targetNamespace = "http://www.ec.europa.eu/budg/abac/soatube/service/es/sync/v1", wsdlLocation = "http://localhost:7001/wifi4eu-financial/soatube-1-read/BUDG_Soatube_ES_Sync_1.wsdl")
@WebServiceClient(name = "Soatube", targetNamespace = "http://www.ec.europa.eu/budg/abac/soatube/service/es/sync/v1", wsdlLocation = "http://wlts0275.cc.cec.eu.int:1043/wifi4eu-financial/soatube-1-read/BUDG_Soatube_ES_Sync_1.wsdl")
public class Soatube_Service
    extends Service
{

    private final static URL SOATUBE_WSDL_LOCATION;
    private final static WebServiceException SOATUBE_EXCEPTION;
    private final static QName SOATUBE_QNAME = new QName("http://www.ec.europa.eu/budg/abac/soatube/service/es/sync/v1", "Soatube");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("http://localhost/soatube-1-read/BUDG_Soatube_ES_Sync_1.wsdl");
            //url = new URL("http://localhost:7001/wifi4eu-financial/soatube-1-read/BUDG_Soatube_ES_Sync_1.wsdl");
            url = new URL("http://wlts0275.cc.cec.eu.int:1043/wifi4eu-financial/soatube-1-read/BUDG_Soatube_ES_Sync_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOATUBE_WSDL_LOCATION = url;
        SOATUBE_EXCEPTION = e;
    }

    public Soatube_Service() {
        super(__getWsdlLocation(), SOATUBE_QNAME);
    }

    public Soatube_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOATUBE_QNAME, features);
    }

    public Soatube_Service(URL wsdlLocation) {
        super(wsdlLocation, SOATUBE_QNAME);
    }

    public Soatube_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOATUBE_QNAME, features);
    }

    public Soatube_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Soatube_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Soatube
     */
    @WebEndpoint(name = "SoatubeSOAP")
    public Soatube getSoatubeSOAP() {
        return super.getPort(new QName("http://www.ec.europa.eu/budg/abac/soatube/service/es/sync/v1", "SoatubeSOAP"), Soatube.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Soatube
     */
    @WebEndpoint(name = "SoatubeSOAP")
    public Soatube getSoatubeSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ec.europa.eu/budg/abac/soatube/service/es/sync/v1", "SoatubeSOAP"), Soatube.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOATUBE_EXCEPTION!= null) {
            throw SOATUBE_EXCEPTION;
        }
        return SOATUBE_WSDL_LOCATION;
    }

}
