<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	name="RejectionWSV1"  
	xmlns:reject="http://ec.europa.eu/rdg/jagate/ws/rejection/v1/interfaces"
	targetNamespace="http://ec.europa.eu/rdg/jagate/ws/rejection/v1"
	xmlns="http://ec.europa.eu/rdg/jagate/ws/rejection/v1">

	<!-- Types -->
	<wsdl:types>
		<xs:schema>
			<xs:import namespace="http://ec.europa.eu/rdg/jagate/ws/rejection/v1/interfaces" schemaLocation="RejectionInterface.xsd" />
		</xs:schema>
	</wsdl:types>

	<!-- Messages -->
	<wsdl:message name="RejectTransactionRequest">
		<wsdl:part element="reject:RejectTransactionRequest" name="request" />
	</wsdl:message>

	<wsdl:message name="RejectTransactionResponse">
		<wsdl:part element="reject:RejectTransactionResponse" name="response" />
	</wsdl:message>

	<wsdl:message name="RejectTransactionException">
		<wsdl:part element="reject:RejectTransactionException" name="exception" />
	</wsdl:message>	
	
	<wsdl:portType name="IRejectionService">
		<wsdl:documentation>Performs rejection on transaction</wsdl:documentation>
		<wsdl:operation name="RejectTransaction">
			<wsdl:documentation>For compass rejection</wsdl:documentation>
			<wsdl:input message="RejectTransactionRequest" />
			<wsdl:output message="RejectTransactionResponse" />
			<wsdl:fault name="RejectTransactionException" message="RejectTransactionException"/>
		</wsdl:operation>
	</wsdl:portType>

	<!-- Binding -->
	<wsdl:binding name="IRejectionServiceBinding" type="IRejectionService">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="RejectTransaction">
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
			<wsdl:fault name="RejectTransactionException">
				<soap:fault name="RejectTransactionException" use="literal" />
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>

	<!-- Service definition -->
	<wsdl:service name="RejectionService">
		<wsdl:port binding="IRejectionServiceBinding" name="RejectionServiceBinding">
			<soap:address location="http://ec.europa.eu/rdg/jagate/ws/rejection/v1"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>