update nuts set label=N'Belgique-België' where level = 0 and label=N'BELGIQUE-BELGIË';
update nuts set label=N'България (Bulgaria)' where level = 0 and label=N'БЪЛГАРИЯ (BULGARIA)';
update nuts set label=N'Česká Republika' where level = 0 and label=N'ČESKÁ REPUBLIKA';
update nuts set label=N'Danmark' where level = 0 and label=N'DANMARK';
update nuts set label=N'Deutschland' where level = 0 and label=N'DEUTSCHLAND';
update nuts set label=N'Eesti' where level = 0 and label=N'EESTI';
update nuts set label=N'Ireland' where level = 0 and label=N'IRELAND';
update nuts set label=N'Ελλαδα (Ellada)' where level = 0 and label=N'ΕΛΛΑΔΑ (ELLADA)';
update nuts set label=N'España' where level = 0 and label=N'ESPAÑA';
update nuts set label=N'France' where level = 0 and label=N'FRANCE';
update nuts set label=N'Hrvatska' where level = 0 and label=N'HRVATSKA';
update nuts set label=N'Italia' where level = 0 and label=N'ITALIA';
update nuts set label=N'Κυπρος (Kypros)' where level = 0 and label=N'ΚΥΠΡΟΣ (KYPROS)';
update nuts set label=N'Latvija' where level = 0 and label=N'LATVIJA';
update nuts set label=N'Lietuva' where level = 0 and label=N'LIETUVA';
update nuts set label=N'Luxembourg' where level = 0 and label=N'LUXEMBOURG';
update nuts set label=N'Magyarország' where level = 0 and label=N'MAGYARORSZÁG';
update nuts set label=N'Malta' where level = 0 and label=N'MALTA';
update nuts set label=N'Nederland' where level = 0 and label=N'NEDERLAND';
update nuts set label=N'Österreich' where level = 0 and label=N'ÖSTERREICH';
update nuts set label=N'Polska' where level = 0 and label=N'POLSKA';
update nuts set label=N'Portugal' where level = 0 and label=N'PORTUGAL';
update nuts set label=N'România' where level = 0 and label=N'ROMÂNIA';
update nuts set label=N'Slovenija' where level = 0 and label=N'SLOVENIJA';
update nuts set label=N'Slovensko' where level = 0 and label=N'SLOVENSKO';
update nuts set label=N'Suomi / Finland' where level = 0 and label=N'SUOMI / FINLAND';
update nuts set label=N'Sverige' where level = 0 and label=N'SVERIGE';
update nuts set label=N'United Kingdom' where level = 0 and label=N'UNITED KINGDOM';
update nuts set label=N'Norway' where level = 0 and label=N'NORWAY';
update nuts set label=N'Iceland' where level = 0 and label=N'ICELAND';

update municipalities set country=N'Belgique-België' where country=N'BELGIQUE-BELGIË';
update municipalities set country=N'България (Bulgaria)' where country=N'БЪЛГАРИЯ (BULGARIA)';
update municipalities set country=N'Česká Republika' where country=N'ČESKÁ REPUBLIKA';
update municipalities set country=N'Danmark' where country=N'DANMARK';
update municipalities set country=N'Deutschland' where country=N'DEUTSCHLAND';
update municipalities set country=N'Eesti' where country=N'EESTI';
update municipalities set country=N'Ireland' where country=N'IRELAND';
update municipalities set country=N'Ελλαδα (Ellada)' where country=N'ΕΛΛΑΔΑ (ELLADA)';
update municipalities set country=N'España' where country=N'ESPAÑA';
update municipalities set country=N'France' where country=N'FRANCE';
update municipalities set country=N'Hrvatska' where country=N'HRVATSKA';
update municipalities set country=N'Italia' where country=N'ITALIA';
update municipalities set country=N'Κυπρος (Kypros)' where country=N'ΚΥΠΡΟΣ (KYPROS)';
update municipalities set country=N'Latvija' where country=N'LATVIJA';
update municipalities set country=N'Lietuva' where country=N'LIETUVA';
update municipalities set country=N'Luxembourg' where country=N'LUXEMBOURG';
update municipalities set country=N'Magyarország' where country=N'MAGYARORSZÁG';
update municipalities set country=N'Malta' where country=N'MALTA';
update municipalities set country=N'Nederland' where country=N'NEDERLAND';
update municipalities set country=N'Österreich' where country=N'ÖSTERREICH';
update municipalities set country=N'Polska' where country=N'POLSKA';
update municipalities set country=N'Portugal' where country=N'PORTUGAL';
update municipalities set country=N'România' where country=N'ROMÂNIA';
update municipalities set country=N'Slovenija' where country=N'SLOVENIJA';
update municipalities set country=N'Slovensko' where country=N'SLOVENSKO';
update municipalities set country=N'Suomi / Finland' where country=N'SUOMI / FINLAND';
update municipalities set country=N'Sverige' where country=N'SVERIGE';
update municipalities set country=N'United Kingdom' where country=N'UNITED KINGDOM';
update municipalities set country=N'Norway' where country=N'NORWAY';
update municipalities set country=N'Iceland' where country=N'ICELAND';

update voucher_simulations set country=N'Belgique-België' where country=N'BELGIQUE-BELGIË';
update voucher_simulations set country=N'България (Bulgaria)' where country=N'БЪЛГАРИЯ (BULGARIA)';
update voucher_simulations set country=N'Česká Republika' where country=N'ČESKÁ REPUBLIKA';
update voucher_simulations set country=N'Danmark' where country=N'DANMARK';
update voucher_simulations set country=N'Deutschland' where country=N'DEUTSCHLAND';
update voucher_simulations set country=N'Eesti' where country=N'EESTI';
update voucher_simulations set country=N'Ireland' where country=N'IRELAND';
update voucher_simulations set country=N'Ελλαδα (Ellada)' where country=N'ΕΛΛΑΔΑ (ELLADA)';
update voucher_simulations set country=N'España' where country=N'ESPAÑA';
update voucher_simulations set country=N'France' where country=N'FRANCE';
update voucher_simulations set country=N'Hrvatska' where country=N'HRVATSKA';
update voucher_simulations set country=N'Italia' where country=N'ITALIA';
update voucher_simulations set country=N'Κυπρος (Kypros)' where country=N'ΚΥΠΡΟΣ (KYPROS)';
update voucher_simulations set country=N'Latvija' where country=N'LATVIJA';
update voucher_simulations set country=N'Lietuva' where country=N'LIETUVA';
update voucher_simulations set country=N'Luxembourg' where country=N'LUXEMBOURG';
update voucher_simulations set country=N'Magyarország' where country=N'MAGYARORSZÁG';
update voucher_simulations set country=N'Malta' where country=N'MALTA';
update voucher_simulations set country=N'Nederland' where country=N'NEDERLAND';
update voucher_simulations set country=N'Österreich' where country=N'ÖSTERREICH';
update voucher_simulations set country=N'Polska' where country=N'POLSKA';
update voucher_simulations set country=N'Portugal' where country=N'PORTUGAL';
update voucher_simulations set country=N'România' where country=N'ROMÂNIA';
update voucher_simulations set country=N'Slovenija' where country=N'SLOVENIJA';
update voucher_simulations set country=N'Slovensko' where country=N'SLOVENSKO';
update voucher_simulations set country=N'Suomi / Finland' where country=N'SUOMI / FINLAND';
update voucher_simulations set country=N'Sverige' where country=N'SVERIGE';
update voucher_simulations set country=N'United Kingdom' where country=N'UNITED KINGDOM';
update voucher_simulations set country=N'Norway' where country=N'NORWAY';
update voucher_simulations set country=N'Iceland' where country=N'ICELAND';

update users set country=N'Belgique-België' where country=N'BELGIQUE-BELGIË';
update users set country=N'България (Bulgaria)' where country=N'БЪЛГАРИЯ (BULGARIA)';
update users set country=N'Česká Republika' where country=N'ČESKÁ REPUBLIKA';
update users set country=N'Danmark' where country=N'DANMARK';
update users set country=N'Deutschland' where country=N'DEUTSCHLAND';
update users set country=N'Eesti' where country=N'EESTI';
update users set country=N'Ireland' where country=N'IRELAND';
update users set country=N'Ελλαδα (Ellada)' where country=N'ΕΛΛΑΔΑ (ELLADA)';
update users set country=N'España' where country=N'ESPAÑA';
update users set country=N'France' where country=N'FRANCE';
update users set country=N'Hrvatska' where country=N'HRVATSKA';
update users set country=N'Italia' where country=N'ITALIA';
update users set country=N'Κυπρος (Kypros)' where country=N'ΚΥΠΡΟΣ (KYPROS)';
update users set country=N'Latvija' where country=N'LATVIJA';
update users set country=N'Lietuva' where country=N'LIETUVA';
update users set country=N'Luxembourg' where country=N'LUXEMBOURG';
update users set country=N'Magyarország' where country=N'MAGYARORSZÁG';
update users set country=N'Malta' where country=N'MALTA';
update users set country=N'Nederland' where country=N'NEDERLAND';
update users set country=N'Österreich' where country=N'ÖSTERREICH';
update users set country=N'Polska' where country=N'POLSKA';
update users set country=N'Portugal' where country=N'PORTUGAL';
update users set country=N'România' where country=N'ROMÂNIA';
update users set country=N'Slovenija' where country=N'SLOVENIJA';
update users set country=N'Slovensko' where country=N'SLOVENSKO';
update users set country=N'Suomi / Finland' where country=N'SUOMI / FINLAND';
update users set country=N'Sverige' where country=N'SVERIGE';
update users set country=N'United Kingdom' where country=N'UNITED KINGDOM';
update users set country=N'Norway' where country=N'NORWAY';
update users set country=N'Iceland' where country=N'ICELAND';