INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Ratková a okolie','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí AGLOMERÁCIA HRONOVCE','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie miest a obcí Šariša','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('SPOLOČENSTVO OBCÍ MIKROREGIÓNU PODHORIE','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Drotária','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Trstín - Horná Krupá - Bíňovce','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión Branč-združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí dolného Žitného Ostrova','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie miest a obcí okresov Zvolen, Detva a Krupina, združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Šípok','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('ZDRUŽENIE OBCÍ PRE ROZVOJ POMORAVIA','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('„ MIKROREGIÓN HRIČOV združenie obcí"','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión Stredné a Dolné Poiplie""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Kľakovskej doliny','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Záujmové združenie spoločenstva obcí mikroregiónu Juh Šíravy""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie podzoborských obcí - Zoboralji Községek regionális Társulása','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('ZDRAVSPOL - združenie obcí so sídlom v Hurbanove','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí a miest Hontiansko Poipeľského regiónu so sídlom v Šahách','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest a obcí Spiša','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Hrončiansko - Osrblianskej železnice','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie miest a obcí RUDOHORIE','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí - regionálne vzdelávacie centrum samosprávy v Nitre','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Dolnohronské regionálne združenie','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie Vlára - Váh, združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Veľký potok - Ipeľ','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí - kanalizácia do spoločnej ČOV','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí a miest mikroregión Novozámocko','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Torysský prameň','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Malé Ozorovce, Veľké Ozorovce, Zbehňov, Zemplínska Teplica','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie obcí Dubová','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Nitrianske regionálne združenie obcí - ZMOS','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('REGIONÁLNE VZDELÁVACIE CENTRUM, ZDRUŽENIE OBCÍ, RIMAVSKÁ SOBOTA','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Kuklov, Borský Svätý Jur, Sekule a Moravský Svátý Ján - budovanie skupinového vodovodu','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miet a obcí Medzibodrožia','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Kanalizácia Vrbové - Krakovany','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí - Mikroregión Hurbanovo a okolie','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí regiónu Cirocha','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Záujmové združenie miest a obcí pre trvalo udržateľnú energetickú efektívnosť CITENERGO','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie historických miest a obcí Slovenskej republiky','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión Dolného Gemera - združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Medzičilizia','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí pre odkanalizovanie južnej časti Zemplínskej Šíravy','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión obcí ROŇAVA - združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Čičava','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión HORNOHRAD, združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Zlatníckej doliny','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Kvetňanka','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Torysa-net','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Enviropark Pomoravie','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('ZDRUŽENIE OBCÍ HORNÉHO ŽITNÉHO OSTROVA pre odvádzanie a čistenie odpadových vôd','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión Údolie Čebovského potoka - združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest a obcí Turčianska Vážsko-Fatranská cesta','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest a obcí regiónu Južného Zemplína','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Zduženie obcí - Mikroregión Csángó','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest a obcí pre separovaný zber odpadu - Záhorie','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí VIESKY','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Mikroregión Bardejov - Horná Topľa','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí mikroregiónu Minčol','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest a obcí údolia Bodvy','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Mikroregión Klátovské rameno - Tőkési ág Kistérség','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('EKOLÓG OLŠAVA" záujmové združenie obcí"','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie mesta a obcí Dolných Kysúc','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí odpadového hospodárstva Gabčíkovského regiónu','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Ponitrianske združenie obcí pre separovaný zber a nakladanie s odpadom','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí pod Mutnom','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Kecerovský mikroregión - združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest a obcí veľkokrtíšskeho regiónu','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión ČIERNY HRON - združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión IZRA - združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí pre likvidáciu odpadu Poltár','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie miest a obcí TEKOV','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest Slovenska','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión Teplý Vrch - združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí mikroregiónu Prameň Hornádu a Čierneho Váhu','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Duša""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí pre separovaný zber Hont - Poiplie""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie mesta o obcí mikroregiónu Šurany-Bánov-Lipová','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest a obcí Záhorie','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí kopaničiarskeho regiónu Veľká Javorina - Bradlo','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Horná Krupá - Bíňovce','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie miest a obcí Stredného Gemera','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie miest a obcí Gemera a Malohontu','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Uh - Olšava','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí MIKROREGIÓN DOMAŠA','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Malý Žitný ostrov','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie prihraničných obcí pre VKČOV','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Dvory a okolie - združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Mikroregión Dolná Svinka""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Spoločenstvo obcí topoľčiansko-duchonského mikroregiónu - združenie obcí""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest a obcí galantsko-šalianskeho regiónu','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí NEOS""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Budovanie, združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Mikroregión Terchovská dolina','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Havran - Dolný Liptov','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí MIKROREGIÓN MILOJ SPIŠ""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie obcí pre rozvoj odpadového hospodárstva Banskej Štiavnice a okolia','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión Turčiansko-Čremoštiansky - združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Zdravý mikroregión""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie Dolný Liptov','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Most priateľstva - Hídverő Társulás""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Šírava - Morské oko""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí, Mikroregión Rimavská dolina','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Záujmové združenie obcí Hont - Tekov','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí mikroregiónu OKNA""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Handlovskej doliny','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí BIOMASA SPIŠ','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('ZDRUŽENIE OBCÍ - MIKROREGIÓN ŠAŠTÍNSKO','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Hrušovsko-Beňadický mikroregión - združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí mikroregiónu Cergát - Váh""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí - PODHORIE','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('ZDRUŹENIE OBCI PATRIA','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest a obcí Hnileckého regiónu','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Mikroregión Domica""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión Dobrá voda - združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Mikroregión Spišskej občiny','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí-SEPAR""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('REGIONÁLNE ZDRUŽENIE OBCÍ LATORICA','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('PRESSKAN','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Považskobystrické regionálne združenie miest a obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí TOPĽA-DATA""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí mikroregión - Ipeľská dolina Ipoly völgye mikrorégió','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Mikroregión Inovec','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Pod Bielymi Karpatami','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Mikroregiónu Suchánska dolina','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie obcí Hornád','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie mesta Modra a obcí malokarpatského mikroregiónu','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión Obručná - združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie obcí Košice - okolie','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest a obcí Biela Orava','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Horného Liptova - Čistota','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión Blžská dolina - združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('VODOCOOP','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí subregión Pod Bradlom','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie pre rozvoj Považia','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí dolného Potorysia','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest a obcí dunajského regiónu','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí SEZA','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí za zdravšie Požitavie','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí MIkroregión Horná Svinka""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí pre separovaný zber odpadu regiónu Podunajsko','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí TOPOĽ','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión POĽANA . centrumturistiky, zdravých vôd a kultúrnych pamiatok, združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Záujmové združenie obcí - SIKENICA - Községek Érdekvédelmi Szövetsége','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión Dolné Pohronie a južná časť Podunajska""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Mikroregión Pod Panským dielom','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie miest a obcí stredného Považia','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Mikroregión Slovenský raj - Sever','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión Tarbucka - združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest a obcí hornej Nitry','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Púchovská dolina""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí ZOBOR','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Rieka Poprad, z.o.','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Pezinský mikroregión','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Slanského mikroregiónu','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí pre separovaný zber TATIAR""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí prihraničnej rieky Poprad - v likvidácií','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Miniregión Pridunajsko','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest a obcí okresu Komárno""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí - Južný región""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie obcí Vtáčnik','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí mikroregiónu Severné Podpoľanie','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión Oravská vrchovina - Združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Mikroregiónu Štítnická dolina','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí MIKROREGIÓN PÚCHOV','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión Červený Kameň, združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Mikroregión Palóc - Hont','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí pre trvalo udržateľné nakladanie s komunálnymi odpadmi','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('DIGITÁLNE ŠTIAVNICKO - ZDRUŽENIE OBCÍ PRE INTERNETIZÁCIU ŠTIAVNICKÉHO REGIÓNU','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('SPOLOČENSTVO OBCÍ MIKROREGIÓNU POVAŽSKÝ INOVEC','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Turistika bez hraníc','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí na ochranu Baldovskej minerálnej vody - Sivá Brada','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie miest a obcí - Požitavský región','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí EKOTORYSA','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí mikroregiónu BOROLO','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Záujmové združenie obcí v 1.pásme Jadrovej elektrárne Mochovce','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí pod hradom Čičva','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('ZDRUŽENIE OBCÍ MIKROREGIÓN KREMNICKÉ VRCHY','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('TROJHRANIČIE, združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión Novohradské podzámčie - združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí mikroregión Pliešovská kotlina""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí bielokarpatsko-trenčianskeho mikroregiónu','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí - MIKROREGIÓN SKALICKO','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí mikroregionu BÚČKY ""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('TICCE MIKROREGIÓN, združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Uhrovská dolina""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí - Termál','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie miest a obcí Zemplín" Michalovský región"','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Horného Žitného ostrova v odpadovom hospodárstve so sídlom v Šamoríne','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí pod Končiarom','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí - Včelince a Rumince','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí MIKROREGIÓN Podtríbečie - Drevenica""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Dolné Považie a Podunajská nížina - Mátyusföld','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest a obcí pre využívanie obnoviteľných zdrojov','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie obcí BUCHLOV','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('REGIONÁLNE ZDRUŽENIE MIEST A OBCÍ, REGIÓN STREDNÉ PONITRIE','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí EKOSEP-KYSUCE','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Pro-Danubia - Združenie obcí pre miestnu dopravu po Dunaji','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí HONT','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('BOCOV - združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí DUDOK""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Za čisté Dolné Pohronie""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Mikroregión pri Slanej','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí separovaného zberu','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Rajecká dolina','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí mikroregiónu Muránska planina','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('ZDRUŽENIE OBCÍ REGIONÁLNE VZDELÁVACIE CENTRUM MARTIN','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Hanušovce nad Topľou a okolie','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí údolia Kaňapty','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí cestovného ruchu Zemplínska Šírava','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí JURAVA','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí stredného Liptova EKOLÓG','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest a obcí Rajeckej doliny','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí oravsko - liptovského mikroregiónu OrLi""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Záhorská Ves a Suchohrad pre výstavbu a prevádzkovanie ČOV a kanalizáciu v obciach','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión MEDVEŠ, združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('VODANAŠA','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Mikroregión Beckov - Zelená voda - Bezovec','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Trniny','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie vidieckeho turizmu HRON" - združenie obcí"','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Bioenergia Bystricko','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Záujmové regionálne združenie miest a obcí Mochovce','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí - Mikroregión pri Velických jazerách','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('REO-Združenie pre separovaný zber','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí SEPAD','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie miest a obcí Horného Gemera','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest a obcí, región JE Jaslovské Bohunice','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí MIKROREGIÓN MAKOVICA','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión Východný Hont, združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí aglomerácia Rajecké Teplice','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí MIKROREGIÓN SLNEČNICA','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión Pod Mošníkom - združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Záujmové združenie obcí VEKOČEM','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí skupinového vodovodu CHANAVA','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí pre hospodárenie s odpadom v Malokarpatskom partnerstve','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie miest a obcí pod Duklou, Giraltovce','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Olšavského a Slanského regiónu','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí - HAVRAN','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie Prívodu vody""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí mikroregiónu Nízke Tatry a Rudohorie RENTAR""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest a obcí Novohradu','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Veselé ČOV','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Tribečsko - Inoveckého regiónu','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí - Čistý Liptov','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Milič""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Koordinačné združenie obcí mikroregiónu Podpoľanie','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Bernolákovo-Ivanka pri Dunaji na vybudovanie cyklistického chodníka','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Šúr','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí mikroregiónu Starohorská dolina','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Pukavica','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión Požitavie - Širočina - záujmové združenie obcí pre CR""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí EKOLÓG','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie obcí Magura - Strážov','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne vzdelávacie centrum - združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie miest a obcí Horného Považia','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie obcí Teplička','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest a obcí Horná Rimava""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Zemianske Sady, Pusté Sady a Šalgočka za účelom separácie odpadu','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí - Mikroregión Bošáčka','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Mikroregiónu Západný Tríbeč','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie miest a obcí Prešov - Šariš','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí DOLNÝ SPIŠ - NET','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí časti Použia','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí - Budovanie kanalizácie GHKPV','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie výstavby kanalizácie v regióne Malacky','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Bačkov, Dvorianky, Hriadky, Parchovany, Tušice, Vojčice','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Mikroregión Čremošná""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Záujmové združenie obcí Mikroregión Údolie Gortvy','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí pre CR Mikroregión KVETNIANKA""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('SPOLOČNÝ POĽOVNÝ REVÍR - záujmové združenie obcí Hrachovište - Višňové','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión MAGNEZIT, združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie maličkých historických obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('BURÓD, združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Mikroregión Machnáč-Inovec','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Drahňov - Varhaňovce','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest a obcí okresu Košice - okolie','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Bánovecko','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión Palócska vrchovina - Palóc dombvidék - združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Skládka TKO Vyšehradné - záujmové združenie obcí Nitrianske Pravno, Tužina, Pravenec, Kľačno, Malinová, Poluvsie a Chvojnica','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('ROVINA - združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie obcí Laborecká niva""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Rudnaya','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie mesta a obcí Sobranského regiónu','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie miest a obcí Žiarsky región','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('SEZO - SPIŠ, združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Mikroregión Turiec v Gemeri','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí POBEBRAVIE','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Čierna voda - Uh','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Mikroregión Turecká""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Torysského mikroregiónu','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí mikroregiónu Poondavie','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí pre rozvoj mikroregiónu Horehron','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Mikroregión Pieniny - východ - v likvidácií','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí ČACHTICE - KOPANICE','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí SEPARO','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Olšavský mikroregión združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('SPOLOČENSTVO OBCÍ MIKROREGIÓNU JAVORINA','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest a obcí myjavského regiónu','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí MIKROREGIÓN SĽUBICA""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión pod Poludnicou združenie obcí""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Mikroregión - združenie obcí strehovskej doliny','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Mikroregiónu Chopok - juh','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Priemyselný park AGRO-SOBRANSKO - združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest a obcí Malokarpatského regiónu','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí hornej Torysy','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('ZDRUŽENIE MIEST A OBCÍ KYSÚC','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Mikroregión Kysucký triangel','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí mikroregiónu Veľké Zálužie-Lehota-Jarok-Báb-Rumanová','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie miest a obcí Použia','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Zádielska Tiesňava','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Šamorín a Kvetoslavov pre rozvoj alternatívnej dopravy','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí kanalizácia Orechová Potôň - Vieska - Michal na Ostrove','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí na vybudovanie spoločnej vákuovej kanalizácie a ČOV','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí kanalizácia Vydrany - Veľké Blahovo','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Bašovce, Ostrov, Veľké Orvište','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Ekospiš, združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Holeška na triedenie a nakladanie s odpadmi','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Stredného Žitného ostrova pre separovaný zber a nakladanie s odpadmi','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Kamenín, Kamenný Most a Nána','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí mestskej oblasti Trnava','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí CYKLO 5','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Modra - Šenkvice','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí - Cyklodoprava v okrese Pezinok','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Lednicko-rovňanského regiónu""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Zelená cesta','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Hrachovište, Vaďovce, Višňové','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Regionálne združenie obcí RUŽÍN','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Čipčie','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí ONDAVA','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('PRAMEŇ združenie obcí Konská, Kunerad, Kamenná Poruba, Stránske, Zbyňov','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí regiónu Čergov - Topľa','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Strážovské vrchy','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Ekocentrum Dolná Orava - združenie obcí','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Lužianka','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí - Papradňanská dolina','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí pod Inovcom','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí CykloEko','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Čistá Mošurovanka','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Ratkovce a Žlkovce','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí za čistejší Sekčov','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Podzoborská hrádza""','SK');
INSERT INTO `wifi4eu`.`organizations`(`name`, `country`) VALUES ('Združenie obcí Malokarpatské podhorie','SK');
