
package eu.europa.ec.budg.abac.legal_entity.service.es.sync.v2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-07-28T12:43:24.291+02:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "MessageFault", targetNamespace = "http://www.ec.europa.eu/budg/abac/message/v1")
public class FaultMessage extends Exception {
    
    private eu.europa.ec.budg.abac.message.v1.MessageFaultType messageFault;

    public FaultMessage() {
        super();
    }
    
    public FaultMessage(String message) {
        super(message);
    }
    
    public FaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public FaultMessage(String message, eu.europa.ec.budg.abac.message.v1.MessageFaultType messageFault) {
        super(message);
        this.messageFault = messageFault;
    }

    public FaultMessage(String message, eu.europa.ec.budg.abac.message.v1.MessageFaultType messageFault, Throwable cause) {
        super(message, cause);
        this.messageFault = messageFault;
    }

    public eu.europa.ec.budg.abac.message.v1.MessageFaultType getFaultInfo() {
        return this.messageFault;
    }
}
