-- INSERT CY LAUS (added new name fields)
UPDATE laus SET name_national=N'Λευκωσία', name_latin=N'Lefkosia', abac_name=N'Leukosia', display_name=N'Λευκωσία-Lefkosia' WHERE id=2953;
UPDATE laus SET name_national=N'Άγιος Δομέτιος', name_latin=N'Agios Dometios', abac_name=N'Agios Dometios', display_name=N'Άγιος Δομέτιος-Agios Dometios' WHERE id=2954;
UPDATE laus SET name_national=N'Έγκωμη Λευκωσίας', name_latin=N'Egkomi Lefkosias', abac_name=N'Egkome Leukosias', display_name=N'Έγκωμη Λευκωσίας-Egkomi Lefkosias' WHERE id=2955;
UPDATE laus SET name_national=N'Στρόβολος', name_latin=N'Strovolos', abac_name=N'Strobolos', display_name=N'Στρόβολος-Strovolos' WHERE id=2956;
UPDATE laus SET name_national=N'Αγλαντζιά ή Αγλαγγιά', name_latin=N'Aglantzia or Aglangia', abac_name=N'Aglantzia e Aglaggia', display_name=N'Αγλαντζιά ή Αγλαγγιά-Aglantzia or Aglangia' WHERE id=2957;
UPDATE laus SET name_national=N'Ορτάκιοϊ (Μιντζέλι)', name_latin=N'Ortakioï (Mintzeli)', abac_name=N'Ortakioi (Mintzeli)', display_name=N'Ορτάκιοϊ (Μιντζέλι)-Ortakioï (Mintzeli)' WHERE id=2958;
UPDATE laus SET name_national=N'Τράχωνας', name_latin=N'Trachonas', abac_name=N'Trakhonas', display_name=N'Τράχωνας-Trachonas' WHERE id=2959;
UPDATE laus SET name_national=N'Λακατάμεια', name_latin=N'Lakatameia', abac_name=N'Lakatameia', display_name=N'Λακατάμεια-Lakatameia' WHERE id=2960;
UPDATE laus SET name_national=N'Συνοικισμός Ανθούπολης', name_latin=N'Synoikismos Anthoupolis', abac_name=N'Sunoikismos Anthoupoles', display_name=N'Συνοικισμός Ανθούπολης-Synoikismos Anthoupolis' WHERE id=2961;
UPDATE laus SET name_national=N'Λατσιά ή Λακκιά', name_latin=N'Latsia or Lakkia', abac_name=N'Latsia e Lakkia', display_name=N'Λατσιά ή Λακκιά-Latsia or Lakkia' WHERE id=2962;
UPDATE laus SET name_national=N'Γέρι', name_latin=N'Geri', abac_name=N'Geri', display_name=N'Γέρι-Geri' WHERE id=2963;
UPDATE laus SET name_national=N'Σιά', name_latin=N'Sia', abac_name=N'Sia', display_name=N'Σιά-Sia' WHERE id=2964;
UPDATE laus SET name_national=N'Μαθιάτης', name_latin=N'Mathiatis', abac_name=N'Mathiates', display_name=N'Μαθιάτης-Mathiatis' WHERE id=2965;
UPDATE laus SET name_national=N'Αλάμπρα', name_latin=N'Alampra', abac_name=N'Alampra', display_name=N'Αλάμπρα-Alampra' WHERE id=2966;
UPDATE laus SET name_national=N'Αγία Βαρβάρα Λευκωσίας', name_latin=N'Agia Varvara Lefkosias', abac_name=N'Agia Barbara Leukosias', display_name=N'Αγία Βαρβάρα Λευκωσίας-Agia Varvara Lefkosias' WHERE id=2967;
UPDATE laus SET name_national=N'Κοτσιάτης', name_latin=N'Kotsiatis', abac_name=N'Kotsiates', display_name=N'Κοτσιάτης-Kotsiatis' WHERE id=2968;
UPDATE laus SET name_national=N'Νήσου', name_latin=N'Nisou', abac_name=N'Nesou', display_name=N'Νήσου-Nisou' WHERE id=2969;
UPDATE laus SET name_national=N'Πέρα Χωριό', name_latin=N'Pera Chorio', abac_name=N'Pera Khorio', display_name=N'Πέρα Χωριό-Pera Chorio' WHERE id=2970;
UPDATE laus SET name_national=N'Δάλι', name_latin=N'Dali', abac_name=N'Dali', display_name=N'Δάλι-Dali' WHERE id=2971;
UPDATE laus SET name_national=N'Λύμπια', name_latin=N'Lympia', abac_name=N'Lumpia', display_name=N'Λύμπια-Lympia' WHERE id=2972;
UPDATE laus SET name_national=N'Λυθροδόντας', name_latin=N'Lythrodontas', abac_name=N'Luthrodontas', display_name=N'Λυθροδόντας-Lythrodontas' WHERE id=2973;
UPDATE laus SET name_national=N'Λουρουκίνα', name_latin=N'Louroukina', abac_name=N'Louroukina', display_name=N'Λουρουκίνα-Louroukina' WHERE id=2974;
UPDATE laus SET name_national=N'Ποταμιά', name_latin=N'Potamia', abac_name=N'Potamia', display_name=N'Ποταμιά-Potamia' WHERE id=2975;
UPDATE laus SET name_national=N'''Αγιος Σωζόμενος', name_latin=N'Agios Sozomenos', abac_name=N'''Agios Sozomenos', display_name=N'''Αγιος Σωζόμενος-Agios Sozomenos' WHERE id=2976;
UPDATE laus SET name_national=N'Πυρόγι', name_latin=N'Pyrogi', abac_name=N'Purogi', display_name=N'Πυρόγι-Pyrogi' WHERE id=2977;
UPDATE laus SET name_national=N'Μαργό', name_latin=N'Margo', abac_name=N'Margo', display_name=N'Μαργό-Margo' WHERE id=2978;
UPDATE laus SET name_national=N'Αγιά (Aγιά Κεπίρ)', name_latin=N'Agia (Agia Kepir)', abac_name=N'Agia (Agia Kepir)', display_name=N'Αγιά (Aγιά Κεπίρ)-Agia (Agia Kepir)' WHERE id=2979;
UPDATE laus SET name_national=N'Τύμβου', name_latin=N'Tymvou', abac_name=N'Tumbou', display_name=N'Τύμβου-Tymvou' WHERE id=2980;
UPDATE laus SET name_national=N'Μόρα', name_latin=N'Mora', abac_name=N'Mora', display_name=N'Μόρα-Mora' WHERE id=2981;
UPDATE laus SET name_national=N'Μια Μηλιά', name_latin=N'Mia Milia', abac_name=N'Mia Melia', display_name=N'Μια Μηλιά-Mia Milia' WHERE id=2982;
UPDATE laus SET name_national=N'Μάνδρες Λευκωσίας', name_latin=N'Mandres Lefkosias', abac_name=N'Mandres Leukosias', display_name=N'Μάνδρες Λευκωσίας-Mandres Lefkosias' WHERE id=2983;
UPDATE laus SET name_national=N'Παλαίκυθρο', name_latin=N'Palaikythro', abac_name=N'Palaikuthro', display_name=N'Παλαίκυθρο-Palaikythro' WHERE id=2984;
UPDATE laus SET name_national=N'''Εξω Μετόχι', name_latin=N'Exo Metochi', abac_name=N'''Exo Metokhi', display_name=N'''Εξω Μετόχι-Exo Metochi' WHERE id=2985;
UPDATE laus SET name_national=N'Επιχό', name_latin=N'Epicho', abac_name=N'Epikho', display_name=N'Επιχό-Epicho' WHERE id=2986;
UPDATE laus SET name_national=N'Βώνη', name_latin=N'Voni', abac_name=N'Bone', display_name=N'Βώνη-Voni' WHERE id=2987;
UPDATE laus SET name_national=N'Τραχώνι Λευκωσίας', name_latin=N'Trachoni Lefkosias', abac_name=N'Trakhoni Leukosias', display_name=N'Τραχώνι Λευκωσίας-Trachoni Lefkosias' WHERE id=2988;
UPDATE laus SET name_national=N'Νέο Χωριό Λευκωσίας', name_latin=N'Neo Chorio Lefkosias', abac_name=N'Neo Khorio Leukosias', display_name=N'Νέο Χωριό Λευκωσίας-Neo Chorio Lefkosias' WHERE id=2989;
UPDATE laus SET name_national=N'Κυθρέα', name_latin=N'Kythrea', abac_name=N'Kuthrea', display_name=N'Κυθρέα-Kythrea' WHERE id=2990;
UPDATE laus SET name_national=N'Μπέϊκιοϊ', name_latin=N'Beikioï', abac_name=N'Mpeikioi', display_name=N'Μπέϊκιοϊ-Beikioï' WHERE id=2991;
UPDATE laus SET name_national=N'Πέτρα του Διγενή', name_latin=N'Petra tou Digeni', abac_name=N'Petra tou Digene', display_name=N'Πέτρα του Διγενή-Petra tou Digeni' WHERE id=2992;
UPDATE laus SET name_national=N'Καλυβάκια', name_latin=N'Kalyvakia', abac_name=N'Kalubakia', display_name=N'Καλυβάκια-Kalyvakia' WHERE id=2993;
UPDATE laus SET name_national=N'Κουρού Μοναστήρι', name_latin=N'Kourou Monastiri', abac_name=N'Kourou Monasteri', display_name=N'Κουρού Μοναστήρι-Kourou Monastiri' WHERE id=2994;
UPDATE laus SET name_national=N'Καμπί', name_latin=N'Kampi', abac_name=N'Kampi', display_name=N'Καμπί-Kampi' WHERE id=2995;
UPDATE laus SET name_national=N'Φαρμακάς', name_latin=N'Farmakas', abac_name=N'Pharmakas', display_name=N'Φαρμακάς-Farmakas' WHERE id=2996;
UPDATE laus SET name_national=N'Απλίκι', name_latin=N'Apliki', abac_name=N'Apliki', display_name=N'Απλίκι-Apliki' WHERE id=2997;
UPDATE laus SET name_national=N'Λαζανιάς', name_latin=N'Lazanias', abac_name=N'Lazanias', display_name=N'Λαζανιάς-Lazanias' WHERE id=2998;
UPDATE laus SET name_national=N'Γούρρη', name_latin=N'Gourri', abac_name=N'Gourre', display_name=N'Γούρρη-Gourri' WHERE id=2999;
UPDATE laus SET name_national=N'Φικάρδου', name_latin=N'Fikardou', abac_name=N'Phikardou', display_name=N'Φικάρδου-Fikardou' WHERE id=3000;
UPDATE laus SET name_national=N'Άγιος Επιφάνιος Ορεινής', name_latin=N'Agios Epifanios Oreinis', abac_name=N'Agios Epiphanios Oreines', display_name=N'Άγιος Επιφάνιος Ορεινής-Agios Epifanios Oreinis' WHERE id=3001;
UPDATE laus SET name_national=N'Καλό Χωριό Ορεινής', name_latin=N'Kalo Chorio Oreinis', abac_name=N'Kalo Khorio Oreines', display_name=N'Καλό Χωριό Ορεινής-Kalo Chorio Oreinis' WHERE id=3002;
UPDATE laus SET name_national=N'Μαλούντα', name_latin=N'Malounta', abac_name=N'Malounta', display_name=N'Μαλούντα-Malounta' WHERE id=3003;
UPDATE laus SET name_national=N'Κλήρου', name_latin=N'Klirou', abac_name=N'Klerou', display_name=N'Κλήρου-Klirou' WHERE id=3004;
UPDATE laus SET name_national=N'Αρεδιού', name_latin=N'Arediou', abac_name=N'Arediou', display_name=N'Αρεδιού-Arediou' WHERE id=3005;
UPDATE laus SET name_national=N'Άγιος Ιωάννης Μαλούντας', name_latin=N'Agios Ioannis Malountas', abac_name=N'Agios Ioannes Malountas', display_name=N'Άγιος Ιωάννης Μαλούντας-Agios Ioannis Malountas' WHERE id=3006;
UPDATE laus SET name_national=N'Αγροκηπιά', name_latin=N'Agrokipia', abac_name=N'Agrokepia', display_name=N'Αγροκηπιά-Agrokipia' WHERE id=3007;
UPDATE laus SET name_national=N'Μιτσερό', name_latin=N'Mitsero', abac_name=N'Mitsero', display_name=N'Μιτσερό-Mitsero' WHERE id=3008;
UPDATE laus SET name_national=N'Καπέδες', name_latin=N'Kapedes', abac_name=N'Kapedes', display_name=N'Καπέδες-Kapedes' WHERE id=3009;
UPDATE laus SET name_national=N'Καταλιόντας', name_latin=N'Kataliontas', abac_name=N'Kataliontas', display_name=N'Καταλιόντας-Kataliontas' WHERE id=3010;
UPDATE laus SET name_national=N'Αναλιόντας', name_latin=N'Analiontas', abac_name=N'Analiontas', display_name=N'Αναλιόντας-Analiontas' WHERE id=3011;
UPDATE laus SET name_national=N'Καμπιά', name_latin=N'Kampia', abac_name=N'Kampia', display_name=N'Καμπιά-Kampia' WHERE id=3012;
UPDATE laus SET name_national=N'Μαργί', name_latin=N'Margi', abac_name=N'Margi', display_name=N'Μαργί-Margi' WHERE id=3013;
UPDATE laus SET name_national=N'Τσέρι', name_latin=N'Tseri', abac_name=N'Tseri', display_name=N'Τσέρι-Tseri' WHERE id=3014;
UPDATE laus SET name_national=N'Πολιτικό', name_latin=N'Politiko', abac_name=N'Politiko', display_name=N'Πολιτικό-Politiko' WHERE id=3015;
UPDATE laus SET name_national=N'Πέρα', name_latin=N'Pera', abac_name=N'Pera', display_name=N'Πέρα-Pera' WHERE id=3016;
UPDATE laus SET name_national=N'Επισκοπειό', name_latin=N'Episkopeio', abac_name=N'Episkopeio', display_name=N'Επισκοπειό-Episkopeio' WHERE id=3017;
UPDATE laus SET name_national=N'Ψιμολόφου', name_latin=N'Psimolofou', abac_name=N'Psimolophou', display_name=N'Ψιμολόφου-Psimolofou' WHERE id=3018;
UPDATE laus SET name_national=N'Εργάτες', name_latin=N'Ergates', abac_name=N'Ergates', display_name=N'Εργάτες-Ergates' WHERE id=3019;
UPDATE laus SET name_national=N'Ανάγεια', name_latin=N'Anageia', abac_name=N'Anageia', display_name=N'Ανάγεια-Anageia' WHERE id=3020;
UPDATE laus SET name_national=N'Πάνω Δευτερά', name_latin=N'Pano Deftera', abac_name=N'Pano Deutera', display_name=N'Πάνω Δευτερά-Pano Deftera' WHERE id=3021;
UPDATE laus SET name_national=N'Κάτω Δευτερά', name_latin=N'Kato Deftera', abac_name=N'Kato Deutera', display_name=N'Κάτω Δευτερά-Kato Deftera' WHERE id=3022;
UPDATE laus SET name_national=N'Άγιοι Τριμιθιάς', name_latin=N'Agioi Trimithias', abac_name=N'Agioi Trimithias', display_name=N'Άγιοι Τριμιθιάς-Agioi Trimithias' WHERE id=3023;
UPDATE laus SET name_national=N'Παλαιομέτοχο', name_latin=N'Palaiometocho', abac_name=N'Palaiometokho', display_name=N'Παλαιομέτοχο-Palaiometocho' WHERE id=3024;
UPDATE laus SET name_national=N'Δένεια', name_latin=N'Deneia', abac_name=N'Deneia', display_name=N'Δένεια-Deneia' WHERE id=3025;
UPDATE laus SET name_national=N'Κοκκινοτριμιθιά', name_latin=N'Kokkinotrimithia', abac_name=N'Kokkinotrimithia', display_name=N'Κοκκινοτριμιθιά-Kokkinotrimithia' WHERE id=3026;
UPDATE laus SET name_national=N'Μάμμαρη', name_latin=N'Mammari', abac_name=N'Mammare', display_name=N'Μάμμαρη-Mammari' WHERE id=3027;
UPDATE laus SET name_national=N'Γερόλακκος', name_latin=N'Gerolakkos', abac_name=N'Gerolakkos', display_name=N'Γερόλακκος-Gerolakkos' WHERE id=3028;
UPDATE laus SET name_national=N'Αγία Μαρίνα Σκυλλούρας', name_latin=N'Agia Marina Skyllouras', abac_name=N'Agia Marina Skullouras', display_name=N'Αγία Μαρίνα Σκυλλούρας-Agia Marina Skyllouras' WHERE id=3029;
UPDATE laus SET name_national=N'Σκυλλούρα', name_latin=N'Skylloura', abac_name=N'Skulloura', display_name=N'Σκυλλούρα-Skylloura' WHERE id=3030;
UPDATE laus SET name_national=N'Άγιος Βασίλειος', name_latin=N'Agios Vasileios', abac_name=N'Agios Basileios', display_name=N'Άγιος Βασίλειος-Agios Vasileios' WHERE id=3031;
UPDATE laus SET name_national=N'Δύο Ποταμοί', name_latin=N'Dyo Potamoi', abac_name=N'Duo Potamoi', display_name=N'Δύο Ποταμοί-Dyo Potamoi' WHERE id=3032;
UPDATE laus SET name_national=N'Κανλί (Κανλίκιογιου)', name_latin=N'Kanli (Kanlikiogiou)', abac_name=N'Kanli (Kanlikiogiou)', display_name=N'Κανλί (Κανλίκιογιου)-Kanli (Kanlikiogiou)' WHERE id=3033;
UPDATE laus SET name_national=N'Κιόνελι', name_latin=N'Kioneli', abac_name=N'Kioneli', display_name=N'Κιόνελι-Kioneli' WHERE id=3034;
UPDATE laus SET name_national=N'Παλαιχώρι Μόρφου', name_latin=N'Palaichori Morfou', abac_name=N'Palaikhori Morphou', display_name=N'Παλαιχώρι Μόρφου-Palaichori Morfou' WHERE id=3035;
UPDATE laus SET name_national=N'Ασκάς', name_latin=N'Askas', abac_name=N'Askas', display_name=N'Ασκάς-Askas' WHERE id=3036;
UPDATE laus SET name_national=N'Άλωνα', name_latin=N'Alona', abac_name=N'Alona', display_name=N'Άλωνα-Alona' WHERE id=3037;
UPDATE laus SET name_national=N'Φτερικούδι', name_latin=N'Fterikoudi', abac_name=N'Phterikoudi', display_name=N'Φτερικούδι-Fterikoudi' WHERE id=3038;
UPDATE laus SET name_national=N'Πολύστυπος', name_latin=N'Polystypos', abac_name=N'Polustupos', display_name=N'Πολύστυπος-Polystypos' WHERE id=3039;
UPDATE laus SET name_national=N'Λαγουδερά', name_latin=N'Lagoudera', abac_name=N'Lagoudera', display_name=N'Λαγουδερά-Lagoudera' WHERE id=3040;
UPDATE laus SET name_national=N'Σαράντι', name_latin=N'Saranti', abac_name=N'Saranti', display_name=N'Σαράντι-Saranti' WHERE id=3041;
UPDATE laus SET name_national=N'Λιβάδια Λευκωσίας', name_latin=N'Livadia Lefkosias', abac_name=N'Libadia Leukosias', display_name=N'Λιβάδια Λευκωσίας-Livadia Lefkosias' WHERE id=3042;
UPDATE laus SET name_national=N'Αληθινού', name_latin=N'Alithinou', abac_name=N'Alethinou', display_name=N'Αληθινού-Alithinou' WHERE id=3043;
UPDATE laus SET name_national=N'Πλατανιστάσα', name_latin=N'Platanistasa', abac_name=N'Platanistasa', display_name=N'Πλατανιστάσα-Platanistasa' WHERE id=3044;
UPDATE laus SET name_national=N'Παλαιχώρι Ορεινής', name_latin=N'Palaichori Oreinis', abac_name=N'Palaikhori Oreines', display_name=N'Παλαιχώρι Ορεινής-Palaichori Oreinis' WHERE id=3045;
UPDATE laus SET name_national=N'Ξυλιάτος', name_latin=N'Xyliatos', abac_name=N'Ksuliatos', display_name=N'Ξυλιάτος-Xyliatos' WHERE id=3046;
UPDATE laus SET name_national=N'Άγιος Γεώργιος Καυκάλλου', name_latin=N'Agios Georgios Kafkallou', abac_name=N'Agios Georgios Kaukallou', display_name=N'Άγιος Γεώργιος Καυκάλλου-Agios Georgios Kafkallou' WHERE id=3047;
UPDATE laus SET name_national=N'Νικητάρι', name_latin=N'Nikitari', abac_name=N'Niketari', display_name=N'Νικητάρι-Nikitari' WHERE id=3048;
UPDATE laus SET name_national=N'Βυζακιά', name_latin=N'Vyzakia', abac_name=N'Buzakia', display_name=N'Βυζακιά-Vyzakia' WHERE id=3049;
UPDATE laus SET name_national=N'Αγία Μαρίνα Ξυλιάτου', name_latin=N'Agia Marina Xyliatou', abac_name=N'Agia Marina Ksuliatou', display_name=N'Αγία Μαρίνα Ξυλιάτου-Agia Marina Xyliatou' WHERE id=3050;
UPDATE laus SET name_national=N'Άγιοι Ηλιόφωτοι', name_latin=N'Agioi Iliofotoi', abac_name=N'Agioi Eliophotoi', display_name=N'Άγιοι Ηλιόφωτοι-Agioi Iliofotoi' WHERE id=3051;
UPDATE laus SET name_national=N'Κάτω Μονή', name_latin=N'Kato Moni', abac_name=N'Kato Mone', display_name=N'Κάτω Μονή-Kato Moni' WHERE id=3052;
UPDATE laus SET name_national=N'Ορούντα', name_latin=N'Orounta', abac_name=N'Orounta', display_name=N'Ορούντα-Orounta' WHERE id=3053;
UPDATE laus SET name_national=N'Πάνω Κουτραφάς', name_latin=N'Pano Koutrafas', abac_name=N'Pano Koutraphas', display_name=N'Πάνω Κουτραφάς-Pano Koutrafas' WHERE id=3054;
UPDATE laus SET name_national=N'Κάτω Κουτραφάς', name_latin=N'Kato Koutrafas', abac_name=N'Kato Koutraphas', display_name=N'Κάτω Κουτραφάς-Kato Koutrafas' WHERE id=3055;
UPDATE laus SET name_national=N'Ποτάμι', name_latin=N'Potami', abac_name=N'Potami', display_name=N'Ποτάμι-Potami' WHERE id=3056;
UPDATE laus SET name_national=N'Μόρφου', name_latin=N'Morfou', abac_name=N'Morphou', display_name=N'Μόρφου-Morfou' WHERE id=3057;
UPDATE laus SET name_national=N'Πάνω Ζώδεια', name_latin=N'Pano Zodeia', abac_name=N'Pano Zodeia', display_name=N'Πάνω Ζώδεια-Pano Zodeia' WHERE id=3058;
UPDATE laus SET name_national=N'Κάτω Ζώδεια', name_latin=N'Kato Zodeia', abac_name=N'Kato Zodeia', display_name=N'Κάτω Ζώδεια-Kato Zodeia' WHERE id=3059;
UPDATE laus SET name_national=N'Καζιβερά', name_latin=N'Kazivera', abac_name=N'Kazibera', display_name=N'Καζιβερά-Kazivera' WHERE id=3060;
UPDATE laus SET name_national=N'Πραστιό Λευκωσίας', name_latin=N'Prastio Lefkosias', abac_name=N'Prastio Leukosias', display_name=N'Πραστιό Λευκωσίας-Prastio Lefkosias' WHERE id=3061;
UPDATE laus SET name_national=N'Νικήτας', name_latin=N'Nikitas', abac_name=N'Niketas', display_name=N'Νικήτας-Nikitas' WHERE id=3062;
UPDATE laus SET name_national=N'Συριανοχώρι', name_latin=N'Syrianochori', abac_name=N'Surianokhori', display_name=N'Συριανοχώρι-Syrianochori' WHERE id=3063;
UPDATE laus SET name_national=N'Καλό Χωριό Καπούτη', name_latin=N'Kalo Chorio Kapouti', abac_name=N'Kalo Khorio Kapoute', display_name=N'Καλό Χωριό Καπούτη-Kalo Chorio Kapouti' WHERE id=3064;
UPDATE laus SET name_national=N'Ακάκι', name_latin=N'Akaki', abac_name=N'Akaki', display_name=N'Ακάκι-Akaki' WHERE id=3065;
UPDATE laus SET name_national=N'Περιστερώνα Λευκωσίας', name_latin=N'Peristerona Lefkosias', abac_name=N'Peristerona Leukosias', display_name=N'Περιστερώνα Λευκωσίας-Peristerona Lefkosias' WHERE id=3066;
UPDATE laus SET name_national=N'Αστρομερίτης', name_latin=N'Astromeritis', abac_name=N'Astromerites', display_name=N'Αστρομερίτης-Astromeritis' WHERE id=3067;
UPDATE laus SET name_national=N'Αυλώνα', name_latin=N'Avlona', abac_name=N'Aulona', display_name=N'Αυλώνα-Avlona' WHERE id=3068;
UPDATE laus SET name_national=N'Κατωκοπιά', name_latin=N'Katokopia', abac_name=N'Katokopia', display_name=N'Κατωκοπιά-Katokopia' WHERE id=3069;
UPDATE laus SET name_national=N'Αργάκι', name_latin=N'Argaki', abac_name=N'Argaki', display_name=N'Αργάκι-Argaki' WHERE id=3070;
UPDATE laus SET name_national=N'Μάσαρη', name_latin=N'Masari', abac_name=N'Masare', display_name=N'Μάσαρη-Masari' WHERE id=3071;
UPDATE laus SET name_national=N'Φυλλιά', name_latin=N'Fyllia', abac_name=N'Phullia', display_name=N'Φυλλιά-Fyllia' WHERE id=3072;
UPDATE laus SET name_national=N'Μένικο', name_latin=N'Meniko', abac_name=N'Meniko', display_name=N'Μένικο-Meniko' WHERE id=3073;
UPDATE laus SET name_national=N'Κυρά', name_latin=N'Kyra', abac_name=N'Kura', display_name=N'Κυρά-Kyra' WHERE id=3074;
UPDATE laus SET name_national=N'Σπήλια', name_latin=N'Spilia', abac_name=N'Spelia', display_name=N'Σπήλια-Spilia' WHERE id=3075;
UPDATE laus SET name_national=N'Αγία Ειρήνη Λευκωσίας', name_latin=N'Agia Eirini Lefkosias', abac_name=N'Agia Eirene Leukosias', display_name=N'Αγία Ειρήνη Λευκωσίας-Agia Eirini Lefkosias' WHERE id=3076;
UPDATE laus SET name_national=N'Καννάβια', name_latin=N'Kannavia', abac_name=N'Kannabia', display_name=N'Καννάβια-Kannavia' WHERE id=3077;
UPDATE laus SET name_national=N'Κακοπετριά', name_latin=N'Kakopetria', abac_name=N'Kakopetria', display_name=N'Κακοπετριά-Kakopetria' WHERE id=3078;
UPDATE laus SET name_national=N'Άγιος Θεόδωρος Σολέας', name_latin=N'Agios Theodoros Soleas', abac_name=N'Agios Theodoros Soleas', display_name=N'Άγιος Θεόδωρος Σολέας-Agios Theodoros Soleas' WHERE id=3079;
UPDATE laus SET name_national=N'Γαλάτα', name_latin=N'Galata', abac_name=N'Galata', display_name=N'Γαλάτα-Galata' WHERE id=3080;
UPDATE laus SET name_national=N'Σιναόρος', name_latin=N'Sinaoros', abac_name=N'Sinaoros', display_name=N'Σιναόρος-Sinaoros' WHERE id=3081;
UPDATE laus SET name_national=N'Καλιάνα', name_latin=N'Kaliana', abac_name=N'Kaliana', display_name=N'Καλιάνα-Kaliana' WHERE id=3082;
UPDATE laus SET name_national=N'Τεμβριά', name_latin=N'Temvria', abac_name=N'Tembria', display_name=N'Τεμβριά-Temvria' WHERE id=3083;
UPDATE laus SET name_national=N'Κοράκου', name_latin=N'Korakou', abac_name=N'Korakou', display_name=N'Κοράκου-Korakou' WHERE id=3084;
UPDATE laus SET name_national=N'Ευρύχου', name_latin=N'Evrychou', abac_name=N'Eurukhou', display_name=N'Ευρύχου-Evrychou' WHERE id=3085;
UPDATE laus SET name_national=N'Φλάσου', name_latin=N'Flasou', abac_name=N'Phlasou', display_name=N'Φλάσου-Flasou' WHERE id=3086;
UPDATE laus SET name_national=N'Άγιος Επιφάνιος Σολέας', name_latin=N'Agios Epifanios Soleas', abac_name=N'Agios Epiphanios Soleas', display_name=N'Άγιος Επιφάνιος Σολέας-Agios Epifanios Soleas' WHERE id=3087;
UPDATE laus SET name_national=N'Ληνού', name_latin=N'Linou', abac_name=N'Lenou', display_name=N'Ληνού-Linou' WHERE id=3088;
UPDATE laus SET name_national=N'Κατύδατα', name_latin=N'Katydata', abac_name=N'Katudata', display_name=N'Κατύδατα-Katydata' WHERE id=3089;
UPDATE laus SET name_national=N'Σκουριώτισσα (Φουκάσα)', name_latin=N'Skouriotissa (Foukasa)', abac_name=N'Skouriotissa (Phoukasa)', display_name=N'Σκουριώτισσα (Φουκάσα)-Skouriotissa (Foukasa)' WHERE id=3090;
UPDATE laus SET name_national=N'Πεδουλάς', name_latin=N'Pedoulas', abac_name=N'Pedoulas', display_name=N'Πεδουλάς-Pedoulas' WHERE id=3091;
UPDATE laus SET name_national=N'Μυλικούρι', name_latin=N'Mylikouri', abac_name=N'Mulikouri', display_name=N'Μυλικούρι-Mylikouri' WHERE id=3092;
UPDATE laus SET name_national=N'Μουτουλλάς', name_latin=N'Moutoullas', abac_name=N'Moutoullas', display_name=N'Μουτουλλάς-Moutoullas' WHERE id=3093;
UPDATE laus SET name_national=N'Οίκος', name_latin=N'Oikos', abac_name=N'Oikos', display_name=N'Οίκος-Oikos' WHERE id=3094;
UPDATE laus SET name_national=N'Καλοπαναγιώτης', name_latin=N'Kalopanagiotis', abac_name=N'Kalopanagiotes', display_name=N'Καλοπαναγιώτης-Kalopanagiotis' WHERE id=3095;
UPDATE laus SET name_national=N'Γερακιές', name_latin=N'Gerakies', abac_name=N'Gerakies', display_name=N'Γερακιές-Gerakies' WHERE id=3096;
UPDATE laus SET name_national=N'Τσακίστρα', name_latin=N'Tsakistra', abac_name=N'Tsakistra', display_name=N'Τσακίστρα-Tsakistra' WHERE id=3097;
UPDATE laus SET name_national=N'Κάμπος', name_latin=N'Kampos', abac_name=N'Kampos', display_name=N'Κάμπος-Kampos' WHERE id=3098;
UPDATE laus SET name_national=N'Άγιος Νικόλαος Σολέας', name_latin=N'Agios Nikolaos Soleas', abac_name=N'Agios Nikolaos Soleas', display_name=N'Άγιος Νικόλαος Σολέας-Agios Nikolaos Soleas' WHERE id=3099;
UPDATE laus SET name_national=N'Άγιος Γεώργιος Σολέας', name_latin=N'Agios Georgios Soleas', abac_name=N'Agios Georgios Soleas', display_name=N'Άγιος Γεώργιος Σολέας-Agios Georgios Soleas' WHERE id=3100;
UPDATE laus SET name_national=N'Πέτρα', name_latin=N'Petra', abac_name=N'Petra', display_name=N'Πέτρα-Petra' WHERE id=3101;
UPDATE laus SET name_national=N'Καλό Χωριό Σολέας', name_latin=N'Kalo Chorio Soleas', abac_name=N'Kalo Khorio Soleas', display_name=N'Καλό Χωριό Σολέας-Kalo Chorio Soleas' WHERE id=3102;
UPDATE laus SET name_national=N'Λεύκα', name_latin=N'Lefka', abac_name=N'Leuka', display_name=N'Λεύκα-Lefka' WHERE id=3103;
UPDATE laus SET name_national=N'Αμπελικού', name_latin=N'Ampelikou', abac_name=N'Ampelikou', display_name=N'Αμπελικού-Ampelikou' WHERE id=3104;
UPDATE laus SET name_national=N'Περιστερωνάρι', name_latin=N'Peristeronari', abac_name=N'Peristeronari', display_name=N'Περιστερωνάρι-Peristeronari' WHERE id=3105;
UPDATE laus SET name_national=N'Ελιά Λευκωσίας', name_latin=N'Elia Lefkosias', abac_name=N'Elia Leukosias', display_name=N'Ελιά Λευκωσίας-Elia Lefkosias' WHERE id=3106;
UPDATE laus SET name_national=N'Καραβοστάσι', name_latin=N'Karavostasi', abac_name=N'Karabostasi', display_name=N'Καραβοστάσι-Karavostasi' WHERE id=3107;
UPDATE laus SET name_national=N'Πεντάγεια', name_latin=N'Pentageia', abac_name=N'Pentageia', display_name=N'Πεντάγεια-Pentageia' WHERE id=3108;
UPDATE laus SET name_national=N'Αγγολέμι', name_latin=N'Angolemi', abac_name=N'Aggolemi', display_name=N'Αγγολέμι-Angolemi' WHERE id=3109;
UPDATE laus SET name_national=N'Βαρίσεια', name_latin=N'Variseia', abac_name=N'Bariseia', display_name=N'Βαρίσεια-Variseia' WHERE id=3110;
UPDATE laus SET name_national=N'Γαληνή', name_latin=N'Galini', abac_name=N'Galene', display_name=N'Γαληνή-Galini' WHERE id=3111;
UPDATE laus SET name_national=N'Ξερόβουνος', name_latin=N'Xerovounos', abac_name=N'Kserobounos', display_name=N'Ξερόβουνος-Xerovounos' WHERE id=3112;
UPDATE laus SET name_national=N'Λουτρός', name_latin=N'Loutros', abac_name=N'Loutros', display_name=N'Λουτρός-Loutros' WHERE id=3113;
UPDATE laus SET name_national=N'Άγιος Ιωάννης Σελέμανη', name_latin=N'Agios Ioannis Selemani', abac_name=N'Agios Ioannes Selemane', display_name=N'Άγιος Ιωάννης Σελέμανη-Agios Ioannis Selemani' WHERE id=3114;
UPDATE laus SET name_national=N'Αμμαδιές', name_latin=N'Ammadies', abac_name=N'Ammadies', display_name=N'Αμμαδιές-Ammadies' WHERE id=3115;
UPDATE laus SET name_national=N'Πάνω Πύργος', name_latin=N'Pano Pyrgos', abac_name=N'Pano Purgos', display_name=N'Πάνω Πύργος-Pano Pyrgos' WHERE id=3116;
UPDATE laus SET name_national=N'Κάτω Πύργος', name_latin=N'Kato Pyrgos', abac_name=N'Kato Purgos', display_name=N'Κάτω Πύργος-Kato Pyrgos' WHERE id=3117;
UPDATE laus SET name_national=N'Σελλάδι του ''Αππη (και Άγιο Γεωργούδι)', name_latin=N'Selladi tou Appi (and Agio Georgoudi)', abac_name=N'Selladi tou ''Appe (kai Agio Georgoudi)', display_name=N'Σελλάδι του ''Αππη (και Άγιο Γεωργούδι)-Selladi tou Appi (and Agio Georgoudi)' WHERE id=3118;
UPDATE laus SET name_national=N'Αλεύγα', name_latin=N'Alevga', abac_name=N'Aleuga', display_name=N'Αλεύγα-Alevga' WHERE id=3119;
UPDATE laus SET name_national=N'Πηγένια', name_latin=N'Pigenia', abac_name=N'Pegenia', display_name=N'Πηγένια-Pigenia' WHERE id=3120;
UPDATE laus SET name_national=N'Παχύαμμος', name_latin=N'Pachyammos', abac_name=N'Pakhuammos', display_name=N'Παχύαμμος-Pachyammos' WHERE id=3121;
UPDATE laus SET name_national=N'Κόκκινα', name_latin=N'Kokkina', abac_name=N'Kokkina', display_name=N'Κόκκινα-Kokkina' WHERE id=3122;
UPDATE laus SET name_national=N'Φροδίσια (Βροΐσια)', name_latin=N'Frodisia (Vroisia)', abac_name=N'Phrodisia (BroIsia)', display_name=N'Φροδίσια (Βροΐσια)-Frodisia (Vroisia)' WHERE id=3123;
UPDATE laus SET name_national=N'Άγιος Θεόδωρος Τιλλιρίας', name_latin=N'Agios Theodoros Tillirias', abac_name=N'Agios Theodoros Tillirias', display_name=N'Άγιος Θεόδωρος Τιλλιρίας-Agios Theodoros Tillirias' WHERE id=3124;
UPDATE laus SET name_national=N'Μανσούρα', name_latin=N'Mansoura', abac_name=N'Mansoura', display_name=N'Μανσούρα-Mansoura' WHERE id=3125;
UPDATE laus SET name_national=N'Μοσφίλι', name_latin=N'Mosfili', abac_name=N'Mosphili', display_name=N'Μοσφίλι-Mosfili' WHERE id=3126;
UPDATE laus SET name_national=N'Κερύνεια', name_latin=N'Keryneia', abac_name=N'Keruneia', display_name=N'Κερύνεια-Keryneia' WHERE id=3127;
UPDATE laus SET name_national=N'Πάνω Δίκωμο', name_latin=N'Pano Dikomo', abac_name=N'Pano Dikomo', display_name=N'Πάνω Δίκωμο-Pano Dikomo' WHERE id=3128;
UPDATE laus SET name_national=N'Κάτω Δίκωμο', name_latin=N'Kato Dikomo', abac_name=N'Kato Dikomo', display_name=N'Κάτω Δίκωμο-Kato Dikomo' WHERE id=3129;
UPDATE laus SET name_national=N'Κουτσοβέντης', name_latin=N'Koutsoventis', abac_name=N'Koutsobentes', display_name=N'Κουτσοβέντης-Koutsoventis' WHERE id=3130;
UPDATE laus SET name_national=N'Βουνό', name_latin=N'Vouno', abac_name=N'Bouno', display_name=N'Βουνό-Vouno' WHERE id=3131;
UPDATE laus SET name_national=N'Σιχαρί', name_latin=N'Sichari', abac_name=N'Sikhari', display_name=N'Σιχαρί-Sichari' WHERE id=3132;
UPDATE laus SET name_national=N'Φότα', name_latin=N'Fota', abac_name=N'Phota', display_name=N'Φότα-Fota' WHERE id=3133;
UPDATE laus SET name_national=N'Κρηνί', name_latin=N'Krini', abac_name=N'Kreni', display_name=N'Κρηνί-Krini' WHERE id=3134;
UPDATE laus SET name_national=N'Πιλερί', name_latin=N'Pileri', abac_name=N'Pileri', display_name=N'Πιλερί-Pileri' WHERE id=3135;
UPDATE laus SET name_national=N'Κιόμουρτζου', name_latin=N'Kiomourtzou', abac_name=N'Kiomourtzou', display_name=N'Κιόμουρτζου-Kiomourtzou' WHERE id=3136;
UPDATE laus SET name_national=N'Αγίρδα', name_latin=N'Agirda', abac_name=N'Agirda', display_name=N'Αγίρδα-Agirda' WHERE id=3137;
UPDATE laus SET name_national=N'Άγιος Ερμόλαος', name_latin=N'Agios Ermolaos', abac_name=N'Agios Ermolaos', display_name=N'Άγιος Ερμόλαος-Agios Ermolaos' WHERE id=3138;
UPDATE laus SET name_national=N'Σύσκληπος', name_latin=N'Sysklipos', abac_name=N'Susklepos', display_name=N'Σύσκληπος-Sysklipos' WHERE id=3139;
UPDATE laus SET name_national=N'Κοντεμένος', name_latin=N'Kontemenos', abac_name=N'Kontemenos', display_name=N'Κοντεμένος-Kontemenos' WHERE id=3140;
UPDATE laus SET name_national=N'Ασώματος Κερύνειας', name_latin=N'Asomatos Keryneias', abac_name=N'Asomatos Keruneias', display_name=N'Ασώματος Κερύνειας-Asomatos Keryneias' WHERE id=3141;
UPDATE laus SET name_national=N'Καμπυλή', name_latin=N'Kampyli', abac_name=N'Kampule', display_name=N'Καμπυλή-Kampyli' WHERE id=3142;
UPDATE laus SET name_national=N'Καρπάσεια', name_latin=N'Karpaseia', abac_name=N'Karpaseia', display_name=N'Καρπάσεια-Karpaseia' WHERE id=3143;
UPDATE laus SET name_national=N'Μύρτου', name_latin=N'Myrtou', abac_name=N'Murtou', display_name=N'Μύρτου-Myrtou' WHERE id=3144;
UPDATE laus SET name_national=N'Διόριος', name_latin=N'Diorios', abac_name=N'Diorios', display_name=N'Διόριος-Diorios' WHERE id=3145;
UPDATE laus SET name_national=N'Αγία Ειρήνη Κερύνειας', name_latin=N'Agia Eirini Keryneias', abac_name=N'Agia Eirene Keruneias', display_name=N'Αγία Ειρήνη Κερύνειας-Agia Eirini Keryneias' WHERE id=3146;
UPDATE laus SET name_national=N'Κορμακίτης', name_latin=N'Kormakitis', abac_name=N'Kormakites', display_name=N'Κορμακίτης-Kormakitis' WHERE id=3147;
UPDATE laus SET name_national=N'Λιβερά', name_latin=N'Livera', abac_name=N'Libera', display_name=N'Λιβερά-Livera' WHERE id=3148;
UPDATE laus SET name_national=N'Καλογραία', name_latin=N'Kalograia', abac_name=N'Kalograia', display_name=N'Καλογραία-Kalograia' WHERE id=3149;
UPDATE laus SET name_national=N'Άγιος Αμβρόσιος Κερύνειας', name_latin=N'Agios Amvrosios Keryneias', abac_name=N'Agios Ambrosios Keruneias', display_name=N'Άγιος Αμβρόσιος Κερύνειας-Agios Amvrosios Keryneias' WHERE id=3150;
UPDATE laus SET name_national=N'Χάρκεια (Χάρτσεια)', name_latin=N'Charkeia (Chartseia)', abac_name=N'Kharkeia (Khartseia)', display_name=N'Χάρκεια (Χάρτσεια)-Charkeia (Chartseia)' WHERE id=3151;
UPDATE laus SET name_national=N'Τραπέζα', name_latin=N'Trapeza', abac_name=N'Trapeza', display_name=N'Τραπέζα-Trapeza' WHERE id=3152;
UPDATE laus SET name_national=N'Κλεπίνη', name_latin=N'Klepini', abac_name=N'Klepine', display_name=N'Κλεπίνη-Klepini' WHERE id=3153;
UPDATE laus SET name_national=N'Άγιος Επίκτητος', name_latin=N'Agios Epiktitos', abac_name=N'Agios Epiktetos', display_name=N'Άγιος Επίκτητος-Agios Epiktitos' WHERE id=3154;
UPDATE laus SET name_national=N'Μπέλαπαϊς', name_latin=N'Belapais', abac_name=N'Mpelapais', display_name=N'Μπέλαπαϊς-Belapais' WHERE id=3155;
UPDATE laus SET name_national=N'Καζάφανι', name_latin=N'Kazafani', abac_name=N'Kazaphani', display_name=N'Καζάφανι-Kazafani' WHERE id=3156;
UPDATE laus SET name_national=N'Θέρμεια', name_latin=N'Thermeia', abac_name=N'Thermeia', display_name=N'Θέρμεια-Thermeia' WHERE id=3157;
UPDATE laus SET name_national=N'Καράκουμι', name_latin=N'Karakoumi', abac_name=N'Karakoumi', display_name=N'Καράκουμι-Karakoumi' WHERE id=3158;
UPDATE laus SET name_national=N'Τέμπλος', name_latin=N'Templos', abac_name=N'Templos', display_name=N'Τέμπλος-Templos' WHERE id=3159;
UPDATE laus SET name_national=N'Κάρμι', name_latin=N'Karmi', abac_name=N'Karmi', display_name=N'Κάρμι-Karmi' WHERE id=3160;
UPDATE laus SET name_national=N'Φτέριχα', name_latin=N'Ftericha', abac_name=N'Phterikha', display_name=N'Φτέριχα-Ftericha' WHERE id=3161;
UPDATE laus SET name_national=N'Τριμίθι', name_latin=N'Trimithi', abac_name=N'Trimithi', display_name=N'Τριμίθι-Trimithi' WHERE id=3162;
UPDATE laus SET name_national=N'Παλαιόσοφος', name_latin=N'Palaiosofos', abac_name=N'Palaiosophos', display_name=N'Παλαιόσοφος-Palaiosofos' WHERE id=3163;
UPDATE laus SET name_national=N'Μότηδες', name_latin=N'Motides', abac_name=N'Motedes', display_name=N'Μότηδες-Motides' WHERE id=3164;
UPDATE laus SET name_national=N'Ελιά Κερύνειας', name_latin=N'Elia Keryneias', abac_name=N'Elia Keruneias', display_name=N'Ελιά Κερύνειας-Elia Keryneias' WHERE id=3165;
UPDATE laus SET name_national=N'Καραβάς', name_latin=N'Karavas', abac_name=N'Karabas', display_name=N'Καραβάς-Karavas' WHERE id=3166;
UPDATE laus SET name_national=N'Άγιος Γεώργιος Κερύνειας', name_latin=N'Agios Georgios Keryneias', abac_name=N'Agios Georgios Keruneias', display_name=N'Άγιος Γεώργιος Κερύνειας-Agios Georgios Keryneias' WHERE id=3167;
UPDATE laus SET name_national=N'Αγριδάκι', name_latin=N'Agridaki', abac_name=N'Agridaki', display_name=N'Αγριδάκι-Agridaki' WHERE id=3168;
UPDATE laus SET name_national=N'Λάρνακας Λαπήθου', name_latin=N'Larnakas Lapithou', abac_name=N'Larnakas Lapethou', display_name=N'Λάρνακας Λαπήθου-Larnakas Lapithou' WHERE id=3169;
UPDATE laus SET name_national=N'Λάπηθος', name_latin=N'Lapithos', abac_name=N'Lapethos', display_name=N'Λάπηθος-Lapithos' WHERE id=3170;
UPDATE laus SET name_national=N'Βασίλεια', name_latin=N'Vasileia', abac_name=N'Basileia', display_name=N'Βασίλεια-Vasileia' WHERE id=3171;
UPDATE laus SET name_national=N'Πάναγρα', name_latin=N'Panagra', abac_name=N'Panagra', display_name=N'Πάναγρα-Panagra' WHERE id=3172;
UPDATE laus SET name_national=N'Όργα', name_latin=N'Orga', abac_name=N'Orga', display_name=N'Όργα-Orga' WHERE id=3173;
UPDATE laus SET name_national=N'Αμμόχωστος', name_latin=N'Ammochostos', abac_name=N'Ammokhostos', display_name=N'Αμμόχωστος-Ammochostos' WHERE id=3174;
UPDATE laus SET name_national=N'Αγία Νάπα', name_latin=N'Agia Napa', abac_name=N'Agia Napa', display_name=N'Αγία Νάπα-Agia Napa' WHERE id=3175;
UPDATE laus SET name_national=N'Παραλίμνι', name_latin=N'Paralimni', abac_name=N'Paralimni', display_name=N'Παραλίμνι-Paralimni' WHERE id=3176;
UPDATE laus SET name_national=N'Δερύνεια', name_latin=N'Deryneia', abac_name=N'Deruneia', display_name=N'Δερύνεια-Deryneia' WHERE id=3177;
UPDATE laus SET name_national=N'Σωτήρα Αμμοχώστου', name_latin=N'Sotira Ammochostou', abac_name=N'Sotera Ammokhostou', display_name=N'Σωτήρα Αμμοχώστου-Sotira Ammochostou' WHERE id=3178;
UPDATE laus SET name_national=N'Λιοπέτρι', name_latin=N'Liopetri', abac_name=N'Liopetri', display_name=N'Λιοπέτρι-Liopetri' WHERE id=3179;
UPDATE laus SET name_national=N'Φρέναρος', name_latin=N'Frenaros', abac_name=N'Phrenaros', display_name=N'Φρέναρος-Frenaros' WHERE id=3180;
UPDATE laus SET name_national=N'Αυγόρου', name_latin=N'Avgorou', abac_name=N'Augorou', display_name=N'Αυγόρου-Avgorou' WHERE id=3181;
UPDATE laus SET name_national=N'Άχνα', name_latin=N'Achna', abac_name=N'Akhna', display_name=N'Άχνα-Achna' WHERE id=3182;
UPDATE laus SET name_national=N'Μακράσυκα', name_latin=N'Makrasyka', abac_name=N'Makrasuka', display_name=N'Μακράσυκα-Makrasyka' WHERE id=3183;
UPDATE laus SET name_national=N'Καλοψίδα', name_latin=N'Kalopsida', abac_name=N'Kalopsida', display_name=N'Καλοψίδα-Kalopsida' WHERE id=3184;
UPDATE laus SET name_national=N'Αχερίτου', name_latin=N'Acheritou', abac_name=N'Akheritou', display_name=N'Αχερίτου-Acheritou' WHERE id=3185;
UPDATE laus SET name_national=N'Έγκωμη Αμμοχώστου', name_latin=N'Egkomi Ammochostou', abac_name=N'Egkome Ammokhostou', display_name=N'Έγκωμη Αμμοχώστου-Egkomi Ammochostou' WHERE id=3186;
UPDATE laus SET name_national=N'Άγιος Σέργιος', name_latin=N'Agios Sergios', abac_name=N'Agios Sergios', display_name=N'Άγιος Σέργιος-Agios Sergios' WHERE id=3187;
UPDATE laus SET name_national=N'Στύλλοι', name_latin=N'Stylloi', abac_name=N'Stulloi', display_name=N'Στύλλοι-Stylloi' WHERE id=3188;
UPDATE laus SET name_national=N'Λιμνιά', name_latin=N'Limnia', abac_name=N'Limnia', display_name=N'Λιμνιά-Limnia' WHERE id=3189;
UPDATE laus SET name_national=N'Αλόδα', name_latin=N'Aloda', abac_name=N'Aloda', display_name=N'Αλόδα-Aloda' WHERE id=3190;
UPDATE laus SET name_national=N'Σπαθαρικό', name_latin=N'Spathariko', abac_name=N'Spathariko', display_name=N'Σπαθαρικό-Spathariko' WHERE id=3191;
UPDATE laus SET name_national=N'Αρναδί', name_latin=N'Arnadi', abac_name=N'Arnadi', display_name=N'Αρναδί-Arnadi' WHERE id=3192;
UPDATE laus SET name_national=N'Άγιος Γεώργιος Αμμοχώστου', name_latin=N'Agios Georgios Ammochostou', abac_name=N'Agios Georgios Ammokhostou', display_name=N'Άγιος Γεώργιος Αμμοχώστου-Agios Georgios Ammochostou' WHERE id=3193;
UPDATE laus SET name_national=N'Περιβόλια Τρικώμου', name_latin=N'Perivolia Trikomou', abac_name=N'Peribolia Trikomou', display_name=N'Περιβόλια Τρικώμου-Perivolia Trikomou' WHERE id=3194;
UPDATE laus SET name_national=N'Σύγκραση', name_latin=N'Sygkrasi', abac_name=N'Sugkrase', display_name=N'Σύγκραση-Sygkrasi' WHERE id=3195;
UPDATE laus SET name_national=N'Λάπαθος', name_latin=N'Lapathos', abac_name=N'Lapathos', display_name=N'Λάπαθος-Lapathos' WHERE id=3196;
UPDATE laus SET name_national=N'Τρίκωμο', name_latin=N'Trikomo', abac_name=N'Trikomo', display_name=N'Τρίκωμο-Trikomo' WHERE id=3197;
UPDATE laus SET name_national=N'Κούκλια Αμμοχώστου', name_latin=N'Kouklia Ammochostou', abac_name=N'Kouklia Ammokhostou', display_name=N'Κούκλια Αμμοχώστου-Kouklia Ammochostou' WHERE id=3198;
UPDATE laus SET name_national=N'Κοντέα', name_latin=N'Kontea', abac_name=N'Kontea', display_name=N'Κοντέα-Kontea' WHERE id=3199;
UPDATE laus SET name_national=N'Λύση', name_latin=N'Lysi', abac_name=N'Luse', display_name=N'Λύση-Lysi' WHERE id=3200;
UPDATE laus SET name_national=N'Βατιλή', name_latin=N'Vatili', abac_name=N'Batile', display_name=N'Βατιλή-Vatili' WHERE id=3201;
UPDATE laus SET name_national=N'Στρογγυλός', name_latin=N'Strongylos', abac_name=N'Stroggulos', display_name=N'Στρογγυλός-Strongylos' WHERE id=3202;
UPDATE laus SET name_national=N'Σίντα', name_latin=N'Sinta', abac_name=N'Sinta', display_name=N'Σίντα-Sinta' WHERE id=3203;
UPDATE laus SET name_national=N'Γαϊδουράς (Νέα Σπάρτη)', name_latin=N'Gaidouras (Nea Sparti)', abac_name=N'Gaidouras (Nea Sparte)', display_name=N'Γαϊδουράς (Νέα Σπάρτη)-Gaidouras (Nea Sparti)' WHERE id=3204;
UPDATE laus SET name_national=N'Πραστιό Αμμοχώστου', name_latin=N'Prastio Ammochostou', abac_name=N'Prastio Ammokhostou', display_name=N'Πραστιό Αμμοχώστου-Prastio Ammochostou' WHERE id=3205;
UPDATE laus SET name_national=N'Πυργά (η) Αμμοχώστου', name_latin=N'Pyrga Ammochostou', abac_name=N'Purga (e) Ammokhostou', display_name=N'Πυργά (η) Αμμοχώστου-Pyrga Ammochostou' WHERE id=3206;
UPDATE laus SET name_national=N'Μουσουλίτα', name_latin=N'Mousoulita', abac_name=N'Mousoulita', display_name=N'Μουσουλίτα-Mousoulita' WHERE id=3207;
UPDATE laus SET name_national=N'Σανταλάρης', name_latin=N'Santalaris', abac_name=N'Santalares', display_name=N'Σανταλάρης-Santalaris' WHERE id=3208;
UPDATE laus SET name_national=N'Μαράθα', name_latin=N'Maratha', abac_name=N'Maratha', display_name=N'Μαράθα-Maratha' WHERE id=3209;
UPDATE laus SET name_national=N'Περιστερώνα Αμμοχώστου', name_latin=N'Peristerona Ammochostou', abac_name=N'Peristerona Ammokhostou', display_name=N'Περιστερώνα Αμμοχώστου-Peristerona Ammochostou' WHERE id=3210;
UPDATE laus SET name_national=N'Πηγή', name_latin=N'Pigi', abac_name=N'Pege', display_name=N'Πηγή-Pigi' WHERE id=3211;
UPDATE laus SET name_national=N'Γέναγρα', name_latin=N'Genagra', abac_name=N'Genagra', display_name=N'Γέναγρα-Genagra' WHERE id=3212;
UPDATE laus SET name_national=N'Μηλιά Αμμοχώστου', name_latin=N'Milia Ammochostou', abac_name=N'Melia Ammokhostou', display_name=N'Μηλιά Αμμοχώστου-Milia Ammochostou' WHERE id=3213;
UPDATE laus SET name_national=N'Γύψου', name_latin=N'Gypsou', abac_name=N'Gupsou', display_name=N'Γύψου-Gypsou' WHERE id=3214;
UPDATE laus SET name_national=N'Λευκόνοικο', name_latin=N'Lefkonoiko', abac_name=N'Leukonoiko', display_name=N'Λευκόνοικο-Lefkonoiko' WHERE id=3215;
UPDATE laus SET name_national=N'Ψυλλάτος', name_latin=N'Psyllatos', abac_name=N'Psullatos', display_name=N'Ψυλλάτος-Psyllatos' WHERE id=3216;
UPDATE laus SET name_national=N'Κνώδαρα', name_latin=N'Knodara', abac_name=N'Knodara', display_name=N'Κνώδαρα-Knodara' WHERE id=3217;
UPDATE laus SET name_national=N'Γούφες', name_latin=N'Goufes', abac_name=N'Gouphes', display_name=N'Γούφες-Goufes' WHERE id=3218;
UPDATE laus SET name_national=N'Άσκεια (Άσσεια)', name_latin=N'Askeia (Αsseia)', abac_name=N'Askeia (Asseia)', display_name=N'Άσκεια (Άσσεια)-Askeia (Αsseia)' WHERE id=3219;
UPDATE laus SET name_national=N'Αφάντεια-Ορνίθι', name_latin=N'Afanteia-Ornithi', abac_name=N'Aphanteia-Ornithi', display_name=N'Αφάντεια-Ορνίθι-Afanteia-Ornithi' WHERE id=3220;
UPDATE laus SET name_national=N'Αγγαστίνα', name_latin=N'Angastina', abac_name=N'Aggastina', display_name=N'Αγγαστίνα-Angastina' WHERE id=3221;
UPDATE laus SET name_national=N'Μαραθόβουνος', name_latin=N'Marathovounos', abac_name=N'Marathobounos', display_name=N'Μαραθόβουνος-Marathovounos' WHERE id=3222;
UPDATE laus SET name_national=N'Βιτσάδα', name_latin=N'Vitsada', abac_name=N'Bitsada', display_name=N'Βιτσάδα-Vitsada' WHERE id=3223;
UPDATE laus SET name_national=N'Κίαδος (Τζιάος)', name_latin=N'Kiados (Tziaos)', abac_name=N'Kiados (Tziaos)', display_name=N'Κίαδος (Τζιάος)-Kiados (Tziaos)' WHERE id=3224;
UPDATE laus SET name_national=N'Κορνόκηπος', name_latin=N'Kornokipos', abac_name=N'Kornokepos', display_name=N'Κορνόκηπος-Kornokipos' WHERE id=3225;
UPDATE laus SET name_national=N'Άγιος Χαρίτων', name_latin=N'Agios Chariton', abac_name=N'Agios Khariton', display_name=N'Άγιος Χαρίτων-Agios Chariton' WHERE id=3226;
UPDATE laus SET name_national=N'Τρυπημένη', name_latin=N'Trypimeni', abac_name=N'Trupemene', display_name=N'Τρυπημένη-Trypimeni' WHERE id=3227;
UPDATE laus SET name_national=N'Άρτεμι', name_latin=N'Artemi', abac_name=N'Artemi', display_name=N'Άρτεμι-Artemi' WHERE id=3228;
UPDATE laus SET name_national=N'Άγιος Νικόλαος Αμμοχώστου', name_latin=N'Agios Nikolaos Ammochostou', abac_name=N'Agios Nikolaos Ammokhostou', display_name=N'Άγιος Νικόλαος Αμμοχώστου-Agios Nikolaos Ammochostou' WHERE id=3229;
UPDATE laus SET name_national=N'Πλατάνι', name_latin=N'Platani', abac_name=N'Platani', display_name=N'Πλατάνι-Platani' WHERE id=3230;
UPDATE laus SET name_national=N'Ακανθού', name_latin=N'Akanthou', abac_name=N'Akanthou', display_name=N'Ακανθού-Akanthou' WHERE id=3231;
UPDATE laus SET name_national=N'Μελούντα', name_latin=N'Melounta', abac_name=N'Melounta', display_name=N'Μελούντα-Melounta' WHERE id=3232;
UPDATE laus SET name_national=N'Άγιος Ιάκωβος', name_latin=N'Agios Iakovos', abac_name=N'Agios Iakobos', display_name=N'Άγιος Ιάκωβος-Agios Iakovos' WHERE id=3233;
UPDATE laus SET name_national=N'Άγιος Ανδρόνικος Tρικώμου (Τοπσούκιογιου ή Άγιο Ανδρονικούδι)', name_latin=N'Agios Andronikos Trikomou (Topsoukiogiou or Agio Andronikoudi)', abac_name=N'Agios Andronikos Trikomou (Topsoukiogiou e Agio Andronikoudi)', display_name=N'Άγιος Ανδρόνικος Tρικώμου (Τοπσούκιογιου ή Άγιο Ανδρονικούδι)-Agios Andronikos Trikomou (Topsoukiogiou or Agio Andronikoudi)' WHERE id=3234;
UPDATE laus SET name_national=N'Μάνδρες Αμμοχώστου', name_latin=N'Mandres Ammochostou', abac_name=N'Mandres Ammokhostou', display_name=N'Μάνδρες Αμμοχώστου-Mandres Ammochostou' WHERE id=3235;
UPDATE laus SET name_national=N'Άρδανα', name_latin=N'Ardana', abac_name=N'Ardana', display_name=N'Άρδανα-Ardana' WHERE id=3236;
UPDATE laus SET name_national=N'Φλαμούδι', name_latin=N'Flamoudi', abac_name=N'Phlamoudi', display_name=N'Φλαμούδι-Flamoudi' WHERE id=3237;
UPDATE laus SET name_national=N'Μπογάζι', name_latin=N'Bogazi', abac_name=N'Mpogazi', display_name=N'Μπογάζι-Bogazi' WHERE id=3238;
UPDATE laus SET name_national=N'Μοναργά', name_latin=N'Monarga', abac_name=N'Monarga', display_name=N'Μοναργά-Monarga' WHERE id=3239;
UPDATE laus SET name_national=N'Άγιος Ηλίας', name_latin=N'Agios Ilias', abac_name=N'Agios Elias', display_name=N'Άγιος Ηλίας-Agios Ilias' WHERE id=3240;
UPDATE laus SET name_national=N'Γαστριά', name_latin=N'Gastria', abac_name=N'Gastria', display_name=N'Γαστριά-Gastria' WHERE id=3241;
UPDATE laus SET name_national=N'Αυγολίδα', name_latin=N'Avgolida', abac_name=N'Augolida', display_name=N'Αυγολίδα-Avgolida' WHERE id=3242;
UPDATE laus SET name_national=N'Πατρίκι', name_latin=N'Patriki', abac_name=N'Patriki', display_name=N'Πατρίκι-Patriki' WHERE id=3243;
UPDATE laus SET name_national=N'Γεράνι', name_latin=N'Gerani', abac_name=N'Gerani', display_name=N'Γεράνι-Gerani' WHERE id=3244;
UPDATE laus SET name_national=N'Όβγορος', name_latin=N'Ovgoros', abac_name=N'Obgoros', display_name=N'Όβγορος-Ovgoros' WHERE id=3245;
UPDATE laus SET name_national=N'Δαυλός', name_latin=N'Davlos', abac_name=N'Daulos', display_name=N'Δαυλός-Davlos' WHERE id=3246;
UPDATE laus SET name_national=N'Άγιος Θεόδωρος Αμμοχώστου', name_latin=N'Agios Theodoros Ammochostou', abac_name=N'Agios Theodoros Ammokhostou', display_name=N'Άγιος Θεόδωρος Αμμοχώστου-Agios Theodoros Ammochostou' WHERE id=3247;
UPDATE laus SET name_national=N'Βοκολίδα', name_latin=N'Vokolida', abac_name=N'Bokolida', display_name=N'Βοκολίδα-Vokolida' WHERE id=3248;
UPDATE laus SET name_national=N'Ταύρου', name_latin=N'Tavrou', abac_name=N'Taurou', display_name=N'Ταύρου-Tavrou' WHERE id=3249;
UPDATE laus SET name_national=N'Άγιος Ευστάθιος', name_latin=N'Agios Efstathios', abac_name=N'Agios Eustathios', display_name=N'Άγιος Ευστάθιος-Agios Efstathios' WHERE id=3250;
UPDATE laus SET name_national=N'Λιβάδια Αμμοχώστου', name_latin=N'Livadia Ammochostou', abac_name=N'Libadia Ammokhostou', display_name=N'Λιβάδια Αμμοχώστου-Livadia Ammochostou' WHERE id=3251;
UPDATE laus SET name_national=N'Κρίδεια', name_latin=N'Krideia', abac_name=N'Krideia', display_name=N'Κρίδεια-Krideia' WHERE id=3252;
UPDATE laus SET name_national=N'Κώμη (Κώμη Κεπίρ)', name_latin=N'Komi (Komi Kepir)', abac_name=N'Kome (Kome Kepir)', display_name=N'Κώμη (Κώμη Κεπίρ)-Komi (Komi Kepir)' WHERE id=3253;
UPDATE laus SET name_national=N'Γαλάτεια', name_latin=N'Galateia', abac_name=N'Galateia', display_name=N'Γαλάτεια-Galateia' WHERE id=3254;
UPDATE laus SET name_national=N'Επτακώμη', name_latin=N'Eptakomi', abac_name=N'Eptakome', display_name=N'Επτακώμη-Eptakomi' WHERE id=3255;
UPDATE laus SET name_national=N'Κώμα του Γιαλού', name_latin=N'Koma tou Gialou', abac_name=N'Koma tou Gialou', display_name=N'Κώμα του Γιαλού-Koma tou Gialou' WHERE id=3256;
UPDATE laus SET name_national=N'Νέτα', name_latin=N'Neta', abac_name=N'Neta', display_name=N'Νέτα-Neta' WHERE id=3257;
UPDATE laus SET name_national=N'Βοθύλακας', name_latin=N'Vοthylakas', abac_name=N'Bothulakas', display_name=N'Βοθύλακας-Vοthylakas' WHERE id=3258;
UPDATE laus SET name_national=N'Λυθράγκωμη', name_latin=N'Lythragkomi', abac_name=N'Luthragkome', display_name=N'Λυθράγκωμη-Lythragkomi' WHERE id=3259;
UPDATE laus SET name_national=N'Βασίλι', name_latin=N'Vasili', abac_name=N'Basili', display_name=N'Βασίλι-Vasili' WHERE id=3260;
UPDATE laus SET name_national=N'Λεονάρισσο', name_latin=N'Leonarisso', abac_name=N'Leonarisso', display_name=N'Λεονάρισσο-Leonarisso' WHERE id=3261;
UPDATE laus SET name_national=N'Πλατανισσός', name_latin=N'Platanissos', abac_name=N'Platanissos', display_name=N'Πλατανισσός-Platanissos' WHERE id=3262;
UPDATE laus SET name_national=N'Κοιλάνεμος', name_latin=N'Koilanemos', abac_name=N'Koilanemos', display_name=N'Κοιλάνεμος-Koilanemos' WHERE id=3263;
UPDATE laus SET name_national=N'Άγιος Ανδρόνικος Καρπασίας', name_latin=N'Agios Andronikos Karpasias', abac_name=N'Agios Andronikos Karpasias', display_name=N'Άγιος Ανδρόνικος Καρπασίας-Agios Andronikos Karpasias' WHERE id=3264;
UPDATE laus SET name_national=N'Άγιος Συμεών', name_latin=N'Agios Symeon', abac_name=N'Agios Sumeon', display_name=N'Άγιος Συμεών-Agios Symeon' WHERE id=3265;
UPDATE laus SET name_national=N'Μελάναργα', name_latin=N'Melanarga', abac_name=N'Melanarga', display_name=N'Μελάναργα-Melanarga' WHERE id=3266;
UPDATE laus SET name_national=N'Αιγιαλούσα', name_latin=N'Aigialousa', abac_name=N'Aigialousa', display_name=N'Αιγιαλούσα-Aigialousa' WHERE id=3267;
UPDATE laus SET name_national=N'Αγία Τριάς', name_latin=N'Agia Trias', abac_name=N'Agia Trias', display_name=N'Αγία Τριάς-Agia Trias' WHERE id=3268;
UPDATE laus SET name_national=N'Κορόβεια', name_latin=N'Koroveia', abac_name=N'Korobeia', display_name=N'Κορόβεια-Koroveia' WHERE id=3269;
UPDATE laus SET name_national=N'Γαληνόπωρνη', name_latin=N'Galinoporni', abac_name=N'Galenoporne', display_name=N'Γαληνόπωρνη-Galinoporni' WHERE id=3270;
UPDATE laus SET name_national=N'Ριζοκάρπασο', name_latin=N'Rizokarpaso', abac_name=N'Rizokarpaso', display_name=N'Ριζοκάρπασο-Rizokarpaso' WHERE id=3271;
UPDATE laus SET name_national=N'Λάρνακα', name_latin=N'Larnaka', abac_name=N'Larnaka', display_name=N'Λάρνακα-Larnaka' WHERE id=3272;
UPDATE laus SET name_national=N'Αραδίππου', name_latin=N'Aradippou', abac_name=N'Aradippou', display_name=N'Αραδίππου-Aradippou' WHERE id=3273;
UPDATE laus SET name_national=N'Λιβάδια Λάρνακας', name_latin=N'Livadia Larnakas', abac_name=N'Libadia Larnakas', display_name=N'Λιβάδια Λάρνακας-Livadia Larnakas' WHERE id=3274;
UPDATE laus SET name_national=N'Δρομολαξιά -Μενεού', name_latin=N'Dromolaxia - Meneou', abac_name=N'Dromolaxia -Meneou', display_name=N'Δρομολαξιά -Μενεού-Dromolaxia - Meneou' WHERE id=3275;
UPDATE laus SET name_national=N'Κελλιά', name_latin=N'Kellia', abac_name=N'Kellia', display_name=N'Κελλιά-Kellia' WHERE id=3276;
UPDATE laus SET name_national=N'Τρούλλοι', name_latin=N'Troulloi', abac_name=N'Troulloi', display_name=N'Τρούλλοι-Troulloi' WHERE id=3277;
UPDATE laus SET name_national=N'Bορόκληνη (Ορόκληνη)', name_latin=N'Voroklini (Oroklini)', abac_name=N'Boroklene (Oroklene)', display_name=N'Bορόκληνη (Ορόκληνη)-Voroklini (Oroklini)' WHERE id=3278;
UPDATE laus SET name_national=N'Αβδελλερό', name_latin=N'Avdellero', abac_name=N'Abdellero', display_name=N'Αβδελλερό-Avdellero' WHERE id=3279;
UPDATE laus SET name_national=N'Πύλα', name_latin=N'Pyla', abac_name=N'Pula', display_name=N'Πύλα-Pyla' WHERE id=3280;
UPDATE laus SET name_national=N'Ξυλοτύμβου', name_latin=N'Xylotymvou', abac_name=N'Ksulotumbou', display_name=N'Ξυλοτύμβου-Xylotymvou' WHERE id=3281;
UPDATE laus SET name_national=N'Ορμίδεια', name_latin=N'Ormideia', abac_name=N'Ormideia', display_name=N'Ορμίδεια-Ormideia' WHERE id=3282;
UPDATE laus SET name_national=N'Ξυλοφάγου', name_latin=N'Xylofagou', abac_name=N'Ksulophagou', display_name=N'Ξυλοφάγου-Xylofagou' WHERE id=3283;
UPDATE laus SET name_national=N'Πέργαμος', name_latin=N'Pergamos', abac_name=N'Pergamos', display_name=N'Πέργαμος-Pergamos' WHERE id=3284;
UPDATE laus SET name_national=N'Κίτι', name_latin=N'Kiti', abac_name=N'Kiti', display_name=N'Κίτι-Kiti' WHERE id=3285;
UPDATE laus SET name_national=N'Περιβόλια Λάρνακας', name_latin=N'Perivolia Larnakas', abac_name=N'Peribolia Larnakas', display_name=N'Περιβόλια Λάρνακας-Perivolia Larnakas' WHERE id=3286;
UPDATE laus SET name_national=N'Τερσεφάνου', name_latin=N'Tersefanou', abac_name=N'Tersephanou', display_name=N'Τερσεφάνου-Tersefanou' WHERE id=3287;
UPDATE laus SET name_national=N'Σοφτάδες', name_latin=N'Softades', abac_name=N'Sophtades', display_name=N'Σοφτάδες-Softades' WHERE id=3288;
UPDATE laus SET name_national=N'Μαζωτός', name_latin=N'Mazotos', abac_name=N'Mazotos', display_name=N'Μαζωτός-Mazotos' WHERE id=3289;
UPDATE laus SET name_national=N'Αλαμινός', name_latin=N'Alaminos', abac_name=N'Alaminos', display_name=N'Αλαμινός-Alaminos' WHERE id=3290;
UPDATE laus SET name_national=N'Αναφωτίδα', name_latin=N'Anafotida', abac_name=N'Anaphotida', display_name=N'Αναφωτίδα-Anafotida' WHERE id=3291;
UPDATE laus SET name_national=N'Απλάντα', name_latin=N'Aplanta', abac_name=N'Aplanta', display_name=N'Απλάντα-Aplanta' WHERE id=3292;
UPDATE laus SET name_national=N'Κιβισίλι', name_latin=N'Kivisili', abac_name=N'Kibisili', display_name=N'Κιβισίλι-Kivisili' WHERE id=3293;
UPDATE laus SET name_national=N'Αλεθρικό', name_latin=N'Alethriko', abac_name=N'Alethriko', display_name=N'Αλεθρικό-Alethriko' WHERE id=3294;
UPDATE laus SET name_national=N'Κλαυδιά', name_latin=N'Klavdia', abac_name=N'Klaudia', display_name=N'Κλαυδιά-Klavdia' WHERE id=3295;
UPDATE laus SET name_national=N'Αγγλισίδες', name_latin=N'Anglisides', abac_name=N'Agglisides', display_name=N'Αγγλισίδες-Anglisides' WHERE id=3296;
UPDATE laus SET name_national=N'Μενόγεια', name_latin=N'Menogeia', abac_name=N'Menogeia', display_name=N'Μενόγεια-Menogeia' WHERE id=3297;
UPDATE laus SET name_national=N'Πετροφάνι', name_latin=N'Petrofani', abac_name=N'Petrophani', display_name=N'Πετροφάνι-Petrofani' WHERE id=3298;
UPDATE laus SET name_national=N'Αθιένου', name_latin=N'Athienou', abac_name=N'Athienou', display_name=N'Αθιένου-Athienou' WHERE id=3299;
UPDATE laus SET name_national=N'Μελούσεια', name_latin=N'Melouseia', abac_name=N'Melouseia', display_name=N'Μελούσεια-Melouseia' WHERE id=3300;
UPDATE laus SET name_national=N'Τρεμετουσιά', name_latin=N'Tremetousia', abac_name=N'Tremetousia', display_name=N'Τρεμετουσιά-Tremetousia' WHERE id=3301;
UPDATE laus SET name_national=N'Άρσος Λάρνακας', name_latin=N'Arsos Larnakas', abac_name=N'Arsos Larnakas', display_name=N'Άρσος Λάρνακας-Arsos Larnakas' WHERE id=3302;
UPDATE laus SET name_national=N'Καλό Χωριό Λάρνακας', name_latin=N'Kalo Chorio Larnakas', abac_name=N'Kalo Khorio Larnakas', display_name=N'Καλό Χωριό Λάρνακας-Kalo Chorio Larnakas' WHERE id=3303;
UPDATE laus SET name_national=N'Αγία Άννα', name_latin=N'Agia Anna', abac_name=N'Agia Anna', display_name=N'Αγία Άννα-Agia Anna' WHERE id=3304;
UPDATE laus SET name_national=N'Μοσφιλωτή', name_latin=N'Mosfiloti', abac_name=N'Mosphilote', display_name=N'Μοσφιλωτή-Mosfiloti' WHERE id=3305;
UPDATE laus SET name_national=N'Ψευδάς', name_latin=N'Psevdas', abac_name=N'Pseudas', display_name=N'Ψευδάς-Psevdas' WHERE id=3306;
UPDATE laus SET name_national=N'Πυργά (τα) Λάρνακας', name_latin=N'Pyrga Larnakas', abac_name=N'Purga (ta) Larnakas', display_name=N'Πυργά (τα) Λάρνακας-Pyrga Larnakas' WHERE id=3307;
UPDATE laus SET name_national=N'Κόρνος', name_latin=N'Kornos', abac_name=N'Kornos', display_name=N'Κόρνος-Kornos' WHERE id=3308;
UPDATE laus SET name_national=N'Δελίκηπος', name_latin=N'Delikipos', abac_name=N'Delikepos', display_name=N'Δελίκηπος-Delikipos' WHERE id=3309;
UPDATE laus SET name_national=N'Κόση', name_latin=N'Kosi', abac_name=N'Kose', display_name=N'Κόση-Kosi' WHERE id=3310;
UPDATE laus SET name_national=N'Ζύγι', name_latin=N'Zygi', abac_name=N'Zugi', display_name=N'Ζύγι-Zygi' WHERE id=3311;
UPDATE laus SET name_national=N'Μαρί', name_latin=N'Mari', abac_name=N'Mari', display_name=N'Μαρί-Mari' WHERE id=3312;
UPDATE laus SET name_national=N'Καλαβασός', name_latin=N'Kalavasos', abac_name=N'Kalabasos', display_name=N'Καλαβασός-Kalavasos' WHERE id=3313;
UPDATE laus SET name_national=N'Τόχνη', name_latin=N'Tochni', abac_name=N'Tokhne', display_name=N'Τόχνη-Tochni' WHERE id=3314;
UPDATE laus SET name_national=N'Χοιροκoιτία', name_latin=N'Choirokoitia', abac_name=N'Khoirokoitia', display_name=N'Χοιροκoιτία-Choirokoitia' WHERE id=3315;
UPDATE laus SET name_national=N'Ψεματισμένος', name_latin=N'Psematismenos', abac_name=N'Psematismenos', display_name=N'Ψεματισμένος-Psematismenos' WHERE id=3316;
UPDATE laus SET name_national=N'Μαρώνι', name_latin=N'Maroni', abac_name=N'Maroni', display_name=N'Μαρώνι-Maroni' WHERE id=3317;
UPDATE laus SET name_national=N'Άγιος Θεόδωρος Λάρνακας', name_latin=N'Agios Theodoros Larnakas', abac_name=N'Agios Theodoros Larnakas', display_name=N'Άγιος Θεόδωρος Λάρνακας-Agios Theodoros Larnakas' WHERE id=3318;
UPDATE laus SET name_national=N'Σκαρίνου', name_latin=N'Skarinou', abac_name=N'Skarinou', display_name=N'Σκαρίνου-Skarinou' WHERE id=3319;
UPDATE laus SET name_national=N'Κοφίνου', name_latin=N'Kofinou', abac_name=N'Kophinou', display_name=N'Κοφίνου-Kofinou' WHERE id=3320;
UPDATE laus SET name_national=N'Κάτω Λεύκαρα', name_latin=N'Kato Lefkara', abac_name=N'Kato Leukara', display_name=N'Κάτω Λεύκαρα-Kato Lefkara' WHERE id=3321;
UPDATE laus SET name_national=N'Πάνω Λεύκαρα', name_latin=N'Pano Lefkara', abac_name=N'Pano Leukara', display_name=N'Πάνω Λεύκαρα-Pano Lefkara' WHERE id=3322;
UPDATE laus SET name_national=N'Κάτω Δρυς', name_latin=N'Kato Drys', abac_name=N'Kato Drus', display_name=N'Κάτω Δρυς-Kato Drys' WHERE id=3323;
UPDATE laus SET name_national=N'Βάβλα', name_latin=N'Vavla', abac_name=N'Babla', display_name=N'Βάβλα-Vavla' WHERE id=3324;
UPDATE laus SET name_national=N'Λάγεια', name_latin=N'Lageia', abac_name=N'Lageia', display_name=N'Λάγεια-Lageia' WHERE id=3325;
UPDATE laus SET name_national=N'Ορά', name_latin=N'Ora', abac_name=N'Ora', display_name=N'Ορά-Ora' WHERE id=3326;
UPDATE laus SET name_national=N'Μελίνη', name_latin=N'Melini', abac_name=N'Meline', display_name=N'Μελίνη-Melini' WHERE id=3327;
UPDATE laus SET name_national=N'Οδού', name_latin=N'Odou', abac_name=N'Odou', display_name=N'Οδού-Odou' WHERE id=3328;
UPDATE laus SET name_national=N'Άγιοι Βαβατσινιάς', name_latin=N'Agioi Vavatsinias', abac_name=N'Agioi Babatsinias', display_name=N'Άγιοι Βαβατσινιάς-Agioi Vavatsinias' WHERE id=3329;
UPDATE laus SET name_national=N'Βαβατσινιά', name_latin=N'Vavatsinia', abac_name=N'Babatsinia', display_name=N'Βαβατσινιά-Vavatsinia' WHERE id=3330;
UPDATE laus SET name_national=N'Λεμεσός', name_latin=N'Lemesos', abac_name=N'Lemesos', display_name=N'Λεμεσός-Lemesos' WHERE id=3331;
UPDATE laus SET name_national=N'Μέσα Γειτονιά', name_latin=N'Mesa Geitonia', abac_name=N'Mesa Geitonia', display_name=N'Μέσα Γειτονιά-Mesa Geitonia' WHERE id=3332;
UPDATE laus SET name_national=N'Άγιος Αθανάσιος', name_latin=N'Agios Athanasios', abac_name=N'Agios Athanasios', display_name=N'Άγιος Αθανάσιος-Agios Athanasios' WHERE id=3333;
UPDATE laus SET name_national=N'Γερμασόγεια', name_latin=N'Germasogeia', abac_name=N'Germasogeia', display_name=N'Γερμασόγεια-Germasogeia' WHERE id=3334;
UPDATE laus SET name_national=N'Πάνω Πολεμίδια', name_latin=N'Pano Polemidia', abac_name=N'Pano Polemidia', display_name=N'Πάνω Πολεμίδια-Pano Polemidia' WHERE id=3335;
UPDATE laus SET name_national=N'''Υψωνας', name_latin=N'Ypsonas', abac_name=N'''Upsonas', display_name=N'''Υψωνας-Ypsonas' WHERE id=3336;
UPDATE laus SET name_national=N'Κάτω Πολεμίδια', name_latin=N'Kato Polemidia', abac_name=N'Kato Polemidia', display_name=N'Κάτω Πολεμίδια-Kato Polemidia' WHERE id=3337;
UPDATE laus SET name_national=N'Παλόδεια', name_latin=N'Palodeia', abac_name=N'Palodeia', display_name=N'Παλόδεια-Palodeia' WHERE id=3338;
UPDATE laus SET name_national=N'Παραμύθα', name_latin=N'Paramytha', abac_name=N'Paramutha', display_name=N'Παραμύθα-Paramytha' WHERE id=3339;
UPDATE laus SET name_national=N'Σπιτάλι', name_latin=N'Spitali', abac_name=N'Spitali', display_name=N'Σπιτάλι-Spitali' WHERE id=3340;
UPDATE laus SET name_national=N'Φασούλα Λεμεσού', name_latin=N'Fasoula Lemesou', abac_name=N'Phasoula Lemesou', display_name=N'Φασούλα Λεμεσού-Fasoula Lemesou' WHERE id=3341;
UPDATE laus SET name_national=N'Μαθικολώνη', name_latin=N'Mathikoloni', abac_name=N'Mathikolone', display_name=N'Μαθικολώνη-Mathikoloni' WHERE id=3342;
UPDATE laus SET name_national=N'Γεράσα', name_latin=N'Gerasa', abac_name=N'Gerasa', display_name=N'Γεράσα-Gerasa' WHERE id=3343;
UPDATE laus SET name_national=N'Αψιού', name_latin=N'Apsiou', abac_name=N'Apsiou', display_name=N'Αψιού-Apsiou' WHERE id=3344;
UPDATE laus SET name_national=N'Απεσιά', name_latin=N'Apesia', abac_name=N'Apesia', display_name=N'Απεσιά-Apesia' WHERE id=3345;
UPDATE laus SET name_national=N'Κορφή', name_latin=N'Korfi', abac_name=N'Korphe', display_name=N'Κορφή-Korfi' WHERE id=3346;
UPDATE laus SET name_national=N'Λιμνάτης', name_latin=N'Limnatis', abac_name=N'Limnates', display_name=N'Λιμνάτης-Limnatis' WHERE id=3347;
UPDATE laus SET name_national=N'Καπηλειό', name_latin=N'Kapileio', abac_name=N'Kapeleio', display_name=N'Καπηλειό-Kapileio' WHERE id=3348;
UPDATE laus SET name_national=N'Μουτταγιάκα', name_latin=N'Mouttagiaka', abac_name=N'Mouttagiaka', display_name=N'Μουτταγιάκα-Mouttagiaka' WHERE id=3349;
UPDATE laus SET name_national=N'Αρμενοχώρι', name_latin=N'Armenochori', abac_name=N'Armenokhori', display_name=N'Αρμενοχώρι-Armenochori' WHERE id=3350;
UPDATE laus SET name_national=N'Φοινικάρια', name_latin=N'Foinikaria', abac_name=N'Phoinikaria', display_name=N'Φοινικάρια-Foinikaria' WHERE id=3351;
UPDATE laus SET name_national=N'Ακρούντα', name_latin=N'Akrounta', abac_name=N'Akrounta', display_name=N'Ακρούντα-Akrounta' WHERE id=3352;
UPDATE laus SET name_national=N'Άγιος Τύχων', name_latin=N'Agios Tychon', abac_name=N'Agios Tukhon', display_name=N'Άγιος Τύχων-Agios Tychon' WHERE id=3353;
UPDATE laus SET name_national=N'Παρεκκλησιά', name_latin=N'Parekklisia', abac_name=N'Parekklesia', display_name=N'Παρεκκλησιά-Parekklisia' WHERE id=3354;
UPDATE laus SET name_national=N'Πεντάκωμο', name_latin=N'Pentakomo', abac_name=N'Pentakomo', display_name=N'Πεντάκωμο-Pentakomo' WHERE id=3355;
UPDATE laus SET name_national=N'Μοναγρούλλι', name_latin=N'Monagroulli', abac_name=N'Monagroulli', display_name=N'Μοναγρούλλι-Monagroulli' WHERE id=3356;
UPDATE laus SET name_national=N'Μονή', name_latin=N'Moni', abac_name=N'Mone', display_name=N'Μονή-Moni' WHERE id=3357;
UPDATE laus SET name_national=N'Πύργος Λεμεσού', name_latin=N'Pyrgos Lemesou', abac_name=N'Purgos Lemesou', display_name=N'Πύργος Λεμεσού-Pyrgos Lemesou' WHERE id=3358;
UPDATE laus SET name_national=N'Ασγάτα', name_latin=N'Asgata', abac_name=N'Asgata', display_name=N'Ασγάτα-Asgata' WHERE id=3359;
UPDATE laus SET name_national=N'Βάσα Κελλακίου', name_latin=N'Vasa Kellakiou', abac_name=N'Basa Kellakiou', display_name=N'Βάσα Κελλακίου-Vasa Kellakiou' WHERE id=3360;
UPDATE laus SET name_national=N'Σανίδα', name_latin=N'Sanida', abac_name=N'Sanida', display_name=N'Σανίδα-Sanida' WHERE id=3361;
UPDATE laus SET name_national=N'Πραστιό Κελλακίου', name_latin=N'Prastio Kellakiou', abac_name=N'Prastio Kellakiou', display_name=N'Πραστιό Κελλακίου-Prastio Kellakiou' WHERE id=3362;
UPDATE laus SET name_national=N'Κλωνάρι', name_latin=N'Klonari', abac_name=N'Klonari', display_name=N'Κλωνάρι-Klonari' WHERE id=3363;
UPDATE laus SET name_national=N'Βίκλα', name_latin=N'Vikla', abac_name=N'Bikla', display_name=N'Βίκλα-Vikla' WHERE id=3364;
UPDATE laus SET name_national=N'Κελλάκι', name_latin=N'Kellaki', abac_name=N'Kellaki', display_name=N'Κελλάκι-Kellaki' WHERE id=3365;
UPDATE laus SET name_national=N'Ακαπνού', name_latin=N'Akapnou', abac_name=N'Akapnou', display_name=N'Ακαπνού-Akapnou' WHERE id=3366;
UPDATE laus SET name_national=N'Επταγώνεια', name_latin=N'Eptagoneia', abac_name=N'Eptagoneia', display_name=N'Επταγώνεια-Eptagoneia' WHERE id=3367;
UPDATE laus SET name_national=N'Διερώνα', name_latin=N'Dierona', abac_name=N'Dierona', display_name=N'Διερώνα-Dierona' WHERE id=3368;
UPDATE laus SET name_national=N'Αρακαπάς', name_latin=N'Arakapas', abac_name=N'Arakapas', display_name=N'Αρακαπάς-Arakapas' WHERE id=3369;
UPDATE laus SET name_national=N'Άγιος Παύλος', name_latin=N'Agios Pavlos', abac_name=N'Agios Paulos', display_name=N'Άγιος Παύλος-Agios Pavlos' WHERE id=3370;
UPDATE laus SET name_national=N'Άγιος Κωνσταντίνος', name_latin=N'Agios Konstantinos', abac_name=N'Agios Konstantinos', display_name=N'Άγιος Κωνσταντίνος-Agios Konstantinos' WHERE id=3371;
UPDATE laus SET name_national=N'Συκόπετρα', name_latin=N'Sykopetra', abac_name=N'Sukopetra', display_name=N'Συκόπετρα-Sykopetra' WHERE id=3372;
UPDATE laus SET name_national=N'Λουβαράς', name_latin=N'Louvaras', abac_name=N'Loubaras', display_name=N'Λουβαράς-Louvaras' WHERE id=3373;
UPDATE laus SET name_national=N'Καλό Χωριό Λεμεσού', name_latin=N'Kalo Chorio Lemesou', abac_name=N'Kalo Khorio Lemesou', display_name=N'Καλό Χωριό Λεμεσού-Kalo Chorio Lemesou' WHERE id=3374;
UPDATE laus SET name_national=N'Ζωοπηγή', name_latin=N'Zoopigi', abac_name=N'Zoopege', display_name=N'Ζωοπηγή-Zoopigi' WHERE id=3375;
UPDATE laus SET name_national=N'Ακρωτήρι', name_latin=N'Akrotiri', abac_name=N'Akroteri', display_name=N'Ακρωτήρι-Akrotiri' WHERE id=3376;
UPDATE laus SET name_national=N'Ασώματος Λεμεσού', name_latin=N'Asomatos Lemesou', abac_name=N'Asomatos Lemesou', display_name=N'Ασώματος Λεμεσού-Asomatos Lemesou' WHERE id=3377;
UPDATE laus SET name_national=N'Τσερκέζοι', name_latin=N'Tserkezoi', abac_name=N'Tserkezoi', display_name=N'Τσερκέζοι-Tserkezoi' WHERE id=3378;
UPDATE laus SET name_national=N'Τραχώνι Λεμεσού', name_latin=N'Trachoni Lemesou', abac_name=N'Trakhoni Lemesou', display_name=N'Τραχώνι Λεμεσού-Trachoni Lemesou' WHERE id=3379;
UPDATE laus SET name_national=N'Κολόσσι', name_latin=N'Kolossi', abac_name=N'Kolossi', display_name=N'Κολόσσι-Kolossi' WHERE id=3380;
UPDATE laus SET name_national=N'Ερήμη', name_latin=N'Erimi', abac_name=N'Ereme', display_name=N'Ερήμη-Erimi' WHERE id=3381;
UPDATE laus SET name_national=N'Επισκοπή Λεμεσού', name_latin=N'Episkopi Lemesou', abac_name=N'Episkope Lemesou', display_name=N'Επισκοπή Λεμεσού-Episkopi Lemesou' WHERE id=3382;
UPDATE laus SET name_national=N'Καντού', name_latin=N'Kantou', abac_name=N'Kantou', display_name=N'Καντού-Kantou' WHERE id=3383;
UPDATE laus SET name_national=N'Σωτήρα Λεμεσού', name_latin=N'Sotira Lemesou', abac_name=N'Sotera Lemesou', display_name=N'Σωτήρα Λεμεσού-Sotira Lemesou' WHERE id=3384;
UPDATE laus SET name_national=N'Πραστιό Αυδήμου', name_latin=N'Prastio Avdimou', abac_name=N'Prastio Audemou', display_name=N'Πραστιό Αυδήμου-Prastio Avdimou' WHERE id=3385;
UPDATE laus SET name_national=N'Παραμάλι', name_latin=N'Paramali', abac_name=N'Paramali', display_name=N'Παραμάλι-Paramali' WHERE id=3386;
UPDATE laus SET name_national=N'Αυδήμου', name_latin=N'Avdimou', abac_name=N'Audemou', display_name=N'Αυδήμου-Avdimou' WHERE id=3387;
UPDATE laus SET name_national=N'Πλατανίστεια', name_latin=N'Platanisteia', abac_name=N'Platanisteia', display_name=N'Πλατανίστεια-Platanisteia' WHERE id=3388;
UPDATE laus SET name_national=N'Άγιος Θωμάς', name_latin=N'Agios Thomas', abac_name=N'Agios Thomas', display_name=N'Άγιος Θωμάς-Agios Thomas' WHERE id=3389;
UPDATE laus SET name_national=N'Αλέκτορα', name_latin=N'Alektora', abac_name=N'Alektora', display_name=N'Αλέκτορα-Alektora' WHERE id=3390;
UPDATE laus SET name_national=N'Ανώγυρα', name_latin=N'Anogyra', abac_name=N'Anogura', display_name=N'Ανώγυρα-Anogyra' WHERE id=3391;
UPDATE laus SET name_national=N'Πισσούρι', name_latin=N'Pissouri', abac_name=N'Pissouri', display_name=N'Πισσούρι-Pissouri' WHERE id=3392;
UPDATE laus SET name_national=N'Σούνι-Ζανακιά', name_latin=N'Souni-Zanakia', abac_name=N'Souni-Zanakia', display_name=N'Σούνι-Ζανακιά-Souni-Zanakia' WHERE id=3393;
UPDATE laus SET name_national=N'Άλασσα', name_latin=N'Alassa', abac_name=N'Alassa', display_name=N'Άλασσα-Alassa' WHERE id=3394;
UPDATE laus SET name_national=N'Κάτω Κιβίδες', name_latin=N'Kato Kivides', abac_name=N'Kato Kibides', display_name=N'Κάτω Κιβίδες-Kato Kivides' WHERE id=3395;
UPDATE laus SET name_national=N'Πάνω Κιβίδες', name_latin=N'Pano Kivides', abac_name=N'Pano Kibides', display_name=N'Πάνω Κιβίδες-Pano Kivides' WHERE id=3396;
UPDATE laus SET name_national=N'Άγιος Αμβρόσιος Λεμεσού', name_latin=N'Agios Amvrosios Lemesou', abac_name=N'Agios Ambrosios Lemesou', display_name=N'Άγιος Αμβρόσιος Λεμεσού-Agios Amvrosios Lemesou' WHERE id=3397;
UPDATE laus SET name_national=N'Άγιος Θεράπων', name_latin=N'Agios Therapon', abac_name=N'Agios Therapon', display_name=N'Άγιος Θεράπων-Agios Therapon' WHERE id=3398;
UPDATE laus SET name_national=N'Λόφου', name_latin=N'Lofou', abac_name=N'Lophou', display_name=N'Λόφου-Lofou' WHERE id=3399;
UPDATE laus SET name_national=N'Πάχνα', name_latin=N'Pachna', abac_name=N'Pakhna', display_name=N'Πάχνα-Pachna' WHERE id=3400;
UPDATE laus SET name_national=N'Άγιος Γεώργιος Λεμεσού', name_latin=N'Agios Georgios Lemesou', abac_name=N'Agios Georgios Lemesou', display_name=N'Άγιος Γεώργιος Λεμεσού-Agios Georgios Lemesou' WHERE id=3401;
UPDATE laus SET name_national=N'Δωρός', name_latin=N'Doros', abac_name=N'Doros', display_name=N'Δωρός-Doros' WHERE id=3402;
UPDATE laus SET name_national=N'Λάνεια', name_latin=N'Laneia', abac_name=N'Laneia', display_name=N'Λάνεια-Laneia' WHERE id=3403;
UPDATE laus SET name_national=N'Σιλίκου', name_latin=N'Silikou', abac_name=N'Silikou', display_name=N'Σιλίκου-Silikou' WHERE id=3404;
UPDATE laus SET name_national=N'Μονάγρι', name_latin=N'Monagri', abac_name=N'Monagri', display_name=N'Μονάγρι-Monagri' WHERE id=3405;
UPDATE laus SET name_national=N'Τριμήκληνη', name_latin=N'Trimiklini', abac_name=N'Trimeklene', display_name=N'Τριμήκληνη-Trimiklini' WHERE id=3406;
UPDATE laus SET name_national=N'Άγιος Μάμας', name_latin=N'Agios Mamas', abac_name=N'Agios Mamas', display_name=N'Άγιος Μάμας-Agios Mamas' WHERE id=3407;
UPDATE laus SET name_national=N'Κουκά', name_latin=N'Kouka', abac_name=N'Kouka', display_name=N'Κουκά-Kouka' WHERE id=3408;
UPDATE laus SET name_national=N'Μονιάτης', name_latin=N'Moniatis', abac_name=N'Moniates', display_name=N'Μονιάτης-Moniatis' WHERE id=3409;
UPDATE laus SET name_national=N'Δωρά', name_latin=N'Dora', abac_name=N'Dora', display_name=N'Δωρά-Dora' WHERE id=3410;
UPDATE laus SET name_national=N'Γεροβάσα (Τρόζενα)', name_latin=N'Gerovasa (Trozena)', abac_name=N'Gerobasa (Trozena)', display_name=N'Γεροβάσα (Τρόζενα)-Gerovasa (Trozena)' WHERE id=3411;
UPDATE laus SET name_national=N'Άρσος Λεμεσού', name_latin=N'Arsos Lemesou', abac_name=N'Arsos Lemesou', display_name=N'Άρσος Λεμεσού-Arsos Lemesou' WHERE id=3412;
UPDATE laus SET name_national=N'Κισσούσα', name_latin=N'Kissousa', abac_name=N'Kissousa', display_name=N'Κισσούσα-Kissousa' WHERE id=3413;
UPDATE laus SET name_national=N'Μαλιά', name_latin=N'Malia', abac_name=N'Malia', display_name=N'Μαλιά-Malia' WHERE id=3414;
UPDATE laus SET name_national=N'Βάσα Κοιλανίου', name_latin=N'Vasa Koilaniou', abac_name=N'Basa Koilaniou', display_name=N'Βάσα Κοιλανίου-Vasa Koilaniou' WHERE id=3415;
UPDATE laus SET name_national=N'Βουνί', name_latin=N'Vouni', abac_name=N'Bouni', display_name=N'Βουνί-Vouni' WHERE id=3416;
UPDATE laus SET name_national=N'Πέρα Πεδί', name_latin=N'Pera Pedi', abac_name=N'Pera Pedi', display_name=N'Πέρα Πεδί-Pera Pedi' WHERE id=3417;
UPDATE laus SET name_national=N'Μανδριά Λεμεσού', name_latin=N'Mandria Lemesou', abac_name=N'Mandria Lemesou', display_name=N'Μανδριά Λεμεσού-Mandria Lemesou' WHERE id=3418;
UPDATE laus SET name_national=N'Ποταμιού', name_latin=N'Potamiou', abac_name=N'Potamiou', display_name=N'Ποταμιού-Potamiou' WHERE id=3419;
UPDATE laus SET name_national=N'Όμοδος', name_latin=N'Omodos', abac_name=N'Omodos', display_name=N'Όμοδος-Omodos' WHERE id=3420;
UPDATE laus SET name_national=N'Κοιλάνι', name_latin=N'Koilani', abac_name=N'Koilani', display_name=N'Κοιλάνι-Koilani' WHERE id=3421;
UPDATE laus SET name_national=N'Άγιος Δημήτριος', name_latin=N'Agios Dimitrios', abac_name=N'Agios Demetrios', display_name=N'Άγιος Δημήτριος-Agios Dimitrios' WHERE id=3422;
UPDATE laus SET name_national=N'Παλαιόμυλος', name_latin=N'Palaiomylos', abac_name=N'Palaiomulos', display_name=N'Παλαιόμυλος-Palaiomylos' WHERE id=3423;
UPDATE laus SET name_national=N'Πρόδρομος', name_latin=N'Prodromos', abac_name=N'Prodromos', display_name=N'Πρόδρομος-Prodromos' WHERE id=3424;
UPDATE laus SET name_national=N'Καμινάρια', name_latin=N'Kaminaria', abac_name=N'Kaminaria', display_name=N'Καμινάρια-Kaminaria' WHERE id=3425;
UPDATE laus SET name_national=N'Τρεις Ελιές', name_latin=N'Treis Elies', abac_name=N'Treis Elies', display_name=N'Τρεις Ελιές-Treis Elies' WHERE id=3426;
UPDATE laus SET name_national=N'Λεμίθου', name_latin=N'Lemithou', abac_name=N'Lemithou', display_name=N'Λεμίθου-Lemithou' WHERE id=3427;
UPDATE laus SET name_national=N'Κάτω Πλάτρες (Toρνάρηδες)', name_latin=N'Kato Platres (Tornarides)', abac_name=N'Kato Platres (Tornaredes)', display_name=N'Κάτω Πλάτρες (Toρνάρηδες)-Kato Platres (Tornarides)' WHERE id=3428;
UPDATE laus SET name_national=N'Πάνω Πλάτρες', name_latin=N'Pano Platres', abac_name=N'Pano Platres', display_name=N'Πάνω Πλάτρες-Pano Platres' WHERE id=3429;
UPDATE laus SET name_national=N'Φοινί', name_latin=N'Foini', abac_name=N'Phoini', display_name=N'Φοινί-Foini' WHERE id=3430;
UPDATE laus SET name_national=N'Αμίαντος', name_latin=N'Amiantos', abac_name=N'Amiantos', display_name=N'Αμίαντος-Amiantos' WHERE id=3431;
UPDATE laus SET name_national=N'Τρόοδος', name_latin=N'Troodos', abac_name=N'Troodos', display_name=N'Τρόοδος-Troodos' WHERE id=3432;
UPDATE laus SET name_national=N'Άγιος Θεόδωρος Λεμεσού', name_latin=N'Agios Theodoros Lemesou', abac_name=N'Agios Theodoros Lemesou', display_name=N'Άγιος Θεόδωρος Λεμεσού-Agios Theodoros Lemesou' WHERE id=3433;
UPDATE laus SET name_national=N'Άγιος Ιωάννης Λεμεσού', name_latin=N'Agios Ioannis Lemesou', abac_name=N'Agios Ioannes Lemesou', display_name=N'Άγιος Ιωάννης Λεμεσού-Agios Ioannis Lemesou' WHERE id=3434;
UPDATE laus SET name_national=N'Κάτω Μύλος', name_latin=N'Kato Mylos', abac_name=N'Kato Mulos', display_name=N'Κάτω Μύλος-Kato Mylos' WHERE id=3435;
UPDATE laus SET name_national=N'Ποταμίτισσα', name_latin=N'Potamitissa', abac_name=N'Potamitissa', display_name=N'Ποταμίτισσα-Potamitissa' WHERE id=3436;
UPDATE laus SET name_national=N'Δύμες', name_latin=N'Dymes', abac_name=N'Dumes', display_name=N'Δύμες-Dymes' WHERE id=3437;
UPDATE laus SET name_national=N'Πελένδρι', name_latin=N'Pelendri', abac_name=N'Pelendri', display_name=N'Πελένδρι-Pelendri' WHERE id=3438;
UPDATE laus SET name_national=N'Αγρός', name_latin=N'Agros', abac_name=N'Agros', display_name=N'Αγρός-Agros' WHERE id=3439;
UPDATE laus SET name_national=N'Αγρίδια', name_latin=N'Agridia', abac_name=N'Agridia', display_name=N'Αγρίδια-Agridia' WHERE id=3440;
UPDATE laus SET name_national=N'Χανδριά', name_latin=N'Chandria', abac_name=N'Khandria', display_name=N'Χανδριά-Chandria' WHERE id=3441;
UPDATE laus SET name_national=N'Κυπερούντα', name_latin=N'Kyperounta', abac_name=N'Kuperounta', display_name=N'Κυπερούντα-Kyperounta' WHERE id=3442;
UPDATE laus SET name_national=N'Πάφος', name_latin=N'Pafos', abac_name=N'Paphos', display_name=N'Πάφος-Pafos' WHERE id=3443;
UPDATE laus SET name_national=N'Γεροσκήπου', name_latin=N'Geroskipou', abac_name=N'Geroskepou', display_name=N'Γεροσκήπου-Geroskipou' WHERE id=3444;
UPDATE laus SET name_national=N'Κονιά', name_latin=N'Konia', abac_name=N'Konia', display_name=N'Κονιά-Konia' WHERE id=3445;
UPDATE laus SET name_national=N'Αγία Μαρινούδα', name_latin=N'Agia Marinouda', abac_name=N'Agia Marinouda', display_name=N'Αγία Μαρινούδα-Agia Marinouda' WHERE id=3446;
UPDATE laus SET name_national=N'Αχέλεια', name_latin=N'Acheleia', abac_name=N'Akheleia', display_name=N'Αχέλεια-Acheleia' WHERE id=3447;
UPDATE laus SET name_national=N'Χλώρακας', name_latin=N'Chlorakas', abac_name=N'Khlorakas', display_name=N'Χλώρακας-Chlorakas' WHERE id=3448;
UPDATE laus SET name_national=N'Λέμπα', name_latin=N'Lempa', abac_name=N'Lempa', display_name=N'Λέμπα-Lempa' WHERE id=3449;
UPDATE laus SET name_national=N'Έμπα', name_latin=N'Empa', abac_name=N'Empa', display_name=N'Έμπα-Empa' WHERE id=3450;
UPDATE laus SET name_national=N'Τρεμιθούσα', name_latin=N'Tremithousa', abac_name=N'Tremithousa', display_name=N'Τρεμιθούσα-Tremithousa' WHERE id=3451;
UPDATE laus SET name_national=N'Μέσα Χωριό', name_latin=N'Mesa Chorio', abac_name=N'Mesa Khorio', display_name=N'Μέσα Χωριό-Mesa Chorio' WHERE id=3452;
UPDATE laus SET name_national=N'Μεσόγη', name_latin=N'Mesogi', abac_name=N'Mesoge', display_name=N'Μεσόγη-Mesogi' WHERE id=3453;
UPDATE laus SET name_national=N'Τάλα', name_latin=N'Tala', abac_name=N'Tala', display_name=N'Τάλα-Tala' WHERE id=3454;
UPDATE laus SET name_national=N'Κισσόνεργα', name_latin=N'Kissonerga', abac_name=N'Kissonerga', display_name=N'Κισσόνεργα-Kissonerga' WHERE id=3455;
UPDATE laus SET name_national=N'Κούκλια Πάφου', name_latin=N'Kouklia Pafou', abac_name=N'Kouklia Paphou', display_name=N'Κούκλια Πάφου-Kouklia Pafou' WHERE id=3456;
UPDATE laus SET name_national=N'Μανδριά Πάφου', name_latin=N'Mandria Pafou', abac_name=N'Mandria Paphou', display_name=N'Μανδριά Πάφου-Mandria Pafou' WHERE id=3457;
UPDATE laus SET name_national=N'Νικόκλεια', name_latin=N'Nikokleia', abac_name=N'Nikokleia', display_name=N'Νικόκλεια-Nikokleia' WHERE id=3458;
UPDATE laus SET name_national=N'Σουσκιού', name_latin=N'Souskiou', abac_name=N'Souskiou', display_name=N'Σουσκιού-Souskiou' WHERE id=3459;
UPDATE laus SET name_national=N'Τίμη', name_latin=N'Timi', abac_name=N'Time', display_name=N'Τίμη-Timi' WHERE id=3460;
UPDATE laus SET name_national=N'Αγία Βαρβάρα Πάφου', name_latin=N'Agia Varvara Pafou', abac_name=N'Agia Barbara Paphou', display_name=N'Αγία Βαρβάρα Πάφου-Agia Varvara Pafou' WHERE id=3461;
UPDATE laus SET name_national=N'Αναρίτα', name_latin=N'Anarita', abac_name=N'Anarita', display_name=N'Αναρίτα-Anarita' WHERE id=3462;
UPDATE laus SET name_national=N'Φοίνικας', name_latin=N'Foinikas', abac_name=N'Phoinikas', display_name=N'Φοίνικας-Foinikas' WHERE id=3463;
UPDATE laus SET name_national=N'Μαραθούντα', name_latin=N'Marathounta', abac_name=N'Marathounta', display_name=N'Μαραθούντα-Marathounta' WHERE id=3464;
UPDATE laus SET name_national=N'Άρμου', name_latin=N'Armou', abac_name=N'Armou', display_name=N'Άρμου-Armou' WHERE id=3465;
UPDATE laus SET name_national=N'Επισκοπή Πάφου', name_latin=N'Episkopi Pafou', abac_name=N'Episkope Paphou', display_name=N'Επισκοπή Πάφου-Episkopi Pafou' WHERE id=3466;
UPDATE laus SET name_national=N'Νατά', name_latin=N'Nata', abac_name=N'Nata', display_name=N'Νατά-Nata' WHERE id=3467;
UPDATE laus SET name_national=N'Χολέτρια', name_latin=N'Choletria', abac_name=N'Kholetria', display_name=N'Χολέτρια-Choletria' WHERE id=3468;
UPDATE laus SET name_national=N'Αξύλου', name_latin=N'Axylou', abac_name=N'Axulou', display_name=N'Αξύλου-Axylou' WHERE id=3469;
UPDATE laus SET name_national=N'Ελεδιό', name_latin=N'Eledio', abac_name=N'Eledio', display_name=N'Ελεδιό-Eledio' WHERE id=3470;
UPDATE laus SET name_national=N'Τσάδα', name_latin=N'Tsada', abac_name=N'Tsada', display_name=N'Τσάδα-Tsada' WHERE id=3471;
UPDATE laus SET name_national=N'Κοίλη', name_latin=N'Koili', abac_name=N'Koile', display_name=N'Κοίλη-Koili' WHERE id=3472;
UPDATE laus SET name_national=N'Στρουμπί', name_latin=N'Stroumpi', abac_name=N'Stroumpi', display_name=N'Στρουμπί-Stroumpi' WHERE id=3473;
UPDATE laus SET name_national=N'Πολέμι', name_latin=N'Polemi', abac_name=N'Polemi', display_name=N'Πολέμι-Polemi' WHERE id=3474;
UPDATE laus SET name_national=N'Καλλέπεια', name_latin=N'Kallepeia', abac_name=N'Kallepeia', display_name=N'Καλλέπεια-Kallepeia' WHERE id=3475;
UPDATE laus SET name_national=N'Λετύμβου', name_latin=N'Letymvou', abac_name=N'Letumbou', display_name=N'Λετύμβου-Letymvou' WHERE id=3476;
UPDATE laus SET name_national=N'Πιταργού', name_latin=N'Pitargou', abac_name=N'Pitargou', display_name=N'Πιταργού-Pitargou' WHERE id=3477;
UPDATE laus SET name_national=N'Κούρδακα', name_latin=N'Kourdaka', abac_name=N'Kourdaka', display_name=N'Κούρδακα-Kourdaka' WHERE id=3478;
UPDATE laus SET name_national=N'Λεμώνα', name_latin=N'Lemona', abac_name=N'Lemona', display_name=N'Λεμώνα-Lemona' WHERE id=3479;
UPDATE laus SET name_national=N'Χούλου', name_latin=N'Choulou', abac_name=N'Khoulou', display_name=N'Χούλου-Choulou' WHERE id=3480;
UPDATE laus SET name_national=N'Ακουρσός', name_latin=N'Akoursos', abac_name=N'Akoursos', display_name=N'Ακουρσός-Akoursos' WHERE id=3481;
UPDATE laus SET name_national=N'Κάθικας', name_latin=N'Kathikas', abac_name=N'Kathikas', display_name=N'Κάθικας-Kathikas' WHERE id=3482;
UPDATE laus SET name_national=N'Πέγεια', name_latin=N'Pegeia', abac_name=N'Pegeia', display_name=N'Πέγεια-Pegeia' WHERE id=3483;
UPDATE laus SET name_national=N'Πάνω Aρχιμανδρίτα', name_latin=N'Pano Archimandrita', abac_name=N'Pano Arkhimandrita', display_name=N'Πάνω Aρχιμανδρίτα-Pano Archimandrita' WHERE id=3484;
UPDATE laus SET name_national=N'Φασούλα Πάφου', name_latin=N'Fasoula Pafou', abac_name=N'Phasoula Paphou', display_name=N'Φασούλα Πάφου-Fasoula Pafou' WHERE id=3485;
UPDATE laus SET name_national=N'Μούσερε', name_latin=N'Mousere', abac_name=N'Mousere', display_name=N'Μούσερε-Mousere' WHERE id=3486;
UPDATE laus SET name_national=N'Μάρωνας', name_latin=N'Maronas', abac_name=N'Maronas', display_name=N'Μάρωνας-Maronas' WHERE id=3487;
UPDATE laus SET name_national=N'Μαμώνια', name_latin=N'Mamonia', abac_name=N'Mamonia', display_name=N'Μαμώνια-Mamonia' WHERE id=3488;
UPDATE laus SET name_national=N'Άγιος Γεώργιος Πάφου', name_latin=N'Agios Georgios Pafou', abac_name=N'Agios Georgios Paphou', display_name=N'Άγιος Γεώργιος Πάφου-Agios Georgios Pafou' WHERE id=3489;
UPDATE laus SET name_national=N'Σταυροκόννου', name_latin=N'Stavrokonnou', abac_name=N'Staurokonnou', display_name=N'Σταυροκόννου-Stavrokonnou' WHERE id=3490;
UPDATE laus SET name_national=N'Πραστιό Πάφου', name_latin=N'Prastio Pafou', abac_name=N'Prastio Paphou', display_name=N'Πραστιό Πάφου-Prastio Pafou' WHERE id=3491;
UPDATE laus SET name_national=N'Τραχυπέδουλα', name_latin=N'Trachypedoula', abac_name=N'Trakhupedoula', display_name=N'Τραχυπέδουλα-Trachypedoula' WHERE id=3492;
UPDATE laus SET name_national=N'Κελοκέδαρα', name_latin=N'Kelokedara', abac_name=N'Kelokedara', display_name=N'Κελοκέδαρα-Kelokedara' WHERE id=3493;
UPDATE laus SET name_national=N'Σαλαμιού', name_latin=N'Salamiou', abac_name=N'Salamiou', display_name=N'Σαλαμιού-Salamiou' WHERE id=3494;
UPDATE laus SET name_national=N'Κιδάσι', name_latin=N'Kidasi', abac_name=N'Kidasi', display_name=N'Κιδάσι-Kidasi' WHERE id=3495;
UPDATE laus SET name_national=N'Κέδαρες', name_latin=N'Kedares', abac_name=N'Kedares', display_name=N'Κέδαρες-Kedares' WHERE id=3496;
UPDATE laus SET name_national=N'Μέσανα', name_latin=N'Mesana', abac_name=N'Mesana', display_name=N'Μέσανα-Mesana' WHERE id=3497;
UPDATE laus SET name_national=N'Πραιτώρι', name_latin=N'Praitori', abac_name=N'Praitori', display_name=N'Πραιτώρι-Praitori' WHERE id=3498;
UPDATE laus SET name_national=N'Φιλούσα Κελοκεδάρων', name_latin=N'Filousa Kelokedaron', abac_name=N'Philousa Kelokedaron', display_name=N'Φιλούσα Κελοκεδάρων-Filousa Kelokedaron' WHERE id=3499;
UPDATE laus SET name_national=N'Αρμίνου', name_latin=N'Arminou', abac_name=N'Arminou', display_name=N'Αρμίνου-Arminou' WHERE id=3500;
UPDATE laus SET name_national=N'Άγιος Νικόλαος Πάφου', name_latin=N'Agios Nikolaos Pafou', abac_name=N'Agios Nikolaos Paphou', display_name=N'Άγιος Νικόλαος Πάφου-Agios Nikolaos Pafou' WHERE id=3501;
UPDATE laus SET name_national=N'Άγιος Ιωάννης Πάφου', name_latin=N'Agios Ioannis Pafou', abac_name=N'Agios Ioannes Paphou', display_name=N'Άγιος Ιωάννης Πάφου-Agios Ioannis Pafou' WHERE id=3502;
UPDATE laus SET name_national=N'Αμαργέτη', name_latin=N'Amargeti', abac_name=N'Amargete', display_name=N'Αμαργέτη-Amargeti' WHERE id=3503;
UPDATE laus SET name_national=N'Αγία Μαρίνα Κελοκεδάρων', name_latin=N'Agia Marina Kelokedaron', abac_name=N'Agia Marina Kelokedaron', display_name=N'Αγία Μαρίνα Κελοκεδάρων-Agia Marina Kelokedaron' WHERE id=3504;
UPDATE laus SET name_national=N'Πενταλιά', name_latin=N'Pentalia', abac_name=N'Pentalia', display_name=N'Πενταλιά-Pentalia' WHERE id=3505;
UPDATE laus SET name_national=N'Φάλεια', name_latin=N'Faleia', abac_name=N'Phaleia', display_name=N'Φάλεια-Faleia' WHERE id=3506;
UPDATE laus SET name_national=N'Γαλαταριά', name_latin=N'Galataria', abac_name=N'Galataria', display_name=N'Γαλαταριά-Galataria' WHERE id=3507;
UPDATE laus SET name_national=N'Κοιλίνεια', name_latin=N'Koilineia', abac_name=N'Koilineia', display_name=N'Κοιλίνεια-Koilineia' WHERE id=3508;
UPDATE laus SET name_national=N'Βρέτσια', name_latin=N'Vretsia', abac_name=N'Bretsia', display_name=N'Βρέτσια-Vretsia' WHERE id=3509;
UPDATE laus SET name_national=N'Στατός-Άγιος Φώτιος', name_latin=N'Statos-Agios Fotios', abac_name=N'Statos-Agios Photios', display_name=N'Στατός-Άγιος Φώτιος-Statos-Agios Fotios' WHERE id=3510;
UPDATE laus SET name_national=N'Λαπηθιού', name_latin=N'Lapithiou', abac_name=N'Lapethiou', display_name=N'Λαπηθιού-Lapithiou' WHERE id=3511;
UPDATE laus SET name_national=N'Μαμούνταλη', name_latin=N'Mamountali', abac_name=N'Mamountale', display_name=N'Μαμούνταλη-Mamountali' WHERE id=3512;
UPDATE laus SET name_national=N'Πάνω Παναγιά', name_latin=N'Pano Panagia', abac_name=N'Pano Panagia', display_name=N'Πάνω Παναγιά-Pano Panagia' WHERE id=3513;
UPDATE laus SET name_national=N'Ασπρογιά', name_latin=N'Asprogia', abac_name=N'Asprogia', display_name=N'Ασπρογιά-Asprogia' WHERE id=3514;
UPDATE laus SET name_national=N'Ψάθι', name_latin=N'Psathi', abac_name=N'Psathi', display_name=N'Ψάθι-Psathi' WHERE id=3515;
UPDATE laus SET name_national=N'Άγιος Δημητριανός', name_latin=N'Agios Dimitrianos', abac_name=N'Agios Demetrianos', display_name=N'Άγιος Δημητριανός-Agios Dimitrianos' WHERE id=3516;
UPDATE laus SET name_national=N'Κανναβιού', name_latin=N'Kannaviou', abac_name=N'Kannabiou', display_name=N'Κανναβιού-Kannaviou' WHERE id=3517;
UPDATE laus SET name_national=N'Θρινιά', name_latin=N'Thrinia', abac_name=N'Thrinia', display_name=N'Θρινιά-Thrinia' WHERE id=3518;
UPDATE laus SET name_national=N'Μηλιά Πάφου', name_latin=N'Milia Pafou', abac_name=N'Melia Paphou', display_name=N'Μηλιά Πάφου-Milia Pafou' WHERE id=3519;
UPDATE laus SET name_national=N'Κρίτου Μαρόττου', name_latin=N'Kritou Marottou', abac_name=N'Kritou Marottou', display_name=N'Κρίτου Μαρόττου-Kritou Marottou' WHERE id=3520;
UPDATE laus SET name_national=N'Φύτη', name_latin=N'Fyti', abac_name=N'Phute', display_name=N'Φύτη-Fyti' WHERE id=3521;
UPDATE laus SET name_national=N'Λάσα', name_latin=N'Lasa', abac_name=N'Lasa', display_name=N'Λάσα-Lasa' WHERE id=3522;
UPDATE laus SET name_national=N'Δρύμου', name_latin=N'Drymou', abac_name=N'Drumou', display_name=N'Δρύμου-Drymou' WHERE id=3523;
UPDATE laus SET name_national=N'Σίμου', name_latin=N'Simou', abac_name=N'Simou', display_name=N'Σίμου-Simou' WHERE id=3524;
UPDATE laus SET name_national=N'Αναδιού', name_latin=N'Anadiou', abac_name=N'Anadiou', display_name=N'Αναδιού-Anadiou' WHERE id=3525;
UPDATE laus SET name_national=N'Σαραμά', name_latin=N'Sarama', abac_name=N'Sarama', display_name=N'Σαραμά-Sarama' WHERE id=3526;
UPDATE laus SET name_national=N'Ευρέτου', name_latin=N'Evretou', abac_name=N'Euretou', display_name=N'Ευρέτου-Evretou' WHERE id=3527;
UPDATE laus SET name_national=N'Τριμιθούσα', name_latin=N'Trimithousa', abac_name=N'Trimithousa', display_name=N'Τριμιθούσα-Trimithousa' WHERE id=3528;
UPDATE laus SET name_national=N'Φιλούσα Χρυσοχούς', name_latin=N'Filousa Chrysochous', abac_name=N'Philousa Khrusokhous', display_name=N'Φιλούσα Χρυσοχούς-Filousa Chrysochous' WHERE id=3529;
UPDATE laus SET name_national=N'Κιός', name_latin=N'Kios', abac_name=N'Kios', display_name=N'Κιός-Kios' WHERE id=3530;
UPDATE laus SET name_national=N'Ζαχαριά', name_latin=N'Zacharia', abac_name=N'Zakharia', display_name=N'Ζαχαριά-Zacharia' WHERE id=3531;
UPDATE laus SET name_national=N'Μελάδεια', name_latin=N'Meladeia', abac_name=N'Meladeia', display_name=N'Μελάδεια-Meladeia' WHERE id=3532;
UPDATE laus SET name_national=N'Μελάνδρα', name_latin=N'Melandra', abac_name=N'Melandra', display_name=N'Μελάνδρα-Melandra' WHERE id=3533;
UPDATE laus SET name_national=N'Λυσός', name_latin=N'Lysos', abac_name=N'Lusos', display_name=N'Λυσός-Lysos' WHERE id=3534;
UPDATE laus SET name_national=N'Περιστερώνα Πάφου', name_latin=N'Peristerona Pafou', abac_name=N'Peristerona Paphou', display_name=N'Περιστερώνα Πάφου-Peristerona Pafou' WHERE id=3535;
UPDATE laus SET name_national=N'Θελέτρα', name_latin=N'Theletra', abac_name=N'Theletra', display_name=N'Θελέτρα-Theletra' WHERE id=3536;
UPDATE laus SET name_national=N'Γιόλου', name_latin=N'Giolou', abac_name=N'Giolou', display_name=N'Γιόλου-Giolou' WHERE id=3537;
UPDATE laus SET name_national=N'Πάνω Ακουρδάλεια', name_latin=N'Pano Akourdaleia', abac_name=N'Pano Akourdaleia', display_name=N'Πάνω Ακουρδάλεια-Pano Akourdaleia' WHERE id=3538;
UPDATE laus SET name_national=N'Μηλιού', name_latin=N'Miliou', abac_name=N'Meliou', display_name=N'Μηλιού-Miliou' WHERE id=3539;
UPDATE laus SET name_national=N'Κάτω Ακουρδάλεια', name_latin=N'Kato Akourdaleia', abac_name=N'Kato Akourdaleia', display_name=N'Κάτω Ακουρδάλεια-Kato Akourdaleia' WHERE id=3540;
UPDATE laus SET name_national=N'Τέρα', name_latin=N'Tera', abac_name=N'Tera', display_name=N'Τέρα-Tera' WHERE id=3541;
UPDATE laus SET name_national=N'Κρίτου Τέρα', name_latin=N'Kritou Tera', abac_name=N'Kritou Tera', display_name=N'Κρίτου Τέρα-Kritou Tera' WHERE id=3542;
UPDATE laus SET name_national=N'Σκούλλη', name_latin=N'Skoulli', abac_name=N'Skoulle', display_name=N'Σκούλλη-Skoulli' WHERE id=3543;
UPDATE laus SET name_national=N'Χόλη', name_latin=N'Choli', abac_name=N'Khole', display_name=N'Χόλη-Choli' WHERE id=3544;
UPDATE laus SET name_national=N'Λουκρούνου', name_latin=N'Loukrounou', abac_name=N'Loukrounou', display_name=N'Λουκρούνου-Loukrounou' WHERE id=3545;
UPDATE laus SET name_national=N'Καραμούλληδες', name_latin=N'Karamoullides', abac_name=N'Karamoulledes', display_name=N'Καραμούλληδες-Karamoullides' WHERE id=3546;
UPDATE laus SET name_national=N'Χρυσοχού', name_latin=N'Chrysochou', abac_name=N'Khrusokhou', display_name=N'Χρυσοχού-Chrysochou' WHERE id=3547;
UPDATE laus SET name_national=N'Πόλις', name_latin=N'Polis', abac_name=N'Polis', display_name=N'Πόλις-Polis' WHERE id=3548;
UPDATE laus SET name_national=N'Νέο Χωριό Πάφου', name_latin=N'Neo Chorio Pafou', abac_name=N'Neo Khorio Paphou', display_name=N'Νέο Χωριό Πάφου-Neo Chorio Pafou' WHERE id=3549;
UPDATE laus SET name_national=N'Γουδί', name_latin=N'Goudi', abac_name=N'Goudi', display_name=N'Γουδί-Goudi' WHERE id=3550;
UPDATE laus SET name_national=N'Κάτω Αρόδες', name_latin=N'Kato Arodes', abac_name=N'Kato Arodes', display_name=N'Κάτω Αρόδες-Kato Arodes' WHERE id=3551;
UPDATE laus SET name_national=N'Πάνω Αρόδες', name_latin=N'Pano Arodes', abac_name=N'Pano Arodes', display_name=N'Πάνω Αρόδες-Pano Arodes' WHERE id=3552;
UPDATE laus SET name_national=N'''Ινεια', name_latin=N'Ineia', abac_name=N'''Ineia', display_name=N'''Ινεια-Ineia' WHERE id=3553;
UPDATE laus SET name_national=N'Δρούσεια', name_latin=N'Drouseia', abac_name=N'Drouseia', display_name=N'Δρούσεια-Drouseia' WHERE id=3554;
UPDATE laus SET name_national=N'Φάσλι', name_latin=N'Fasli', abac_name=N'Phasli', display_name=N'Φάσλι-Fasli' WHERE id=3555;
UPDATE laus SET name_national=N'Ανδρολίκου', name_latin=N'Androlikou', abac_name=N'Androlikou', display_name=N'Ανδρολίκου-Androlikou' WHERE id=3556;
UPDATE laus SET name_national=N'Πελαθούσα', name_latin=N'Pelathousa', abac_name=N'Pelathousa', display_name=N'Πελαθούσα-Pelathousa' WHERE id=3557;
UPDATE laus SET name_national=N'Κυνούσα', name_latin=N'Kynousa', abac_name=N'Kunousa', display_name=N'Κυνούσα-Kynousa' WHERE id=3558;
UPDATE laus SET name_national=N'Μακούντα', name_latin=N'Makounta', abac_name=N'Makounta', display_name=N'Μακούντα-Makounta' WHERE id=3559;
UPDATE laus SET name_national=N'Αργάκα', name_latin=N'Argaka', abac_name=N'Argaka', display_name=N'Αργάκα-Argaka' WHERE id=3560;
UPDATE laus SET name_national=N'Γιαλιά', name_latin=N'Gialia', abac_name=N'Gialia', display_name=N'Γιαλιά-Gialia' WHERE id=3561;
UPDATE laus SET name_national=N'Αγία Μαρίνα Χρυσοχούς', name_latin=N'Agia Marina Chrysochous', abac_name=N'Agia Marina Khrusokhous', display_name=N'Αγία Μαρίνα Χρυσοχούς-Agia Marina Chrysochous' WHERE id=3562;
UPDATE laus SET name_national=N'Νέα Δήμματα', name_latin=N'Nea Dimmata', abac_name=N'Nea Demmata', display_name=N'Νέα Δήμματα-Nea Dimmata' WHERE id=3563;
UPDATE laus SET name_national=N'Πομός', name_latin=N'Pomos', abac_name=N'Pomos', display_name=N'Πομός-Pomos' WHERE id=3564;
UPDATE laus SET name_national=N'Στενή', name_latin=N'Steni', abac_name=N'Stene', display_name=N'Στενή-Steni' WHERE id=3565;
UPDATE laus SET name_national=N'Άγιος Ισίδωρος', name_latin=N'Agios Isidoros', abac_name=N'Agios Isidoros', display_name=N'Άγιος Ισίδωρος-Agios Isidoros' WHERE id=3566;
UPDATE laus SET name_national=N'Λιβάδι', name_latin=N'Livadi', abac_name=N'Libadi', display_name=N'Λιβάδι-Livadi' WHERE id=3567;

--615
--select nuts3, lau1, name_national, name_latin, abac_name, display_name, id 
--from laus where country_code = 'CY' order by name1 asc
