-- MT
--SQL (names)
UPDATE laus SET name_national=N'Birgu', name_latin=N'Citta'' Vittoriosa', abac_name=N'Birgu', display_name=N'Birgu' WHERE id=77464;
UPDATE laus SET name_national=N'Birkirkara', name_latin=N'Birkirkara', abac_name=N'Birkirkara', display_name=N'Birkirkara' WHERE id=77478;
UPDATE laus SET name_national=N'Birżebbuġa', name_latin=N'Birżebbuġa', abac_name=N'Birzebbuga', display_name=N'Birżebbuġa' WHERE id=77491;
UPDATE laus SET name_national=N'Bormla', name_latin=N'Citta'' Cospicua', abac_name=N'Bormla', display_name=N'Bormla' WHERE id=77466;
UPDATE laus SET name_national=N'Għajnsielem and Comino', name_latin=N'Għajnsielem and Comino', abac_name=N'Ghajnsielem and Comino', display_name=N'Għajnsielem and Comino' WHERE id=77519;
UPDATE laus SET name_national=N'Ħad-Dingli', name_latin=N'Dingli', abac_name=N'Had-Dingli', display_name=N'Ħad-Dingli' WHERE id=77506;
UPDATE laus SET name_national=N'Ħal Balzan', name_latin=N'Balzan', abac_name=N'Hal Balzan', display_name=N'Ħal Balzan' WHERE id=77505;
UPDATE laus SET name_national=N'Ħal Għargħur', name_latin=N'Għargħur', abac_name=N'Hal Gharghur', display_name=N'Ħal Għargħur' WHERE id=77511;
UPDATE laus SET name_national=N'Ħal Għaxaq', name_latin=N'Għaxaq', abac_name=N'Hal Ghaxaq', display_name=N'Ħal Għaxaq' WHERE id=77493;
UPDATE laus SET name_national=N'Ħal Kirkop', name_latin=N'Kirkop', abac_name=N'Hal Kirkop', display_name=N'Ħal Kirkop' WHERE id=77494;
UPDATE laus SET name_national=N'Ħal Lija', name_latin=N'Lija', abac_name=N'Hal Lija', display_name=N'Ħal Lija' WHERE id=77508;
UPDATE laus SET name_national=N'Ħal Luqa', name_latin=N'Luqa', abac_name=N'Hal Luqa', display_name=N'Ħal Luqa' WHERE id=77471;
UPDATE laus SET name_national=N'Ħal Qormi', name_latin=N'Citta'' Pinto', abac_name=N'Hal Qormi', display_name=N'Ħal Qormi' WHERE id=77477;
UPDATE laus SET name_national=N'Ħal Safi', name_latin=N'Safi', abac_name=N'Hal Safi', display_name=N'Ħal Safi' WHERE id=77499;
UPDATE laus SET name_national=N'Ħal Tarxien', name_latin=N'Tarxien', abac_name=N'Hal Tarxien', display_name=N'Ħal Tarxien' WHERE id=77475;
UPDATE laus SET name_national=N'Ħ''Attard', name_latin=N'Attard', abac_name=N'H''Attard', display_name=N'Ħ''Attard' WHERE id=77504;
UPDATE laus SET name_national=N'Ħaż-Żabbar', name_latin=N'Citta'' Hompesch', abac_name=N'Haz-Zabbar', display_name=N'Ħaż-Żabbar' WHERE id=77467;
UPDATE laus SET name_national=N'Ħaż-Żebbuġ', name_latin=N'Citta'' Rohan', abac_name=N'Haz-Zebbug', display_name=N'Ħaż-Żebbuġ' WHERE id=77502;
UPDATE laus SET name_national=N'Il-Fgura', name_latin=N'Fgura', abac_name=N'Il-Fgura', display_name=N'Il-Fgura' WHERE id=77468;
UPDATE laus SET name_national=N'Il-Fontana', name_latin=N'Fontana', abac_name=N'Il-Fontana', display_name=N'Il-Fontana' WHERE id=77518;
UPDATE laus SET name_national=N'Il-Furjana', name_latin=N'Floriana', abac_name=N'Il-Furjana', display_name=N'Il-Furjana' WHERE id=77469;
UPDATE laus SET name_national=N'Il-Gudja', name_latin=N'Gudja', abac_name=N'Il-Gudja', display_name=N'Il-Gudja' WHERE id=77492;
UPDATE laus SET name_national=N'Il-Gżira', name_latin=N'Gżira', abac_name=N'Il-Gzira', display_name=N'Il-Gżira' WHERE id=77479;
UPDATE laus SET name_national=N'Il-Ħamrun', name_latin=N'Ħamrun', abac_name=N'Il-Hamrun', display_name=N'Il-Ħamrun' WHERE id=77480;
UPDATE laus SET name_national=N'Il-Kalkara', name_latin=N'Kalkara', abac_name=N'Il-Kalkara', display_name=N'Il-Kalkara' WHERE id=77470;
UPDATE laus SET name_national=N'Il-Marsa', name_latin=N'Marsa', abac_name=N'Il-Marsa', display_name=N'Il-Marsa' WHERE id=77472;
UPDATE laus SET name_national=N'Il-Mellieħa', name_latin=N'Mellieħa', abac_name=N'Il-Mellieha', display_name=N'Il-Mellieħa' WHERE id=77512;
UPDATE laus SET name_national=N'Il-Mosta', name_latin=N'Mosta', abac_name=N'Il-Mosta', display_name=N'Il-Mosta' WHERE id=77514;
UPDATE laus SET name_national=N'Il-Munxar', name_latin=N'Munxar', abac_name=N'Il-Munxar', display_name=N'Il-Munxar' WHERE id=77523;
UPDATE laus SET name_national=N'Il-Qala', name_latin=N'Qala', abac_name=N'Il-Qala', display_name=N'Il-Qala' WHERE id=77525;
UPDATE laus SET name_national=N'Il-Qrendi', name_latin=N'Qrendi', abac_name=N'Il-Qrendi', display_name=N'Il-Qrendi' WHERE id=77498;
UPDATE laus SET name_national=N'In-Nadur', name_latin=N'Nadur', abac_name=N'In-Nadur', display_name=N'In-Nadur' WHERE id=77524;
UPDATE laus SET name_national=N'In-Naxxar', name_latin=N'Naxxar', abac_name=N'In-Naxxar', display_name=N'In-Naxxar' WHERE id=77515;
UPDATE laus SET name_national=N'Ir-Rabat', name_latin=N'Rabat (Malta)', abac_name=N'Ir-Rabat', display_name=N'Ir-Rabat' WHERE id=77509;
UPDATE laus SET name_national=N'Ir-Rabat, Għawdex', name_latin=N'Citta'' Victoria', abac_name=N'Ir-Rabat, Ghawdex', display_name=N'Ir-Rabat, Għawdex' WHERE id=77517;
UPDATE laus SET name_national=N'Is-Siġġiewi', name_latin=N'Citta'' Ferdinand', abac_name=N'Is-Siggiewi', display_name=N'Is-Siġġiewi' WHERE id=77503;
UPDATE laus SET name_national=N'Is-Swieqi', name_latin=N'Swieqi', abac_name=N'Is-Swieqi', display_name=N'Is-Swieqi' WHERE id=77488;
UPDATE laus SET name_national=N'Ix-Xagħra', name_latin=N'Xagħra', abac_name=N'Ix-Xaghra', display_name=N'Ix-Xagħra' WHERE id=77528;
UPDATE laus SET name_national=N'Ix-Xewkija', name_latin=N'Xewkija', abac_name=N'Ix-Xewkija', display_name=N'Ix-Xewkija' WHERE id=77529;
UPDATE laus SET name_national=N'Ix-Xgħajra', name_latin=N'Xgħajra', abac_name=N'Ix-Xghajra', display_name=N'Ix-Xgħajra' WHERE id=77476;
UPDATE laus SET name_national=N'Iż-Żebbuġ', name_latin=N'Żebbuġ (Gozo)', abac_name=N'Iz-Zebbug', display_name=N'Iż-Żebbuġ' WHERE id=77530;
UPDATE laus SET name_national=N'Iż-Żejtun', name_latin=N'Citta'' Beland', abac_name=N'Iz-Zejtun', display_name=N'Iż-Żejtun' WHERE id=77490;
UPDATE laus SET name_national=N'Iż-Żurrieq', name_latin=N'Żurrieq', abac_name=N'Iz-Zurrieq', display_name=N'Iż-Żurrieq' WHERE id=77500;
UPDATE laus SET name_national=N'L-Għarb', name_latin=N'Għarb', abac_name=N'L-Gharb', display_name=N'L-Għarb' WHERE id=77520;
UPDATE laus SET name_national=N'L-Għasri', name_latin=N'Għasri', abac_name=N'L-Ghasri', display_name=N'L-Għasri' WHERE id=77521;
UPDATE laus SET name_national=N'L-Iklin', name_latin=N'Iklin', abac_name=N'L-Iklin', display_name=N'L-Iklin' WHERE id=77507;
UPDATE laus SET name_national=N'L-Imdina', name_latin=N'Citta'' Notabile', abac_name=N'L-Imdina', display_name=N'L-Imdina' WHERE id=77501;
UPDATE laus SET name_national=N'L-Imġarr', name_latin=N'Mġarr', abac_name=N'L-Imgarr', display_name=N'L-Imġarr' WHERE id=77513;
UPDATE laus SET name_national=N'L-Imqabba', name_latin=N'Mqabba', abac_name=N'L-Imqabba', display_name=N'L-Imqabba' WHERE id=77497;
UPDATE laus SET name_national=N'L-Imsida', name_latin=N'Msida', abac_name=N'L-Imsida', display_name=N'L-Imsida' WHERE id=77481;
UPDATE laus SET name_national=N'L-Imtarfa', name_latin=N'Mtarfa', abac_name=N'L-Imtarfa', display_name=N'L-Imtarfa' WHERE id=77510;
UPDATE laus SET name_national=N'L-Isla', name_latin=N'Citta'' Invicta', abac_name=N'L-Isla', display_name=N'L-Isla' WHERE id=77465;
UPDATE laus SET name_national=N'Marsaskala', name_latin=N'Marsaskala', abac_name=N'Marsaskala', display_name=N'Marsaskala' WHERE id=77495;
UPDATE laus SET name_national=N'Marsaxlokk', name_latin=N'Marsaxlokk', abac_name=N'Marsaxlokk', display_name=N'Marsaxlokk' WHERE id=77496;
UPDATE laus SET name_national=N'Paola', name_latin=N'Paola', abac_name=N'Paola', display_name=N'Paola' WHERE id=77473;
UPDATE laus SET name_national=N'Pembroke', name_latin=N'Pembroke', abac_name=N'Pembroke', display_name=N'Pembroke' WHERE id=77482;
UPDATE laus SET name_national=N'San Ġiljan', name_latin=N'San Ġiljan', abac_name=N'San Giljan', display_name=N'San Ġiljan' WHERE id=77484;
UPDATE laus SET name_national=N'San Ġwann', name_latin=N'San Ġwann', abac_name=N'San Gwann', display_name=N'San Ġwann' WHERE id=77485;
UPDATE laus SET name_national=N'San Lawrenz', name_latin=N'San Lawrenz', abac_name=N'San Lawrenz', display_name=N'San Lawrenz' WHERE id=77526;
UPDATE laus SET name_national=N'San Pawl Il-Baħar', name_latin=N'San Pawl Il-Baħar', abac_name=N'San Pawl Il-Bahar', display_name=N'San Pawl Il-Baħar' WHERE id=77516;
UPDATE laus SET name_national=N'Santa Luċija', name_latin=N'Santa Luċija', abac_name=N'Santa Lucija', display_name=N'Santa Luċija' WHERE id=77474;
UPDATE laus SET name_national=N'Santa Venera', name_latin=N'Santa Venera', abac_name=N'Santa Venera', display_name=N'Santa Venera' WHERE id=77486;
UPDATE laus SET name_national=N'Ta'' Kerċem', name_latin=N'Kerċem', abac_name=N'Ta'' Kercem', display_name=N'Ta'' Kerċem' WHERE id=77522;
UPDATE laus SET name_national=N'Ta'' Sannat', name_latin=N'Sannat', abac_name=N'Ta'' Sannat', display_name=N'Ta'' Sannat' WHERE id=77527;
UPDATE laus SET name_national=N'Ta'' Xbiex', name_latin=N'Ta'' Xbiex', abac_name=N'Ta'' Xbiex', display_name=N'Ta'' Xbiex' WHERE id=77489;
UPDATE laus SET name_national=N'Tal-Pieta''', name_latin=N'Pieta''', abac_name=N'Tal-Pieta''', display_name=N'Tal-Pieta''' WHERE id=77483;
UPDATE laus SET name_national=N'Tas-Sliema', name_latin=N'Sliema', abac_name=N'Tas-Sliema', display_name=N'Tas-Sliema' WHERE id=77487;
UPDATE laus SET name_national=N'Valletta', name_latin=N'Citta'' Umilissima', abac_name=N'Valletta', display_name=N'Valletta' WHERE id=77463;
--68
--select nuts3, lau1, name_national, name_latin, abac_name, display_name, id 
--from laus where country_code = 'MT' order by name1 asc