-- LV
--SQL (names)
UPDATE laus SET name_national=N'Ādažu novads', name_latin=N'Adazu novads', abac_name=N'Adazu novads', display_name=N'Ādažu novads' WHERE id=77433;
UPDATE laus SET name_national=N'Aglonas novads', name_latin=N'Aglonas novads', abac_name=N'Aglonas novads', display_name=N'Aglonas novads' WHERE id=77392;
UPDATE laus SET name_national=N'Aizkraukles novads', name_latin=N'Aizkraukles novads', abac_name=N'Aizkraukles novads', display_name=N'Aizkraukles novads' WHERE id=77353;
UPDATE laus SET name_national=N'Aizputes novads', name_latin=N'Aizputes novads', abac_name=N'Aizputes novads', display_name=N'Aizputes novads' WHERE id=77396;
UPDATE laus SET name_national=N'Aknīstes novads', name_latin=N'Aknistes novads', abac_name=N'Aknistes novads', display_name=N'Aknīstes novads' WHERE id=77386;
UPDATE laus SET name_national=N'Alojas novads', name_latin=N'Alojas novads', abac_name=N'Alojas novads', display_name=N'Alojas novads' WHERE id=77405;
UPDATE laus SET name_national=N'Alsungas novads', name_latin=N'Alsungas novads', abac_name=N'Alsungas novads', display_name=N'Alsungas novads' WHERE id=77395;
UPDATE laus SET name_national=N'Alūksnes novads', name_latin=N'Aluksnes novads', abac_name=N'Aluksnes novads', display_name=N'Alūksnes novads' WHERE id=77359;
UPDATE laus SET name_national=N'Amatas novads', name_latin=N'Amatas novads', abac_name=N'Amatas novads', display_name=N'Amatas novads' WHERE id=77371;
UPDATE laus SET name_national=N'Apes novads', name_latin=N'Apes novads', abac_name=N'Apes novads', display_name=N'Apes novads' WHERE id=77360;
UPDATE laus SET name_national=N'Auces novads', name_latin=N'Auces novads', abac_name=N'Auces novads', display_name=N'Auces novads' WHERE id=77380;
UPDATE laus SET name_national=N'Babītes novads', name_latin=N'Babites novads', abac_name=N'Babites novads', display_name=N'Babītes novads' WHERE id=77434;
UPDATE laus SET name_national=N'Baldones novads', name_latin=N'Baldones novads', abac_name=N'Baldones novads', display_name=N'Baldones novads' WHERE id=77426;
UPDATE laus SET name_national=N'Baltinavas novads', name_latin=N'Baltinavas novads', abac_name=N'Baltinavas novads', display_name=N'Baltinavas novads' WHERE id=77363;
UPDATE laus SET name_national=N'Balvu novads', name_latin=N'Balvu novads', abac_name=N'Balvu novads', display_name=N'Balvu novads' WHERE id=77361;
UPDATE laus SET name_national=N'Bauskas novads', name_latin=N'Bauskas novads', abac_name=N'Bauskas novads', display_name=N'Bauskas novads' WHERE id=77365;
UPDATE laus SET name_national=N'Beverīnas novads', name_latin=N'Beverinas novads', abac_name=N'Beverinas novads', display_name=N'Beverīnas novads' WHERE id=77459;
UPDATE laus SET name_national=N'Brocēnu novads', name_latin=N'Brocenu novads', abac_name=N'Brocenu novads', display_name=N'Brocēnu novads' WHERE id=77444;
UPDATE laus SET name_national=N'Burtnieku novads', name_latin=N'Burtnieku novads', abac_name=N'Burtnieku novads', display_name=N'Burtnieku novads' WHERE id=77460;
UPDATE laus SET name_national=N'Carnikavas novads', name_latin=N'Carnikavas novads', abac_name=N'Carnikavas novads', display_name=N'Carnikavas novads' WHERE id=77435;
UPDATE laus SET name_national=N'Cēsu novads', name_latin=N'Cesu novads', abac_name=N'Cesu novads', display_name=N'Cēsu novads' WHERE id=77369;
UPDATE laus SET name_national=N'Cesvaines novads', name_latin=N'Cesvaines novads', abac_name=N'Cesvaines novads', display_name=N'Cesvaines novads' WHERE id=77412;
UPDATE laus SET name_national=N'Ciblas novads', name_latin=N'Ciblas novads', abac_name=N'Ciblas novads', display_name=N'Ciblas novads' WHERE id=77410;
UPDATE laus SET name_national=N'Dagdas novads', name_latin=N'Dagdas novads', abac_name=N'Dagdas novads', display_name=N'Dagdas novads' WHERE id=77391;
UPDATE laus SET name_national=N'Daugavpils', name_latin=N'Daugavpils', abac_name=N'Daugavpils', display_name=N'Daugavpils' WHERE id=77345;
UPDATE laus SET name_national=N'Daugavpils novads', name_latin=N'Daugavpils novads', abac_name=N'Daugavpils novads', display_name=N'Daugavpils novads' WHERE id=77377;
UPDATE laus SET name_national=N'Dobeles novads', name_latin=N'Dobeles novads', abac_name=N'Dobeles novads', display_name=N'Dobeles novads' WHERE id=77379;
UPDATE laus SET name_national=N'Dundagas novads', name_latin=N'Dundagas novads', abac_name=N'Dundagas novads', display_name=N'Dundagas novads' WHERE id=77446;
UPDATE laus SET name_national=N'Durbes novads', name_latin=N'Durbes novads', abac_name=N'Durbes novads', display_name=N'Durbes novads' WHERE id=77397;
UPDATE laus SET name_national=N'Engures novads', name_latin=N'Engures novads', abac_name=N'Engures novads', display_name=N'Engures novads' WHERE id=77451;
UPDATE laus SET name_national=N'Ērgļu novads', name_latin=N'Erglu novads', abac_name=N'Erglu novads', display_name=N'Ērgļu novads' WHERE id=77415;
UPDATE laus SET name_national=N'Garkalnes novads', name_latin=N'Garkalnes novads', abac_name=N'Garkalnes novads', display_name=N'Garkalnes novads' WHERE id=77436;
UPDATE laus SET name_national=N'Grobiņas novads', name_latin=N'Grobinas novads', abac_name=N'Grobinas novads', display_name=N'Grobiņas novads' WHERE id=77398;
UPDATE laus SET name_national=N'Gulbenes novads', name_latin=N'Gulbenes novads', abac_name=N'Gulbenes novads', display_name=N'Gulbenes novads' WHERE id=77382;
UPDATE laus SET name_national=N'Iecavas novads', name_latin=N'Iecavas novads', abac_name=N'Iecavas novads', display_name=N'Iecavas novads' WHERE id=77366;
UPDATE laus SET name_national=N'Ikšķiles novads', name_latin=N'Ikskiles novads', abac_name=N'Ikskiles novads', display_name=N'Ikšķiles novads' WHERE id=77417;
UPDATE laus SET name_national=N'Ilūkstes novads', name_latin=N'Ilukstes novads', abac_name=N'Ilukstes novads', display_name=N'Ilūkstes novads' WHERE id=77378;
UPDATE laus SET name_national=N'Inčukalna novads', name_latin=N'Incukalna novads', abac_name=N'Incukalna novads', display_name=N'Inčukalna novads' WHERE id=77432;
UPDATE laus SET name_national=N'Jaunjelgavas novads', name_latin=N'Jaunjelgavas novads', abac_name=N'Jaunjelgavas novads', display_name=N'Jaunjelgavas novads' WHERE id=77354;
UPDATE laus SET name_national=N'Jaunpiebalgas novads', name_latin=N'Jaunpiebalgas novads', abac_name=N'Jaunpiebalgas novads', display_name=N'Jaunpiebalgas novads' WHERE id=77372;
UPDATE laus SET name_national=N'Jaunpils novads', name_latin=N'Jaunpils novads', abac_name=N'Jaunpils novads', display_name=N'Jaunpils novads' WHERE id=77452;
UPDATE laus SET name_national=N'Jēkabpils', name_latin=N'Jekabpils', abac_name=N'Jekabpils', display_name=N'Jēkabpils' WHERE id=77347;
UPDATE laus SET name_national=N'Jēkabpils novads', name_latin=N'Jekabpils novads', abac_name=N'Jekabpils novads', display_name=N'Jēkabpils novads' WHERE id=77385;
UPDATE laus SET name_national=N'Jelgava', name_latin=N'Jelgava', abac_name=N'Jelgava', display_name=N'Jelgava' WHERE id=77346;
UPDATE laus SET name_national=N'Jelgavas novads', name_latin=N'Jelgavas novads', abac_name=N'Jelgavas novads', display_name=N'Jelgavas novads' WHERE id=77383;
UPDATE laus SET name_national=N'Jūrmala', name_latin=N'Jurmala', abac_name=N'Jurmala', display_name=N'Jūrmala' WHERE id=77348;
UPDATE laus SET name_national=N'Kandavas novads', name_latin=N'Kandavas novads', abac_name=N'Kandavas novads', display_name=N'Kandavas novads' WHERE id=77450;
UPDATE laus SET name_national=N'Kārsavas novads', name_latin=N'Karsavas novads', abac_name=N'Karsavas novads', display_name=N'Kārsavas novads' WHERE id=77408;
UPDATE laus SET name_national=N'Ķeguma novads', name_latin=N'Keguma novads', abac_name=N'Keguma novads', display_name=N'Ķeguma novads' WHERE id=77418;
UPDATE laus SET name_national=N'Ķekavas novads', name_latin=N'Kekavas novads', abac_name=N'Kekavas novads', display_name=N'Ķekavas novads' WHERE id=77427;
UPDATE laus SET name_national=N'Kocēnu novads', name_latin=N'Kocenu novads', abac_name=N'Kocenu novads', display_name=N'Kocēnu novads' WHERE id=77456;
UPDATE laus SET name_national=N'Kokneses novads', name_latin=N'Kokneses novads', abac_name=N'Kokneses novads', display_name=N'Kokneses novads' WHERE id=77356;
UPDATE laus SET name_national=N'Krāslavas novads', name_latin=N'Kraslavas novads', abac_name=N'Kraslavas novads', display_name=N'Krāslavas novads' WHERE id=77390;
UPDATE laus SET name_national=N'Krimuldas novads', name_latin=N'Krimuldas novads', abac_name=N'Krimuldas novads', display_name=N'Krimuldas novads' WHERE id=77437;
UPDATE laus SET name_national=N'Krustpils novads', name_latin=N'Krustpils novads', abac_name=N'Krustpils novads', display_name=N'Krustpils novads' WHERE id=77388;
UPDATE laus SET name_national=N'Kuldīgas novads', name_latin=N'Kuldigas novads', abac_name=N'Kuldigas novads', display_name=N'Kuldīgas novads' WHERE id=77393;
UPDATE laus SET name_national=N'Lielvārdes novads', name_latin=N'Lielvardes novads', abac_name=N'Lielvardes novads', display_name=N'Lielvārdes novads' WHERE id=77419;
UPDATE laus SET name_national=N'Liepāja', name_latin=N'Liepaja', abac_name=N'Liepaja', display_name=N'Liepāja' WHERE id=77349;
UPDATE laus SET name_national=N'Līgatnes novads', name_latin=N'Ligatnes novads', abac_name=N'Ligatnes novads', display_name=N'Līgatnes novads' WHERE id=77370;
UPDATE laus SET name_national=N'Limbažu novads', name_latin=N'Limbazu novads', abac_name=N'Limbazu novads', display_name=N'Limbažu novads' WHERE id=77404;
UPDATE laus SET name_national=N'Līvānu novads', name_latin=N'Livanu novads', abac_name=N'Livanu novads', display_name=N'Līvānu novads' WHERE id=77421;
UPDATE laus SET name_national=N'Lubānas novads', name_latin=N'Lubanas novads', abac_name=N'Lubanas novads', display_name=N'Lubānas novads' WHERE id=77413;
UPDATE laus SET name_national=N'Ludzas novads', name_latin=N'Ludzas novads', abac_name=N'Ludzas novads', display_name=N'Ludzas novads' WHERE id=77407;
UPDATE laus SET name_national=N'Madonas novads', name_latin=N'Madonas novads', abac_name=N'Madonas novads', display_name=N'Madonas novads' WHERE id=77411;
UPDATE laus SET name_national=N'Mālpils novads', name_latin=N'Malpils novads', abac_name=N'Malpils novads', display_name=N'Mālpils novads' WHERE id=77438;
UPDATE laus SET name_national=N'Mārupes novads', name_latin=N'Marupes novads', abac_name=N'Marupes novads', display_name=N'Mārupes novads' WHERE id=77439;
UPDATE laus SET name_national=N'Mazsalacas novads', name_latin=N'Mazsalacas novads', abac_name=N'Mazsalacas novads', display_name=N'Mazsalacas novads' WHERE id=77457;
UPDATE laus SET name_national=N'Mērsraga novads', name_latin=N'Mersraga novads', abac_name=N'Mersraga novads', display_name=N'Mērsraga novads' WHERE id=77447;
UPDATE laus SET name_national=N'Naukšēnu novads', name_latin=N'Nauksenu novads', abac_name=N'Nauksenu novads', display_name=N'Naukšēnu novads' WHERE id=77461;
UPDATE laus SET name_national=N'Neretas novads', name_latin=N'Neretas novads', abac_name=N'Neretas novads', display_name=N'Neretas novads' WHERE id=77357;
UPDATE laus SET name_national=N'Nīcas novads', name_latin=N'Nicas novads', abac_name=N'Nicas novads', display_name=N'Nīcas novads' WHERE id=77401;
UPDATE laus SET name_national=N'Ogres novads', name_latin=N'Ogres novads', abac_name=N'Ogres novads', display_name=N'Ogres novads' WHERE id=77416;
UPDATE laus SET name_national=N'Olaines novads', name_latin=N'Olaines novads', abac_name=N'Olaines novads', display_name=N'Olaines novads' WHERE id=77428;
UPDATE laus SET name_national=N'Ozolnieku novads', name_latin=N'Ozolnieku novads', abac_name=N'Ozolnieku novads', display_name=N'Ozolnieku novads' WHERE id=77384;
UPDATE laus SET name_national=N'Pārgaujas novads', name_latin=N'Pargaujas novads', abac_name=N'Pargaujas novads', display_name=N'Pārgaujas novads' WHERE id=77374;
UPDATE laus SET name_national=N'Pāvilostas novads', name_latin=N'Pavilostas novads', abac_name=N'Pavilostas novads', display_name=N'Pāvilostas novads' WHERE id=77399;
UPDATE laus SET name_national=N'Pļaviņu novads', name_latin=N'Plavinu novads', abac_name=N'Plavinu novads', display_name=N'Pļaviņu novads' WHERE id=77355;
UPDATE laus SET name_national=N'Preiļu novads', name_latin=N'Preilu novads', abac_name=N'Preilu novads', display_name=N'Preiļu novads' WHERE id=77420;
UPDATE laus SET name_national=N'Priekules novads', name_latin=N'Priekules novads', abac_name=N'Priekules novads', display_name=N'Priekules novads' WHERE id=77400;
UPDATE laus SET name_national=N'Priekuļu novads', name_latin=N'Priekulu novads', abac_name=N'Priekulu novads', display_name=N'Priekuļu novads' WHERE id=77373;
UPDATE laus SET name_national=N'Raunas novads', name_latin=N'Raunas novads', abac_name=N'Raunas novads', display_name=N'Raunas novads' WHERE id=77375;
UPDATE laus SET name_national=N'Rēzekne', name_latin=N'Rezekne', abac_name=N'Rezekne', display_name=N'Rēzekne' WHERE id=77350;
UPDATE laus SET name_national=N'Rēzeknes novads', name_latin=N'Rezeknes novads', abac_name=N'Rezeknes novads', display_name=N'Rēzeknes novads' WHERE id=77424;
UPDATE laus SET name_national=N'Riebiņu novads', name_latin=N'Riebinu novads', abac_name=N'Riebinu novads', display_name=N'Riebiņu novads' WHERE id=77422;
UPDATE laus SET name_national=N'Rīga', name_latin=N'Riga', abac_name=N'Riga', display_name=N'Rīga' WHERE id=77344;
UPDATE laus SET name_national=N'Rojas novads', name_latin=N'Rojas novads', abac_name=N'Rojas novads', display_name=N'Rojas novads' WHERE id=77448;
UPDATE laus SET name_national=N'Ropažu novads', name_latin=N'Ropazu novads', abac_name=N'Ropazu novads', display_name=N'Ropažu novads' WHERE id=77440;
UPDATE laus SET name_national=N'Rucavas novads', name_latin=N'Rucavas novads', abac_name=N'Rucavas novads', display_name=N'Rucavas novads' WHERE id=77402;
UPDATE laus SET name_national=N'Rugāju novads', name_latin=N'Rugaju novads', abac_name=N'Rugaju novads', display_name=N'Rugāju novads' WHERE id=77364;
UPDATE laus SET name_national=N'Rūjienas novads', name_latin=N'Rujienas novads', abac_name=N'Rujienas novads', display_name=N'Rūjienas novads' WHERE id=77458;
UPDATE laus SET name_national=N'Rundāles novads', name_latin=N'Rundales novads', abac_name=N'Rundales novads', display_name=N'Rundāles novads' WHERE id=77367;
UPDATE laus SET name_national=N'Salacgrīvas novads', name_latin=N'Salacgrivas novads', abac_name=N'Salacgrivas novads', display_name=N'Salacgrīvas novads' WHERE id=77406;
UPDATE laus SET name_national=N'Salas novads', name_latin=N'Salas novads', abac_name=N'Salas novads', display_name=N'Salas novads' WHERE id=77389;
UPDATE laus SET name_national=N'Salaspils novads', name_latin=N'Salaspils novads', abac_name=N'Salaspils novads', display_name=N'Salaspils novads' WHERE id=77429;
UPDATE laus SET name_national=N'Saldus novads', name_latin=N'Saldus novads', abac_name=N'Saldus novads', display_name=N'Saldus novads' WHERE id=77443;
UPDATE laus SET name_national=N'Saulkrastu novads', name_latin=N'Saulkrastu novads', abac_name=N'Saulkrastu novads', display_name=N'Saulkrastu novads' WHERE id=77430;
UPDATE laus SET name_national=N'Sējas novads', name_latin=N'Sejas novads', abac_name=N'Sejas novads', display_name=N'Sējas novads' WHERE id=77441;
UPDATE laus SET name_national=N'Siguldas novads', name_latin=N'Siguldas novads', abac_name=N'Siguldas novads', display_name=N'Siguldas novads' WHERE id=77431;
UPDATE laus SET name_national=N'Skrīveru novads', name_latin=N'Skriveru novads', abac_name=N'Skriveru novads', display_name=N'Skrīveru novads' WHERE id=77358;
UPDATE laus SET name_national=N'Skrundas novads', name_latin=N'Skrundas novads', abac_name=N'Skrundas novads', display_name=N'Skrundas novads' WHERE id=77394;
UPDATE laus SET name_national=N'Smiltenes novads', name_latin=N'Smiltenes novads', abac_name=N'Smiltenes novads', display_name=N'Smiltenes novads' WHERE id=77454;
UPDATE laus SET name_national=N'Stopiņu novads', name_latin=N'Stopinu novads', abac_name=N'Stopinu novads', display_name=N'Stopiņu novads' WHERE id=77442;
UPDATE laus SET name_national=N'Strenču novads', name_latin=N'Strencu novads', abac_name=N'Strencu novads', display_name=N'Strenču novads' WHERE id=77455;
UPDATE laus SET name_national=N'Talsu novads', name_latin=N'Talsu novads', abac_name=N'Talsu novads', display_name=N'Talsu novads' WHERE id=77445;
UPDATE laus SET name_national=N'Tērvetes novads', name_latin=N'Tervetes novads', abac_name=N'Tervetes novads', display_name=N'Tērvetes novads' WHERE id=77381;
UPDATE laus SET name_national=N'Tukuma novads', name_latin=N'Tukuma novads', abac_name=N'Tukuma novads', display_name=N'Tukuma novads' WHERE id=77449;
UPDATE laus SET name_national=N'Vaiņodes novads', name_latin=N'Vainodes novads', abac_name=N'Vainodes novads', display_name=N'Vaiņodes novads' WHERE id=77403;
UPDATE laus SET name_national=N'Valkas novads', name_latin=N'Valkas novads', abac_name=N'Valkas novads', display_name=N'Valkas novads' WHERE id=77453;
UPDATE laus SET name_national=N'Valmiera', name_latin=N'Valmiera', abac_name=N'Valmiera', display_name=N'Valmiera' WHERE id=77351;
UPDATE laus SET name_national=N'Varakļānu novads', name_latin=N'Varaklanu novads', abac_name=N'Varaklanu novads', display_name=N'Varakļānu novads' WHERE id=77414;
UPDATE laus SET name_national=N'Vārkavas novads', name_latin=N'Varkavas novads', abac_name=N'Varkavas novads', display_name=N'Vārkavas novads' WHERE id=77423;
UPDATE laus SET name_national=N'Vecpiebalgas novads', name_latin=N'Vecpiebalgas novads', abac_name=N'Vecpiebalgas novads', display_name=N'Vecpiebalgas novads' WHERE id=77376;
UPDATE laus SET name_national=N'Vecumnieku novads', name_latin=N'Vecumnieku novads', abac_name=N'Vecumnieku novads', display_name=N'Vecumnieku novads' WHERE id=77368;
UPDATE laus SET name_national=N'Ventspils', name_latin=N'Ventspils', abac_name=N'Ventspils', display_name=N'Ventspils' WHERE id=77352;
UPDATE laus SET name_national=N'Ventspils novads', name_latin=N'Ventspils novads', abac_name=N'Ventspils novads', display_name=N'Ventspils novads' WHERE id=77462;
UPDATE laus SET name_national=N'Viesītes novads', name_latin=N'Viesites novads', abac_name=N'Viesites novads', display_name=N'Viesītes novads' WHERE id=77387;
UPDATE laus SET name_national=N'Viļakas novads', name_latin=N'Vilakas novads', abac_name=N'Vilakas novads', display_name=N'Viļakas novads' WHERE id=77362;
UPDATE laus SET name_national=N'Viļānu novads', name_latin=N'Vilanu novads', abac_name=N'Vilanu novads', display_name=N'Viļānu novads' WHERE id=77425;
UPDATE laus SET name_national=N'Zilupes novads', name_latin=N'Zilupes novads', abac_name=N'Zilupes novads', display_name=N'Zilupes novads' WHERE id=77409;
--119


--select nuts3, lau1, name_national, name_latin, abac_name, display_name, id 
--from laus where country_code = 'LV' order by name1 asc