-- INSERT HR LAUS (added new name fields)
UPDATE laus SET name_national=N'Andrijaševci', name_latin=N'Andrijaševci', abac_name=N'Andrijasevci', display_name=N'Andrijaševci' WHERE id=65278;
UPDATE laus SET name_national=N'Antunovac', name_latin=N'Antunovac', abac_name=N'Antunovac', display_name=N'Antunovac' WHERE id=65279;
UPDATE laus SET name_national=N'Babina Greda', name_latin=N'Babina greda', abac_name=N'Babina Greda', display_name=N'Babina Greda' WHERE id=65280;
UPDATE laus SET name_national=N'Bakar', name_latin=N'Bakar', abac_name=N'Bakar', display_name=N'Bakar' WHERE id=65281;
UPDATE laus SET name_national=N'Bale - Valle', name_latin=N'Bale - valle', abac_name=N'Bale - Valle', display_name=N'Bale - Valle' WHERE id=65282;
UPDATE laus SET name_national=N'Barban', name_latin=N'Barban', abac_name=N'Barban', display_name=N'Barban' WHERE id=65283;
UPDATE laus SET name_national=N'Barilović', name_latin=N'Barilović', abac_name=N'Barilovic', display_name=N'Barilović' WHERE id=65284;
UPDATE laus SET name_national=N'Baška', name_latin=N'Baška', abac_name=N'Baska', display_name=N'Baška' WHERE id=65285;
UPDATE laus SET name_national=N'Baška Voda', name_latin=N'Baška voda', abac_name=N'Baska Voda', display_name=N'Baška Voda' WHERE id=65286;
UPDATE laus SET name_national=N'Bebrina', name_latin=N'Bebrina', abac_name=N'Bebrina', display_name=N'Bebrina' WHERE id=65287;
UPDATE laus SET name_national=N'Bedekovčina', name_latin=N'Bedekovčina', abac_name=N'Bedekovcina', display_name=N'Bedekovčina' WHERE id=65288;
UPDATE laus SET name_national=N'Bedenica', name_latin=N'Bedenica', abac_name=N'Bedenica', display_name=N'Bedenica' WHERE id=65289;
UPDATE laus SET name_national=N'Bednja', name_latin=N'Bednja', abac_name=N'Bednja', display_name=N'Bednja' WHERE id=65290;
UPDATE laus SET name_national=N'Beli Manastir', name_latin=N'Beli manastir', abac_name=N'Beli Manastir', display_name=N'Beli Manastir' WHERE id=65291;
UPDATE laus SET name_national=N'Belica', name_latin=N'Belica', abac_name=N'Belica', display_name=N'Belica' WHERE id=65292;
UPDATE laus SET name_national=N'Belišće', name_latin=N'Belišće', abac_name=N'Belisce', display_name=N'Belišće' WHERE id=65293;
UPDATE laus SET name_national=N'Benkovac', name_latin=N'Benkovac', abac_name=N'Benkovac', display_name=N'Benkovac' WHERE id=65294;
UPDATE laus SET name_national=N'Berek', name_latin=N'Berek', abac_name=N'Berek', display_name=N'Berek' WHERE id=65295;
UPDATE laus SET name_national=N'Beretinec', name_latin=N'Beretinec', abac_name=N'Beretinec', display_name=N'Beretinec' WHERE id=65296;
UPDATE laus SET name_national=N'Bibinje', name_latin=N'Bibinje', abac_name=N'Bibinje', display_name=N'Bibinje' WHERE id=65297;
UPDATE laus SET name_national=N'Bilice', name_latin=N'Bilice', abac_name=N'Bilice', display_name=N'Bilice' WHERE id=65298;
UPDATE laus SET name_national=N'Bilje', name_latin=N'Bilje', abac_name=N'Bilje', display_name=N'Bilje' WHERE id=65299;
UPDATE laus SET name_national=N'Biograd Na Moru', name_latin=N'Biograd na moru', abac_name=N'Biograd Na Moru', display_name=N'Biograd Na Moru' WHERE id=65300;
UPDATE laus SET name_national=N'Biskupija', name_latin=N'Biskupija', abac_name=N'Biskupija', display_name=N'Biskupija' WHERE id=65301;
UPDATE laus SET name_national=N'Bistra', name_latin=N'Bistra', abac_name=N'Bistra', display_name=N'Bistra' WHERE id=65302;
UPDATE laus SET name_national=N'Bizovac', name_latin=N'Bizovac', abac_name=N'Bizovac', display_name=N'Bizovac' WHERE id=65303;
UPDATE laus SET name_national=N'Bjelovar', name_latin=N'Bjelovar', abac_name=N'Bjelovar', display_name=N'Bjelovar' WHERE id=65304;
UPDATE laus SET name_national=N'Blato', name_latin=N'Blato', abac_name=N'Blato', display_name=N'Blato' WHERE id=65305;
UPDATE laus SET name_national=N'Bogdanovci', name_latin=N'Bogdanovci', abac_name=N'Bogdanovci', display_name=N'Bogdanovci' WHERE id=65306;
UPDATE laus SET name_national=N'Bol', name_latin=N'Bol', abac_name=N'Bol', display_name=N'Bol' WHERE id=65307;
UPDATE laus SET name_national=N'Borovo', name_latin=N'Borovo', abac_name=N'Borovo', display_name=N'Borovo' WHERE id=65308;
UPDATE laus SET name_national=N'Bosiljevo', name_latin=N'Bosiljevo', abac_name=N'Bosiljevo', display_name=N'Bosiljevo' WHERE id=65309;
UPDATE laus SET name_national=N'Bošnjaci', name_latin=N'Bošnjaci', abac_name=N'Bosnjaci', display_name=N'Bošnjaci' WHERE id=65310;
UPDATE laus SET name_national=N'Brckovljani', name_latin=N'Brckovljani', abac_name=N'Brckovljani', display_name=N'Brckovljani' WHERE id=65311;
UPDATE laus SET name_national=N'Brdovec', name_latin=N'Brdovec', abac_name=N'Brdovec', display_name=N'Brdovec' WHERE id=65312;
UPDATE laus SET name_national=N'Brela', name_latin=N'Brela', abac_name=N'Brela', display_name=N'Brela' WHERE id=65313;
UPDATE laus SET name_national=N'Brestovac', name_latin=N'Brestovac', abac_name=N'Brestovac', display_name=N'Brestovac' WHERE id=65314;
UPDATE laus SET name_national=N'Breznica', name_latin=N'Breznica', abac_name=N'Breznica', display_name=N'Breznica' WHERE id=65315;
UPDATE laus SET name_national=N'Breznički Hum', name_latin=N'Breznički hum', abac_name=N'Breznicki Hum', display_name=N'Breznički Hum' WHERE id=65316;
UPDATE laus SET name_national=N'Brinje', name_latin=N'Brinje', abac_name=N'Brinje', display_name=N'Brinje' WHERE id=65317;
UPDATE laus SET name_national=N'Brod Moravice', name_latin=N'Brod moravice', abac_name=N'Brod Moravice', display_name=N'Brod Moravice' WHERE id=65318;
UPDATE laus SET name_national=N'Brodski Stupnik', name_latin=N'Brodski stupnik', abac_name=N'Brodski Stupnik', display_name=N'Brodski Stupnik' WHERE id=65319;
UPDATE laus SET name_national=N'Brtonigla - Verteneglio', name_latin=N'Brtonigla - verteneglio', abac_name=N'Brtonigla - Verteneglio', display_name=N'Brtonigla - Verteneglio' WHERE id=65320;
UPDATE laus SET name_national=N'Budinščina', name_latin=N'Budinščina', abac_name=N'Budinscina', display_name=N'Budinščina' WHERE id=65321;
UPDATE laus SET name_national=N'Buje', name_latin=N'Buje - buie', abac_name=N'Buje', display_name=N'Buje' WHERE id=65322;
UPDATE laus SET name_national=N'Bukovlje', name_latin=N'Bukovlje', abac_name=N'Bukovlje', display_name=N'Bukovlje' WHERE id=65323;
UPDATE laus SET name_national=N'Buzet', name_latin=N'Buzet', abac_name=N'Buzet', display_name=N'Buzet' WHERE id=65324;
UPDATE laus SET name_national=N'Čabar', name_latin=N'Čabar', abac_name=N'Cabar', display_name=N'Čabar' WHERE id=65325;
UPDATE laus SET name_national=N'Čačinci', name_latin=N'Čačinci', abac_name=N'Cacinci', display_name=N'Čačinci' WHERE id=65326;
UPDATE laus SET name_national=N'Čađavica', name_latin=N'Čađavica', abac_name=N'Cadavica', display_name=N'Čađavica' WHERE id=65327;
UPDATE laus SET name_national=N'Čaglin', name_latin=N'Čaglin', abac_name=N'Caglin', display_name=N'Čaglin' WHERE id=65328;
UPDATE laus SET name_national=N'Čakovec', name_latin=N'Čakovec', abac_name=N'Cakovec', display_name=N'Čakovec' WHERE id=65329;
UPDATE laus SET name_national=N'Čavle', name_latin=N'Čavle', abac_name=N'Cavle', display_name=N'Čavle' WHERE id=65330;
UPDATE laus SET name_national=N'Čazma', name_latin=N'Čazma', abac_name=N'Cazma', display_name=N'Čazma' WHERE id=65331;
UPDATE laus SET name_national=N'Čeminac', name_latin=N'Čeminac', abac_name=N'Ceminac', display_name=N'Čeminac' WHERE id=65332;
UPDATE laus SET name_national=N'Čepin', name_latin=N'Čepin', abac_name=N'Cepin', display_name=N'Čepin' WHERE id=65333;
UPDATE laus SET name_national=N'Cerna', name_latin=N'Cerna', abac_name=N'Cerna', display_name=N'Cerna' WHERE id=65334;
UPDATE laus SET name_national=N'Cernik', name_latin=N'Cernik', abac_name=N'Cernik', display_name=N'Cernik' WHERE id=65335;
UPDATE laus SET name_national=N'Cerovlje', name_latin=N'Cerovlje', abac_name=N'Cerovlje', display_name=N'Cerovlje' WHERE id=65336;
UPDATE laus SET name_national=N'Cestica', name_latin=N'Cestica', abac_name=N'Cestica', display_name=N'Cestica' WHERE id=65337;
UPDATE laus SET name_national=N'Cetingrad', name_latin=N'Cetingrad', abac_name=N'Cetingrad', display_name=N'Cetingrad' WHERE id=65338;
UPDATE laus SET name_national=N'Cista Provo', name_latin=N'Cista provo', abac_name=N'Cista Provo', display_name=N'Cista Provo' WHERE id=65339;
UPDATE laus SET name_national=N'Civljane', name_latin=N'Civljane', abac_name=N'Civljane', display_name=N'Civljane' WHERE id=65340;
UPDATE laus SET name_national=N'Cres', name_latin=N'Cres', abac_name=N'Cres', display_name=N'Cres' WHERE id=65341;
UPDATE laus SET name_national=N'Crikvenica', name_latin=N'Crikvenica', abac_name=N'Crikvenica', display_name=N'Crikvenica' WHERE id=65342;
UPDATE laus SET name_national=N'Crnac', name_latin=N'Crnac', abac_name=N'Crnac', display_name=N'Crnac' WHERE id=65343;
UPDATE laus SET name_national=N'Đakovo', name_latin=N'Đakovo', abac_name=N'Dakovo', display_name=N'Đakovo' WHERE id=65344;
UPDATE laus SET name_national=N'Darda', name_latin=N'Darda', abac_name=N'Darda', display_name=N'Darda' WHERE id=65345;
UPDATE laus SET name_national=N'Daruvar', name_latin=N'Daruvar', abac_name=N'Daruvar', display_name=N'Daruvar' WHERE id=65346;
UPDATE laus SET name_national=N'Davor', name_latin=N'Davor', abac_name=N'Davor', display_name=N'Davor' WHERE id=65347;
UPDATE laus SET name_national=N'Dekanovec', name_latin=N'Dekanovec', abac_name=N'Dekanovec', display_name=N'Dekanovec' WHERE id=65348;
UPDATE laus SET name_national=N'Đelekovec', name_latin=N'Đelekovec', abac_name=N'Delekovec', display_name=N'Đelekovec' WHERE id=65349;
UPDATE laus SET name_national=N'Delnice', name_latin=N'Delnice', abac_name=N'Delnice', display_name=N'Delnice' WHERE id=65350;
UPDATE laus SET name_national=N'Desinić', name_latin=N'Desinić', abac_name=N'Desinic', display_name=N'Desinić' WHERE id=65351;
UPDATE laus SET name_national=N'Dežanovac', name_latin=N'Dežanovac', abac_name=N'Dezanovac', display_name=N'Dežanovac' WHERE id=65352;
UPDATE laus SET name_national=N'Dicmo', name_latin=N'Dicmo', abac_name=N'Dicmo', display_name=N'Dicmo' WHERE id=65353;
UPDATE laus SET name_national=N'Dobrinj', name_latin=N'Dobrinj', abac_name=N'Dobrinj', display_name=N'Dobrinj' WHERE id=65354;
UPDATE laus SET name_national=N'Domašinec', name_latin=N'Domašinec', abac_name=N'Domasinec', display_name=N'Domašinec' WHERE id=65355;
UPDATE laus SET name_national=N'Donja Dubrava', name_latin=N'Donja dubrava', abac_name=N'Donja Dubrava', display_name=N'Donja Dubrava' WHERE id=65356;
UPDATE laus SET name_national=N'Donja Motičina', name_latin=N'Donja motičina', abac_name=N'Donja Moticina', display_name=N'Donja Motičina' WHERE id=65357;
UPDATE laus SET name_national=N'Donja Stubica', name_latin=N'Donja stubica', abac_name=N'Donja Stubica', display_name=N'Donja Stubica' WHERE id=65358;
UPDATE laus SET name_national=N'Donja Voća', name_latin=N'Donja voća', abac_name=N'Donja Voca', display_name=N'Donja Voća' WHERE id=65359;
UPDATE laus SET name_national=N'Donji Andrijevci', name_latin=N'Donji andrijevci', abac_name=N'Donji Andrijevci', display_name=N'Donji Andrijevci' WHERE id=65360;
UPDATE laus SET name_national=N'Donji Kraljevec', name_latin=N'Donji kraljevec', abac_name=N'Donji Kraljevec', display_name=N'Donji Kraljevec' WHERE id=65361;
UPDATE laus SET name_national=N'Donji Kukuruzari', name_latin=N'Donji kukuruzari', abac_name=N'Donji Kukuruzari', display_name=N'Donji Kukuruzari' WHERE id=65362;
UPDATE laus SET name_national=N'Donji Lapac', name_latin=N'Donji lapac', abac_name=N'Donji Lapac', display_name=N'Donji Lapac' WHERE id=65363;
UPDATE laus SET name_national=N'Donji Miholjac', name_latin=N'Donji miholjac', abac_name=N'Donji Miholjac', display_name=N'Donji Miholjac' WHERE id=65364;
UPDATE laus SET name_national=N'Donji Vidovec', name_latin=N'Donji vidovec', abac_name=N'Donji Vidovec', display_name=N'Donji Vidovec' WHERE id=65365;
UPDATE laus SET name_national=N'Dragalić', name_latin=N'Dragalić', abac_name=N'Dragalic', display_name=N'Dragalić' WHERE id=65366;
UPDATE laus SET name_national=N'Draganić', name_latin=N'Draganić', abac_name=N'Draganic', display_name=N'Draganić' WHERE id=65367;
UPDATE laus SET name_national=N'Draž', name_latin=N'Draž', abac_name=N'Draz', display_name=N'Draž' WHERE id=65368;
UPDATE laus SET name_national=N'Drenje', name_latin=N'Drenje', abac_name=N'Drenje', display_name=N'Drenje' WHERE id=65369;
UPDATE laus SET name_national=N'Drenovci', name_latin=N'Drenovci', abac_name=N'Drenovci', display_name=N'Drenovci' WHERE id=65370;
UPDATE laus SET name_national=N'Drniš', name_latin=N'Drniš', abac_name=N'Drnis', display_name=N'Drniš' WHERE id=65371;
UPDATE laus SET name_national=N'Drnje', name_latin=N'Drnje', abac_name=N'Drnje', display_name=N'Drnje' WHERE id=65372;
UPDATE laus SET name_national=N'Dubrava', name_latin=N'Dubrava', abac_name=N'Dubrava', display_name=N'Dubrava' WHERE id=65373;
UPDATE laus SET name_national=N'Dubravica', name_latin=N'Dubravica', abac_name=N'Dubravica', display_name=N'Dubravica' WHERE id=65374;
UPDATE laus SET name_national=N'Dubrovačko Primorje', name_latin=N'Dubrovačko primorje', abac_name=N'Dubrovacko Primorje', display_name=N'Dubrovačko Primorje' WHERE id=65375;
UPDATE laus SET name_national=N'Dubrovnik', name_latin=N'Dubrovnik', abac_name=N'Dubrovnik', display_name=N'Dubrovnik' WHERE id=65376;
UPDATE laus SET name_national=N'Duga Resa', name_latin=N'Duga resa', abac_name=N'Duga Resa', display_name=N'Duga Resa' WHERE id=65377;
UPDATE laus SET name_national=N'Dugi Rat', name_latin=N'Dugi rat', abac_name=N'Dugi Rat', display_name=N'Dugi Rat' WHERE id=65378;
UPDATE laus SET name_national=N'Dugo Selo', name_latin=N'Dugo selo', abac_name=N'Dugo Selo', display_name=N'Dugo Selo' WHERE id=65379;
UPDATE laus SET name_national=N'Dugopolje', name_latin=N'Dugopolje', abac_name=N'Dugopolje', display_name=N'Dugopolje' WHERE id=65380;
UPDATE laus SET name_national=N'Đulovac', name_latin=N'Đulovac', abac_name=N'Dulovac', display_name=N'Đulovac' WHERE id=65381;
UPDATE laus SET name_national=N'Đurđenovac', name_latin=N'Đurđenovac', abac_name=N'Durdenovac', display_name=N'Đurđenovac' WHERE id=65382;
UPDATE laus SET name_national=N'Đurđevac', name_latin=N'Đurđevac', abac_name=N'Durdevac', display_name=N'Đurđevac' WHERE id=65383;
UPDATE laus SET name_national=N'Đurmanec', name_latin=N'Đurmanec', abac_name=N'Durmanec', display_name=N'Đurmanec' WHERE id=65384;
UPDATE laus SET name_national=N'Dvor', name_latin=N'Dvor', abac_name=N'Dvor', display_name=N'Dvor' WHERE id=65385;
UPDATE laus SET name_national=N'Erdut', name_latin=N'Erdut', abac_name=N'Erdut', display_name=N'Erdut' WHERE id=65386;
UPDATE laus SET name_national=N'Ernestinovo', name_latin=N'Ernestinovo', abac_name=N'Ernestinovo', display_name=N'Ernestinovo' WHERE id=65387;
UPDATE laus SET name_national=N'Ervenik', name_latin=N'Ervenik', abac_name=N'Ervenik', display_name=N'Ervenik' WHERE id=65388;
UPDATE laus SET name_national=N'Farkaševac', name_latin=N'Farkaševac', abac_name=N'Farkasevac', display_name=N'Farkaševac' WHERE id=65389;
UPDATE laus SET name_national=N'Fažana - Fasana', name_latin=N'Fažana - fasana', abac_name=N'Fazana - Fasana', display_name=N'Fažana - Fasana' WHERE id=65390;
UPDATE laus SET name_national=N'Ferdinandovac', name_latin=N'Ferdinandovac', abac_name=N'Ferdinandovac', display_name=N'Ferdinandovac' WHERE id=65391;
UPDATE laus SET name_national=N'Feričanci', name_latin=N'Feričanci', abac_name=N'Fericanci', display_name=N'Feričanci' WHERE id=65392;
UPDATE laus SET name_national=N'Funtana - Fontane', name_latin=N'Funtana - fontane', abac_name=N'Funtana - Fontane', display_name=N'Funtana - Fontane' WHERE id=65393;
UPDATE laus SET name_national=N'Fužine', name_latin=N'Fužine', abac_name=N'Fuzine', display_name=N'Fužine' WHERE id=65394;
UPDATE laus SET name_national=N'Galovac', name_latin=N'Galovac', abac_name=N'Galovac', display_name=N'Galovac' WHERE id=65395;
UPDATE laus SET name_national=N'Garčin', name_latin=N'Garčin', abac_name=N'Garcin', display_name=N'Garčin' WHERE id=65396;
UPDATE laus SET name_national=N'Garešnica', name_latin=N'Garešnica', abac_name=N'Garesnica', display_name=N'Garešnica' WHERE id=65397;
UPDATE laus SET name_national=N'Generalski Stol', name_latin=N'Generalski stol', abac_name=N'Generalski Stol', display_name=N'Generalski Stol' WHERE id=65398;
UPDATE laus SET name_national=N'Glina', name_latin=N'Glina', abac_name=N'Glina', display_name=N'Glina' WHERE id=65399;
UPDATE laus SET name_national=N'Gola', name_latin=N'Gola', abac_name=N'Gola', display_name=N'Gola' WHERE id=65400;
UPDATE laus SET name_national=N'Goričan', name_latin=N'Goričan', abac_name=N'Gorican', display_name=N'Goričan' WHERE id=65401;
UPDATE laus SET name_national=N'Gorjani', name_latin=N'Gorjani', abac_name=N'Gorjani', display_name=N'Gorjani' WHERE id=65402;
UPDATE laus SET name_national=N'Gornja Rijeka', name_latin=N'Gornja rijeka', abac_name=N'Gornja Rijeka', display_name=N'Gornja Rijeka' WHERE id=65403;
UPDATE laus SET name_national=N'Gornja Stubica', name_latin=N'Gornja stubica', abac_name=N'Gornja Stubica', display_name=N'Gornja Stubica' WHERE id=65404;
UPDATE laus SET name_national=N'Gornja Vrba', name_latin=N'Gornja vrba', abac_name=N'Gornja Vrba', display_name=N'Gornja Vrba' WHERE id=65405;
UPDATE laus SET name_national=N'Gornji Bogićevci', name_latin=N'Gornji bogićevci', abac_name=N'Gornji Bogicevci', display_name=N'Gornji Bogićevci' WHERE id=65406;
UPDATE laus SET name_national=N'Gornji Kneginec', name_latin=N'Gornji kneginec', abac_name=N'Gornji Kneginec', display_name=N'Gornji Kneginec' WHERE id=65407;
UPDATE laus SET name_national=N'Gornji Mihaljevec', name_latin=N'Gornji mihaljevec', abac_name=N'Gornji Mihaljevec', display_name=N'Gornji Mihaljevec' WHERE id=65408;
UPDATE laus SET name_national=N'Gospić', name_latin=N'Gospić', abac_name=N'Gospic', display_name=N'Gospić' WHERE id=65409;
UPDATE laus SET name_national=N'Gračac', name_latin=N'Gračac', abac_name=N'Gracac', display_name=N'Gračac' WHERE id=65410;
UPDATE laus SET name_national=N'Gračišće', name_latin=N'Gračišće', abac_name=N'Gracisce', display_name=N'Gračišće' WHERE id=65411;
UPDATE laus SET name_national=N'Grad Zagreb', name_latin=N'Grad zagreb', abac_name=N'Grad Zagreb', display_name=N'Grad Zagreb' WHERE id=65412;
UPDATE laus SET name_national=N'Gradac', name_latin=N'Gradac', abac_name=N'Gradac', display_name=N'Gradac' WHERE id=65413;
UPDATE laus SET name_national=N'Gradec', name_latin=N'Gradec', abac_name=N'Gradec', display_name=N'Gradec' WHERE id=65414;
UPDATE laus SET name_national=N'Gradina', name_latin=N'Gradina', abac_name=N'Gradina', display_name=N'Gradina' WHERE id=65415;
UPDATE laus SET name_national=N'Gradište', name_latin=N'Gradište', abac_name=N'Gradiste', display_name=N'Gradište' WHERE id=65416;
UPDATE laus SET name_national=N'Grožnjan - Grisignana', name_latin=N'Grožnjan - grisignana', abac_name=N'Groznjan - Grisignana', display_name=N'Grožnjan - Grisignana' WHERE id=65417;
UPDATE laus SET name_national=N'Grubišno Polje', name_latin=N'Grubišno polje', abac_name=N'Grubisno Polje', display_name=N'Grubišno Polje' WHERE id=65418;
UPDATE laus SET name_national=N'Gundinci', name_latin=N'Gundinci', abac_name=N'Gundinci', display_name=N'Gundinci' WHERE id=65419;
UPDATE laus SET name_national=N'Gunja', name_latin=N'Gunja', abac_name=N'Gunja', display_name=N'Gunja' WHERE id=65420;
UPDATE laus SET name_national=N'Gvozd', name_latin=N'Gvozd', abac_name=N'Gvozd', display_name=N'Gvozd' WHERE id=65421;
UPDATE laus SET name_national=N'Hercegovac', name_latin=N'Hercegovac', abac_name=N'Hercegovac', display_name=N'Hercegovac' WHERE id=65422;
UPDATE laus SET name_national=N'Hlebine', name_latin=N'Hlebine', abac_name=N'Hlebine', display_name=N'Hlebine' WHERE id=65423;
UPDATE laus SET name_national=N'Hrašćina', name_latin=N'Hrašćina', abac_name=N'Hrascina', display_name=N'Hrašćina' WHERE id=65424;
UPDATE laus SET name_national=N'Hrvace', name_latin=N'Hrvace', abac_name=N'Hrvace', display_name=N'Hrvace' WHERE id=65425;
UPDATE laus SET name_national=N'Hrvatska Dubica', name_latin=N'Hrvatska dubica', abac_name=N'Hrvatska Dubica', display_name=N'Hrvatska Dubica' WHERE id=65426;
UPDATE laus SET name_national=N'Hrvatska Kostajnica', name_latin=N'Hrvatska kostajnica', abac_name=N'Hrvatska Kostajnica', display_name=N'Hrvatska Kostajnica' WHERE id=65427;
UPDATE laus SET name_national=N'Hum Na Sutli', name_latin=N'Hum na sutli', abac_name=N'Hum Na Sutli', display_name=N'Hum Na Sutli' WHERE id=65428;
UPDATE laus SET name_national=N'Hvar', name_latin=N'Hvar', abac_name=N'Hvar', display_name=N'Hvar' WHERE id=65429;
UPDATE laus SET name_national=N'Ilok', name_latin=N'Ilok', abac_name=N'Ilok', display_name=N'Ilok' WHERE id=65430;
UPDATE laus SET name_national=N'Imotski', name_latin=N'Imotski', abac_name=N'Imotski', display_name=N'Imotski' WHERE id=65431;
UPDATE laus SET name_national=N'Ivanec', name_latin=N'Ivanec', abac_name=N'Ivanec', display_name=N'Ivanec' WHERE id=65432;
UPDATE laus SET name_national=N'Ivanić-Grad', name_latin=N'Ivanić-grad', abac_name=N'Ivanic-Grad', display_name=N'Ivanić-Grad' WHERE id=65433;
UPDATE laus SET name_national=N'Ivankovo', name_latin=N'Ivankovo', abac_name=N'Ivankovo', display_name=N'Ivankovo' WHERE id=65434;
UPDATE laus SET name_national=N'Ivanska', name_latin=N'Ivanska', abac_name=N'Ivanska', display_name=N'Ivanska' WHERE id=65435;
UPDATE laus SET name_national=N'Jagodnjak', name_latin=N'Jagodnjak', abac_name=N'Jagodnjak', display_name=N'Jagodnjak' WHERE id=65436;
UPDATE laus SET name_national=N'Jakovlje', name_latin=N'Jakovlje', abac_name=N'Jakovlje', display_name=N'Jakovlje' WHERE id=65437;
UPDATE laus SET name_national=N'Jakšić', name_latin=N'Jakšić', abac_name=N'Jaksic', display_name=N'Jakšić' WHERE id=65438;
UPDATE laus SET name_national=N'Jalžabet', name_latin=N'Jalžabet', abac_name=N'Jalzabet', display_name=N'Jalžabet' WHERE id=65439;
UPDATE laus SET name_national=N'Janjina', name_latin=N'Janjina', abac_name=N'Janjina', display_name=N'Janjina' WHERE id=65440;
UPDATE laus SET name_national=N'Jarmina', name_latin=N'Jarmina', abac_name=N'Jarmina', display_name=N'Jarmina' WHERE id=65441;
UPDATE laus SET name_national=N'Jasenice', name_latin=N'Jasenice', abac_name=N'Jasenice', display_name=N'Jasenice' WHERE id=65442;
UPDATE laus SET name_national=N'Jasenovac', name_latin=N'Jasenovac', abac_name=N'Jasenovac', display_name=N'Jasenovac' WHERE id=65443;
UPDATE laus SET name_national=N'Jastrebarsko', name_latin=N'Jastrebarsko', abac_name=N'Jastrebarsko', display_name=N'Jastrebarsko' WHERE id=65444;
UPDATE laus SET name_national=N'Jelenje', name_latin=N'Jelenje', abac_name=N'Jelenje', display_name=N'Jelenje' WHERE id=65445;
UPDATE laus SET name_national=N'Jelsa', name_latin=N'Jelsa', abac_name=N'Jelsa', display_name=N'Jelsa' WHERE id=65446;
UPDATE laus SET name_national=N'Jesenje', name_latin=N'Jesenje', abac_name=N'Jesenje', display_name=N'Jesenje' WHERE id=65447;
UPDATE laus SET name_national=N'Josipdol', name_latin=N'Josipdol', abac_name=N'Josipdol', display_name=N'Josipdol' WHERE id=65448;
UPDATE laus SET name_national=N'Kali', name_latin=N'Kali', abac_name=N'Kali', display_name=N'Kali' WHERE id=65449;
UPDATE laus SET name_national=N'Kalinovac', name_latin=N'Kalinovac', abac_name=N'Kalinovac', display_name=N'Kalinovac' WHERE id=65450;
UPDATE laus SET name_national=N'Kalnik', name_latin=N'Kalnik', abac_name=N'Kalnik', display_name=N'Kalnik' WHERE id=65451;
UPDATE laus SET name_national=N'Kamanje', name_latin=N'Kamanje', abac_name=N'Kamanje', display_name=N'Kamanje' WHERE id=65452;
UPDATE laus SET name_national=N'Kanfanar', name_latin=N'Kanfanar', abac_name=N'Kanfanar', display_name=N'Kanfanar' WHERE id=65453;
UPDATE laus SET name_national=N'Kapela', name_latin=N'Kapela', abac_name=N'Kapela', display_name=N'Kapela' WHERE id=65454;
UPDATE laus SET name_national=N'Kaptol', name_latin=N'Kaptol', abac_name=N'Kaptol', display_name=N'Kaptol' WHERE id=65455;
UPDATE laus SET name_national=N'Karlobag', name_latin=N'Karlobag', abac_name=N'Karlobag', display_name=N'Karlobag' WHERE id=65456;
UPDATE laus SET name_national=N'Karlovac', name_latin=N'Karlovac', abac_name=N'Karlovac', display_name=N'Karlovac' WHERE id=65457;
UPDATE laus SET name_national=N'Karojba', name_latin=N'Karojba', abac_name=N'Karojba', display_name=N'Karojba' WHERE id=65458;
UPDATE laus SET name_national=N'Kastav', name_latin=N'Kastav', abac_name=N'Kastav', display_name=N'Kastav' WHERE id=65459;
UPDATE laus SET name_national=N'Kaštela', name_latin=N'Kaštela', abac_name=N'Kastela', display_name=N'Kaštela' WHERE id=65460;
UPDATE laus SET name_national=N'Kaštelir-Labinci - Castelliere-S. Domenica', name_latin=N'Kaštelir-labinci - castelliere-s. Domenica', abac_name=N'Kastelir-Labinci - Castelliere-S. Domenica', display_name=N'Kaštelir-Labinci - Castelliere-S. Domenica' WHERE id=65461;
UPDATE laus SET name_national=N'Kijevo', name_latin=N'Kijevo', abac_name=N'Kijevo', display_name=N'Kijevo' WHERE id=65462;
UPDATE laus SET name_national=N'Kistanje', name_latin=N'Kistanje', abac_name=N'Kistanje', display_name=N'Kistanje' WHERE id=65463;
UPDATE laus SET name_national=N'Klakar', name_latin=N'Klakar', abac_name=N'Klakar', display_name=N'Klakar' WHERE id=65464;
UPDATE laus SET name_national=N'Klana', name_latin=N'Klana', abac_name=N'Klana', display_name=N'Klana' WHERE id=65465;
UPDATE laus SET name_national=N'Klanjec', name_latin=N'Klanjec', abac_name=N'Klanjec', display_name=N'Klanjec' WHERE id=65466;
UPDATE laus SET name_national=N'Klenovnik', name_latin=N'Klenovnik', abac_name=N'Klenovnik', display_name=N'Klenovnik' WHERE id=65467;
UPDATE laus SET name_national=N'Klinča Sela', name_latin=N'Klinča sela', abac_name=N'Klinca Sela', display_name=N'Klinča Sela' WHERE id=65468;
UPDATE laus SET name_national=N'Klis', name_latin=N'Klis', abac_name=N'Klis', display_name=N'Klis' WHERE id=65469;
UPDATE laus SET name_national=N'Kloštar Ivanić', name_latin=N'Kloštar ivanić', abac_name=N'Klostar Ivanic', display_name=N'Kloštar Ivanić' WHERE id=65470;
UPDATE laus SET name_national=N'Kloštar Podravski', name_latin=N'Kloštar podravski', abac_name=N'Klostar Podravski', display_name=N'Kloštar Podravski' WHERE id=65471;
UPDATE laus SET name_national=N'Kneževi Vinogradi', name_latin=N'Kneževi vinogradi', abac_name=N'Knezevi Vinogradi', display_name=N'Kneževi Vinogradi' WHERE id=65472;
UPDATE laus SET name_national=N'Knin', name_latin=N'Knin', abac_name=N'Knin', display_name=N'Knin' WHERE id=65473;
UPDATE laus SET name_national=N'Kolan', name_latin=N'Kolan', abac_name=N'Kolan', display_name=N'Kolan' WHERE id=65474;
UPDATE laus SET name_national=N'Komiža', name_latin=N'Komiža', abac_name=N'Komiza', display_name=N'Komiža' WHERE id=65475;
UPDATE laus SET name_national=N'Konavle', name_latin=N'Konavle', abac_name=N'Konavle', display_name=N'Konavle' WHERE id=65476;
UPDATE laus SET name_national=N'Končanica', name_latin=N'Končanica', abac_name=N'Koncanica', display_name=N'Končanica' WHERE id=65477;
UPDATE laus SET name_national=N'Konjščina', name_latin=N'Konjščina', abac_name=N'Konjscina', display_name=N'Konjščina' WHERE id=65478;
UPDATE laus SET name_national=N'Koprivnica', name_latin=N'Koprivnica', abac_name=N'Koprivnica', display_name=N'Koprivnica' WHERE id=65479;
UPDATE laus SET name_national=N'Koprivnički Bregi', name_latin=N'Koprivnički bregi', abac_name=N'Koprivnicki Bregi', display_name=N'Koprivnički Bregi' WHERE id=65480;
UPDATE laus SET name_national=N'Koprivnički Ivanec', name_latin=N'Koprivnički ivanec', abac_name=N'Koprivnicki Ivanec', display_name=N'Koprivnički Ivanec' WHERE id=65481;
UPDATE laus SET name_national=N'Korčula', name_latin=N'Korčula', abac_name=N'Korcula', display_name=N'Korčula' WHERE id=65482;
UPDATE laus SET name_national=N'Koška', name_latin=N'Koška', abac_name=N'Koska', display_name=N'Koška' WHERE id=65483;
UPDATE laus SET name_national=N'Kostrena', name_latin=N'Kostrena', abac_name=N'Kostrena', display_name=N'Kostrena' WHERE id=65484;
UPDATE laus SET name_national=N'Kotoriba', name_latin=N'Kotoriba', abac_name=N'Kotoriba', display_name=N'Kotoriba' WHERE id=65485;
UPDATE laus SET name_national=N'Kraljevec Na Sutli', name_latin=N'Kraljevec na sutli', abac_name=N'Kraljevec Na Sutli', display_name=N'Kraljevec Na Sutli' WHERE id=65486;
UPDATE laus SET name_national=N'Kraljevica', name_latin=N'Kraljevica', abac_name=N'Kraljevica', display_name=N'Kraljevica' WHERE id=65487;
UPDATE laus SET name_national=N'Krapina', name_latin=N'Krapina', abac_name=N'Krapina', display_name=N'Krapina' WHERE id=65488;
UPDATE laus SET name_national=N'Krapinske Toplice', name_latin=N'Krapinske toplice', abac_name=N'Krapinske Toplice', display_name=N'Krapinske Toplice' WHERE id=65489;
UPDATE laus SET name_national=N'Krašić', name_latin=N'Krašić', abac_name=N'Krasic', display_name=N'Krašić' WHERE id=65490;
UPDATE laus SET name_national=N'Kravarsko', name_latin=N'Kravarsko', abac_name=N'Kravarsko', display_name=N'Kravarsko' WHERE id=65491;
UPDATE laus SET name_national=N'Križ', name_latin=N'Križ', abac_name=N'Kriz', display_name=N'Križ' WHERE id=65492;
UPDATE laus SET name_national=N'Križevci', name_latin=N'Križevci', abac_name=N'Krizevci', display_name=N'Križevci' WHERE id=65493;
UPDATE laus SET name_national=N'Krk', name_latin=N'Krk', abac_name=N'Krk', display_name=N'Krk' WHERE id=65494;
UPDATE laus SET name_national=N'Krnjak', name_latin=N'Krnjak', abac_name=N'Krnjak', display_name=N'Krnjak' WHERE id=65495;
UPDATE laus SET name_national=N'Kršan', name_latin=N'Kršan', abac_name=N'Krsan', display_name=N'Kršan' WHERE id=65496;
UPDATE laus SET name_national=N'Kukljica', name_latin=N'Kukljica', abac_name=N'Kukljica', display_name=N'Kukljica' WHERE id=65497;
UPDATE laus SET name_national=N'Kula Norinska', name_latin=N'Kula norinska', abac_name=N'Kula Norinska', display_name=N'Kula Norinska' WHERE id=65498;
UPDATE laus SET name_national=N'Kumrovec', name_latin=N'Kumrovec', abac_name=N'Kumrovec', display_name=N'Kumrovec' WHERE id=65499;
UPDATE laus SET name_national=N'Kutina', name_latin=N'Kutina', abac_name=N'Kutina', display_name=N'Kutina' WHERE id=65500;
UPDATE laus SET name_national=N'Kutjevo', name_latin=N'Kutjevo', abac_name=N'Kutjevo', display_name=N'Kutjevo' WHERE id=65501;
UPDATE laus SET name_national=N'Labin', name_latin=N'Labin', abac_name=N'Labin', display_name=N'Labin' WHERE id=65502;
UPDATE laus SET name_national=N'Lanišće', name_latin=N'Lanišće', abac_name=N'Lanisce', display_name=N'Lanišće' WHERE id=65503;
UPDATE laus SET name_national=N'Lasinja', name_latin=N'Lasinja', abac_name=N'Lasinja', display_name=N'Lasinja' WHERE id=65504;
UPDATE laus SET name_national=N'Lastovo', name_latin=N'Lastovo', abac_name=N'Lastovo', display_name=N'Lastovo' WHERE id=65505;
UPDATE laus SET name_national=N'Lećevica', name_latin=N'Lećevica', abac_name=N'Lecevica', display_name=N'Lećevica' WHERE id=65506;
UPDATE laus SET name_national=N'Legrad', name_latin=N'Legrad', abac_name=N'Legrad', display_name=N'Legrad' WHERE id=65507;
UPDATE laus SET name_national=N'Lekenik', name_latin=N'Lekenik', abac_name=N'Lekenik', display_name=N'Lekenik' WHERE id=65508;
UPDATE laus SET name_national=N'Lepoglava', name_latin=N'Lepoglava', abac_name=N'Lepoglava', display_name=N'Lepoglava' WHERE id=65509;
UPDATE laus SET name_national=N'Levanjska Varoš', name_latin=N'Levanjska varoš', abac_name=N'Levanjska Varos', display_name=N'Levanjska Varoš' WHERE id=65510;
UPDATE laus SET name_national=N'Lipik', name_latin=N'Lipik', abac_name=N'Lipik', display_name=N'Lipik' WHERE id=65511;
UPDATE laus SET name_national=N'Lipovljani', name_latin=N'Lipovljani', abac_name=N'Lipovljani', display_name=N'Lipovljani' WHERE id=65512;
UPDATE laus SET name_national=N'Lišane Ostrovičke', name_latin=N'Lišane ostrovičke', abac_name=N'Lisane Ostrovicke', display_name=N'Lišane Ostrovičke' WHERE id=65513;
UPDATE laus SET name_national=N'Ližnjan - Lisignano', name_latin=N'Ližnjan - lisignano', abac_name=N'Liznjan - Lisignano', display_name=N'Ližnjan - Lisignano' WHERE id=65514;
UPDATE laus SET name_national=N'Ljubešćica', name_latin=N'Ljubešćica', abac_name=N'Ljubescica', display_name=N'Ljubešćica' WHERE id=65515;
UPDATE laus SET name_national=N'Lobor', name_latin=N'Lobor', abac_name=N'Lobor', display_name=N'Lobor' WHERE id=65516;
UPDATE laus SET name_national=N'Lokve', name_latin=N'Lokve', abac_name=N'Lokve', display_name=N'Lokve' WHERE id=65517;
UPDATE laus SET name_national=N'Lokvičići', name_latin=N'Lokvičići', abac_name=N'Lokvicici', display_name=N'Lokvičići' WHERE id=65518;
UPDATE laus SET name_national=N'Lopar', name_latin=N'Lopar', abac_name=N'Lopar', display_name=N'Lopar' WHERE id=65519;
UPDATE laus SET name_national=N'Lovas', name_latin=N'Lovas', abac_name=N'Lovas', display_name=N'Lovas' WHERE id=65520;
UPDATE laus SET name_national=N'Lovinac', name_latin=N'Lovinac', abac_name=N'Lovinac', display_name=N'Lovinac' WHERE id=65521;
UPDATE laus SET name_national=N'Lovran', name_latin=N'Lovran', abac_name=N'Lovran', display_name=N'Lovran' WHERE id=65522;
UPDATE laus SET name_national=N'Lovreć', name_latin=N'Lovreć', abac_name=N'Lovrec', display_name=N'Lovreć' WHERE id=65523;
UPDATE laus SET name_national=N'Ludbreg', name_latin=N'Ludbreg', abac_name=N'Ludbreg', display_name=N'Ludbreg' WHERE id=65524;
UPDATE laus SET name_national=N'Luka', name_latin=N'Luka', abac_name=N'Luka', display_name=N'Luka' WHERE id=65525;
UPDATE laus SET name_national=N'Lukač', name_latin=N'Lukač', abac_name=N'Lukac', display_name=N'Lukač' WHERE id=65526;
UPDATE laus SET name_national=N'Lumbarda', name_latin=N'Lumbarda', abac_name=N'Lumbarda', display_name=N'Lumbarda' WHERE id=65527;
UPDATE laus SET name_national=N'Lupoglav', name_latin=N'Lupoglav', abac_name=N'Lupoglav', display_name=N'Lupoglav' WHERE id=65528;
UPDATE laus SET name_national=N'Mače', name_latin=N'Mače', abac_name=N'Mace', display_name=N'Mače' WHERE id=65529;
UPDATE laus SET name_national=N'Magadenovac', name_latin=N'Magadenovac', abac_name=N'Magadenovac', display_name=N'Magadenovac' WHERE id=65530;
UPDATE laus SET name_national=N'Majur', name_latin=N'Majur', abac_name=N'Majur', display_name=N'Majur' WHERE id=65531;
UPDATE laus SET name_national=N'Makarska', name_latin=N'Makarska', abac_name=N'Makarska', display_name=N'Makarska' WHERE id=65532;
UPDATE laus SET name_national=N'Mala Subotica', name_latin=N'Mala subotica', abac_name=N'Mala Subotica', display_name=N'Mala Subotica' WHERE id=65533;
UPDATE laus SET name_national=N'Mali Bukovec', name_latin=N'Mali bukovec', abac_name=N'Mali Bukovec', display_name=N'Mali Bukovec' WHERE id=65534;
UPDATE laus SET name_national=N'Mali Lošinj', name_latin=N'Mali lošinj', abac_name=N'Mali Losinj', display_name=N'Mali Lošinj' WHERE id=65535;
UPDATE laus SET name_national=N'Malinska-Dubašnica', name_latin=N'Malinska-dubašnica', abac_name=N'Malinska-Dubasnica', display_name=N'Malinska-Dubašnica' WHERE id=65536;
UPDATE laus SET name_national=N'Marčana', name_latin=N'Marčana', abac_name=N'Marcana', display_name=N'Marčana' WHERE id=65537;
UPDATE laus SET name_national=N'Marija Bistrica', name_latin=N'Marija bistrica', abac_name=N'Marija Bistrica', display_name=N'Marija Bistrica' WHERE id=65538;
UPDATE laus SET name_national=N'Marija Gorica', name_latin=N'Marija gorica', abac_name=N'Marija Gorica', display_name=N'Marija Gorica' WHERE id=65539;
UPDATE laus SET name_national=N'Marijanci', name_latin=N'Marijanci', abac_name=N'Marijanci', display_name=N'Marijanci' WHERE id=65540;
UPDATE laus SET name_national=N'Marina', name_latin=N'Marina', abac_name=N'Marina', display_name=N'Marina' WHERE id=65541;
UPDATE laus SET name_national=N'Markušica', name_latin=N'Markušica', abac_name=N'Markusica', display_name=N'Markušica' WHERE id=65542;
UPDATE laus SET name_national=N'Martijanec', name_latin=N'Martijanec', abac_name=N'Martijanec', display_name=N'Martijanec' WHERE id=65543;
UPDATE laus SET name_national=N'Martinska Ves', name_latin=N'Martinska ves', abac_name=N'Martinska Ves', display_name=N'Martinska Ves' WHERE id=65544;
UPDATE laus SET name_national=N'Maruševec', name_latin=N'Maruševec', abac_name=N'Marusevec', display_name=N'Maruševec' WHERE id=65545;
UPDATE laus SET name_national=N'Matulji', name_latin=N'Matulji', abac_name=N'Matulji', display_name=N'Matulji' WHERE id=65546;
UPDATE laus SET name_national=N'Medulin', name_latin=N'Medulin', abac_name=N'Medulin', display_name=N'Medulin' WHERE id=65547;
UPDATE laus SET name_national=N'Metković', name_latin=N'Metković', abac_name=N'Metkovic', display_name=N'Metković' WHERE id=65548;
UPDATE laus SET name_national=N'Mihovljan', name_latin=N'Mihovljan', abac_name=N'Mihovljan', display_name=N'Mihovljan' WHERE id=65549;
UPDATE laus SET name_national=N'Mikleuš', name_latin=N'Mikleuš', abac_name=N'Mikleus', display_name=N'Mikleuš' WHERE id=65550;
UPDATE laus SET name_national=N'Milna', name_latin=N'Milna', abac_name=N'Milna', display_name=N'Milna' WHERE id=65551;
UPDATE laus SET name_national=N'Mljet', name_latin=N'Mljet', abac_name=N'Mljet', display_name=N'Mljet' WHERE id=65552;
UPDATE laus SET name_national=N'Molve', name_latin=N'Molve', abac_name=N'Molve', display_name=N'Molve' WHERE id=65553;
UPDATE laus SET name_national=N'Mošćenička Draga', name_latin=N'Mošćenička draga', abac_name=N'Moscenicka Draga', display_name=N'Mošćenička Draga' WHERE id=65554;
UPDATE laus SET name_national=N'Motovun - Montona', name_latin=N'Motovun - montona', abac_name=N'Motovun - Montona', display_name=N'Motovun - Montona' WHERE id=65555;
UPDATE laus SET name_national=N'Mrkopalj', name_latin=N'Mrkopalj', abac_name=N'Mrkopalj', display_name=N'Mrkopalj' WHERE id=65556;
UPDATE laus SET name_national=N'Muć', name_latin=N'Muć', abac_name=N'Muc', display_name=N'Muć' WHERE id=65557;
UPDATE laus SET name_national=N'Mursko-Središće', name_latin=N'Mursko središće', abac_name=N'Mursko-Sredisce', display_name=N'Mursko-Središće' WHERE id=65558;
UPDATE laus SET name_national=N'Murter - Kornati', name_latin=N'Murter - kornati', abac_name=N'Murter - Kornati', display_name=N'Murter - Kornati' WHERE id=65559;
UPDATE laus SET name_national=N'Našice', name_latin=N'Našice', abac_name=N'Nasice', display_name=N'Našice' WHERE id=65560;
UPDATE laus SET name_national=N'Nedelišće', name_latin=N'Nedelišće', abac_name=N'Nedelisce', display_name=N'Nedelišće' WHERE id=65561;
UPDATE laus SET name_national=N'Negoslavci', name_latin=N'Negoslavci', abac_name=N'Negoslavci', display_name=N'Negoslavci' WHERE id=65562;
UPDATE laus SET name_national=N'Nerežišća', name_latin=N'Nerežišća', abac_name=N'Nerezisca', display_name=N'Nerežišća' WHERE id=65563;
UPDATE laus SET name_national=N'Netretić', name_latin=N'Netretić', abac_name=N'Netretic', display_name=N'Netretić' WHERE id=65564;
UPDATE laus SET name_national=N'Nijemci', name_latin=N'Nijemci', abac_name=N'Nijemci', display_name=N'Nijemci' WHERE id=65565;
UPDATE laus SET name_national=N'Nin', name_latin=N'Nin', abac_name=N'Nin', display_name=N'Nin' WHERE id=65566;
UPDATE laus SET name_national=N'Nova Bukovica', name_latin=N'Nova bukovica', abac_name=N'Nova Bukovica', display_name=N'Nova Bukovica' WHERE id=65567;
UPDATE laus SET name_national=N'Nova Gradiška', name_latin=N'Nova gradiška', abac_name=N'Nova Gradiska', display_name=N'Nova Gradiška' WHERE id=65568;
UPDATE laus SET name_national=N'Nova Kapela', name_latin=N'Nova kapela', abac_name=N'Nova Kapela', display_name=N'Nova Kapela' WHERE id=65569;
UPDATE laus SET name_national=N'Nova Rača', name_latin=N'Nova rača', abac_name=N'Nova Raca', display_name=N'Nova Rača' WHERE id=65570;
UPDATE laus SET name_national=N'Novalja', name_latin=N'Novalja', abac_name=N'Novalja', display_name=N'Novalja' WHERE id=65571;
UPDATE laus SET name_national=N'Novi Golubovec', name_latin=N'Novi golubovec', abac_name=N'Novi Golubovec', display_name=N'Novi Golubovec' WHERE id=65572;
UPDATE laus SET name_national=N'Novi Marof', name_latin=N'Novi marof', abac_name=N'Novi Marof', display_name=N'Novi Marof' WHERE id=65573;
UPDATE laus SET name_national=N'Novi Vinodolski', name_latin=N'Novi vinodolski', abac_name=N'Novi Vinodolski', display_name=N'Novi Vinodolski' WHERE id=65574;
UPDATE laus SET name_national=N'Novigrad', name_latin=N'Novigrad', abac_name=N'Novigrad', display_name=N'Novigrad' WHERE id=65575;
UPDATE laus SET name_national=N'Novigrad Podravski', name_latin=N'Novigrad - cittanova', abac_name=N'Novigrad Podravski', display_name=N'Novigrad Podravski' WHERE id=65576;
UPDATE laus SET name_national=N'Novigrad-Cittanova', name_latin=N'Novigrad podravski', abac_name=N'Novigrad-Cittanova', display_name=N'Novigrad-Cittanova' WHERE id=65577;
UPDATE laus SET name_national=N'Novo Virje', name_latin=N'Novo virje', abac_name=N'Novo Virje', display_name=N'Novo Virje' WHERE id=65578;
UPDATE laus SET name_national=N'Novska', name_latin=N'Novska', abac_name=N'Novska', display_name=N'Novska' WHERE id=65579;
UPDATE laus SET name_national=N'Nuštar', name_latin=N'Nuštar', abac_name=N'Nustar', display_name=N'Nuštar' WHERE id=65580;
UPDATE laus SET name_national=N'Obrovac', name_latin=N'Obrovac', abac_name=N'Obrovac', display_name=N'Obrovac' WHERE id=65581;
UPDATE laus SET name_national=N'Ogulin', name_latin=N'Ogulin', abac_name=N'Ogulin', display_name=N'Ogulin' WHERE id=65582;
UPDATE laus SET name_national=N'Okrug', name_latin=N'Okrug', abac_name=N'Okrug', display_name=N'Okrug' WHERE id=65583;
UPDATE laus SET name_national=N'Okučani', name_latin=N'Okučani', abac_name=N'Okucani', display_name=N'Okučani' WHERE id=65584;
UPDATE laus SET name_national=N'Omiš', name_latin=N'Omiš', abac_name=N'Omis', display_name=N'Omiš' WHERE id=65585;
UPDATE laus SET name_national=N'Omišalj', name_latin=N'Omišalj', abac_name=N'Omisalj', display_name=N'Omišalj' WHERE id=65586;
UPDATE laus SET name_national=N'Opatija', name_latin=N'Opatija', abac_name=N'Opatija', display_name=N'Opatija' WHERE id=65587;
UPDATE laus SET name_national=N'Oprisavci', name_latin=N'Oprisavci', abac_name=N'Oprisavci', display_name=N'Oprisavci' WHERE id=65588;
UPDATE laus SET name_national=N'Oprtalj - Portole', name_latin=N'Oprtalj - portole', abac_name=N'Oprtalj - Portole', display_name=N'Oprtalj - Portole' WHERE id=65589;
UPDATE laus SET name_national=N'Opuzen', name_latin=N'Opuzen', abac_name=N'Opuzen', display_name=N'Opuzen' WHERE id=65590;
UPDATE laus SET name_national=N'Orahovica', name_latin=N'Orahovica', abac_name=N'Orahovica', display_name=N'Orahovica' WHERE id=65591;
UPDATE laus SET name_national=N'Orebić', name_latin=N'Orebić', abac_name=N'Orebic', display_name=N'Orebić' WHERE id=65592;
UPDATE laus SET name_national=N'Orehovica', name_latin=N'Orehovica', abac_name=N'Orehovica', display_name=N'Orehovica' WHERE id=65593;
UPDATE laus SET name_national=N'Oriovac', name_latin=N'Oriovac', abac_name=N'Oriovac', display_name=N'Oriovac' WHERE id=65594;
UPDATE laus SET name_national=N'Orle', name_latin=N'Orle', abac_name=N'Orle', display_name=N'Orle' WHERE id=65595;
UPDATE laus SET name_national=N'Oroslavje', name_latin=N'Oroslavje', abac_name=N'Oroslavje', display_name=N'Oroslavje' WHERE id=65596;
UPDATE laus SET name_national=N'Osijek', name_latin=N'Osijek', abac_name=N'Osijek', display_name=N'Osijek' WHERE id=65597;
UPDATE laus SET name_national=N'Otočac', name_latin=N'Otočac', abac_name=N'Otocac', display_name=N'Otočac' WHERE id=65598;
UPDATE laus SET name_national=N'Otok (Splitsko-dalmatinska županija)', name_latin=N'Otok (Splitsko-dalmatinska županija)', abac_name=N'Otok (Splitsko-dalmatinska zupanija)', display_name=N'Otok (Splitsko-dalmatinska županija)' WHERE id=65599;
UPDATE laus SET name_national=N'Otok (Vukovarsko-srijemska županija)', name_latin=N'Otok (Vukovarsko-srijemska županija)', abac_name=N'Otok (Vukovarsko-srijemska zupanija)', display_name=N'Otok (Vukovarsko-srijemska županija)' WHERE id=65600;
UPDATE laus SET name_national=N'Ozalj', name_latin=N'Ozalj', abac_name=N'Ozalj', display_name=N'Ozalj' WHERE id=65601;
UPDATE laus SET name_national=N'Pag', name_latin=N'Pag', abac_name=N'Pag', display_name=N'Pag' WHERE id=65602;
UPDATE laus SET name_national=N'Pakoštane', name_latin=N'Pakoštane', abac_name=N'Pakostane', display_name=N'Pakoštane' WHERE id=65603;
UPDATE laus SET name_national=N'Pakrac', name_latin=N'Pakrac', abac_name=N'Pakrac', display_name=N'Pakrac' WHERE id=65604;
UPDATE laus SET name_national=N'Pašman', name_latin=N'Pašman', abac_name=N'Pasman', display_name=N'Pašman' WHERE id=65605;
UPDATE laus SET name_national=N'Pazin', name_latin=N'Pazin', abac_name=N'Pazin', display_name=N'Pazin' WHERE id=65606;
UPDATE laus SET name_national=N'Perušić', name_latin=N'Perušić', abac_name=N'Perusic', display_name=N'Perušić' WHERE id=65607;
UPDATE laus SET name_national=N'Peteranec', name_latin=N'Peteranec', abac_name=N'Peteranec', display_name=N'Peteranec' WHERE id=65608;
UPDATE laus SET name_national=N'Petlovac', name_latin=N'Petlovac', abac_name=N'Petlovac', display_name=N'Petlovac' WHERE id=65609;
UPDATE laus SET name_national=N'Petrijanec', name_latin=N'Petrijanec', abac_name=N'Petrijanec', display_name=N'Petrijanec' WHERE id=65610;
UPDATE laus SET name_national=N'Petrijevci', name_latin=N'Petrijevci', abac_name=N'Petrijevci', display_name=N'Petrijevci' WHERE id=65611;
UPDATE laus SET name_national=N'Petrinja', name_latin=N'Petrinja', abac_name=N'Petrinja', display_name=N'Petrinja' WHERE id=65612;
UPDATE laus SET name_national=N'Petrovsko', name_latin=N'Petrovsko', abac_name=N'Petrovsko', display_name=N'Petrovsko' WHERE id=65613;
UPDATE laus SET name_national=N'Pićan', name_latin=N'Pićan', abac_name=N'Pican', display_name=N'Pićan' WHERE id=65614;
UPDATE laus SET name_national=N'Pirovac', name_latin=N'Pirovac', abac_name=N'Pirovac', display_name=N'Pirovac' WHERE id=65615;
UPDATE laus SET name_national=N'Pisarovina', name_latin=N'Pisarovina', abac_name=N'Pisarovina', display_name=N'Pisarovina' WHERE id=65616;
UPDATE laus SET name_national=N'Pitomača', name_latin=N'Pitomača', abac_name=N'Pitomaca', display_name=N'Pitomača' WHERE id=65617;
UPDATE laus SET name_national=N'Plaški', name_latin=N'Plaški', abac_name=N'Plaski', display_name=N'Plaški' WHERE id=65618;
UPDATE laus SET name_national=N'Pleternica', name_latin=N'Pleternica', abac_name=N'Pleternica', display_name=N'Pleternica' WHERE id=65619;
UPDATE laus SET name_national=N'Plitvička Jezera', name_latin=N'Plitvička jezera', abac_name=N'Plitvicka Jezera', display_name=N'Plitvička Jezera' WHERE id=65620;
UPDATE laus SET name_national=N'Ploče', name_latin=N'Ploče', abac_name=N'Ploce', display_name=N'Ploče' WHERE id=65621;
UPDATE laus SET name_national=N'Podbablje', name_latin=N'Podbablje', abac_name=N'Podbablje', display_name=N'Podbablje' WHERE id=65622;
UPDATE laus SET name_national=N'Podcrkavlje', name_latin=N'Podcrkavlje', abac_name=N'Podcrkavlje', display_name=N'Podcrkavlje' WHERE id=65623;
UPDATE laus SET name_national=N'Podgora', name_latin=N'Podgora', abac_name=N'Podgora', display_name=N'Podgora' WHERE id=65624;
UPDATE laus SET name_national=N'Podgorač', name_latin=N'Podgorač', abac_name=N'Podgorac', display_name=N'Podgorač' WHERE id=65625;
UPDATE laus SET name_national=N'Podravska Moslavina', name_latin=N'Podravska moslavina', abac_name=N'Podravska Moslavina', display_name=N'Podravska Moslavina' WHERE id=65626;
UPDATE laus SET name_national=N'Podravske Sesvete', name_latin=N'Podravske sesvete', abac_name=N'Podravske Sesvete', display_name=N'Podravske Sesvete' WHERE id=65627;
UPDATE laus SET name_national=N'Podstrana', name_latin=N'Podstrana', abac_name=N'Podstrana', display_name=N'Podstrana' WHERE id=65628;
UPDATE laus SET name_national=N'Podturen', name_latin=N'Podturen', abac_name=N'Podturen', display_name=N'Podturen' WHERE id=65629;
UPDATE laus SET name_national=N'Pojezerje', name_latin=N'Pojezerje', abac_name=N'Pojezerje', display_name=N'Pojezerje' WHERE id=65630;
UPDATE laus SET name_national=N'Pokupsko', name_latin=N'Pokupsko', abac_name=N'Pokupsko', display_name=N'Pokupsko' WHERE id=65631;
UPDATE laus SET name_national=N'Polača', name_latin=N'Polača', abac_name=N'Polaca', display_name=N'Polača' WHERE id=65632;
UPDATE laus SET name_national=N'Poličnik', name_latin=N'Poličnik', abac_name=N'Policnik', display_name=N'Poličnik' WHERE id=65633;
UPDATE laus SET name_national=N'Popovac', name_latin=N'Popovac', abac_name=N'Popovac', display_name=N'Popovac' WHERE id=65634;
UPDATE laus SET name_national=N'Popovača', name_latin=N'Popovača', abac_name=N'Popovaca', display_name=N'Popovača' WHERE id=65635;
UPDATE laus SET name_national=N'Poreč - Parenzo', name_latin=N'Poreč - parenzo', abac_name=N'Porec - Parenzo', display_name=N'Poreč - Parenzo' WHERE id=65636;
UPDATE laus SET name_national=N'Posedarje', name_latin=N'Posedarje', abac_name=N'Posedarje', display_name=N'Posedarje' WHERE id=65637;
UPDATE laus SET name_national=N'Postira', name_latin=N'Postira', abac_name=N'Postira', display_name=N'Postira' WHERE id=65638;
UPDATE laus SET name_national=N'Povljana', name_latin=N'Povljana', abac_name=N'Povljana', display_name=N'Povljana' WHERE id=65639;
UPDATE laus SET name_national=N'Požega', name_latin=N'Požega', abac_name=N'Pozega', display_name=N'Požega' WHERE id=65640;
UPDATE laus SET name_national=N'Pregrada', name_latin=N'Pregrada', abac_name=N'Pregrada', display_name=N'Pregrada' WHERE id=65641;
UPDATE laus SET name_national=N'Preko', name_latin=N'Preko', abac_name=N'Preko', display_name=N'Preko' WHERE id=65642;
UPDATE laus SET name_national=N'Prelog', name_latin=N'Prelog', abac_name=N'Prelog', display_name=N'Prelog' WHERE id=65643;
UPDATE laus SET name_national=N'Preseka', name_latin=N'Preseka', abac_name=N'Preseka', display_name=N'Preseka' WHERE id=65644;
UPDATE laus SET name_national=N'Prgomet', name_latin=N'Prgomet', abac_name=N'Prgomet', display_name=N'Prgomet' WHERE id=65645;
UPDATE laus SET name_national=N'Pribislavec', name_latin=N'Pribislavec', abac_name=N'Pribislavec', display_name=N'Pribislavec' WHERE id=65646;
UPDATE laus SET name_national=N'Primorski Dolac', name_latin=N'Primorski dolac', abac_name=N'Primorski Dolac', display_name=N'Primorski Dolac' WHERE id=65647;
UPDATE laus SET name_national=N'Primošten', name_latin=N'Primošten', abac_name=N'Primosten', display_name=N'Primošten' WHERE id=65648;
UPDATE laus SET name_national=N'Privlaka (Vukovarsko-srijemska županija)', name_latin=N'Privlaka (Vukovarsko-srijemska županija)', abac_name=N'Privlaka (Vukovarsko-srijemska zupanija)', display_name=N'Privlaka (Vukovarsko-srijemska županija)' WHERE id=65650;
UPDATE laus SET name_national=N'Privlaka (Zadarska županija)', name_latin=N'Privlaka (Zadarska županija)', abac_name=N'Privlaka (Zadarska zupanija)', display_name=N'Privlaka (Zadarska županija)' WHERE id=65649;
UPDATE laus SET name_national=N'Proložac', name_latin=N'Proložac', abac_name=N'Prolozac', display_name=N'Proložac' WHERE id=65651;
UPDATE laus SET name_national=N'Promina', name_latin=N'Promina', abac_name=N'Promina', display_name=N'Promina' WHERE id=65652;
UPDATE laus SET name_national=N'Pučišća', name_latin=N'Pučišća', abac_name=N'Pucisca', display_name=N'Pučišća' WHERE id=65653;
UPDATE laus SET name_national=N'Pula - Pola', name_latin=N'Pula - pola', abac_name=N'Pula - Pola', display_name=N'Pula - Pola' WHERE id=65654;
UPDATE laus SET name_national=N'Punat', name_latin=N'Punat', abac_name=N'Punat', display_name=N'Punat' WHERE id=65655;
UPDATE laus SET name_national=N'Punitovci', name_latin=N'Punitovci', abac_name=N'Punitovci', display_name=N'Punitovci' WHERE id=65656;
UPDATE laus SET name_national=N'Pušća', name_latin=N'Pušća', abac_name=N'Pusca', display_name=N'Pušća' WHERE id=65657;
UPDATE laus SET name_national=N'Rab', name_latin=N'Rab', abac_name=N'Rab', display_name=N'Rab' WHERE id=65658;
UPDATE laus SET name_national=N'Radoboj', name_latin=N'Radoboj', abac_name=N'Radoboj', display_name=N'Radoboj' WHERE id=65659;
UPDATE laus SET name_national=N'Rakovec', name_latin=N'Rakovec', abac_name=N'Rakovec', display_name=N'Rakovec' WHERE id=65660;
UPDATE laus SET name_national=N'Rakovica', name_latin=N'Rakovica', abac_name=N'Rakovica', display_name=N'Rakovica' WHERE id=65661;
UPDATE laus SET name_national=N'Raša', name_latin=N'Raša', abac_name=N'Rasa', display_name=N'Raša' WHERE id=65662;
UPDATE laus SET name_national=N'Rasinja', name_latin=N'Rasinja', abac_name=N'Rasinja', display_name=N'Rasinja' WHERE id=65663;
UPDATE laus SET name_national=N'Ravna Gora', name_latin=N'Ravna gora', abac_name=N'Ravna Gora', display_name=N'Ravna Gora' WHERE id=65664;
UPDATE laus SET name_national=N'Ražanac', name_latin=N'Ražanac', abac_name=N'Razanac', display_name=N'Ražanac' WHERE id=65665;
UPDATE laus SET name_national=N'Rešetari', name_latin=N'Rešetari', abac_name=N'Resetari', display_name=N'Rešetari' WHERE id=65666;
UPDATE laus SET name_national=N'Ribnik', name_latin=N'Ribnik', abac_name=N'Ribnik', display_name=N'Ribnik' WHERE id=65667;
UPDATE laus SET name_national=N'Rijeka', name_latin=N'Rijeka', abac_name=N'Rijeka', display_name=N'Rijeka' WHERE id=65668;
UPDATE laus SET name_national=N'Rogoznica', name_latin=N'Rogoznica', abac_name=N'Rogoznica', display_name=N'Rogoznica' WHERE id=65669;
UPDATE laus SET name_national=N'Rovinj', name_latin=N'Rovinj - rovigno', abac_name=N'Rovinj', display_name=N'Rovinj' WHERE id=65670;
UPDATE laus SET name_national=N'Rovišće', name_latin=N'Rovišće', abac_name=N'Rovisce', display_name=N'Rovišće' WHERE id=65671;
UPDATE laus SET name_national=N'Rugvica', name_latin=N'Rugvica', abac_name=N'Rugvica', display_name=N'Rugvica' WHERE id=65672;
UPDATE laus SET name_national=N'Runovići', name_latin=N'Runovići', abac_name=N'Runovici', display_name=N'Runovići' WHERE id=65673;
UPDATE laus SET name_national=N'Ružić', name_latin=N'Ružić', abac_name=N'Ruzic', display_name=N'Ružić' WHERE id=65674;
UPDATE laus SET name_national=N'Saborsko', name_latin=N'Saborsko', abac_name=N'Saborsko', display_name=N'Saborsko' WHERE id=65675;
UPDATE laus SET name_national=N'Sali', name_latin=N'Sali', abac_name=N'Sali', display_name=N'Sali' WHERE id=65676;
UPDATE laus SET name_national=N'Samobor', name_latin=N'Samobor', abac_name=N'Samobor', display_name=N'Samobor' WHERE id=65677;
UPDATE laus SET name_national=N'Šandrovac', name_latin=N'Šandrovac', abac_name=N'Sandrovac', display_name=N'Šandrovac' WHERE id=65678;
UPDATE laus SET name_national=N'Satnica Đakovačka', name_latin=N'Satnica đakovačka', abac_name=N'Satnica Dakovacka', display_name=N'Satnica Đakovačka' WHERE id=65679;
UPDATE laus SET name_national=N'Seget', name_latin=N'Seget', abac_name=N'Seget', display_name=N'Seget' WHERE id=65680;
UPDATE laus SET name_national=N'Selca', name_latin=N'Selca', abac_name=N'Selca', display_name=N'Selca' WHERE id=65681;
UPDATE laus SET name_national=N'Selnica', name_latin=N'Selnica', abac_name=N'Selnica', display_name=N'Selnica' WHERE id=65682;
UPDATE laus SET name_national=N'Semeljci', name_latin=N'Semeljci', abac_name=N'Semeljci', display_name=N'Semeljci' WHERE id=65683;
UPDATE laus SET name_national=N'Senj', name_latin=N'Senj', abac_name=N'Senj', display_name=N'Senj' WHERE id=65684;
UPDATE laus SET name_national=N'Šenkovec', name_latin=N'Šenkovec', abac_name=N'Senkovec', display_name=N'Šenkovec' WHERE id=65685;
UPDATE laus SET name_national=N'Šestanovac', name_latin=N'Šestanovac', abac_name=N'Sestanovac', display_name=N'Šestanovac' WHERE id=65686;
UPDATE laus SET name_national=N'Severin', name_latin=N'Severin', abac_name=N'Severin', display_name=N'Severin' WHERE id=65687;
UPDATE laus SET name_national=N'Šibenik', name_latin=N'Šibenik', abac_name=N'Sibenik', display_name=N'Šibenik' WHERE id=65688;
UPDATE laus SET name_national=N'Sibinj', name_latin=N'Sibinj', abac_name=N'Sibinj', display_name=N'Sibinj' WHERE id=65689;
UPDATE laus SET name_national=N'Sikirevci', name_latin=N'Sikirevci', abac_name=N'Sikirevci', display_name=N'Sikirevci' WHERE id=65690;
UPDATE laus SET name_national=N'Sinj', name_latin=N'Sinj', abac_name=N'Sinj', display_name=N'Sinj' WHERE id=65691;
UPDATE laus SET name_national=N'Sirač', name_latin=N'Sirač', abac_name=N'Sirac', display_name=N'Sirač' WHERE id=65692;
UPDATE laus SET name_national=N'Sisak', name_latin=N'Sisak', abac_name=N'Sisak', display_name=N'Sisak' WHERE id=65693;
UPDATE laus SET name_national=N'Škabrnja', name_latin=N'Škabrnja', abac_name=N'Skabrnja', display_name=N'Škabrnja' WHERE id=65694;
UPDATE laus SET name_national=N'Skrad', name_latin=N'Skrad', abac_name=N'Skrad', display_name=N'Skrad' WHERE id=65695;
UPDATE laus SET name_national=N'Skradin', name_latin=N'Skradin', abac_name=N'Skradin', display_name=N'Skradin' WHERE id=65696;
UPDATE laus SET name_national=N'Slatina', name_latin=N'Slatina', abac_name=N'Slatina', display_name=N'Slatina' WHERE id=65697;
UPDATE laus SET name_national=N'Slavonski Brod', name_latin=N'Slavonski brod', abac_name=N'Slavonski Brod', display_name=N'Slavonski Brod' WHERE id=65698;
UPDATE laus SET name_national=N'Slavonski Šamac', name_latin=N'Slavonski šamac', abac_name=N'Slavonski Samac', display_name=N'Slavonski Šamac' WHERE id=65699;
UPDATE laus SET name_national=N'Slivno', name_latin=N'Slivno', abac_name=N'Slivno', display_name=N'Slivno' WHERE id=65700;
UPDATE laus SET name_national=N'Slunj', name_latin=N'Slunj', abac_name=N'Slunj', display_name=N'Slunj' WHERE id=65701;
UPDATE laus SET name_national=N'Smokvica', name_latin=N'Smokvica', abac_name=N'Smokvica', display_name=N'Smokvica' WHERE id=65702;
UPDATE laus SET name_national=N'Šodolovci', name_latin=N'Šodolovci', abac_name=N'Sodolovci', display_name=N'Šodolovci' WHERE id=65703;
UPDATE laus SET name_national=N'Sokolovac', name_latin=N'Sokolovac', abac_name=N'Sokolovac', display_name=N'Sokolovac' WHERE id=65704;
UPDATE laus SET name_national=N'Solin', name_latin=N'Solin', abac_name=N'Solin', display_name=N'Solin' WHERE id=65705;
UPDATE laus SET name_national=N'Šolta', name_latin=N'Šolta', abac_name=N'Solta', display_name=N'Šolta' WHERE id=65706;
UPDATE laus SET name_national=N'Sopje', name_latin=N'Sopje', abac_name=N'Sopje', display_name=N'Sopje' WHERE id=65707;
UPDATE laus SET name_national=N'Špišić Bukovica', name_latin=N'Špišić bukovica', abac_name=N'Spisic Bukovica', display_name=N'Špišić Bukovica' WHERE id=65708;
UPDATE laus SET name_national=N'Split', name_latin=N'Split', abac_name=N'Split', display_name=N'Split' WHERE id=65709;
UPDATE laus SET name_national=N'Sračinec', name_latin=N'Sračinec', abac_name=N'Sracinec', display_name=N'Sračinec' WHERE id=65710;
UPDATE laus SET name_national=N'Stankovci', name_latin=N'Stankovci', abac_name=N'Stankovci', display_name=N'Stankovci' WHERE id=65711;
UPDATE laus SET name_national=N'Stara Gradiška', name_latin=N'Stara gradiška', abac_name=N'Stara Gradiska', display_name=N'Stara Gradiška' WHERE id=65712;
UPDATE laus SET name_national=N'Stari Grad', name_latin=N'Stari grad', abac_name=N'Stari Grad', display_name=N'Stari Grad' WHERE id=65713;
UPDATE laus SET name_national=N'Stari Jankovci', name_latin=N'Stari jankovci', abac_name=N'Stari Jankovci', display_name=N'Stari Jankovci' WHERE id=65714;
UPDATE laus SET name_national=N'Stari Mikanovci', name_latin=N'Stari mikanovci', abac_name=N'Stari Mikanovci', display_name=N'Stari Mikanovci' WHERE id=65715;
UPDATE laus SET name_national=N'Starigrad', name_latin=N'Starigrad', abac_name=N'Starigrad', display_name=N'Starigrad' WHERE id=65716;
UPDATE laus SET name_national=N'Staro Petrovo Selo', name_latin=N'Staro petrovo selo', abac_name=N'Staro Petrovo Selo', display_name=N'Staro Petrovo Selo' WHERE id=65717;
UPDATE laus SET name_national=N'Štefanje', name_latin=N'Štefanje', abac_name=N'Stefanje', display_name=N'Štefanje' WHERE id=65718;
UPDATE laus SET name_national=N'Štitar', name_latin=N'Štitar', abac_name=N'Stitar', display_name=N'Štitar' WHERE id=65719;
UPDATE laus SET name_national=N'Ston', name_latin=N'Ston', abac_name=N'Ston', display_name=N'Ston' WHERE id=65720;
UPDATE laus SET name_national=N'Strahoninec', name_latin=N'Strahoninec', abac_name=N'Strahoninec', display_name=N'Strahoninec' WHERE id=65721;
UPDATE laus SET name_national=N'Štrigova', name_latin=N'Štrigova', abac_name=N'Strigova', display_name=N'Štrigova' WHERE id=65722;
UPDATE laus SET name_national=N'Strizivojna', name_latin=N'Strizivojna', abac_name=N'Strizivojna', display_name=N'Strizivojna' WHERE id=65723;
UPDATE laus SET name_national=N'Stubičke Toplice', name_latin=N'Stubičke toplice', abac_name=N'Stubicke Toplice', display_name=N'Stubičke Toplice' WHERE id=65724;
UPDATE laus SET name_national=N'Stupnik', name_latin=N'Stupnik', abac_name=N'Stupnik', display_name=N'Stupnik' WHERE id=65725;
UPDATE laus SET name_national=N'Sućuraj', name_latin=N'Sućuraj', abac_name=N'Sucuraj', display_name=N'Sućuraj' WHERE id=65726;
UPDATE laus SET name_national=N'Suhopolje', name_latin=N'Suhopolje', abac_name=N'Suhopolje', display_name=N'Suhopolje' WHERE id=65727;
UPDATE laus SET name_national=N'Sukošan', name_latin=N'Sukošan', abac_name=N'Sukosan', display_name=N'Sukošan' WHERE id=65728;
UPDATE laus SET name_national=N'Sunja', name_latin=N'Sunja', abac_name=N'Sunja', display_name=N'Sunja' WHERE id=65729;
UPDATE laus SET name_national=N'Supetar', name_latin=N'Supetar', abac_name=N'Supetar', display_name=N'Supetar' WHERE id=65730;
UPDATE laus SET name_national=N'Sutivan', name_latin=N'Sutivan', abac_name=N'Sutivan', display_name=N'Sutivan' WHERE id=65731;
UPDATE laus SET name_national=N'Sveta Marija', name_latin=N'Sveta marija', abac_name=N'Sveta Marija', display_name=N'Sveta Marija' WHERE id=65732;
UPDATE laus SET name_national=N'Sveta Nedelja (Istarska županija)', name_latin=N'Sveta Nedelja (Istarska županija)', abac_name=N'Sveta Nedelja (Istarska zupanija)', display_name=N'Sveta Nedelja (Istarska županija)' WHERE id=65733;
UPDATE laus SET name_national=N'Sveta Nedelja (Zagrebačka županija)', name_latin=N'Sveta Nedelja (Zagrebačka županija)', abac_name=N'Sveta Nedelja (Zagrebacka zupanija)', display_name=N'Sveta Nedelja (Zagrebačka županija)' WHERE id=65734;
UPDATE laus SET name_national=N'Sveti Đurđ', name_latin=N'Sveti đurđ', abac_name=N'Sveti Durd', display_name=N'Sveti Đurđ' WHERE id=65735;
UPDATE laus SET name_national=N'Sveti Filip I Jakov', name_latin=N'Sveti filip i jakov', abac_name=N'Sveti Filip I Jakov', display_name=N'Sveti Filip I Jakov' WHERE id=65736;
UPDATE laus SET name_national=N'Sveti Ilija', name_latin=N'Sveti ilija', abac_name=N'Sveti Ilija', display_name=N'Sveti Ilija' WHERE id=65737;
UPDATE laus SET name_national=N'Sveti Ivan Žabno', name_latin=N'Sveti ivan žabno', abac_name=N'Sveti Ivan Zabno', display_name=N'Sveti Ivan Žabno' WHERE id=65738;
UPDATE laus SET name_national=N'Sveti Ivan Zelina', name_latin=N'Sveti ivan zelina', abac_name=N'Sveti Ivan Zelina', display_name=N'Sveti Ivan Zelina' WHERE id=65739;
UPDATE laus SET name_national=N'Sveti Juraj Na Bregu', name_latin=N'Sveti juraj na bregu', abac_name=N'Sveti Juraj Na Bregu', display_name=N'Sveti Juraj Na Bregu' WHERE id=65740;
UPDATE laus SET name_national=N'Sveti Križ Začretje', name_latin=N'Sveti križ začretje', abac_name=N'Sveti Kriz Zacretje', display_name=N'Sveti Križ Začretje' WHERE id=65741;
UPDATE laus SET name_national=N'Sveti Lovreč', name_latin=N'Sveti lovreč', abac_name=N'Sveti Lovrec', display_name=N'Sveti Lovreč' WHERE id=65742;
UPDATE laus SET name_national=N'Sveti Martin Na Muri', name_latin=N'Sveti martin na muri', abac_name=N'Sveti Martin Na Muri', display_name=N'Sveti Martin Na Muri' WHERE id=65743;
UPDATE laus SET name_national=N'Sveti Petar Orehovec', name_latin=N'Sveti petar orehovec', abac_name=N'Sveti Petar Orehovec', display_name=N'Sveti Petar Orehovec' WHERE id=65744;
UPDATE laus SET name_national=N'Sveti Petar U Šumi', name_latin=N'Sveti petar u šumi', abac_name=N'Sveti Petar U Sumi', display_name=N'Sveti Petar U Šumi' WHERE id=65745;
UPDATE laus SET name_national=N'Svetvinčenat', name_latin=N'Svetvinčenat', abac_name=N'Svetvincenat', display_name=N'Svetvinčenat' WHERE id=65746;
UPDATE laus SET name_national=N'Tar-Vabriga - Torre-Abrega', name_latin=N'Tar-vabriga - torre-abrega', abac_name=N'Tar-Vabriga - Torre-Abrega', display_name=N'Tar-Vabriga - Torre-Abrega' WHERE id=65747;
UPDATE laus SET name_national=N'Tinjan', name_latin=N'Tinjan', abac_name=N'Tinjan', display_name=N'Tinjan' WHERE id=65748;
UPDATE laus SET name_national=N'Tisno', name_latin=N'Tisno', abac_name=N'Tisno', display_name=N'Tisno' WHERE id=65749;
UPDATE laus SET name_national=N'Tkon', name_latin=N'Tkon', abac_name=N'Tkon', display_name=N'Tkon' WHERE id=65750;
UPDATE laus SET name_national=N'Tompojevci', name_latin=N'Tompojevci', abac_name=N'Tompojevci', display_name=N'Tompojevci' WHERE id=65751;
UPDATE laus SET name_national=N'Topusko', name_latin=N'Topusko', abac_name=N'Topusko', display_name=N'Topusko' WHERE id=65752;
UPDATE laus SET name_national=N'Tordinci', name_latin=N'Tordinci', abac_name=N'Tordinci', display_name=N'Tordinci' WHERE id=65753;
UPDATE laus SET name_national=N'Tounj', name_latin=N'Tounj', abac_name=N'Tounj', display_name=N'Tounj' WHERE id=65754;
UPDATE laus SET name_national=N'Tovarnik', name_latin=N'Tovarnik', abac_name=N'Tovarnik', display_name=N'Tovarnik' WHERE id=65755;
UPDATE laus SET name_national=N'Tribunj', name_latin=N'Tribunj', abac_name=N'Tribunj', display_name=N'Tribunj' WHERE id=65756;
UPDATE laus SET name_national=N'Trilj', name_latin=N'Trilj', abac_name=N'Trilj', display_name=N'Trilj' WHERE id=65757;
UPDATE laus SET name_national=N'Trnava', name_latin=N'Trnava', abac_name=N'Trnava', display_name=N'Trnava' WHERE id=65758;
UPDATE laus SET name_national=N'Trnovec Bartolovečki', name_latin=N'Trnovec bartolovečki', abac_name=N'Trnovec Bartolovecki', display_name=N'Trnovec Bartolovečki' WHERE id=65759;
UPDATE laus SET name_national=N'Trogir', name_latin=N'Trogir', abac_name=N'Trogir', display_name=N'Trogir' WHERE id=65760;
UPDATE laus SET name_national=N'Trpanj', name_latin=N'Trpanj', abac_name=N'Trpanj', display_name=N'Trpanj' WHERE id=65761;
UPDATE laus SET name_national=N'Trpinja', name_latin=N'Trpinja', abac_name=N'Trpinja', display_name=N'Trpinja' WHERE id=65762;
UPDATE laus SET name_national=N'Tučepi', name_latin=N'Tučepi', abac_name=N'Tucepi', display_name=N'Tučepi' WHERE id=65763;
UPDATE laus SET name_national=N'Tuhelj', name_latin=N'Tuhelj', abac_name=N'Tuhelj', display_name=N'Tuhelj' WHERE id=65764;
UPDATE laus SET name_national=N'Udbina', name_latin=N'Udbina', abac_name=N'Udbina', display_name=N'Udbina' WHERE id=65765;
UPDATE laus SET name_national=N'Umag', name_latin=N'Umag - umago', abac_name=N'Umag', display_name=N'Umag' WHERE id=65766;
UPDATE laus SET name_national=N'Unešić', name_latin=N'Unešić', abac_name=N'Unesic', display_name=N'Unešić' WHERE id=65767;
UPDATE laus SET name_national=N'Valpovo', name_latin=N'Valpovo', abac_name=N'Valpovo', display_name=N'Valpovo' WHERE id=65768;
UPDATE laus SET name_national=N'Varaždin', name_latin=N'Varaždin', abac_name=N'Varazdin', display_name=N'Varaždin' WHERE id=65769;
UPDATE laus SET name_national=N'Varaždinske Toplice', name_latin=N'Varaždinske toplice', abac_name=N'Varazdinske Toplice', display_name=N'Varaždinske Toplice' WHERE id=65770;
UPDATE laus SET name_national=N'Vela Luka', name_latin=N'Vela luka', abac_name=N'Vela Luka', display_name=N'Vela Luka' WHERE id=65771;
UPDATE laus SET name_national=N'Velika', name_latin=N'Velika', abac_name=N'Velika', display_name=N'Velika' WHERE id=65772;
UPDATE laus SET name_national=N'Velika Gorica', name_latin=N'Velika gorica', abac_name=N'Velika Gorica', display_name=N'Velika Gorica' WHERE id=65773;
UPDATE laus SET name_national=N'Velika Kopanica', name_latin=N'Velika kopanica', abac_name=N'Velika Kopanica', display_name=N'Velika Kopanica' WHERE id=65774;
UPDATE laus SET name_national=N'Velika Ludina', name_latin=N'Velika ludina', abac_name=N'Velika Ludina', display_name=N'Velika Ludina' WHERE id=65775;
UPDATE laus SET name_national=N'Velika Pisanica', name_latin=N'Velika pisanica', abac_name=N'Velika Pisanica', display_name=N'Velika Pisanica' WHERE id=65776;
UPDATE laus SET name_national=N'Velika Trnovitica', name_latin=N'Velika trnovitica', abac_name=N'Velika Trnovitica', display_name=N'Velika Trnovitica' WHERE id=65777;
UPDATE laus SET name_national=N'Veliki Bukovec', name_latin=N'Veliki bukovec', abac_name=N'Veliki Bukovec', display_name=N'Veliki Bukovec' WHERE id=65778;
UPDATE laus SET name_national=N'Veliki Grđevac', name_latin=N'Veliki grđevac', abac_name=N'Veliki Grdevac', display_name=N'Veliki Grđevac' WHERE id=65779;
UPDATE laus SET name_national=N'Veliko Trgovišće', name_latin=N'Veliko trgovišće', abac_name=N'Veliko Trgovisce', display_name=N'Veliko Trgovišće' WHERE id=65780;
UPDATE laus SET name_national=N'Veliko Trojstvo', name_latin=N'Veliko trojstvo', abac_name=N'Veliko Trojstvo', display_name=N'Veliko Trojstvo' WHERE id=65781;
UPDATE laus SET name_national=N'Vidovec', name_latin=N'Vidovec', abac_name=N'Vidovec', display_name=N'Vidovec' WHERE id=65782;
UPDATE laus SET name_national=N'Viljevo', name_latin=N'Viljevo', abac_name=N'Viljevo', display_name=N'Viljevo' WHERE id=65783;
UPDATE laus SET name_national=N'Vinica', name_latin=N'Vinica', abac_name=N'Vinica', display_name=N'Vinica' WHERE id=65784;
UPDATE laus SET name_national=N'Vinkovci', name_latin=N'Vinkovci', abac_name=N'Vinkovci', display_name=N'Vinkovci' WHERE id=65785;
UPDATE laus SET name_national=N'Vinodolska Općina', name_latin=N'Vinodolska općina', abac_name=N'Vinodolska Opcina', display_name=N'Vinodolska Općina' WHERE id=65786;
UPDATE laus SET name_national=N'Vir', name_latin=N'Vir', abac_name=N'Vir', display_name=N'Vir' WHERE id=65787;
UPDATE laus SET name_national=N'Virje', name_latin=N'Virje', abac_name=N'Virje', display_name=N'Virje' WHERE id=65788;
UPDATE laus SET name_national=N'Virovitica', name_latin=N'Virovitica', abac_name=N'Virovitica', display_name=N'Virovitica' WHERE id=65789;
UPDATE laus SET name_national=N'Vis', name_latin=N'Vis', abac_name=N'Vis', display_name=N'Vis' WHERE id=65790;
UPDATE laus SET name_national=N'Viškovci', name_latin=N'Viškovci', abac_name=N'Viskovci', display_name=N'Viškovci' WHERE id=65791;
UPDATE laus SET name_national=N'Viškovo', name_latin=N'Viškovo', abac_name=N'Viskovo', display_name=N'Viškovo' WHERE id=65792;
UPDATE laus SET name_national=N'Višnjan - Visignano', name_latin=N'Višnjan - visignano', abac_name=N'Visnjan - Visignano', display_name=N'Višnjan - Visignano' WHERE id=65793;
UPDATE laus SET name_national=N'Visoko', name_latin=N'Visoko', abac_name=N'Visoko', display_name=N'Visoko' WHERE id=65794;
UPDATE laus SET name_national=N'Vižinada - Visinada', name_latin=N'Vižinada - visinada', abac_name=N'Vizinada - Visinada', display_name=N'Vižinada - Visinada' WHERE id=65795;
UPDATE laus SET name_national=N'Vladislavci', name_latin=N'Vladislavci', abac_name=N'Vladislavci', display_name=N'Vladislavci' WHERE id=65796;
UPDATE laus SET name_national=N'Voćin', name_latin=N'Voćin', abac_name=N'Vocin', display_name=N'Voćin' WHERE id=65797;
UPDATE laus SET name_national=N'Vodice', name_latin=N'Vodice', abac_name=N'Vodice', display_name=N'Vodice' WHERE id=65798;
UPDATE laus SET name_national=N'Vođinci', name_latin=N'Vođinci', abac_name=N'Vodinci', display_name=N'Vođinci' WHERE id=65799;
UPDATE laus SET name_national=N'Vodnjan - Dignano', name_latin=N'Vodnjan - dignano', abac_name=N'Vodnjan - Dignano', display_name=N'Vodnjan - Dignano' WHERE id=65800;
UPDATE laus SET name_national=N'Vojnić', name_latin=N'Vojnić', abac_name=N'Vojnic', display_name=N'Vojnić' WHERE id=65801;
UPDATE laus SET name_national=N'Vratišinec', name_latin=N'Vratišinec', abac_name=N'Vratisinec', display_name=N'Vratišinec' WHERE id=65802;
UPDATE laus SET name_national=N'Vrbanja', name_latin=N'Vrbanja', abac_name=N'Vrbanja', display_name=N'Vrbanja' WHERE id=65803;
UPDATE laus SET name_national=N'Vrbje', name_latin=N'Vrbje', abac_name=N'Vrbje', display_name=N'Vrbje' WHERE id=65804;
UPDATE laus SET name_national=N'Vrbnik', name_latin=N'Vrbnik', abac_name=N'Vrbnik', display_name=N'Vrbnik' WHERE id=65805;
UPDATE laus SET name_national=N'Vrbovec', name_latin=N'Vrbovec', abac_name=N'Vrbovec', display_name=N'Vrbovec' WHERE id=65806;
UPDATE laus SET name_national=N'Vrbovsko', name_latin=N'Vrbovsko', abac_name=N'Vrbovsko', display_name=N'Vrbovsko' WHERE id=65807;
UPDATE laus SET name_national=N'Vrgorac', name_latin=N'Vrgorac', abac_name=N'Vrgorac', display_name=N'Vrgorac' WHERE id=65808;
UPDATE laus SET name_national=N'Vrhovine', name_latin=N'Vrhovine', abac_name=N'Vrhovine', display_name=N'Vrhovine' WHERE id=65809;
UPDATE laus SET name_national=N'Vrlika', name_latin=N'Vrlika', abac_name=N'Vrlika', display_name=N'Vrlika' WHERE id=65810;
UPDATE laus SET name_national=N'Vrpolje', name_latin=N'Vrpolje', abac_name=N'Vrpolje', display_name=N'Vrpolje' WHERE id=65811;
UPDATE laus SET name_national=N'Vrsar - Orsera', name_latin=N'Vrsar - orsera', abac_name=N'Vrsar - Orsera', display_name=N'Vrsar - Orsera' WHERE id=65812;
UPDATE laus SET name_national=N'Vrsi', name_latin=N'Vrsi', abac_name=N'Vrsi', display_name=N'Vrsi' WHERE id=65813;
UPDATE laus SET name_national=N'Vuka', name_latin=N'Vuka', abac_name=N'Vuka', display_name=N'Vuka' WHERE id=65814;
UPDATE laus SET name_national=N'Vukovar', name_latin=N'Vukovar', abac_name=N'Vukovar', display_name=N'Vukovar' WHERE id=65815;
UPDATE laus SET name_national=N'Zabok', name_latin=N'Zabok', abac_name=N'Zabok', display_name=N'Zabok' WHERE id=65816;
UPDATE laus SET name_national=N'Zadar', name_latin=N'Zadar', abac_name=N'Zadar', display_name=N'Zadar' WHERE id=65817;
UPDATE laus SET name_national=N'Zadvarje', name_latin=N'Zadvarje', abac_name=N'Zadvarje', display_name=N'Zadvarje' WHERE id=65818;
UPDATE laus SET name_national=N'Zagorska Sela', name_latin=N'Zagorska sela', abac_name=N'Zagorska Sela', display_name=N'Zagorska Sela' WHERE id=65819;
UPDATE laus SET name_national=N'Zagvozd', name_latin=N'Zagvozd', abac_name=N'Zagvozd', display_name=N'Zagvozd' WHERE id=65820;
UPDATE laus SET name_national=N'Žakanje', name_latin=N'Žakanje', abac_name=N'Zakanje', display_name=N'Žakanje' WHERE id=65821;
UPDATE laus SET name_national=N'Zaprešić', name_latin=N'Zaprešić', abac_name=N'Zapresic', display_name=N'Zaprešić' WHERE id=65822;
UPDATE laus SET name_national=N'Zažablje', name_latin=N'Zažablje', abac_name=N'Zazablje', display_name=N'Zažablje' WHERE id=65823;
UPDATE laus SET name_national=N'Zdenci', name_latin=N'Zdenci', abac_name=N'Zdenci', display_name=N'Zdenci' WHERE id=65824;
UPDATE laus SET name_national=N'Zemunik Donji', name_latin=N'Zemunik donji', abac_name=N'Zemunik Donji', display_name=N'Zemunik Donji' WHERE id=65825;
UPDATE laus SET name_national=N'Zlatar', name_latin=N'Zlatar', abac_name=N'Zlatar', display_name=N'Zlatar' WHERE id=65826;
UPDATE laus SET name_national=N'Zlatar Bistrica', name_latin=N'Zlatar bistrica', abac_name=N'Zlatar Bistrica', display_name=N'Zlatar Bistrica' WHERE id=65827;
UPDATE laus SET name_national=N'Zmijavci', name_latin=N'Zmijavci', abac_name=N'Zmijavci', display_name=N'Zmijavci' WHERE id=65828;
UPDATE laus SET name_national=N'Žminj', name_latin=N'Žminj', abac_name=N'Zminj', display_name=N'Žminj' WHERE id=65829;
UPDATE laus SET name_national=N'Zrinski Topolovac', name_latin=N'Zrinski topolovac', abac_name=N'Zrinski Topolovac', display_name=N'Zrinski Topolovac' WHERE id=65830;
UPDATE laus SET name_national=N'Žumberak', name_latin=N'Žumberak', abac_name=N'Zumberak', display_name=N'Žumberak' WHERE id=65831;
UPDATE laus SET name_national=N'Župa Dubrovačka', name_latin=N'Župa dubrovačka', abac_name=N'Zupa Dubrovacka', display_name=N'Župa Dubrovačka' WHERE id=65832;
UPDATE laus SET name_national=N'Županja', name_latin=N'Županja', abac_name=N'Zupanja', display_name=N'Županja' WHERE id=65833;

--556

--select nuts3, lau1, name_national, name_latin, abac_name, display_name, id 
--from laus where country_code = 'HR' order by name1 asc