-- INSERT EE LAUS (update nuts3 code, added new name fields)
-- SQL (nuts3 + names)
UPDATE laus SET nuts3='EE001', name_national=N'Anija vald', name_latin=N'Anija vald', abac_name=N'Anija vald', display_name=N'Anija vald' WHERE id=20980;
UPDATE laus SET nuts3='EE001', name_national=N'Harku vald', name_latin=N'Harku vald', abac_name=N'Harku vald', display_name=N'Harku vald' WHERE id=20986;
UPDATE laus SET nuts3='EE001', name_national=N'Jõelähtme vald', name_latin=N'Jõelähtme vald', abac_name=N'Joelahtme vald', display_name=N'Jõelähtme vald' WHERE id=20989;
UPDATE laus SET nuts3='EE001', name_national=N'Keila linn', name_latin=N'Keila linn', abac_name=N'Keila linn', display_name=N'Keila linn' WHERE id=20997;
UPDATE laus SET nuts3='EE001', name_national=N'Kiili vald', name_latin=N'Kiili vald', abac_name=N'Kiili vald', display_name=N'Kiili vald' WHERE id=20999;
UPDATE laus SET nuts3='EE001', name_national=N'Kose vald', name_latin=N'Kose vald', abac_name=N'Kose vald', display_name=N'Kose vald' WHERE id=21002;
UPDATE laus SET nuts3='EE001', name_national=N'Kuusalu vald', name_latin=N'Kuusalu vald', abac_name=N'Kuusalu vald', display_name=N'Kuusalu vald' WHERE id=21003;
UPDATE laus SET nuts3='EE001', name_national=N'Lääne-Harju vald', name_latin=N'Lääne-Harju vald', abac_name=N'Laane-Harju vald', display_name=N'Lääne-Harju vald' WHERE id=21004;
UPDATE laus SET nuts3='EE001', name_national=N'Loksa linn', name_latin=N'Loksa linn', abac_name=N'Loksa linn', display_name=N'Loksa linn' WHERE id=21007;
UPDATE laus SET nuts3='EE001', name_national=N'Maardu linn', name_latin=N'Maardu linn', abac_name=N'Maardu linn', display_name=N'Maardu linn' WHERE id=21010;
UPDATE laus SET nuts3='EE001', name_national=N'Raasiku vald', name_latin=N'Raasiku vald', abac_name=N'Raasiku vald', display_name=N'Raasiku vald' WHERE id=21026;
UPDATE laus SET nuts3='EE001', name_national=N'Rae vald', name_latin=N'Rae vald', abac_name=N'Rae vald', display_name=N'Rae vald' WHERE id=21027;
UPDATE laus SET nuts3='EE001', name_national=N'Saku vald', name_latin=N'Saku vald', abac_name=N'Saku vald', display_name=N'Saku vald' WHERE id=21036;
UPDATE laus SET nuts3='EE001', name_national=N'Saue vald', name_latin=N'Saue vald', abac_name=N'Saue vald', display_name=N'Saue vald' WHERE id=21037;
UPDATE laus SET nuts3='EE001', name_national=N'Tallinn', name_latin=N'Tallinn', abac_name=N'Tallinn', display_name=N'Tallinn' WHERE id=21040;
UPDATE laus SET nuts3='EE001', name_national=N'Viimsi vald', name_latin=N'Viimsi vald', abac_name=N'Viimsi vald', display_name=N'Viimsi vald' WHERE id=21050;
UPDATE laus SET nuts3='EE004', name_national=N'Häädemeeste vald', name_latin=N'Häädemeeste vald', abac_name=N'Haademeeste vald', display_name=N'Häädemeeste vald' WHERE id=20983;
UPDATE laus SET nuts3='EE004', name_national=N'Haapsalu linn', name_latin=N'Haapsalu linn', abac_name=N'Haapsalu linn', display_name=N'Haapsalu linn' WHERE id=20984;
UPDATE laus SET nuts3='EE004', name_national=N'Hiiumaa vald', name_latin=N'Hiiumaa vald', abac_name=N'Hiiumaa vald', display_name=N'Hiiumaa vald' WHERE id=20987;
UPDATE laus SET nuts3='EE004', name_national=N'Kihnu vald', name_latin=N'Kihnu vald', abac_name=N'Kihnu vald', display_name=N'Kihnu vald' WHERE id=20998;
UPDATE laus SET nuts3='EE004', name_national=N'Lääne-Nigula vald', name_latin=N'Lääne-Nigula vald', abac_name=N'Laane-Nigula vald', display_name=N'Lääne-Nigula vald' WHERE id=21005;
UPDATE laus SET nuts3='EE004', name_national=N'Lääneranna vald', name_latin=N'Lääneranna vald', abac_name=N'Laaneranna vald', display_name=N'Lääneranna vald' WHERE id=21006;
UPDATE laus SET nuts3='EE004', name_national=N'Muhu vald', name_latin=N'Muhu vald', abac_name=N'Muhu vald', display_name=N'Muhu vald' WHERE id=21012;
UPDATE laus SET nuts3='EE004', name_national=N'Pärnu linn', name_latin=N'Pärnu linn', abac_name=N'Parnu linn', display_name=N'Pärnu linn' WHERE id=21020;
UPDATE laus SET nuts3='EE004', name_national=N'Põhja-Pärnumaa vald', name_latin=N'Põhja-Pärnumaa vald', abac_name=N'Pohja-Parnumaa vald', display_name=N'Põhja-Pärnumaa vald' WHERE id=21022;
UPDATE laus SET nuts3='EE004', name_national=N'Ruhnu vald', name_latin=N'Ruhnu vald', abac_name=N'Ruhnu vald', display_name=N'Ruhnu vald' WHERE id=21033;
UPDATE laus SET nuts3='EE004', name_national=N'Saarde vald', name_latin=N'Saarde vald', abac_name=N'Saarde vald', display_name=N'Saarde vald' WHERE id=21034;
UPDATE laus SET nuts3='EE004', name_national=N'Saaremaa vald', name_latin=N'Saaremaa vald', abac_name=N'Saaremaa vald', display_name=N'Saaremaa vald' WHERE id=21035;
UPDATE laus SET nuts3='EE004', name_national=N'Tori vald', name_latin=N'Tori vald', abac_name=N'Tori vald', display_name=N'Tori vald' WHERE id=21045;
UPDATE laus SET nuts3='EE004', name_national=N'Vormsi vald', name_latin=N'Vormsi vald', abac_name=N'Vormsi vald', display_name=N'Vormsi vald' WHERE id=21055;
UPDATE laus SET nuts3='EE006', name_national=N'Haljala vald', name_latin=N'Haljala vald', abac_name=N'Haljala vald', display_name=N'Haljala vald' WHERE id=20985;
UPDATE laus SET nuts3='EE006', name_national=N'Järva vald', name_latin=N'Järva vald', abac_name=N'Jarva vald', display_name=N'Järva vald' WHERE id=20988;
UPDATE laus SET nuts3='EE006', name_national=N'Kadrina vald', name_latin=N'Kadrina vald', abac_name=N'Kadrina vald', display_name=N'Kadrina vald' WHERE id=20992;
UPDATE laus SET nuts3='EE006', name_national=N'Kehtna vald', name_latin=N'Kehtna vald', abac_name=N'Kehtna vald', display_name=N'Kehtna vald' WHERE id=20996;
UPDATE laus SET nuts3='EE006', name_national=N'Kohila vald', name_latin=N'Kohila vald', abac_name=N'Kohila vald', display_name=N'Kohila vald' WHERE id=21000;
UPDATE laus SET nuts3='EE006', name_national=N'Märjamaa vald', name_latin=N'Märjamaa vald', abac_name=N'Marjamaa vald', display_name=N'Märjamaa vald' WHERE id=21011;
UPDATE laus SET nuts3='EE006', name_national=N'Paide linn', name_latin=N'Paide linn', abac_name=N'Paide linn', display_name=N'Paide linn' WHERE id=21019;
UPDATE laus SET nuts3='EE006', name_national=N'Rakvere linn', name_latin=N'Rakvere linn', abac_name=N'Rakvere linn', display_name=N'Rakvere linn' WHERE id=21028;
UPDATE laus SET nuts3='EE006', name_national=N'Rakvere vald', name_latin=N'Rakvere vald', abac_name=N'Rakvere vald', display_name=N'Rakvere vald' WHERE id=21029;
UPDATE laus SET nuts3='EE006', name_national=N'Rapla vald', name_latin=N'Rapla vald', abac_name=N'Rapla vald', display_name=N'Rapla vald' WHERE id=21031;
UPDATE laus SET nuts3='EE006', name_national=N'Tapa vald', name_latin=N'Tapa vald', abac_name=N'Tapa vald', display_name=N'Tapa vald' WHERE id=21041;
UPDATE laus SET nuts3='EE006', name_national=N'Türi vald', name_latin=N'Türi vald', abac_name=N'Turi vald', display_name=N'Türi vald' WHERE id=21047;
UPDATE laus SET nuts3='EE006', name_national=N'Väike-Maarja vald', name_latin=N'Väike-Maarja vald', abac_name=N'Väike-Maarja vald', display_name=N'Väike-Maarja vald' WHERE id=21048;
UPDATE laus SET nuts3='EE006', name_national=N'Vinni vald', name_latin=N'Vinni vald', abac_name=N'Vinni vald', display_name=N'Vinni vald' WHERE id=21053;
UPDATE laus SET nuts3='EE006', name_national=N'Viru-Nigula vald', name_latin=N'Viru-Nigula vald', abac_name=N'Viru-Nigula vald', display_name=N'Viru-Nigula vald' WHERE id=21054;
UPDATE laus SET nuts3='EE007', name_national=N'Alutaguse vald', name_latin=N'Alutaguse vald', abac_name=N'Alutaguse vald', display_name=N'Alutaguse vald' WHERE id=20979;
UPDATE laus SET nuts3='EE007', name_national=N'Jõhvi vald', name_latin=N'Jõhvi vald', abac_name=N'Johvi vald', display_name=N'Jõhvi vald' WHERE id=20991;
UPDATE laus SET nuts3='EE007', name_national=N'Kohtla-Järve linn', name_latin=N'Kohtla-Järve linn', abac_name=N'Kohtla-Jarve linn', display_name=N'Kohtla-Järve linn' WHERE id=21001;
UPDATE laus SET nuts3='EE007', name_national=N'Lüganuse vald', name_latin=N'Lüganuse vald', abac_name=N'Luganuse vald', display_name=N'Lüganuse vald' WHERE id=21008;
UPDATE laus SET nuts3='EE007', name_national=N'Narva linn', name_latin=N'Narva linn', abac_name=N'Narva linn', display_name=N'Narva linn' WHERE id=21015;
UPDATE laus SET nuts3='EE007', name_national=N'Narva-Jõesuu linn', name_latin=N'Narva-Jõesuu linn', abac_name=N'Narva-Joesuu linn', display_name=N'Narva-Jõesuu linn' WHERE id=21016;
UPDATE laus SET nuts3='EE007', name_national=N'Sillamäe linn', name_latin=N'Sillamäe linn', abac_name=N'Sillamae linn', display_name=N'Sillamäe linn' WHERE id=21039;
UPDATE laus SET nuts3='EE007', name_national=N'Toila vald', name_latin=N'Toila vald', abac_name=N'Toila vald', display_name=N'Toila vald' WHERE id=21044;
UPDATE laus SET nuts3='EE008', name_national=N'Antsla vald', name_latin=N'Antsla vald', abac_name=N'Antsla vald', display_name=N'Antsla vald' WHERE id=20981;
UPDATE laus SET nuts3='EE008', name_national=N'Elva vald', name_latin=N'Elva vald', abac_name=N'Elva vald', display_name=N'Elva vald' WHERE id=20982;
UPDATE laus SET nuts3='EE008', name_national=N'Jõgeva vald', name_latin=N'Jõgeva vald', abac_name=N'Jogeva vald', display_name=N'Jõgeva vald' WHERE id=20990;
UPDATE laus SET nuts3='EE008', name_national=N'Kambja vald', name_latin=N'Kambja vald', abac_name=N'Kambja vald', display_name=N'Kambja vald' WHERE id=20993;
UPDATE laus SET nuts3='EE008', name_national=N'Kanepi vald', name_latin=N'Kanepi vald', abac_name=N'Kanepi vald', display_name=N'Kanepi vald' WHERE id=20994;
UPDATE laus SET nuts3='EE008', name_national=N'Kastre vald', name_latin=N'Kastre vald', abac_name=N'Kastre vald', display_name=N'Kastre vald' WHERE id=20995;
UPDATE laus SET nuts3='EE008', name_national=N'Luunja vald', name_latin=N'Luunja vald', abac_name=N'Luunja vald', display_name=N'Luunja vald' WHERE id=21009;
UPDATE laus SET nuts3='EE008', name_national=N'Mulgi vald', name_latin=N'Mulgi vald', abac_name=N'Mulgi vald', display_name=N'Mulgi vald' WHERE id=21013;
UPDATE laus SET nuts3='EE008', name_national=N'Mustvee vald', name_latin=N'Mustvee vald', abac_name=N'Mustvee vald', display_name=N'Mustvee vald' WHERE id=21014;
UPDATE laus SET nuts3='EE008', name_national=N'Nõo vald', name_latin=N'Nõo vald', abac_name=N'Noo vald', display_name=N'Nõo vald' WHERE id=21017;
UPDATE laus SET nuts3='EE008', name_national=N'Otepää vald', name_latin=N'Otepää vald', abac_name=N'Otepaa vald', display_name=N'Otepää vald' WHERE id=21018;
UPDATE laus SET nuts3='EE008', name_national=N'Peipsiääre vald', name_latin=N'Peipsiääre vald', abac_name=N'Peipsiaare vald', display_name=N'Peipsiääre vald' WHERE id=21021;
UPDATE laus SET nuts3='EE008', name_national=N'Põhja-Sakala vald', name_latin=N'Põhja-Sakala vald', abac_name=N'Pohja-Sakala vald', display_name=N'Põhja-Sakala vald' WHERE id=21023;
UPDATE laus SET nuts3='EE008', name_national=N'Põltsamaa vald', name_latin=N'Põltsamaa vald', abac_name=N'Poltsamaa vald', display_name=N'Põltsamaa vald' WHERE id=21024;
UPDATE laus SET nuts3='EE008', name_national=N'Põlva vald', name_latin=N'Põlva vald', abac_name=N'Polva vald', display_name=N'Põlva vald' WHERE id=21025;
UPDATE laus SET nuts3='EE008', name_national=N'Räpina vald', name_latin=N'Räpina vald', abac_name=N'Rapina vald', display_name=N'Räpina vald' WHERE id=21030;
UPDATE laus SET nuts3='EE008', name_national=N'Rõuge vald', name_latin=N'Rõuge vald', abac_name=N'Rouge vald', display_name=N'Rõuge vald' WHERE id=21032;
UPDATE laus SET nuts3='EE008', name_national=N'Setomaa vald', name_latin=N'Setomaa vald', abac_name=N'Setomaa vald', display_name=N'Setomaa vald' WHERE id=21038;
UPDATE laus SET nuts3='EE008', name_national=N'Tartu linn', name_latin=N'Tartu linn', abac_name=N'Tartu linn', display_name=N'Tartu linn' WHERE id=21042;
UPDATE laus SET nuts3='EE008', name_national=N'Tartu vald', name_latin=N'Tartu vald', abac_name=N'Tartu vald', display_name=N'Tartu vald' WHERE id=21043;
UPDATE laus SET nuts3='EE008', name_national=N'Tõrva vald', name_latin=N'Tõrva vald', abac_name=N'Torva vald', display_name=N'Tõrva vald' WHERE id=21046;
UPDATE laus SET nuts3='EE008', name_national=N'Valga vald', name_latin=N'Valga vald', abac_name=N'Valga vald', display_name=N'Valga vald' WHERE id=21049;
UPDATE laus SET nuts3='EE008', name_national=N'Viljandi linn', name_latin=N'Viljandi linn', abac_name=N'Viljandi linn', display_name=N'Viljandi linn' WHERE id=21051;
UPDATE laus SET nuts3='EE008', name_national=N'Viljandi vald', name_latin=N'Viljandi vald', abac_name=N'Viljandi vald', display_name=N'Viljandi vald' WHERE id=21052;
UPDATE laus SET nuts3='EE008', name_national=N'Võru linn', name_latin=N'Võru linn', abac_name=N'Voru linn', display_name=N'Võru linn' WHERE id=21056;
UPDATE laus SET nuts3='EE008', name_national=N'Võru vald', name_latin=N'Võru vald', abac_name=N'Voru vald', display_name=N'Võru vald' WHERE id=21057;

--79

--select nuts3, lau1, name_national, name_latin, abac_name, display_name, id 
--from laus where country_code = 'EE' order by name1 asc