-- INSERT BG LAUS (update lau code, added new name fields)
UPDATE laus SET name_national=N'Айтос', name_latin=N'Aytos', abac_name=N'Aitos', display_name=N'Айтос-Aytos' WHERE id=2688;
UPDATE laus SET name_national=N'Бургас', name_latin=N'Burgas', abac_name=N'Burgas', display_name=N'Бургас-Burgas' WHERE id=2689;
UPDATE laus SET name_national=N'Средец', name_latin=N'Sredets', abac_name=N'Sredets', display_name=N'Средец-Sredets' WHERE id=2690;
UPDATE laus SET name_national=N'Камено', name_latin=N'Kameno', abac_name=N'Kameno', display_name=N'Камено-Kameno' WHERE id=2691;
UPDATE laus SET name_national=N'Карнобат', name_latin=N'Karnobat', abac_name=N'Karnobat', display_name=N'Карнобат-Karnobat' WHERE id=2692;
UPDATE laus SET name_national=N'Малко Търново', name_latin=N'Malko Tarnovo', abac_name=N'Malko T''rnovo', display_name=N'Малко Търново-Malko Tarnovo' WHERE id=2693;
UPDATE laus SET name_national=N'Царево', name_latin=N'Tsarevo', abac_name=N'Tsarevo', display_name=N'Царево-Tsarevo' WHERE id=2694;
UPDATE laus SET name_national=N'Несебър', name_latin=N'Nesebar', abac_name=N'Neseb''r', display_name=N'Несебър-Nesebar' WHERE id=2695;
UPDATE laus SET name_national=N'Поморие', name_latin=N'Pomorie', abac_name=N'Pomorie', display_name=N'Поморие-Pomorie' WHERE id=2696;
UPDATE laus SET name_national=N'Руен', name_latin=N'Ruen', abac_name=N'Ruen', display_name=N'Руен-Ruen' WHERE id=2697;
UPDATE laus SET name_national=N'Созопол', name_latin=N'Sozopol', abac_name=N'Sozopol', display_name=N'Созопол-Sozopol' WHERE id=2698;
UPDATE laus SET name_national=N'Сунгурларе', name_latin=N'Sungurlare', abac_name=N'Sungurlare', display_name=N'Сунгурларе-Sungurlare' WHERE id=2699;
UPDATE laus SET name_national=N'Приморско', name_latin=N'Primorsko', abac_name=N'Primorsko', display_name=N'Приморско-Primorsko' WHERE id=2700;
UPDATE laus SET name_national=N'Банско', name_latin=N'Bansko', abac_name=N'Bansko', display_name=N'Банско-Bansko' WHERE id=2701;
UPDATE laus SET name_national=N'Белица', name_latin=N'Belitsa', abac_name=N'Belitsa', display_name=N'Белица-Belitsa' WHERE id=2702;
UPDATE laus SET name_national=N'Благоевград', name_latin=N'Blagoevgrad', abac_name=N'Blagoevgrad', display_name=N'Благоевград-Blagoevgrad' WHERE id=2703;
UPDATE laus SET name_national=N'Гоце Делчев', name_latin=N'Gotse Delchev', abac_name=N'Gotse Delchev', display_name=N'Гоце Делчев-Gotse Delchev' WHERE id=2704;
UPDATE laus SET name_national=N'Гърмен', name_latin=N'Garmen', abac_name=N'G''rmen', display_name=N'Гърмен-Garmen' WHERE id=2705;
UPDATE laus SET name_national=N'Кресна', name_latin=N'Kresna', abac_name=N'Kresna', display_name=N'Кресна-Kresna' WHERE id=2706;
UPDATE laus SET name_national=N'Петрич', name_latin=N'Petrich', abac_name=N'Petrich', display_name=N'Петрич-Petrich' WHERE id=2707;
UPDATE laus SET name_national=N'Разлог', name_latin=N'Razlog', abac_name=N'Razlog', display_name=N'Разлог-Razlog' WHERE id=2708;
UPDATE laus SET name_national=N'Сандански', name_latin=N'Sandanski', abac_name=N'Sandanski', display_name=N'Сандански-Sandanski' WHERE id=2709;
UPDATE laus SET name_national=N'Сатовча', name_latin=N'Satovcha', abac_name=N'Satovcha', display_name=N'Сатовча-Satovcha' WHERE id=2710;
UPDATE laus SET name_national=N'Симитли', name_latin=N'Simitli', abac_name=N'Simitli', display_name=N'Симитли-Simitli' WHERE id=2711;
UPDATE laus SET name_national=N'Струмяни', name_latin=N'Strumyani', abac_name=N'Strumiani', display_name=N'Струмяни-Strumyani' WHERE id=2712;
UPDATE laus SET name_national=N'Хаджидимово', name_latin=N'Hadzhidimovo', abac_name=N'Khadzhidimovo', display_name=N'Хаджидимово-Hadzhidimovo' WHERE id=2713;
UPDATE laus SET name_national=N'Якоруда', name_latin=N'Yakoruda', abac_name=N'Iakoruda', display_name=N'Якоруда-Yakoruda' WHERE id=2714;
UPDATE laus SET name_national=N'Балчик', name_latin=N'Balchik', abac_name=N'Balchik', display_name=N'Балчик-Balchik' WHERE id=2715;
UPDATE laus SET name_national=N'Генерал Тошево', name_latin=N'General Toshevo', abac_name=N'General Toshevo', display_name=N'Генерал Тошево-General Toshevo' WHERE id=2716;
UPDATE laus SET name_national=N'Добрич - селска', name_latin=N'Dobrich-selska', abac_name=N'Dobrich - selska', display_name=N'Добрич - селска-Dobrich-selska' WHERE id=2717;
UPDATE laus SET name_national=N'Каварна', name_latin=N'Kavarna', abac_name=N'Kavarna', display_name=N'Каварна-Kavarna' WHERE id=2718;
UPDATE laus SET name_national=N'Крушари', name_latin=N'Krushari', abac_name=N'Krushari', display_name=N'Крушари-Krushari' WHERE id=2719;
UPDATE laus SET name_national=N'Тервел', name_latin=N'Tervel', abac_name=N'Tervel', display_name=N'Тервел-Tervel' WHERE id=2720;
UPDATE laus SET name_national=N'Добрич', name_latin=N'Dobrich', abac_name=N'Dobrich', display_name=N'Добрич-Dobrich' WHERE id=2721;
UPDATE laus SET name_national=N'Шабла', name_latin=N'Shabla', abac_name=N'Shabla', display_name=N'Шабла-Shabla' WHERE id=2722;
UPDATE laus SET name_national=N'Габрово', name_latin=N'Gabrovo', abac_name=N'Gabrovo', display_name=N'Габрово-Gabrovo' WHERE id=2723;
UPDATE laus SET name_national=N'Дряново', name_latin=N'Dryanovo', abac_name=N'Drianovo', display_name=N'Дряново-Dryanovo' WHERE id=2724;
UPDATE laus SET name_national=N'Севлиево', name_latin=N'Sevlievo', abac_name=N'Sevlievo', display_name=N'Севлиево-Sevlievo' WHERE id=2725;
UPDATE laus SET name_national=N'Трявна', name_latin=N'Tryavna', abac_name=N'Triavna', display_name=N'Трявна-Tryavna' WHERE id=2726;
UPDATE laus SET name_national=N'Димитровград', name_latin=N'Dimitrovgrad', abac_name=N'Dimitrovgrad', display_name=N'Димитровград-Dimitrovgrad' WHERE id=2727;
UPDATE laus SET name_national=N'Ивайловград', name_latin=N'Ivaylovgrad', abac_name=N'Ivailovgrad', display_name=N'Ивайловград-Ivaylovgrad' WHERE id=2728;
UPDATE laus SET name_national=N'Любимец', name_latin=N'Lyubimets', abac_name=N'Liubimets', display_name=N'Любимец-Lyubimets' WHERE id=2729;
UPDATE laus SET name_national=N'Маджарово', name_latin=N'Madzharovo', abac_name=N'Madzharovo', display_name=N'Маджарово-Madzharovo' WHERE id=2730;
UPDATE laus SET name_national=N'Минерални бани', name_latin=N'Mineralni bani', abac_name=N'Mineralni bani', display_name=N'Минерални бани-Mineralni bani' WHERE id=2731;
UPDATE laus SET name_national=N'Свиленград', name_latin=N'Svilengrad', abac_name=N'Svilengrad', display_name=N'Свиленград-Svilengrad' WHERE id=2732;
UPDATE laus SET name_national=N'Симеоновград', name_latin=N'Simeonovgrad', abac_name=N'Simeonovgrad', display_name=N'Симеоновград-Simeonovgrad' WHERE id=2733;
UPDATE laus SET name_national=N'Стамболово', name_latin=N'Stambolovo', abac_name=N'Stambolovo', display_name=N'Стамболово-Stambolovo' WHERE id=2734;
UPDATE laus SET name_national=N'Тополовград', name_latin=N'Topolovgrad', abac_name=N'Topolovgrad', display_name=N'Тополовград-Topolovgrad' WHERE id=2735;
UPDATE laus SET name_national=N'Харманли', name_latin=N'Harmanli', abac_name=N'Kharmanli', display_name=N'Харманли-Harmanli' WHERE id=2736;
UPDATE laus SET name_national=N'Хасково', name_latin=N'Haskovo', abac_name=N'Khaskovo', display_name=N'Хасково-Haskovo' WHERE id=2737;
UPDATE laus SET name_national=N'Болярово', name_latin=N'Bolyarovo', abac_name=N'Boliarovo', display_name=N'Болярово-Bolyarovo' WHERE id=2738;
UPDATE laus SET name_national=N'Елхово', name_latin=N'Elhovo', abac_name=N'Elkhovo', display_name=N'Елхово-Elhovo' WHERE id=2739;
UPDATE laus SET name_national=N'Стралджа', name_latin=N'Straldzha', abac_name=N'Straldzha', display_name=N'Стралджа-Straldzha' WHERE id=2740;
UPDATE laus SET name_national=N'Тунджа', name_latin=N'Tundzha', abac_name=N'Tundzha', display_name=N'Тунджа-Tundzha' WHERE id=2741;
UPDATE laus SET name_national=N'Ямбол', name_latin=N'Yambol', abac_name=N'Iambol', display_name=N'Ямбол-Yambol' WHERE id=2742;
UPDATE laus SET name_national=N'Бобов дол', name_latin=N'Bobovdol', abac_name=N'Bobov dol', display_name=N'Бобов дол-Bobovdol' WHERE id=2743;
UPDATE laus SET name_national=N'Бобошево', name_latin=N'Boboshevo', abac_name=N'Boboshevo', display_name=N'Бобошево-Boboshevo' WHERE id=2744;
UPDATE laus SET name_national=N'Кочериново', name_latin=N'Kocherinovo', abac_name=N'Kocherinovo', display_name=N'Кочериново-Kocherinovo' WHERE id=2745;
UPDATE laus SET name_national=N'Кюстендил', name_latin=N'Kyustendil', abac_name=N'Kiustendil', display_name=N'Кюстендил-Kyustendil' WHERE id=2746;
UPDATE laus SET name_national=N'Невестино', name_latin=N'Nevestino', abac_name=N'Nevestino', display_name=N'Невестино-Nevestino' WHERE id=2747;
UPDATE laus SET name_national=N'Рила', name_latin=N'Rila', abac_name=N'Rila', display_name=N'Рила-Rila' WHERE id=2748;
UPDATE laus SET name_national=N'Сапарева баня', name_latin=N'Sapareva banya', abac_name=N'Sapareva bania', display_name=N'Сапарева баня-Sapareva banya' WHERE id=2749;
UPDATE laus SET name_national=N'Дупница', name_latin=N'Dupnitsa', abac_name=N'Dupnitsa', display_name=N'Дупница-Dupnitsa' WHERE id=2750;
UPDATE laus SET name_national=N'Трекляно', name_latin=N'Treklyano', abac_name=N'Trekliano', display_name=N'Трекляно-Treklyano' WHERE id=2751;
UPDATE laus SET name_national=N'Ардино', name_latin=N'Ardino', abac_name=N'Ardino', display_name=N'Ардино-Ardino' WHERE id=2752;
UPDATE laus SET name_national=N'Джебел', name_latin=N'Dzhebel', abac_name=N'Dzhebel', display_name=N'Джебел-Dzhebel' WHERE id=2753;
UPDATE laus SET name_national=N'Кирково', name_latin=N'Kirkovo', abac_name=N'Kirkovo', display_name=N'Кирково-Kirkovo' WHERE id=2754;
UPDATE laus SET name_national=N'Крумовград', name_latin=N'Krumovgrad', abac_name=N'Krumovgrad', display_name=N'Крумовград-Krumovgrad' WHERE id=2755;
UPDATE laus SET name_national=N'Кърджали', name_latin=N'Kardzhali', abac_name=N'K''rdzhali', display_name=N'Кърджали-Kardzhali' WHERE id=2756;
UPDATE laus SET name_national=N'Момчилград', name_latin=N'Momchilgrad', abac_name=N'Momchilgrad', display_name=N'Момчилград-Momchilgrad' WHERE id=2757;
UPDATE laus SET name_national=N'Черноочене', name_latin=N'Chernoochene', abac_name=N'Chernoochene', display_name=N'Черноочене-Chernoochene' WHERE id=2758;
UPDATE laus SET name_national=N'Априлци', name_latin=N'Apriltsi', abac_name=N'Apriltsi', display_name=N'Априлци-Apriltsi' WHERE id=2759;
UPDATE laus SET name_national=N'Летница', name_latin=N'Letnitsa', abac_name=N'Letnitsa', display_name=N'Летница-Letnitsa' WHERE id=2760;
UPDATE laus SET name_national=N'Ловеч', name_latin=N'Lovech', abac_name=N'Lovech', display_name=N'Ловеч-Lovech' WHERE id=2761;
UPDATE laus SET name_national=N'Луковит', name_latin=N'Lukovit', abac_name=N'Lukovit', display_name=N'Луковит-Lukovit' WHERE id=2762;
UPDATE laus SET name_national=N'Тетевен', name_latin=N'Teteven', abac_name=N'Teteven', display_name=N'Тетевен-Teteven' WHERE id=2763;
UPDATE laus SET name_national=N'Троян', name_latin=N'Troyan', abac_name=N'Troian', display_name=N'Троян-Troyan' WHERE id=2764;
UPDATE laus SET name_national=N'Угърчин', name_latin=N'Ugarchin', abac_name=N'Ug''rchin', display_name=N'Угърчин-Ugarchin' WHERE id=2765;
UPDATE laus SET name_national=N'Ябланица', name_latin=N'Yablanitsa', abac_name=N'Iablanitsa', display_name=N'Ябланица-Yablanitsa' WHERE id=2766;
UPDATE laus SET name_national=N'Берковица', name_latin=N'Berkovitsa', abac_name=N'Berkovitsa', display_name=N'Берковица-Berkovitsa' WHERE id=2767;
UPDATE laus SET name_national=N'Бойчиновци', name_latin=N'Boychinovtsi', abac_name=N'Boichinovtsi', display_name=N'Бойчиновци-Boychinovtsi' WHERE id=2768;
UPDATE laus SET name_national=N'Брусарци', name_latin=N'Brusartsi', abac_name=N'Brusartsi', display_name=N'Брусарци-Brusartsi' WHERE id=2769;
UPDATE laus SET name_national=N'Вълчедръм', name_latin=N'Valchedram', abac_name=N'V''lchedr''m', display_name=N'Вълчедръм-Valchedram' WHERE id=2770;
UPDATE laus SET name_national=N'Вършец', name_latin=N'Varshets', abac_name=N'V''rshets', display_name=N'Вършец-Varshets' WHERE id=2771;
UPDATE laus SET name_national=N'Георги Дамяново', name_latin=N'Georgi Damyanovo', abac_name=N'Georgi Damianovo', display_name=N'Георги Дамяново-Georgi Damyanovo' WHERE id=2772;
UPDATE laus SET name_national=N'Лом', name_latin=N'Lom', abac_name=N'Lom', display_name=N'Лом-Lom' WHERE id=2773;
UPDATE laus SET name_national=N'Медковец', name_latin=N'Medkovets', abac_name=N'Medkovets', display_name=N'Медковец-Medkovets' WHERE id=2774;
UPDATE laus SET name_national=N'Монтана', name_latin=N'Montana', abac_name=N'Montana', display_name=N'Монтана-Montana' WHERE id=2775;
UPDATE laus SET name_national=N'Чипровци', name_latin=N'Chiprovtsi', abac_name=N'Chiprovtsi', display_name=N'Чипровци-Chiprovtsi' WHERE id=2776;
UPDATE laus SET name_national=N'Якимово', name_latin=N'Yakimovo', abac_name=N'Iakimovo', display_name=N'Якимово-Yakimovo' WHERE id=2777;
UPDATE laus SET name_national=N'Батак', name_latin=N'Batak', abac_name=N'Batak', display_name=N'Батак-Batak' WHERE id=2778;
UPDATE laus SET name_national=N'Белово', name_latin=N'Belovo', abac_name=N'Belovo', display_name=N'Белово-Belovo' WHERE id=2779;
UPDATE laus SET name_national=N'Брацигово', name_latin=N'Bratsigovo', abac_name=N'Bratsigovo', display_name=N'Брацигово-Bratsigovo' WHERE id=2780;
UPDATE laus SET name_national=N'Велинград', name_latin=N'Velingrad', abac_name=N'Velingrad', display_name=N'Велинград-Velingrad' WHERE id=2781;
UPDATE laus SET name_national=N'Лесичово', name_latin=N'Lesichovo', abac_name=N'Lesichovo', display_name=N'Лесичово-Lesichovo' WHERE id=2782;
UPDATE laus SET name_national=N'Пазарджик', name_latin=N'Pazardzhik', abac_name=N'Pazardzhik', display_name=N'Пазарджик-Pazardzhik' WHERE id=2783;
UPDATE laus SET name_national=N'Панагюрище', name_latin=N'Panagyurishte', abac_name=N'Panagiurishche', display_name=N'Панагюрище-Panagyurishte' WHERE id=2784;
UPDATE laus SET name_national=N'Пещера', name_latin=N'Peshtera', abac_name=N'Peshchera', display_name=N'Пещера-Peshtera' WHERE id=2785;
UPDATE laus SET name_national=N'Ракитово', name_latin=N'Rakitovo', abac_name=N'Rakitovo', display_name=N'Ракитово-Rakitovo' WHERE id=2786;
UPDATE laus SET name_national=N'Септември', name_latin=N'Septemvri', abac_name=N'Septemvri', display_name=N'Септември-Septemvri' WHERE id=2787;
UPDATE laus SET name_national=N'Стрелча', name_latin=N'Strelcha', abac_name=N'Strelcha', display_name=N'Стрелча-Strelcha' WHERE id=2788;
UPDATE laus SET name_national=N'Асеновград', name_latin=N'Asenovgrad', abac_name=N'Asenovgrad', display_name=N'Асеновград-Asenovgrad' WHERE id=2789;
UPDATE laus SET name_national=N'Брезово', name_latin=N'Brezovo', abac_name=N'Brezovo', display_name=N'Брезово-Brezovo' WHERE id=2790;
UPDATE laus SET name_national=N'Калояново', name_latin=N'Kaloyanovo', abac_name=N'Kaloianovo', display_name=N'Калояново-Kaloyanovo' WHERE id=2791;
UPDATE laus SET name_national=N'Карлово', name_latin=N'Karlovo', abac_name=N'Karlovo', display_name=N'Карлово-Karlovo' WHERE id=2792;
UPDATE laus SET name_national=N'Лъки', name_latin=N'Laki', abac_name=N'L''ki', display_name=N'Лъки-Laki' WHERE id=2793;
UPDATE laus SET name_national=N'Марица', name_latin=N'Maritsa', abac_name=N'Maritsa', display_name=N'Марица-Maritsa' WHERE id=2794;
UPDATE laus SET name_national=N'Пловдив', name_latin=N'Plovdiv', abac_name=N'Plovdiv', display_name=N'Пловдив-Plovdiv' WHERE id=2795;
UPDATE laus SET name_national=N'Първомай', name_latin=N'Parvomay', abac_name=N'P''rvomai', display_name=N'Първомай-Parvomay' WHERE id=2796;
UPDATE laus SET name_national=N'Раковски', name_latin=N'Rakovski', abac_name=N'Rakovski', display_name=N'Раковски-Rakovski' WHERE id=2797;
UPDATE laus SET name_national=N'Родопи', name_latin=N'Rodopi', abac_name=N'Rodopi', display_name=N'Родопи-Rodopi' WHERE id=2798;
UPDATE laus SET name_national=N'Садово', name_latin=N'Sadovo', abac_name=N'Sadovo', display_name=N'Садово-Sadovo' WHERE id=2799;
UPDATE laus SET name_national=N'Съединение', name_latin=N'Saedinenie', abac_name=N'S''edinenie', display_name=N'Съединение-Saedinenie' WHERE id=2800;
UPDATE laus SET name_national=N'Хисаря', name_latin=N'Hisarya', abac_name=N'Khisaria', display_name=N'Хисаря-Hisarya' WHERE id=2801;
UPDATE laus SET name_national=N'Кричим', name_latin=N'Krichim', abac_name=N'Krichim', display_name=N'Кричим-Krichim' WHERE id=2802;
UPDATE laus SET name_national=N'Перущица', name_latin=N'Perushtitsa', abac_name=N'Perushchitsa', display_name=N'Перущица-Perushtitsa' WHERE id=2803;
UPDATE laus SET name_national=N'Стамболийски', name_latin=N'Stamboliyski', abac_name=N'Stamboliiski', display_name=N'Стамболийски-Stamboliyski' WHERE id=2804;
UPDATE laus SET name_national=N'Куклен', name_latin=N'Kuklen', abac_name=N'Kuklen', display_name=N'Куклен-Kuklen' WHERE id=2805;
UPDATE laus SET name_national=N'Сопот', name_latin=N'Sopot', abac_name=N'Sopot', display_name=N'Сопот-Sopot' WHERE id=2806;
UPDATE laus SET name_national=N'Брезник', name_latin=N'Breznik', abac_name=N'Breznik', display_name=N'Брезник-Breznik' WHERE id=2807;
UPDATE laus SET name_national=N'Земен', name_latin=N'Zemen', abac_name=N'Zemen', display_name=N'Земен-Zemen' WHERE id=2808;
UPDATE laus SET name_national=N'Ковачевци', name_latin=N'Kovachevtsi', abac_name=N'Kovachevtsi', display_name=N'Ковачевци-Kovachevtsi' WHERE id=2809;
UPDATE laus SET name_national=N'Перник', name_latin=N'Pernik', abac_name=N'Pernik', display_name=N'Перник-Pernik' WHERE id=2810;
UPDATE laus SET name_national=N'Радомир', name_latin=N'Radomir', abac_name=N'Radomir', display_name=N'Радомир-Radomir' WHERE id=2811;
UPDATE laus SET name_national=N'Трън', name_latin=N'Tran', abac_name=N'Tr''n', display_name=N'Трън-Tran' WHERE id=2812;
UPDATE laus SET name_national=N'Белене', name_latin=N'Belene', abac_name=N'Belene', display_name=N'Белене-Belene' WHERE id=2813;
UPDATE laus SET name_national=N'Гулянци', name_latin=N'Gulyantsi', abac_name=N'Guliantsi', display_name=N'Гулянци-Gulyantsi' WHERE id=2814;
UPDATE laus SET name_national=N'Долна Митрополия', name_latin=N'Dolna Mitropolia', abac_name=N'Dolna Mitropoliia', display_name=N'Долна Митрополия-Dolna Mitropolia' WHERE id=2815;
UPDATE laus SET name_national=N'Долни Дъбник', name_latin=N'Dolni Dabnik', abac_name=N'Dolni D''bnik', display_name=N'Долни Дъбник-Dolni Dabnik' WHERE id=2816;
UPDATE laus SET name_national=N'Левски', name_latin=N'Levski', abac_name=N'Levski', display_name=N'Левски-Levski' WHERE id=2817;
UPDATE laus SET name_national=N'Никопол', name_latin=N'Nikopol', abac_name=N'Nikopol', display_name=N'Никопол-Nikopol' WHERE id=2818;
UPDATE laus SET name_national=N'Искър', name_latin=N'Iskar', abac_name=N'Isk''r', display_name=N'Искър-Iskar' WHERE id=2819;
UPDATE laus SET name_national=N'Плевен', name_latin=N'Pleven', abac_name=N'Pleven', display_name=N'Плевен-Pleven' WHERE id=2820;
UPDATE laus SET name_national=N'Пордим', name_latin=N'Pordim', abac_name=N'Pordim', display_name=N'Пордим-Pordim' WHERE id=2821;
UPDATE laus SET name_national=N'Червен бряг', name_latin=N'Cherven bryag', abac_name=N'Cherven briag', display_name=N'Червен бряг-Cherven bryag' WHERE id=2822;
UPDATE laus SET name_national=N'Кнежа', name_latin=N'Knezha', abac_name=N'Knezha', display_name=N'Кнежа-Knezha' WHERE id=2823;
UPDATE laus SET name_national=N'Завет', name_latin=N'Zavet', abac_name=N'Zavet', display_name=N'Завет-Zavet' WHERE id=2824;
UPDATE laus SET name_national=N'Исперих', name_latin=N'Isperih', abac_name=N'Isperikh', display_name=N'Исперих-Isperih' WHERE id=2825;
UPDATE laus SET name_national=N'Кубрат', name_latin=N'Kubrat', abac_name=N'Kubrat', display_name=N'Кубрат-Kubrat' WHERE id=2826;
UPDATE laus SET name_national=N'Лозница', name_latin=N'Loznitsa', abac_name=N'Loznitsa', display_name=N'Лозница-Loznitsa' WHERE id=2827;
UPDATE laus SET name_national=N'Разград', name_latin=N'Razgrad', abac_name=N'Razgrad', display_name=N'Разград-Razgrad' WHERE id=2828;
UPDATE laus SET name_national=N'Самуил', name_latin=N'Samuil', abac_name=N'Samuil', display_name=N'Самуил-Samuil' WHERE id=2829;
UPDATE laus SET name_national=N'Цар Калоян', name_latin=N'Tsar Kaloyan', abac_name=N'Tsar Kaloian', display_name=N'Цар Калоян-Tsar Kaloyan' WHERE id=2830;
UPDATE laus SET name_national=N'Борово', name_latin=N'Borovo', abac_name=N'Borovo', display_name=N'Борово-Borovo' WHERE id=2831;
UPDATE laus SET name_national=N'Бяла (Русе)', name_latin=N'Byala (Ruse)', abac_name=N'Biala (Ruse)', display_name=N'Бяла (Русе)-Byala (Ruse)' WHERE id=2832;
UPDATE laus SET name_national=N'Ветово', name_latin=N'Vetovo', abac_name=N'Vetovo', display_name=N'Ветово-Vetovo' WHERE id=2833;
UPDATE laus SET name_national=N'Две могили', name_latin=N'Dve mogili', abac_name=N'Dve mogili', display_name=N'Две могили-Dve mogili' WHERE id=2834;
UPDATE laus SET name_national=N'Иваново', name_latin=N'Ivanovo', abac_name=N'Ivanovo', display_name=N'Иваново-Ivanovo' WHERE id=2835;
UPDATE laus SET name_national=N'Русе', name_latin=N'Ruse', abac_name=N'Ruse', display_name=N'Русе-Ruse' WHERE id=2836;
UPDATE laus SET name_national=N'Сливо поле', name_latin=N'Slivo pole', abac_name=N'Slivo pole', display_name=N'Сливо поле-Slivo pole' WHERE id=2837;
UPDATE laus SET name_national=N'Ценово', name_latin=N'Tsenovo', abac_name=N'Tsenovo', display_name=N'Ценово-Tsenovo' WHERE id=2838;
UPDATE laus SET name_national=N'Божурище', name_latin=N'Bozhurishte', abac_name=N'Bozhurishche', display_name=N'Божурище-Bozhurishte' WHERE id=2839;
UPDATE laus SET name_national=N'Ботевград', name_latin=N'Botevgrad', abac_name=N'Botevgrad', display_name=N'Ботевград-Botevgrad' WHERE id=2840;
UPDATE laus SET name_national=N'Годеч', name_latin=N'Godech', abac_name=N'Godech', display_name=N'Годеч-Godech' WHERE id=2841;
UPDATE laus SET name_national=N'Горна Малина', name_latin=N'Gorna Malina', abac_name=N'Gorna Malina', display_name=N'Горна Малина-Gorna Malina' WHERE id=2842;
UPDATE laus SET name_national=N'Драгоман', name_latin=N'Dragoman', abac_name=N'Dragoman', display_name=N'Драгоман-Dragoman' WHERE id=2843;
UPDATE laus SET name_national=N'Елин Пелин', name_latin=N'Elin Pelin', abac_name=N'Elin Pelin', display_name=N'Елин Пелин-Elin Pelin' WHERE id=2844;
UPDATE laus SET name_national=N'Етрополе', name_latin=N'Etropole', abac_name=N'Etropole', display_name=N'Етрополе-Etropole' WHERE id=2845;
UPDATE laus SET name_national=N'Ихтиман', name_latin=N'Ihtiman', abac_name=N'Ikhtiman', display_name=N'Ихтиман-Ihtiman' WHERE id=2846;
UPDATE laus SET name_national=N'Копривщица', name_latin=N'Koprivshtitsa', abac_name=N'Koprivshchitsa', display_name=N'Копривщица-Koprivshtitsa' WHERE id=2847;
UPDATE laus SET name_national=N'Костенец', name_latin=N'Kostenets', abac_name=N'Kostenets', display_name=N'Костенец-Kostenets' WHERE id=2848;
UPDATE laus SET name_national=N'Костинброд', name_latin=N'Kostinbrod', abac_name=N'Kostinbrod', display_name=N'Костинброд-Kostinbrod' WHERE id=2849;
UPDATE laus SET name_national=N'Правец', name_latin=N'Pravets', abac_name=N'Pravets', display_name=N'Правец-Pravets' WHERE id=2850;
UPDATE laus SET name_national=N'Самоков', name_latin=N'Samokov', abac_name=N'Samokov', display_name=N'Самоков-Samokov' WHERE id=2851;
UPDATE laus SET name_national=N'Своге', name_latin=N'Svoge', abac_name=N'Svoge', display_name=N'Своге-Svoge' WHERE id=2852;
UPDATE laus SET name_national=N'Сливница', name_latin=N'Slivnitsa', abac_name=N'Slivnitsa', display_name=N'Сливница-Slivnitsa' WHERE id=2853;
UPDATE laus SET name_national=N'Златица', name_latin=N'Zlatitsa', abac_name=N'Zlatitsa', display_name=N'Златица-Zlatitsa' WHERE id=2854;
UPDATE laus SET name_national=N'Антон', name_latin=N'Anton', abac_name=N'Anton', display_name=N'Антон-Anton' WHERE id=2855;
UPDATE laus SET name_national=N'Пирдоп', name_latin=N'Pirdop', abac_name=N'Pirdop', display_name=N'Пирдоп-Pirdop' WHERE id=2856;
UPDATE laus SET name_national=N'Мирково', name_latin=N'Mirkovo', abac_name=N'Mirkovo', display_name=N'Мирково-Mirkovo' WHERE id=2857;
UPDATE laus SET name_national=N'Чавдар', name_latin=N'Chavdar', abac_name=N'Chavdar', display_name=N'Чавдар-Chavdar' WHERE id=2858;
UPDATE laus SET name_national=N'Челопеч', name_latin=N'Chelopech', abac_name=N'Chelopech', display_name=N'Челопеч-Chelopech' WHERE id=2859;
UPDATE laus SET name_national=N'Долна баня', name_latin=N'Dolna banya', abac_name=N'Dolna bania', display_name=N'Долна баня-Dolna banya' WHERE id=2860;
UPDATE laus SET name_national=N'Венец', name_latin=N'Venets', abac_name=N'Venets', display_name=N'Венец-Venets' WHERE id=2861;
UPDATE laus SET name_national=N'Върбица', name_latin=N'Varbitsa', abac_name=N'V''rbitsa', display_name=N'Върбица-Varbitsa' WHERE id=2862;
UPDATE laus SET name_national=N'Хитрино', name_latin=N'Hitrino', abac_name=N'Khitrino', display_name=N'Хитрино-Hitrino' WHERE id=2863;
UPDATE laus SET name_national=N'Каолиново', name_latin=N'Kaolinovo', abac_name=N'Kaolinovo', display_name=N'Каолиново-Kaolinovo' WHERE id=2864;
UPDATE laus SET name_national=N'Каспичан', name_latin=N'Kaspichan', abac_name=N'Kaspichan', display_name=N'Каспичан-Kaspichan' WHERE id=2865;
UPDATE laus SET name_national=N'Никола Козлево', name_latin=N'Nikola Kozlevo', abac_name=N'Nikola Kozlevo', display_name=N'Никола Козлево-Nikola Kozlevo' WHERE id=2866;
UPDATE laus SET name_national=N'Нови пазар', name_latin=N'Novi pazar', abac_name=N'Novi pazar', display_name=N'Нови пазар-Novi pazar' WHERE id=2867;
UPDATE laus SET name_national=N'Велики Преслав', name_latin=N'Veliki Preslav', abac_name=N'Veliki Preslav', display_name=N'Велики Преслав-Veliki Preslav' WHERE id=2868;
UPDATE laus SET name_national=N'Смядово', name_latin=N'Smyadovo', abac_name=N'Smiadovo', display_name=N'Смядово-Smyadovo' WHERE id=2869;
UPDATE laus SET name_national=N'Шумен', name_latin=N'Shumen', abac_name=N'Shumen', display_name=N'Шумен-Shumen' WHERE id=2870;
UPDATE laus SET name_national=N'Алфатар', name_latin=N'Alfatar', abac_name=N'Alfatar', display_name=N'Алфатар-Alfatar' WHERE id=2871;
UPDATE laus SET name_national=N'Главиница', name_latin=N'Glavinitsa', abac_name=N'Glavinitsa', display_name=N'Главиница-Glavinitsa' WHERE id=2872;
UPDATE laus SET name_national=N'Дулово', name_latin=N'Dulovo', abac_name=N'Dulovo', display_name=N'Дулово-Dulovo' WHERE id=2873;
UPDATE laus SET name_national=N'Кайнарджа', name_latin=N'Kaynardzha', abac_name=N'Kainardzha', display_name=N'Кайнарджа-Kaynardzha' WHERE id=2874;
UPDATE laus SET name_national=N'Силистра', name_latin=N'Silistra', abac_name=N'Silistra', display_name=N'Силистра-Silistra' WHERE id=2875;
UPDATE laus SET name_national=N'Ситово', name_latin=N'Sitovo', abac_name=N'Sitovo', display_name=N'Ситово-Sitovo' WHERE id=2876;
UPDATE laus SET name_national=N'Тутракан', name_latin=N'Tutrakan', abac_name=N'Tutrakan', display_name=N'Тутракан-Tutrakan' WHERE id=2877;
UPDATE laus SET name_national=N'Котел', name_latin=N'Kotel', abac_name=N'Kotel', display_name=N'Котел-Kotel' WHERE id=2878;
UPDATE laus SET name_national=N'Нова Загора', name_latin=N'Nova Zagora', abac_name=N'Nova Zagora', display_name=N'Нова Загора-Nova Zagora' WHERE id=2879;
UPDATE laus SET name_national=N'Сливен', name_latin=N'Sliven', abac_name=N'Sliven', display_name=N'Сливен-Sliven' WHERE id=2880;
UPDATE laus SET name_national=N'Твърдица', name_latin=N'Tvarditsa', abac_name=N'Tv''rditsa', display_name=N'Твърдица-Tvarditsa' WHERE id=2881;
UPDATE laus SET name_national=N'Баните', name_latin=N'Banite', abac_name=N'Banite', display_name=N'Баните-Banite' WHERE id=2882;
UPDATE laus SET name_national=N'Борино', name_latin=N'Borino', abac_name=N'Borino', display_name=N'Борино-Borino' WHERE id=2883;
UPDATE laus SET name_national=N'Девин', name_latin=N'Devin', abac_name=N'Devin', display_name=N'Девин-Devin' WHERE id=2884;
UPDATE laus SET name_national=N'Доспат', name_latin=N'Dospat', abac_name=N'Dospat', display_name=N'Доспат-Dospat' WHERE id=2885;
UPDATE laus SET name_national=N'Златоград', name_latin=N'Zlatograd', abac_name=N'Zlatograd', display_name=N'Златоград-Zlatograd' WHERE id=2886;
UPDATE laus SET name_national=N'Мадан', name_latin=N'Madan', abac_name=N'Madan', display_name=N'Мадан-Madan' WHERE id=2887;
UPDATE laus SET name_national=N'Неделино', name_latin=N'Nedelino', abac_name=N'Nedelino', display_name=N'Неделино-Nedelino' WHERE id=2888;
UPDATE laus SET name_national=N'Рудозем', name_latin=N'Rudozem', abac_name=N'Rudozem', display_name=N'Рудозем-Rudozem' WHERE id=2889;
UPDATE laus SET name_national=N'Смолян', name_latin=N'Smolyan', abac_name=N'Smolian', display_name=N'Смолян-Smolyan' WHERE id=2890;
UPDATE laus SET name_national=N'Чепеларе', name_latin=N'Chepelare', abac_name=N'Chepelare', display_name=N'Чепеларе-Chepelare' WHERE id=2891;
UPDATE laus SET name_national=N'Столична', name_latin=N'Stolichna', abac_name=N'Stolichna', display_name=N'Столична-Stolichna' WHERE id=2892;
UPDATE laus SET name_national=N'Братя Даскалови', name_latin=N'Bratya Daskalovi', abac_name=N'Bratia Daskalovi', display_name=N'Братя Даскалови-Bratya Daskalovi' WHERE id=2893;
UPDATE laus SET name_national=N'Гълъбово', name_latin=N'Galabovo', abac_name=N'G''l''bovo', display_name=N'Гълъбово-Galabovo' WHERE id=2894;
UPDATE laus SET name_national=N'Казанлък', name_latin=N'Kazanlak', abac_name=N'Kazanl''k', display_name=N'Казанлък-Kazanlak' WHERE id=2895;
UPDATE laus SET name_national=N'Мъглиж', name_latin=N'Maglizh', abac_name=N'M''glizh', display_name=N'Мъглиж-Maglizh' WHERE id=2896;
UPDATE laus SET name_national=N'Опан', name_latin=N'Opan', abac_name=N'Opan', display_name=N'Опан-Opan' WHERE id=2897;
UPDATE laus SET name_national=N'Павел баня', name_latin=N'Pavel banya', abac_name=N'Pavel bania', display_name=N'Павел баня-Pavel banya' WHERE id=2898;
UPDATE laus SET name_national=N'Раднево', name_latin=N'Radnevo', abac_name=N'Radnevo', display_name=N'Раднево-Radnevo' WHERE id=2899;
UPDATE laus SET name_national=N'Стара Загора', name_latin=N'Stara Zagora', abac_name=N'Stara Zagora', display_name=N'Стара Загора-Stara Zagora' WHERE id=2900;
UPDATE laus SET name_national=N'Чирпан', name_latin=N'Chirpan', abac_name=N'Chirpan', display_name=N'Чирпан-Chirpan' WHERE id=2901;
UPDATE laus SET name_national=N'Гурково', name_latin=N'Gurkovo', abac_name=N'Gurkovo', display_name=N'Гурково-Gurkovo' WHERE id=2902;
UPDATE laus SET name_national=N'Николаево', name_latin=N'Nikolaevo', abac_name=N'Nikolaevo', display_name=N'Николаево-Nikolaevo' WHERE id=2903;
UPDATE laus SET name_national=N'Антоново', name_latin=N'Antonovo', abac_name=N'Antonovo', display_name=N'Антоново-Antonovo' WHERE id=2904;
UPDATE laus SET name_national=N'Омуртаг', name_latin=N'Omurtag', abac_name=N'Omurtag', display_name=N'Омуртаг-Omurtag' WHERE id=2905;
UPDATE laus SET name_national=N'Опака', name_latin=N'Opaka', abac_name=N'Opaka', display_name=N'Опака-Opaka' WHERE id=2906;
UPDATE laus SET name_national=N'Попово', name_latin=N'Popovo', abac_name=N'Popovo', display_name=N'Попово-Popovo' WHERE id=2907;
UPDATE laus SET name_national=N'Търговище', name_latin=N'Targovishte', abac_name=N'T''rgovishche', display_name=N'Търговище-Targovishte' WHERE id=2908;
UPDATE laus SET name_national=N'Аврен', name_latin=N'Avren', abac_name=N'Avren', display_name=N'Аврен-Avren' WHERE id=2909;
UPDATE laus SET name_national=N'Аксаково', name_latin=N'Aksakovo', abac_name=N'Aksakovo', display_name=N'Аксаково-Aksakovo' WHERE id=2910;
UPDATE laus SET name_national=N'Белослав', name_latin=N'Beloslav', abac_name=N'Beloslav', display_name=N'Белослав-Beloslav' WHERE id=2911;
UPDATE laus SET name_national=N'Бяла (Варна)', name_latin=N'Byala (Varna)', abac_name=N'Biala (Varna)', display_name=N'Бяла (Варна)-Byala (Varna)' WHERE id=2912;
UPDATE laus SET name_national=N'Варна', name_latin=N'Varna', abac_name=N'Varna', display_name=N'Варна-Varna' WHERE id=2913;
UPDATE laus SET name_national=N'Ветрино', name_latin=N'Vetrino', abac_name=N'Vetrino', display_name=N'Ветрино-Vetrino' WHERE id=2914;
UPDATE laus SET name_national=N'Вълчи дол', name_latin=N'Valchi dol', abac_name=N'V''lchi dol', display_name=N'Вълчи дол-Valchi dol' WHERE id=2915;
UPDATE laus SET name_national=N'Долни чифлик', name_latin=N'Dolni chiflik', abac_name=N'Dolni chiflik', display_name=N'Долни чифлик-Dolni chiflik' WHERE id=2916;
UPDATE laus SET name_national=N'Девня', name_latin=N'Devnya', abac_name=N'Devnia', display_name=N'Девня-Devnya' WHERE id=2917;
UPDATE laus SET name_national=N'Дългопол', name_latin=N'Dalgopol', abac_name=N'D''lgopol', display_name=N'Дългопол-Dalgopol' WHERE id=2918;
UPDATE laus SET name_national=N'Провадия', name_latin=N'Provadia', abac_name=N'Provadiia', display_name=N'Провадия-Provadia' WHERE id=2919;
UPDATE laus SET name_national=N'Суворово', name_latin=N'Suvorovo', abac_name=N'Suvorovo', display_name=N'Суворово-Suvorovo' WHERE id=2920;
UPDATE laus SET name_national=N'Белоградчик', name_latin=N'Belogradchik', abac_name=N'Belogradchik', display_name=N'Белоградчик-Belogradchik' WHERE id=2921;
UPDATE laus SET name_national=N'Бойница', name_latin=N'Boynitsa', abac_name=N'Boinitsa', display_name=N'Бойница-Boynitsa' WHERE id=2922;
UPDATE laus SET name_national=N'Брегово', name_latin=N'Bregovo', abac_name=N'Bregovo', display_name=N'Брегово-Bregovo' WHERE id=2923;
UPDATE laus SET name_national=N'Видин', name_latin=N'Vidin', abac_name=N'Vidin', display_name=N'Видин-Vidin' WHERE id=2924;
UPDATE laus SET name_national=N'Грамада', name_latin=N'Gramada', abac_name=N'Gramada', display_name=N'Грамада-Gramada' WHERE id=2925;
UPDATE laus SET name_national=N'Димово', name_latin=N'Dimovo', abac_name=N'Dimovo', display_name=N'Димово-Dimovo' WHERE id=2926;
UPDATE laus SET name_national=N'Кула', name_latin=N'Kula', abac_name=N'Kula', display_name=N'Кула-Kula' WHERE id=2927;
UPDATE laus SET name_national=N'Макреш', name_latin=N'Makresh', abac_name=N'Makresh', display_name=N'Макреш-Makresh' WHERE id=2928;
UPDATE laus SET name_national=N'Ново село', name_latin=N'Novo selo', abac_name=N'Novo selo', display_name=N'Ново село-Novo selo' WHERE id=2929;
UPDATE laus SET name_national=N'Ружинци', name_latin=N'Ruzhintsi', abac_name=N'Ruzhintsi', display_name=N'Ружинци-Ruzhintsi' WHERE id=2930;
UPDATE laus SET name_national=N'Чупрене', name_latin=N'Chuprene', abac_name=N'Chuprene', display_name=N'Чупрене-Chuprene' WHERE id=2931;
UPDATE laus SET name_national=N'Борован', name_latin=N'Borovan', abac_name=N'Borovan', display_name=N'Борован-Borovan' WHERE id=2932;
UPDATE laus SET name_national=N'Бяла Слатина', name_latin=N'Byala Slatina', abac_name=N'Biala Slatina', display_name=N'Бяла Слатина-Byala Slatina' WHERE id=2933;
UPDATE laus SET name_national=N'Враца', name_latin=N'Vratsa', abac_name=N'Vratsa', display_name=N'Враца-Vratsa' WHERE id=2934;
UPDATE laus SET name_national=N'Козлодуй', name_latin=N'Kozloduy', abac_name=N'Kozlodui', display_name=N'Козлодуй-Kozloduy' WHERE id=2935;
UPDATE laus SET name_national=N'Криводол', name_latin=N'Krivodol', abac_name=N'Krivodol', display_name=N'Криводол-Krivodol' WHERE id=2936;
UPDATE laus SET name_national=N'Мездра', name_latin=N'Mezdra', abac_name=N'Mezdra', display_name=N'Мездра-Mezdra' WHERE id=2937;
UPDATE laus SET name_national=N'Мизия', name_latin=N'Mizia', abac_name=N'Miziia', display_name=N'Мизия-Mizia' WHERE id=2938;
UPDATE laus SET name_national=N'Оряхово', name_latin=N'Oryahovo', abac_name=N'Oriakhovo', display_name=N'Оряхово-Oryahovo' WHERE id=2939;
UPDATE laus SET name_national=N'Роман', name_latin=N'Roman', abac_name=N'Roman', display_name=N'Роман-Roman' WHERE id=2940;
UPDATE laus SET name_national=N'Хайредин', name_latin=N'Hayredin', abac_name=N'Khairedin', display_name=N'Хайредин-Hayredin' WHERE id=2941;
UPDATE laus SET name_national=N'Велико Търново', name_latin=N'Veliko Tarnovo', abac_name=N'Veliko T''rnovo', display_name=N'Велико Търново-Veliko Tarnovo' WHERE id=2942;
UPDATE laus SET name_national=N'Горна Оряховица', name_latin=N'Gorna Oryahovitsa', abac_name=N'Gorna Oriakhovitsa', display_name=N'Горна Оряховица-Gorna Oryahovitsa' WHERE id=2943;
UPDATE laus SET name_national=N'Елена', name_latin=N'Elena', abac_name=N'Elena', display_name=N'Елена-Elena' WHERE id=2944;
UPDATE laus SET name_national=N'Златарица', name_latin=N'Zlataritsa', abac_name=N'Zlataritsa', display_name=N'Златарица-Zlataritsa' WHERE id=2945;
UPDATE laus SET name_national=N'Лясковец', name_latin=N'Lyaskovets', abac_name=N'Liaskovets', display_name=N'Лясковец-Lyaskovets' WHERE id=2946;
UPDATE laus SET name_national=N'Павликени', name_latin=N'Pavlikeni', abac_name=N'Pavlikeni', display_name=N'Павликени-Pavlikeni' WHERE id=2947;
UPDATE laus SET name_national=N'Полски Тръмбеш', name_latin=N'Polski Trambesh', abac_name=N'Polski Tr''mbesh', display_name=N'Полски Тръмбеш-Polski Trambesh' WHERE id=2948;
UPDATE laus SET name_national=N'Свищов', name_latin=N'Svishtov', abac_name=N'Svishchov', display_name=N'Свищов-Svishtov' WHERE id=2949;
UPDATE laus SET name_national=N'Стражица', name_latin=N'Strazhitsa', abac_name=N'Strazhitsa', display_name=N'Стражица-Strazhitsa' WHERE id=2950;
UPDATE laus SET name_national=N'Сухиндол', name_latin=N'Suhindol', abac_name=N'Sukhindol', display_name=N'Сухиндол-Suhindol' WHERE id=2951;
UPDATE laus SET name_national=N'Сърница', name_latin=N'Sarnitsa', abac_name=N'S''rnitsa', display_name=N'Сърница-Sarnitsa' WHERE id=2952;

--265
--select nuts3, lau1, name_national, name_latin, abac_name, display_name, id 
--from laus where country_code = 'BG' order by name1 asc

