 -- SQL (names)
UPDATE laus SET name_national=N'Ajdovščina', name_latin=N'Ajdovščina', abac_name=N'Ajdovscina', display_name=N'Ajdovščina' WHERE id=84582;
UPDATE laus SET name_national=N'Ankaran', name_latin=N'Ankaran/Ancarano', abac_name=N'Ankaran', display_name=N'Ankaran' WHERE id=84793;
UPDATE laus SET name_national=N'Apače', name_latin=N'Apače', abac_name=N'Apace', display_name=N'Apače' WHERE id=84775;
UPDATE laus SET name_national=N'Beltinci', name_latin=N'Beltinci', abac_name=N'Beltinci', display_name=N'Beltinci' WHERE id=84583;
UPDATE laus SET name_national=N'Benedikt', name_latin=N'Benedikt', abac_name=N'Benedikt', display_name=N'Benedikt' WHERE id=84728;
UPDATE laus SET name_national=N'Bistrica ob Sotli', name_latin=N'Bistrica ob Sotli', abac_name=N'Bistrica ob Sotli', display_name=N'Bistrica ob Sotli' WHERE id=84729;
UPDATE laus SET name_national=N'Bled', name_latin=N'Bled', abac_name=N'Bled', display_name=N'Bled' WHERE id=84584;
UPDATE laus SET name_national=N'Bloke', name_latin=N'Bloke', abac_name=N'Bloke', display_name=N'Bloke' WHERE id=84730;
UPDATE laus SET name_national=N'Bohinj', name_latin=N'Bohinj', abac_name=N'Bohinj', display_name=N'Bohinj' WHERE id=84585;
UPDATE laus SET name_national=N'Borovnica', name_latin=N'Borovnica', abac_name=N'Borovnica', display_name=N'Borovnica' WHERE id=84586;
UPDATE laus SET name_national=N'Bovec', name_latin=N'Bovec', abac_name=N'Bovec', display_name=N'Bovec' WHERE id=84587;
UPDATE laus SET name_national=N'Braslovče', name_latin=N'Braslovče', abac_name=N'Braslovce', display_name=N'Braslovče' WHERE id=84731;
UPDATE laus SET name_national=N'Brda', name_latin=N'Brda', abac_name=N'Brda', display_name=N'Brda' WHERE id=84588;
UPDATE laus SET name_national=N'Brežice', name_latin=N'Brežice', abac_name=N'Brezice', display_name=N'Brežice' WHERE id=84590;
UPDATE laus SET name_national=N'Brezovica', name_latin=N'Brezovica', abac_name=N'Brezovica', display_name=N'Brezovica' WHERE id=84589;
UPDATE laus SET name_national=N'Cankova', name_latin=N'Cankova', abac_name=N'Cankova', display_name=N'Cankova' WHERE id=84732;
UPDATE laus SET name_national=N'Celje', name_latin=N'Celje', abac_name=N'Celje', display_name=N'Celje' WHERE id=84592;
UPDATE laus SET name_national=N'Cerklje na Gorenjskem', name_latin=N'Cerklje na Gorenjskem', abac_name=N'Cerklje na Gorenjskem', display_name=N'Cerklje na Gorenjskem' WHERE id=84593;
UPDATE laus SET name_national=N'Cerknica', name_latin=N'Cerknica', abac_name=N'Cerknica', display_name=N'Cerknica' WHERE id=84594;
UPDATE laus SET name_national=N'Cerkno', name_latin=N'Cerkno', abac_name=N'Cerkno', display_name=N'Cerkno' WHERE id=84595;
UPDATE laus SET name_national=N'Cerkvenjak', name_latin=N'Cerkvenjak', abac_name=N'Cerkvenjak', display_name=N'Cerkvenjak' WHERE id=84733;
UPDATE laus SET name_national=N'Cirkulane', name_latin=N'Cirkulane', abac_name=N'Cirkulane', display_name=N'Cirkulane' WHERE id=84776;
UPDATE laus SET name_national=N'Črenšovci', name_latin=N'Črenšovci', abac_name=N'Crensovci', display_name=N'Črenšovci' WHERE id=84596;
UPDATE laus SET name_national=N'Črna na Koroškem', name_latin=N'Črna na Koroškem', abac_name=N'Crna na Koroskem', display_name=N'Črna na Koroškem' WHERE id=84597;
UPDATE laus SET name_national=N'Črnomelj', name_latin=N'Črnomelj', abac_name=N'Crnomelj', display_name=N'Črnomelj' WHERE id=84598;
UPDATE laus SET name_national=N'Destrnik', name_latin=N'Destrnik', abac_name=N'Destrnik', display_name=N'Destrnik' WHERE id=84599;
UPDATE laus SET name_national=N'Divača', name_latin=N'Divača', abac_name=N'Divaca', display_name=N'Divača' WHERE id=84600;
UPDATE laus SET name_national=N'Dobje', name_latin=N'Dobje', abac_name=N'Dobje', display_name=N'Dobje' WHERE id=84734;
UPDATE laus SET name_national=N'Dobrepolje', name_latin=N'Dobrepolje', abac_name=N'Dobrepolje', display_name=N'Dobrepolje' WHERE id=84601;
UPDATE laus SET name_national=N'Dobrna', name_latin=N'Dobrna', abac_name=N'Dobrna', display_name=N'Dobrna' WHERE id=84735;
UPDATE laus SET name_national=N'Dobrova - Polhov Gradec', name_latin=N'Dobrova - Polhov Gradec', abac_name=N'Dobrova - Polhov Gradec', display_name=N'Dobrova - Polhov Gradec' WHERE id=84602;
UPDATE laus SET name_national=N'Dobrovnik', name_latin=N'Dobrovnik/Dobronak', abac_name=N'Dobrovnik', display_name=N'Dobrovnik' WHERE id=84736;
UPDATE laus SET name_national=N'Dol pri Ljubljani', name_latin=N'Dol pri Ljubljani', abac_name=N'Dol pri Ljubljani', display_name=N'Dol pri Ljubljani' WHERE id=84603;
UPDATE laus SET name_national=N'Dolenjske Toplice', name_latin=N'Dolenjske Toplice', abac_name=N'Dolenjske Toplice', display_name=N'Dolenjske Toplice' WHERE id=84737;
UPDATE laus SET name_national=N'Domžale', name_latin=N'Domžale', abac_name=N'Domzale', display_name=N'Domžale' WHERE id=84604;
UPDATE laus SET name_national=N'Dornava', name_latin=N'Dornava', abac_name=N'Dornava', display_name=N'Dornava' WHERE id=84605;
UPDATE laus SET name_national=N'Dravograd', name_latin=N'Dravograd', abac_name=N'Dravograd', display_name=N'Dravograd' WHERE id=84606;
UPDATE laus SET name_national=N'Duplek', name_latin=N'Duplek', abac_name=N'Duplek', display_name=N'Duplek' WHERE id=84607;
UPDATE laus SET name_national=N'Gorenja vas - Poljane', name_latin=N'Gorenja vas - Poljane', abac_name=N'Gorenja vas - Poljane', display_name=N'Gorenja vas - Poljane' WHERE id=84608;
UPDATE laus SET name_national=N'Gorišnica', name_latin=N'Gorišnica', abac_name=N'Gorisnica', display_name=N'Gorišnica' WHERE id=84609;
UPDATE laus SET name_national=N'Gorje', name_latin=N'Gorje', abac_name=N'Gorje', display_name=N'Gorje' WHERE id=84787;
UPDATE laus SET name_national=N'Gornja Radgona', name_latin=N'Gornja Radgona', abac_name=N'Gornja Radgona', display_name=N'Gornja Radgona' WHERE id=84610;
UPDATE laus SET name_national=N'Gornji Grad', name_latin=N'Gornji Grad', abac_name=N'Gornji Grad', display_name=N'Gornji Grad' WHERE id=84611;
UPDATE laus SET name_national=N'Gornji Petrovci', name_latin=N'Gornji Petrovci', abac_name=N'Gornji Petrovci', display_name=N'Gornji Petrovci' WHERE id=84612;
UPDATE laus SET name_national=N'Grad', name_latin=N'Grad', abac_name=N'Grad', display_name=N'Grad' WHERE id=84738;
UPDATE laus SET name_national=N'Grosuplje', name_latin=N'Grosuplje', abac_name=N'Grosuplje', display_name=N'Grosuplje' WHERE id=84613;
UPDATE laus SET name_national=N'Hajdina', name_latin=N'Hajdina', abac_name=N'Hajdina', display_name=N'Hajdina' WHERE id=84739;
UPDATE laus SET name_national=N'Hoče - Slivnica', name_latin=N'Hoče - Slivnica', abac_name=N'Hoce - Slivnica', display_name=N'Hoče - Slivnica' WHERE id=84740;
UPDATE laus SET name_national=N'Hodoš', name_latin=N'Hodoš/Hodos', abac_name=N'Hodos', display_name=N'Hodoš' WHERE id=84741;
UPDATE laus SET name_national=N'Horjul', name_latin=N'Horjul', abac_name=N'Horjul', display_name=N'Horjul' WHERE id=84742;
UPDATE laus SET name_national=N'Hrastnik', name_latin=N'Hrastnik', abac_name=N'Hrastnik', display_name=N'Hrastnik' WHERE id=84615;
UPDATE laus SET name_national=N'Hrpelje - Kozina', name_latin=N'Hrpelje - Kozina', abac_name=N'Hrpelje - Kozina', display_name=N'Hrpelje - Kozina' WHERE id=84616;
UPDATE laus SET name_national=N'Idrija', name_latin=N'Idrija', abac_name=N'Idrija', display_name=N'Idrija' WHERE id=84617;
UPDATE laus SET name_national=N'Ig', name_latin=N'Ig', abac_name=N'Ig', display_name=N'Ig' WHERE id=84618;
UPDATE laus SET name_national=N'Ilirska Bistrica', name_latin=N'Ilirska Bistrica', abac_name=N'Ilirska Bistrica', display_name=N'Ilirska Bistrica' WHERE id=84619;
UPDATE laus SET name_national=N'Ivančna Gorica', name_latin=N'Ivančna Gorica', abac_name=N'Ivancna Gorica', display_name=N'Ivančna Gorica' WHERE id=84620;
UPDATE laus SET name_national=N'Izola', name_latin=N'Izola/Isola', abac_name=N'Izola', display_name=N'Izola' WHERE id=84621;
UPDATE laus SET name_national=N'Jesenice', name_latin=N'Jesenice', abac_name=N'Jesenice', display_name=N'Jesenice' WHERE id=84622;
UPDATE laus SET name_national=N'Jezersko', name_latin=N'Jezersko', abac_name=N'Jezersko', display_name=N'Jezersko' WHERE id=84743;
UPDATE laus SET name_national=N'Juršinci', name_latin=N'Juršinci', abac_name=N'Jursinci', display_name=N'Juršinci' WHERE id=84623;
UPDATE laus SET name_national=N'Kamnik', name_latin=N'Kamnik', abac_name=N'Kamnik', display_name=N'Kamnik' WHERE id=84624;
UPDATE laus SET name_national=N'Kanal', name_latin=N'Kanal', abac_name=N'Kanal', display_name=N'Kanal' WHERE id=84625;
UPDATE laus SET name_national=N'Kidričevo', name_latin=N'Kidričevo', abac_name=N'Kidricevo', display_name=N'Kidričevo' WHERE id=84626;
UPDATE laus SET name_national=N'Kobarid', name_latin=N'Kobarid', abac_name=N'Kobarid', display_name=N'Kobarid' WHERE id=84627;
UPDATE laus SET name_national=N'Kobilje', name_latin=N'Kobilje', abac_name=N'Kobilje', display_name=N'Kobilje' WHERE id=84628;
UPDATE laus SET name_national=N'Kočevje', name_latin=N'Kočevje', abac_name=N'Kocevje', display_name=N'Kočevje' WHERE id=84629;
UPDATE laus SET name_national=N'Komen', name_latin=N'Komen', abac_name=N'Komen', display_name=N'Komen' WHERE id=84630;
UPDATE laus SET name_national=N'Komenda', name_latin=N'Komenda', abac_name=N'Komenda', display_name=N'Komenda' WHERE id=84744;
UPDATE laus SET name_national=N'Koper', name_latin=N'Koper/Capodistria', abac_name=N'Koper', display_name=N'Koper' WHERE id=84631;
UPDATE laus SET name_national=N'Kostanjevica na Krki', name_latin=N'Kostanjevica na Krki', abac_name=N'Kostanjevica na Krki', display_name=N'Kostanjevica na Krki' WHERE id=84777;
UPDATE laus SET name_national=N'Kostel', name_latin=N'Kostel', abac_name=N'Kostel', display_name=N'Kostel' WHERE id=84745;
UPDATE laus SET name_national=N'Kozje', name_latin=N'Kozje', abac_name=N'Kozje', display_name=N'Kozje' WHERE id=84632;
UPDATE laus SET name_national=N'Kranj', name_latin=N'Kranj', abac_name=N'Kranj', display_name=N'Kranj' WHERE id=84633;
UPDATE laus SET name_national=N'Kranjska Gora', name_latin=N'Kranjska Gora', abac_name=N'Kranjska Gora', display_name=N'Kranjska Gora' WHERE id=84634;
UPDATE laus SET name_national=N'Križevci', name_latin=N'Križevci', abac_name=N'Krizevci', display_name=N'Križevci' WHERE id=84746;
UPDATE laus SET name_national=N'Krško', name_latin=N'Krško', abac_name=N'Krsko', display_name=N'Krško' WHERE id=84635;
UPDATE laus SET name_national=N'Kungota', name_latin=N'Kungota', abac_name=N'Kungota', display_name=N'Kungota' WHERE id=84636;
UPDATE laus SET name_national=N'Kuzma', name_latin=N'Kuzma', abac_name=N'Kuzma', display_name=N'Kuzma' WHERE id=84637;
UPDATE laus SET name_national=N'Laško', name_latin=N'Laško', abac_name=N'Lasko', display_name=N'Laško' WHERE id=84638;
UPDATE laus SET name_national=N'Lenart', name_latin=N'Lenart', abac_name=N'Lenart', display_name=N'Lenart' WHERE id=84639;
UPDATE laus SET name_national=N'Lendava', name_latin=N'Lendava/Lendva', abac_name=N'Lendava', display_name=N'Lendava' WHERE id=84640;
UPDATE laus SET name_national=N'Litija', name_latin=N'Litija', abac_name=N'Litija', display_name=N'Litija' WHERE id=84641;
UPDATE laus SET name_national=N'Ljubljana', name_latin=N'Ljubljana', abac_name=N'Ljubljana', display_name=N'Ljubljana' WHERE id=84642;
UPDATE laus SET name_national=N'Ljubno', name_latin=N'Ljubno', abac_name=N'Ljubno', display_name=N'Ljubno' WHERE id=84643;
UPDATE laus SET name_national=N'Ljutomer', name_latin=N'Ljutomer', abac_name=N'Ljutomer', display_name=N'Ljutomer' WHERE id=84644;
UPDATE laus SET name_national=N'Log - Dragomer', name_latin=N'Log - Dragomer', abac_name=N'Log - Dragomer', display_name=N'Log - Dragomer' WHERE id=84788;
UPDATE laus SET name_national=N'Logatec', name_latin=N'Logatec', abac_name=N'Logatec', display_name=N'Logatec' WHERE id=84645;
UPDATE laus SET name_national=N'Loška dolina', name_latin=N'Loška dolina', abac_name=N'Loska dolina', display_name=N'Loška dolina' WHERE id=84646;
UPDATE laus SET name_national=N'Loški Potok', name_latin=N'Loški Potok', abac_name=N'Loski Potok', display_name=N'Loški Potok' WHERE id=84647;
UPDATE laus SET name_national=N'Lovrenc na Pohorju', name_latin=N'Lovrenc na Pohorju', abac_name=N'Lovrenc na Pohorju', display_name=N'Lovrenc na Pohorju' WHERE id=84747;
UPDATE laus SET name_national=N'Luče', name_latin=N'Luče', abac_name=N'Luce', display_name=N'Luče' WHERE id=84648;
UPDATE laus SET name_national=N'Lukovica', name_latin=N'Lukovica', abac_name=N'Lukovica', display_name=N'Lukovica' WHERE id=84649;
UPDATE laus SET name_national=N'Majšperk', name_latin=N'Majšperk', abac_name=N'Majsperk', display_name=N'Majšperk' WHERE id=84650;
UPDATE laus SET name_national=N'Makole', name_latin=N'Makole', abac_name=N'Makole', display_name=N'Makole' WHERE id=84778;
UPDATE laus SET name_national=N'Maribor', name_latin=N'Maribor', abac_name=N'Maribor', display_name=N'Maribor' WHERE id=84651;
UPDATE laus SET name_national=N'Markovci', name_latin=N'Markovci', abac_name=N'Markovci', display_name=N'Markovci' WHERE id=84748;
UPDATE laus SET name_national=N'Medvode', name_latin=N'Medvode', abac_name=N'Medvode', display_name=N'Medvode' WHERE id=84652;
UPDATE laus SET name_national=N'Mengeš', name_latin=N'Mengeš', abac_name=N'Menges', display_name=N'Mengeš' WHERE id=84653;
UPDATE laus SET name_national=N'Metlika', name_latin=N'Metlika', abac_name=N'Metlika', display_name=N'Metlika' WHERE id=84654;
UPDATE laus SET name_national=N'Mežica', name_latin=N'Mežica', abac_name=N'Mezica', display_name=N'Mežica' WHERE id=84655;
UPDATE laus SET name_national=N'Miklavž na Dravskem polju', name_latin=N'Miklavž na Dravskem polju', abac_name=N'Miklavz na Dravskem polju', display_name=N'Miklavž na Dravskem polju' WHERE id=84749;
UPDATE laus SET name_national=N'Miren - Kostanjevica', name_latin=N'Miren - Kostanjevica', abac_name=N'Miren - Kostanjevica', display_name=N'Miren - Kostanjevica' WHERE id=84656;
UPDATE laus SET name_national=N'Mirna', name_latin=N'Mirna', abac_name=N'Mirna', display_name=N'Mirna' WHERE id=84792;
UPDATE laus SET name_national=N'Mirna Peč', name_latin=N'Mirna Peč', abac_name=N'Mirna Pec', display_name=N'Mirna Peč' WHERE id=84750;
UPDATE laus SET name_national=N'Mislinja', name_latin=N'Mislinja', abac_name=N'Mislinja', display_name=N'Mislinja' WHERE id=84657;
UPDATE laus SET name_national=N'Mokronog - Trebelno', name_latin=N'Mokronog - Trebelno', abac_name=N'Mokronog - Trebelno', display_name=N'Mokronog - Trebelno' WHERE id=84779;
UPDATE laus SET name_national=N'Moravče', name_latin=N'Moravče', abac_name=N'Moravce', display_name=N'Moravče' WHERE id=84658;
UPDATE laus SET name_national=N'Moravske Toplice', name_latin=N'Moravske Toplice', abac_name=N'Moravske Toplice', display_name=N'Moravske Toplice' WHERE id=84659;
UPDATE laus SET name_national=N'Mozirje', name_latin=N'Mozirje', abac_name=N'Mozirje', display_name=N'Mozirje' WHERE id=84660;
UPDATE laus SET name_national=N'Murska Sobota', name_latin=N'Murska Sobota', abac_name=N'Murska Sobota', display_name=N'Murska Sobota' WHERE id=84661;
UPDATE laus SET name_national=N'Muta', name_latin=N'Muta', abac_name=N'Muta', display_name=N'Muta' WHERE id=84662;
UPDATE laus SET name_national=N'Naklo', name_latin=N'Naklo', abac_name=N'Naklo', display_name=N'Naklo' WHERE id=84663;
UPDATE laus SET name_national=N'Nazarje', name_latin=N'Nazarje', abac_name=N'Nazarje', display_name=N'Nazarje' WHERE id=84664;
UPDATE laus SET name_national=N'Nova Gorica', name_latin=N'Nova Gorica', abac_name=N'Nova Gorica', display_name=N'Nova Gorica' WHERE id=84665;
UPDATE laus SET name_national=N'Novo mesto', name_latin=N'Novo mesto', abac_name=N'Novo mesto', display_name=N'Novo mesto' WHERE id=84666;
UPDATE laus SET name_national=N'Odranci', name_latin=N'Odranci', abac_name=N'Odranci', display_name=N'Odranci' WHERE id=84667;
UPDATE laus SET name_national=N'Oplotnica', name_latin=N'Oplotnica', abac_name=N'Oplotnica', display_name=N'Oplotnica' WHERE id=84751;
UPDATE laus SET name_national=N'Ormož', name_latin=N'Ormož', abac_name=N'Ormoz', display_name=N'Ormož' WHERE id=84668;
UPDATE laus SET name_national=N'Osilnica', name_latin=N'Osilnica', abac_name=N'Osilnica', display_name=N'Osilnica' WHERE id=84669;
UPDATE laus SET name_national=N'Pesnica', name_latin=N'Pesnica', abac_name=N'Pesnica', display_name=N'Pesnica' WHERE id=84670;
UPDATE laus SET name_national=N'Piran', name_latin=N'Piran/Pirano', abac_name=N'Piran', display_name=N'Piran' WHERE id=84671;
UPDATE laus SET name_national=N'Pivka', name_latin=N'Pivka', abac_name=N'Pivka', display_name=N'Pivka' WHERE id=84672;
UPDATE laus SET name_national=N'Podčetrtek', name_latin=N'Podčetrtek', abac_name=N'Podcetrtek', display_name=N'Podčetrtek' WHERE id=84673;
UPDATE laus SET name_national=N'Podlehnik', name_latin=N'Podlehnik', abac_name=N'Podlehnik', display_name=N'Podlehnik' WHERE id=84752;
UPDATE laus SET name_national=N'Podvelka', name_latin=N'Podvelka', abac_name=N'Podvelka', display_name=N'Podvelka' WHERE id=84674;
UPDATE laus SET name_national=N'Poljčane', name_latin=N'Poljčane', abac_name=N'Poljcane', display_name=N'Poljčane' WHERE id=84780;
UPDATE laus SET name_national=N'Polzela', name_latin=N'Polzela', abac_name=N'Polzela', display_name=N'Polzela' WHERE id=84753;
UPDATE laus SET name_national=N'Postojna', name_latin=N'Postojna', abac_name=N'Postojna', display_name=N'Postojna' WHERE id=84675;
UPDATE laus SET name_national=N'Prebold', name_latin=N'Prebold', abac_name=N'Prebold', display_name=N'Prebold' WHERE id=84754;
UPDATE laus SET name_national=N'Preddvor', name_latin=N'Preddvor', abac_name=N'Preddvor', display_name=N'Preddvor' WHERE id=84676;
UPDATE laus SET name_national=N'Prevalje', name_latin=N'Prevalje', abac_name=N'Prevalje', display_name=N'Prevalje' WHERE id=84755;
UPDATE laus SET name_national=N'Ptuj', name_latin=N'Ptuj', abac_name=N'Ptuj', display_name=N'Ptuj' WHERE id=84677;
UPDATE laus SET name_national=N'Puconci', name_latin=N'Puconci', abac_name=N'Puconci', display_name=N'Puconci' WHERE id=84678;
UPDATE laus SET name_national=N'Rače - Fram', name_latin=N'Rače - Fram', abac_name=N'Race - Fram', display_name=N'Rače - Fram' WHERE id=84679;
UPDATE laus SET name_national=N'Radeče', name_latin=N'Radeče', abac_name=N'Radece', display_name=N'Radeče' WHERE id=84680;
UPDATE laus SET name_national=N'Radenci', name_latin=N'Radenci', abac_name=N'Radenci', display_name=N'Radenci' WHERE id=84681;
UPDATE laus SET name_national=N'Radlje ob Dravi', name_latin=N'Radlje ob Dravi', abac_name=N'Radlje ob Dravi', display_name=N'Radlje ob Dravi' WHERE id=84682;
UPDATE laus SET name_national=N'Radovljica', name_latin=N'Radovljica', abac_name=N'Radovljica', display_name=N'Radovljica' WHERE id=84683;
UPDATE laus SET name_national=N'Ravne na Koroškem', name_latin=N'Ravne na Koroškem', abac_name=N'Ravne na Koroskem', display_name=N'Ravne na Koroškem' WHERE id=84684;
UPDATE laus SET name_national=N'Razkrižje', name_latin=N'Razkrižje', abac_name=N'Razkrizje', display_name=N'Razkrižje' WHERE id=84756;
UPDATE laus SET name_national=N'Rečica ob Savinji', name_latin=N'Rečica ob Savinji', abac_name=N'Recica ob Savinji', display_name=N'Rečica ob Savinji' WHERE id=84789;
UPDATE laus SET name_national=N'Renče - Vogrsko', name_latin=N'Renče - Vogrsko', abac_name=N'Rence - Vogrsko', display_name=N'Renče - Vogrsko' WHERE id=84781;
UPDATE laus SET name_national=N'Ribnica', name_latin=N'Ribnica', abac_name=N'Ribnica', display_name=N'Ribnica' WHERE id=84685;
UPDATE laus SET name_national=N'Ribnica na Pohorju', name_latin=N'Ribnica na Pohorju', abac_name=N'Ribnica na Pohorju', display_name=N'Ribnica na Pohorju' WHERE id=84757;
UPDATE laus SET name_national=N'Rogaška Slatina', name_latin=N'Rogaška Slatina', abac_name=N'Rogaska Slatina', display_name=N'Rogaška Slatina' WHERE id=84687;
UPDATE laus SET name_national=N'Rogašovci', name_latin=N'Rogašovci', abac_name=N'Rogasovci', display_name=N'Rogašovci' WHERE id=84686;
UPDATE laus SET name_national=N'Rogatec', name_latin=N'Rogatec', abac_name=N'Rogatec', display_name=N'Rogatec' WHERE id=84688;
UPDATE laus SET name_national=N'Ruše', name_latin=N'Ruše', abac_name=N'Ruse', display_name=N'Ruše' WHERE id=84689;
UPDATE laus SET name_national=N'Šalovci', name_latin=N'Šalovci', abac_name=N'Salovci', display_name=N'Šalovci' WHERE id=84614;
UPDATE laus SET name_national=N'Selnica ob Dravi', name_latin=N'Selnica ob Dravi', abac_name=N'Selnica ob Dravi', display_name=N'Selnica ob Dravi' WHERE id=84758;
UPDATE laus SET name_national=N'Semič', name_latin=N'Semič', abac_name=N'Semic', display_name=N'Semič' WHERE id=84690;
UPDATE laus SET name_national=N'Šempeter - Vrtojba', name_latin=N'Šempeter - Vrtojba', abac_name=N'Sempeter - Vrtojba', display_name=N'Šempeter - Vrtojba' WHERE id=84763;
UPDATE laus SET name_national=N'Šenčur', name_latin=N'Šenčur', abac_name=N'Sencur', display_name=N'Šenčur' WHERE id=84698;
UPDATE laus SET name_national=N'Šentilj', name_latin=N'Šentilj', abac_name=N'Sentilj', display_name=N'Šentilj' WHERE id=84699;
UPDATE laus SET name_national=N'Šentjernej', name_latin=N'Šentjernej', abac_name=N'Sentjernej', display_name=N'Šentjernej' WHERE id=84700;
UPDATE laus SET name_national=N'Šentjur', name_latin=N'Šentjur', abac_name=N'Sentjur', display_name=N'Šentjur' WHERE id=84701;
UPDATE laus SET name_national=N'Šentrupert', name_latin=N'Šentrupert', abac_name=N'Sentrupert', display_name=N'Šentrupert' WHERE id=84791;
UPDATE laus SET name_national=N'Sevnica', name_latin=N'Sevnica', abac_name=N'Sevnica', display_name=N'Sevnica' WHERE id=84691;
UPDATE laus SET name_national=N'Sežana', name_latin=N'Sežana', abac_name=N'Sezana', display_name=N'Sežana' WHERE id=84692;
UPDATE laus SET name_national=N'Škocjan', name_latin=N'Škocjan', abac_name=N'Skocjan', display_name=N'Škocjan' WHERE id=84702;
UPDATE laus SET name_national=N'Škofja Loka', name_latin=N'Škofja Loka', abac_name=N'Skofja Loka', display_name=N'Škofja Loka' WHERE id=84703;
UPDATE laus SET name_national=N'Škofljica', name_latin=N'Škofljica', abac_name=N'Skofljica', display_name=N'Škofljica' WHERE id=84704;
UPDATE laus SET name_national=N'Slovenj Gradec', name_latin=N'Slovenj Gradec', abac_name=N'Slovenj Gradec', display_name=N'Slovenj Gradec' WHERE id=84693;
UPDATE laus SET name_national=N'Slovenska Bistrica', name_latin=N'Slovenska Bistrica', abac_name=N'Slovenska Bistrica', display_name=N'Slovenska Bistrica' WHERE id=84694;
UPDATE laus SET name_national=N'Slovenske Konjice', name_latin=N'Slovenske Konjice', abac_name=N'Slovenske Konjice', display_name=N'Slovenske Konjice' WHERE id=84695;
UPDATE laus SET name_national=N'Šmarje pri Jelšah', name_latin=N'Šmarje pri Jelšah', abac_name=N'Smarje pri Jelsah', display_name=N'Šmarje pri Jelšah' WHERE id=84705;
UPDATE laus SET name_national=N'Šmarješke Toplice', name_latin=N'Šmarješke Toplice', abac_name=N'Smarjeske Toplice', display_name=N'Šmarješke Toplice' WHERE id=84786;
UPDATE laus SET name_national=N'Šmartno ob Paki', name_latin=N'Šmartno ob Paki', abac_name=N'Smartno ob Paki', display_name=N'Šmartno ob Paki' WHERE id=84706;
UPDATE laus SET name_national=N'Šmartno pri Litiji', name_latin=N'Šmartno pri Litiji', abac_name=N'Smartno pri Litiji', display_name=N'Šmartno pri Litiji' WHERE id=84774;
UPDATE laus SET name_national=N'Sodražica', name_latin=N'Sodražica', abac_name=N'Sodrazica', display_name=N'Sodražica' WHERE id=84759;
UPDATE laus SET name_national=N'Solčava', name_latin=N'Solčava', abac_name=N'Solcava', display_name=N'Solčava' WHERE id=84760;
UPDATE laus SET name_national=N'Šoštanj', name_latin=N'Šoštanj', abac_name=N'Sostanj', display_name=N'Šoštanj' WHERE id=84707;
UPDATE laus SET name_national=N'Središče ob Dravi', name_latin=N'Središče ob Dravi', abac_name=N'Sredisce ob Dravi', display_name=N'Središče ob Dravi' WHERE id=84782;
UPDATE laus SET name_national=N'Starše', name_latin=N'Starše', abac_name=N'Starse', display_name=N'Starše' WHERE id=84696;
UPDATE laus SET name_national=N'Štore', name_latin=N'Štore', abac_name=N'Store', display_name=N'Štore' WHERE id=84708;
UPDATE laus SET name_national=N'Straža', name_latin=N'Straža', abac_name=N'Straza', display_name=N'Straža' WHERE id=84783;
UPDATE laus SET name_national=N'Sveta Ana', name_latin=N'Sveta Ana', abac_name=N'Sveta Ana', display_name=N'Sveta Ana' WHERE id=84761;
UPDATE laus SET name_national=N'Sveta Trojica v Slov. goricah', name_latin=N'Sveta Trojica v Slov. goricah', abac_name=N'Sveta Trojica v Slov. goricah', display_name=N'Sveta Trojica v Slov. goricah' WHERE id=84784;
UPDATE laus SET name_national=N'Sveti Andraž v Slov. goricah', name_latin=N'Sveti Andraž v Slov. goricah', abac_name=N'Sveti Andraz v Slov. goricah', display_name=N'Sveti Andraž v Slov. goricah' WHERE id=84762;
UPDATE laus SET name_national=N'Sveti Jurij ob Ščavnici', name_latin=N'Sveti Jurij ob Ščavnici', abac_name=N'Sveti Jurij ob Scavnici', display_name=N'Sveti Jurij ob Ščavnici' WHERE id=84697;
UPDATE laus SET name_national=N'Sveti Jurij v Slov. goricah', name_latin=N'Sveti Jurij v Slov. goricah', abac_name=N'Sveti Jurij v Slov. goricah', display_name=N'Sveti Jurij v Slov. goricah' WHERE id=84790;
UPDATE laus SET name_national=N'Sveti Tomaž', name_latin=N'Sveti Tomaž', abac_name=N'Sveti Tomaz', display_name=N'Sveti Tomaž' WHERE id=84785;
UPDATE laus SET name_national=N'Tabor', name_latin=N'Tabor', abac_name=N'Tabor', display_name=N'Tabor' WHERE id=84764;
UPDATE laus SET name_national=N'Tišina', name_latin=N'Tišina', abac_name=N'Tisina', display_name=N'Tišina' WHERE id=84591;
UPDATE laus SET name_national=N'Tolmin', name_latin=N'Tolmin', abac_name=N'Tolmin', display_name=N'Tolmin' WHERE id=84709;
UPDATE laus SET name_national=N'Trbovlje', name_latin=N'Trbovlje', abac_name=N'Trbovlje', display_name=N'Trbovlje' WHERE id=84710;
UPDATE laus SET name_national=N'Trebnje', name_latin=N'Trebnje', abac_name=N'Trebnje', display_name=N'Trebnje' WHERE id=84711;
UPDATE laus SET name_national=N'Trnovska vas', name_latin=N'Trnovska vas', abac_name=N'Trnovska vas', display_name=N'Trnovska vas' WHERE id=84765;
UPDATE laus SET name_national=N'Tržič', name_latin=N'Tržič', abac_name=N'Trzic', display_name=N'Tržič' WHERE id=84712;
UPDATE laus SET name_national=N'Trzin', name_latin=N'Trzin', abac_name=N'Trzin', display_name=N'Trzin' WHERE id=84766;
UPDATE laus SET name_national=N'Turnišče', name_latin=N'Turnišče', abac_name=N'Turnisce', display_name=N'Turnišče' WHERE id=84713;
UPDATE laus SET name_national=N'Velenje', name_latin=N'Velenje', abac_name=N'Velenje', display_name=N'Velenje' WHERE id=84714;
UPDATE laus SET name_national=N'Velika Polana', name_latin=N'Velika Polana', abac_name=N'Velika Polana', display_name=N'Velika Polana' WHERE id=84767;
UPDATE laus SET name_national=N'Velike Lašče', name_latin=N'Velike Lašče', abac_name=N'Velike Lasce', display_name=N'Velike Lašče' WHERE id=84715;
UPDATE laus SET name_national=N'Veržej', name_latin=N'Veržej', abac_name=N'Verzej', display_name=N'Veržej' WHERE id=84768;
UPDATE laus SET name_national=N'Videm', name_latin=N'Videm', abac_name=N'Videm', display_name=N'Videm' WHERE id=84716;
UPDATE laus SET name_national=N'Vipava', name_latin=N'Vipava', abac_name=N'Vipava', display_name=N'Vipava' WHERE id=84717;
UPDATE laus SET name_national=N'Vitanje', name_latin=N'Vitanje', abac_name=N'Vitanje', display_name=N'Vitanje' WHERE id=84718;
UPDATE laus SET name_national=N'Vodice', name_latin=N'Vodice', abac_name=N'Vodice', display_name=N'Vodice' WHERE id=84719;
UPDATE laus SET name_national=N'Vojnik', name_latin=N'Vojnik', abac_name=N'Vojnik', display_name=N'Vojnik' WHERE id=84720;
UPDATE laus SET name_national=N'Vransko', name_latin=N'Vransko', abac_name=N'Vransko', display_name=N'Vransko' WHERE id=84769;
UPDATE laus SET name_national=N'Vrhnika', name_latin=N'Vrhnika', abac_name=N'Vrhnika', display_name=N'Vrhnika' WHERE id=84721;
UPDATE laus SET name_national=N'Vuzenica', name_latin=N'Vuzenica', abac_name=N'Vuzenica', display_name=N'Vuzenica' WHERE id=84722;
UPDATE laus SET name_national=N'Zagorje ob Savi', name_latin=N'Zagorje ob Savi', abac_name=N'Zagorje ob Savi', display_name=N'Zagorje ob Savi' WHERE id=84723;
UPDATE laus SET name_national=N'Žalec', name_latin=N'Žalec', abac_name=N'Zalec', display_name=N'Žalec' WHERE id=84770;
UPDATE laus SET name_national=N'Zavrč', name_latin=N'Zavrč', abac_name=N'Zavrc', display_name=N'Zavrč' WHERE id=84724;
UPDATE laus SET name_national=N'Železniki', name_latin=N'Železniki', abac_name=N'Zelezniki', display_name=N'Železniki' WHERE id=84726;
UPDATE laus SET name_national=N'Žetale', name_latin=N'Žetale', abac_name=N'Zetale', display_name=N'Žetale' WHERE id=84771;
UPDATE laus SET name_national=N'Žiri', name_latin=N'Žiri', abac_name=N'Ziri', display_name=N'Žiri' WHERE id=84727;
UPDATE laus SET name_national=N'Žirovnica', name_latin=N'Žirovnica', abac_name=N'Zirovnica', display_name=N'Žirovnica' WHERE id=84772;
UPDATE laus SET name_national=N'Zreče', name_latin=N'Zreče', abac_name=N'Zrece', display_name=N'Zreče' WHERE id=84725;
UPDATE laus SET name_national=N'Žužemberk', name_latin=N'Žužemberk', abac_name=N'Zuzemberk', display_name=N'Žužemberk' WHERE id=84773;
--2123

--select nuts3, lau1, name_national, name_latin, abac_name, display_name, id 
--from laus where country_code = 'SI' order by name1 asc