-- Adedd new name columns
UPDATE laus SET name_national=N'ABRANTES', name_latin=N'ABRANTES', abac_name=N'ABRANTES', display_name=N'ABRANTES' WHERE id=80999;
UPDATE laus SET name_national=N'ÁGUEDA', name_latin=N'ÁGUEDA', abac_name=N'AGUEDA', display_name=N'ÁGUEDA' WHERE id=80803;
UPDATE laus SET name_national=N'AGUIAR DA BEIRA', name_latin=N'AGUIAR DA BEIRA', abac_name=N'AGUIAR DA BEIRA', display_name=N'AGUIAR DA BEIRA' WHERE id=80920;
UPDATE laus SET name_national=N'ALANDROAL', name_latin=N'ALANDROAL', abac_name=N'ALANDROAL', display_name=N'ALANDROAL' WHERE id=80890;
UPDATE laus SET name_national=N'ALBERGARIA-A-VELHA', name_latin=N'ALBERGARIA-A-VELHA', abac_name=N'ALBERGARIA-A-VELHA', display_name=N'ALBERGARIA-A-VELHA' WHERE id=80804;
UPDATE laus SET name_national=N'ALBUFEIRA', name_latin=N'ALBUFEIRA', abac_name=N'ALBUFEIRA', display_name=N'ALBUFEIRA' WHERE id=80904;
UPDATE laus SET name_national=N'ALCÁCER DO SAL', name_latin=N'ALCÁCER DO SAL', abac_name=N'ALCACER DO SAL', display_name=N'ALCÁCER DO SAL' WHERE id=81020;
UPDATE laus SET name_national=N'ALCANENA', name_latin=N'ALCANENA', abac_name=N'ALCANENA', display_name=N'ALCANENA' WHERE id=81000;
UPDATE laus SET name_national=N'ALCOBAÇA', name_latin=N'ALCOBAÇA', abac_name=N'ALCOBACA', display_name=N'ALCOBAÇA' WHERE id=80934;
UPDATE laus SET name_national=N'ALCOCHETE', name_latin=N'ALCOCHETE', abac_name=N'ALCOCHETE', display_name=N'ALCOCHETE' WHERE id=81021;
UPDATE laus SET name_national=N'ALCOUTIM', name_latin=N'ALCOUTIM', abac_name=N'ALCOUTIM', display_name=N'ALCOUTIM' WHERE id=80905;
UPDATE laus SET name_national=N'ALENQUER', name_latin=N'ALENQUER', abac_name=N'ALENQUER', display_name=N'ALENQUER' WHERE id=80950;
UPDATE laus SET name_national=N'ALFÂNDEGA DA FÉ', name_latin=N'ALFÂNDEGA DA FÉ', abac_name=N'ALFANDEGA DA FE', display_name=N'ALFÂNDEGA DA FÉ' WHERE id=80850;
UPDATE laus SET name_national=N'ALIJÓ', name_latin=N'ALIJÓ', abac_name=N'ALIJO', display_name=N'ALIJÓ' WHERE id=81043;
UPDATE laus SET name_national=N'ALJEZUR', name_latin=N'ALJEZUR', abac_name=N'ALJEZUR', display_name=N'ALJEZUR' WHERE id=80906;
UPDATE laus SET name_national=N'ALJUSTREL', name_latin=N'ALJUSTREL', abac_name=N'ALJUSTREL', display_name=N'ALJUSTREL' WHERE id=80822;
UPDATE laus SET name_national=N'ALMADA', name_latin=N'ALMADA', abac_name=N'ALMADA', display_name=N'ALMADA' WHERE id=81022;
UPDATE laus SET name_national=N'ALMEIDA', name_latin=N'ALMEIDA', abac_name=N'ALMEIDA', display_name=N'ALMEIDA' WHERE id=80921;
UPDATE laus SET name_national=N'ALMEIRIM', name_latin=N'ALMEIRIM', abac_name=N'ALMEIRIM', display_name=N'ALMEIRIM' WHERE id=81001;
UPDATE laus SET name_national=N'ALMODÔVAR', name_latin=N'ALMODÔVAR', abac_name=N'ALMODOVAR', display_name=N'ALMODÔVAR' WHERE id=80823;
UPDATE laus SET name_national=N'ALPIARÇA', name_latin=N'ALPIARÇA', abac_name=N'ALPIARCA', display_name=N'ALPIARÇA' WHERE id=81002;
UPDATE laus SET name_national=N'ALTER DO CHÃO', name_latin=N'ALTER DO CHÃO', abac_name=N'ALTER DO CHAO', display_name=N'ALTER DO CHÃO' WHERE id=80966;
UPDATE laus SET name_national=N'ALVAIÁZERE', name_latin=N'ALVAIÁZERE', abac_name=N'ALVAIAZERE', display_name=N'ALVAIÁZERE' WHERE id=80935;
UPDATE laus SET name_national=N'ALVITO', name_latin=N'ALVITO', abac_name=N'ALVITO', display_name=N'ALVITO' WHERE id=80824;
UPDATE laus SET name_national=N'AMADORA', name_latin=N'AMADORA', abac_name=N'AMADORA', display_name=N'AMADORA' WHERE id=80964;
UPDATE laus SET name_national=N'AMARANTE', name_latin=N'AMARANTE', abac_name=N'AMARANTE', display_name=N'AMARANTE' WHERE id=80981;
UPDATE laus SET name_national=N'AMARES', name_latin=N'AMARES', abac_name=N'AMARES', display_name=N'AMARES' WHERE id=80836;
UPDATE laus SET name_national=N'ANADIA', name_latin=N'ANADIA', abac_name=N'ANADIA', display_name=N'ANADIA' WHERE id=80805;
UPDATE laus SET name_national=N'ANGRA DO HEROÍSMO', name_latin=N'ANGRA DO HEROÍSMO', abac_name=N'ANGRA DO HEROISMO', display_name=N'ANGRA DO HEROÍSMO' WHERE id=81099;
UPDATE laus SET name_national=N'ANSIÃO', name_latin=N'ANSIÃO', abac_name=N'ANSIAO', display_name=N'ANSIÃO' WHERE id=80936;
UPDATE laus SET name_national=N'ARCOS DE VALDEVEZ', name_latin=N'ARCOS DE VALDEVEZ', abac_name=N'ARCOS DE VALDEVEZ', display_name=N'ARCOS DE VALDEVEZ' WHERE id=81033;
UPDATE laus SET name_national=N'ARGANIL', name_latin=N'ARGANIL', abac_name=N'ARGANIL', display_name=N'ARGANIL' WHERE id=80873;
UPDATE laus SET name_national=N'ARMAMAR', name_latin=N'ARMAMAR', abac_name=N'ARMAMAR', display_name=N'ARMAMAR' WHERE id=81057;
UPDATE laus SET name_national=N'AROUCA', name_latin=N'AROUCA', abac_name=N'AROUCA', display_name=N'AROUCA' WHERE id=80806;
UPDATE laus SET name_national=N'ARRAIOLOS', name_latin=N'ARRAIOLOS', abac_name=N'ARRAIOLOS', display_name=N'ARRAIOLOS' WHERE id=80891;
UPDATE laus SET name_national=N'ARRONCHES', name_latin=N'ARRONCHES', abac_name=N'ARRONCHES', display_name=N'ARRONCHES' WHERE id=80967;
UPDATE laus SET name_national=N'ARRUDA DOS VINHOS', name_latin=N'ARRUDA DOS VINHOS', abac_name=N'ARRUDA DOS VINHOS', display_name=N'ARRUDA DOS VINHOS' WHERE id=80951;
UPDATE laus SET name_national=N'AVEIRO', name_latin=N'AVEIRO', abac_name=N'AVEIRO', display_name=N'AVEIRO' WHERE id=80807;
UPDATE laus SET name_national=N'AVIS', name_latin=N'AVIS', abac_name=N'AVIS', display_name=N'AVIS' WHERE id=80968;
UPDATE laus SET name_national=N'AZAMBUJA', name_latin=N'AZAMBUJA', abac_name=N'AZAMBUJA', display_name=N'AZAMBUJA' WHERE id=80952;
UPDATE laus SET name_national=N'BAIÃO', name_latin=N'BAIÃO', abac_name=N'BAIAO', display_name=N'BAIÃO' WHERE id=80982;
UPDATE laus SET name_national=N'BARCELOS', name_latin=N'BARCELOS', abac_name=N'BARCELOS', display_name=N'BARCELOS' WHERE id=80837;
UPDATE laus SET name_national=N'BARRANCOS', name_latin=N'BARRANCOS', abac_name=N'BARRANCOS', display_name=N'BARRANCOS' WHERE id=80825;
UPDATE laus SET name_national=N'BARREIRO', name_latin=N'BARREIRO', abac_name=N'BARREIRO', display_name=N'BARREIRO' WHERE id=81023;
UPDATE laus SET name_national=N'BATALHA', name_latin=N'BATALHA', abac_name=N'BATALHA', display_name=N'BATALHA' WHERE id=80937;
UPDATE laus SET name_national=N'BEJA', name_latin=N'BEJA', abac_name=N'BEJA', display_name=N'BEJA' WHERE id=80826;
UPDATE laus SET name_national=N'BELMONTE', name_latin=N'BELMONTE', abac_name=N'BELMONTE', display_name=N'BELMONTE' WHERE id=80862;
UPDATE laus SET name_national=N'BENAVENTE', name_latin=N'BENAVENTE', abac_name=N'BENAVENTE', display_name=N'BENAVENTE' WHERE id=81003;
UPDATE laus SET name_national=N'BOMBARRAL', name_latin=N'BOMBARRAL', abac_name=N'BOMBARRAL', display_name=N'BOMBARRAL' WHERE id=80938;
UPDATE laus SET name_national=N'BORBA', name_latin=N'BORBA', abac_name=N'BORBA', display_name=N'BORBA' WHERE id=80892;
UPDATE laus SET name_national=N'BOTICAS', name_latin=N'BOTICAS', abac_name=N'BOTICAS', display_name=N'BOTICAS' WHERE id=81044;
UPDATE laus SET name_national=N'BRAGA', name_latin=N'BRAGA', abac_name=N'BRAGA', display_name=N'BRAGA' WHERE id=80838;
UPDATE laus SET name_national=N'BRAGANÇA', name_latin=N'BRAGANÇA', abac_name=N'BRAGANCA', display_name=N'BRAGANÇA' WHERE id=80851;
UPDATE laus SET name_national=N'CABECEIRAS DE BASTO', name_latin=N'CABECEIRAS DE BASTO', abac_name=N'CABECEIRAS DE BASTO', display_name=N'CABECEIRAS DE BASTO' WHERE id=80839;
UPDATE laus SET name_national=N'CADAVAL', name_latin=N'CADAVAL', abac_name=N'CADAVAL', display_name=N'CADAVAL' WHERE id=80953;
UPDATE laus SET name_national=N'CALDAS DA RAINHA', name_latin=N'CALDAS DA RAINHA', abac_name=N'CALDAS DA RAINHA', display_name=N'CALDAS DA RAINHA' WHERE id=80939;
UPDATE laus SET name_national=N'CALHETA (MADEIRA)', name_latin=N'CALHETA (MADEIRA)', abac_name=N'CALHETA (MADEIRA)', display_name=N'CALHETA (MADEIRA)' WHERE id=81081;
UPDATE laus SET name_national=N'CALHETA (SÃO JORGE)', name_latin=N'CALHETA (SÃO JORGE)', abac_name=N'CALHETA (SAO JORGE)', display_name=N'CALHETA (SÃO JORGE)' WHERE id=81102;
UPDATE laus SET name_national=N'CÂMARA DE LOBOS', name_latin=N'CÂMARA DE LOBOS', abac_name=N'CAMARA DE LOBOS', display_name=N'CÂMARA DE LOBOS' WHERE id=81082;
UPDATE laus SET name_national=N'CAMINHA', name_latin=N'CAMINHA', abac_name=N'CAMINHA', display_name=N'CAMINHA' WHERE id=81034;
UPDATE laus SET name_national=N'CAMPO MAIOR', name_latin=N'CAMPO MAIOR', abac_name=N'CAMPO MAIOR', display_name=N'CAMPO MAIOR' WHERE id=80969;
UPDATE laus SET name_national=N'CANTANHEDE', name_latin=N'CANTANHEDE', abac_name=N'CANTANHEDE', display_name=N'CANTANHEDE' WHERE id=80874;
UPDATE laus SET name_national=N'CARRAZEDA DE ANSIÃES', name_latin=N'CARRAZEDA DE ANSIÃES', abac_name=N'CARRAZEDA DE ANSIAES', display_name=N'CARRAZEDA DE ANSIÃES' WHERE id=80852;
UPDATE laus SET name_national=N'CARREGAL DO SAL', name_latin=N'CARREGAL DO SAL', abac_name=N'CARREGAL DO SAL', display_name=N'CARREGAL DO SAL' WHERE id=81058;
UPDATE laus SET name_national=N'CARTAXO', name_latin=N'CARTAXO', abac_name=N'CARTAXO', display_name=N'CARTAXO' WHERE id=81004;
UPDATE laus SET name_national=N'CASCAIS', name_latin=N'CASCAIS', abac_name=N'CASCAIS', display_name=N'CASCAIS' WHERE id=80954;
UPDATE laus SET name_national=N'CASTANHEIRA DE PÊRA', name_latin=N'CASTANHEIRA DE PÊRA', abac_name=N'CASTANHEIRA DE PERA', display_name=N'CASTANHEIRA DE PÊRA' WHERE id=80940;
UPDATE laus SET name_national=N'CASTELO BRANCO', name_latin=N'CASTELO BRANCO', abac_name=N'CASTELO BRANCO', display_name=N'CASTELO BRANCO' WHERE id=80863;
UPDATE laus SET name_national=N'CASTELO DE PAIVA', name_latin=N'CASTELO DE PAIVA', abac_name=N'CASTELO DE PAIVA', display_name=N'CASTELO DE PAIVA' WHERE id=80808;
UPDATE laus SET name_national=N'CASTELO DE VIDE', name_latin=N'CASTELO DE VIDE', abac_name=N'CASTELO DE VIDE', display_name=N'CASTELO DE VIDE' WHERE id=80970;
UPDATE laus SET name_national=N'CASTRO DAIRE', name_latin=N'CASTRO DAIRE', abac_name=N'CASTRO DAIRE', display_name=N'CASTRO DAIRE' WHERE id=81059;
UPDATE laus SET name_national=N'CASTRO MARIM', name_latin=N'CASTRO MARIM', abac_name=N'CASTRO MARIM', display_name=N'CASTRO MARIM' WHERE id=80907;
UPDATE laus SET name_national=N'CASTRO VERDE', name_latin=N'CASTRO VERDE', abac_name=N'CASTRO VERDE', display_name=N'CASTRO VERDE' WHERE id=80827;
UPDATE laus SET name_national=N'CELORICO DA BEIRA', name_latin=N'CELORICO DA BEIRA', abac_name=N'CELORICO DA BEIRA', display_name=N'CELORICO DA BEIRA' WHERE id=80922;
UPDATE laus SET name_national=N'CELORICO DE BASTO', name_latin=N'CELORICO DE BASTO', abac_name=N'CELORICO DE BASTO', display_name=N'CELORICO DE BASTO' WHERE id=80840;
UPDATE laus SET name_national=N'CHAMUSCA', name_latin=N'CHAMUSCA', abac_name=N'CHAMUSCA', display_name=N'CHAMUSCA' WHERE id=81005;
UPDATE laus SET name_national=N'CHAVES', name_latin=N'CHAVES', abac_name=N'CHAVES', display_name=N'CHAVES' WHERE id=81045;
UPDATE laus SET name_national=N'CINFÃES', name_latin=N'CINFÃES', abac_name=N'CINFAES', display_name=N'CINFÃES' WHERE id=81060;
UPDATE laus SET name_national=N'COIMBRA', name_latin=N'COIMBRA', abac_name=N'COIMBRA', display_name=N'COIMBRA' WHERE id=80875;
UPDATE laus SET name_national=N'CONDEIXA-A-NOVA', name_latin=N'CONDEIXA-A-NOVA', abac_name=N'CONDEIXA-A-NOVA', display_name=N'CONDEIXA-A-NOVA' WHERE id=80876;
UPDATE laus SET name_national=N'CONSTÂNCIA', name_latin=N'CONSTÂNCIA', abac_name=N'CONSTANCIA', display_name=N'CONSTÂNCIA' WHERE id=81006;
UPDATE laus SET name_national=N'CORUCHE', name_latin=N'CORUCHE', abac_name=N'CORUCHE', display_name=N'CORUCHE' WHERE id=81007;
UPDATE laus SET name_national=N'CORVO', name_latin=N'CORVO', abac_name=N'CORVO', display_name=N'CORVO' WHERE id=81110;
UPDATE laus SET name_national=N'COVILHÃ', name_latin=N'COVILHÃ', abac_name=N'COVILHA', display_name=N'COVILHÃ' WHERE id=80864;
UPDATE laus SET name_national=N'CRATO', name_latin=N'CRATO', abac_name=N'CRATO', display_name=N'CRATO' WHERE id=80971;
UPDATE laus SET name_national=N'CUBA', name_latin=N'CUBA', abac_name=N'CUBA', display_name=N'CUBA' WHERE id=80828;
UPDATE laus SET name_national=N'ELVAS', name_latin=N'ELVAS', abac_name=N'ELVAS', display_name=N'ELVAS' WHERE id=80972;
UPDATE laus SET name_national=N'ENTRONCAMENTO', name_latin=N'ENTRONCAMENTO', abac_name=N'ENTRONCAMENTO', display_name=N'ENTRONCAMENTO' WHERE id=81008;
UPDATE laus SET name_national=N'ESPINHO', name_latin=N'ESPINHO', abac_name=N'ESPINHO', display_name=N'ESPINHO' WHERE id=80809;
UPDATE laus SET name_national=N'ESPOSENDE', name_latin=N'ESPOSENDE', abac_name=N'ESPOSENDE', display_name=N'ESPOSENDE' WHERE id=80841;
UPDATE laus SET name_national=N'ESTARREJA', name_latin=N'ESTARREJA', abac_name=N'ESTARREJA', display_name=N'ESTARREJA' WHERE id=80810;
UPDATE laus SET name_national=N'ESTREMOZ', name_latin=N'ESTREMOZ', abac_name=N'ESTREMOZ', display_name=N'ESTREMOZ' WHERE id=80893;
UPDATE laus SET name_national=N'ÉVORA', name_latin=N'ÉVORA', abac_name=N'EVORA', display_name=N'ÉVORA' WHERE id=80894;
UPDATE laus SET name_national=N'FAFE', name_latin=N'FAFE', abac_name=N'FAFE', display_name=N'FAFE' WHERE id=80842;
UPDATE laus SET name_national=N'FARO', name_latin=N'FARO', abac_name=N'FARO', display_name=N'FARO' WHERE id=80908;
UPDATE laus SET name_national=N'FELGUEIRAS', name_latin=N'FELGUEIRAS', abac_name=N'FELGUEIRAS', display_name=N'FELGUEIRAS' WHERE id=80983;
UPDATE laus SET name_national=N'FERREIRA DO ALENTEJO', name_latin=N'FERREIRA DO ALENTEJO', abac_name=N'FERREIRA DO ALENTEJO', display_name=N'FERREIRA DO ALENTEJO' WHERE id=80829;
UPDATE laus SET name_national=N'FERREIRA DO ZÊZERE', name_latin=N'FERREIRA DO ZÊZERE', abac_name=N'FERREIRA DO ZEZERE', display_name=N'FERREIRA DO ZÊZERE' WHERE id=81009;
UPDATE laus SET name_national=N'FIGUEIRA DA FOZ', name_latin=N'FIGUEIRA DA FOZ', abac_name=N'FIGUEIRA DA FOZ', display_name=N'FIGUEIRA DA FOZ' WHERE id=80877;
UPDATE laus SET name_national=N'FIGUEIRA DE CASTELO RODRIGO', name_latin=N'FIGUEIRA DE CASTELO RODRIGO', abac_name=N'FIGUEIRA DE CASTELO RODRIGO', display_name=N'FIGUEIRA DE CASTELO RODRIGO' WHERE id=80923;
UPDATE laus SET name_national=N'FIGUEIRÓ DOS VINHOS', name_latin=N'FIGUEIRÓ DOS VINHOS', abac_name=N'FIGUEIRO DOS VINHOS', display_name=N'FIGUEIRÓ DOS VINHOS' WHERE id=80941;
UPDATE laus SET name_national=N'FORNOS DE ALGODRES', name_latin=N'FORNOS DE ALGODRES', abac_name=N'FORNOS DE ALGODRES', display_name=N'FORNOS DE ALGODRES' WHERE id=80924;
UPDATE laus SET name_national=N'FREIXO DE ESPADA À CINTA', name_latin=N'FREIXO DE ESPADA À CINTA', abac_name=N'FREIXO DE ESPADA A CINTA', display_name=N'FREIXO DE ESPADA À CINTA' WHERE id=80853;
UPDATE laus SET name_national=N'FRONTEIRA', name_latin=N'FRONTEIRA', abac_name=N'FRONTEIRA', display_name=N'FRONTEIRA' WHERE id=80973;
UPDATE laus SET name_national=N'FUNCHAL', name_latin=N'FUNCHAL', abac_name=N'FUNCHAL', display_name=N'FUNCHAL' WHERE id=81083;
UPDATE laus SET name_national=N'FUNDÃO', name_latin=N'FUNDÃO', abac_name=N'FUNDAO', display_name=N'FUNDÃO' WHERE id=80865;
UPDATE laus SET name_national=N'GAVIÃO', name_latin=N'GAVIÃO', abac_name=N'GAVIAO', display_name=N'GAVIÃO' WHERE id=80974;
UPDATE laus SET name_national=N'GÓIS', name_latin=N'GÓIS', abac_name=N'GOIS', display_name=N'GÓIS' WHERE id=80878;
UPDATE laus SET name_national=N'GOLEGÃ', name_latin=N'GOLEGÃ', abac_name=N'GOLEGA', display_name=N'GOLEGÃ' WHERE id=81010;
UPDATE laus SET name_national=N'GONDOMAR', name_latin=N'GONDOMAR', abac_name=N'GONDOMAR', display_name=N'GONDOMAR' WHERE id=80984;
UPDATE laus SET name_national=N'GOUVEIA', name_latin=N'GOUVEIA', abac_name=N'GOUVEIA', display_name=N'GOUVEIA' WHERE id=80925;
UPDATE laus SET name_national=N'GRÂNDOLA', name_latin=N'GRÂNDOLA', abac_name=N'GRANDOLA', display_name=N'GRÂNDOLA' WHERE id=81024;
UPDATE laus SET name_national=N'GUARDA', name_latin=N'GUARDA', abac_name=N'GUARDA', display_name=N'GUARDA' WHERE id=80926;
UPDATE laus SET name_national=N'GUIMARÃES', name_latin=N'GUIMARÃES', abac_name=N'GUIMARAES', display_name=N'GUIMARÃES' WHERE id=80843;
UPDATE laus SET name_national=N'HORTA', name_latin=N'HORTA', abac_name=N'HORTA', display_name=N'HORTA' WHERE id=81107;
UPDATE laus SET name_national=N'IDANHA-A-NOVA', name_latin=N'IDANHA-A-NOVA', abac_name=N'IDANHA-A-NOVA', display_name=N'IDANHA-A-NOVA' WHERE id=80866;
UPDATE laus SET name_national=N'ÍLHAVO', name_latin=N'ÍLHAVO', abac_name=N'ILHAVO', display_name=N'ÍLHAVO' WHERE id=80812;
UPDATE laus SET name_national=N'LAGOA (ALGARVE)', name_latin=N'LAGOA (ALGARVE)', abac_name=N'LAGOA (ALGARVE)', display_name=N'LAGOA (ALGARVE)' WHERE id=80909;
UPDATE laus SET name_national=N'LAGOA (SÃO MIGUEL)', name_latin=N'LAGOA (SÃO MIGUEL)', abac_name=N'LAGOA (SAO MIGUEL)', display_name=N'LAGOA (SÃO MIGUEL)' WHERE id=81093;
UPDATE laus SET name_national=N'LAGOS', name_latin=N'LAGOS', abac_name=N'LAGOS', display_name=N'LAGOS' WHERE id=80910;
UPDATE laus SET name_national=N'LAJES DAS FLORES', name_latin=N'LAJES DAS FLORES', abac_name=N'LAJES DAS FLORES', display_name=N'LAJES DAS FLORES' WHERE id=81108;
UPDATE laus SET name_national=N'LAJES DO PICO', name_latin=N'LAJES DO PICO', abac_name=N'LAJES DO PICO', display_name=N'LAJES DO PICO' WHERE id=81104;
UPDATE laus SET name_national=N'LAMEGO', name_latin=N'LAMEGO', abac_name=N'LAMEGO', display_name=N'LAMEGO' WHERE id=81061;
UPDATE laus SET name_national=N'LEIRIA', name_latin=N'LEIRIA', abac_name=N'LEIRIA', display_name=N'LEIRIA' WHERE id=80942;
UPDATE laus SET name_national=N'LISBOA', name_latin=N'LISBOA', abac_name=N'LISBOA', display_name=N'LISBOA' WHERE id=80955;
UPDATE laus SET name_national=N'LOULÉ', name_latin=N'LOULÉ', abac_name=N'LOULE', display_name=N'LOULÉ' WHERE id=80911;
UPDATE laus SET name_national=N'LOURES', name_latin=N'LOURES', abac_name=N'LOURES', display_name=N'LOURES' WHERE id=80956;
UPDATE laus SET name_national=N'LOURINHÃ', name_latin=N'LOURINHÃ', abac_name=N'LOURINHA', display_name=N'LOURINHÃ' WHERE id=80957;
UPDATE laus SET name_national=N'LOUSÃ', name_latin=N'LOUSÃ', abac_name=N'LOUSA', display_name=N'LOUSÃ' WHERE id=80879;
UPDATE laus SET name_national=N'LOUSADA', name_latin=N'LOUSADA', abac_name=N'LOUSADA', display_name=N'LOUSADA' WHERE id=80985;
UPDATE laus SET name_national=N'MAÇÃO', name_latin=N'MAÇÃO', abac_name=N'MACAO', display_name=N'MAÇÃO' WHERE id=81011;
UPDATE laus SET name_national=N'MACEDO DE CAVALEIROS', name_latin=N'MACEDO DE CAVALEIROS', abac_name=N'MACEDO DE CAVALEIROS', display_name=N'MACEDO DE CAVALEIROS' WHERE id=80854;
UPDATE laus SET name_national=N'MACHICO', name_latin=N'MACHICO', abac_name=N'MACHICO', display_name=N'MACHICO' WHERE id=81084;
UPDATE laus SET name_national=N'MADALENA', name_latin=N'MADALENA', abac_name=N'MADALENA', display_name=N'MADALENA' WHERE id=81105;
UPDATE laus SET name_national=N'MAFRA', name_latin=N'MAFRA', abac_name=N'MAFRA', display_name=N'MAFRA' WHERE id=80958;
UPDATE laus SET name_national=N'MAIA', name_latin=N'MAIA', abac_name=N'MAIA', display_name=N'MAIA' WHERE id=80986;
UPDATE laus SET name_national=N'MANGUALDE', name_latin=N'MANGUALDE', abac_name=N'MANGUALDE', display_name=N'MANGUALDE' WHERE id=81062;
UPDATE laus SET name_national=N'MANTEIGAS', name_latin=N'MANTEIGAS', abac_name=N'MANTEIGAS', display_name=N'MANTEIGAS' WHERE id=80927;
UPDATE laus SET name_national=N'MARCO DE CANAVESES', name_latin=N'MARCO DE CANAVESES', abac_name=N'MARCO DE CANAVESES', display_name=N'MARCO DE CANAVESES' WHERE id=80987;
UPDATE laus SET name_national=N'MARINHA GRANDE', name_latin=N'MARINHA GRANDE', abac_name=N'MARINHA GRANDE', display_name=N'MARINHA GRANDE' WHERE id=80943;
UPDATE laus SET name_national=N'MARVÃO', name_latin=N'MARVÃO', abac_name=N'MARVAO', display_name=N'MARVÃO' WHERE id=80975;
UPDATE laus SET name_national=N'MATOSINHOS', name_latin=N'MATOSINHOS', abac_name=N'MATOSINHOS', display_name=N'MATOSINHOS' WHERE id=80988;
UPDATE laus SET name_national=N'MEALHADA', name_latin=N'MEALHADA', abac_name=N'MEALHADA', display_name=N'MEALHADA' WHERE id=80813;
UPDATE laus SET name_national=N'MÊDA', name_latin=N'MÊDA', abac_name=N'MEDA', display_name=N'MÊDA' WHERE id=80928;
UPDATE laus SET name_national=N'MELGAÇO', name_latin=N'MELGAÇO', abac_name=N'MELGACO', display_name=N'MELGAÇO' WHERE id=81035;
UPDATE laus SET name_national=N'MÉRTOLA', name_latin=N'MÉRTOLA', abac_name=N'MERTOLA', display_name=N'MÉRTOLA' WHERE id=80830;
UPDATE laus SET name_national=N'MESÃO FRIO', name_latin=N'MESÃO FRIO', abac_name=N'MESAO FRIO', display_name=N'MESÃO FRIO' WHERE id=81046;
UPDATE laus SET name_national=N'MIRA', name_latin=N'MIRA', abac_name=N'MIRA', display_name=N'MIRA' WHERE id=80880;
UPDATE laus SET name_national=N'MIRANDA DO CORVO', name_latin=N'MIRANDA DO CORVO', abac_name=N'MIRANDA DO CORVO', display_name=N'MIRANDA DO CORVO' WHERE id=80881;
UPDATE laus SET name_national=N'MIRANDA DO DOURO', name_latin=N'MIRANDA DO DOURO', abac_name=N'MIRANDA DO DOURO', display_name=N'MIRANDA DO DOURO' WHERE id=80855;
UPDATE laus SET name_national=N'MIRANDELA', name_latin=N'MIRANDELA', abac_name=N'MIRANDELA', display_name=N'MIRANDELA' WHERE id=80856;
UPDATE laus SET name_national=N'MOGADOURO', name_latin=N'MOGADOURO', abac_name=N'MOGADOURO', display_name=N'MOGADOURO' WHERE id=80857;
UPDATE laus SET name_national=N'MOIMENTA DA BEIRA', name_latin=N'MOIMENTA DA BEIRA', abac_name=N'MOIMENTA DA BEIRA', display_name=N'MOIMENTA DA BEIRA' WHERE id=81063;
UPDATE laus SET name_national=N'MOITA', name_latin=N'MOITA', abac_name=N'MOITA', display_name=N'MOITA' WHERE id=81025;
UPDATE laus SET name_national=N'MONÇÃO', name_latin=N'MONÇÃO', abac_name=N'MONCAO', display_name=N'MONÇÃO' WHERE id=81036;
UPDATE laus SET name_national=N'MONCHIQUE', name_latin=N'MONCHIQUE', abac_name=N'MONCHIQUE', display_name=N'MONCHIQUE' WHERE id=80912;
UPDATE laus SET name_national=N'MONDIM DE BASTO', name_latin=N'MONDIM DE BASTO', abac_name=N'MONDIM DE BASTO', display_name=N'MONDIM DE BASTO' WHERE id=81047;
UPDATE laus SET name_national=N'MONFORTE', name_latin=N'MONFORTE', abac_name=N'MONFORTE', display_name=N'MONFORTE' WHERE id=80976;
UPDATE laus SET name_national=N'MONTALEGRE', name_latin=N'MONTALEGRE', abac_name=N'MONTALEGRE', display_name=N'MONTALEGRE' WHERE id=81048;
UPDATE laus SET name_national=N'MONTEMOR-O-NOVO', name_latin=N'MONTEMOR-O-NOVO', abac_name=N'MONTEMOR-O-NOVO', display_name=N'MONTEMOR-O-NOVO' WHERE id=80895;
UPDATE laus SET name_national=N'MONTEMOR-O-VELHO', name_latin=N'MONTEMOR-O-VELHO', abac_name=N'MONTEMOR-O-VELHO', display_name=N'MONTEMOR-O-VELHO' WHERE id=80882;
UPDATE laus SET name_national=N'MONTIJO', name_latin=N'MONTIJO', abac_name=N'MONTIJO', display_name=N'MONTIJO' WHERE id=81026;
UPDATE laus SET name_national=N'MORA', name_latin=N'MORA', abac_name=N'MORA', display_name=N'MORA' WHERE id=80896;
UPDATE laus SET name_national=N'MORTÁGUA', name_latin=N'MORTÁGUA', abac_name=N'MORTAGUA', display_name=N'MORTÁGUA' WHERE id=81064;
UPDATE laus SET name_national=N'MOURA', name_latin=N'MOURA', abac_name=N'MOURA', display_name=N'MOURA' WHERE id=80831;
UPDATE laus SET name_national=N'MOURÃO', name_latin=N'MOURÃO', abac_name=N'MOURAO', display_name=N'MOURÃO' WHERE id=80897;
UPDATE laus SET name_national=N'MURÇA', name_latin=N'MURÇA', abac_name=N'MURCA', display_name=N'MURÇA' WHERE id=81049;
UPDATE laus SET name_national=N'MURTOSA', name_latin=N'MURTOSA', abac_name=N'MURTOSA', display_name=N'MURTOSA' WHERE id=80814;
UPDATE laus SET name_national=N'NAZARÉ', name_latin=N'NAZARÉ', abac_name=N'NAZARE', display_name=N'NAZARÉ' WHERE id=80944;
UPDATE laus SET name_national=N'NELAS', name_latin=N'NELAS', abac_name=N'NELAS', display_name=N'NELAS' WHERE id=81065;
UPDATE laus SET name_national=N'NISA', name_latin=N'NISA', abac_name=N'NISA', display_name=N'NISA' WHERE id=80977;
UPDATE laus SET name_national=N'NORDESTE', name_latin=N'NORDESTE', abac_name=N'NORDESTE', display_name=N'NORDESTE' WHERE id=81094;
UPDATE laus SET name_national=N'ÓBIDOS', name_latin=N'ÓBIDOS', abac_name=N'OBIDOS', display_name=N'ÓBIDOS' WHERE id=80945;
UPDATE laus SET name_national=N'ODEMIRA', name_latin=N'ODEMIRA', abac_name=N'ODEMIRA', display_name=N'ODEMIRA' WHERE id=80832;
UPDATE laus SET name_national=N'ODIVELAS', name_latin=N'ODIVELAS', abac_name=N'ODIVELAS', display_name=N'ODIVELAS' WHERE id=80965;
UPDATE laus SET name_national=N'OEIRAS', name_latin=N'OEIRAS', abac_name=N'OEIRAS', display_name=N'OEIRAS' WHERE id=80959;
UPDATE laus SET name_national=N'OLEIROS', name_latin=N'OLEIROS', abac_name=N'OLEIROS', display_name=N'OLEIROS' WHERE id=80867;
UPDATE laus SET name_national=N'OLHÃO', name_latin=N'OLHÃO', abac_name=N'OLHAO', display_name=N'OLHÃO' WHERE id=80913;
UPDATE laus SET name_national=N'OLIVEIRA DE AZEMÉIS', name_latin=N'OLIVEIRA DE AZEMÉIS', abac_name=N'OLIVEIRA DE AZEMEIS', display_name=N'OLIVEIRA DE AZEMÉIS' WHERE id=80815;
UPDATE laus SET name_national=N'OLIVEIRA DE FRADES', name_latin=N'OLIVEIRA DE FRADES', abac_name=N'OLIVEIRA DE FRADES', display_name=N'OLIVEIRA DE FRADES' WHERE id=81066;
UPDATE laus SET name_national=N'OLIVEIRA DO BAIRRO', name_latin=N'OLIVEIRA DO BAIRRO', abac_name=N'OLIVEIRA DO BAIRRO', display_name=N'OLIVEIRA DO BAIRRO' WHERE id=80816;
UPDATE laus SET name_national=N'OLIVEIRA DO HOSPITAL', name_latin=N'OLIVEIRA DO HOSPITAL', abac_name=N'OLIVEIRA DO HOSPITAL', display_name=N'OLIVEIRA DO HOSPITAL' WHERE id=80883;
UPDATE laus SET name_national=N'OURÉM', name_latin=N'OURÉM', abac_name=N'OUREM', display_name=N'OURÉM' WHERE id=81019;
UPDATE laus SET name_national=N'OURIQUE', name_latin=N'OURIQUE', abac_name=N'OURIQUE', display_name=N'OURIQUE' WHERE id=80833;
UPDATE laus SET name_national=N'OVAR', name_latin=N'OVAR', abac_name=N'OVAR', display_name=N'OVAR' WHERE id=80817;
UPDATE laus SET name_national=N'PAÇOS DE FERREIRA', name_latin=N'PAÇOS DE FERREIRA', abac_name=N'PACOS DE FERREIRA', display_name=N'PAÇOS DE FERREIRA' WHERE id=80989;
UPDATE laus SET name_national=N'PALMELA', name_latin=N'PALMELA', abac_name=N'PALMELA', display_name=N'PALMELA' WHERE id=81027;
UPDATE laus SET name_national=N'PAMPILHOSA DA SERRA', name_latin=N'PAMPILHOSA DA SERRA', abac_name=N'PAMPILHOSA DA SERRA', display_name=N'PAMPILHOSA DA SERRA' WHERE id=80884;
UPDATE laus SET name_national=N'PAREDES', name_latin=N'PAREDES', abac_name=N'PAREDES', display_name=N'PAREDES' WHERE id=80990;
UPDATE laus SET name_national=N'PAREDES DE COURA', name_latin=N'PAREDES DE COURA', abac_name=N'PAREDES DE COURA', display_name=N'PAREDES DE COURA' WHERE id=81037;
UPDATE laus SET name_national=N'PEDRÓGÃO GRANDE', name_latin=N'PEDRÓGÃO GRANDE', abac_name=N'PEDROGAO GRANDE', display_name=N'PEDRÓGÃO GRANDE' WHERE id=80946;
UPDATE laus SET name_national=N'PENACOVA', name_latin=N'PENACOVA', abac_name=N'PENACOVA', display_name=N'PENACOVA' WHERE id=80885;
UPDATE laus SET name_national=N'PENAFIEL', name_latin=N'PENAFIEL', abac_name=N'PENAFIEL', display_name=N'PENAFIEL' WHERE id=80991;
UPDATE laus SET name_national=N'PENALVA DO CASTELO', name_latin=N'PENALVA DO CASTELO', abac_name=N'PENALVA DO CASTELO', display_name=N'PENALVA DO CASTELO' WHERE id=81067;
UPDATE laus SET name_national=N'PENAMACOR', name_latin=N'PENAMACOR', abac_name=N'PENAMACOR', display_name=N'PENAMACOR' WHERE id=80868;
UPDATE laus SET name_national=N'PENEDONO', name_latin=N'PENEDONO', abac_name=N'PENEDONO', display_name=N'PENEDONO' WHERE id=81068;
UPDATE laus SET name_national=N'PENELA', name_latin=N'PENELA', abac_name=N'PENELA', display_name=N'PENELA' WHERE id=80886;
UPDATE laus SET name_national=N'PENICHE', name_latin=N'PENICHE', abac_name=N'PENICHE', display_name=N'PENICHE' WHERE id=80947;
UPDATE laus SET name_national=N'PESO DA RÉGUA', name_latin=N'PESO DA RÉGUA', abac_name=N'PESO DA REGUA', display_name=N'PESO DA RÉGUA' WHERE id=81050;
UPDATE laus SET name_national=N'PINHEL', name_latin=N'PINHEL', abac_name=N'PINHEL', display_name=N'PINHEL' WHERE id=80929;
UPDATE laus SET name_national=N'POMBAL', name_latin=N'POMBAL', abac_name=N'POMBAL', display_name=N'POMBAL' WHERE id=80948;
UPDATE laus SET name_national=N'PONTA DELGADA', name_latin=N'PONTA DELGADA', abac_name=N'PONTA DELGADA', display_name=N'PONTA DELGADA' WHERE id=81095;
UPDATE laus SET name_national=N'PONTA DO SOL', name_latin=N'PONTA DO SOL', abac_name=N'PONTA DO SOL', display_name=N'PONTA DO SOL' WHERE id=81085;
UPDATE laus SET name_national=N'PONTE DA BARCA', name_latin=N'PONTE DA BARCA', abac_name=N'PONTE DA BARCA', display_name=N'PONTE DA BARCA' WHERE id=81038;
UPDATE laus SET name_national=N'PONTE DE LIMA', name_latin=N'PONTE DE LIMA', abac_name=N'PONTE DE LIMA', display_name=N'PONTE DE LIMA' WHERE id=81039;
UPDATE laus SET name_national=N'PONTE DE SOR', name_latin=N'PONTE DE SOR', abac_name=N'PONTE DE SOR', display_name=N'PONTE DE SOR' WHERE id=80978;
UPDATE laus SET name_national=N'PORTALEGRE', name_latin=N'PORTALEGRE', abac_name=N'PORTALEGRE', display_name=N'PORTALEGRE' WHERE id=80979;
UPDATE laus SET name_national=N'PORTEL', name_latin=N'PORTEL', abac_name=N'PORTEL', display_name=N'PORTEL' WHERE id=80898;
UPDATE laus SET name_national=N'PORTIMÃO', name_latin=N'PORTIMÃO', abac_name=N'PORTIMAO', display_name=N'PORTIMÃO' WHERE id=80914;
UPDATE laus SET name_national=N'PORTO', name_latin=N'PORTO', abac_name=N'PORTO', display_name=N'PORTO' WHERE id=80992;
UPDATE laus SET name_national=N'PORTO DE MÓS', name_latin=N'PORTO DE MÓS', abac_name=N'PORTO DE MOS', display_name=N'PORTO DE MÓS' WHERE id=80949;
UPDATE laus SET name_national=N'PORTO MONIZ', name_latin=N'PORTO MONIZ', abac_name=N'PORTO MONIZ', display_name=N'PORTO MONIZ' WHERE id=81086;
UPDATE laus SET name_national=N'PORTO SANTO', name_latin=N'PORTO SANTO', abac_name=N'PORTO SANTO', display_name=N'PORTO SANTO' WHERE id=81091;
UPDATE laus SET name_national=N'PÓVOA DE LANHOSO', name_latin=N'PÓVOA DE LANHOSO', abac_name=N'POVOA DE LANHOSO', display_name=N'PÓVOA DE LANHOSO' WHERE id=80844;
UPDATE laus SET name_national=N'PÓVOA DE VARZIM', name_latin=N'PÓVOA DE VARZIM', abac_name=N'POVOA DE VARZIM', display_name=N'PÓVOA DE VARZIM' WHERE id=80993;
UPDATE laus SET name_national=N'POVOAÇÃO', name_latin=N'POVOAÇÃO', abac_name=N'POVOACAO', display_name=N'POVOAÇÃO' WHERE id=81096;
UPDATE laus SET name_national=N'PRAIA DA VITÓRIA', name_latin=N'PRAIA DA VITÓRIA', abac_name=N'PRAIA DA VITORIA', display_name=N'PRAIA DA VITÓRIA' WHERE id=81100;
UPDATE laus SET name_national=N'PROENÇA-A-NOVA', name_latin=N'PROENÇA-A-NOVA', abac_name=N'PROENCA-A-NOVA', display_name=N'PROENÇA-A-NOVA' WHERE id=80869;
UPDATE laus SET name_national=N'REDONDO', name_latin=N'REDONDO', abac_name=N'REDONDO', display_name=N'REDONDO' WHERE id=80899;
UPDATE laus SET name_national=N'REGUENGOS DE MONSARAZ', name_latin=N'REGUENGOS DE MONSARAZ', abac_name=N'REGUENGOS DE MONSARAZ', display_name=N'REGUENGOS DE MONSARAZ' WHERE id=80900;
UPDATE laus SET name_national=N'RESENDE', name_latin=N'RESENDE', abac_name=N'RESENDE', display_name=N'RESENDE' WHERE id=81069;
UPDATE laus SET name_national=N'RIBEIRA BRAVA', name_latin=N'RIBEIRA BRAVA', abac_name=N'RIBEIRA BRAVA', display_name=N'RIBEIRA BRAVA' WHERE id=81087;
UPDATE laus SET name_national=N'RIBEIRA DE PENA', name_latin=N'RIBEIRA DE PENA', abac_name=N'RIBEIRA DE PENA', display_name=N'RIBEIRA DE PENA' WHERE id=81051;
UPDATE laus SET name_national=N'RIBEIRA GRANDE', name_latin=N'RIBEIRA GRANDE', abac_name=N'RIBEIRA GRANDE', display_name=N'RIBEIRA GRANDE' WHERE id=81097;
UPDATE laus SET name_national=N'RIO MAIOR', name_latin=N'RIO MAIOR', abac_name=N'RIO MAIOR', display_name=N'RIO MAIOR' WHERE id=81012;
UPDATE laus SET name_national=N'SABROSA', name_latin=N'SABROSA', abac_name=N'SABROSA', display_name=N'SABROSA' WHERE id=81052;
UPDATE laus SET name_national=N'SABUGAL', name_latin=N'SABUGAL', abac_name=N'SABUGAL', display_name=N'SABUGAL' WHERE id=80930;
UPDATE laus SET name_national=N'SALVATERRA DE MAGOS', name_latin=N'SALVATERRA DE MAGOS', abac_name=N'SALVATERRA DE MAGOS', display_name=N'SALVATERRA DE MAGOS' WHERE id=81013;
UPDATE laus SET name_national=N'SANTA COMBA DÃO', name_latin=N'SANTA COMBA DÃO', abac_name=N'SANTA COMBA DAO', display_name=N'SANTA COMBA DÃO' WHERE id=81070;
UPDATE laus SET name_national=N'SANTA CRUZ', name_latin=N'SANTA CRUZ', abac_name=N'SANTA CRUZ', display_name=N'SANTA CRUZ' WHERE id=81088;
UPDATE laus SET name_national=N'SANTA CRUZ DA GRACIOSA', name_latin=N'SANTA CRUZ DA GRACIOSA', abac_name=N'SANTA CRUZ DA GRACIOSA', display_name=N'SANTA CRUZ DA GRACIOSA' WHERE id=81101;
UPDATE laus SET name_national=N'SANTA CRUZ DAS FLORES', name_latin=N'SANTA CRUZ DAS FLORES', abac_name=N'SANTA CRUZ DAS FLORES', display_name=N'SANTA CRUZ DAS FLORES' WHERE id=81109;
UPDATE laus SET name_national=N'SANTA MARIA DA FEIRA', name_latin=N'SANTA MARIA DA FEIRA', abac_name=N'SANTA MARIA DA FEIRA', display_name=N'SANTA MARIA DA FEIRA' WHERE id=80811;
UPDATE laus SET name_national=N'SANTA MARTA DE PENAGUIÃO', name_latin=N'SANTA MARTA DE PENAGUIÃO', abac_name=N'SANTA MARTA DE PENAGUIAO', display_name=N'SANTA MARTA DE PENAGUIÃO' WHERE id=81053;
UPDATE laus SET name_national=N'SANTANA', name_latin=N'SANTANA', abac_name=N'SANTANA', display_name=N'SANTANA' WHERE id=81089;
UPDATE laus SET name_national=N'SANTARÉM', name_latin=N'SANTARÉM', abac_name=N'SANTAREM', display_name=N'SANTARÉM' WHERE id=81014;
UPDATE laus SET name_national=N'SANTIAGO DO CACÉM', name_latin=N'SANTIAGO DO CACÉM', abac_name=N'SANTIAGO DO CACEM', display_name=N'SANTIAGO DO CACÉM' WHERE id=81028;
UPDATE laus SET name_national=N'SANTO TIRSO', name_latin=N'SANTO TIRSO', abac_name=N'SANTO TIRSO', display_name=N'SANTO TIRSO' WHERE id=80994;
UPDATE laus SET name_national=N'SÃO BRÁS DE ALPORTEL', name_latin=N'SÃO BRÁS DE ALPORTEL', abac_name=N'SAO BRAS DE ALPORTEL', display_name=N'SÃO BRÁS DE ALPORTEL' WHERE id=80915;
UPDATE laus SET name_national=N'SÃO JOÃO DA MADEIRA', name_latin=N'SÃO JOÃO DA MADEIRA', abac_name=N'SAO JOAO DA MADEIRA', display_name=N'SÃO JOÃO DA MADEIRA' WHERE id=80818;
UPDATE laus SET name_national=N'SÃO JOÃO DA PESQUEIRA', name_latin=N'SÃO JOÃO DA PESQUEIRA', abac_name=N'SAO JOAO DA PESQUEIRA', display_name=N'SÃO JOÃO DA PESQUEIRA' WHERE id=81071;
UPDATE laus SET name_national=N'SÃO PEDRO DO SUL', name_latin=N'SÃO PEDRO DO SUL', abac_name=N'SAO PEDRO DO SUL', display_name=N'SÃO PEDRO DO SUL' WHERE id=81072;
UPDATE laus SET name_national=N'SÃO ROQUE DO PICO', name_latin=N'SÃO ROQUE DO PICO', abac_name=N'SAO ROQUE DO PICO', display_name=N'SÃO ROQUE DO PICO' WHERE id=81106;
UPDATE laus SET name_national=N'SÃO VICENTE', name_latin=N'SÃO VICENTE', abac_name=N'SAO VICENTE', display_name=N'SÃO VICENTE' WHERE id=81090;
UPDATE laus SET name_national=N'SARDOAL', name_latin=N'SARDOAL', abac_name=N'SARDOAL', display_name=N'SARDOAL' WHERE id=81015;
UPDATE laus SET name_national=N'SÁTÃO', name_latin=N'SÁTÃO', abac_name=N'SATAO', display_name=N'SÁTÃO' WHERE id=81073;
UPDATE laus SET name_national=N'SEIA', name_latin=N'SEIA', abac_name=N'SEIA', display_name=N'SEIA' WHERE id=80931;
UPDATE laus SET name_national=N'SEIXAL', name_latin=N'SEIXAL', abac_name=N'SEIXAL', display_name=N'SEIXAL' WHERE id=81029;
UPDATE laus SET name_national=N'SERNANCELHE', name_latin=N'SERNANCELHE', abac_name=N'SERNANCELHE', display_name=N'SERNANCELHE' WHERE id=81074;
UPDATE laus SET name_national=N'SERPA', name_latin=N'SERPA', abac_name=N'SERPA', display_name=N'SERPA' WHERE id=80834;
UPDATE laus SET name_national=N'SERTÃ', name_latin=N'SERTÃ', abac_name=N'SERTA', display_name=N'SERTÃ' WHERE id=80870;
UPDATE laus SET name_national=N'SESIMBRA', name_latin=N'SESIMBRA', abac_name=N'SESIMBRA', display_name=N'SESIMBRA' WHERE id=81030;
UPDATE laus SET name_national=N'SETÚBAL', name_latin=N'SETÚBAL', abac_name=N'SETUBAL', display_name=N'SETÚBAL' WHERE id=81031;
UPDATE laus SET name_national=N'SEVER DO VOUGA', name_latin=N'SEVER DO VOUGA', abac_name=N'SEVER DO VOUGA', display_name=N'SEVER DO VOUGA' WHERE id=80819;
UPDATE laus SET name_national=N'SILVES', name_latin=N'SILVES', abac_name=N'SILVES', display_name=N'SILVES' WHERE id=80916;
UPDATE laus SET name_national=N'SINES', name_latin=N'SINES', abac_name=N'SINES', display_name=N'SINES' WHERE id=81032;
UPDATE laus SET name_national=N'SINTRA', name_latin=N'SINTRA', abac_name=N'SINTRA', display_name=N'SINTRA' WHERE id=80960;
UPDATE laus SET name_national=N'SOBRAL DE MONTE AGRAÇO', name_latin=N'SOBRAL DE MONTE AGRAÇO', abac_name=N'SOBRAL DE MONTE AGRACO', display_name=N'SOBRAL DE MONTE AGRAÇO' WHERE id=80961;
UPDATE laus SET name_national=N'SOURE', name_latin=N'SOURE', abac_name=N'SOURE', display_name=N'SOURE' WHERE id=80887;
UPDATE laus SET name_national=N'SOUSEL', name_latin=N'SOUSEL', abac_name=N'SOUSEL', display_name=N'SOUSEL' WHERE id=80980;
UPDATE laus SET name_national=N'TÁBUA', name_latin=N'TÁBUA', abac_name=N'TABUA', display_name=N'TÁBUA' WHERE id=80888;
UPDATE laus SET name_national=N'TABUAÇO', name_latin=N'TABUAÇO', abac_name=N'TABUACO', display_name=N'TABUAÇO' WHERE id=81075;
UPDATE laus SET name_national=N'TAROUCA', name_latin=N'TAROUCA', abac_name=N'TAROUCA', display_name=N'TAROUCA' WHERE id=81076;
UPDATE laus SET name_national=N'TAVIRA', name_latin=N'TAVIRA', abac_name=N'TAVIRA', display_name=N'TAVIRA' WHERE id=80917;
UPDATE laus SET name_national=N'TERRAS DE BOURO', name_latin=N'TERRAS DE BOURO', abac_name=N'TERRAS DE BOURO', display_name=N'TERRAS DE BOURO' WHERE id=80845;
UPDATE laus SET name_national=N'TOMAR', name_latin=N'TOMAR', abac_name=N'TOMAR', display_name=N'TOMAR' WHERE id=81016;
UPDATE laus SET name_national=N'TONDELA', name_latin=N'TONDELA', abac_name=N'TONDELA', display_name=N'TONDELA' WHERE id=81077;
UPDATE laus SET name_national=N'TORRE DE MONCORVO', name_latin=N'TORRE DE MONCORVO', abac_name=N'TORRE DE MONCORVO', display_name=N'TORRE DE MONCORVO' WHERE id=80858;
UPDATE laus SET name_national=N'TORRES NOVAS', name_latin=N'TORRES NOVAS', abac_name=N'TORRES NOVAS', display_name=N'TORRES NOVAS' WHERE id=81017;
UPDATE laus SET name_national=N'TORRES VEDRAS', name_latin=N'TORRES VEDRAS', abac_name=N'TORRES VEDRAS', display_name=N'TORRES VEDRAS' WHERE id=80962;
UPDATE laus SET name_national=N'TRANCOSO', name_latin=N'TRANCOSO', abac_name=N'TRANCOSO', display_name=N'TRANCOSO' WHERE id=80932;
UPDATE laus SET name_national=N'TROFA', name_latin=N'TROFA', abac_name=N'TROFA', display_name=N'TROFA' WHERE id=80998;
UPDATE laus SET name_national=N'VAGOS', name_latin=N'VAGOS', abac_name=N'VAGOS', display_name=N'VAGOS' WHERE id=80820;
UPDATE laus SET name_national=N'VALE DE CAMBRA', name_latin=N'VALE DE CAMBRA', abac_name=N'VALE DE CAMBRA', display_name=N'VALE DE CAMBRA' WHERE id=80821;
UPDATE laus SET name_national=N'VALENÇA', name_latin=N'VALENÇA', abac_name=N'VALENCA', display_name=N'VALENÇA' WHERE id=81040;
UPDATE laus SET name_national=N'VALONGO', name_latin=N'VALONGO', abac_name=N'VALONGO', display_name=N'VALONGO' WHERE id=80995;
UPDATE laus SET name_national=N'VALPAÇOS', name_latin=N'VALPAÇOS', abac_name=N'VALPACOS', display_name=N'VALPAÇOS' WHERE id=81054;
UPDATE laus SET name_national=N'VELAS', name_latin=N'VELAS', abac_name=N'VELAS', display_name=N'VELAS' WHERE id=81103;
UPDATE laus SET name_national=N'VENDAS NOVAS', name_latin=N'VENDAS NOVAS', abac_name=N'VENDAS NOVAS', display_name=N'VENDAS NOVAS' WHERE id=80901;
UPDATE laus SET name_national=N'VIANA DO ALENTEJO', name_latin=N'VIANA DO ALENTEJO', abac_name=N'VIANA DO ALENTEJO', display_name=N'VIANA DO ALENTEJO' WHERE id=80902;
UPDATE laus SET name_national=N'VIANA DO CASTELO', name_latin=N'VIANA DO CASTELO', abac_name=N'VIANA DO CASTELO', display_name=N'VIANA DO CASTELO' WHERE id=81041;
UPDATE laus SET name_national=N'VIDIGUEIRA', name_latin=N'VIDIGUEIRA', abac_name=N'VIDIGUEIRA', display_name=N'VIDIGUEIRA' WHERE id=80835;
UPDATE laus SET name_national=N'VIEIRA DO MINHO', name_latin=N'VIEIRA DO MINHO', abac_name=N'VIEIRA DO MINHO', display_name=N'VIEIRA DO MINHO' WHERE id=80846;
UPDATE laus SET name_national=N'VILA DE REI', name_latin=N'VILA DE REI', abac_name=N'VILA DE REI', display_name=N'VILA DE REI' WHERE id=80871;
UPDATE laus SET name_national=N'VILA DO BISPO', name_latin=N'VILA DO BISPO', abac_name=N'VILA DO BISPO', display_name=N'VILA DO BISPO' WHERE id=80918;
UPDATE laus SET name_national=N'VILA DO CONDE', name_latin=N'VILA DO CONDE', abac_name=N'VILA DO CONDE', display_name=N'VILA DO CONDE' WHERE id=80996;
UPDATE laus SET name_national=N'VILA DO PORTO', name_latin=N'VILA DO PORTO', abac_name=N'VILA DO PORTO', display_name=N'VILA DO PORTO' WHERE id=81092;
UPDATE laus SET name_national=N'VILA FLOR', name_latin=N'VILA FLOR', abac_name=N'VILA FLOR', display_name=N'VILA FLOR' WHERE id=80859;
UPDATE laus SET name_national=N'VILA FRANCA DE XIRA', name_latin=N'VILA FRANCA DE XIRA', abac_name=N'VILA FRANCA DE XIRA', display_name=N'VILA FRANCA DE XIRA' WHERE id=80963;
UPDATE laus SET name_national=N'VILA FRANCA DO CAMPO', name_latin=N'VILA FRANCA DO CAMPO', abac_name=N'VILA FRANCA DO CAMPO', display_name=N'VILA FRANCA DO CAMPO' WHERE id=81098;
UPDATE laus SET name_national=N'VILA NOVA DA BARQUINHA', name_latin=N'VILA NOVA DA BARQUINHA', abac_name=N'VILA NOVA DA BARQUINHA', display_name=N'VILA NOVA DA BARQUINHA' WHERE id=81018;
UPDATE laus SET name_national=N'VILA NOVA DE CERVEIRA', name_latin=N'VILA NOVA DE CERVEIRA', abac_name=N'VILA NOVA DE CERVEIRA', display_name=N'VILA NOVA DE CERVEIRA' WHERE id=81042;
UPDATE laus SET name_national=N'VILA NOVA DE FAMALICÃO', name_latin=N'VILA NOVA DE FAMALICÃO', abac_name=N'VILA NOVA DE FAMALICAO', display_name=N'VILA NOVA DE FAMALICÃO' WHERE id=80847;
UPDATE laus SET name_national=N'VILA NOVA DE FOZ CÔA', name_latin=N'VILA NOVA DE FOZ CÔA', abac_name=N'VILA NOVA DE FOZ COA', display_name=N'VILA NOVA DE FOZ CÔA' WHERE id=80933;
UPDATE laus SET name_national=N'VILA NOVA DE GAIA', name_latin=N'VILA NOVA DE GAIA', abac_name=N'VILA NOVA DE GAIA', display_name=N'VILA NOVA DE GAIA' WHERE id=80997;
UPDATE laus SET name_national=N'VILA NOVA DE PAIVA', name_latin=N'VILA NOVA DE PAIVA', abac_name=N'VILA NOVA DE PAIVA', display_name=N'VILA NOVA DE PAIVA' WHERE id=81078;
UPDATE laus SET name_national=N'VILA NOVA DE POIARES', name_latin=N'VILA NOVA DE POIARES', abac_name=N'VILA NOVA DE POIARES', display_name=N'VILA NOVA DE POIARES' WHERE id=80889;
UPDATE laus SET name_national=N'VILA POUCA DE AGUIAR', name_latin=N'VILA POUCA DE AGUIAR', abac_name=N'VILA POUCA DE AGUIAR', display_name=N'VILA POUCA DE AGUIAR' WHERE id=81055;
UPDATE laus SET name_national=N'VILA REAL', name_latin=N'VILA REAL', abac_name=N'VILA REAL', display_name=N'VILA REAL' WHERE id=81056;
UPDATE laus SET name_national=N'VILA REAL DE SANTO ANTÓNIO', name_latin=N'VILA REAL DE SANTO ANTÓNIO', abac_name=N'VILA REAL DE SANTO ANTONIO', display_name=N'VILA REAL DE SANTO ANTÓNIO' WHERE id=80919;
UPDATE laus SET name_national=N'VILA VELHA DE RÓDÃO', name_latin=N'VILA VELHA DE RÓDÃO', abac_name=N'VILA VELHA DE RODAO', display_name=N'VILA VELHA DE RÓDÃO' WHERE id=80872;
UPDATE laus SET name_national=N'VILA VERDE', name_latin=N'VILA VERDE', abac_name=N'VILA VERDE', display_name=N'VILA VERDE' WHERE id=80848;
UPDATE laus SET name_national=N'VILA VIÇOSA', name_latin=N'VILA VIÇOSA', abac_name=N'VILA VICOSA', display_name=N'VILA VIÇOSA' WHERE id=80903;
UPDATE laus SET name_national=N'VIMIOSO', name_latin=N'VIMIOSO', abac_name=N'VIMIOSO', display_name=N'VIMIOSO' WHERE id=80860;
UPDATE laus SET name_national=N'VINHAIS', name_latin=N'VINHAIS', abac_name=N'VINHAIS', display_name=N'VINHAIS' WHERE id=80861;
UPDATE laus SET name_national=N'VISEU', name_latin=N'VISEU', abac_name=N'VISEU', display_name=N'VISEU' WHERE id=81079;
UPDATE laus SET name_national=N'VIZELA', name_latin=N'VIZELA', abac_name=N'VIZELA', display_name=N'VIZELA' WHERE id=80849;
UPDATE laus SET name_national=N'VOUZELA', name_latin=N'VOUZELA', abac_name=N'VOUZELA', display_name=N'VOUZELA' WHERE id=81080;
--308
--select nuts3, lau1, name_national, name_latin, abac_name, display_name, id 
--from laus where country_code = 'PT' order by name1 asc