-- NL
--SQL (names)
UPDATE laus SET name_national=N'Aa en Hunze', name_latin=N'Aa en Hunze', abac_name=N'Aa en Hunze', display_name=N'Aa en Hunze' WHERE id=77848;
UPDATE laus SET name_national=N'Aalburg', name_latin=N'Aalburg', abac_name=N'Aalburg', display_name=N'Aalburg' WHERE id=77755;
UPDATE laus SET name_national=N'Aalsmeer', name_latin=N'Aalsmeer', abac_name=N'Aalsmeer', display_name=N'Aalsmeer' WHERE id=77649;
UPDATE laus SET name_national=N'Aalten', name_latin=N'Aalten', abac_name=N'Aalten', display_name=N'Aalten' WHERE id=77586;
UPDATE laus SET name_national=N'Achtkarspelen', name_latin=N'Achtkarspelen', abac_name=N'Achtkarspelen', display_name=N'Achtkarspelen' WHERE id=77548;
UPDATE laus SET name_national=N'Alblasserdam', name_latin=N'Alblasserdam', abac_name=N'Alblasserdam', display_name=N'Alblasserdam' WHERE id=77689;
UPDATE laus SET name_national=N'Albrandswaard', name_latin=N'Albrandswaard', abac_name=N'Albrandswaard', display_name=N'Albrandswaard' WHERE id=77727;
UPDATE laus SET name_national=N'Alkmaar', name_latin=N'Alkmaar', abac_name=N'Alkmaar', display_name=N'Alkmaar' WHERE id=77650;
UPDATE laus SET name_national=N'Almelo', name_latin=N'Almelo', abac_name=N'Almelo', display_name=N'Almelo' WHERE id=77566;
UPDATE laus SET name_national=N'Almere', name_latin=N'Almere', abac_name=N'Almere', display_name=N'Almere' WHERE id=77541;
UPDATE laus SET name_national=N'Alphen aan den Rijn', name_latin=N'Alphen aan den Rijn', abac_name=N'Alphen aan den Rijn', display_name=N'Alphen aan den Rijn' WHERE id=77690;
UPDATE laus SET name_national=N'Alphen-Chaam', name_latin=N'Alphen-Chaam', abac_name=N'Alphen-Chaam', display_name=N'Alphen-Chaam' WHERE id=77868;
UPDATE laus SET name_national=N'Ameland', name_latin=N'Ameland', abac_name=N'Ameland', display_name=N'Ameland' WHERE id=77549;
UPDATE laus SET name_national=N'Amersfoort', name_latin=N'Amersfoort', abac_name=N'Amersfoort', display_name=N'Amersfoort' WHERE id=77629;
UPDATE laus SET name_national=N'Amstelveen', name_latin=N'Amstelveen', abac_name=N'Amstelveen', display_name=N'Amstelveen' WHERE id=77651;
UPDATE laus SET name_national=N'Amsterdam', name_latin=N'Amsterdam', abac_name=N'Amsterdam', display_name=N'Amsterdam' WHERE id=77652;
UPDATE laus SET name_national=N'Apeldoorn', name_latin=N'Apeldoorn', abac_name=N'Apeldoorn', display_name=N'Apeldoorn' WHERE id=77587;
UPDATE laus SET name_national=N'Appingedam', name_latin=N'Appingedam', abac_name=N'Appingedam', display_name=N'Appingedam' WHERE id=77531;
UPDATE laus SET name_national=N'Arnhem', name_latin=N'Arnhem', abac_name=N'Arnhem', display_name=N'Arnhem' WHERE id=77588;
UPDATE laus SET name_national=N'Assen', name_latin=N'Assen', abac_name=N'Assen', display_name=N'Assen' WHERE id=77561;
UPDATE laus SET name_national=N'Asten', name_latin=N'Asten', abac_name=N'Asten', display_name=N'Asten' WHERE id=77756;
UPDATE laus SET name_national=N'Baarle-Nassau', name_latin=N'Baarle-Nassau', abac_name=N'Baarle-Nassau', display_name=N'Baarle-Nassau' WHERE id=77757;
UPDATE laus SET name_national=N'Baarn', name_latin=N'Baarn', abac_name=N'Baarn', display_name=N'Baarn' WHERE id=77630;
UPDATE laus SET name_national=N'Barendrecht', name_latin=N'Barendrecht', abac_name=N'Barendrecht', display_name=N'Barendrecht' WHERE id=77691;
UPDATE laus SET name_national=N'Barneveld', name_latin=N'Barneveld', abac_name=N'Barneveld', display_name=N'Barneveld' WHERE id=77589;
UPDATE laus SET name_national=N'Bedum', name_latin=N'Bedum', abac_name=N'Bedum', display_name=N'Bedum' WHERE id=77532;
UPDATE laus SET name_national=N'Beek', name_latin=N'Beek', abac_name=N'Beek', display_name=N'Beek' WHERE id=77806;
UPDATE laus SET name_national=N'Beemster', name_latin=N'Beemster', abac_name=N'Beemster', display_name=N'Beemster' WHERE id=77653;
UPDATE laus SET name_national=N'Beesel', name_latin=N'Beesel', abac_name=N'Beesel', display_name=N'Beesel' WHERE id=77807;
UPDATE laus SET name_national=N'Berg en Dal', name_latin=N'Berg en Dal', abac_name=N'Berg en Dal', display_name=N'Berg en Dal' WHERE id=77905;
UPDATE laus SET name_national=N'Bergeijk', name_latin=N'Bergeijk', abac_name=N'Bergeijk', display_name=N'Bergeijk' WHERE id=77869;
UPDATE laus SET name_national=N'Bergen (L.)', name_latin=N'Bergen (L.)', abac_name=N'Bergen (L.)', display_name=N'Bergen (L.)' WHERE id=77808;
UPDATE laus SET name_national=N'Bergen (NH.)', name_latin=N'Bergen (NH.)', abac_name=N'Bergen (NH.)', display_name=N'Bergen (NH.)' WHERE id=77654;
UPDATE laus SET name_national=N'Bergen op Zoom', name_latin=N'Bergen op Zoom', abac_name=N'Bergen op Zoom', display_name=N'Bergen op Zoom' WHERE id=77758;
UPDATE laus SET name_national=N'Berkelland', name_latin=N'Berkelland', abac_name=N'Berkelland', display_name=N'Berkelland' WHERE id=77883;
UPDATE laus SET name_national=N'Bernheze', name_latin=N'Bernheze', abac_name=N'Bernheze', display_name=N'Bernheze' WHERE id=77866;
UPDATE laus SET name_national=N'Best', name_latin=N'Best', abac_name=N'Best', display_name=N'Best' WHERE id=77759;
UPDATE laus SET name_national=N'Beuningen', name_latin=N'Beuningen', abac_name=N'Beuningen', display_name=N'Beuningen' WHERE id=77590;
UPDATE laus SET name_national=N'Beverwijk', name_latin=N'Beverwijk', abac_name=N'Beverwijk', display_name=N'Beverwijk' WHERE id=77655;
UPDATE laus SET name_national=N'Binnenmaas', name_latin=N'Binnenmaas', abac_name=N'Binnenmaas', display_name=N'Binnenmaas' WHERE id=77717;
UPDATE laus SET name_national=N'Bladel', name_latin=N'Bladel', abac_name=N'Bladel', display_name=N'Bladel' WHERE id=77870;
UPDATE laus SET name_national=N'Blaricum', name_latin=N'Blaricum', abac_name=N'Blaricum', display_name=N'Blaricum' WHERE id=77656;
UPDATE laus SET name_national=N'Bloemendaal', name_latin=N'Bloemendaal', abac_name=N'Bloemendaal', display_name=N'Bloemendaal' WHERE id=77657;
UPDATE laus SET name_national=N'Bodegraven-Reeuwijk', name_latin=N'Bodegraven-Reeuwijk', abac_name=N'Bodegraven-Reeuwijk', display_name=N'Bodegraven-Reeuwijk' WHERE id=77893;
UPDATE laus SET name_national=N'Boekel', name_latin=N'Boekel', abac_name=N'Boekel', display_name=N'Boekel' WHERE id=77760;
UPDATE laus SET name_national=N'Borger-Odoorn', name_latin=N'Borger-Odoorn', abac_name=N'Borger-Odoorn', display_name=N'Borger-Odoorn' WHERE id=77849;
UPDATE laus SET name_national=N'Borne', name_latin=N'Borne', abac_name=N'Borne', display_name=N'Borne' WHERE id=77567;
UPDATE laus SET name_national=N'Borsele', name_latin=N'Borsele', abac_name=N'Borsele', display_name=N'Borsele' WHERE id=77739;
UPDATE laus SET name_national=N'Boxmeer', name_latin=N'Boxmeer', abac_name=N'Boxmeer', display_name=N'Boxmeer' WHERE id=77761;
UPDATE laus SET name_national=N'Boxtel', name_latin=N'Boxtel', abac_name=N'Boxtel', display_name=N'Boxtel' WHERE id=77762;
UPDATE laus SET name_national=N'Breda', name_latin=N'Breda', abac_name=N'Breda', display_name=N'Breda' WHERE id=77763;
UPDATE laus SET name_national=N'Brielle', name_latin=N'Brielle', abac_name=N'Brielle', display_name=N'Brielle' WHERE id=77693;
UPDATE laus SET name_national=N'Bronckhorst', name_latin=N'Bronckhorst', abac_name=N'Bronckhorst', display_name=N'Bronckhorst' WHERE id=77884;
UPDATE laus SET name_national=N'Brummen', name_latin=N'Brummen', abac_name=N'Brummen', display_name=N'Brummen' WHERE id=77591;
UPDATE laus SET name_national=N'Brunssum', name_latin=N'Brunssum', abac_name=N'Brunssum', display_name=N'Brunssum' WHERE id=77809;
UPDATE laus SET name_national=N'Bunnik', name_latin=N'Bunnik', abac_name=N'Bunnik', display_name=N'Bunnik' WHERE id=77632;
UPDATE laus SET name_national=N'Bunschoten', name_latin=N'Bunschoten', abac_name=N'Bunschoten', display_name=N'Bunschoten' WHERE id=77633;
UPDATE laus SET name_national=N'Buren', name_latin=N'Buren', abac_name=N'Buren', display_name=N'Buren' WHERE id=77592;
UPDATE laus SET name_national=N'Capelle aan den IJssel', name_latin=N'Capelle aan den IJssel', abac_name=N'Capelle aan den IJssel', display_name=N'Capelle aan den IJssel' WHERE id=77694;
UPDATE laus SET name_national=N'Castricum', name_latin=N'Castricum', abac_name=N'Castricum', display_name=N'Castricum' WHERE id=77658;
UPDATE laus SET name_national=N'Coevorden', name_latin=N'Coevorden', abac_name=N'Coevorden', display_name=N'Coevorden' WHERE id=77562;
UPDATE laus SET name_national=N'Cranendonck', name_latin=N'Cranendonck', abac_name=N'Cranendonck', display_name=N'Cranendonck' WHERE id=77860;
UPDATE laus SET name_national=N'Cromstrijen', name_latin=N'Cromstrijen', abac_name=N'Cromstrijen', display_name=N'Cromstrijen' WHERE id=77726;
UPDATE laus SET name_national=N'Cuijk', name_latin=N'Cuijk', abac_name=N'Cuijk', display_name=N'Cuijk' WHERE id=77850;
UPDATE laus SET name_national=N'Culemborg', name_latin=N'Culemborg', abac_name=N'Culemborg', display_name=N'Culemborg' WHERE id=77593;
UPDATE laus SET name_national=N'Dalfsen', name_latin=N'Dalfsen', abac_name=N'Dalfsen', display_name=N'Dalfsen' WHERE id=77568;
UPDATE laus SET name_national=N'Dantumadiel', name_latin=N'Dantumadiel', abac_name=N'Dantumadiel', display_name=N'Dantumadiel' WHERE id=77887;
UPDATE laus SET name_national=N'De Bilt', name_latin=N'De Bilt', abac_name=N'De Bilt', display_name=N'De Bilt' WHERE id=77631;
UPDATE laus SET name_national=N'De Fryske Marren', name_latin=N'De Fryske Marren', abac_name=N'De Fryske Marren', display_name=N'De Fryske Marren' WHERE id=77903;
UPDATE laus SET name_national=N'De Marne', name_latin=N'De Marne', abac_name=N'De Marne', display_name=N'De Marne' WHERE id=77843;
UPDATE laus SET name_national=N'De Ronde Venen', name_latin=N'De Ronde Venen', abac_name=N'De Ronde Venen', display_name=N'De Ronde Venen' WHERE id=77753;
UPDATE laus SET name_national=N'De Wolden', name_latin=N'De Wolden', abac_name=N'De Wolden', display_name=N'De Wolden' WHERE id=77852;
UPDATE laus SET name_national=N'Delft', name_latin=N'Delft', abac_name=N'Delft', display_name=N'Delft' WHERE id=77695;
UPDATE laus SET name_national=N'Delfzijl', name_latin=N'Delfzijl', abac_name=N'Delfzijl', display_name=N'Delfzijl' WHERE id=77534;
UPDATE laus SET name_national=N'Den Helder', name_latin=N'Den Helder', abac_name=N'Den Helder', display_name=N'Den Helder' WHERE id=77669;
UPDATE laus SET name_national=N'Deurne', name_latin=N'Deurne', abac_name=N'Deurne', display_name=N'Deurne' WHERE id=77764;
UPDATE laus SET name_national=N'Deventer', name_latin=N'Deventer', abac_name=N'Deventer', display_name=N'Deventer' WHERE id=77569;
UPDATE laus SET name_national=N'Diemen', name_latin=N'Diemen', abac_name=N'Diemen', display_name=N'Diemen' WHERE id=77659;
UPDATE laus SET name_national=N'Dinkelland', name_latin=N'Dinkelland', abac_name=N'Dinkelland', display_name=N'Dinkelland' WHERE id=77880;
UPDATE laus SET name_national=N'Doesburg', name_latin=N'Doesburg', abac_name=N'Doesburg', display_name=N'Doesburg' WHERE id=77594;
UPDATE laus SET name_national=N'Doetinchem', name_latin=N'Doetinchem', abac_name=N'Doetinchem', display_name=N'Doetinchem' WHERE id=77595;
UPDATE laus SET name_national=N'Dongen', name_latin=N'Dongen', abac_name=N'Dongen', display_name=N'Dongen' WHERE id=77766;
UPDATE laus SET name_national=N'Dongeradeel', name_latin=N'Dongeradeel', abac_name=N'Dongeradeel', display_name=N'Dongeradeel' WHERE id=77547;
UPDATE laus SET name_national=N'Dordrecht', name_latin=N'Dordrecht', abac_name=N'Dordrecht', display_name=N'Dordrecht' WHERE id=77696;
UPDATE laus SET name_national=N'Drechterland', name_latin=N'Drechterland', abac_name=N'Drechterland', display_name=N'Drechterland' WHERE id=77692;
UPDATE laus SET name_national=N'Drimmelen', name_latin=N'Drimmelen', abac_name=N'Drimmelen', display_name=N'Drimmelen' WHERE id=77865;
UPDATE laus SET name_national=N'Dronten', name_latin=N'Dronten', abac_name=N'Dronten', display_name=N'Dronten' WHERE id=77627;
UPDATE laus SET name_national=N'Druten', name_latin=N'Druten', abac_name=N'Druten', display_name=N'Druten' WHERE id=77596;
UPDATE laus SET name_national=N'Duiven', name_latin=N'Duiven', abac_name=N'Duiven', display_name=N'Duiven' WHERE id=77597;
UPDATE laus SET name_national=N'Echt-Susteren', name_latin=N'Echt-Susteren', abac_name=N'Echt-Susteren', display_name=N'Echt-Susteren' WHERE id=77863;
UPDATE laus SET name_national=N'Edam-Volendam', name_latin=N'Edam-Volendam', abac_name=N'Edam-Volendam', display_name=N'Edam-Volendam' WHERE id=77660;
UPDATE laus SET name_national=N'Ede', name_latin=N'Ede', abac_name=N'Ede', display_name=N'Ede' WHERE id=77598;
UPDATE laus SET name_national=N'Eemnes', name_latin=N'Eemnes', abac_name=N'Eemnes', display_name=N'Eemnes' WHERE id=77634;
UPDATE laus SET name_national=N'Eemsmond', name_latin=N'Eemsmond', abac_name=N'Eemsmond', display_name=N'Eemsmond' WHERE id=77838;
UPDATE laus SET name_national=N'Eersel', name_latin=N'Eersel', abac_name=N'Eersel', display_name=N'Eersel' WHERE id=77767;
UPDATE laus SET name_national=N'Eijsden-Margraten', name_latin=N'Eijsden-Margraten', abac_name=N'Eijsden-Margraten', display_name=N'Eijsden-Margraten' WHERE id=77894;
UPDATE laus SET name_national=N'Eindhoven', name_latin=N'Eindhoven', abac_name=N'Eindhoven', display_name=N'Eindhoven' WHERE id=77768;
UPDATE laus SET name_national=N'Elburg', name_latin=N'Elburg', abac_name=N'Elburg', display_name=N'Elburg' WHERE id=77599;
UPDATE laus SET name_national=N'Emmen', name_latin=N'Emmen', abac_name=N'Emmen', display_name=N'Emmen' WHERE id=77563;
UPDATE laus SET name_national=N'Enkhuizen', name_latin=N'Enkhuizen', abac_name=N'Enkhuizen', display_name=N'Enkhuizen' WHERE id=77661;
UPDATE laus SET name_national=N'Enschede', name_latin=N'Enschede', abac_name=N'Enschede', display_name=N'Enschede' WHERE id=77570;
UPDATE laus SET name_national=N'Epe', name_latin=N'Epe', abac_name=N'Epe', display_name=N'Epe' WHERE id=77600;
UPDATE laus SET name_national=N'Ermelo', name_latin=N'Ermelo', abac_name=N'Ermelo', display_name=N'Ermelo' WHERE id=77601;
UPDATE laus SET name_national=N'Etten-Leur', name_latin=N'Etten-Leur', abac_name=N'Etten-Leur', display_name=N'Etten-Leur' WHERE id=77769;
UPDATE laus SET name_national=N'Ferwerderadiel', name_latin=N'Ferwerderadiel', abac_name=N'Ferwerderadiel', display_name=N'Ferwerderadiel' WHERE id=77867;
UPDATE laus SET name_national=N'Geertruidenberg', name_latin=N'Geertruidenberg', abac_name=N'Geertruidenberg', display_name=N'Geertruidenberg' WHERE id=77770;
UPDATE laus SET name_national=N'Geldermalsen', name_latin=N'Geldermalsen', abac_name=N'Geldermalsen', display_name=N'Geldermalsen' WHERE id=77602;
UPDATE laus SET name_national=N'Geldrop-Mierlo', name_latin=N'Geldrop-Mierlo', abac_name=N'Geldrop-Mierlo', display_name=N'Geldrop-Mierlo' WHERE id=77878;
UPDATE laus SET name_national=N'Gemert-Bakel', name_latin=N'Gemert-Bakel', abac_name=N'Gemert-Bakel', display_name=N'Gemert-Bakel' WHERE id=77839;
UPDATE laus SET name_national=N'Gennep', name_latin=N'Gennep', abac_name=N'Gennep', display_name=N'Gennep' WHERE id=77810;
UPDATE laus SET name_national=N'Giessenlanden', name_latin=N'Giessenlanden', abac_name=N'Giessenlanden', display_name=N'Giessenlanden' WHERE id=77745;
UPDATE laus SET name_national=N'Gilze en Rijen', name_latin=N'Gilze en Rijen', abac_name=N'Gilze en Rijen', display_name=N'Gilze en Rijen' WHERE id=77771;
UPDATE laus SET name_national=N'Goeree-Overflakkee', name_latin=N'Goeree-Overflakkee', abac_name=N'Goeree-Overflakkee', display_name=N'Goeree-Overflakkee' WHERE id=77898;
UPDATE laus SET name_national=N'Goes', name_latin=N'Goes', abac_name=N'Goes', display_name=N'Goes' WHERE id=77740;
UPDATE laus SET name_national=N'Goirle', name_latin=N'Goirle', abac_name=N'Goirle', display_name=N'Goirle' WHERE id=77772;
UPDATE laus SET name_national=N'Gooise Meren', name_latin=N'Gooise Meren', abac_name=N'Gooise Meren', display_name=N'Gooise Meren' WHERE id=77904;
UPDATE laus SET name_national=N'Gorinchem', name_latin=N'Gorinchem', abac_name=N'Gorinchem', display_name=N'Gorinchem' WHERE id=77697;
UPDATE laus SET name_national=N'Gouda', name_latin=N'Gouda', abac_name=N'Gouda', display_name=N'Gouda' WHERE id=77698;
UPDATE laus SET name_national=N'Grave', name_latin=N'Grave', abac_name=N'Grave', display_name=N'Grave' WHERE id=77773;
UPDATE laus SET name_national=N'Groningen', name_latin=N'Groningen', abac_name=N'Groningen', display_name=N'Groningen' WHERE id=77535;
UPDATE laus SET name_national=N'Grootegast', name_latin=N'Grootegast', abac_name=N'Grootegast', display_name=N'Grootegast' WHERE id=77536;
UPDATE laus SET name_national=N'Gulpen-Wittem', name_latin=N'Gulpen-Wittem', abac_name=N'Gulpen-Wittem', display_name=N'Gulpen-Wittem' WHERE id=77871;
UPDATE laus SET name_national=N'Haaksbergen', name_latin=N'Haaksbergen', abac_name=N'Haaksbergen', display_name=N'Haaksbergen' WHERE id=77571;
UPDATE laus SET name_national=N'Haaren', name_latin=N'Haaren', abac_name=N'Haaren', display_name=N'Haaren' WHERE id=77774;
UPDATE laus SET name_national=N'Haarlem', name_latin=N'Haarlem', abac_name=N'Haarlem', display_name=N'Haarlem' WHERE id=77662;
UPDATE laus SET name_national=N'Haarlemmerliede en Spaarnwoude', name_latin=N'Haarlemmerliede en Spaarnwoude', abac_name=N'Haarlemmerliede en Spaarnwoude', display_name=N'Haarlemmerliede en Spaarnwoude' WHERE id=77663;
UPDATE laus SET name_national=N'Haarlemmermeer', name_latin=N'Haarlemmermeer', abac_name=N'Haarlemmermeer', display_name=N'Haarlemmermeer' WHERE id=77664;
UPDATE laus SET name_national=N'Halderberge', name_latin=N'Halderberge', abac_name=N'Halderberge', display_name=N'Halderberge' WHERE id=77840;
UPDATE laus SET name_national=N'Hardenberg', name_latin=N'Hardenberg', abac_name=N'Hardenberg', display_name=N'Hardenberg' WHERE id=77572;
UPDATE laus SET name_national=N'Harderwijk', name_latin=N'Harderwijk', abac_name=N'Harderwijk', display_name=N'Harderwijk' WHERE id=77603;
UPDATE laus SET name_national=N'Hardinxveld-Giessendam', name_latin=N'Hardinxveld-Giessendam', abac_name=N'Hardinxveld-Giessendam', display_name=N'Hardinxveld-Giessendam' WHERE id=77700;
UPDATE laus SET name_national=N'Haren', name_latin=N'Haren', abac_name=N'Haren', display_name=N'Haren' WHERE id=77537;
UPDATE laus SET name_national=N'Harlingen', name_latin=N'Harlingen', abac_name=N'Harlingen', display_name=N'Harlingen' WHERE id=77550;
UPDATE laus SET name_national=N'Hattem', name_latin=N'Hattem', abac_name=N'Hattem', display_name=N'Hattem' WHERE id=77604;
UPDATE laus SET name_national=N'Heemskerk', name_latin=N'Heemskerk', abac_name=N'Heemskerk', display_name=N'Heemskerk' WHERE id=77665;
UPDATE laus SET name_national=N'Heemstede', name_latin=N'Heemstede', abac_name=N'Heemstede', display_name=N'Heemstede' WHERE id=77666;
UPDATE laus SET name_national=N'Heerde', name_latin=N'Heerde', abac_name=N'Heerde', display_name=N'Heerde' WHERE id=77605;
UPDATE laus SET name_national=N'Heerenveen', name_latin=N'Heerenveen', abac_name=N'Heerenveen', display_name=N'Heerenveen' WHERE id=77551;
UPDATE laus SET name_national=N'Heerhugowaard', name_latin=N'Heerhugowaard', abac_name=N'Heerhugowaard', display_name=N'Heerhugowaard' WHERE id=77667;
UPDATE laus SET name_national=N'Heerlen', name_latin=N'Heerlen', abac_name=N'Heerlen', display_name=N'Heerlen' WHERE id=77811;
UPDATE laus SET name_national=N'Heeze-Leende', name_latin=N'Heeze-Leende', abac_name=N'Heeze-Leende', display_name=N'Heeze-Leende' WHERE id=77841;
UPDATE laus SET name_national=N'Heiloo', name_latin=N'Heiloo', abac_name=N'Heiloo', display_name=N'Heiloo' WHERE id=77668;
UPDATE laus SET name_national=N'Hellendoorn', name_latin=N'Hellendoorn', abac_name=N'Hellendoorn', display_name=N'Hellendoorn' WHERE id=77573;
UPDATE laus SET name_national=N'Hellevoetsluis', name_latin=N'Hellevoetsluis', abac_name=N'Hellevoetsluis', display_name=N'Hellevoetsluis' WHERE id=77701;
UPDATE laus SET name_national=N'Helmond', name_latin=N'Helmond', abac_name=N'Helmond', display_name=N'Helmond' WHERE id=77775;
UPDATE laus SET name_national=N'Hendrik-Ido-Ambacht', name_latin=N'Hendrik-Ido-Ambacht', abac_name=N'Hendrik-Ido-Ambacht', display_name=N'Hendrik-Ido-Ambacht' WHERE id=77702;
UPDATE laus SET name_national=N'Hengelo', name_latin=N'Hengelo', abac_name=N'Hengelo', display_name=N'Hengelo' WHERE id=77574;
UPDATE laus SET name_national=N'Heumen', name_latin=N'Heumen', abac_name=N'Heumen', display_name=N'Heumen' WHERE id=77606;
UPDATE laus SET name_national=N'Heusden', name_latin=N'Heusden', abac_name=N'Heusden', display_name=N'Heusden' WHERE id=77777;
UPDATE laus SET name_national=N'Hillegom', name_latin=N'Hillegom', abac_name=N'Hillegom', display_name=N'Hillegom' WHERE id=77704;
UPDATE laus SET name_national=N'Hilvarenbeek', name_latin=N'Hilvarenbeek', abac_name=N'Hilvarenbeek', display_name=N'Hilvarenbeek' WHERE id=77778;
UPDATE laus SET name_national=N'Hilversum', name_latin=N'Hilversum', abac_name=N'Hilversum', display_name=N'Hilversum' WHERE id=77670;
UPDATE laus SET name_national=N'Hof van Twente', name_latin=N'Hof van Twente', abac_name=N'Hof van Twente', display_name=N'Hof van Twente' WHERE id=77875;
UPDATE laus SET name_national=N'Hollands Kroon', name_latin=N'Hollands Kroon', abac_name=N'Hollands Kroon', display_name=N'Hollands Kroon' WHERE id=77896;
UPDATE laus SET name_national=N'Hoogeveen', name_latin=N'Hoogeveen', abac_name=N'Hoogeveen', display_name=N'Hoogeveen' WHERE id=77564;
UPDATE laus SET name_national=N'Hoorn', name_latin=N'Hoorn', abac_name=N'Hoorn', display_name=N'Hoorn' WHERE id=77671;
UPDATE laus SET name_national=N'Horst aan de Maas', name_latin=N'Horst aan de Maas', abac_name=N'Horst aan de Maas', display_name=N'Horst aan de Maas' WHERE id=77829;
UPDATE laus SET name_national=N'Houten', name_latin=N'Houten', abac_name=N'Houten', display_name=N'Houten' WHERE id=77635;
UPDATE laus SET name_national=N'Huizen', name_latin=N'Huizen', abac_name=N'Huizen', display_name=N'Huizen' WHERE id=77672;
UPDATE laus SET name_national=N'Hulst', name_latin=N'Hulst', abac_name=N'Hulst', display_name=N'Hulst' WHERE id=77742;
UPDATE laus SET name_national=N'IJsselstein', name_latin=N'IJsselstein', abac_name=N'IJsselstein', display_name=N'IJsselstein' WHERE id=77646;
UPDATE laus SET name_national=N'Kaag en Braassem', name_latin=N'Kaag en Braassem', abac_name=N'Kaag en Braassem', display_name=N'Kaag en Braassem' WHERE id=77886;
UPDATE laus SET name_national=N'Kampen', name_latin=N'Kampen', abac_name=N'Kampen', display_name=N'Kampen' WHERE id=77575;
UPDATE laus SET name_national=N'Kapelle', name_latin=N'Kapelle', abac_name=N'Kapelle', display_name=N'Kapelle' WHERE id=77743;
UPDATE laus SET name_national=N'Katwijk', name_latin=N'Katwijk', abac_name=N'Katwijk', display_name=N'Katwijk' WHERE id=77705;
UPDATE laus SET name_national=N'Kerkrade', name_latin=N'Kerkrade', abac_name=N'Kerkrade', display_name=N'Kerkrade' WHERE id=77812;
UPDATE laus SET name_national=N'Koggenland', name_latin=N'Koggenland', abac_name=N'Koggenland', display_name=N'Koggenland' WHERE id=77834;
UPDATE laus SET name_national=N'Kollumerland en Nieuwkruisland', name_latin=N'Kollumerland en Nieuwkruisland', abac_name=N'Kollumerland en Nieuwkruisland', display_name=N'Kollumerland en Nieuwkruisland' WHERE id=77552;
UPDATE laus SET name_national=N'Korendijk', name_latin=N'Korendijk', abac_name=N'Korendijk', display_name=N'Korendijk' WHERE id=77718;
UPDATE laus SET name_national=N'Krimpen aan den IJssel', name_latin=N'Krimpen aan den IJssel', abac_name=N'Krimpen aan den IJssel', display_name=N'Krimpen aan den IJssel' WHERE id=77706;
UPDATE laus SET name_national=N'Krimpenerwaard', name_latin=N'Krimpenerwaard', abac_name=N'Krimpenerwaard', display_name=N'Krimpenerwaard' WHERE id=77902;
UPDATE laus SET name_national=N'Laarbeek', name_latin=N'Laarbeek', abac_name=N'Laarbeek', display_name=N'Laarbeek' WHERE id=77842;
UPDATE laus SET name_national=N'Landerd', name_latin=N'Landerd', abac_name=N'Landerd', display_name=N'Landerd' WHERE id=77851;
UPDATE laus SET name_national=N'Landgraaf', name_latin=N'Landgraaf', abac_name=N'Landgraaf', display_name=N'Landgraaf' WHERE id=77805;
UPDATE laus SET name_national=N'Landsmeer', name_latin=N'Landsmeer', abac_name=N'Landsmeer', display_name=N'Landsmeer' WHERE id=77673;
UPDATE laus SET name_national=N'Langedijk', name_latin=N'Langedijk', abac_name=N'Langedijk', display_name=N'Langedijk' WHERE id=77674;
UPDATE laus SET name_national=N'Lansingerland', name_latin=N'Lansingerland', abac_name=N'Lansingerland', display_name=N'Lansingerland' WHERE id=77835;
UPDATE laus SET name_national=N'Laren', name_latin=N'Laren', abac_name=N'Laren', display_name=N'Laren' WHERE id=77675;
UPDATE laus SET name_national=N'Leek', name_latin=N'Leek', abac_name=N'Leek', display_name=N'Leek' WHERE id=77538;
UPDATE laus SET name_national=N'Leerdam', name_latin=N'Leerdam', abac_name=N'Leerdam', display_name=N'Leerdam' WHERE id=77707;
UPDATE laus SET name_national=N'Leeuwarden', name_latin=N'Leeuwarden', abac_name=N'Leeuwarden', display_name=N'Leeuwarden' WHERE id=77553;
UPDATE laus SET name_national=N'Leiden', name_latin=N'Leiden', abac_name=N'Leiden', display_name=N'Leiden' WHERE id=77708;
UPDATE laus SET name_national=N'Leiderdorp', name_latin=N'Leiderdorp', abac_name=N'Leiderdorp', display_name=N'Leiderdorp' WHERE id=77709;
UPDATE laus SET name_national=N'Leidschendam-Voorburg', name_latin=N'Leidschendam-Voorburg', abac_name=N'Leidschendam-Voorburg', display_name=N'Leidschendam-Voorburg' WHERE id=77897;
UPDATE laus SET name_national=N'Lelystad', name_latin=N'Lelystad', abac_name=N'Lelystad', display_name=N'Lelystad' WHERE id=77828;
UPDATE laus SET name_national=N'Leudal', name_latin=N'Leudal', abac_name=N'Leudal', display_name=N'Leudal' WHERE id=77836;
UPDATE laus SET name_national=N'Leusden', name_latin=N'Leusden', abac_name=N'Leusden', display_name=N'Leusden' WHERE id=77636;
UPDATE laus SET name_national=N'Lingewaal', name_latin=N'Lingewaal', abac_name=N'Lingewaal', display_name=N'Lingewaal' WHERE id=77752;
UPDATE laus SET name_national=N'Lingewaard', name_latin=N'Lingewaard', abac_name=N'Lingewaard', display_name=N'Lingewaard' WHERE id=77859;
UPDATE laus SET name_national=N'Lisse', name_latin=N'Lisse', abac_name=N'Lisse', display_name=N'Lisse' WHERE id=77710;
UPDATE laus SET name_national=N'Lochem', name_latin=N'Lochem', abac_name=N'Lochem', display_name=N'Lochem' WHERE id=77607;
UPDATE laus SET name_national=N'Loon op Zand', name_latin=N'Loon op Zand', abac_name=N'Loon op Zand', display_name=N'Loon op Zand' WHERE id=77779;
UPDATE laus SET name_national=N'Lopik', name_latin=N'Lopik', abac_name=N'Lopik', display_name=N'Lopik' WHERE id=77637;
UPDATE laus SET name_national=N'Loppersum', name_latin=N'Loppersum', abac_name=N'Loppersum', display_name=N'Loppersum' WHERE id=77539;
UPDATE laus SET name_national=N'Losser', name_latin=N'Losser', abac_name=N'Losser', display_name=N'Losser' WHERE id=77576;
UPDATE laus SET name_national=N'Maasdriel', name_latin=N'Maasdriel', abac_name=N'Maasdriel', display_name=N'Maasdriel' WHERE id=77608;
UPDATE laus SET name_national=N'Maasgouw', name_latin=N'Maasgouw', abac_name=N'Maasgouw', display_name=N'Maasgouw' WHERE id=77837;
UPDATE laus SET name_national=N'Maassluis', name_latin=N'Maassluis', abac_name=N'Maassluis', display_name=N'Maassluis' WHERE id=77711;
UPDATE laus SET name_national=N'Maastricht', name_latin=N'Maastricht', abac_name=N'Maastricht', display_name=N'Maastricht' WHERE id=77813;
UPDATE laus SET name_national=N'Marum', name_latin=N'Marum', abac_name=N'Marum', display_name=N'Marum' WHERE id=77540;
UPDATE laus SET name_national=N'Medemblik', name_latin=N'Medemblik', abac_name=N'Medemblik', display_name=N'Medemblik' WHERE id=77676;
UPDATE laus SET name_national=N'Meerssen', name_latin=N'Meerssen', abac_name=N'Meerssen', display_name=N'Meerssen' WHERE id=77814;
UPDATE laus SET name_national=N'Meppel', name_latin=N'Meppel', abac_name=N'Meppel', display_name=N'Meppel' WHERE id=77565;
UPDATE laus SET name_national=N'Middelburg', name_latin=N'Middelburg', abac_name=N'Middelburg', display_name=N'Middelburg' WHERE id=77744;
UPDATE laus SET name_national=N'Midden-Delfland', name_latin=N'Midden-Delfland', abac_name=N'Midden-Delfland', display_name=N'Midden-Delfland' WHERE id=77882;
UPDATE laus SET name_national=N'Midden-Drenthe', name_latin=N'Midden-Drenthe', abac_name=N'Midden-Drenthe', display_name=N'Midden-Drenthe' WHERE id=77873;
UPDATE laus SET name_national=N'Mill en Sint Hubert', name_latin=N'Mill en Sint Hubert', abac_name=N'Mill en Sint Hubert', display_name=N'Mill en Sint Hubert' WHERE id=77780;
UPDATE laus SET name_national=N'Moerdijk', name_latin=N'Moerdijk', abac_name=N'Moerdijk', display_name=N'Moerdijk' WHERE id=77862;
UPDATE laus SET name_national=N'Molenwaard', name_latin=N'Molenwaard', abac_name=N'Molenwaard', display_name=N'Molenwaard' WHERE id=77900;
UPDATE laus SET name_national=N'Montferland', name_latin=N'Montferland', abac_name=N'Montferland', display_name=N'Montferland' WHERE id=77906;
UPDATE laus SET name_national=N'Montfoort', name_latin=N'Montfoort', abac_name=N'Montfoort', display_name=N'Montfoort' WHERE id=77638;
UPDATE laus SET name_national=N'Mook en Middelaar', name_latin=N'Mook en Middelaar', abac_name=N'Mook en Middelaar', display_name=N'Mook en Middelaar' WHERE id=77815;
UPDATE laus SET name_national=N'Neder-Betuwe', name_latin=N'Neder-Betuwe', abac_name=N'Neder-Betuwe', display_name=N'Neder-Betuwe' WHERE id=77876;
UPDATE laus SET name_national=N'Nederweert', name_latin=N'Nederweert', abac_name=N'Nederweert', display_name=N'Nederweert' WHERE id=77816;
UPDATE laus SET name_national=N'Neerijnen', name_latin=N'Neerijnen', abac_name=N'Neerijnen', display_name=N'Neerijnen' WHERE id=77628;
UPDATE laus SET name_national=N'Nieuwegein', name_latin=N'Nieuwegein', abac_name=N'Nieuwegein', display_name=N'Nieuwegein' WHERE id=77648;
UPDATE laus SET name_national=N'Nieuwkoop', name_latin=N'Nieuwkoop', abac_name=N'Nieuwkoop', display_name=N'Nieuwkoop' WHERE id=77712;
UPDATE laus SET name_national=N'Nijkerk', name_latin=N'Nijkerk', abac_name=N'Nijkerk', display_name=N'Nijkerk' WHERE id=77609;
UPDATE laus SET name_national=N'Nijmegen', name_latin=N'Nijmegen', abac_name=N'Nijmegen', display_name=N'Nijmegen' WHERE id=77610;
UPDATE laus SET name_national=N'Nissewaard', name_latin=N'Nissewaard', abac_name=N'Nissewaard', display_name=N'Nissewaard' WHERE id=77901;
UPDATE laus SET name_national=N'Noord-Beveland', name_latin=N'Noord-Beveland', abac_name=N'Noord-Beveland', display_name=N'Noord-Beveland' WHERE id=77853;
UPDATE laus SET name_national=N'Noordenveld', name_latin=N'Noordenveld', abac_name=N'Noordenveld', display_name=N'Noordenveld' WHERE id=77855;
UPDATE laus SET name_national=N'Noordoostpolder', name_latin=N'Noordoostpolder', abac_name=N'Noordoostpolder', display_name=N'Noordoostpolder' WHERE id=77577;
UPDATE laus SET name_national=N'Noordwijk', name_latin=N'Noordwijk', abac_name=N'Noordwijk', display_name=N'Noordwijk' WHERE id=77713;
UPDATE laus SET name_national=N'Noordwijkerhout', name_latin=N'Noordwijkerhout', abac_name=N'Noordwijkerhout', display_name=N'Noordwijkerhout' WHERE id=77714;
UPDATE laus SET name_national=N'Nuenen, Gerwen en Nederwetten', name_latin=N'Nuenen, Gerwen en Nederwetten', abac_name=N'Nuenen, Gerwen en Nederwetten', display_name=N'Nuenen, Gerwen en Nederwetten' WHERE id=77781;
UPDATE laus SET name_national=N'Nunspeet', name_latin=N'Nunspeet', abac_name=N'Nunspeet', display_name=N'Nunspeet' WHERE id=77626;
UPDATE laus SET name_national=N'Nuth', name_latin=N'Nuth', abac_name=N'Nuth', display_name=N'Nuth' WHERE id=77817;
UPDATE laus SET name_national=N'Oegstgeest', name_latin=N'Oegstgeest', abac_name=N'Oegstgeest', display_name=N'Oegstgeest' WHERE id=77715;
UPDATE laus SET name_national=N'Oirschot', name_latin=N'Oirschot', abac_name=N'Oirschot', display_name=N'Oirschot' WHERE id=77782;
UPDATE laus SET name_national=N'Oisterwijk', name_latin=N'Oisterwijk', abac_name=N'Oisterwijk', display_name=N'Oisterwijk' WHERE id=77783;
UPDATE laus SET name_national=N'Oldambt', name_latin=N'Oldambt', abac_name=N'Oldambt', display_name=N'Oldambt' WHERE id=77890;
UPDATE laus SET name_national=N'Oldebroek', name_latin=N'Oldebroek', abac_name=N'Oldebroek', display_name=N'Oldebroek' WHERE id=77611;
UPDATE laus SET name_national=N'Oldenzaal', name_latin=N'Oldenzaal', abac_name=N'Oldenzaal', display_name=N'Oldenzaal' WHERE id=77578;
UPDATE laus SET name_national=N'Olst-Wijhe', name_latin=N'Olst-Wijhe', abac_name=N'Olst-Wijhe', display_name=N'Olst-Wijhe' WHERE id=77879;
UPDATE laus SET name_national=N'Ommen', name_latin=N'Ommen', abac_name=N'Ommen', display_name=N'Ommen' WHERE id=77579;
UPDATE laus SET name_national=N'Onderbanken', name_latin=N'Onderbanken', abac_name=N'Onderbanken', display_name=N'Onderbanken' WHERE id=77804;
UPDATE laus SET name_national=N'Oost Gelre', name_latin=N'Oost Gelre', abac_name=N'Oost Gelre', display_name=N'Oost Gelre' WHERE id=77833;
UPDATE laus SET name_national=N'Oosterhout', name_latin=N'Oosterhout', abac_name=N'Oosterhout', display_name=N'Oosterhout' WHERE id=77784;
UPDATE laus SET name_national=N'Ooststellingwerf', name_latin=N'Ooststellingwerf', abac_name=N'Ooststellingwerf', display_name=N'Ooststellingwerf' WHERE id=77554;
UPDATE laus SET name_national=N'Oostzaan', name_latin=N'Oostzaan', abac_name=N'Oostzaan', display_name=N'Oostzaan' WHERE id=77677;
UPDATE laus SET name_national=N'Opmeer', name_latin=N'Opmeer', abac_name=N'Opmeer', display_name=N'Opmeer' WHERE id=77678;
UPDATE laus SET name_national=N'Opsterland', name_latin=N'Opsterland', abac_name=N'Opsterland', display_name=N'Opsterland' WHERE id=77555;
UPDATE laus SET name_national=N'Oss', name_latin=N'Oss', abac_name=N'Oss', display_name=N'Oss' WHERE id=77785;
UPDATE laus SET name_national=N'Oud-Beijerland', name_latin=N'Oud-Beijerland', abac_name=N'Oud-Beijerland', display_name=N'Oud-Beijerland' WHERE id=77716;
UPDATE laus SET name_national=N'Oude IJsselstreek', name_latin=N'Oude IJsselstreek', abac_name=N'Oude IJsselstreek', display_name=N'Oude IJsselstreek' WHERE id=77830;
UPDATE laus SET name_national=N'Ouder-Amstel', name_latin=N'Ouder-Amstel', abac_name=N'Ouder-Amstel', display_name=N'Ouder-Amstel' WHERE id=77679;
UPDATE laus SET name_national=N'Oudewater', name_latin=N'Oudewater', abac_name=N'Oudewater', display_name=N'Oudewater' WHERE id=77719;
UPDATE laus SET name_national=N'Overbetuwe', name_latin=N'Overbetuwe', abac_name=N'Overbetuwe', display_name=N'Overbetuwe' WHERE id=77874;
UPDATE laus SET name_national=N'Papendrecht', name_latin=N'Papendrecht', abac_name=N'Papendrecht', display_name=N'Papendrecht' WHERE id=77720;
UPDATE laus SET name_national=N'Peel en Maas', name_latin=N'Peel en Maas', abac_name=N'Peel en Maas', display_name=N'Peel en Maas' WHERE id=77889;
UPDATE laus SET name_national=N'Pekela', name_latin=N'Pekela', abac_name=N'Pekela', display_name=N'Pekela' WHERE id=77765;
UPDATE laus SET name_national=N'Pijnacker-Nootdorp', name_latin=N'Pijnacker-Nootdorp', abac_name=N'Pijnacker-Nootdorp', display_name=N'Pijnacker-Nootdorp' WHERE id=77899;
UPDATE laus SET name_national=N'Purmerend', name_latin=N'Purmerend', abac_name=N'Purmerend', display_name=N'Purmerend' WHERE id=77680;
UPDATE laus SET name_national=N'Putten', name_latin=N'Putten', abac_name=N'Putten', display_name=N'Putten' WHERE id=77612;
UPDATE laus SET name_national=N'Raalte', name_latin=N'Raalte', abac_name=N'Raalte', display_name=N'Raalte' WHERE id=77580;
UPDATE laus SET name_national=N'Reimerswaal', name_latin=N'Reimerswaal', abac_name=N'Reimerswaal', display_name=N'Reimerswaal' WHERE id=77746;
UPDATE laus SET name_national=N'Renkum', name_latin=N'Renkum', abac_name=N'Renkum', display_name=N'Renkum' WHERE id=77613;
UPDATE laus SET name_national=N'Renswoude', name_latin=N'Renswoude', abac_name=N'Renswoude', display_name=N'Renswoude' WHERE id=77639;
UPDATE laus SET name_national=N'Reusel-De Mierden', name_latin=N'Reusel-De Mierden', abac_name=N'Reusel-De Mierden', display_name=N'Reusel-De Mierden' WHERE id=77844;
UPDATE laus SET name_national=N'Rheden', name_latin=N'Rheden', abac_name=N'Rheden', display_name=N'Rheden' WHERE id=77614;
UPDATE laus SET name_national=N'Rhenen', name_latin=N'Rhenen', abac_name=N'Rhenen', display_name=N'Rhenen' WHERE id=77640;
UPDATE laus SET name_national=N'Ridderkerk', name_latin=N'Ridderkerk', abac_name=N'Ridderkerk', display_name=N'Ridderkerk' WHERE id=77721;
UPDATE laus SET name_national=N'Rijssen-Holten', name_latin=N'Rijssen-Holten', abac_name=N'Rijssen-Holten', display_name=N'Rijssen-Holten' WHERE id=77877;
UPDATE laus SET name_national=N'Rijswijk', name_latin=N'Rijswijk', abac_name=N'Rijswijk', display_name=N'Rijswijk' WHERE id=77723;
UPDATE laus SET name_national=N'Roerdalen', name_latin=N'Roerdalen', abac_name=N'Roerdalen', display_name=N'Roerdalen' WHERE id=77845;
UPDATE laus SET name_national=N'Roermond', name_latin=N'Roermond', abac_name=N'Roermond', display_name=N'Roermond' WHERE id=77818;
UPDATE laus SET name_national=N'Roosendaal', name_latin=N'Roosendaal', abac_name=N'Roosendaal', display_name=N'Roosendaal' WHERE id=77846;
UPDATE laus SET name_national=N'Rotterdam', name_latin=N'Rotterdam', abac_name=N'Rotterdam', display_name=N'Rotterdam' WHERE id=77722;
UPDATE laus SET name_national=N'Rozendaal', name_latin=N'Rozendaal', abac_name=N'Rozendaal', display_name=N'Rozendaal' WHERE id=77615;
UPDATE laus SET name_national=N'Rucphen', name_latin=N'Rucphen', abac_name=N'Rucphen', display_name=N'Rucphen' WHERE id=77786;
UPDATE laus SET name_national=N'Schagen', name_latin=N'Schagen', abac_name=N'Schagen', display_name=N'Schagen' WHERE id=77681;
UPDATE laus SET name_national=N'Scherpenzeel', name_latin=N'Scherpenzeel', abac_name=N'Scherpenzeel', display_name=N'Scherpenzeel' WHERE id=77616;
UPDATE laus SET name_national=N'Schiedam', name_latin=N'Schiedam', abac_name=N'Schiedam', display_name=N'Schiedam' WHERE id=77724;
UPDATE laus SET name_national=N'Schiermonnikoog', name_latin=N'Schiermonnikoog', abac_name=N'Schiermonnikoog', display_name=N'Schiermonnikoog' WHERE id=77556;
UPDATE laus SET name_national=N'Schinnen', name_latin=N'Schinnen', abac_name=N'Schinnen', display_name=N'Schinnen' WHERE id=77819;
UPDATE laus SET name_national=N'Schouwen-Duiveland', name_latin=N'Schouwen-Duiveland', abac_name=N'Schouwen-Duiveland', display_name=N'Schouwen-Duiveland' WHERE id=77847;
UPDATE laus SET name_national=N'''s-Gravenhage', name_latin=N'''s-Gravenhage', abac_name=N'''s-Gravenhage', display_name=N'''s-Gravenhage' WHERE id=77699;
UPDATE laus SET name_national=N'''s-Hertogenbosch', name_latin=N'''s-Hertogenbosch', abac_name=N'''s-Hertogenbosch', display_name=N'''s-Hertogenbosch' WHERE id=77776;
UPDATE laus SET name_national=N'Simpelveld', name_latin=N'Simpelveld', abac_name=N'Simpelveld', display_name=N'Simpelveld' WHERE id=77820;
UPDATE laus SET name_national=N'Sint Anthonis', name_latin=N'Sint Anthonis', abac_name=N'Sint Anthonis', display_name=N'Sint Anthonis' WHERE id=77858;
UPDATE laus SET name_national=N'Sint-Michielsgestel', name_latin=N'Sint-Michielsgestel', abac_name=N'Sint-Michielsgestel', display_name=N'Sint-Michielsgestel' WHERE id=77787;
UPDATE laus SET name_national=N'Sittard-Geleen', name_latin=N'Sittard-Geleen', abac_name=N'Sittard-Geleen', display_name=N'Sittard-Geleen' WHERE id=77885;
UPDATE laus SET name_national=N'Sliedrecht', name_latin=N'Sliedrecht', abac_name=N'Sliedrecht', display_name=N'Sliedrecht' WHERE id=77725;
UPDATE laus SET name_national=N'Sluis', name_latin=N'Sluis', abac_name=N'Sluis', display_name=N'Sluis' WHERE id=77864;
UPDATE laus SET name_national=N'Smallingerland', name_latin=N'Smallingerland', abac_name=N'Smallingerland', display_name=N'Smallingerland' WHERE id=77557;
UPDATE laus SET name_national=N'Soest', name_latin=N'Soest', abac_name=N'Soest', display_name=N'Soest' WHERE id=77641;
UPDATE laus SET name_national=N'Someren', name_latin=N'Someren', abac_name=N'Someren', display_name=N'Someren' WHERE id=77788;
UPDATE laus SET name_national=N'Son en Breugel', name_latin=N'Son en Breugel', abac_name=N'Son en Breugel', display_name=N'Son en Breugel' WHERE id=77789;
UPDATE laus SET name_national=N'Stadskanaal', name_latin=N'Stadskanaal', abac_name=N'Stadskanaal', display_name=N'Stadskanaal' WHERE id=77542;
UPDATE laus SET name_national=N'Staphorst', name_latin=N'Staphorst', abac_name=N'Staphorst', display_name=N'Staphorst' WHERE id=77581;
UPDATE laus SET name_national=N'Stede Broec', name_latin=N'Stede Broec', abac_name=N'Stede Broec', display_name=N'Stede Broec' WHERE id=77703;
UPDATE laus SET name_national=N'Steenbergen', name_latin=N'Steenbergen', abac_name=N'Steenbergen', display_name=N'Steenbergen' WHERE id=77790;
UPDATE laus SET name_national=N'Steenwijkerland', name_latin=N'Steenwijkerland', abac_name=N'Steenwijkerland', display_name=N'Steenwijkerland' WHERE id=77861;
UPDATE laus SET name_national=N'Stein', name_latin=N'Stein', abac_name=N'Stein', display_name=N'Stein' WHERE id=77821;
UPDATE laus SET name_national=N'Stichtse Vecht', name_latin=N'Stichtse Vecht', abac_name=N'Stichtse Vecht', display_name=N'Stichtse Vecht' WHERE id=77895;
UPDATE laus SET name_national=N'Strijen', name_latin=N'Strijen', abac_name=N'Strijen', display_name=N'Strijen' WHERE id=77729;
UPDATE laus SET name_national=N'Súdwest-Fryslân', name_latin=N'Súdwest-Fryslân', abac_name=N'Sudwest-Fryslan', display_name=N'Súdwest-Fryslân' WHERE id=77892;
UPDATE laus SET name_national=N'Ten Boer', name_latin=N'Ten Boer', abac_name=N'Ten Boer', display_name=N'Ten Boer' WHERE id=77533;
UPDATE laus SET name_national=N'Terneuzen', name_latin=N'Terneuzen', abac_name=N'Terneuzen', display_name=N'Terneuzen' WHERE id=77748;
UPDATE laus SET name_national=N'Terschelling', name_latin=N'Terschelling', abac_name=N'Terschelling', display_name=N'Terschelling' WHERE id=77558;
UPDATE laus SET name_national=N'Texel', name_latin=N'Texel', abac_name=N'Texel', display_name=N'Texel' WHERE id=77682;
UPDATE laus SET name_national=N'Teylingen', name_latin=N'Teylingen', abac_name=N'Teylingen', display_name=N'Teylingen' WHERE id=77831;
UPDATE laus SET name_national=N'Tholen', name_latin=N'Tholen', abac_name=N'Tholen', display_name=N'Tholen' WHERE id=77749;
UPDATE laus SET name_national=N'Tiel', name_latin=N'Tiel', abac_name=N'Tiel', display_name=N'Tiel' WHERE id=77617;
UPDATE laus SET name_national=N'Tilburg', name_latin=N'Tilburg', abac_name=N'Tilburg', display_name=N'Tilburg' WHERE id=77792;
UPDATE laus SET name_national=N'Tubbergen', name_latin=N'Tubbergen', abac_name=N'Tubbergen', display_name=N'Tubbergen' WHERE id=77582;
UPDATE laus SET name_national=N'Twenterand', name_latin=N'Twenterand', abac_name=N'Twenterand', display_name=N'Twenterand' WHERE id=77856;
UPDATE laus SET name_national=N'Tynaarlo', name_latin=N'Tynaarlo', abac_name=N'Tynaarlo', display_name=N'Tynaarlo' WHERE id=77872;
UPDATE laus SET name_national=N'Tytsjerksteradiel', name_latin=N'Tytsjerksteradiel', abac_name=N'Tytsjerksteradiel', display_name=N'Tytsjerksteradiel' WHERE id=77754;
UPDATE laus SET name_national=N'Uden', name_latin=N'Uden', abac_name=N'Uden', display_name=N'Uden' WHERE id=77793;
UPDATE laus SET name_national=N'Uitgeest', name_latin=N'Uitgeest', abac_name=N'Uitgeest', display_name=N'Uitgeest' WHERE id=77683;
UPDATE laus SET name_national=N'Uithoorn', name_latin=N'Uithoorn', abac_name=N'Uithoorn', display_name=N'Uithoorn' WHERE id=77684;
UPDATE laus SET name_national=N'Urk', name_latin=N'Urk', abac_name=N'Urk', display_name=N'Urk' WHERE id=77583;
UPDATE laus SET name_national=N'Utrecht', name_latin=N'Utrecht', abac_name=N'Utrecht', display_name=N'Utrecht' WHERE id=77642;
UPDATE laus SET name_national=N'Utrechtse Heuvelrug', name_latin=N'Utrechtse Heuvelrug', abac_name=N'Utrechtse Heuvelrug', display_name=N'Utrechtse Heuvelrug' WHERE id=77832;
UPDATE laus SET name_national=N'Vaals', name_latin=N'Vaals', abac_name=N'Vaals', display_name=N'Vaals' WHERE id=77822;
UPDATE laus SET name_national=N'Valkenburg aan de Geul', name_latin=N'Valkenburg aan de Geul', abac_name=N'Valkenburg aan de Geul', display_name=N'Valkenburg aan de Geul' WHERE id=77827;
UPDATE laus SET name_national=N'Valkenswaard', name_latin=N'Valkenswaard', abac_name=N'Valkenswaard', display_name=N'Valkenswaard' WHERE id=77794;
UPDATE laus SET name_national=N'Veendam', name_latin=N'Veendam', abac_name=N'Veendam', display_name=N'Veendam' WHERE id=77543;
UPDATE laus SET name_national=N'Veenendaal', name_latin=N'Veenendaal', abac_name=N'Veenendaal', display_name=N'Veenendaal' WHERE id=77643;
UPDATE laus SET name_national=N'Veere', name_latin=N'Veere', abac_name=N'Veere', display_name=N'Veere' WHERE id=77750;
UPDATE laus SET name_national=N'Veldhoven', name_latin=N'Veldhoven', abac_name=N'Veldhoven', display_name=N'Veldhoven' WHERE id=77795;
UPDATE laus SET name_national=N'Velsen', name_latin=N'Velsen', abac_name=N'Velsen', display_name=N'Velsen' WHERE id=77685;
UPDATE laus SET name_national=N'Venlo', name_latin=N'Venlo', abac_name=N'Venlo', display_name=N'Venlo' WHERE id=77823;
UPDATE laus SET name_national=N'Venray', name_latin=N'Venray', abac_name=N'Venray', display_name=N'Venray' WHERE id=77824;
UPDATE laus SET name_national=N'Vianen', name_latin=N'Vianen', abac_name=N'Vianen', display_name=N'Vianen' WHERE id=77730;
UPDATE laus SET name_national=N'Vlaardingen', name_latin=N'Vlaardingen', abac_name=N'Vlaardingen', display_name=N'Vlaardingen' WHERE id=77731;
UPDATE laus SET name_national=N'Vlieland', name_latin=N'Vlieland', abac_name=N'Vlieland', display_name=N'Vlieland' WHERE id=77559;
UPDATE laus SET name_national=N'Vlissingen', name_latin=N'Vlissingen', abac_name=N'Vlissingen', display_name=N'Vlissingen' WHERE id=77751;
UPDATE laus SET name_national=N'Voerendaal', name_latin=N'Voerendaal', abac_name=N'Voerendaal', display_name=N'Voerendaal' WHERE id=77825;
UPDATE laus SET name_national=N'Voorschoten', name_latin=N'Voorschoten', abac_name=N'Voorschoten', display_name=N'Voorschoten' WHERE id=77732;
UPDATE laus SET name_national=N'Voorst', name_latin=N'Voorst', abac_name=N'Voorst', display_name=N'Voorst' WHERE id=77618;
UPDATE laus SET name_national=N'Vught', name_latin=N'Vught', abac_name=N'Vught', display_name=N'Vught' WHERE id=77796;
UPDATE laus SET name_national=N'Waalre', name_latin=N'Waalre', abac_name=N'Waalre', display_name=N'Waalre' WHERE id=77797;
UPDATE laus SET name_national=N'Waalwijk', name_latin=N'Waalwijk', abac_name=N'Waalwijk', display_name=N'Waalwijk' WHERE id=77798;
UPDATE laus SET name_national=N'Waddinxveen', name_latin=N'Waddinxveen', abac_name=N'Waddinxveen', display_name=N'Waddinxveen' WHERE id=77733;
UPDATE laus SET name_national=N'Wageningen', name_latin=N'Wageningen', abac_name=N'Wageningen', display_name=N'Wageningen' WHERE id=77619;
UPDATE laus SET name_national=N'Wassenaar', name_latin=N'Wassenaar', abac_name=N'Wassenaar', display_name=N'Wassenaar' WHERE id=77734;
UPDATE laus SET name_national=N'Waterland', name_latin=N'Waterland', abac_name=N'Waterland', display_name=N'Waterland' WHERE id=77791;
UPDATE laus SET name_national=N'Weert', name_latin=N'Weert', abac_name=N'Weert', display_name=N'Weert' WHERE id=77826;
UPDATE laus SET name_national=N'Weesp', name_latin=N'Weesp', abac_name=N'Weesp', display_name=N'Weesp' WHERE id=77686;
UPDATE laus SET name_national=N'Werkendam', name_latin=N'Werkendam', abac_name=N'Werkendam', display_name=N'Werkendam' WHERE id=77799;
UPDATE laus SET name_national=N'West Maas en Waal', name_latin=N'West Maas en Waal', abac_name=N'West Maas en Waal', display_name=N'West Maas en Waal' WHERE id=77741;
UPDATE laus SET name_national=N'Westerveld', name_latin=N'Westerveld', abac_name=N'Westerveld', display_name=N'Westerveld' WHERE id=77857;
UPDATE laus SET name_national=N'Westervoort', name_latin=N'Westervoort', abac_name=N'Westervoort', display_name=N'Westervoort' WHERE id=77620;
UPDATE laus SET name_national=N'Westland', name_latin=N'Westland', abac_name=N'Westland', display_name=N'Westland' WHERE id=77881;
UPDATE laus SET name_national=N'Weststellingwerf', name_latin=N'Weststellingwerf', abac_name=N'Weststellingwerf', display_name=N'Weststellingwerf' WHERE id=77560;
UPDATE laus SET name_national=N'Westvoorne', name_latin=N'Westvoorne', abac_name=N'Westvoorne', display_name=N'Westvoorne' WHERE id=77728;
UPDATE laus SET name_national=N'Wierden', name_latin=N'Wierden', abac_name=N'Wierden', display_name=N'Wierden' WHERE id=77584;
UPDATE laus SET name_national=N'Wijchen', name_latin=N'Wijchen', abac_name=N'Wijchen', display_name=N'Wijchen' WHERE id=77622;
UPDATE laus SET name_national=N'Wijdemeren', name_latin=N'Wijdemeren', abac_name=N'Wijdemeren', display_name=N'Wijdemeren' WHERE id=77854;
UPDATE laus SET name_national=N'Wijk bij Duurstede', name_latin=N'Wijk bij Duurstede', abac_name=N'Wijk bij Duurstede', display_name=N'Wijk bij Duurstede' WHERE id=77645;
UPDATE laus SET name_national=N'Winsum', name_latin=N'Winsum', abac_name=N'Winsum', display_name=N'Winsum' WHERE id=77545;
UPDATE laus SET name_national=N'Winterswijk', name_latin=N'Winterswijk', abac_name=N'Winterswijk', display_name=N'Winterswijk' WHERE id=77621;
UPDATE laus SET name_national=N'Woensdrecht', name_latin=N'Woensdrecht', abac_name=N'Woensdrecht', display_name=N'Woensdrecht' WHERE id=77800;
UPDATE laus SET name_national=N'Woerden', name_latin=N'Woerden', abac_name=N'Woerden', display_name=N'Woerden' WHERE id=77735;
UPDATE laus SET name_national=N'Wormerland', name_latin=N'Wormerland', abac_name=N'Wormerland', display_name=N'Wormerland' WHERE id=77803;
UPDATE laus SET name_national=N'Woudenberg', name_latin=N'Woudenberg', abac_name=N'Woudenberg', display_name=N'Woudenberg' WHERE id=77644;
UPDATE laus SET name_national=N'Woudrichem', name_latin=N'Woudrichem', abac_name=N'Woudrichem', display_name=N'Woudrichem' WHERE id=77801;
UPDATE laus SET name_national=N'Zaanstad', name_latin=N'Zaanstad', abac_name=N'Zaanstad', display_name=N'Zaanstad' WHERE id=77688;
UPDATE laus SET name_national=N'Zaltbommel', name_latin=N'Zaltbommel', abac_name=N'Zaltbommel', display_name=N'Zaltbommel' WHERE id=77623;
UPDATE laus SET name_national=N'Zandvoort', name_latin=N'Zandvoort', abac_name=N'Zandvoort', display_name=N'Zandvoort' WHERE id=77687;
UPDATE laus SET name_national=N'Zederik', name_latin=N'Zederik', abac_name=N'Zederik', display_name=N'Zederik' WHERE id=77747;
UPDATE laus SET name_national=N'Zeewolde', name_latin=N'Zeewolde', abac_name=N'Zeewolde', display_name=N'Zeewolde' WHERE id=77544;
UPDATE laus SET name_national=N'Zeist', name_latin=N'Zeist', abac_name=N'Zeist', display_name=N'Zeist' WHERE id=77647;
UPDATE laus SET name_national=N'Zevenaar', name_latin=N'Zevenaar', abac_name=N'Zevenaar', display_name=N'Zevenaar' WHERE id=77624;
UPDATE laus SET name_national=N'Zoetermeer', name_latin=N'Zoetermeer', abac_name=N'Zoetermeer', display_name=N'Zoetermeer' WHERE id=77736;
UPDATE laus SET name_national=N'Zoeterwoude', name_latin=N'Zoeterwoude', abac_name=N'Zoeterwoude', display_name=N'Zoeterwoude' WHERE id=77737;
UPDATE laus SET name_national=N'Zuidhorn', name_latin=N'Zuidhorn', abac_name=N'Zuidhorn', display_name=N'Zuidhorn' WHERE id=77546;
UPDATE laus SET name_national=N'Zuidplas', name_latin=N'Zuidplas', abac_name=N'Zuidplas', display_name=N'Zuidplas' WHERE id=77888;
UPDATE laus SET name_national=N'Zundert', name_latin=N'Zundert', abac_name=N'Zundert', display_name=N'Zundert' WHERE id=77802;
UPDATE laus SET name_national=N'Zutphen', name_latin=N'Zutphen', abac_name=N'Zutphen', display_name=N'Zutphen' WHERE id=77625;
UPDATE laus SET name_national=N'Zwartewaterland', name_latin=N'Zwartewaterland', abac_name=N'Zwartewaterland', display_name=N'Zwartewaterland' WHERE id=77891;
UPDATE laus SET name_national=N'Zwijndrecht', name_latin=N'Zwijndrecht', abac_name=N'Zwijndrecht', display_name=N'Zwijndrecht' WHERE id=77738;
UPDATE laus SET name_national=N'Zwolle', name_latin=N'Zwolle', abac_name=N'Zwolle', display_name=N'Zwolle' WHERE id=77585;

-- Laus || nuts may not exist for the following so they are commented
--SQL (names + lau1)
UPDATE laus SET lau1='GM1948', name_national=N'Meierijstad', name_latin=N'Meierijstad', abac_name=N'Meierijstad', display_name=N'Meierijstad' WHERE id=88455;
UPDATE laus SET lau1='GM1950', name_national=N'Westerwolde', name_latin=N'Westerwolde', abac_name=N'Westerwolde', display_name=N'Westerwolde' WHERE id=88456;

--MISSING NUTS
insert into nuts (code, label, level, country_code, _order, sorting) values ('NL124', 'Noord-Friesland', 3, 'NL', 19, (select top 1 sorting +1 from nuts order by sorting desc))

--SQL (names + lau1 + nuts3)
UPDATE laus SET nuts3='NL113', lau1='GM1952', name_national=N'Midden-Groningen', name_latin=N'Midden-Groningen', abac_name=N'Midden-Groningen', display_name=N'Midden-Groningen' WHERE id=88457;
UPDATE laus SET nuts3='NL124', lau1='GM1949', name_national=N'Waadhoeke', name_latin=N'Waadhoeke', abac_name=N'Waadhoeke', display_name=N'Waadhoeke' WHERE id=88458;
--381

--select nuts3, lau1, name_national, name_latin, abac_name, display_name, id 
--from laus where country_code = 'NL' order by name1 asc