  update [dbo].[laus] set abac_name = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
  abac_name collate Latin1_General_CS_AS, N'ó' collate Latin1_General_CS_AS, N'o' collate Latin1_General_CS_AS)
  , N'ò' collate Latin1_General_CS_AS, N'o' collate Latin1_General_CS_AS)
  , N'ö' collate Latin1_General_CS_AS, N'o' collate Latin1_General_CS_AS)
  , N'ð' collate Latin1_General_CS_AS, N'o' collate Latin1_General_CS_AS)
  , N'ô' collate Latin1_General_CS_AS, N'o' collate Latin1_General_CS_AS)
  , N'õ' collate Latin1_General_CS_AS, N'o' collate Latin1_General_CS_AS)
  , N'ø' collate Latin1_General_CS_AS, N'o' collate Latin1_General_CS_AS)
  , N'ő' collate Latin1_General_CS_AS, N'o' collate Latin1_General_CS_AS)

  , N'Ò' collate Latin1_General_CS_AS, N'O' collate Latin1_General_CS_AS)
  , N'Ó' collate Latin1_General_CS_AS, N'O' collate Latin1_General_CS_AS)
  , N'Ö' collate Latin1_General_CS_AS, N'O' collate Latin1_General_CS_AS)
  , N'Ô' collate Latin1_General_CS_AS, N'O' collate Latin1_General_CS_AS)
  , N'Õ' collate Latin1_General_CS_AS, N'O' collate Latin1_General_CS_AS)
  , N'Ø' collate Latin1_General_CS_AS, N'O' collate Latin1_General_CS_AS)
  , N'Ő' collate Latin1_General_CS_AS, N'O' collate Latin1_General_CS_AS)

  , N'ñ' collate Latin1_General_CS_AS, N'n' collate Latin1_General_CS_AS)
  , N'ń' collate Latin1_General_CS_AS, N'n' collate Latin1_General_CS_AS)
  , N'ň' collate Latin1_General_CS_AS, N'n' collate Latin1_General_CS_AS)
  , N'ņ' collate Latin1_General_CS_AS, N'n' collate Latin1_General_CS_AS)

  , N'Ñ' collate Latin1_General_CS_AS, N'N' collate Latin1_General_CS_AS)
  , N'Ń' collate Latin1_General_CS_AS, N'N' collate Latin1_General_CS_AS)
  , N'Ň' collate Latin1_General_CS_AS, N'N' collate Latin1_General_CS_AS)
  , N'Ņ' collate Latin1_General_CS_AS, N'N' collate Latin1_General_CS_AS)

  , N'è' collate Latin1_General_CS_AS, N'e' collate Latin1_General_CS_AS)
  , N'é' collate Latin1_General_CS_AS, N'e' collate Latin1_General_CS_AS)
  , N'ê' collate Latin1_General_CS_AS, N'e' collate Latin1_General_CS_AS)
  , N'ë' collate Latin1_General_CS_AS, N'e' collate Latin1_General_CS_AS)
  , N'ę' collate Latin1_General_CS_AS, N'e' collate Latin1_General_CS_AS)
  , N'ė' collate Latin1_General_CS_AS, N'e' collate Latin1_General_CS_AS)
  , N'ě' collate Latin1_General_CS_AS, N'e' collate Latin1_General_CS_AS)
  , N'ē' collate Latin1_General_CS_AS, N'e' collate Latin1_General_CS_AS)

  , N'È' collate Latin1_General_CS_AS, N'E' collate Latin1_General_CS_AS)
  , N'É' collate Latin1_General_CS_AS, N'E' collate Latin1_General_CS_AS)
  , N'Ê' collate Latin1_General_CS_AS, N'E' collate Latin1_General_CS_AS)
  , N'Ë' collate Latin1_General_CS_AS, N'E' collate Latin1_General_CS_AS)
  , N'Ę' collate Latin1_General_CS_AS, N'E' collate Latin1_General_CS_AS)
  , N'Ė' collate Latin1_General_CS_AS, N'E' collate Latin1_General_CS_AS)
  , N'Ě' collate Latin1_General_CS_AS, N'E' collate Latin1_General_CS_AS)
  , N'Ē' collate Latin1_General_CS_AS, N'E' collate Latin1_General_CS_AS)

  , N'á' collate Latin1_General_CS_AS, N'a' collate Latin1_General_CS_AS)
  , N'ã' collate Latin1_General_CS_AS, N'a' collate Latin1_General_CS_AS)
  , N'â' collate Latin1_General_CS_AS, N'a' collate Latin1_General_CS_AS)
  , N'à' collate Latin1_General_CS_AS, N'a' collate Latin1_General_CS_AS)
  , N'ä' collate Latin1_General_CS_AS, N'a' collate Latin1_General_CS_AS)
  , N'å' collate Latin1_General_CS_AS, N'a' collate Latin1_General_CS_AS)
  , N'æ' collate Latin1_General_CS_AS, N'ae' collate Latin1_General_CS_AS)
  , N'ą' collate Latin1_General_CS_AS, N'a' collate Latin1_General_CS_AS)
  , N'ă' collate Latin1_General_CS_AS, N'a' collate Latin1_General_CS_AS)
  , N'ā' collate Latin1_General_CS_AS, N'a' collate Latin1_General_CS_AS)

  , N'À' collate Latin1_General_CS_AS, N'A' collate Latin1_General_CS_AS)
  , N'Á' collate Latin1_General_CS_AS, N'A' collate Latin1_General_CS_AS)
  , N'Â' collate Latin1_General_CS_AS, N'A' collate Latin1_General_CS_AS)
  , N'Ã' collate Latin1_General_CS_AS, N'A' collate Latin1_General_CS_AS)
  , N'Å' collate Latin1_General_CS_AS, N'A' collate Latin1_General_CS_AS)
  , N'Ä' collate Latin1_General_CS_AS, N'A' collate Latin1_General_CS_AS)
  , N'Æ' collate Latin1_General_CS_AS, N'AE' collate Latin1_General_CS_AS)
  , N'Ą' collate Latin1_General_CS_AS, N'A' collate Latin1_General_CS_AS)
  , N'Ă' collate Latin1_General_CS_AS, N'A' collate Latin1_General_CS_AS)
  , N'Ā' collate Latin1_General_CS_AS, N'A' collate Latin1_General_CS_AS)

  , N'ù' collate Latin1_General_CS_AS, N'u' collate Latin1_General_CS_AS)
  , N'ú' collate Latin1_General_CS_AS, N'u' collate Latin1_General_CS_AS)
  , N'û' collate Latin1_General_CS_AS, N'u' collate Latin1_General_CS_AS)
  , N'ü' collate Latin1_General_CS_AS, N'u' collate Latin1_General_CS_AS)
  , N'µ' collate Latin1_General_CS_AS, N'u' collate Latin1_General_CS_AS)
  , N'ų' collate Latin1_General_CS_AS, N'u' collate Latin1_General_CS_AS)
  , N'ū' collate Latin1_General_CS_AS, N'u' collate Latin1_General_CS_AS)
  , N'ů' collate Latin1_General_CS_AS, N'u' collate Latin1_General_CS_AS)
  , N'ű' collate Latin1_General_CS_AS, N'u' collate Latin1_General_CS_AS)

  , N'Ù' collate Latin1_General_CS_AS, N'U' collate Latin1_General_CS_AS)
  , N'Ú' collate Latin1_General_CS_AS, N'U' collate Latin1_General_CS_AS)
  , N'Û' collate Latin1_General_CS_AS, N'U' collate Latin1_General_CS_AS)
  , N'Ü' collate Latin1_General_CS_AS, N'U' collate Latin1_General_CS_AS)
  , N'Ų' collate Latin1_General_CS_AS, N'U' collate Latin1_General_CS_AS)
  , N'Ū' collate Latin1_General_CS_AS, N'U' collate Latin1_General_CS_AS)
  , N'Ů' collate Latin1_General_CS_AS, N'U' collate Latin1_General_CS_AS)
  , N'Ű' collate Latin1_General_CS_AS, N'U' collate Latin1_General_CS_AS)

  , N'Ý' collate Latin1_General_CS_AS, N'Y' collate Latin1_General_CS_AS)
  , N'Ÿ' collate Latin1_General_CS_AS, N'Y' collate Latin1_General_CS_AS)

  , N'ÿ' collate Latin1_General_CS_AS, N'y' collate Latin1_General_CS_AS)
  , N'ý' collate Latin1_General_CS_AS, N'y' collate Latin1_General_CS_AS)

  , N'ç' collate Latin1_General_CS_AS, N'c' collate Latin1_General_CS_AS)
  , N'œ' collate Latin1_General_CS_AS, N'oe' collate Latin1_General_CS_AS)
  , N'č' collate Latin1_General_CS_AS, N'c' collate Latin1_General_CS_AS)
  , N'ć' collate Latin1_General_CS_AS, N'c' collate Latin1_General_CS_AS)
  , N'ċ' collate Latin1_General_CS_AS, N'c' collate Latin1_General_CS_AS)

  , N'Ç' collate Latin1_General_CS_AS, N'C' collate Latin1_General_CS_AS)
  , N'Œ' collate Latin1_General_CS_AS, N'OE' collate Latin1_General_CS_AS)
  , N'Č' collate Latin1_General_CS_AS, N'C' collate Latin1_General_CS_AS)
  , N'Ć' collate Latin1_General_CS_AS, N'C' collate Latin1_General_CS_AS)
  , N'Ċ' collate Latin1_General_CS_AS, N'C' collate Latin1_General_CS_AS)

  , N'ì' collate Latin1_General_CS_AS, N'i' collate Latin1_General_CS_AS)
  , N'í' collate Latin1_General_CS_AS, N'i' collate Latin1_General_CS_AS)
  , N'î' collate Latin1_General_CS_AS, N'i' collate Latin1_General_CS_AS)
  , N'ï' collate Latin1_General_CS_AS, N'i' collate Latin1_General_CS_AS)
  , N'į' collate Latin1_General_CS_AS, N'i' collate Latin1_General_CS_AS)
  , N'ī' collate Latin1_General_CS_AS, N'i' collate Latin1_General_CS_AS)

  , N'Ì' collate Latin1_General_CS_AS, N'I' collate Latin1_General_CS_AS)
  , N'Í' collate Latin1_General_CS_AS, N'I' collate Latin1_General_CS_AS)
  , N'Î' collate Latin1_General_CS_AS, N'I' collate Latin1_General_CS_AS)
  , N'Ï' collate Latin1_General_CS_AS, N'I' collate Latin1_General_CS_AS)
  , N'Į' collate Latin1_General_CS_AS, N'I' collate Latin1_General_CS_AS)
  , N'Ī' collate Latin1_General_CS_AS, N'I' collate Latin1_General_CS_AS)

  , N'Đ' collate Latin1_General_CS_AS, N'D' collate Latin1_General_CS_AS)
  , N'Þ' collate Latin1_General_CS_AS, N'Th' collate Latin1_General_CS_AS)
  , N'Ď' collate Latin1_General_CS_AS, N'D' collate Latin1_General_CS_AS)
  , N'ď' collate Latin1_General_CS_AS, N'd' collate Latin1_General_CS_AS)
  , N'đ' collate Latin1_General_CS_AS, N'd' collate Latin1_General_CS_AS)
  , N'ß' collate Latin1_General_CS_AS, N'ss' collate Latin1_General_CS_AS)
  , N'Š' collate Latin1_General_CS_AS, N'S' collate Latin1_General_CS_AS)
  , N'š' collate Latin1_General_CS_AS, N's' collate Latin1_General_CS_AS)
  , N'Ś' collate Latin1_General_CS_AS, N'S' collate Latin1_General_CS_AS)
  , N'ś' collate Latin1_General_CS_AS, N's' collate Latin1_General_CS_AS)
  , N'Ş' collate Latin1_General_CS_AS, N'S' collate Latin1_General_CS_AS)
  , N'ş' collate Latin1_General_CS_AS, N's' collate Latin1_General_CS_AS)
  , N'β' collate Latin1_General_CS_AS, N'b' collate Latin1_General_CS_AS)
  , N'ł' collate Latin1_General_CS_AS, N'l' collate Latin1_General_CS_AS)
  , N'ļ' collate Latin1_General_CS_AS, N'l' collate Latin1_General_CS_AS)
  , N'Ł' collate Latin1_General_CS_AS, N'L' collate Latin1_General_CS_AS)
  , N'ľ' collate Latin1_General_CS_AS, N'l' collate Latin1_General_CS_AS)
  , N'Ľ' collate Latin1_General_CS_AS, N'L' collate Latin1_General_CS_AS)
  , N'Ž' collate Latin1_General_CS_AS, N'Z' collate Latin1_General_CS_AS)
  , N'ž' collate Latin1_General_CS_AS, N'z' collate Latin1_General_CS_AS)
  , N'Ż' collate Latin1_General_CS_AS, N'Z' collate Latin1_General_CS_AS)
  , N'ż' collate Latin1_General_CS_AS, N'z' collate Latin1_General_CS_AS)
  , N'Ź' collate Latin1_General_CS_AS, N'Z' collate Latin1_General_CS_AS)
  , N'ź' collate Latin1_General_CS_AS, N'z' collate Latin1_General_CS_AS)
  , N'Ţ' collate Latin1_General_CS_AS, N'T' collate Latin1_General_CS_AS)
  , N'ţ' collate Latin1_General_CS_AS, N't' collate Latin1_General_CS_AS)
  , N'Ť' collate Latin1_General_CS_AS, N'T' collate Latin1_General_CS_AS)
  , N'ť' collate Latin1_General_CS_AS, N't' collate Latin1_General_CS_AS)
  , N'Ý' collate Latin1_General_CS_AS, N'Y' collate Latin1_General_CS_AS)
  , N'ý' collate Latin1_General_CS_AS, N'y' collate Latin1_General_CS_AS)
  , N'Ř' collate Latin1_General_CS_AS, N'R' collate Latin1_General_CS_AS)
  , N'ř' collate Latin1_General_CS_AS, N'r' collate Latin1_General_CS_AS)
  , N'ŕ' collate Latin1_General_CS_AS, N'r' collate Latin1_General_CS_AS)
  , N'Ħ' collate Latin1_General_CS_AS, N'H' collate Latin1_General_CS_AS)
  , N'ħ' collate Latin1_General_CS_AS, N'h' collate Latin1_General_CS_AS)
  , N'Ġ' collate Latin1_General_CS_AS, N'G' collate Latin1_General_CS_AS)
  , N'ġ' collate Latin1_General_CS_AS, N'g' collate Latin1_General_CS_AS)
  , N'þ' collate Latin1_General_CS_AS, N'th' collate Latin1_General_CS_AS)
  , N'ķ' collate Latin1_General_CS_AS, N'k' collate Latin1_General_CS_AS)
  , N'Ķ' collate Latin1_General_CS_AS, N'K' collate Latin1_General_CS_AS)
  , N'_' collate Latin1_General_CS_AS, N'-' collate Latin1_General_CS_AS)