REM INSERTING into WIF_CONSTANTS
SET DEFINE OFF;
Insert into WIF_CONSTANTS (ID,NAME,VALUE) values (21,'LEF_V_LOC_DOC_SCAN_TABLE_ALIAS','SCANNED DOCUMENT');
Insert into WIF_CONSTANTS (ID,NAME,VALUE) values (1,'ABAC_SYS_CD','WIF');
Insert into WIF_CONSTANTS (ID,NAME,VALUE) values (2,'LEF_V_LOC_DEST','ABACBUDT');
Insert into WIF_CONSTANTS (ID,NAME,VALUE) values (3,'LEF_V_LOC_TRANS_AREA_CD','THP');
Insert into WIF_CONSTANTS (ID,NAME,VALUE) values (4,'LEF_V_LOC_TRANS_TP_CD','THP');
Insert into WIF_CONSTANTS (ID,NAME,VALUE) values (5,'LEF_V_LOC_TRANS_ACTION_CD','CREATE');
Insert into WIF_CONSTANTS (ID,NAME,VALUE) values (6,'LEF_V_LOC_TABLE_ALIAS','LEGAL ENTITY');
Insert into WIF_CONSTANTS (ID,NAME,VALUE) values (7,'LEF_V_LOC_DEBTOR_CAT_ID','3');
Insert into WIF_CONSTANTS (ID,NAME,VALUE) values (8,'LEF_V_LOC_LEGAL_TYPE_CD','PULB');
Insert into WIF_CONSTANTS (ID,NAME,VALUE) values (9,'LEF_V_LOC_RESP_ORG_STRUCT_KEY_CD','\\EU\CE\INEA');
Insert into WIF_CONSTANTS (ID,NAME,VALUE) values (10,'LEF_V_LOC_RESP_ORG_STRUCT_TP_CD','EGY');
Insert into WIF_CONSTANTS (ID,NAME,VALUE) values (11,'LEF_V_LOC_DOC_TABLE_ALIAS','DOCUMENT REFERENCE');
Insert into WIF_CONSTANTS (ID,NAME,VALUE) values (12,'LEF_V_LOC_VISA_TABLE_ALIAS','VISA');
Insert into WIF_CONSTANTS (ID,NAME,VALUE) values (13,'LEF_V_LOC_VISA_ACTION_CD','AC');
Insert into WIF_CONSTANTS (ID,NAME,VALUE) values (14,'LEF_V_LOC_VISA_SIGNATURE','PANAGIOTOPOULOS Alexander');
Insert into WIF_CONSTANTS (ID,NAME,VALUE) values (15,'LEF_V_LOC_VISA_DEFAULT_COMMENT','VISA GIVEN BY WIFI4EU');
Insert into WIF_CONSTANTS (ID,NAME,VALUE) values (16,'LEF_V_LOC_VISA_AGENT_ID','panaale');
Insert into WIF_CONSTANTS (ID,NAME,VALUE) values (17,'LEF_V_LOC_VISA_WRKFLW_CENTER_CD','WIFI4EU');
Insert into WIF_CONSTANTS (ID,NAME,VALUE) values (18,'LEF_V_LOC_VISA_WRKFLW_ORG_NAME','INEA');
Insert into WIF_CONSTANTS (ID,NAME,VALUE) values (19,'LEF_V_LOC_VISA_SIGN_AS_AGENT_TYPE','FIA');
Insert into WIF_CONSTANTS (ID,NAME,VALUE) values (20,'LEF_V_LOC_VISA_SUPPLIED_AGENT_NAME','panaale');


