-- -----------------------------------------------------
-- Table "WIFI4EU_ABAC"."WIF_DOCUMENTS"
-- -----------------------------------------------------
CREATE TABLE "WIFI4EU_ABAC"."WIF_DOCUMENTS" (
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"DATA" BFILE,
	"ARES_REFERENCE" VARCHAR2(50 BYTE),
	"ARES_DATE" VARCHAR2(20 BYTE),
	"SIZE" NUMBER(18,0) NOT NULL ENABLE,
	"MIMETYPE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"DATE_CREATED" VARCHAR2(20 BYTE) DEFAULT TO_CHAR(sysdate, 'MM/DD/YYYY HH:MM:SS') NOT NULL ENABLE,
	"DATE_UPDATED" VARCHAR2(20 BYTE),
	"WF_STATUS" VARCHAR2(20 BYTE) DEFAULT 'READY_FOR_ABAC' NOT NULL ENABLE,
	CONSTRAINT "WIF_DOCUMENTS_PK" PRIMARY KEY ("ID")
	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
	TABLESPACE "WIFI4EU_ABAC" ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING;
TABLESPACE "WIFI4EU_ABAC" ;

COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_DOCUMENTS"."ID" IS 'Incremental ID';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_DOCUMENTS"."DATA" IS 'Binary file content';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_DOCUMENTS"."ARES_REFERENCE" IS 'ARES document reference';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_DOCUMENTS"."ARES_DATE" IS 'ARES document date, format MM/DD/YYYY HH:MM:SS';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_DOCUMENTS"."DATE_CREATED" IS 'Creation date, format MM/DD/YYYY HH:MM:SS';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_DOCUMENTS"."DATE_UPDATED" IS 'Modification date, format MM/DD/YYYY HH:MM:SS';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_DOCUMENTS"."WF_STATUS" IS 'Workflow status';


-- -----------------------------------------------------
-- Table "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"
-- -----------------------------------------------------
CREATE TABLE "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY" (
    "ID" NUMBER(18,0) NOT NULL ENABLE,
    "MID" NUMBER(18,0) NOT NULL ENABLE,
    "OFFICIAL_NAME" VARCHAR2(400 BYTE) NOT NULL ENABLE,
    "REGION" VARCHAR2(400 BYTE),
    "LANGUAGE_CODE" VARCHAR2(3 BYTE),
    "COUNTRY_CODE" VARCHAR2(2 BYTE) NOT NULL ENABLE,
    "OFFICIAL_ADDRESS" VARCHAR2(400 BYTE) NOT NULL ENABLE,
    "OFFICIAL_ADDRESS_STR_NO" VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "POSTAL_CODE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "ABAC_FEL_ID" VARCHAR2(50 BYTE),
    "WF_STATUS" VARCHAR2(20 BYTE) DEFAULT 'IMPORTED' NOT NULL ENABLE,
    "DATE_CREATED" VARCHAR2(20 BYTE) DEFAULT SYSDATE NOT NULL ENABLE,
    CONSTRAINT "WIF_MUNICIPALITY_PK" PRIMARY KEY ("ID")
	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
	TABLESPACE "WIFI4EU_ABAC"  ENABLE
) SEGMENT CREATION DEFERRED
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "WIFI4EU_ABAC" ;
 
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."ID" IS 'AIRGAP incremental id';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."MID" IS 'MUNICIPALITY registration ID from Portal';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."OFFICIAL_NAME" IS 'Offical name of the municipality';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."REGION" IS 'Name of the region';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."LANGUAGE_CODE" IS 'Language ISO code';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."COUNTRY_CODE" IS 'Country ISO2 code';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."OFFICIAL_ADDRESS" IS 'The offical address of the municipality';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."OFFICIAL_ADDRESS_STR_NO" IS 'The street number';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."POSTAL_CODE" IS 'Postal code';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."ABAC_FEL_ID" IS 'A reference in format 6000XXXXXX with a reference validly pointing at a LEF in ABAC';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."WF_STATUS" IS 'Workflow status : IMPORTED, READY_FOR_ABAC, WAITING_FOR_ABAC, ABAC_FINISH, ABAC_ERROR';


-- -----------------------------------------------------
-- Table "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"
-- -----------------------------------------------------
CREATE TABLE "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT" (
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"ID_LE" NUMBER(18,0) NOT NULL ENABLE,
	"ABAC_ID" NUMBER(18,0),
	"WF_STATUS" VARCHAR2(20 BYTE) DEFAULT 'READY_FOR_ABAC' NOT NULL ENABLE,
	"USER_IMPORTED" VARCHAR2(20 BYTE),
	"DATE_CREATED" VARCHAR2(20 BYTE) DEFAULT TO_CHAR(sysdate, 'MM/DD/YYYY HH:MM:SS') NOT NULL ENABLE,
	"DATE_UPDATED" VARCHAR2(20 BYTE),
	"COUNTERSIGNATURE_DATE" VARCHAR2(20 BYTE),
	"ID_COUNTERSIGNATURE_FILE" NUMBER(18,0),
	"USER_COUNTERSIGNATURED" VARCHAR2(20 BYTE),
	"DATE_COUNTERSIGNATURED" VARCHAR2(20 BYTE),
	CONSTRAINT "WIF_LC_PK" PRIMARY KEY ("ID")
	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255,
	CONSTRAINT "WIF_LC_LE_FK" FOREIGN KEY ("ID_LE") REFERENCES "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"("ID"),
	CONSTRAINT "WIF_LC_DOC_FK" FOREIGN KEY ("ID_COUNTERSIGNATURE_FILE") REFERENCES "WIFI4EU_ABAC"."WIF_DOCUMENTS"("ID")	
) SEGMENT CREATION DEFERRED
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "WIFI4EU_ABAC" ;

COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"."ID" IS 'Incremental ID';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"."ID_LE" IS 'ID of the related LegalEntity';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"."ID_COUNTERSIGNATURE_FILE" IS 'ID of the related file with the countersignature';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"."COUNTERSIGNATURE_DATE" IS 'Date when the countersignature was applied, format MM/DD/YYYY HH:MM:SS';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"."USER_COUNTERSIGNATURED" IS 'Username who launched the countersignature';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"."DATE_COUNTERSIGNATURED" IS 'Date when was launched the countersignature, format MM/DD/YYYY HH:MM:SS';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"."DATE_CREATED" IS 'Creation date, format MM/DD/YYYY HH:MM:SS';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"."DATE_UPDATED" IS 'Modification date, format MM/DD/YYYY HH:MM:SS';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"."USER_IMPORTED" IS 'Username of the last user who exported it';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"."WF_STATUS" IS 'Workflow status';


-- -----------------------------------------------------
-- Table "WIFI4EU_ABAC"."WIF_BUDGETARY_COMMITMENT"
-- -----------------------------------------------------
CREATE TABLE "WIFI4EU_ABAC"."WIF_BUDGETARY_COMMITMENT" (
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"ID_LE" NUMBER(18,0) NOT NULL ENABLE,
	"ID_LC" NUMBER(18,0),
	"ABAC_ID" NUMBER(18,0),
	"WF_STATUS" VARCHAR2(20 BYTE) DEFAULT 'READY_FOR_ABAC' NOT NULL ENABLE,
	"USER_IMPORTED" VARCHAR2(20 BYTE),
	"DATE_CREATED" VARCHAR2(20 BYTE) DEFAULT TO_CHAR(sysdate, 'MM/DD/YYYY HH:MM:SS') NOT NULL ENABLE,
	"DATE_UPDATED" VARCHAR2(20 BYTE),
	CONSTRAINT "WIF_BC_PK" PRIMARY KEY ("ID")
	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255,
	CONSTRAINT "WIF_BC_LE_FK" FOREIGN KEY ("ID_LE") REFERENCES "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"("ID"),
	CONSTRAINT "WIF_BC_LC_FK" FOREIGN KEY ("ID_LC") REFERENCES "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"("ID")
) SEGMENT CREATION DEFERRED
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "WIFI4EU_ABAC" ;

COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BUDGETARY_COMMITMENT"."ID" IS 'Incremental ID';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BUDGETARY_COMMITMENT"."ID_LE" IS 'ID of the related LegalEntity';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BUDGETARY_COMMITMENT"."ID_LC" IS 'ID of the related LegalCommitment';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BUDGETARY_COMMITMENT"."DATE_CREATED" IS 'Creation date, format MM/DD/YYYY HH:MM:SS';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BUDGETARY_COMMITMENT"."DATE_UPDATED" IS 'Modification date, format MM/DD/YYYY HH:MM:SS';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BUDGETARY_COMMITMENT"."USER_IMPORTED" IS 'Username of the last user who exported it';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BUDGETARY_COMMITMENT"."WF_STATUS" IS 'Workflow status';


-- -----------------------------------------------------
-- Table "WIFI4EU_ABAC"."WIF_BANK_ACCOUNTS"
-- -----------------------------------------------------
CREATE TABLE "WIFI4EU_ABAC"."WIF_BANK_ACCOUNTS" (
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"ID_LE" NUMBER(18,0) NOT NULL ENABLE,
	"ABAC_ID" NUMBER(18,0),
	"WF_STATUS" VARCHAR2(20 BYTE) DEFAULT 'READY_FOR_ABAC' NOT NULL ENABLE,
	"ID_BANK_DOCUMENT" NUMBER(18,0) NOT NULL ENABLE,
	"ACCOUNT_NAME" VARCHAR2(70 BYTE),
	"IBAN" VARCHAR2(100 BYTE),
	"BANK_NAME" VARCHAR2(120 BYTE),
	"BANK_ADDRESS" VARCHAR2(120 BYTE),
	"BANK_CITY" VARCHAR2(50 BYTE),
	"BANK_COUNTRY_CODE" VARCHAR2(2 BYTE),
	"ACC_HOLDER_ADDRESS" VARCHAR2(120 BYTE),
	"ACC_HOLDER_CITY" VARCHAR2(50 BYTE),
	"ACC_HOLDER_COUNTRY_CODE" VARCHAR2(2 BYTE),
	CONSTRAINT "WIF_BA_PK" PRIMARY KEY ("ID")
	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255,
	CONSTRAINT "WIF_BA_LE_FK" FOREIGN KEY ("ID_LE") REFERENCES "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"("ID"),
	CONSTRAINT "WIF_BA_DOC_FK" FOREIGN KEY ("ID_BANK_DOCUMENT") REFERENCES "WIFI4EU_ABAC"."WIF_DOCUMENTS"("ID")
) SEGMENT CREATION DEFERRED
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "WIFI4EU_ABAC" ;

COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BANK_ACCOUNTS"."ID" IS 'Incremental ID';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BANK_ACCOUNTS"."ID_LE" IS 'ID of the related LegalEntity';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BANK_ACCOUNTS"."ID_BANK_DOCUMENT" IS 'ID of the related file with the bank statement';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BANK_ACCOUNTS"."WF_STATUS" IS 'Workflow status';


-- -----------------------------------------------------
-- Table "WIFI4EU_ABAC"."WIF_CALLS"
-- -----------------------------------------------------
CREATE TABLE "WIFI4EU_ABAC"."WIF_CALLS" (
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(50 BYTE),
	"START_DATE" VARCHAR2(20 BYTE),
	"END_DATE" VARCHAR2(20 BYTE),	
	"APPLICATION" VARCHAR2(50 BYTE),
	"COMMITMENT_CODE" VARCHAR2(50 BYTE),
	"AMOUNT" NUMBER(5,0),
	"AGENT_ID" VARCHAR2(20 BYTE),
	"AGENT_NAME" VARCHAR2(50 BYTE),
	CONSTRAINT "WIF_CALLS_PK" PRIMARY KEY ("ID")
	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
) SEGMENT CREATION DEFERRED
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "WIFI4EU_ABAC" ;

COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_CALLS"."ID" IS 'Incremental ID';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_CALLS"."COMMITMENT_CODE" IS 'ID of the Global Commitment to create the Budgetary Commitments L2';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_CALLS"."AGENT_ID" IS 'User ID of the responsible user for the objects creation in ABAC';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_CALLS"."AGENT_NAME" IS 'User name of the responsible user for the objects creation in ABAC';


-- -----------------------------------------------------
-- Table "WIFI4EU_ABAC"."WIF_ROLES"
-- -----------------------------------------------------
CREATE TABLE "WIFI4EU_ABAC"."WIF_ROLES" (
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"CODE" VARCHAR2(20 BYTE),
	"NAME" VARCHAR2(50 BYTE),
	CONSTRAINT "WIF_ROLES_PK" PRIMARY KEY ("ID")
	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
) SEGMENT CREATION DEFERRED
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "WIFI4EU_ABAC" ;


-- -----------------------------------------------------
-- Table "WIFI4EU_ABAC"."WIF_USERS"
-- -----------------------------------------------------
CREATE TABLE "WIFI4EU_ABAC"."WIF_USERS" (
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"USERNAME" VARCHAR2(20 BYTE),
	"NAME" VARCHAR2(50 BYTE),
	"EMAIL" VARCHAR2(50 BYTE),
	CONSTRAINT "WIF_USERS_PK" PRIMARY KEY ("ID")
	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
) SEGMENT CREATION DEFERRED
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "WIFI4EU_ABAC" ;


-- -----------------------------------------------------
-- Table "WIFI4EU_ABAC"."WIF_USER_ROLES"
-- -----------------------------------------------------
CREATE TABLE "WIFI4EU_ABAC"."WIF_USER_ROLES" (
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"USER_ID" NUMBER(18,0) NOT NULL ENABLE,
	"ROLE_ID" NUMBER(18,0) NOT NULL ENABLE,
	CONSTRAINT "WIF_UR_PK" PRIMARY KEY ("ID")
	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255,
	CONSTRAINT "WIF_UR_USERS_FK" FOREIGN KEY ("USER_ID") REFERENCES "WIFI4EU_ABAC"."WIF_USERS"("ID"),
	CONSTRAINT "WIF_UR_ROLES_FK" FOREIGN KEY ("ROLE_ID") REFERENCES "WIFI4EU_ABAC"."WIF_ROLES"("ID")	
) SEGMENT CREATION DEFERRED
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "WIFI4EU_ABAC" ;


-- -----------------------------------------------------
-- Table "WIFI4EU_ABAC"."WIF_REPORTS"
-- -----------------------------------------------------
CREATE TABLE "WIFI4EU_ABAC"."WIF_REPORTS" (
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"USER_ID" NUMBER(18,0) NOT NULL ENABLE,
	"TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"DATE_CREATED" VARCHAR2(20 BYTE) DEFAULT TO_CHAR(sysdate, 'MM/DD/YYYY HH:MM:SS') NOT NULL ENABLE,
	"LE_ID" NUMBER(18,0) NOT NULL ENABLE,
	"BC_ID" NUMBER(18,0) NOT NULL ENABLE,
	"LC_ID" NUMBER(18,0) NOT NULL ENABLE,
	CONSTRAINT "WIF_REP_PK" PRIMARY KEY ("ID")
	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255,
	CONSTRAINT "WIF_REP_USERS_FK" FOREIGN KEY ("USER_ID") REFERENCES "WIFI4EU_ABAC"."WIF_USERS"("ID"),
	CONSTRAINT "WIF_REP_LE_FK" FOREIGN KEY ("LE_ID") REFERENCES "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"("ID"),
	CONSTRAINT "WIF_REP_BC_FK" FOREIGN KEY ("BC_ID") REFERENCES "WIFI4EU_ABAC"."WIF_BUDGETARY_COMMITMENT"("ID"),
	CONSTRAINT "WIF_REP_LC_FK" FOREIGN KEY ("LC_ID") REFERENCES "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"("ID")	
) SEGMENT CREATION DEFERRED
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "WIFI4EU_ABAC" ;

COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_REPORTS"."ID" IS 'Incremental ID';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_REPORTS"."USER_ID" IS 'ID of the user that requested the export';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_REPORTS"."TYPE" IS 'Type of export requested: LE, BC or LC';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_REPORTS"."LE_ID" IS 'ID of the related LegalEntity';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_REPORTS"."BC_ID" IS 'ID of the related BudgetaryCommitment';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_REPORTS"."LC_ID" IS 'ID of the related LegalCommitment';






