--------------------------------------------------------
--  DDL for DB Link ABACBUDT_SHARED.CC.CEC.EU.INT
--------------------------------------------------------

  CREATE SHARED DATABASE LINK "ABACBUDT_SHARED.CC.CEC.EU.INT"
   CONNECT TO "WIFI4EU$" IDENTIFIED BY VALUES ':1'
   AUTHENTICATED BY "WIFI4EU$" IDENTIFIED BY VALUES ':2'
   USING 'ABACBUDT';


--------------------------------------------------------
--  DDL for Table WIF_CONSTANTS
--------------------------------------------------------

  CREATE TABLE "WIFI4EU_ABAC"."WIF_CONSTANTS"
   (	"ID" NUMBER(18,0),
	"NAME" VARCHAR2(200 BYTE),
	"VALUE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WIFI4EU_ABAC" ;
--------------------------------------------------------
--  DDL for Index WIF_CONSTANTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WIFI4EU_ABAC"."WIF_CONSTANTS_PK" ON "WIFI4EU_ABAC"."WIF_CONSTANTS" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WIFI4EU_ABAC" ;
--------------------------------------------------------
--  Constraints for Table WIF_CONSTANTS
--------------------------------------------------------

  ALTER TABLE "WIFI4EU_ABAC"."WIF_CONSTANTS" ADD CONSTRAINT "WIF_CONSTANTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WIFI4EU_ABAC"  ENABLE;
  ALTER TABLE "WIFI4EU_ABAC"."WIF_CONSTANTS" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "WIFI4EU_ABAC"."WIF_CONSTANTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "WIFI4EU_ABAC"."WIF_CONSTANTS" MODIFY ("ID" NOT NULL ENABLE);


-- -----------------------------------------------------
-- Table "WIFI4EU_ABAC"."WIF_DOCUMENTS"
-- -----------------------------------------------------
CREATE TABLE "WIFI4EU_ABAC"."WIF_DOCUMENTS" (
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"DATA" BFILE,
	"ARES_REFERENCE" VARCHAR2(50 BYTE),
	"ARES_DATE" VARCHAR2(20 BYTE),
	"SIZE" NUMBER(18,0) NOT NULL ENABLE,
	"MIMETYPE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"DATE_CREATED" VARCHAR2(20 BYTE) DEFAULT TO_CHAR(sysdate, 'MM/DD/YYYY HH:MM:SS') NOT NULL ENABLE,
	"DATE_UPDATED" VARCHAR2(20 BYTE),
	"WF_STATUS" VARCHAR2(20 BYTE) DEFAULT 'READY_FOR_ABAC' NOT NULL ENABLE,
	CONSTRAINT "WIF_DOCUMENTS_PK" PRIMARY KEY ("ID")
	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
	TABLESPACE "WIFI4EU_ABAC" ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "WIFI4EU_ABAC" ;

COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_DOCUMENTS"."ID" IS 'Incremental ID';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_DOCUMENTS"."DATA" IS 'Binary file content';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_DOCUMENTS"."ARES_REFERENCE" IS 'ARES document reference';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_DOCUMENTS"."ARES_DATE" IS 'ARES document date, format MM/DD/YYYY HH:MM:SS';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_DOCUMENTS"."DATE_CREATED" IS 'Creation date, format MM/DD/YYYY HH:MM:SS';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_DOCUMENTS"."DATE_UPDATED" IS 'Modification date, format MM/DD/YYYY HH:MM:SS';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_DOCUMENTS"."WF_STATUS" IS 'Workflow status';


--------------------------------------------------------
--  DDL for Table WIF_LEGAL_ENTITY
--------------------------------------------------------

  CREATE TABLE "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"
   (	"ID" NUMBER(18,0),
	"MID" NUMBER(18,0),
	"OFFICIAL_NAME" VARCHAR2(400 BYTE),
	"LANGUAGE_CODE" VARCHAR2(3 BYTE),
	"COUNTRY_CODE" VARCHAR2(2 BYTE),
	"OFFICIAL_ADDRESS" VARCHAR2(400 BYTE),
	"POSTAL_CODE" VARCHAR2(50 BYTE),
	"CITY" VARCHAR2(400 BYTE),
	"REGISTRATION_NUMBER" NUMBER(18,0),
	"ABAC_FEL_ID" VARCHAR2(50 BYTE),
	"WF_STATUS" VARCHAR2(20 BYTE) DEFAULT 'IMPORTED',
	"DATE_CREATED" DATE DEFAULT SYSDATE,
	"DATE_UPDATED" DATE,
	"SIGNATURE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WIFI4EU_ABAC" ;

   COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."ID" IS 'AIGAP incremental id';
   COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."MID" IS 'MUNICIPALITY registration ID from Portal';
   COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."OFFICIAL_NAME" IS 'Offical name of the municipality';
   COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."LANGUAGE_CODE" IS 'Language ISO code';
   COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."COUNTRY_CODE" IS 'Country ISO2 code';
   COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."OFFICIAL_ADDRESS" IS 'The offical address of the municipality';
   COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."POSTAL_CODE" IS 'Postal code';
   COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."ABAC_FEL_ID" IS 'A reference in format 6000XXXXXX with a reference validly pointing at a LEF in ABAC';
   COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."WF_STATUS" IS 'Workflow status : IMPORTED, READY_FOR_ABAC, WAITING_FOR_ABAC, ABAC_FINISH, ABAC_ERROR';
   COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."DATE_CREATED" IS 'Date when the entry was created in the system';
   COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."CITY" IS 'Name of the city';
--------------------------------------------------------
--  DDL for Index WIF_MUNICIPALITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WIFI4EU_ABAC"."WIF_MUNICIPALITY_PK" ON "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WIFI4EU_ABAC" ;
--------------------------------------------------------
--  DDL for Index WIF_LEGAL_ENTITY_MID_UNQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY_MID_UNQ" ON "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY" ("OFFICIAL_NAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WIFI4EU_ABAC" ;
--------------------------------------------------------
--  Constraints for Table WIF_LEGAL_ENTITY
--------------------------------------------------------

  ALTER TABLE "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY" ADD CONSTRAINT "WIF_LEGAL_ENTITY_MID_UNQ" UNIQUE ("OFFICIAL_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WIFI4EU_ABAC"  ENABLE;
  ALTER TABLE "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY" ADD CONSTRAINT "WIF_MUNICIPALITY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WIFI4EU_ABAC"  ENABLE;
  ALTER TABLE "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY" MODIFY ("DATE_CREATED" NOT NULL ENABLE);
  ALTER TABLE "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY" MODIFY ("WF_STATUS" NOT NULL ENABLE);
  ALTER TABLE "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY" MODIFY ("POSTAL_CODE" NOT NULL ENABLE);
  ALTER TABLE "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY" MODIFY ("OFFICIAL_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY" MODIFY ("COUNTRY_CODE" NOT NULL ENABLE);
  ALTER TABLE "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY" MODIFY ("OFFICIAL_NAME" NOT NULL ENABLE);
  ALTER TABLE "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY" MODIFY ("MID" NOT NULL ENABLE);
  ALTER TABLE "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY" MODIFY ("ID" NOT NULL ENABLE);


--------------------------------------------------------
--  DDL for Table WIF_ABAC_REQUEST_PROCESS
--------------------------------------------------------

  CREATE TABLE "WIFI4EU_ABAC"."WIF_ABAC_REQUEST_PROCESS"
   (	"ID" NUMBER(18,0),
	"LE_ID" NUMBER(18,0),
	"L_RUN_ID" NUMBER(10,0),
	"L_LOC_SYS_CD" VARCHAR2(3 BYTE),
	"L_LOC_OBJ_FK" VARCHAR2(56 BYTE),
	"L_QUE_ID" NUMBER(18,0),
	"SUBMIT_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WIFI4EU_ABAC" ;

   COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_ABAC_REQUEST_PROCESS"."LE_ID" IS ' Municipality ID in AIRGAP';
   COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_ABAC_REQUEST_PROCESS"."L_RUN_ID" IS 'This is created by the application and is a unique identifier for the batch process.';
   COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_ABAC_REQUEST_PROCESS"."L_LOC_SYS_CD" IS 'This is a constant that identifies the application in ABAC ("WIF").';
   COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_ABAC_REQUEST_PROCESS"."L_LOC_OBJ_FK" IS 'This is created by the application and is a unique identifier for the LE. The format should be "WIF.XXXXXX" where XXXXXX is the id in the application.';
--------------------------------------------------------
--  DDL for Index WIF_ABAC_BATCH_STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WIFI4EU_ABAC"."WIF_ABAC_BATCH_STATUS_PK" ON "WIFI4EU_ABAC"."WIF_ABAC_REQUEST_PROCESS" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WIFI4EU_ABAC" ;
--------------------------------------------------------
--  Constraints for Table WIF_ABAC_REQUEST_PROCESS
--------------------------------------------------------

  ALTER TABLE "WIFI4EU_ABAC"."WIF_ABAC_REQUEST_PROCESS" MODIFY ("SUBMIT_DATE" NOT NULL ENABLE);
  ALTER TABLE "WIFI4EU_ABAC"."WIF_ABAC_REQUEST_PROCESS" ADD CONSTRAINT "WIF_ABAC_BATCH_STATUS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WIFI4EU_ABAC"  ENABLE;
  ALTER TABLE "WIFI4EU_ABAC"."WIF_ABAC_REQUEST_PROCESS" MODIFY ("L_LOC_OBJ_FK" NOT NULL ENABLE);
  ALTER TABLE "WIFI4EU_ABAC"."WIF_ABAC_REQUEST_PROCESS" MODIFY ("L_LOC_SYS_CD" NOT NULL ENABLE);
  ALTER TABLE "WIFI4EU_ABAC"."WIF_ABAC_REQUEST_PROCESS" MODIFY ("L_RUN_ID" NOT NULL ENABLE);
  ALTER TABLE "WIFI4EU_ABAC"."WIF_ABAC_REQUEST_PROCESS" MODIFY ("LE_ID" NOT NULL ENABLE);
  ALTER TABLE "WIFI4EU_ABAC"."WIF_ABAC_REQUEST_PROCESS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table WIF_ABAC_REQUEST_PROCESS
--------------------------------------------------------

  ALTER TABLE "WIFI4EU_ABAC"."WIF_ABAC_REQUEST_PROCESS" ADD CONSTRAINT "WIF_ABAC_BATCH_LE_ID_FK" FOREIGN KEY ("LE_ID")
	  REFERENCES "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY" ("ID") ENABLE;


--------------------------------------------------------
--  DDL for View WIF_ABAC_LEF_STATUS_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "WIFI4EU_ABAC"."WIF_ABAC_LEF_STATUS_VIEW" ("LOC_OBJ_FOREIGN_ID", "STATUS", "LE_KEY", "ERROR_MESSAGE") AS
  select
le.LOC_OBJ_FOREIGN_ID,
case
  when le.PROCESSED = 'N'
  then 'WAITING_FOR_ABAC'

  when le.PROCESSED = 'OK' and lekey.head_loc_obj_foreign_id is null
  then 'WAITING_APPROVAL'

  when le.PROCESSED = 'OK' and lekey.head_loc_obj_foreign_id is not null
  then 'ABAC_FINISH'

  when le.PROCESSED = 'NOK'
  then 'ABAC_ERROR'
end  as status,
lekey.head_loc_obj_foreign_id as LE_KEY,
err.msg_txt as ERROR_MESSAGE
FROM V_LOC_THP_LEGAL_ENTITIES@ABACBUDT_SHARED le
LEFT JOIN V_O_LOG_ERRORS@ABACBUDT_SHARED err ON err.batch_id = le.run_id and err.loc_sys_cd = le.loc_sys_cd and err.msg_tp_cd <> 'I'
LEFT JOIN V_O_THP_COMMON_LOCAL_LINKS@ABACBUDT_SHARED lekey ON lekey.loc_obj_foreign_id = le.loc_obj_foreign_id
where le.LOC_OBJ_FOREIGN_ID like 'WIF%';


-- -----------------------------------------------------
-- Table "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"
-- -----------------------------------------------------
CREATE TABLE "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT" (
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"ID_LE" NUMBER(18,0) NOT NULL ENABLE,
	"ABAC_ID" NUMBER(18,0),
	"WF_STATUS" VARCHAR2(20 BYTE) DEFAULT 'READY_FOR_ABAC' NOT NULL ENABLE,
	"USER_IMPORTED" VARCHAR2(20 BYTE),
	"DATE_CREATED" VARCHAR2(20 BYTE) DEFAULT TO_CHAR(sysdate, 'MM/DD/YYYY HH:MM:SS') NOT NULL ENABLE,
	"DATE_UPDATED" VARCHAR2(20 BYTE),
	"COUNTERSIGNATURE_DATE" VARCHAR2(20 BYTE),
	"ID_COUNTERSIGNATURE_FILE" NUMBER(18,0),
	"USER_COUNTERSIGNATURED" VARCHAR2(20 BYTE),
	"DATE_COUNTERSIGNATURED" VARCHAR2(20 BYTE),
	CONSTRAINT "WIF_LC_PK" PRIMARY KEY ("ID")
	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255,
	CONSTRAINT "WIF_LC_LE_FK" FOREIGN KEY ("ID_LE") REFERENCES "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"("ID"),
	CONSTRAINT "WIF_LC_DOC_FK" FOREIGN KEY ("ID_COUNTERSIGNATURE_FILE") REFERENCES "WIFI4EU_ABAC"."WIF_DOCUMENTS"("ID")	
)  SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "WIFI4EU_ABAC" ;

COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"."ID" IS 'Incremental ID';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"."ID_LE" IS 'ID of the related LegalEntity';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"."ID_COUNTERSIGNATURE_FILE" IS 'ID of the related file with the countersignature';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"."COUNTERSIGNATURE_DATE" IS 'Date when the countersignature was applied, format MM/DD/YYYY HH:MM:SS';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"."USER_COUNTERSIGNATURED" IS 'Username who launched the countersignature';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"."DATE_COUNTERSIGNATURED" IS 'Date when was launched the countersignature, format MM/DD/YYYY HH:MM:SS';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"."DATE_CREATED" IS 'Creation date, format MM/DD/YYYY HH:MM:SS';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"."DATE_UPDATED" IS 'Modification date, format MM/DD/YYYY HH:MM:SS';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"."USER_IMPORTED" IS 'Username of the last user who exported it';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"."WF_STATUS" IS 'Workflow status';


-- -----------------------------------------------------
-- Table "WIFI4EU_ABAC"."WIF_BUDGETARY_COMMITMENT"
-- -----------------------------------------------------
CREATE TABLE "WIFI4EU_ABAC"."WIF_BUDGETARY_COMMITMENT" (
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"ID_LE" NUMBER(18,0) NOT NULL ENABLE,
	"ID_LC" NUMBER(18,0),
	"ABAC_ID" NUMBER(18,0),
	"WF_STATUS" VARCHAR2(20 BYTE) DEFAULT 'READY_FOR_ABAC' NOT NULL ENABLE,
	"USER_IMPORTED" VARCHAR2(20 BYTE),
	"DATE_CREATED" VARCHAR2(20 BYTE) DEFAULT TO_CHAR(sysdate, 'MM/DD/YYYY HH:MM:SS') NOT NULL ENABLE,
	"DATE_UPDATED" VARCHAR2(20 BYTE),
	"COMMITMENT_CODE" VARCHAR2(50 BYTE),	
	CONSTRAINT "WIF_BC_PK" PRIMARY KEY ("ID")
	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255,
	CONSTRAINT "WIF_BC_LE_FK" FOREIGN KEY ("ID_LE") REFERENCES "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"("ID"),
	CONSTRAINT "WIF_BC_LC_FK" FOREIGN KEY ("ID_LC") REFERENCES "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"("ID")
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "WIFI4EU_ABAC" ;

COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BUDGETARY_COMMITMENT"."ID" IS 'Incremental ID';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BUDGETARY_COMMITMENT"."ID_LE" IS 'ID of the related LegalEntity';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BUDGETARY_COMMITMENT"."ID_LC" IS 'ID of the related LegalCommitment';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BUDGETARY_COMMITMENT"."DATE_CREATED" IS 'Creation date, format MM/DD/YYYY HH:MM:SS';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BUDGETARY_COMMITMENT"."DATE_UPDATED" IS 'Modification date, format MM/DD/YYYY HH:MM:SS';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BUDGETARY_COMMITMENT"."USER_IMPORTED" IS 'Username of the last user who exported it';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BUDGETARY_COMMITMENT"."WF_STATUS" IS 'Workflow status';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BUDGETARY_COMMITMENT"."COMMITMENT_CODE" IS 'ID of the Global Commitment to create the Budgetary Commitments L2';


-- -----------------------------------------------------
-- Table "WIFI4EU_ABAC"."WIF_BANK_ACCOUNTS"
-- -----------------------------------------------------
CREATE TABLE "WIFI4EU_ABAC"."WIF_BANK_ACCOUNTS" (
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"ID_LE" NUMBER(18,0) NOT NULL ENABLE,
	"ABAC_ID" NUMBER(18,0),
	"WF_STATUS" VARCHAR2(20 BYTE) DEFAULT 'READY_FOR_ABAC' NOT NULL ENABLE,
	"ID_BANK_DOCUMENT" NUMBER(18,0) NOT NULL ENABLE,
	"ACCOUNT_NAME" VARCHAR2(70 BYTE),
	"IBAN" VARCHAR2(100 BYTE),
	"BANK_NAME" VARCHAR2(120 BYTE),
	"BANK_ADDRESS" VARCHAR2(120 BYTE),
	"BANK_CITY" VARCHAR2(50 BYTE),
	"BANK_COUNTRY_CODE" VARCHAR2(2 BYTE),
	"ACC_HOLDER_ADDRESS" VARCHAR2(120 BYTE),
	"ACC_HOLDER_CITY" VARCHAR2(50 BYTE),
	"ACC_HOLDER_COUNTRY_CODE" VARCHAR2(2 BYTE),
	CONSTRAINT "WIF_BA_PK" PRIMARY KEY ("ID")
	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255,
	CONSTRAINT "WIF_BA_LE_FK" FOREIGN KEY ("ID_LE") REFERENCES "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"("ID"),
	CONSTRAINT "WIF_BA_DOC_FK" FOREIGN KEY ("ID_BANK_DOCUMENT") REFERENCES "WIFI4EU_ABAC"."WIF_DOCUMENTS"("ID")
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "WIFI4EU_ABAC" ;

COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BANK_ACCOUNTS"."ID" IS 'Incremental ID';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BANK_ACCOUNTS"."ID_LE" IS 'ID of the related LegalEntity';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BANK_ACCOUNTS"."ID_BANK_DOCUMENT" IS 'ID of the related file with the bank statement';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_BANK_ACCOUNTS"."WF_STATUS" IS 'Workflow status';


-- -----------------------------------------------------
-- Table "WIFI4EU_ABAC"."WIF_CALLS"
-- -----------------------------------------------------
CREATE TABLE "WIFI4EU_ABAC"."WIF_CALLS" (
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(50 BYTE),
	"START_DATE" VARCHAR2(20 BYTE),
	"END_DATE" VARCHAR2(20 BYTE),	
	"APPLICATION" VARCHAR2(50 BYTE),
	"AMOUNT" NUMBER(5,0),
	"AGENT_ID" VARCHAR2(20 BYTE),
	"AGENT_NAME" VARCHAR2(50 BYTE),
	CONSTRAINT "WIF_CALLS_PK" PRIMARY KEY ("ID")
	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "WIFI4EU_ABAC" ;

COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_CALLS"."ID" IS 'Incremental ID';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_CALLS"."AGENT_ID" IS 'User ID of the responsible user for the objects creation in ABAC';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_CALLS"."AGENT_NAME" IS 'User name of the responsible user for the objects creation in ABAC';


-- -----------------------------------------------------
-- Table "WIFI4EU_ABAC"."WIF_ROLES"
-- -----------------------------------------------------
CREATE TABLE "WIFI4EU_ABAC"."WIF_ROLES" (
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"CODE" VARCHAR2(20 BYTE),
	"NAME" VARCHAR2(50 BYTE),
	CONSTRAINT "WIF_ROLES_PK" PRIMARY KEY ("ID")
	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "WIFI4EU_ABAC" ;


-- -----------------------------------------------------
-- Table "WIFI4EU_ABAC"."WIF_USERS"
-- -----------------------------------------------------
CREATE TABLE "WIFI4EU_ABAC"."WIF_USERS" (
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"USERNAME" VARCHAR2(20 BYTE),
	"NAME" VARCHAR2(50 BYTE),
	"EMAIL" VARCHAR2(50 BYTE),
	CONSTRAINT "WIF_USERS_PK" PRIMARY KEY ("ID")
	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "WIFI4EU_ABAC" ;


-- -----------------------------------------------------
-- Table "WIFI4EU_ABAC"."WIF_USER_ROLES"
-- -----------------------------------------------------
CREATE TABLE "WIFI4EU_ABAC"."WIF_USER_ROLES" (
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"USER_ID" NUMBER(18,0) NOT NULL ENABLE,
	"ROLE_ID" NUMBER(18,0) NOT NULL ENABLE,
	CONSTRAINT "WIF_UR_PK" PRIMARY KEY ("ID")
	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255,
	CONSTRAINT "WIF_UR_USERS_FK" FOREIGN KEY ("USER_ID") REFERENCES "WIFI4EU_ABAC"."WIF_USERS"("ID"),
	CONSTRAINT "WIF_UR_ROLES_FK" FOREIGN KEY ("ROLE_ID") REFERENCES "WIFI4EU_ABAC"."WIF_ROLES"("ID")	
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "WIFI4EU_ABAC" ;


-- -----------------------------------------------------
-- Table "WIFI4EU_ABAC"."WIF_REPORTS"
-- -----------------------------------------------------
CREATE TABLE "WIFI4EU_ABAC"."WIF_REPORTS" (
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"USER_ID" NUMBER(18,0) NOT NULL ENABLE,
	"TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"DATE_CREATED" VARCHAR2(20 BYTE) DEFAULT TO_CHAR(sysdate, 'MM/DD/YYYY HH:MM:SS') NOT NULL ENABLE,
	"LE_ID" NUMBER(18,0) NOT NULL ENABLE,
	"BC_ID" NUMBER(18,0) NOT NULL ENABLE,
	"LC_ID" NUMBER(18,0) NOT NULL ENABLE,
	CONSTRAINT "WIF_REP_PK" PRIMARY KEY ("ID")
	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255,
	CONSTRAINT "WIF_REP_USERS_FK" FOREIGN KEY ("USER_ID") REFERENCES "WIFI4EU_ABAC"."WIF_USERS"("ID"),
	CONSTRAINT "WIF_REP_LE_FK" FOREIGN KEY ("LE_ID") REFERENCES "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"("ID"),
	CONSTRAINT "WIF_REP_BC_FK" FOREIGN KEY ("BC_ID") REFERENCES "WIFI4EU_ABAC"."WIF_BUDGETARY_COMMITMENT"("ID"),
	CONSTRAINT "WIF_REP_LC_FK" FOREIGN KEY ("LC_ID") REFERENCES "WIFI4EU_ABAC"."WIF_LEGAL_COMMITMENT"("ID")	
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "WIFI4EU_ABAC" ;

COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_REPORTS"."ID" IS 'Incremental ID';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_REPORTS"."USER_ID" IS 'ID of the user that requested the export';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_REPORTS"."TYPE" IS 'Type of export requested: LE, BC or LC';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_REPORTS"."LE_ID" IS 'ID of the related LegalEntity';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_REPORTS"."BC_ID" IS 'ID of the related BudgetaryCommitment';
COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_REPORTS"."LC_ID" IS 'ID of the related LegalCommitment';

--------------------------------------------------------
--  DDL for Sequence SEQ_LEGAL_ENTITY
--------------------------------------------------------

   CREATE SEQUENCE  "WIFI4EU_ABAC"."SEQ_LEGAL_ENTITY"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence SEQ_WIF_ABAC_STATUS
--------------------------------------------------------

   CREATE SEQUENCE  "WIFI4EU_ABAC"."SEQ_WIF_ABAC_STATUS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence SEQ_LEF_RUN_ID
--------------------------------------------------------

   CREATE SEQUENCE  "WIFI4EU_ABAC"."SEQ_LEF_RUN_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

   
--------------------------------------------------------
--  ADDED COLUMNS AND CONSTRAINTS FOR TABLE "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"
--------------------------------------------------------
 ALTER TABLE "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY" ADD "USER_IMPORTED" VARCHAR2(20 BYTE);
 COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."USER_IMPORTED" IS 'Username of the last user who exported it';
 
 ALTER TABLE "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY" ADD "ID_SIGNATURE_FILE" NUMBER(18,0);
 COMMENT ON COLUMN "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY"."ID_SIGNATURE_FILE" IS 'ID of the related file with the signature';
 ALTER TABLE "WIFI4EU_ABAC"."WIF_LEGAL_ENTITY" ADD CONSTRAINT "WIF_LE_DOC_FK" FOREIGN KEY ("ID_SIGNATURE_FILE") REFERENCES "WIFI4EU_ABAC"."WIF_DOCUMENTS"("ID")

--------------------------------------------------------
--  DDL for Sequence SEQ_DOCUMENTS
--------------------------------------------------------

   CREATE SEQUENCE  "WIFI4EU_ABAC"."SEQ_DOCUMENTS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;


--------------------------------------------------------
--  DDL for Procedure CREATE_LEF_IN_ABAC
--------------------------------------------------------
set define off;

create or replace PROCEDURE                "CREATE_LEF_IN_ABAC"
(LEGALENTITYID IN NUMBER ) AS
  PRAGMA AUTONOMOUS_TRANSACTION;

  l_run_id				          NUMBER;
	l_loc_sys_cd			        VARCHAR2(3);
	l_loc_obj_foreign_id	    VARCHAR2(56);
	l_que_id 				          NUMBER;
  l_destination             VARCHAR2(200);
  l_trans_area_cd           VARCHAR2(200);
  l_trans_tp_cd             VARCHAR2(200);
  l_trans_action_cd         VARCHAR2(200);
  l_table_alias             VARCHAR2(200);
  l_debtor_cat_id           VARCHAR2(200);
  l_legal_type_cd           VARCHAR2(200);
  l_resp_org_struct_key_cd  VARCHAR2(200);
  l_resp_org_struct_tp_cd   VARCHAR2(200);
  l_doc_table_alias         VARCHAR2(200);
  l_visa_table_alias        VARCHAR2(200);
  l_visa_action_cd          VARCHAR2(200);
  l_visa_signature          VARCHAR2(200);
  l_visa_comment            VARCHAR2(200);
  l_visa_agent_id           VARCHAR2(200);
  l_visa_wlkflw_center_cd   VARCHAR2(200);
  l_visa_wlkflw_orgname     VARCHAR2(200);
  l_visa_agent_type         VARCHAR2(200);
  l_visa_agent_name         VARCHAR2(200);
  l_LE_ID NUMBER := LEGALENTITYID;
  l_language_cd             VARCHAR2(1);

BEGIN
 --init constants
 l_run_id := SEQ_LEF_RUN_ID.NEXTVAL;
 SELECT VALUE INTO l_loc_sys_cd from WIF_CONSTANTS WHERE NAME='ABAC_SYS_CD';
 SELECT VALUE INTO l_destination from WIF_CONSTANTS WHERE NAME='LEF_V_LOC_DEST';
 SELECT VALUE INTO l_trans_area_cd from WIF_CONSTANTS WHERE NAME='LEF_V_LOC_TRANS_AREA_CD';
 SELECT VALUE INTO l_trans_tp_cd from WIF_CONSTANTS WHERE NAME='LEF_V_LOC_TRANS_TP_CD';
 SELECT VALUE INTO l_trans_action_cd from WIF_CONSTANTS WHERE NAME='LEF_V_LOC_TRANS_ACTION_CD';
 SELECT VALUE INTO l_table_alias from WIF_CONSTANTS WHERE NAME='LEF_V_LOC_TABLE_ALIAS';
 SELECT VALUE INTO l_debtor_cat_id from WIF_CONSTANTS WHERE NAME='LEF_V_LOC_DEBTOR_CAT_ID';
 SELECT VALUE INTO l_legal_type_cd from WIF_CONSTANTS WHERE NAME='LEF_V_LOC_LEGAL_TYPE_CD';
 SELECT VALUE INTO l_resp_org_struct_key_cd from WIF_CONSTANTS WHERE NAME='LEF_V_LOC_RESP_ORG_STRUCT_KEY_CD';
 SELECT VALUE INTO l_resp_org_struct_tp_cd from WIF_CONSTANTS WHERE NAME='LEF_V_LOC_RESP_ORG_STRUCT_TP_CD';

 SELECT VALUE INTO l_doc_table_alias from WIF_CONSTANTS WHERE NAME='LEF_V_LOC_DOC_TABLE_ALIAS';

 SELECT VALUE INTO l_visa_table_alias from WIF_CONSTANTS WHERE NAME='LEF_V_LOC_VISA_TABLE_ALIAS';
 SELECT VALUE INTO l_visa_action_cd from WIF_CONSTANTS WHERE NAME='LEF_V_LOC_VISA_ACTION_CD';
 SELECT VALUE INTO l_visa_signature from WIF_CONSTANTS WHERE NAME='LEF_V_LOC_VISA_SIGNATURE';
 SELECT VALUE INTO l_visa_comment from WIF_CONSTANTS WHERE NAME='LEF_V_LOC_VISA_DEFAULT_COMMENT';
 SELECT VALUE INTO l_visa_agent_id from WIF_CONSTANTS WHERE NAME='LEF_V_LOC_VISA_AGENT_ID';
 SELECT VALUE INTO l_visa_wlkflw_center_cd from WIF_CONSTANTS WHERE NAME='LEF_V_LOC_VISA_WRKFLW_CENTER_CD';
 SELECT VALUE INTO l_visa_wlkflw_orgname from WIF_CONSTANTS WHERE NAME='LEF_V_LOC_VISA_WRKFLW_ORG_NAME';
 SELECT VALUE INTO l_visa_agent_type from WIF_CONSTANTS WHERE NAME='LEF_V_LOC_VISA_SIGN_AS_AGENT_TYPE';
 SELECT VALUE INTO l_visa_agent_name from WIF_CONSTANTS WHERE NAME='LEF_V_LOC_VISA_SUPPLIED_AGENT_NAME';


 l_loc_obj_foreign_id:= l_loc_sys_cd || '.' || to_char(l_run_id);


 FOR legatEntity in (SELECT * FROM WIF_LEGAL_ENTITY WHERE ID=l_LE_ID) LOOP
    dbms_output.put_line('OFFICIAL_NAME='||legatEntity.OFFICIAL_NAME);

    select LANGUAGE_CD into l_language_cd from V_O_GEN_LANGUAGES@ABACBUDT_SHARED
    where (UPPER(legatEntity.LANGUAGE_CODE) = UPPER(LANGUAGE_SIC_CD)
       or UPPER(legatEntity.LANGUAGE_CODE) = UPPER(LNG_ISO3_CD))
    and valid_flg ='Y';

    -- Logon into ABAC: activate security
    Insert into V_ABAC_BATCHINT_LOGIN@ABACBUDT_SHARED  Values ('X');


    Insert into V_LOC_THP_LEGAL_ENTITIES@ABACBUDT_SHARED
     (RUN_ID, ROW_ID, LOC_SYS_CD, DESTINATION, TRANS_AREA_CD,
      TRANS_TP_CD, TRANS_ACTION_CD, TABLE_ALIAS, LOC_OBJ_FOREIGN_ID, PROCESSED,
      CTY_ISO2_CD, LANGUAGE_CD, NAME, VEND_CUST_SWITCH_CD, STREET,
      CITY, POST_BOX, POST_CD, COUNTY, VAT,
      REMARKS, BIRTH_CITY, BIRTH_CTY_ISO2_CD, BIRTH_DT, CUST_ONLY_FLG,
      DEBTOR_CAT_ID, FIRST_NAME, IDENTIFICATION_NUM, LEGAL_FORM_ID, LEGAL_TYPE_CD,
      MATRICULE_NUM, REG_AUTH, REG_DT, REG_NUM, STREET_2,
      STREET_3, SUPP_ACRONYM, SUP_OFFICIAL_NAME_2, SUP_OFFICIAL_NAME_3, SUP_OFFICIAL_NAME_4,
      ID_DOC_TYPE_ID, TITLE_ID, MAIL_ADR_OPT, PER_ID, RESP_ORG_STRUCT_ID,
      LEGAL_FORM_FPO_TP_ID, ORIG_LOC_OBJ_FOREIGN_ID, IS_NGO_FLG, RESP_ORG_STRUCT_KEY_CD, RESP_ORG_STRUCT_TP_CD,
      NAT_ID_NUM, NAT_ID_CTY_ISO2_CD, PASSP_NUM, PASSP_CTY_ISO2_CD, DRIVL_NUM,
      DRIVL_CTY_ISO2_CD, OTH_DOC_NUM, OTH_DOC_CTY_ISO2_CD, ID_CARD_NUM, ID_CARD_CTY_ISO2_CD,
      REGISTR_CTY_ISO2_CD, BUSS_NAME, CMPY_NUM, LIGHT_VALIDATION_FLG, DUPLICATE_BYPASS_FLG,
      CONTEXT_CD, SELF_EMPLOYED_FLG)
   Values
     (l_run_id, 10, l_loc_sys_cd, l_destination, l_trans_area_cd,
      l_trans_tp_cd, l_trans_action_cd, l_table_alias, l_loc_obj_foreign_id, 'N',
      UPPER(legatEntity.COUNTRY_CODE), l_language_cd, UPPER(legatEntity.OFFICIAL_NAME), 'SUP', UPPER(legatEntity.OFFICIAL_ADDRESS),
      UPPER(legatEntity.OFFICIAL_NAME), NULL, legatEntity.POSTAL_CODE, NULL, NULL,
      NULL, NULL, NULL, NULL, NULL,
      l_debtor_cat_id, NULL, NULL, NULL, l_legal_type_cd,
      NULL, NULL, NULL, NULL, NULL,
      NULL, NULL, NULL, NULL, NULL,
      NULL, NULL, NULL, NULL, NULL,
      NULL, NULL, NULL, l_resp_org_struct_key_cd, l_resp_org_struct_tp_cd,
      NULL, NULL, NULL, NULL, NULL,
      NULL, NULL, NULL, NULL, NULL,
      NULL, NULL, NULL, NULL, NULL,
      NULL, NULL);

      -- insert document rerefences
      Insert into V_LOC_GEN_DOCS_REFERENCES@ABACBUDT_SHARED
       (RUN_ID, ROW_ID, LOC_SYS_CD, DESTINATION, TRANS_AREA_CD,
        TRANS_TP_CD, TRANS_ACTION_CD, TABLE_ALIAS, LOC_OBJ_FOREIGN_ID, PROCESSED,
        DOC_REFERENCE, DOC_DESCRIPTION, OFFICIAL_DOC_FLG)
     Values
       (l_run_id, 20, l_loc_sys_cd, l_destination, l_trans_area_cd,
        l_trans_tp_cd, l_trans_action_cd, l_doc_table_alias, l_loc_obj_foreign_id, 'N',
        'Ares(2017)4800601', 'NO COMMENTS', 'Y');

      -- insert VISA details
      Insert into V_LOC_VISA@ABACBUDT_SHARED
       (RUN_ID, ROW_ID, LOC_SYS_CD, DESTINATION, TRANS_AREA_CD,
        TRANS_TP_CD, TRANS_ACTION_CD, TABLE_ALIAS, LOC_OBJ_FOREIGN_ID, PROCESSED,
        ACTION_CD, SIGNATURE, COMMENT_TXT, PERSON_ID, LOT_LOC_OBJ_FOREIGN_ID,
        LOC_SYS_VISA_DT, AGENT_ID, WRKFLW_CENTER_CD, WRKFLW_ORG_NAME, SIGN_AS_AGENT_TYPE,
        SUPPLIED_AGENT_NAME, SW_ORG_NAME)
     Values
       (l_run_id, 80, l_loc_sys_cd, l_destination, l_trans_area_cd,
        l_trans_tp_cd, l_trans_action_cd, l_visa_table_alias, l_loc_obj_foreign_id, 'N',
        l_visa_action_cd, l_visa_signature, l_visa_comment, NULL, NULL,
        NULL, l_visa_agent_id, l_visa_wlkflw_center_cd, l_visa_wlkflw_orgname, l_visa_agent_type,
        l_visa_agent_name, NULL);

      -- submit batch transmission in ABAC :
      pck_abac_batchint_client.p_submit_batch@ABACBUDT_SHARED(l_run_id, l_loc_sys_cd, 'BATCH_QUE1', l_que_id);

      -- INSERT in STATUS Table
      Insert into WIF_ABAC_REQUEST_PROCESS (ID,LE_ID,L_RUN_ID,L_LOC_SYS_CD,L_LOC_OBJ_FK,L_QUE_ID) values (SEQ_WIF_ABAC_STATUS.NEXTVAL,l_LE_ID,l_run_id,l_loc_sys_cd,l_loc_obj_foreign_id,l_que_id);

      --UPDATE the LEGAL_ENTITY status
      update WIF_LEGAL_ENTITY set WF_STATUS='WAITING_FOR_ABAC' where ID=l_LE_ID;

      -- commit operations
      commit;
 END LOOP;
END CREATE_LEF_IN_ABAC;

/

--------------------------------------------------------
--  DDL for Procedure UPDATE_LEF_STATUS_FROM_ABAC
--------------------------------------------------------

create or replace PROCEDURE  UPDATE_LEF_STATUS_FROM_ABAC AS
  PRAGMA AUTONOMOUS_TRANSACTION;
  WAITING_FOR_ABAC varchar2(30);
  WAITING_APPROVAL varchar2(30);
  rows_affected number;
BEGIN
  --init constants
  WAITING_FOR_ABAC := 'WAITING_FOR_ABAC';
  WAITING_APPROVAL := 'WAITING_APPROVAL';

  rows_affected := 0;
  for request in (
                  select le_id, l_loc_obj_fk, le.WF_STATUS as legal_entity_status, status_vw.status as abac_status, status_vw.LE_KEY
                  from wif_abac_request_process request
                  inner join wif_legal_entity le on request.le_id = le.id and le.wf_status in (WAITING_FOR_ABAC, WAITING_APPROVAL)
                  left join wif_abac_lef_status_view status_vw on request.l_loc_obj_fk = loc_obj_foreign_id
                  order by le_id, l_loc_obj_fk)
  loop
      dbms_output.put_line('LEGAL_ENTITY_ID='||request.le_id);

      if (request.legal_entity_status <> request.abac_status) then
        update wif_legal_entity set WF_STATUS = request.abac_status, abac_fel_id = request.LE_KEY
        where wif_legal_entity.id = request.le_id;
      end if;

      rows_affected := rows_affected + 1;
  END LOOP;
  commit;
END UPDATE_LEF_STATUS_FROM_ABAC;

/

--------------------------------------------------------
--  ADDED COLUMNS AND CONSTRAINTS FOR TABLE "WIFI4EU_ABAC"."WIF_DOCUMENTS"
--------------------------------------------------------

alter table wif_documents add(
  portal_id number,
  legal_entity_id number,
  document_type varchar2(50),
  filename varchar2(255),
  portal_date date
);

alter table wif_documents add constraint WIF_DOC_LE_FK foreign key(legal_entity_id) references WIFI4EU_ABAC.WIF_LEGAL_ENTITY(ID);

/