INSERT INTO LOC_NUTS_T (NUTS_ID, NUTS_CODE, NUTS_LABEL, NUTS_LEVEL, COUNTRY_CODE, _ORDER, SORTING)
VALUES (1, 'ES', 'ESPANYA', 0, 'ES', 9, 710);
INSERT INTO LOC_NUTS_T (NUTS_ID, NUTS_CODE, NUTS_LABEL, NUTS_LEVEL, COUNTRY_CODE, _ORDER, SORTING)
VALUES (2, 'ES5', 'ESTE', 1, 'ES', 9, 757);
INSERT INTO LOC_NUTS_T (NUTS_ID, NUTS_CODE, NUTS_LABEL, NUTS_LEVEL, COUNTRY_CODE, _ORDER, SORTING)
VALUES (3, 'ES51', 'Catalunya', 2, 'ES', 9, 758);
INSERT INTO LOC_NUTS_T (NUTS_ID, NUTS_CODE, NUTS_LABEL, NUTS_LEVEL, COUNTRY_CODE, _ORDER, SORTING)
VALUES (4, 'ES511', 'Barcelona', 3, 'ES', 9, 759);
INSERT INTO LOC_NUTS_T (NUTS_ID, NUTS_CODE, NUTS_LABEL, NUTS_LEVEL, COUNTRY_CODE, _ORDER, SORTING)
VALUES (5, 'ES512', 'Girona', 3, 'ES', 9, 760);
INSERT INTO LOC_NUTS_T (NUTS_ID, NUTS_CODE, NUTS_LABEL, NUTS_LEVEL, COUNTRY_CODE, _ORDER, SORTING)
VALUES (6, 'ES513', 'Lleida', 3, 'ES', 9, 761);
INSERT INTO LOC_NUTS_T (NUTS_ID, NUTS_CODE, NUTS_LABEL, NUTS_LEVEL, COUNTRY_CODE, _ORDER, SORTING)
VALUES (7, 'ES514', 'Tarragona', 3, 'ES', 9, 762);
INSERT INTO LOC_NUTS_T (NUTS_ID, NUTS_CODE, NUTS_LABEL, NUTS_LEVEL, COUNTRY_CODE, _ORDER, SORTING)
VALUES (8, 'SI', 'SLOVENIJA', '0', 'SI', '24', '1498');
INSERT INTO LOC_NUTS_T (NUTS_ID, NUTS_CODE, NUTS_LABEL, NUTS_LEVEL, COUNTRY_CODE, _ORDER, SORTING)
VALUES (9,'SI031', 'Pomurska', '3', 'SI', '24', '1501');
INSERT INTO LOC_NUTS_T (NUTS_ID, NUTS_CODE, NUTS_LABEL, NUTS_LEVEL, COUNTRY_CODE, _ORDER, SORTING)
VALUES (10,'SI032', 'Podravska', '3', 'SI', '24', '1502');
