package abac.legal_entity.service.es.async.v1;

import abac.legal_entity.v2.*;
import abac.message.v1.BusinessRuleMessageResponseType;
import abac.messagefault.v1.FaultMessage;
import abac.organisational_group.v1.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-07-28T12:43:21.483+02:00
 * Generated source version: 3.0.4
 */
@WebService(targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_entity/service/es/async/v1", name = "LegalEntityPort")
@XmlSeeAlso({ObjectFactory.class, abac.legal_entity.v2.ObjectFactory.class, abac.supporting_document.v1.ObjectFactory.class, abac.workflow.v1.ObjectFactory.class, abac.ares_document.v1.ObjectFactory.class, abac.br.v1.ObjectFactory.class, abac.local_abac_document.v1.ObjectFactory.class, abac.central_reference.v1.ObjectFactory.class, abac.complex_type.v1.ObjectFactory.class, abac.abac_object.v1.ObjectFactory.class, abac.organisation.v1.ObjectFactory.class, abac.message.v1.ObjectFactory.class, abac.responsible_user.v1.ObjectFactory.class, abac.legal_entity_bank_account_link.v1.ObjectFactory.class, abac.external_criteria.v1.ObjectFactory.class, abac.scanned_document.v1.ObjectFactory.class, abac.address.v1.ObjectFactory.class, abac.external_criteria_type.v1.ObjectFactory.class, abac.country.v1.ObjectFactory.class, abac.bank_account.v1.ObjectFactory.class, abac.legal_form.v1.ObjectFactory.class, abac.workflow_object.v1.ObjectFactory.class, abac.currency.v1.ObjectFactory.class, abac.external_criteria_code.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LegalEntityPort {

    @WebMethod(operationName = "create_scanned_document", action = "http://www.ec.europa.eu/budg/abac/legal_entity/service/es/async/create_scanned_document/v1")
    @WebResult(name = "LegalEntityCreateScannedDocumentResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_entity/v2", partName = "parameters")
    public BusinessRuleMessageResponseType createScannedDocument(
            @WebParam(partName = "parameters", name = "LegalEntityCreateScannedDocumentRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_entity/v2")
                    LegalEntityCreateScannedDocumentRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "create_responsible_user", action = "http://www.ec.europa.eu/budg/abac/legal_entity/service/es/async/create_responsible_user/v1")
    @WebResult(name = "LegalEntityCreateResponsibleUserResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_entity/v2", partName = "parameters")
    public BusinessRuleMessageResponseType createResponsibleUser(
            @WebParam(partName = "parameters", name = "LegalEntityCreateResponsibleUserRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_entity/v2")
                    LegalEntityCreateResponsibleUserRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "give_visa", action = "http://www.ec.europa.eu/budg/abac/legal_entity/service/es/async/give_visa/v1")
    @WebResult(name = "LegalEntityGiveVisaResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_entity/v2", partName = "parameters")
    public BusinessRuleMessageResponseType giveVisa(
            @WebParam(partName = "parameters", name = "LegalEntityGiveVisaRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_entity/v2")
                    LegalEntityGiveVisaRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "modify_mailing_address", action = "http://www.ec.europa.eu/budg/abac/legal_entity/service/es/async/modify_mailing_address/v1")
    @WebResult(name = "LegalEntityModifyMailingAddressResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_entity/v2", partName = "parameters")
    public BusinessRuleMessageResponseType modifyMailingAddress(
            @WebParam(partName = "parameters", name = "LegalEntityModifyMailingAddressRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_entity/v2")
                    LegalEntityModifyMailingAddressRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "create_mailing_address", action = "http://www.ec.europa.eu/budg/abac/legal_entity/service/es/async/create_mailing_address/v1")
    @WebResult(name = "LegalEntityCreateMailingAddressResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_entity/v2", partName = "parameters")
    public BusinessRuleMessageResponseType createMailingAddress(
            @WebParam(partName = "parameters", name = "LegalEntityCreateMailingAddressRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_entity/v2")
                    LegalEntityCreateMailingAddressRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "create_bank_account", action = "http://www.ec.europa.eu/budg/abac/legal_entity/service/es/async/create_bank_account/v1")
    @WebResult(name = "LegalEntityCreateBankAccountResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_entity/v2", partName = "parameters")
    public BusinessRuleMessageResponseType createBankAccount(
            @WebParam(partName = "parameters", name = "LegalEntityCreateBankAccountRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_entity/v2")
                    LegalEntityCreateBankAccountRequestType parameters
    ) throws FaultMessage;

    @WebMethod(action = "http://www.ec.europa.eu/budg/abac/legal_entity/service/es/async/create/v1")
    @WebResult(name = "LegalEntityCreateResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_entity/v2", partName = "parameters")
    public BusinessRuleMessageResponseType create(
            @WebParam(partName = "parameters", name = "LegalEntityCreateRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_entity/v2")
                    LegalEntityCreateRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "create_ares_document", action = "http://www.ec.europa.eu/budg/abac/legal_entity/service/es/async/create_ares_document/v1")
    @WebResult(name = "LegalEntityCreateAresDocumentResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_entity/v2", partName = "parameters")
    public BusinessRuleMessageResponseType createAresDocument(
            @WebParam(partName = "parameters", name = "LegalEntityCreateAresDocumentRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/legal_entity/v2")
                    LegalEntityCreateAresDocumentRequestType parameters
    ) throws FaultMessage;
}
