INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG341','BGS01','no',N'Айтос-Aytos',N'АЙТОС-AYTOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG341','BGS04','no',N'Бургас-Burgas',N'БУРГАС-BURGAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG341','BGS06','no',N'Средец-Sredets',N'СРЕДЕЦ-SREDETS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG341','BGS08','no',N'Камено-Kameno',N'КАМЕНО-KAMENO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG341','BGS09','no',N'Карнобат-Karnobat',N'КАРНОБАТ-KARNOBAT');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG341','BGS12','no',N'Малко Търново-Malko Tarnovo',N'МАЛКО ТЪРНОВО-MALKO TARNOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG341','BGS13','no',N'Царево-Tsarevo',N'ЦАРЕВО-TSAREVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG341','BGS15','no',N'Несебър-Nesebar',N'НЕСЕБЪР-NESEBAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG341','BGS17','no',N'Поморие-Pomorie',N'ПОМОРИЕ-POMORIE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG341','BGS18','no',N'Руен-Ruen',N'РУЕН-RUEN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG341','BGS21','no',N'Созопол-Sozopol',N'СОЗОПОЛ-SOZOPOL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG341','BGS23','no',N'Сунгурларе-Sungurlare',N'СУНГУРЛАРЕ-SUNGURLARE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG341','BGS27','no',N'Приморско-Primorsko',N'ПРИМОРСКО-PRIMORSKO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG413','BLG01','no',N'Банско-Bansko',N'БАНСКО-BANSKO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG413','BLG02','no',N'Белица-Belitsa',N'БЕЛИЦА-BELITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG413','BLG03','no',N'Благоевград-Blagoevgrad',N'БЛАГОЕВГРАД-BLAGOEVGRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG413','BLG11','no',N'Гоце Делчев-Gotse Delchev',N'ГОЦЕ ДЕЛЧЕВ-GOTSE DELCHEV');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG413','BLG13','no',N'Гърмен-Garmen',N'ГЪРМЕН-GARMEN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG413','BLG28','no',N'Кресна-Kresna',N'КРЕСНА-KRESNA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG413','BLG33','no',N'Петрич-Petrich',N'ПЕТРИЧ-PETRICH');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG413','BLG37','no',N'Разлог-Razlog',N'РАЗЛОГ-RAZLOG');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG413','BLG40','no',N'Сандански-Sandanski',N'САНДАНСКИ-SANDANSKI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG413','BLG42','no',N'Сатовча-Satovcha',N'САТОВЧА-SATOVCHA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG413','BLG44','no',N'Симитли-Simitli',N'СИМИТЛИ-SIMITLI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG413','BLG49','no',N'Струмяни-Strumyani',N'СТРУМЯНИ-STRUMYANI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG413','BLG52','no',N'Хаджидимово-Hadzhidimovo',N'ХАДЖИДИМОВО-HADZHIDIMOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG413','BLG53','no',N'Якоруда-Yakoruda',N'ЯКОРУДА-YAKORUDA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG332','DOB03','no',N'Балчик-Balchik',N'БАЛЧИК-BALCHIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG332','DOB12','no',N'Генерал Тошево-General Toshevo',N'ГЕНЕРАЛ ТОШЕВО-GENERAL TOSHEVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG332','DOB15','no',N'Добрич - селска-Dobrich-selska',N'ДОБРИЧ - СЕЛСКА-DOBRICH-SELSKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG332','DOB17','no',N'Каварна-Kavarna',N'КАВАРНА-KAVARNA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG332','DOB20','no',N'Крушари-Krushari',N'КРУШАРИ-KRUSHARI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG332','DOB27','no',N'Тервел-Tervel',N'ТЕРВЕЛ-TERVEL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG332','DOB28','no',N'Добрич-Dobrich',N'ДОБРИЧ-DOBRICH');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG332','DOB29','no',N'Шабла-Shabla',N'ШАБЛА-SHABLA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG322','GAB05','no',N'Габрово-Gabrovo',N'ГАБРОВО-GABROVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG322','GAB12','no',N'Дряново-Dryanovo',N'ДРЯНОВО-DRYANOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG322','GAB29','no',N'Севлиево-Sevlievo',N'СЕВЛИЕВО-SEVLIEVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG322','GAB35','no',N'Трявна-Tryavna',N'ТРЯВНА-TRYAVNA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG422','HKV09','no',N'Димитровград-Dimitrovgrad',N'ДИМИТРОВГРАД-DIMITROVGRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG422','HKV11','no',N'Ивайловград-Ivaylovgrad',N'ИВАЙЛОВГРАД-IVAYLOVGRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG422','HKV17','no',N'Любимец-Lyubimets',N'ЛЮБИМЕЦ-LYUBIMETS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG422','HKV18','no',N'Маджарово-Madzharovo',N'МАДЖАРОВО-MADZHAROVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG422','HKV19','no',N'Минерални бани-Mineralni bani',N'МИНЕРАЛНИ БАНИ-MINERALNI BANI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG422','HKV28','no',N'Свиленград-Svilengrad',N'СВИЛЕНГРАД-SVILENGRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG422','HKV29','no',N'Симеоновград-Simeonovgrad',N'СИМЕОНОВГРАД-SIMEONOVGRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG422','HKV30','no',N'Стамболово-Stambolovo',N'СТАМБОЛОВО-STAMBOLOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG422','HKV32','no',N'Тополовград-Topolovgrad',N'ТОПОЛОВГРАД-TOPOLOVGRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG422','HKV33','no',N'Харманли-Harmanli',N'ХАРМАНЛИ-HARMANLI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG422','HKV34','no',N'Хасково-Haskovo',N'ХАСКОВО-HASKOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG343','JAM03','no',N'Болярово-Bolyarovo',N'БОЛЯРОВО-BOLYAROVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG343','JAM07','no',N'Елхово-Elhovo',N'ЕЛХОВО-ELHOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG343','JAM22','no',N'Стралджа-Straldzha',N'СТРАЛДЖА-STRALDZHA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG343','JAM25','no',N'Тунджа-Tundzha',N'ТУНДЖА-TUNDZHA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG343','JAM26','no',N'Ямбол-Yambol',N'ЯМБОЛ-YAMBOL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG415','KNL04','no',N'Бобов дол-Bobovdol',N'БОБОВ ДОЛ-BOBOVDOL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG415','KNL05','no',N'Бобошево-Boboshevo',N'БОБОШЕВО-BOBOSHEVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG415','KNL27','no',N'Кочериново-Kocherinovo',N'КОЧЕРИНОВО-KOCHERINOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG415','KNL29','no',N'Кюстендил-Kyustendil',N'КЮСТЕНДИЛ-KYUSTENDIL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG415','KNL31','no',N'Невестино-Nevestino',N'НЕВЕСТИНО-NEVESTINO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG415','KNL38','no',N'Рила-Rila',N'РИЛА-RILA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG415','KNL41','no',N'Сапарева баня-Sapareva banya',N'САПАРЕВА БАНЯ-SAPAREVA BANYA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG415','KNL48','no',N'Дупница-Dupnitsa',N'ДУПНИЦА-DUPNITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG415','KNL50','no',N'Трекляно-Treklyano',N'ТРЕКЛЯНО-TREKLYANO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG425','KRZ02','no',N'Ардино-Ardino',N'АРДИНО-ARDINO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG425','KRZ08','no',N'Джебел-Dzhebel',N'ДЖЕБЕЛ-DZHEBEL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG425','KRZ14','no',N'Кирково-Kirkovo',N'КИРКОВО-KIRKOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG425','KRZ15','no',N'Крумовград-Krumovgrad',N'КРУМОВГРАД-KRUMOVGRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG425','KRZ16','no',N'Кърджали-Kardzhali',N'КЪРДЖАЛИ-KARDZHALI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG425','KRZ21','no',N'Момчилград-Momchilgrad',N'МОМЧИЛГРАД-MOMCHILGRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG425','KRZ35','no',N'Черноочене-Chernoochene',N'ЧЕРНООЧЕНЕ-CHERNOOCHENE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG315','LOV02','no',N'Априлци-Apriltsi',N'АПРИЛЦИ-APRILTSI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG315','LOV17','no',N'Летница-Letnitsa',N'ЛЕТНИЦА-LETNITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG315','LOV18','no',N'Ловеч-Lovech',N'ЛОВЕЧ-LOVECH');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG315','LOV19','no',N'Луковит-Lukovit',N'ЛУКОВИТ-LUKOVIT');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG315','LOV33','no',N'Тетевен-Teteven',N'ТЕТЕВЕН-TETEVEN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG315','LOV34','no',N'Троян-Troyan',N'ТРОЯН-TROYAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG315','LOV36','no',N'Угърчин-Ugarchin',N'УГЪРЧИН-UGARCHIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG315','LOV38','no',N'Ябланица-Yablanitsa',N'ЯБЛАНИЦА-YABLANITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG312','MON02','no',N'Берковица-Berkovitsa',N'БЕРКОВИЦА-BERKOVITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG312','MON04','no',N'Бойчиновци-Boychinovtsi',N'БОЙЧИНОВЦИ-BOYCHINOVTSI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG312','MON07','no',N'Брусарци-Brusartsi',N'БРУСАРЦИ-BRUSARTSI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG312','MON11','no',N'Вълчедръм-Valchedram',N'ВЪЛЧЕДРЪМ-VALCHEDRAM');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG312','MON12','no',N'Вършец-Varshets',N'ВЪРШЕЦ-VARSHETS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG312','MON14','no',N'Георги Дамяново-Georgi Damyanovo',N'ГЕОРГИ ДАМЯНОВО-GEORGI DAMYANOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG312','MON24','no',N'Лом-Lom',N'ЛОМ-LOM');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG312','MON26','no',N'Медковец-Medkovets',N'МЕДКОВЕЦ-MEDKOVETS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG312','MON29','no',N'Монтана-Montana',N'МОНТАНА-MONTANA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG312','MON36','no',N'Чипровци-Chiprovtsi',N'ЧИПРОВЦИ-CHIPROVTSI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG312','MON38','no',N'Якимово-Yakimovo',N'ЯКИМОВО-YAKIMOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG423','PAZ03','no',N'Батак-Batak',N'БАТАК-BATAK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG423','PAZ04','no',N'Белово-Belovo',N'БЕЛОВО-BELOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG423','PAZ06','no',N'Брацигово-Bratsigovo',N'БРАЦИГОВО-BRATSIGOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG423','PAZ08','no',N'Велинград-Velingrad',N'ВЕЛИНГРАД-VELINGRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG423','PAZ14','no',N'Лесичово-Lesichovo',N'ЛЕСИЧОВО-LESICHOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG423','PAZ19','no',N'Пазарджик-Pazardzhik',N'ПАЗАРДЖИК-PAZARDZHIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG423','PAZ20','no',N'Панагюрище-Panagyurishte',N'ПАНАГЮРИЩЕ-PANAGYURISHTE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG423','PAZ21','no',N'Пещера-Peshtera',N'ПЕЩЕРА-PESHTERA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG423','PAZ24','no',N'Ракитово-Rakitovo',N'РАКИТОВО-RAKITOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG423','PAZ29','no',N'Септември-Septemvri',N'СЕПТЕМВРИ-SEPTEMVRI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG423','PAZ32','no',N'Стрелча-Strelcha',N'СТРЕЛЧА-STRELCHA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG421','PDV01','no',N'Асеновград-Asenovgrad',N'АСЕНОВГРАД-ASENOVGRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG421','PDV07','no',N'Брезово-Brezovo',N'БРЕЗОВО-BREZOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG421','PDV12','no',N'Калояново-Kaloyanovo',N'КАЛОЯНОВО-KALOYANOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG421','PDV13','no',N'Карлово-Karlovo',N'КАРЛОВО-KARLOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG421','PDV15','no',N'Лъки-Laki',N'ЛЪКИ-LAKI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG421','PDV17','no',N'Марица-Maritsa',N'МАРИЦА-MARITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG421','PDV22','no',N'Пловдив-Plovdiv',N'ПЛОВДИВ-PLOVDIV');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG421','PDV23','no',N'Първомай-Parvomay',N'ПЪРВОМАЙ-PARVOMAY');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG421','PDV25','no',N'Раковски-Rakovski',N'РАКОВСКИ-RAKOVSKI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG421','PDV26','no',N'Родопи-Rodopi',N'РОДОПИ-RODOPI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG421','PDV28','no',N'Садово-Sadovo',N'САДОВО-SADOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG421','PDV33','no',N'Съединение-Saedinenie',N'СЪЕДИНЕНИЕ-SAEDINENIE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG421','PDV37','no',N'Хисаря-Hisarya',N'ХИСАРЯ-HISARYA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG421','PDV39','no',N'Кричим-Krichim',N'КРИЧИМ-KRICHIM');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG421','PDV40','no',N'Перущица-Perushtitsa',N'ПЕРУЩИЦА-PERUSHTITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG421','PDV41','no',N'Стамболийски-Stamboliyski',N'СТАМБОЛИЙСКИ-STAMBOLIYSKI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG421','PDV42','no',N'Куклен-Kuklen',N'КУКЛЕН-KUKLEN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG421','PDV43','no',N'Сопот-Sopot',N'СОПОТ-SOPOT');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG414','PER08','no',N'Брезник-Breznik',N'БРЕЗНИК-BREZNIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG414','PER19','no',N'Земен-Zemen',N'ЗЕМЕН-ZEMEN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG414','PER22','no',N'Ковачевци-Kovachevtsi',N'КОВАЧЕВЦИ-KOVACHEVTSI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG414','PER32','no',N'Перник-Pernik',N'ПЕРНИК-PERNIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG414','PER36','no',N'Радомир-Radomir',N'РАДОМИР-RADOMIR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG414','PER51','no',N'Трън-Tran',N'ТРЪН-TRAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG314','PVN03','no',N'Белене-Belene',N'БЕЛЕНЕ-BELENE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG314','PVN08','no',N'Гулянци-Gulyantsi',N'ГУЛЯНЦИ-GULYANTSI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG314','PVN10','no',N'Долна Митрополия-Dolna Mitropolia',N'ДОЛНА МИТРОПОЛИЯ-DOLNA MITROPOLIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG314','PVN11','no',N'Долни Дъбник-Dolni Dabnik',N'ДОЛНИ ДЪБНИК-DOLNI DABNIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG314','PVN16','no',N'Левски-Levski',N'ЛЕВСКИ-LEVSKI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG314','PVN21','no',N'Никопол-Nikopol',N'НИКОПОЛ-NIKOPOL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG314','PVN23','no',N'Искър-Iskar',N'ИСКЪР-ISKAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG314','PVN24','no',N'Плевен-Pleven',N'ПЛЕВЕН-PLEVEN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG314','PVN27','no',N'Пордим-Pordim',N'ПОРДИМ-PORDIM');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG314','PVN37','no',N'Червен бряг-Cherven bryag',N'ЧЕРВЕН БРЯГ-CHERVEN BRYAG');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG314','PVN39','no',N'Кнежа-Knezha',N'КНЕЖА-KNEZHA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG324','RAZ11','no',N'Завет-Zavet',N'ЗАВЕТ-ZAVET');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG324','RAZ14','no',N'Исперих-Isperih',N'ИСПЕРИХ-ISPERIH');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG324','RAZ16','no',N'Кубрат-Kubrat',N'КУБРАТ-KUBRAT');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG324','RAZ17','no',N'Лозница-Loznitsa',N'ЛОЗНИЦА-LOZNITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG324','RAZ26','no',N'Разград-Razgrad',N'РАЗГРАД-RAZGRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG324','RAZ29','no',N'Самуил-Samuil',N'САМУИЛ-SAMUIL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG324','RAZ36','no',N'Цар Калоян-Tsar Kaloyan',N'ЦАР КАЛОЯН-TSAR KALOYAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG323','RSE03','no',N'Борово-Borovo',N'БОРОВО-BOROVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG323','RSE04','no',N'Бяла (Русе)-Byala (Ruse)',N'БЯЛА (РУСЕ)-BYALA (RUSE)');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG323','RSE05','no',N'Ветово-Vetovo',N'ВЕТОВО-VETOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG323','RSE08','no',N'Две могили-Dve mogili',N'ДВЕ МОГИЛИ-DVE MOGILI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG323','RSE13','no',N'Иваново-Ivanovo',N'ИВАНОВО-IVANOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG323','RSE27','no',N'Русе-Ruse',N'РУСЕ-RUSE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG323','RSE33','no',N'Сливо поле-Slivo pole',N'СЛИВО ПОЛЕ-SLIVO POLE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG323','RSE37','no',N'Ценово-Tsenovo',N'ЦЕНОВО-TSENOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG412','SFO06','no',N'Божурище-Bozhurishte',N'БОЖУРИЩЕ-BOZHURISHTE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG412','SFO07','no',N'Ботевград-Botevgrad',N'БОТЕВГРАД-BOTEVGRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG412','SFO09','no',N'Годеч-Godech',N'ГОДЕЧ-GODECH');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG412','SFO10','no',N'Горна Малина-Gorna Malina',N'ГОРНА МАЛИНА-GORNA MALINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG412','SFO16','no',N'Драгоман-Dragoman',N'ДРАГОМАН-DRAGOMAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG412','SFO17','no',N'Елин Пелин-Elin Pelin',N'ЕЛИН ПЕЛИН-ELIN PELIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG412','SFO18','no',N'Етрополе-Etropole',N'ЕТРОПОЛЕ-ETROPOLE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG412','SFO20','no',N'Ихтиман-Ihtiman',N'ИХТИМАН-IHTIMAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG412','SFO24','no',N'Копривщица-Koprivshtitsa',N'КОПРИВЩИЦА-KOPRIVSHTITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG412','SFO25','no',N'Костенец-Kostenets',N'КОСТЕНЕЦ-KOSTENETS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG412','SFO26','no',N'Костинброд-Kostinbrod',N'КОСТИНБРОД-KOSTINBROD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG412','SFO34','no',N'Правец-Pravets',N'ПРАВЕЦ-PRAVETS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG412','SFO39','no',N'Самоков-Samokov',N'САМОКОВ-SAMOKOV');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG412','SFO43','no',N'Своге-Svoge',N'СВОГЕ-SVOGE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG412','SFO45','no',N'Сливница-Slivnitsa',N'СЛИВНИЦА-SLIVNITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG412','SFO47','no',N'Златица-Zlatitsa',N'ЗЛАТИЦА-ZLATITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG412','SFO54','no',N'Антон-Anton',N'АНТОН-ANTON');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG412','SFO55','no',N'Пирдоп-Pirdop',N'ПИРДОП-PIRDOP');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG412','SFO56','no',N'Мирково-Mirkovo',N'МИРКОВО-MIRKOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG412','SFO57','no',N'Чавдар-Chavdar',N'ЧАВДАР-CHAVDAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG412','SFO58','no',N'Челопеч-Chelopech',N'ЧЕЛОПЕЧ-CHELOPECH');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG412','SFO59','no',N'Долна баня-Dolna banya',N'ДОЛНА БАНЯ-DOLNA BANYA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG333','SHU07','no',N'Венец-Venets',N'ВЕНЕЦ-VENETS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG333','SHU10','no',N'Върбица-Varbitsa',N'ВЪРБИЦА-VARBITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG333','SHU11','no',N'Хитрино-Hitrino',N'ХИТРИНО-HITRINO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG333','SHU18','no',N'Каолиново-Kaolinovo',N'КАОЛИНОВО-KAOLINOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG333','SHU19','no',N'Каспичан-Kaspichan',N'КАСПИЧАН-KASPICHAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG333','SHU21','no',N'Никола Козлево-Nikola Kozlevo',N'НИКОЛА КОЗЛЕВО-NIKOLA KOZLEVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG333','SHU22','no',N'Нови пазар-Novi pazar',N'НОВИ ПАЗАР-NOVI PAZAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG333','SHU23','no',N'Велики Преслав-Veliki Preslav',N'ВЕЛИКИ ПРЕСЛАВ-VELIKI PRESLAV');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG333','SHU25','no',N'Смядово-Smyadovo',N'СМЯДОВО-SMYADOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG333','SHU30','no',N'Шумен-Shumen',N'ШУМЕН-SHUMEN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG325','SLS01','no',N'Алфатар-Alfatar',N'АЛФАТАР-ALFATAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG325','SLS07','no',N'Главиница-Glavinitsa',N'ГЛАВИНИЦА-GLAVINITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG325','SLS10','no',N'Дулово-Dulovo',N'ДУЛОВО-DULOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG325','SLS15','no',N'Кайнарджа-Kaynardzha',N'КАЙНАРДЖА-KAYNARDZHA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG325','SLS31','no',N'Силистра-Silistra',N'СИЛИСТРА-SILISTRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG325','SLS32','no',N'Ситово-Sitovo',N'СИТОВО-SITOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG325','SLS34','no',N'Тутракан-Tutrakan',N'ТУТРАКАН-TUTRAKAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG342','SLV11','no',N'Котел-Kotel',N'КОТЕЛ-KOTEL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG342','SLV16','no',N'Нова Загора-Nova Zagora',N'НОВА ЗАГОРА-NOVA ZAGORA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG342','SLV20','no',N'Сливен-Sliven',N'СЛИВЕН-SLIVEN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG342','SLV24','no',N'Твърдица-Tvarditsa',N'ТВЪРДИЦА-TVARDITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG424','SML02','no',N'Баните-Banite',N'БАНИТЕ-BANITE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG424','SML05','no',N'Борино-Borino',N'БОРИНО-BORINO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG424','SML09','no',N'Девин-Devin',N'ДЕВИН-DEVIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG424','SML10','no',N'Доспат-Dospat',N'ДОСПАТ-DOSPAT');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG424','SML11','no',N'Златоград-Zlatograd',N'ЗЛАТОГРАД-ZLATOGRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG424','SML16','no',N'Мадан-Madan',N'МАДАН-MADAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG424','SML18','no',N'Неделино-Nedelino',N'НЕДЕЛИНО-NEDELINO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG424','SML27','no',N'Рудозем-Rudozem',N'РУДОЗЕМ-RUDOZEM');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG424','SML31','no',N'Смолян-Smolyan',N'СМОЛЯН-SMOLYAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG424','SML38','no',N'Чепеларе-Chepelare',N'ЧЕПЕЛАРЕ-CHEPELARE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG411','SOF46','no',N'Столична-Stolichna',N'СТОЛИЧНА-STOLICHNA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG344','SZR04','no',N'Братя Даскалови-Bratya Daskalovi',N'БРАТЯ ДАСКАЛОВИ-BRATYA DASKALOVI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG344','SZR07','no',N'Гълъбово-Galabovo',N'ГЪЛЪБОВО-GALABOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG344','SZR12','no',N'Казанлък-Kazanlak',N'КАЗАНЛЪК-KAZANLAK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG344','SZR22','no',N'Мъглиж-Maglizh',N'МЪГЛИЖ-MAGLIZH');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG344','SZR23','no',N'Опан-Opan',N'ОПАН-OPAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG344','SZR24','no',N'Павел баня-Pavel banya',N'ПАВЕЛ БАНЯ-PAVEL BANYA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG344','SZR27','no',N'Раднево-Radnevo',N'РАДНЕВО-RADNEVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG344','SZR31','no',N'Стара Загора-Stara Zagora',N'СТАРА ЗАГОРА-STARA ZAGORA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG344','SZR36','no',N'Чирпан-Chirpan',N'ЧИРПАН-CHIRPAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG344','SZR37','no',N'Гурково-Gurkovo',N'ГУРКОВО-GURKOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG344','SZR38','no',N'Николаево-Nikolaevo',N'НИКОЛАЕВО-NIKOLAEVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG334','TGV02','no',N'Антоново-Antonovo',N'АНТОНОВО-ANTONOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG334','TGV22','no',N'Омуртаг-Omurtag',N'ОМУРТАГ-OMURTAG');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG334','TGV23','no',N'Опака-Opaka',N'ОПАКА-OPAKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG334','TGV24','no',N'Попово-Popovo',N'ПОПОВО-POPOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG334','TGV35','no',N'Търговище-Targovishte',N'ТЪРГОВИЩЕ-TARGOVISHTE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG331','VAR01','no',N'Аврен-Avren',N'АВРЕН-AVREN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG331','VAR02','no',N'Аксаково-Aksakovo',N'АКСАКОВО-AKSAKOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG331','VAR04','no',N'Белослав-Beloslav',N'БЕЛОСЛАВ-BELOSLAV');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG331','VAR05','no',N'Бяла (Варна)-Byala (Varna)',N'БЯЛА (ВАРНА)-BYALA (VARNA)');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG331','VAR06','no',N'Варна-Varna',N'ВАРНА-VARNA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG331','VAR08','no',N'Ветрино-Vetrino',N'ВЕТРИНО-VETRINO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG331','VAR09','no',N'Вълчи дол-Valchi dol',N'ВЪЛЧИ ДОЛ-VALCHI DOL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG331','VAR13','no',N'Долни чифлик-Dolni chiflik',N'ДОЛНИ ЧИФЛИК-DOLNI CHIFLIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG331','VAR14','no',N'Девня-Devnya',N'ДЕВНЯ-DEVNYA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG331','VAR16','no',N'Дългопол-Dalgopol',N'ДЪЛГОПОЛ-DALGOPOL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG331','VAR24','no',N'Провадия-Provadia',N'ПРОВАДИЯ-PROVADIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG331','VAR26','no',N'Суворово-Suvorovo',N'СУВОРОВО-SUVOROVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG311','VID01','no',N'Белоградчик-Belogradchik',N'БЕЛОГРАДЧИК-BELOGRADCHIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG311','VID03','no',N'Бойница-Boynitsa',N'БОЙНИЦА-BOYNITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG311','VID06','no',N'Брегово-Bregovo',N'БРЕГОВО-BREGOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG311','VID09','no',N'Видин-Vidin',N'ВИДИН-VIDIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG311','VID15','no',N'Грамада-Gramada',N'ГРАМАДА-GRAMADA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG311','VID16','no',N'Димово-Dimovo',N'ДИМОВО-DIMOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG311','VID22','no',N'Кула-Kula',N'КУЛА-KULA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG311','VID25','no',N'Макреш-Makresh',N'МАКРЕШ-MAKRESH');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG311','VID30','no',N'Ново село-Novo selo',N'НОВО СЕЛО-NOVO SELO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG311','VID33','no',N'Ружинци-Ruzhintsi',N'РУЖИНЦИ-RUZHINTSI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG311','VID37','no',N'Чупрене-Chuprene',N'ЧУПРЕНЕ-CHUPRENE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG313','VRC05','no',N'Борован-Borovan',N'БОРОВАН-BOROVAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG313','VRC08','no',N'Бяла Слатина-Byala Slatina',N'БЯЛА СЛАТИНА-BYALA SLATINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG313','VRC10','no',N'Враца-Vratsa',N'ВРАЦА-VRATSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG313','VRC20','no',N'Козлодуй-Kozloduy',N'КОЗЛОДУЙ-KOZLODUY');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG313','VRC21','no',N'Криводол-Krivodol',N'КРИВОДОЛ-KRIVODOL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG313','VRC27','no',N'Мездра-Mezdra',N'МЕЗДРА-MEZDRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG313','VRC28','no',N'Мизия-Mizia',N'МИЗИЯ-MIZIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG313','VRC31','no',N'Оряхово-Oryahovo',N'ОРЯХОВО-ORYAHOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG313','VRC32','no',N'Роман-Roman',N'РОМАН-ROMAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG313','VRC35','no',N'Хайредин-Hayredin',N'ХАЙРЕДИН-HAYREDIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG321','VTR04','no',N'Велико Търново-Veliko Tarnovo',N'ВЕЛИКО ТЪРНОВО-VELIKO TARNOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG321','VTR06','no',N'Горна Оряховица-Gorna Oryahovitsa',N'ГОРНА ОРЯХОВИЦА-GORNA ORYAHOVITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG321','VTR13','no',N'Елена-Elena',N'ЕЛЕНА-ELENA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG321','VTR14','no',N'Златарица-Zlataritsa',N'ЗЛАТАРИЦА-ZLATARITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG321','VTR20','no',N'Лясковец-Lyaskovets',N'ЛЯСКОВЕЦ-LYASKOVETS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG321','VTR22','no',N'Павликени-Pavlikeni',N'ПАВЛИКЕНИ-PAVLIKENI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG321','VTR26','no',N'Полски Тръмбеш-Polski Trambesh',N'ПОЛСКИ ТРЪМБЕШ-POLSKI TRAMBESH');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG321','VTR28','no',N'Свищов-Svishtov',N'СВИЩОВ-SVISHTOV');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG321','VTR31','no',N'Стражица-Strazhitsa',N'СТРАЖИЦА-STRAZHITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG321','VTR32','no',N'Сухиндол-Suhindol',N'СУХИНДОЛ-SUHINDOL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('BG','BG423','PAZ39','no',N'Сърница-Sarnitsa',N'СЪРНИЦА-SARNITSA');
