INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1000','no',N'Λευκωσία-Lefkosia',N'ΛΕΥΚΩΣΊΑ-LEFKOSIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1010','no',N'Άγιος Δομέτιος-Agios Dometios',N'ΆΓΙΟΣ ΔΟΜΈΤΙΟΣ-AGIOS DOMETIOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1011','no',N'Έγκωμη Λευκωσίας-Egkomi Lefkosias',N'ΈΓΚΩΜΗ ΛΕΥΚΩΣΊΑΣ-EGKOMI LEFKOSIAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1012','no',N'Στρόβολος-Strovolos',N'ΣΤΡΌΒΟΛΟΣ-STROVOLOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1013','no',N'Αγλαντζιά ή Αγλαγγιά-Aglantzia or Aglangia',N'ΑΓΛΑΝΤΖΙΆ Ή ΑΓΛΑΓΓΙΆ-AGLANTZIA OR AGLANGIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1014','no',N'Ορτάκιοϊ (Μιντζέλι)-Ortakioï (Mintzeli)',N'ΟΡΤΆΚΙΟΪ (ΜΙΝΤΖΈΛΙ)-ORTAKIOÏ (MINTZELI)');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1015','no',N'Τράχωνας-Trachonas',N'ΤΡΆΧΩΝΑΣ-TRACHONAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1021','no',N'Λακατάμεια-Lakatameia',N'ΛΑΚΑΤΆΜΕΙΑ-LAKATAMEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1022','no',N'Συνοικισμός Ανθούπολης-Synoikismos Anthoupolis',N'ΣΥΝΟΙΚΙΣΜΌΣ ΑΝΘΟΎΠΟΛΗΣ-SYNOIKISMOS ANTHOUPOLIS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1023','no',N'Λατσιά ή Λακκιά-Latsia or Lakkia',N'ΛΑΤΣΙΆ Ή ΛΑΚΚΙΆ-LATSIA OR LAKKIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1024','no',N'Γέρι-Geri',N'ΓΈΡΙ-GERI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1100','no',N'Σιά-Sia',N'ΣΙΆ-SIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1101','no',N'Μαθιάτης-Mathiatis',N'ΜΑΘΙΆΤΗΣ-MATHIATIS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1102','no',N'Αλάμπρα-Alampra',N'ΑΛΆΜΠΡΑ-ALAMPRA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1103','no',N'Αγία Βαρβάρα Λευκωσίας-Agia Varvara Lefkosias',N'ΑΓΊΑ ΒΑΡΒΆΡΑ ΛΕΥΚΩΣΊΑΣ-AGIA VARVARA LEFKOSIAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1104','no',N'Κοτσιάτης-Kotsiatis',N'ΚΟΤΣΙΆΤΗΣ-KOTSIATIS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1105','no',N'Νήσου-Nisou',N'ΝΉΣΟΥ-NISOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1106','no',N'Πέρα Χωριό-Pera Chorio',N'ΠΈΡΑ ΧΩΡΙΌ-PERA CHORIO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1107','no',N'Δάλι-Dali',N'ΔΆΛΙ-DALI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1108','no',N'Λύμπια-Lympia',N'ΛΎΜΠΙΑ-LYMPIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1109','no',N'Λυθροδόντας-Lythrodontas',N'ΛΥΘΡΟΔΌΝΤΑΣ-LYTHRODONTAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1110','no',N'Λουρουκίνα-Louroukina',N'ΛΟΥΡΟΥΚΊΝΑ-LOUROUKINA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1120','no',N'Ποταμιά-Potamia',N'ΠΟΤΑΜΙΆ-POTAMIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1121','no',N'''Αγιος Σωζόμενος-Agios Sozomenos',N'''ΑΓΙΟΣ ΣΩΖΌΜΕΝΟΣ-AGIOS SOZOMENOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1122','no',N'Πυρόγι-Pyrogi',N'ΠΥΡΌΓΙ-PYROGI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1123','no',N'Μαργό-Margo',N'ΜΑΡΓΌ-MARGO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1124','no',N'Αγιά (Aγιά Κεπίρ)-Agia (Agia Kepir)',N'ΑΓΙΆ (AΓΙΆ ΚΕΠΊΡ)-AGIA (AGIA KEPIR)');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1125','no',N'Τύμβου-Tymvou',N'ΤΎΜΒΟΥ-TYMVOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1130','no',N'Μόρα-Mora',N'ΜΌΡΑ-MORA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1131','no',N'Μια Μηλιά-Mia Milia',N'ΜΙΑ ΜΗΛΙΆ-MIA MILIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1132','no',N'Μάνδρες Λευκωσίας-Mandres Lefkosias',N'ΜΆΝΔΡΕΣ ΛΕΥΚΩΣΊΑΣ-MANDRES LEFKOSIAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1133','no',N'Παλαίκυθρο-Palaikythro',N'ΠΑΛΑΊΚΥΘΡΟ-PALAIKYTHRO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1134','no',N'''Εξω Μετόχι-Exo Metochi',N'''ΕΞΩ ΜΕΤΌΧΙ-EXO METOCHI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1135','no',N'Επιχό-Epicho',N'ΕΠΙΧΌ-EPICHO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1136','no',N'Βώνη-Voni',N'ΒΏΝΗ-VONI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1137','no',N'Τραχώνι Λευκωσίας-Trachoni Lefkosias',N'ΤΡΑΧΏΝΙ ΛΕΥΚΩΣΊΑΣ-TRACHONI LEFKOSIAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1138','no',N'Νέο Χωριό Λευκωσίας-Neo Chorio Lefkosias',N'ΝΈΟ ΧΩΡΙΌ ΛΕΥΚΩΣΊΑΣ-NEO CHORIO LEFKOSIAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1139','no',N'Κυθρέα-Kythrea',N'ΚΥΘΡΈΑ-KYTHREA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1141','no',N'Μπέϊκιοϊ-Beikioï',N'ΜΠΈΪΚΙΟΪ-BEIKIOÏ');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1142','no',N'Πέτρα του Διγενή-Petra tou Digeni',N'ΠΈΤΡΑ ΤΟΥ ΔΙΓΕΝΉ-PETRA TOU DIGENI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1143','no',N'Καλυβάκια-Kalyvakia',N'ΚΑΛΥΒΆΚΙΑ-KALYVAKIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1144','no',N'Κουρού Μοναστήρι-Kourou Monastiri',N'ΚΟΥΡΟΎ ΜΟΝΑΣΤΉΡΙ-KOUROU MONASTIRI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1200','no',N'Καμπί-Kampi',N'ΚΑΜΠΊ-KAMPI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1201','no',N'Φαρμακάς-Farmakas',N'ΦΑΡΜΑΚΆΣ-FARMAKAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1202','no',N'Απλίκι-Apliki',N'ΑΠΛΊΚΙ-APLIKI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1203','no',N'Λαζανιάς-Lazanias',N'ΛΑΖΑΝΙΆΣ-LAZANIAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1204','no',N'Γούρρη-Gourri',N'ΓΟΎΡΡΗ-GOURRI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1205','no',N'Φικάρδου-Fikardou',N'ΦΙΚΆΡΔΟΥ-FIKARDOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1206','no',N'Άγιος Επιφάνιος Ορεινής-Agios Epifanios Oreinis',N'ΆΓΙΟΣ ΕΠΙΦΆΝΙΟΣ ΟΡΕΙΝΉΣ-AGIOS EPIFANIOS OREINIS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1207','no',N'Καλό Χωριό Ορεινής-Kalo Chorio Oreinis',N'ΚΑΛΌ ΧΩΡΙΌ ΟΡΕΙΝΉΣ-KALO CHORIO OREINIS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1208','no',N'Μαλούντα-Malounta',N'ΜΑΛΟΎΝΤΑ-MALOUNTA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1209','no',N'Κλήρου-Klirou',N'ΚΛΉΡΟΥ-KLIROU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1210','no',N'Αρεδιού-Arediou',N'ΑΡΕΔΙΟΎ-AREDIOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1211','no',N'Άγιος Ιωάννης Μαλούντας-Agios Ioannis Malountas',N'ΆΓΙΟΣ ΙΩΆΝΝΗΣ ΜΑΛΟΎΝΤΑΣ-AGIOS IOANNIS MALOUNTAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1212','no',N'Αγροκηπιά-Agrokipia',N'ΑΓΡΟΚΗΠΙΆ-AGROKIPIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1213','no',N'Μιτσερό-Mitsero',N'ΜΙΤΣΕΡΌ-MITSERO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1220','no',N'Καπέδες-Kapedes',N'ΚΑΠΈΔΕΣ-KAPEDES');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1221','no',N'Καταλιόντας-Kataliontas',N'ΚΑΤΑΛΙΌΝΤΑΣ-KATALIONTAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1222','no',N'Αναλιόντας-Analiontas',N'ΑΝΑΛΙΌΝΤΑΣ-ANALIONTAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1223','no',N'Καμπιά-Kampia',N'ΚΑΜΠΙΆ-KAMPIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1224','no',N'Μαργί-Margi',N'ΜΑΡΓΊ-MARGI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1225','no',N'Τσέρι-Tseri',N'ΤΣΈΡΙ-TSERI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1226','no',N'Πολιτικό-Politiko',N'ΠΟΛΙΤΙΚΌ-POLITIKO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1227','no',N'Πέρα-Pera',N'ΠΈΡΑ-PERA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1228','no',N'Επισκοπειό-Episkopeio',N'ΕΠΙΣΚΟΠΕΙΌ-EPISKOPEIO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1229','no',N'Ψιμολόφου-Psimolofou',N'ΨΙΜΟΛΌΦΟΥ-PSIMOLOFOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1230','no',N'Εργάτες-Ergates',N'ΕΡΓΆΤΕΣ-ERGATES');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1231','no',N'Ανάγεια-Anageia',N'ΑΝΆΓΕΙΑ-ANAGEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1232','no',N'Πάνω Δευτερά-Pano Deftera',N'ΠΆΝΩ ΔΕΥΤΕΡΆ-PANO DEFTERA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1233','no',N'Κάτω Δευτερά-Kato Deftera',N'ΚΆΤΩ ΔΕΥΤΕΡΆ-KATO DEFTERA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1240','no',N'Άγιοι Τριμιθιάς-Agioi Trimithias',N'ΆΓΙΟΙ ΤΡΙΜΙΘΙΆΣ-AGIOI TRIMITHIAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1241','no',N'Παλαιομέτοχο-Palaiometocho',N'ΠΑΛΑΙΟΜΈΤΟΧΟ-PALAIOMETOCHO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1242','no',N'Δένεια-Deneia',N'ΔΈΝΕΙΑ-DENEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1243','no',N'Κοκκινοτριμιθιά-Kokkinotrimithia',N'ΚΟΚΚΙΝΟΤΡΙΜΙΘΙΆ-KOKKINOTRIMITHIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1244','no',N'Μάμμαρη-Mammari',N'ΜΆΜΜΑΡΗ-MAMMARI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1245','no',N'Γερόλακκος-Gerolakkos',N'ΓΕΡΌΛΑΚΚΟΣ-GEROLAKKOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1246','no',N'Αγία Μαρίνα Σκυλλούρας-Agia Marina Skyllouras',N'ΑΓΊΑ ΜΑΡΊΝΑ ΣΚΥΛΛΟΎΡΑΣ-AGIA MARINA SKYLLOURAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1247','no',N'Σκυλλούρα-Skylloura',N'ΣΚΥΛΛΟΎΡΑ-SKYLLOURA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1248','no',N'Άγιος Βασίλειος-Agios Vasileios',N'ΆΓΙΟΣ ΒΑΣΊΛΕΙΟΣ-AGIOS VASILEIOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1249','no',N'Δύο Ποταμοί-Dyo Potamoi',N'ΔΎΟ ΠΟΤΑΜΟΊ-DYO POTAMOI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1250','no',N'Κανλί (Κανλίκιογιου)-Kanli (Kanlikiogiou)',N'ΚΑΝΛΊ (ΚΑΝΛΊΚΙΟΓΙΟΥ)-KANLI (KANLIKIOGIOU)');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1251','no',N'Κιόνελι-Kioneli',N'ΚΙΌΝΕΛΙ-KIONELI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1300','no',N'Παλαιχώρι Μόρφου-Palaichori Morfou',N'ΠΑΛΑΙΧΏΡΙ ΜΌΡΦΟΥ-PALAICHORI MORFOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1301','no',N'Ασκάς-Askas',N'ΑΣΚΆΣ-ASKAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1302','no',N'Άλωνα-Alona',N'ΆΛΩΝΑ-ALONA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1303','no',N'Φτερικούδι-Fterikoudi',N'ΦΤΕΡΙΚΟΎΔΙ-FTERIKOUDI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1304','no',N'Πολύστυπος-Polystypos',N'ΠΟΛΎΣΤΥΠΟΣ-POLYSTYPOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1305','no',N'Λαγουδερά-Lagoudera',N'ΛΑΓΟΥΔΕΡΆ-LAGOUDERA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1306','no',N'Σαράντι-Saranti',N'ΣΑΡΆΝΤΙ-SARANTI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1307','no',N'Λιβάδια Λευκωσίας-Livadia Lefkosias',N'ΛΙΒΆΔΙΑ ΛΕΥΚΩΣΊΑΣ-LIVADIA LEFKOSIAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1308','no',N'Αληθινού-Alithinou',N'ΑΛΗΘΙΝΟΎ-ALITHINOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1309','no',N'Πλατανιστάσα-Platanistasa',N'ΠΛΑΤΑΝΙΣΤΆΣΑ-PLATANISTASA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1310','no',N'Παλαιχώρι Ορεινής-Palaichori Oreinis',N'ΠΑΛΑΙΧΏΡΙ ΟΡΕΙΝΉΣ-PALAICHORI OREINIS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1320','no',N'Ξυλιάτος-Xyliatos',N'ΞΥΛΙΆΤΟΣ-XYLIATOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1321','no',N'Άγιος Γεώργιος Καυκάλλου-Agios Georgios Kafkallou',N'ΆΓΙΟΣ ΓΕΏΡΓΙΟΣ ΚΑΥΚΆΛΛΟΥ-AGIOS GEORGIOS KAFKALLOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1322','no',N'Νικητάρι-Nikitari',N'ΝΙΚΗΤΆΡΙ-NIKITARI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1323','no',N'Βυζακιά-Vyzakia',N'ΒΥΖΑΚΙΆ-VYZAKIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1324','no',N'Αγία Μαρίνα Ξυλιάτου-Agia Marina Xyliatou',N'ΑΓΊΑ ΜΑΡΊΝΑ ΞΥΛΙΆΤΟΥ-AGIA MARINA XYLIATOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1325','no',N'Άγιοι Ηλιόφωτοι-Agioi Iliofotoi',N'ΆΓΙΟΙ ΗΛΙΌΦΩΤΟΙ-AGIOI ILIOFOTOI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1326','no',N'Κάτω Μονή-Kato Moni',N'ΚΆΤΩ ΜΟΝΉ-KATO MONI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1327','no',N'Ορούντα-Orounta',N'ΟΡΟΎΝΤΑ-OROUNTA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1328','no',N'Πάνω Κουτραφάς-Pano Koutrafas',N'ΠΆΝΩ ΚΟΥΤΡΑΦΆΣ-PANO KOUTRAFAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1329','no',N'Κάτω Κουτραφάς-Kato Koutrafas',N'ΚΆΤΩ ΚΟΥΤΡΑΦΆΣ-KATO KOUTRAFAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1330','no',N'Ποτάμι-Potami',N'ΠΟΤΆΜΙ-POTAMI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1340','no',N'Μόρφου-Morfou',N'ΜΌΡΦΟΥ-MORFOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1350','no',N'Πάνω Ζώδεια-Pano Zodeia',N'ΠΆΝΩ ΖΏΔΕΙΑ-PANO ZODEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1351','no',N'Κάτω Ζώδεια-Kato Zodeia',N'ΚΆΤΩ ΖΏΔΕΙΑ-KATO ZODEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1352','no',N'Καζιβερά-Kazivera',N'ΚΑΖΙΒΕΡΆ-KAZIVERA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1353','no',N'Πραστιό Λευκωσίας-Prastio Lefkosias',N'ΠΡΑΣΤΙΌ ΛΕΥΚΩΣΊΑΣ-PRASTIO LEFKOSIAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1354','no',N'Νικήτας-Nikitas',N'ΝΙΚΉΤΑΣ-NIKITAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1355','no',N'Συριανοχώρι-Syrianochori',N'ΣΥΡΙΑΝΟΧΏΡΙ-SYRIANOCHORI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1357','no',N'Καλό Χωριό Καπούτη-Kalo Chorio Kapouti',N'ΚΑΛΌ ΧΩΡΙΌ ΚΑΠΟΎΤΗ-KALO CHORIO KAPOUTI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1360','no',N'Ακάκι-Akaki',N'ΑΚΆΚΙ-AKAKI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1361','no',N'Περιστερώνα Λευκωσίας-Peristerona Lefkosias',N'ΠΕΡΙΣΤΕΡΏΝΑ ΛΕΥΚΩΣΊΑΣ-PERISTERONA LEFKOSIAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1362','no',N'Αστρομερίτης-Astromeritis',N'ΑΣΤΡΟΜΕΡΊΤΗΣ-ASTROMERITIS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1363','no',N'Αυλώνα-Avlona',N'ΑΥΛΏΝΑ-AVLONA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1364','no',N'Κατωκοπιά-Katokopia',N'ΚΑΤΩΚΟΠΙΆ-KATOKOPIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1365','no',N'Αργάκι-Argaki',N'ΑΡΓΆΚΙ-ARGAKI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1366','no',N'Μάσαρη-Masari',N'ΜΆΣΑΡΗ-MASARI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1367','no',N'Φυλλιά-Fyllia',N'ΦΥΛΛΙΆ-FYLLIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1368','no',N'Μένικο-Meniko',N'ΜΈΝΙΚΟ-MENIKO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1369','no',N'Κυρά-Kyra',N'ΚΥΡΆ-KYRA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1400','no',N'Σπήλια-Spilia',N'ΣΠΉΛΙΑ-SPILIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1402','no',N'Αγία Ειρήνη Λευκωσίας-Agia Eirini Lefkosias',N'ΑΓΊΑ ΕΙΡΉΝΗ ΛΕΥΚΩΣΊΑΣ-AGIA EIRINI LEFKOSIAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1403','no',N'Καννάβια-Kannavia',N'ΚΑΝΝΆΒΙΑ-KANNAVIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1404','no',N'Κακοπετριά-Kakopetria',N'ΚΑΚΟΠΕΤΡΙΆ-KAKOPETRIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1405','no',N'Άγιος Θεόδωρος Σολέας-Agios Theodoros Soleas',N'ΆΓΙΟΣ ΘΕΌΔΩΡΟΣ ΣΟΛΈΑΣ-AGIOS THEODOROS SOLEAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1406','no',N'Γαλάτα-Galata',N'ΓΑΛΆΤΑ-GALATA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1407','no',N'Σιναόρος-Sinaoros',N'ΣΙΝΑΌΡΟΣ-SINAOROS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1408','no',N'Καλιάνα-Kaliana',N'ΚΑΛΙΆΝΑ-KALIANA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1409','no',N'Τεμβριά-Temvria',N'ΤΕΜΒΡΙΆ-TEMVRIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1410','no',N'Κοράκου-Korakou',N'ΚΟΡΆΚΟΥ-KORAKOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1411','no',N'Ευρύχου-Evrychou',N'ΕΥΡΎΧΟΥ-EVRYCHOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1412','no',N'Φλάσου-Flasou',N'ΦΛΆΣΟΥ-FLASOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1414','no',N'Άγιος Επιφάνιος Σολέας-Agios Epifanios Soleas',N'ΆΓΙΟΣ ΕΠΙΦΆΝΙΟΣ ΣΟΛΈΑΣ-AGIOS EPIFANIOS SOLEAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1415','no',N'Ληνού-Linou',N'ΛΗΝΟΎ-LINOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1416','no',N'Κατύδατα-Katydata',N'ΚΑΤΎΔΑΤΑ-KATYDATA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1417','no',N'Σκουριώτισσα (Φουκάσα)-Skouriotissa (Foukasa)',N'ΣΚΟΥΡΙΏΤΙΣΣΑ (ΦΟΥΚΆΣΑ)-SKOURIOTISSA (FOUKASA)');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1420','no',N'Πεδουλάς-Pedoulas',N'ΠΕΔΟΥΛΆΣ-PEDOULAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1421','no',N'Μυλικούρι-Mylikouri',N'ΜΥΛΙΚΟΎΡΙ-MYLIKOURI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1422','no',N'Μουτουλλάς-Moutoullas',N'ΜΟΥΤΟΥΛΛΆΣ-MOUTOULLAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1423','no',N'Οίκος-Oikos',N'ΟΊΚΟΣ-OIKOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1424','no',N'Καλοπαναγιώτης-Kalopanagiotis',N'ΚΑΛΟΠΑΝΑΓΙΏΤΗΣ-KALOPANAGIOTIS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1425','no',N'Γερακιές-Gerakies',N'ΓΕΡΑΚΙΈΣ-GERAKIES');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1426','no',N'Τσακίστρα-Tsakistra',N'ΤΣΑΚΊΣΤΡΑ-TSAKISTRA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1427','no',N'Κάμπος-Kampos',N'ΚΆΜΠΟΣ-KAMPOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1430','no',N'Άγιος Νικόλαος Σολέας-Agios Nikolaos Soleas',N'ΆΓΙΟΣ ΝΙΚΌΛΑΟΣ ΣΟΛΈΑΣ-AGIOS NIKOLAOS SOLEAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1431','no',N'Άγιος Γεώργιος Σολέας-Agios Georgios Soleas',N'ΆΓΙΟΣ ΓΕΏΡΓΙΟΣ ΣΟΛΈΑΣ-AGIOS GEORGIOS SOLEAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1432','no',N'Πέτρα-Petra',N'ΠΈΤΡΑ-PETRA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1433','no',N'Καλό Χωριό Σολέας-Kalo Chorio Soleas',N'ΚΑΛΌ ΧΩΡΙΌ ΣΟΛΈΑΣ-KALO CHORIO SOLEAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1435','no',N'Λεύκα-Lefka',N'ΛΕΎΚΑ-LEFKA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1436','no',N'Αμπελικού-Ampelikou',N'ΑΜΠΕΛΙΚΟΎ-AMPELIKOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1437','no',N'Περιστερωνάρι-Peristeronari',N'ΠΕΡΙΣΤΕΡΩΝΆΡΙ-PERISTERONARI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1438','no',N'Ελιά Λευκωσίας-Elia Lefkosias',N'ΕΛΙΆ ΛΕΥΚΩΣΊΑΣ-ELIA LEFKOSIAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1439','no',N'Καραβοστάσι-Karavostasi',N'ΚΑΡΑΒΟΣΤΆΣΙ-KARAVOSTASI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1441','no',N'Πεντάγεια-Pentageia',N'ΠΕΝΤΆΓΕΙΑ-PENTAGEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1443','no',N'Αγγολέμι-Angolemi',N'ΑΓΓΟΛΈΜΙ-ANGOLEMI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1450','no',N'Βαρίσεια-Variseia',N'ΒΑΡΊΣΕΙΑ-VARISEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1451','no',N'Γαληνή-Galini',N'ΓΑΛΗΝΉ-GALINI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1452','no',N'Ξερόβουνος-Xerovounos',N'ΞΕΡΌΒΟΥΝΟΣ-XEROVOUNOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1453','no',N'Λουτρός-Loutros',N'ΛΟΥΤΡΌΣ-LOUTROS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1454','no',N'Άγιος Ιωάννης Σελέμανη-Agios Ioannis Selemani',N'ΆΓΙΟΣ ΙΩΆΝΝΗΣ ΣΕΛΈΜΑΝΗ-AGIOS IOANNIS SELEMANI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1455','no',N'Αμμαδιές-Ammadies',N'ΑΜΜΑΔΙΈΣ-AMMADIES');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1456','no',N'Πάνω Πύργος-Pano Pyrgos',N'ΠΆΝΩ ΠΎΡΓΟΣ-PANO PYRGOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1457','no',N'Κάτω Πύργος-Kato Pyrgos',N'ΚΆΤΩ ΠΎΡΓΟΣ-KATO PYRGOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1458','no',N'Σελλάδι του ''Αππη (και Άγιο Γεωργούδι)-Selladi tou Appi (and Agio Georgoudi)',N'ΣΕΛΛΆΔΙ ΤΟΥ ''ΑΠΠΗ (ΚΑΙ ΆΓΙΟ ΓΕΩΡΓΟΎΔΙ)-SELLADI TOU APPI (AND AGIO GEORGOUDI)');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1459','no',N'Αλεύγα-Alevga',N'ΑΛΕΎΓΑ-ALEVGA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1460','no',N'Πηγένια-Pigenia',N'ΠΗΓΈΝΙΑ-PIGENIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1461','no',N'Παχύαμμος-Pachyammos',N'ΠΑΧΎΑΜΜΟΣ-PACHYAMMOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1464','no',N'Κόκκινα-Kokkina',N'ΚΌΚΚΙΝΑ-KOKKINA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1465','no',N'Φροδίσια (Βροΐσια)-Frodisia (Vroisia)',N'ΦΡΟΔΊΣΙΑ (ΒΡΟΪ́ΣΙΑ)-FRODISIA (VROISIA)');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1466','no',N'Άγιος Θεόδωρος Τιλλιρίας-Agios Theodoros Tillirias',N'ΆΓΙΟΣ ΘΕΌΔΩΡΟΣ ΤΙΛΛΙΡΊΑΣ-AGIOS THEODOROS TILLIRIAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1467','no',N'Μανσούρα-Mansoura',N'ΜΑΝΣΟΎΡΑ-MANSOURA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','1468','no',N'Μοσφίλι-Mosfili',N'ΜΟΣΦΊΛΙ-MOSFILI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2000','no',N'Κερύνεια-Keryneia',N'ΚΕΡΎΝΕΙΑ-KERYNEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2100','no',N'Πάνω Δίκωμο-Pano Dikomo',N'ΠΆΝΩ ΔΊΚΩΜΟ-PANO DIKOMO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2101','no',N'Κάτω Δίκωμο-Kato Dikomo',N'ΚΆΤΩ ΔΊΚΩΜΟ-KATO DIKOMO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2102','no',N'Κουτσοβέντης-Koutsoventis',N'ΚΟΥΤΣΟΒΈΝΤΗΣ-KOUTSOVENTIS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2103','no',N'Βουνό-Vouno',N'ΒΟΥΝΌ-VOUNO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2104','no',N'Σιχαρί-Sichari',N'ΣΙΧΑΡΊ-SICHARI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2110','no',N'Φότα-Fota',N'ΦΌΤΑ-FOTA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2111','no',N'Κρηνί-Krini',N'ΚΡΗΝΊ-KRINI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2112','no',N'Πιλερί-Pileri',N'ΠΙΛΕΡΊ-PILERI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2113','no',N'Κιόμουρτζου-Kiomourtzou',N'ΚΙΌΜΟΥΡΤΖΟΥ-KIOMOURTZOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2114','no',N'Αγίρδα-Agirda',N'ΑΓΊΡΔΑ-AGIRDA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2120','no',N'Άγιος Ερμόλαος-Agios Ermolaos',N'ΆΓΙΟΣ ΕΡΜΌΛΑΟΣ-AGIOS ERMOLAOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2121','no',N'Σύσκληπος-Sysklipos',N'ΣΎΣΚΛΗΠΟΣ-SYSKLIPOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2122','no',N'Κοντεμένος-Kontemenos',N'ΚΟΝΤΕΜΈΝΟΣ-KONTEMENOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2123','no',N'Ασώματος Κερύνειας-Asomatos Keryneias',N'ΑΣΏΜΑΤΟΣ ΚΕΡΎΝΕΙΑΣ-ASOMATOS KERYNEIAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2124','no',N'Καμπυλή-Kampyli',N'ΚΑΜΠΥΛΉ-KAMPYLI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2125','no',N'Καρπάσεια-Karpaseia',N'ΚΑΡΠΆΣΕΙΑ-KARPASEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2126','no',N'Μύρτου-Myrtou',N'ΜΎΡΤΟΥ-MYRTOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2127','no',N'Διόριος-Diorios',N'ΔΙΌΡΙΟΣ-DIORIOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2128','no',N'Αγία Ειρήνη Κερύνειας-Agia Eirini Keryneias',N'ΑΓΊΑ ΕΙΡΉΝΗ ΚΕΡΎΝΕΙΑΣ-AGIA EIRINI KERYNEIAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2129','no',N'Κορμακίτης-Kormakitis',N'ΚΟΡΜΑΚΊΤΗΣ-KORMAKITIS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2130','no',N'Λιβερά-Livera',N'ΛΙΒΕΡΆ-LIVERA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2200','no',N'Καλογραία-Kalograia',N'ΚΑΛΟΓΡΑΊΑ-KALOGRAIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2201','no',N'Άγιος Αμβρόσιος Κερύνειας-Agios Amvrosios Keryneias',N'ΆΓΙΟΣ ΑΜΒΡΌΣΙΟΣ ΚΕΡΎΝΕΙΑΣ-AGIOS AMVROSIOS KERYNEIAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2202','no',N'Χάρκεια (Χάρτσεια)-Charkeia (Chartseia)',N'ΧΆΡΚΕΙΑ (ΧΆΡΤΣΕΙΑ)-CHARKEIA (CHARTSEIA)');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2203','no',N'Τραπέζα-Trapeza',N'ΤΡΑΠΈΖΑ-TRAPEZA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2204','no',N'Κλεπίνη-Klepini',N'ΚΛΕΠΊΝΗ-KLEPINI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2205','no',N'Άγιος Επίκτητος-Agios Epiktitos',N'ΆΓΙΟΣ ΕΠΊΚΤΗΤΟΣ-AGIOS EPIKTITOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2206','no',N'Μπέλαπαϊς-Belapais',N'ΜΠΈΛΑΠΑΪΣ-BELAPAIS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2207','no',N'Καζάφανι-Kazafani',N'ΚΑΖΆΦΑΝΙ-KAZAFANI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2208','no',N'Θέρμεια-Thermeia',N'ΘΈΡΜΕΙΑ-THERMEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2209','no',N'Καράκουμι-Karakoumi',N'ΚΑΡΆΚΟΥΜΙ-KARAKOUMI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2210','no',N'Τέμπλος-Templos',N'ΤΈΜΠΛΟΣ-TEMPLOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2211','no',N'Κάρμι-Karmi',N'ΚΆΡΜΙ-KARMI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2212','no',N'Φτέριχα-Ftericha',N'ΦΤΈΡΙΧΑ-FTERICHA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2213','no',N'Τριμίθι-Trimithi',N'ΤΡΙΜΊΘΙ-TRIMITHI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2214','no',N'Παλαιόσοφος-Palaiosofos',N'ΠΑΛΑΙΌΣΟΦΟΣ-PALAIOSOFOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2215','no',N'Μότηδες-Motides',N'ΜΌΤΗΔΕΣ-MOTIDES');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2216','no',N'Ελιά Κερύνειας-Elia Keryneias',N'ΕΛΙΆ ΚΕΡΎΝΕΙΑΣ-ELIA KERYNEIAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2217','no',N'Καραβάς-Karavas',N'ΚΑΡΑΒΆΣ-KARAVAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2218','no',N'Άγιος Γεώργιος Κερύνειας-Agios Georgios Keryneias',N'ΆΓΙΟΣ ΓΕΏΡΓΙΟΣ ΚΕΡΎΝΕΙΑΣ-AGIOS GEORGIOS KERYNEIAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2220','no',N'Αγριδάκι-Agridaki',N'ΑΓΡΙΔΆΚΙ-AGRIDAKI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2221','no',N'Λάρνακας Λαπήθου-Larnakas Lapithou',N'ΛΆΡΝΑΚΑΣ ΛΑΠΉΘΟΥ-LARNAKAS LAPITHOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2222','no',N'Λάπηθος-Lapithos',N'ΛΆΠΗΘΟΣ-LAPITHOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2223','no',N'Βασίλεια-Vasileia',N'ΒΑΣΊΛΕΙΑ-VASILEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2224','no',N'Πάναγρα-Panagra',N'ΠΆΝΑΓΡΑ-PANAGRA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','2226','no',N'Όργα-Orga',N'ΌΡΓΑ-ORGA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3000','no',N'Αμμόχωστος-Ammochostos',N'ΑΜΜΌΧΩΣΤΟΣ-AMMOCHOSTOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3100','no',N'Αγία Νάπα-Agia Napa',N'ΑΓΊΑ ΝΆΠΑ-AGIA NAPA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3101','no',N'Παραλίμνι-Paralimni',N'ΠΑΡΑΛΊΜΝΙ-PARALIMNI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3102','no',N'Δερύνεια-Deryneia',N'ΔΕΡΎΝΕΙΑ-DERYNEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3103','no',N'Σωτήρα Αμμοχώστου-Sotira Ammochostou',N'ΣΩΤΉΡΑ ΑΜΜΟΧΏΣΤΟΥ-SOTIRA AMMOCHOSTOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3104','no',N'Λιοπέτρι-Liopetri',N'ΛΙΟΠΈΤΡΙ-LIOPETRI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3105','no',N'Φρέναρος-Frenaros',N'ΦΡΈΝΑΡΟΣ-FRENAROS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3110','no',N'Αυγόρου-Avgorou',N'ΑΥΓΌΡΟΥ-AVGOROU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3111','no',N'Άχνα-Achna',N'ΆΧΝΑ-ACHNA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3112','no',N'Μακράσυκα-Makrasyka',N'ΜΑΚΡΆΣΥΚΑ-MAKRASYKA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3113','no',N'Καλοψίδα-Kalopsida',N'ΚΑΛΟΨΊΔΑ-KALOPSIDA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3114','no',N'Αχερίτου-Acheritou',N'ΑΧΕΡΊΤΟΥ-ACHERITOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3120','no',N'Έγκωμη Αμμοχώστου-Egkomi Ammochostou',N'ΈΓΚΩΜΗ ΑΜΜΟΧΏΣΤΟΥ-EGKOMI AMMOCHOSTOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3121','no',N'Άγιος Σέργιος-Agios Sergios',N'ΆΓΙΟΣ ΣΈΡΓΙΟΣ-AGIOS SERGIOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3122','no',N'Στύλλοι-Stylloi',N'ΣΤΎΛΛΟΙ-STYLLOI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3123','no',N'Λιμνιά-Limnia',N'ΛΙΜΝΙΆ-LIMNIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3124','no',N'Αλόδα-Aloda',N'ΑΛΌΔΑ-ALODA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3130','no',N'Σπαθαρικό-Spathariko',N'ΣΠΑΘΑΡΙΚΌ-SPATHARIKO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3131','no',N'Αρναδί-Arnadi',N'ΑΡΝΑΔΊ-ARNADI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3132','no',N'Άγιος Γεώργιος Αμμοχώστου-Agios Georgios Ammochostou',N'ΆΓΙΟΣ ΓΕΏΡΓΙΟΣ ΑΜΜΟΧΏΣΤΟΥ-AGIOS GEORGIOS AMMOCHOSTOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3133','no',N'Περιβόλια Τρικώμου-Perivolia Trikomou',N'ΠΕΡΙΒΌΛΙΑ ΤΡΙΚΏΜΟΥ-PERIVOLIA TRIKOMOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3134','no',N'Σύγκραση-Sygkrasi',N'ΣΎΓΚΡΑΣΗ-SYGKRASI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3135','no',N'Λάπαθος-Lapathos',N'ΛΆΠΑΘΟΣ-LAPATHOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3136','no',N'Τρίκωμο-Trikomo',N'ΤΡΊΚΩΜΟ-TRIKOMO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3200','no',N'Κούκλια Αμμοχώστου-Kouklia Ammochostou',N'ΚΟΎΚΛΙΑ ΑΜΜΟΧΏΣΤΟΥ-KOUKLIA AMMOCHOSTOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3201','no',N'Κοντέα-Kontea',N'ΚΟΝΤΈΑ-KONTEA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3202','no',N'Λύση-Lysi',N'ΛΎΣΗ-LYSI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3203','no',N'Βατιλή-Vatili',N'ΒΑΤΙΛΉ-VATILI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3204','no',N'Στρογγυλός-Strongylos',N'ΣΤΡΟΓΓΥΛΌΣ-STRONGYLOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3205','no',N'Σίντα-Sinta',N'ΣΊΝΤΑ-SINTA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3210','no',N'Γαϊδουράς (Νέα Σπάρτη)-Gaidouras (Nea Sparti)',N'ΓΑΪΔΟΥΡΆΣ (ΝΈΑ ΣΠΆΡΤΗ)-GAIDOURAS (NEA SPARTI)');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3211','no',N'Πραστιό Αμμοχώστου-Prastio Ammochostou',N'ΠΡΑΣΤΙΌ ΑΜΜΟΧΏΣΤΟΥ-PRASTIO AMMOCHOSTOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3212','no',N'Πυργά (η) Αμμοχώστου-Pyrga Ammochostou',N'ΠΥΡΓΆ (Η) ΑΜΜΟΧΏΣΤΟΥ-PYRGA AMMOCHOSTOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3213','no',N'Μουσουλίτα-Mousoulita',N'ΜΟΥΣΟΥΛΊΤΑ-MOUSOULITA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3214','no',N'Σανταλάρης-Santalaris',N'ΣΑΝΤΑΛΆΡΗΣ-SANTALARIS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3215','no',N'Μαράθα-Maratha',N'ΜΑΡΆΘΑ-MARATHA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3216','no',N'Περιστερώνα Αμμοχώστου-Peristerona Ammochostou',N'ΠΕΡΙΣΤΕΡΏΝΑ ΑΜΜΟΧΏΣΤΟΥ-PERISTERONA AMMOCHOSTOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3217','no',N'Πηγή-Pigi',N'ΠΗΓΉ-PIGI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3218','no',N'Γέναγρα-Genagra',N'ΓΈΝΑΓΡΑ-GENAGRA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3219','no',N'Μηλιά Αμμοχώστου-Milia Ammochostou',N'ΜΗΛΙΆ ΑΜΜΟΧΏΣΤΟΥ-MILIA AMMOCHOSTOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3220','no',N'Γύψου-Gypsou',N'ΓΎΨΟΥ-GYPSOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3221','no',N'Λευκόνοικο-Lefkonoiko',N'ΛΕΥΚΌΝΟΙΚΟ-LEFKONOIKO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3222','no',N'Ψυλλάτος-Psyllatos',N'ΨΥΛΛΆΤΟΣ-PSYLLATOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3223','no',N'Κνώδαρα-Knodara',N'ΚΝΏΔΑΡΑ-KNODARA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3224','no',N'Γούφες-Goufes',N'ΓΟΎΦΕΣ-GOUFES');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3231','no',N'Άσκεια (Άσσεια)-Askeia (Αsseia)',N'ΆΣΚΕΙΑ (ΆΣΣΕΙΑ)-ASKEIA (ΑSSEIA)');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3232','no',N'Αφάντεια-Ορνίθι-Afanteia-Ornithi',N'ΑΦΆΝΤΕΙΑ-ΟΡΝΊΘΙ-AFANTEIA-ORNITHI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3233','no',N'Αγγαστίνα-Angastina',N'ΑΓΓΑΣΤΊΝΑ-ANGASTINA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3234','no',N'Μαραθόβουνος-Marathovounos',N'ΜΑΡΑΘΌΒΟΥΝΟΣ-MARATHOVOUNOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3235','no',N'Βιτσάδα-Vitsada',N'ΒΙΤΣΆΔΑ-VITSADA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3236','no',N'Κίαδος (Τζιάος)-Kiados (Tziaos)',N'ΚΊΑΔΟΣ (ΤΖΙΆΟΣ)-KIADOS (TZIAOS)');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3237','no',N'Κορνόκηπος-Kornokipos',N'ΚΟΡΝΌΚΗΠΟΣ-KORNOKIPOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3238','no',N'Άγιος Χαρίτων-Agios Chariton',N'ΆΓΙΟΣ ΧΑΡΊΤΩΝ-AGIOS CHARITON');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3239','no',N'Τρυπημένη-Trypimeni',N'ΤΡΥΠΗΜΈΝΗ-TRYPIMENI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3300','no',N'Άρτεμι-Artemi',N'ΆΡΤΕΜΙ-ARTEMI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3301','no',N'Άγιος Νικόλαος Αμμοχώστου-Agios Nikolaos Ammochostou',N'ΆΓΙΟΣ ΝΙΚΌΛΑΟΣ ΑΜΜΟΧΏΣΤΟΥ-AGIOS NIKOLAOS AMMOCHOSTOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3303','no',N'Πλατάνι-Platani',N'ΠΛΑΤΆΝΙ-PLATANI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3304','no',N'Ακανθού-Akanthou',N'ΑΚΑΝΘΟΎ-AKANTHOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3305','no',N'Μελούντα-Melounta',N'ΜΕΛΟΎΝΤΑ-MELOUNTA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3310','no',N'Άγιος Ιάκωβος-Agios Iakovos',N'ΆΓΙΟΣ ΙΆΚΩΒΟΣ-AGIOS IAKOVOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3311','no',N'Άγιος Ανδρόνικος Tρικώμου (Τοπσούκιογιου ή Άγιο Ανδρονικούδι)-Agios Andronikos Trikomou (Topsoukiogiou or Agio Andronikoudi)',N'ΆΓΙΟΣ ΑΝΔΡΌΝΙΚΟΣ TΡΙΚΏΜΟΥ (ΤΟΠΣΟΎΚΙΟΓΙΟΥ Ή ΆΓΙΟ ΑΝΔΡΟΝΙΚΟΎΔΙ)-AGIOS ANDRONIKOS TRIKOMOU (TOPSOUKIOGIOU OR AGIO ANDRONIKOUDI)');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3312','no',N'Μάνδρες Αμμοχώστου-Mandres Ammochostou',N'ΜΆΝΔΡΕΣ ΑΜΜΟΧΏΣΤΟΥ-MANDRES AMMOCHOSTOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3313','no',N'Άρδανα-Ardana',N'ΆΡΔΑΝΑ-ARDANA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3314','no',N'Φλαμούδι-Flamoudi',N'ΦΛΑΜΟΎΔΙ-FLAMOUDI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3320','no',N'Μπογάζι-Bogazi',N'ΜΠΟΓΆΖΙ-BOGAZI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3321','no',N'Μοναργά-Monarga',N'ΜΟΝΑΡΓΆ-MONARGA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3322','no',N'Άγιος Ηλίας-Agios Ilias',N'ΆΓΙΟΣ ΗΛΊΑΣ-AGIOS ILIAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3323','no',N'Γαστριά-Gastria',N'ΓΑΣΤΡΙΆ-GASTRIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3324','no',N'Αυγολίδα-Avgolida',N'ΑΥΓΟΛΊΔΑ-AVGOLIDA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3325','no',N'Πατρίκι-Patriki',N'ΠΑΤΡΊΚΙ-PATRIKI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3326','no',N'Γεράνι-Gerani',N'ΓΕΡΆΝΙ-GERANI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3327','no',N'Όβγορος-Ovgoros',N'ΌΒΓΟΡΟΣ-OVGOROS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3328','no',N'Δαυλός-Davlos',N'ΔΑΥΛΌΣ-DAVLOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3330','no',N'Άγιος Θεόδωρος Αμμοχώστου-Agios Theodoros Ammochostou',N'ΆΓΙΟΣ ΘΕΌΔΩΡΟΣ ΑΜΜΟΧΏΣΤΟΥ-AGIOS THEODOROS AMMOCHOSTOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3331','no',N'Βοκολίδα-Vokolida',N'ΒΟΚΟΛΊΔΑ-VOKOLIDA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3332','no',N'Ταύρου-Tavrou',N'ΤΑΎΡΟΥ-TAVROU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3333','no',N'Άγιος Ευστάθιος-Agios Efstathios',N'ΆΓΙΟΣ ΕΥΣΤΆΘΙΟΣ-AGIOS EFSTATHIOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3334','no',N'Λιβάδια Αμμοχώστου-Livadia Ammochostou',N'ΛΙΒΆΔΙΑ ΑΜΜΟΧΏΣΤΟΥ-LIVADIA AMMOCHOSTOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3335','no',N'Κρίδεια-Krideia',N'ΚΡΊΔΕΙΑ-KRIDEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3336','no',N'Κώμη (Κώμη Κεπίρ)-Komi (Komi Kepir)',N'ΚΏΜΗ (ΚΏΜΗ ΚΕΠΊΡ)-KOMI (KOMI KEPIR)');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3337','no',N'Γαλάτεια-Galateia',N'ΓΑΛΆΤΕΙΑ-GALATEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3338','no',N'Επτακώμη-Eptakomi',N'ΕΠΤΑΚΏΜΗ-EPTAKOMI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3340','no',N'Κώμα του Γιαλού-Koma tou Gialou',N'ΚΏΜΑ ΤΟΥ ΓΙΑΛΟΎ-KOMA TOU GIALOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3341','no',N'Νέτα-Neta',N'ΝΈΤΑ-NETA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3342','no',N'Βοθύλακας-Vοthylakas',N'ΒΟΘΎΛΑΚΑΣ-VΟTHYLAKAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3343','no',N'Λυθράγκωμη-Lythragkomi',N'ΛΥΘΡΆΓΚΩΜΗ-LYTHRAGKOMI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3344','no',N'Βασίλι-Vasili',N'ΒΑΣΊΛΙ-VASILI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3345','no',N'Λεονάρισσο-Leonarisso',N'ΛΕΟΝΆΡΙΣΣΟ-LEONARISSO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3346','no',N'Πλατανισσός-Platanissos',N'ΠΛΑΤΑΝΙΣΣΌΣ-PLATANISSOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3347','no',N'Κοιλάνεμος-Koilanemos',N'ΚΟΙΛΆΝΕΜΟΣ-KOILANEMOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3348','no',N'Άγιος Ανδρόνικος Καρπασίας-Agios Andronikos Karpasias',N'ΆΓΙΟΣ ΑΝΔΡΌΝΙΚΟΣ ΚΑΡΠΑΣΊΑΣ-AGIOS ANDRONIKOS KARPASIAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3350','no',N'Άγιος Συμεών-Agios Symeon',N'ΆΓΙΟΣ ΣΥΜΕΏΝ-AGIOS SYMEON');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3351','no',N'Μελάναργα-Melanarga',N'ΜΕΛΆΝΑΡΓΑ-MELANARGA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3352','no',N'Αιγιαλούσα-Aigialousa',N'ΑΙΓΙΑΛΟΎΣΑ-AIGIALOUSA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3353','no',N'Αγία Τριάς-Agia Trias',N'ΑΓΊΑ ΤΡΙΆΣ-AGIA TRIAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3354','no',N'Κορόβεια-Koroveia',N'ΚΟΡΌΒΕΙΑ-KOROVEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3355','no',N'Γαληνόπωρνη-Galinoporni',N'ΓΑΛΗΝΌΠΩΡΝΗ-GALINOPORNI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','3356','no',N'Ριζοκάρπασο-Rizokarpaso',N'ΡΙΖΟΚΆΡΠΑΣΟ-RIZOKARPASO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4000','no',N'Λάρνακα-Larnaka',N'ΛΆΡΝΑΚΑ-LARNAKA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4010','no',N'Αραδίππου-Aradippou',N'ΑΡΑΔΊΠΠΟΥ-ARADIPPOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4011','no',N'Λιβάδια Λάρνακας-Livadia Larnakas',N'ΛΙΒΆΔΙΑ ΛΆΡΝΑΚΑΣ-LIVADIA LARNAKAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4014','no',N'Δρομολαξιά -Μενεού-Dromolaxia - Meneou',N'ΔΡΟΜΟΛΑΞΙΆ -ΜΕΝΕΟΎ-DROMOLAXIA - MENEOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4100','no',N'Κελλιά-Kellia',N'ΚΕΛΛΙΆ-KELLIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4101','no',N'Τρούλλοι-Troulloi',N'ΤΡΟΎΛΛΟΙ-TROULLOI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4102','no',N'Bορόκληνη (Ορόκληνη)-Voroklini (Oroklini)',N'BΟΡΌΚΛΗΝΗ (ΟΡΌΚΛΗΝΗ)-VOROKLINI (OROKLINI)');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4103','no',N'Αβδελλερό-Avdellero',N'ΑΒΔΕΛΛΕΡΌ-AVDELLERO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4104','no',N'Πύλα-Pyla',N'ΠΎΛΑ-PYLA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4105','no',N'Ξυλοτύμβου-Xylotymvou',N'ΞΥΛΟΤΎΜΒΟΥ-XYLOTYMVOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4106','no',N'Ορμίδεια-Ormideia',N'ΟΡΜΊΔΕΙΑ-ORMIDEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4107','no',N'Ξυλοφάγου-Xylofagou',N'ΞΥΛΟΦΆΓΟΥ-XYLOFAGOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4108','no',N'Πέργαμος-Pergamos',N'ΠΈΡΓΑΜΟΣ-PERGAMOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4110','no',N'Κίτι-Kiti',N'ΚΊΤΙ-KITI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4111','no',N'Περιβόλια Λάρνακας-Perivolia Larnakas',N'ΠΕΡΙΒΌΛΙΑ ΛΆΡΝΑΚΑΣ-PERIVOLIA LARNAKAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4112','no',N'Τερσεφάνου-Tersefanou',N'ΤΕΡΣΕΦΆΝΟΥ-TERSEFANOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4113','no',N'Σοφτάδες-Softades',N'ΣΟΦΤΆΔΕΣ-SOFTADES');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4120','no',N'Μαζωτός-Mazotos',N'ΜΑΖΩΤΌΣ-MAZOTOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4121','no',N'Αλαμινός-Alaminos',N'ΑΛΑΜΙΝΌΣ-ALAMINOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4122','no',N'Αναφωτίδα-Anafotida',N'ΑΝΑΦΩΤΊΔΑ-ANAFOTIDA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4123','no',N'Απλάντα-Aplanta',N'ΑΠΛΆΝΤΑ-APLANTA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4124','no',N'Κιβισίλι-Kivisili',N'ΚΙΒΙΣΊΛΙ-KIVISILI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4125','no',N'Αλεθρικό-Alethriko',N'ΑΛΕΘΡΙΚΌ-ALETHRIKO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4126','no',N'Κλαυδιά-Klavdia',N'ΚΛΑΥΔΙΆ-KLAVDIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4127','no',N'Αγγλισίδες-Anglisides',N'ΑΓΓΛΙΣΊΔΕΣ-ANGLISIDES');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4128','no',N'Μενόγεια-Menogeia',N'ΜΕΝΌΓΕΙΑ-MENOGEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4201','no',N'Πετροφάνι-Petrofani',N'ΠΕΤΡΟΦΆΝΙ-PETROFANI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4202','no',N'Αθιένου-Athienou',N'ΑΘΙΈΝΟΥ-ATHIENOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4203','no',N'Μελούσεια-Melouseia',N'ΜΕΛΟΎΣΕΙΑ-MELOUSEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4204','no',N'Τρεμετουσιά-Tremetousia',N'ΤΡΕΜΕΤΟΥΣΙΆ-TREMETOUSIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4205','no',N'Άρσος Λάρνακας-Arsos Larnakas',N'ΆΡΣΟΣ ΛΆΡΝΑΚΑΣ-ARSOS LARNAKAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4210','no',N'Καλό Χωριό Λάρνακας-Kalo Chorio Larnakas',N'ΚΑΛΌ ΧΩΡΙΌ ΛΆΡΝΑΚΑΣ-KALO CHORIO LARNAKAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4211','no',N'Αγία Άννα-Agia Anna',N'ΑΓΊΑ ΆΝΝΑ-AGIA ANNA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4212','no',N'Μοσφιλωτή-Mosfiloti',N'ΜΟΣΦΙΛΩΤΉ-MOSFILOTI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4213','no',N'Ψευδάς-Psevdas',N'ΨΕΥΔΆΣ-PSEVDAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4214','no',N'Πυργά (τα) Λάρνακας-Pyrga Larnakas',N'ΠΥΡΓΆ (ΤΑ) ΛΆΡΝΑΚΑΣ-PYRGA LARNAKAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4215','no',N'Κόρνος-Kornos',N'ΚΌΡΝΟΣ-KORNOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4216','no',N'Δελίκηπος-Delikipos',N'ΔΕΛΊΚΗΠΟΣ-DELIKIPOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4217','no',N'Κόση-Kosi',N'ΚΌΣΗ-KOSI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4300','no',N'Ζύγι-Zygi',N'ΖΎΓΙ-ZYGI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4301','no',N'Μαρί-Mari',N'ΜΑΡΊ-MARI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4302','no',N'Καλαβασός-Kalavasos',N'ΚΑΛΑΒΑΣΌΣ-KALAVASOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4303','no',N'Τόχνη-Tochni',N'ΤΌΧΝΗ-TOCHNI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4304','no',N'Χοιροκoιτία-Choirokoitia',N'ΧΟΙΡΟΚOΙΤΊΑ-CHOIROKOITIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4305','no',N'Ψεματισμένος-Psematismenos',N'ΨΕΜΑΤΙΣΜΈΝΟΣ-PSEMATISMENOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4306','no',N'Μαρώνι-Maroni',N'ΜΑΡΏΝΙ-MARONI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4307','no',N'Άγιος Θεόδωρος Λάρνακας-Agios Theodoros Larnakas',N'ΆΓΙΟΣ ΘΕΌΔΩΡΟΣ ΛΆΡΝΑΚΑΣ-AGIOS THEODOROS LARNAKAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4308','no',N'Σκαρίνου-Skarinou',N'ΣΚΑΡΊΝΟΥ-SKARINOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4309','no',N'Κοφίνου-Kofinou',N'ΚΟΦΊΝΟΥ-KOFINOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4310','no',N'Κάτω Λεύκαρα-Kato Lefkara',N'ΚΆΤΩ ΛΕΎΚΑΡΑ-KATO LEFKARA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4311','no',N'Πάνω Λεύκαρα-Pano Lefkara',N'ΠΆΝΩ ΛΕΎΚΑΡΑ-PANO LEFKARA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4312','no',N'Κάτω Δρυς-Kato Drys',N'ΚΆΤΩ ΔΡΥΣ-KATO DRYS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4313','no',N'Βάβλα-Vavla',N'ΒΆΒΛΑ-VAVLA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4314','no',N'Λάγεια-Lageia',N'ΛΆΓΕΙΑ-LAGEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4315','no',N'Ορά-Ora',N'ΟΡΆ-ORA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4316','no',N'Μελίνη-Melini',N'ΜΕΛΊΝΗ-MELINI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4317','no',N'Οδού-Odou',N'ΟΔΟΎ-ODOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4318','no',N'Άγιοι Βαβατσινιάς-Agioi Vavatsinias',N'ΆΓΙΟΙ ΒΑΒΑΤΣΙΝΙΆΣ-AGIOI VAVATSINIAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','4319','no',N'Βαβατσινιά-Vavatsinia',N'ΒΑΒΑΤΣΙΝΙΆ-VAVATSINIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5000','no',N'Λεμεσός-Lemesos',N'ΛΕΜΕΣΌΣ-LEMESOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5011','no',N'Μέσα Γειτονιά-Mesa Geitonia',N'ΜΈΣΑ ΓΕΙΤΟΝΙΆ-MESA GEITONIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5012','no',N'Άγιος Αθανάσιος-Agios Athanasios',N'ΆΓΙΟΣ ΑΘΑΝΆΣΙΟΣ-AGIOS ATHANASIOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5013','no',N'Γερμασόγεια-Germasogeia',N'ΓΕΡΜΑΣΌΓΕΙΑ-GERMASOGEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5020','no',N'Πάνω Πολεμίδια-Pano Polemidia',N'ΠΆΝΩ ΠΟΛΕΜΊΔΙΑ-PANO POLEMIDIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5021','no',N'''Υψωνας-Ypsonas',N'''ΥΨΩΝΑΣ-YPSONAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5022','no',N'Κάτω Πολεμίδια-Kato Polemidia',N'ΚΆΤΩ ΠΟΛΕΜΊΔΙΑ-KATO POLEMIDIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5100','no',N'Παλόδεια-Palodeia',N'ΠΑΛΌΔΕΙΑ-PALODEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5101','no',N'Παραμύθα-Paramytha',N'ΠΑΡΑΜΎΘΑ-PARAMYTHA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5102','no',N'Σπιτάλι-Spitali',N'ΣΠΙΤΆΛΙ-SPITALI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5103','no',N'Φασούλα Λεμεσού-Fasoula Lemesou',N'ΦΑΣΟΎΛΑ ΛΕΜΕΣΟΎ-FASOULA LEMESOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5104','no',N'Μαθικολώνη-Mathikoloni',N'ΜΑΘΙΚΟΛΏΝΗ-MATHIKOLONI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5105','no',N'Γεράσα-Gerasa',N'ΓΕΡΆΣΑ-GERASA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5106','no',N'Αψιού-Apsiou',N'ΑΨΙΟΎ-APSIOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5107','no',N'Απεσιά-Apesia',N'ΑΠΕΣΙΆ-APESIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5108','no',N'Κορφή-Korfi',N'ΚΟΡΦΉ-KORFI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5109','no',N'Λιμνάτης-Limnatis',N'ΛΙΜΝΆΤΗΣ-LIMNATIS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5110','no',N'Καπηλειό-Kapileio',N'ΚΑΠΗΛΕΙΌ-KAPILEIO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5120','no',N'Μουτταγιάκα-Mouttagiaka',N'ΜΟΥΤΤΑΓΙΆΚΑ-MOUTTAGIAKA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5121','no',N'Αρμενοχώρι-Armenochori',N'ΑΡΜΕΝΟΧΏΡΙ-ARMENOCHORI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5122','no',N'Φοινικάρια-Foinikaria',N'ΦΟΙΝΙΚΆΡΙΑ-FOINIKARIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5123','no',N'Ακρούντα-Akrounta',N'ΑΚΡΟΎΝΤΑ-AKROUNTA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5124','no',N'Άγιος Τύχων-Agios Tychon',N'ΆΓΙΟΣ ΤΎΧΩΝ-AGIOS TYCHON');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5125','no',N'Παρεκκλησιά-Parekklisia',N'ΠΑΡΕΚΚΛΗΣΙΆ-PAREKKLISIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5126','no',N'Πεντάκωμο-Pentakomo',N'ΠΕΝΤΆΚΩΜΟ-PENTAKOMO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5127','no',N'Μοναγρούλλι-Monagroulli',N'ΜΟΝΑΓΡΟΎΛΛΙ-MONAGROULLI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5128','no',N'Μονή-Moni',N'ΜΟΝΉ-MONI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5129','no',N'Πύργος Λεμεσού-Pyrgos Lemesou',N'ΠΎΡΓΟΣ ΛΕΜΕΣΟΎ-PYRGOS LEMESOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5130','no',N'Ασγάτα-Asgata',N'ΑΣΓΆΤΑ-ASGATA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5131','no',N'Βάσα Κελλακίου-Vasa Kellakiou',N'ΒΆΣΑ ΚΕΛΛΑΚΊΟΥ-VASA KELLAKIOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5132','no',N'Σανίδα-Sanida',N'ΣΑΝΊΔΑ-SANIDA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5133','no',N'Πραστιό Κελλακίου-Prastio Kellakiou',N'ΠΡΑΣΤΙΌ ΚΕΛΛΑΚΊΟΥ-PRASTIO KELLAKIOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5134','no',N'Κλωνάρι-Klonari',N'ΚΛΩΝΆΡΙ-KLONARI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5135','no',N'Βίκλα-Vikla',N'ΒΊΚΛΑ-VIKLA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5136','no',N'Κελλάκι-Kellaki',N'ΚΕΛΛΆΚΙ-KELLAKI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5137','no',N'Ακαπνού-Akapnou',N'ΑΚΑΠΝΟΎ-AKAPNOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5138','no',N'Επταγώνεια-Eptagoneia',N'ΕΠΤΑΓΏΝΕΙΑ-EPTAGONEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5140','no',N'Διερώνα-Dierona',N'ΔΙΕΡΏΝΑ-DIERONA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5141','no',N'Αρακαπάς-Arakapas',N'ΑΡΑΚΑΠΆΣ-ARAKAPAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5142','no',N'Άγιος Παύλος-Agios Pavlos',N'ΆΓΙΟΣ ΠΑΎΛΟΣ-AGIOS PAVLOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5143','no',N'Άγιος Κωνσταντίνος-Agios Konstantinos',N'ΆΓΙΟΣ ΚΩΝΣΤΑΝΤΊΝΟΣ-AGIOS KONSTANTINOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5144','no',N'Συκόπετρα-Sykopetra',N'ΣΥΚΌΠΕΤΡΑ-SYKOPETRA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5145','no',N'Λουβαράς-Louvaras',N'ΛΟΥΒΑΡΆΣ-LOUVARAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5146','no',N'Καλό Χωριό Λεμεσού-Kalo Chorio Lemesou',N'ΚΑΛΌ ΧΩΡΙΌ ΛΕΜΕΣΟΎ-KALO CHORIO LEMESOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5147','no',N'Ζωοπηγή-Zoopigi',N'ΖΩΟΠΗΓΉ-ZOOPIGI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5200','no',N'Ακρωτήρι-Akrotiri',N'ΑΚΡΩΤΉΡΙ-AKROTIRI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5201','no',N'Ασώματος Λεμεσού-Asomatos Lemesou',N'ΑΣΏΜΑΤΟΣ ΛΕΜΕΣΟΎ-ASOMATOS LEMESOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5202','no',N'Τσερκέζοι-Tserkezoi',N'ΤΣΕΡΚΈΖΟΙ-TSERKEZOI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5203','no',N'Τραχώνι Λεμεσού-Trachoni Lemesou',N'ΤΡΑΧΏΝΙ ΛΕΜΕΣΟΎ-TRACHONI LEMESOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5210','no',N'Κολόσσι-Kolossi',N'ΚΟΛΌΣΣΙ-KOLOSSI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5211','no',N'Ερήμη-Erimi',N'ΕΡΉΜΗ-ERIMI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5212','no',N'Επισκοπή Λεμεσού-Episkopi Lemesou',N'ΕΠΙΣΚΟΠΉ ΛΕΜΕΣΟΎ-EPISKOPI LEMESOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5213','no',N'Καντού-Kantou',N'ΚΑΝΤΟΎ-KANTOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5214','no',N'Σωτήρα Λεμεσού-Sotira Lemesou',N'ΣΩΤΉΡΑ ΛΕΜΕΣΟΎ-SOTIRA LEMESOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5220','no',N'Πραστιό Αυδήμου-Prastio Avdimou',N'ΠΡΑΣΤΙΌ ΑΥΔΉΜΟΥ-PRASTIO AVDIMOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5221','no',N'Παραμάλι-Paramali',N'ΠΑΡΑΜΆΛΙ-PARAMALI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5222','no',N'Αυδήμου-Avdimou',N'ΑΥΔΉΜΟΥ-AVDIMOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5223','no',N'Πλατανίστεια-Platanisteia',N'ΠΛΑΤΑΝΊΣΤΕΙΑ-PLATANISTEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5224','no',N'Άγιος Θωμάς-Agios Thomas',N'ΆΓΙΟΣ ΘΩΜΆΣ-AGIOS THOMAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5225','no',N'Αλέκτορα-Alektora',N'ΑΛΈΚΤΟΡΑ-ALEKTORA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5226','no',N'Ανώγυρα-Anogyra',N'ΑΝΏΓΥΡΑ-ANOGYRA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5227','no',N'Πισσούρι-Pissouri',N'ΠΙΣΣΟΎΡΙ-PISSOURI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5300','no',N'Σούνι-Ζανακιά-Souni-Zanakia',N'ΣΟΎΝΙ-ΖΑΝΑΚΙΆ-SOUNI-ZANAKIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5302','no',N'Άλασσα-Alassa',N'ΆΛΑΣΣΑ-ALASSA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5303','no',N'Κάτω Κιβίδες-Kato Kivides',N'ΚΆΤΩ ΚΙΒΊΔΕΣ-KATO KIVIDES');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5304','no',N'Πάνω Κιβίδες-Pano Kivides',N'ΠΆΝΩ ΚΙΒΊΔΕΣ-PANO KIVIDES');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5305','no',N'Άγιος Αμβρόσιος Λεμεσού-Agios Amvrosios Lemesou',N'ΆΓΙΟΣ ΑΜΒΡΌΣΙΟΣ ΛΕΜΕΣΟΎ-AGIOS AMVROSIOS LEMESOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5306','no',N'Άγιος Θεράπων-Agios Therapon',N'ΆΓΙΟΣ ΘΕΡΆΠΩΝ-AGIOS THERAPON');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5307','no',N'Λόφου-Lofou',N'ΛΌΦΟΥ-LOFOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5308','no',N'Πάχνα-Pachna',N'ΠΆΧΝΑ-PACHNA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5310','no',N'Άγιος Γεώργιος Λεμεσού-Agios Georgios Lemesou',N'ΆΓΙΟΣ ΓΕΏΡΓΙΟΣ ΛΕΜΕΣΟΎ-AGIOS GEORGIOS LEMESOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5311','no',N'Δωρός-Doros',N'ΔΩΡΌΣ-DOROS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5312','no',N'Λάνεια-Laneia',N'ΛΆΝΕΙΑ-LANEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5313','no',N'Σιλίκου-Silikou',N'ΣΙΛΊΚΟΥ-SILIKOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5314','no',N'Μονάγρι-Monagri',N'ΜΟΝΆΓΡΙ-MONAGRI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5315','no',N'Τριμήκληνη-Trimiklini',N'ΤΡΙΜΉΚΛΗΝΗ-TRIMIKLINI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5316','no',N'Άγιος Μάμας-Agios Mamas',N'ΆΓΙΟΣ ΜΆΜΑΣ-AGIOS MAMAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5317','no',N'Κουκά-Kouka',N'ΚΟΥΚΆ-KOUKA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5318','no',N'Μονιάτης-Moniatis',N'ΜΟΝΙΆΤΗΣ-MONIATIS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5320','no',N'Δωρά-Dora',N'ΔΩΡΆ-DORA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5321','no',N'Γεροβάσα (Τρόζενα)-Gerovasa (Trozena)',N'ΓΕΡΟΒΆΣΑ (ΤΡΌΖΕΝΑ)-GEROVASA (TROZENA)');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5322','no',N'Άρσος Λεμεσού-Arsos Lemesou',N'ΆΡΣΟΣ ΛΕΜΕΣΟΎ-ARSOS LEMESOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5323','no',N'Κισσούσα-Kissousa',N'ΚΙΣΣΟΎΣΑ-KISSOUSA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5324','no',N'Μαλιά-Malia',N'ΜΑΛΙΆ-MALIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5325','no',N'Βάσα Κοιλανίου-Vasa Koilaniou',N'ΒΆΣΑ ΚΟΙΛΑΝΊΟΥ-VASA KOILANIOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5326','no',N'Βουνί-Vouni',N'ΒΟΥΝΊ-VOUNI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5327','no',N'Πέρα Πεδί-Pera Pedi',N'ΠΈΡΑ ΠΕΔΊ-PERA PEDI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5328','no',N'Μανδριά Λεμεσού-Mandria Lemesou',N'ΜΑΝΔΡΙΆ ΛΕΜΕΣΟΎ-MANDRIA LEMESOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5329','no',N'Ποταμιού-Potamiou',N'ΠΟΤΑΜΙΟΎ-POTAMIOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5330','no',N'Όμοδος-Omodos',N'ΌΜΟΔΟΣ-OMODOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5331','no',N'Κοιλάνι-Koilani',N'ΚΟΙΛΆΝΙ-KOILANI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5340','no',N'Άγιος Δημήτριος-Agios Dimitrios',N'ΆΓΙΟΣ ΔΗΜΉΤΡΙΟΣ-AGIOS DIMITRIOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5341','no',N'Παλαιόμυλος-Palaiomylos',N'ΠΑΛΑΙΌΜΥΛΟΣ-PALAIOMYLOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5342','no',N'Πρόδρομος-Prodromos',N'ΠΡΌΔΡΟΜΟΣ-PRODROMOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5343','no',N'Καμινάρια-Kaminaria',N'ΚΑΜΙΝΆΡΙΑ-KAMINARIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5344','no',N'Τρεις Ελιές-Treis Elies',N'ΤΡΕΙΣ ΕΛΙΈΣ-TREIS ELIES');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5345','no',N'Λεμίθου-Lemithou',N'ΛΕΜΊΘΟΥ-LEMITHOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5350','no',N'Κάτω Πλάτρες (Toρνάρηδες)-Kato Platres (Tornarides)',N'ΚΆΤΩ ΠΛΆΤΡΕΣ (TOΡΝΆΡΗΔΕΣ)-KATO PLATRES (TORNARIDES)');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5351','no',N'Πάνω Πλάτρες-Pano Platres',N'ΠΆΝΩ ΠΛΆΤΡΕΣ-PANO PLATRES');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5352','no',N'Φοινί-Foini',N'ΦΟΙΝΊ-FOINI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5355','no',N'Αμίαντος-Amiantos',N'ΑΜΊΑΝΤΟΣ-AMIANTOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5356','no',N'Τρόοδος-Troodos',N'ΤΡΌΟΔΟΣ-TROODOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5360','no',N'Άγιος Θεόδωρος Λεμεσού-Agios Theodoros Lemesou',N'ΆΓΙΟΣ ΘΕΌΔΩΡΟΣ ΛΕΜΕΣΟΎ-AGIOS THEODOROS LEMESOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5361','no',N'Άγιος Ιωάννης Λεμεσού-Agios Ioannis Lemesou',N'ΆΓΙΟΣ ΙΩΆΝΝΗΣ ΛΕΜΕΣΟΎ-AGIOS IOANNIS LEMESOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5362','no',N'Κάτω Μύλος-Kato Mylos',N'ΚΆΤΩ ΜΎΛΟΣ-KATO MYLOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5363','no',N'Ποταμίτισσα-Potamitissa',N'ΠΟΤΑΜΊΤΙΣΣΑ-POTAMITISSA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5364','no',N'Δύμες-Dymes',N'ΔΎΜΕΣ-DYMES');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5365','no',N'Πελένδρι-Pelendri',N'ΠΕΛΈΝΔΡΙ-PELENDRI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5366','no',N'Αγρός-Agros',N'ΑΓΡΌΣ-AGROS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5367','no',N'Αγρίδια-Agridia',N'ΑΓΡΊΔΙΑ-AGRIDIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5368','no',N'Χανδριά-Chandria',N'ΧΑΝΔΡΙΆ-CHANDRIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','5369','no',N'Κυπερούντα-Kyperounta',N'ΚΥΠΕΡΟΎΝΤΑ-KYPEROUNTA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6000','no',N'Πάφος-Pafos',N'ΠΆΦΟΣ-PAFOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6010','no',N'Γεροσκήπου-Geroskipou',N'ΓΕΡΟΣΚΉΠΟΥ-GEROSKIPOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6011','no',N'Κονιά-Konia',N'ΚΟΝΙΆ-KONIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6012','no',N'Αγία Μαρινούδα-Agia Marinouda',N'ΑΓΊΑ ΜΑΡΙΝΟΎΔΑ-AGIA MARINOUDA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6014','no',N'Αχέλεια-Acheleia',N'ΑΧΈΛΕΙΑ-ACHELEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6020','no',N'Χλώρακας-Chlorakas',N'ΧΛΏΡΑΚΑΣ-CHLORAKAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6021','no',N'Λέμπα-Lempa',N'ΛΈΜΠΑ-LEMPA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6022','no',N'Έμπα-Empa',N'ΈΜΠΑ-EMPA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6023','no',N'Τρεμιθούσα-Tremithousa',N'ΤΡΕΜΙΘΟΎΣΑ-TREMITHOUSA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6024','no',N'Μέσα Χωριό-Mesa Chorio',N'ΜΈΣΑ ΧΩΡΙΌ-MESA CHORIO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6025','no',N'Μεσόγη-Mesogi',N'ΜΕΣΌΓΗ-MESOGI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6026','no',N'Τάλα-Tala',N'ΤΆΛΑ-TALA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6027','no',N'Κισσόνεργα-Kissonerga',N'ΚΙΣΣΌΝΕΡΓΑ-KISSONERGA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6100','no',N'Κούκλια Πάφου-Kouklia Pafou',N'ΚΟΎΚΛΙΑ ΠΆΦΟΥ-KOUKLIA PAFOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6101','no',N'Μανδριά Πάφου-Mandria Pafou',N'ΜΑΝΔΡΙΆ ΠΆΦΟΥ-MANDRIA PAFOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6102','no',N'Νικόκλεια-Nikokleia',N'ΝΙΚΌΚΛΕΙΑ-NIKOKLEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6103','no',N'Σουσκιού-Souskiou',N'ΣΟΥΣΚΙΟΎ-SOUSKIOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6104','no',N'Τίμη-Timi',N'ΤΊΜΗ-TIMI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6106','no',N'Αγία Βαρβάρα Πάφου-Agia Varvara Pafou',N'ΑΓΊΑ ΒΑΡΒΆΡΑ ΠΆΦΟΥ-AGIA VARVARA PAFOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6107','no',N'Αναρίτα-Anarita',N'ΑΝΑΡΊΤΑ-ANARITA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6108','no',N'Φοίνικας-Foinikas',N'ΦΟΊΝΙΚΑΣ-FOINIKAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6110','no',N'Μαραθούντα-Marathounta',N'ΜΑΡΑΘΟΎΝΤΑ-MARATHOUNTA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6111','no',N'Άρμου-Armou',N'ΆΡΜΟΥ-ARMOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6112','no',N'Επισκοπή Πάφου-Episkopi Pafou',N'ΕΠΙΣΚΟΠΉ ΠΆΦΟΥ-EPISKOPI PAFOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6113','no',N'Νατά-Nata',N'ΝΑΤΆ-NATA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6114','no',N'Χολέτρια-Choletria',N'ΧΟΛΈΤΡΙΑ-CHOLETRIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6115','no',N'Αξύλου-Axylou',N'ΑΞΎΛΟΥ-AXYLOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6116','no',N'Ελεδιό-Eledio',N'ΕΛΕΔΙΌ-ELEDIO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6120','no',N'Τσάδα-Tsada',N'ΤΣΆΔΑ-TSADA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6121','no',N'Κοίλη-Koili',N'ΚΟΊΛΗ-KOILI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6122','no',N'Στρουμπί-Stroumpi',N'ΣΤΡΟΥΜΠΊ-STROUMPI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6123','no',N'Πολέμι-Polemi',N'ΠΟΛΈΜΙ-POLEMI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6124','no',N'Καλλέπεια-Kallepeia',N'ΚΑΛΛΈΠΕΙΑ-KALLEPEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6125','no',N'Λετύμβου-Letymvou',N'ΛΕΤΎΜΒΟΥ-LETYMVOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6126','no',N'Πιταργού-Pitargou',N'ΠΙΤΑΡΓΟΎ-PITARGOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6127','no',N'Κούρδακα-Kourdaka',N'ΚΟΎΡΔΑΚΑ-KOURDAKA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6128','no',N'Λεμώνα-Lemona',N'ΛΕΜΏΝΑ-LEMONA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6129','no',N'Χούλου-Choulou',N'ΧΟΎΛΟΥ-CHOULOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6130','no',N'Ακουρσός-Akoursos',N'ΑΚΟΥΡΣΌΣ-AKOURSOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6132','no',N'Κάθικας-Kathikas',N'ΚΆΘΙΚΑΣ-KATHIKAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6133','no',N'Πέγεια-Pegeia',N'ΠΈΓΕΙΑ-PEGEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6200','no',N'Πάνω Aρχιμανδρίτα-Pano Archimandrita',N'ΠΆΝΩ AΡΧΙΜΑΝΔΡΊΤΑ-PANO ARCHIMANDRITA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6201','no',N'Φασούλα Πάφου-Fasoula Pafou',N'ΦΑΣΟΎΛΑ ΠΆΦΟΥ-FASOULA PAFOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6202','no',N'Μούσερε-Mousere',N'ΜΟΎΣΕΡΕ-MOUSERE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6203','no',N'Μάρωνας-Maronas',N'ΜΆΡΩΝΑΣ-MARONAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6204','no',N'Μαμώνια-Mamonia',N'ΜΑΜΏΝΙΑ-MAMONIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6205','no',N'Άγιος Γεώργιος Πάφου-Agios Georgios Pafou',N'ΆΓΙΟΣ ΓΕΏΡΓΙΟΣ ΠΆΦΟΥ-AGIOS GEORGIOS PAFOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6206','no',N'Σταυροκόννου-Stavrokonnou',N'ΣΤΑΥΡΟΚΌΝΝΟΥ-STAVROKONNOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6207','no',N'Πραστιό Πάφου-Prastio Pafou',N'ΠΡΑΣΤΙΌ ΠΆΦΟΥ-PRASTIO PAFOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6208','no',N'Τραχυπέδουλα-Trachypedoula',N'ΤΡΑΧΥΠΈΔΟΥΛΑ-TRACHYPEDOULA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6210','no',N'Κελοκέδαρα-Kelokedara',N'ΚΕΛΟΚΈΔΑΡΑ-KELOKEDARA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6211','no',N'Σαλαμιού-Salamiou',N'ΣΑΛΑΜΙΟΎ-SALAMIOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6212','no',N'Κιδάσι-Kidasi',N'ΚΙΔΆΣΙ-KIDASI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6213','no',N'Κέδαρες-Kedares',N'ΚΈΔΑΡΕΣ-KEDARES');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6214','no',N'Μέσανα-Mesana',N'ΜΈΣΑΝΑ-MESANA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6215','no',N'Πραιτώρι-Praitori',N'ΠΡΑΙΤΏΡΙ-PRAITORI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6216','no',N'Φιλούσα Κελοκεδάρων-Filousa Kelokedaron',N'ΦΙΛΟΎΣΑ ΚΕΛΟΚΕΔΆΡΩΝ-FILOUSA KELOKEDARON');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6217','no',N'Αρμίνου-Arminou',N'ΑΡΜΊΝΟΥ-ARMINOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6218','no',N'Άγιος Νικόλαος Πάφου-Agios Nikolaos Pafou',N'ΆΓΙΟΣ ΝΙΚΌΛΑΟΣ ΠΆΦΟΥ-AGIOS NIKOLAOS PAFOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6219','no',N'Άγιος Ιωάννης Πάφου-Agios Ioannis Pafou',N'ΆΓΙΟΣ ΙΩΆΝΝΗΣ ΠΆΦΟΥ-AGIOS IOANNIS PAFOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6220','no',N'Αμαργέτη-Amargeti',N'ΑΜΑΡΓΈΤΗ-AMARGETI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6221','no',N'Αγία Μαρίνα Κελοκεδάρων-Agia Marina Kelokedaron',N'ΑΓΊΑ ΜΑΡΊΝΑ ΚΕΛΟΚΕΔΆΡΩΝ-AGIA MARINA KELOKEDARON');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6222','no',N'Πενταλιά-Pentalia',N'ΠΕΝΤΑΛΙΆ-PENTALIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6223','no',N'Φάλεια-Faleia',N'ΦΆΛΕΙΑ-FALEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6224','no',N'Γαλαταριά-Galataria',N'ΓΑΛΑΤΑΡΙΆ-GALATARIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6225','no',N'Κοιλίνεια-Koilineia',N'ΚΟΙΛΊΝΕΙΑ-KOILINEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6226','no',N'Βρέτσια-Vretsia',N'ΒΡΈΤΣΙΑ-VRETSIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6227','no',N'Στατός-Άγιος Φώτιος-Statos-Agios Fotios',N'ΣΤΑΤΌΣ-ΆΓΙΟΣ ΦΏΤΙΟΣ-STATOS-AGIOS FOTIOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6228','no',N'Λαπηθιού-Lapithiou',N'ΛΑΠΗΘΙΟΎ-LAPITHIOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6229','no',N'Μαμούνταλη-Mamountali',N'ΜΑΜΟΎΝΤΑΛΗ-MAMOUNTALI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6230','no',N'Πάνω Παναγιά-Pano Panagia',N'ΠΆΝΩ ΠΑΝΑΓΙΆ-PANO PANAGIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6231','no',N'Ασπρογιά-Asprogia',N'ΑΣΠΡΟΓΙΆ-ASPROGIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6300','no',N'Ψάθι-Psathi',N'ΨΆΘΙ-PSATHI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6301','no',N'Άγιος Δημητριανός-Agios Dimitrianos',N'ΆΓΙΟΣ ΔΗΜΗΤΡΙΑΝΌΣ-AGIOS DIMITRIANOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6302','no',N'Κανναβιού-Kannaviou',N'ΚΑΝΝΑΒΙΟΎ-KANNAVIOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6303','no',N'Θρινιά-Thrinia',N'ΘΡΙΝΙΆ-THRINIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6304','no',N'Μηλιά Πάφου-Milia Pafou',N'ΜΗΛΙΆ ΠΆΦΟΥ-MILIA PAFOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6305','no',N'Κρίτου Μαρόττου-Kritou Marottou',N'ΚΡΊΤΟΥ ΜΑΡΌΤΤΟΥ-KRITOU MAROTTOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6306','no',N'Φύτη-Fyti',N'ΦΎΤΗ-FYTI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6307','no',N'Λάσα-Lasa',N'ΛΆΣΑ-LASA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6308','no',N'Δρύμου-Drymou',N'ΔΡΎΜΟΥ-DRYMOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6310','no',N'Σίμου-Simou',N'ΣΊΜΟΥ-SIMOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6311','no',N'Αναδιού-Anadiou',N'ΑΝΑΔΙΟΎ-ANADIOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6312','no',N'Σαραμά-Sarama',N'ΣΑΡΑΜΆ-SARAMA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6313','no',N'Ευρέτου-Evretou',N'ΕΥΡΈΤΟΥ-EVRETOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6314','no',N'Τριμιθούσα-Trimithousa',N'ΤΡΙΜΙΘΟΎΣΑ-TRIMITHOUSA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6315','no',N'Φιλούσα Χρυσοχούς-Filousa Chrysochous',N'ΦΙΛΟΎΣΑ ΧΡΥΣΟΧΟΎΣ-FILOUSA CHRYSOCHOUS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6316','no',N'Κιός-Kios',N'ΚΙΌΣ-KIOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6317','no',N'Ζαχαριά-Zacharia',N'ΖΑΧΑΡΙΆ-ZACHARIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6318','no',N'Μελάδεια-Meladeia',N'ΜΕΛΆΔΕΙΑ-MELADEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6319','no',N'Μελάνδρα-Melandra',N'ΜΕΛΆΝΔΡΑ-MELANDRA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6320','no',N'Λυσός-Lysos',N'ΛΥΣΌΣ-LYSOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6321','no',N'Περιστερώνα Πάφου-Peristerona Pafou',N'ΠΕΡΙΣΤΕΡΏΝΑ ΠΆΦΟΥ-PERISTERONA PAFOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6330','no',N'Θελέτρα-Theletra',N'ΘΕΛΈΤΡΑ-THELETRA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6331','no',N'Γιόλου-Giolou',N'ΓΙΌΛΟΥ-GIOLOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6332','no',N'Πάνω Ακουρδάλεια-Pano Akourdaleia',N'ΠΆΝΩ ΑΚΟΥΡΔΆΛΕΙΑ-PANO AKOURDALEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6333','no',N'Μηλιού-Miliou',N'ΜΗΛΙΟΎ-MILIOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6334','no',N'Κάτω Ακουρδάλεια-Kato Akourdaleia',N'ΚΆΤΩ ΑΚΟΥΡΔΆΛΕΙΑ-KATO AKOURDALEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6335','no',N'Τέρα-Tera',N'ΤΈΡΑ-TERA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6336','no',N'Κρίτου Τέρα-Kritou Tera',N'ΚΡΊΤΟΥ ΤΈΡΑ-KRITOU TERA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6337','no',N'Σκούλλη-Skoulli',N'ΣΚΟΎΛΛΗ-SKOULLI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6338','no',N'Χόλη-Choli',N'ΧΌΛΗ-CHOLI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6339','no',N'Λουκρούνου-Loukrounou',N'ΛΟΥΚΡΟΎΝΟΥ-LOUKROUNOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6340','no',N'Καραμούλληδες-Karamoullides',N'ΚΑΡΑΜΟΎΛΛΗΔΕΣ-KARAMOULLIDES');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6341','no',N'Χρυσοχού-Chrysochou',N'ΧΡΥΣΟΧΟΎ-CHRYSOCHOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6343','no',N'Πόλις-Polis',N'ΠΌΛΙΣ-POLIS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6344','no',N'Νέο Χωριό Πάφου-Neo Chorio Pafou',N'ΝΈΟ ΧΩΡΙΌ ΠΆΦΟΥ-NEO CHORIO PAFOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6345','no',N'Γουδί-Goudi',N'ΓΟΥΔΊ-GOUDI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6350','no',N'Κάτω Αρόδες-Kato Arodes',N'ΚΆΤΩ ΑΡΌΔΕΣ-KATO ARODES');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6351','no',N'Πάνω Αρόδες-Pano Arodes',N'ΠΆΝΩ ΑΡΌΔΕΣ-PANO ARODES');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6352','no',N'''Ινεια-Ineia',N'''ΙΝΕΙΑ-INEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6353','no',N'Δρούσεια-Drouseia',N'ΔΡΟΎΣΕΙΑ-DROUSEIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6354','no',N'Φάσλι-Fasli',N'ΦΆΣΛΙ-FASLI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6355','no',N'Ανδρολίκου-Androlikou',N'ΑΝΔΡΟΛΊΚΟΥ-ANDROLIKOU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6360','no',N'Πελαθούσα-Pelathousa',N'ΠΕΛΑΘΟΎΣΑ-PELATHOUSA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6361','no',N'Κυνούσα-Kynousa',N'ΚΥΝΟΎΣΑ-KYNOUSA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6362','no',N'Μακούντα-Makounta',N'ΜΑΚΟΎΝΤΑ-MAKOUNTA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6363','no',N'Αργάκα-Argaka',N'ΑΡΓΆΚΑ-ARGAKA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6364','no',N'Γιαλιά-Gialia',N'ΓΙΑΛΙΆ-GIALIA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6365','no',N'Αγία Μαρίνα Χρυσοχούς-Agia Marina Chrysochous',N'ΑΓΊΑ ΜΑΡΊΝΑ ΧΡΥΣΟΧΟΎΣ-AGIA MARINA CHRYSOCHOUS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6366','no',N'Νέα Δήμματα-Nea Dimmata',N'ΝΈΑ ΔΉΜΜΑΤΑ-NEA DIMMATA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6367','no',N'Πομός-Pomos',N'ΠΟΜΌΣ-POMOS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6368','no',N'Στενή-Steni',N'ΣΤΕΝΉ-STENI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6369','no',N'Άγιος Ισίδωρος-Agios Isidoros',N'ΆΓΙΟΣ ΙΣΊΔΩΡΟΣ-AGIOS ISIDOROS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('CY','CY000','6370','no',N'Λιβάδι-Livadi',N'ΛΙΒΆΔΙ-LIVADI');
