INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL513','0101','no',N'ΔΗΜΟΣ ΚΟΜΟΤΗΝΗΣ-Municipality of Komotini',N'ΔΗΜΟΣ ΚΟΜΟΤΗΝΗΣ-MUNICIPALITY OF KOMOTINI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL513','0102','no',N'ΔΗΜΟΣ ΑΡΡΙΑΝΩΝ-Municipality of Arriana',N'ΔΗΜΟΣ ΑΡΡΙΑΝΩΝ-MUNICIPALITY OF ARRIANA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL513','0103','no',N'ΔΗΜΟΣ ΙΑΣΜΟΥ-Municipality of Iasmos',N'ΔΗΜΟΣ ΙΑΣΜΟΥ-MUNICIPALITY OF IASMOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL513','0104','no',N'ΔΗΜΟΣ ΜΑΡΩΝΕΙΑΣ - ΣΑΠΩΝ-Municipality of Maronia - Sapes',N'ΔΗΜΟΣ ΜΑΡΩΝΕΙΑΣ - ΣΑΠΩΝ-MUNICIPALITY OF MARONIA - SAPES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL514','0201','no',N'ΔΗΜΟΣ ΔΡΑΜΑΣ-Municipality of Drama',N'ΔΗΜΟΣ ΔΡΑΜΑΣ-MUNICIPALITY OF DRAMA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL514','0202','no',N'ΔΗΜΟΣ ΔΟΞΑΤΟΥ-Municipality of Doxato',N'ΔΗΜΟΣ ΔΟΞΑΤΟΥ-MUNICIPALITY OF DOXATO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL514','0203','no',N'ΔΗΜΟΣ ΚΑΤΩ ΝΕΥΡΟΚΟΠΙΟΥ-Municipality of Kato Nevrokopi',N'ΔΗΜΟΣ ΚΑΤΩ ΝΕΥΡΟΚΟΠΙΟΥ-MUNICIPALITY OF KATO NEVROKOPI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL514','0204','no',N'ΔΗΜΟΣ ΠΑΡΑΝΕΣΤΙΟΥ-Municipality of Paranesti',N'ΔΗΜΟΣ ΠΑΡΑΝΕΣΤΙΟΥ-MUNICIPALITY OF PARANESTI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL514','0205','no',N'ΔΗΜΟΣ ΠΡΟΣΟΤΣΑΝΗΣ-Municipality of Prossotsani',N'ΔΗΜΟΣ ΠΡΟΣΟΤΣΑΝΗΣ-MUNICIPALITY OF PROSSOTSANI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL511','0301','no',N'ΔΗΜΟΣ ΑΛΕΞΑΝΔΡΟΥΠΟΛΗΣ-Municipality of Alexandroupoli',N'ΔΗΜΟΣ ΑΛΕΞΑΝΔΡΟΥΠΟΛΗΣ-MUNICIPALITY OF ALEXANDROUPOLI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL511','0302','no',N'ΔΗΜΟΣ ΔΙΔΥΜΟΤΕΙΧΟΥ-Municipality of Didymoticho',N'ΔΗΜΟΣ ΔΙΔΥΜΟΤΕΙΧΟΥ-MUNICIPALITY OF DIDYMOTICHO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL511','0303','no',N'ΔΗΜΟΣ ΟΡΕΣΤΙΑΔΑΣ-Municipality of Orestiada',N'ΔΗΜΟΣ ΟΡΕΣΤΙΑΔΑΣ-MUNICIPALITY OF ORESTIADA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL511','0304','no',N'ΔΗΜΟΣ ΣΑΜΟΘΡΑΚΗΣ-Municipality of Samothraki',N'ΔΗΜΟΣ ΣΑΜΟΘΡΑΚΗΣ-MUNICIPALITY OF SAMOTHRAKI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL511','0305','no',N'ΔΗΜΟΣ ΣΟΥΦΛΙΟΥ-Municipality of Soufli',N'ΔΗΜΟΣ ΣΟΥΦΛΙΟΥ-MUNICIPALITY OF SOUFLI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL515','0401','no',N'ΔΗΜΟΣ ΘΑΣΟΥ-Municipality of Thassos',N'ΔΗΜΟΣ ΘΑΣΟΥ-MUNICIPALITY OF THASSOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL515','0501','no',N'ΔΗΜΟΣ ΚΑΒΑΛΑΣ-Municipality of Kavala',N'ΔΗΜΟΣ ΚΑΒΑΛΑΣ-MUNICIPALITY OF KAVALA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL515','0502','no',N'ΔΗΜΟΣ ΝΕΣΤΟΥ-Municipality of Nestos',N'ΔΗΜΟΣ ΝΕΣΤΟΥ-MUNICIPALITY OF NESTOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL515','0503','no',N'ΔΗΜΟΣ ΠΑΓΓΑΙΟΥ-Municipality of Pagheo',N'ΔΗΜΟΣ ΠΑΓΓΑΙΟΥ-MUNICIPALITY OF PAGHEO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL512','0601','no',N'ΔΗΜΟΣ ΞΑΝΘΗΣ-Municipality of Xanthi',N'ΔΗΜΟΣ ΞΑΝΘΗΣ-MUNICIPALITY OF XANTHI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL512','0602','no',N'ΔΗΜΟΣ ΑΒΔΗΡΩΝ-Municipality of Avdira',N'ΔΗΜΟΣ ΑΒΔΗΡΩΝ-MUNICIPALITY OF AVDIRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL512','0603','no',N'ΔΗΜΟΣ ΜΥΚΗΣ-Municipality of Myki',N'ΔΗΜΟΣ ΜΥΚΗΣ-MUNICIPALITY OF MYKI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL512','0604','no',N'ΔΗΜΟΣ ΤΟΠΕΙΡΟΥ-Municipality of Topiros',N'ΔΗΜΟΣ ΤΟΠΕΙΡΟΥ-MUNICIPALITY OF TOPIROS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL522','0701','no',N'ΔΗΜΟΣ ΘΕΣΣΑΛΟΝΙΚΗΣ-Municipality of Thessaloniki',N'ΔΗΜΟΣ ΘΕΣΣΑΛΟΝΙΚΗΣ-MUNICIPALITY OF THESSALONIKI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL522','0702','no',N'ΔΗΜΟΣ ΑΜΠΕΛΟΚΗΠΩΝ - ΜΕΝΕΜΕΝΗΣ-Municipality of Abelokipi - Menemeni',N'ΔΗΜΟΣ ΑΜΠΕΛΟΚΗΠΩΝ - ΜΕΝΕΜΕΝΗΣ-MUNICIPALITY OF ABELOKIPI - MENEMENI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL522','0703','no',N'ΔΗΜΟΣ ΒΟΛΒΗΣ-Municipality of Volvi',N'ΔΗΜΟΣ ΒΟΛΒΗΣ-MUNICIPALITY OF VOLVI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL522','0704','no',N'ΔΗΜΟΣ ΔΕΛΤΑ-Municipality of Delta',N'ΔΗΜΟΣ ΔΕΛΤΑ-MUNICIPALITY OF DELTA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL522','0705','no',N'ΔΗΜΟΣ ΘΕΡΜΑΪΚΟΥ-Municipality of Thermaikos',N'ΔΗΜΟΣ ΘΕΡΜΑΪΚΟΥ-MUNICIPALITY OF THERMAIKOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL522','0706','no',N'ΔΗΜΟΣ ΘΕΡΜΗΣ-Municipality of Thermi',N'ΔΗΜΟΣ ΘΕΡΜΗΣ-MUNICIPALITY OF THERMI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL522','0707','no',N'ΔΗΜΟΣ ΚΑΛΑΜΑΡΙΑΣ-Municipality of Kalamaria',N'ΔΗΜΟΣ ΚΑΛΑΜΑΡΙΑΣ-MUNICIPALITY OF KALAMARIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL522','0708','no',N'ΔΗΜΟΣ ΚΟΡΔΕΛΙΟΥ - ΕΥΟΣΜΟΥ-Municipality of Kordelio - Evosmos',N'ΔΗΜΟΣ ΚΟΡΔΕΛΙΟΥ - ΕΥΟΣΜΟΥ-MUNICIPALITY OF KORDELIO - EVOSMOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL522','0709','no',N'ΔΗΜΟΣ ΛΑΓΚΑΔΑ-Municipality of Lagadas',N'ΔΗΜΟΣ ΛΑΓΚΑΔΑ-MUNICIPALITY OF LAGADAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL522','0710','no',N'ΔΗΜΟΣ ΝΕΑΠΟΛΗΣ - ΣΥΚΕΩΝ-Municipality of Neapoli - Sykees',N'ΔΗΜΟΣ ΝΕΑΠΟΛΗΣ - ΣΥΚΕΩΝ-MUNICIPALITY OF NEAPOLI - SYKEES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL522','0711','no',N'ΔΗΜΟΣ ΠΑΥΛΟΥ ΜΕΛΑ-Municipality of Pavlos Melas',N'ΔΗΜΟΣ ΠΑΥΛΟΥ ΜΕΛΑ-MUNICIPALITY OF PAVLOS MELAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL522','0712','no',N'ΔΗΜΟΣ ΠΥΛΑΙΑΣ - ΧΟΡΤΙΑΤΗ-Municipality of Pylea - Chortiatis',N'ΔΗΜΟΣ ΠΥΛΑΙΑΣ - ΧΟΡΤΙΑΤΗ-MUNICIPALITY OF PYLEA - CHORTIATIS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL522','0713','no',N'ΔΗΜΟΣ ΧΑΛΚΗΔΟΝΟΣ-Municipality of Chalkidona',N'ΔΗΜΟΣ ΧΑΛΚΗΔΟΝΟΣ-MUNICIPALITY OF CHALKIDONA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL522','0714','no',N'ΔΗΜΟΣ ΩΡΑΙΟΚΑΣΤΡΟΥ-Municipality of Oreokastro',N'ΔΗΜΟΣ ΩΡΑΙΟΚΑΣΤΡΟΥ-MUNICIPALITY OF OREOKASTRO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL521','0801','no',N'ΔΗΜΟΣ ΒΕΡΟΙΑΣ-Municipality of Veria',N'ΔΗΜΟΣ ΒΕΡΟΙΑΣ-MUNICIPALITY OF VERIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL521','0802','no',N'ΔΗΜΟΣ ΑΛΕΞΑΝΔΡΕΙΑΣ-Municipality of Alexandria',N'ΔΗΜΟΣ ΑΛΕΞΑΝΔΡΕΙΑΣ-MUNICIPALITY OF ALEXANDRIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL521','0803','no',N'ΔΗΜΟΣ ΝΑΟΥΣΑΣ-Municipality of Naoussa',N'ΔΗΜΟΣ ΝΑΟΥΣΑΣ-MUNICIPALITY OF NAOUSSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL523','0901','no',N'ΔΗΜΟΣ ΚΙΛΚΙΣ-Municipality of Kilkis',N'ΔΗΜΟΣ ΚΙΛΚΙΣ-MUNICIPALITY OF KILKIS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL523','0902','no',N'ΔΗΜΟΣ ΠΑΙΟΝΙΑΣ-Municipality of Peonia',N'ΔΗΜΟΣ ΠΑΙΟΝΙΑΣ-MUNICIPALITY OF PEONIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL524','1001','no',N'ΔΗΜΟΣ ΕΔΕΣΣΑΣ-Municipality of Edessa',N'ΔΗΜΟΣ ΕΔΕΣΣΑΣ-MUNICIPALITY OF EDESSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL524','1002','no',N'ΔΗΜΟΣ ΑΛΜΩΠΙΑΣ-Municipality of Almopia',N'ΔΗΜΟΣ ΑΛΜΩΠΙΑΣ-MUNICIPALITY OF ALMOPIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL524','1003','no',N'ΔΗΜΟΣ ΠΕΛΛΑΣ-Municipality of Pella',N'ΔΗΜΟΣ ΠΕΛΛΑΣ-MUNICIPALITY OF PELLA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL524','1004','no',N'ΔΗΜΟΣ ΣΚΥΔΡΑΣ-Municipality of Skydra',N'ΔΗΜΟΣ ΣΚΥΔΡΑΣ-MUNICIPALITY OF SKYDRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL525','1101','no',N'ΔΗΜΟΣ ΚΑΤΕΡΙΝΗΣ-Municipality of Katerini',N'ΔΗΜΟΣ ΚΑΤΕΡΙΝΗΣ-MUNICIPALITY OF KATERINI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL525','1102','no',N'ΔΗΜΟΣ ΔΙΟΥ - ΟΛΥΜΠΟΥ-Municipality of Dion - Olympos',N'ΔΗΜΟΣ ΔΙΟΥ - ΟΛΥΜΠΟΥ-MUNICIPALITY OF DION - OLYMPOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL525','1103','no',N'ΔΗΜΟΣ ΠΥΔΝΑΣ - ΚΟΛΙΝΔΡΟΥ-Municipality of Pydna - Kolindros',N'ΔΗΜΟΣ ΠΥΔΝΑΣ - ΚΟΛΙΝΔΡΟΥ-MUNICIPALITY OF PYDNA - KOLINDROS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL526','1201','no',N'ΔΗΜΟΣ ΣΕΡΡΩΝ-Municipality of Serres',N'ΔΗΜΟΣ ΣΕΡΡΩΝ-MUNICIPALITY OF SERRES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL526','1202','no',N'ΔΗΜΟΣ ΑΜΦΙΠΟΛΗΣ-Municipality of Amfipoli',N'ΔΗΜΟΣ ΑΜΦΙΠΟΛΗΣ-MUNICIPALITY OF AMFIPOLI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL526','1203','no',N'ΔΗΜΟΣ ΒΙΣΑΛΤΙΑΣ-Municipality of Vissaltia',N'ΔΗΜΟΣ ΒΙΣΑΛΤΙΑΣ-MUNICIPALITY OF VISSALTIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL526','1204','no',N'ΔΗΜΟΣ ΕΜΜΑΝΟΥΗΛ ΠΑΠΠΑ-Municipality of Emmanuel Pappas',N'ΔΗΜΟΣ ΕΜΜΑΝΟΥΗΛ ΠΑΠΠΑ-MUNICIPALITY OF EMMANUEL PAPPAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL526','1205','no',N'ΔΗΜΟΣ ΗΡΑΚΛΕΙΑΣ-Municipality of Iraklia',N'ΔΗΜΟΣ ΗΡΑΚΛΕΙΑΣ-MUNICIPALITY OF IRAKLIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL526','1206','no',N'ΔΗΜΟΣ ΝΕΑΣ ΖΙΧΝΗΣ-Municipality of Nea Zichni',N'ΔΗΜΟΣ ΝΕΑΣ ΖΙΧΝΗΣ-MUNICIPALITY OF NEA ZICHNI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL526','1207','no',N'ΔΗΜΟΣ ΣΙΝΤΙΚΗΣ-Municipality of Sintiki',N'ΔΗΜΟΣ ΣΙΝΤΙΚΗΣ-MUNICIPALITY OF SINTIKI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL527','1301','no',N'ΔΗΜΟΣ ΠΟΛΥΓΥΡΟΥ-Municipality of Polygyros',N'ΔΗΜΟΣ ΠΟΛΥΓΥΡΟΥ-MUNICIPALITY OF POLYGYROS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL527','1302','no',N'ΔΗΜΟΣ ΑΡΙΣΤΟΤΕΛΗ-Municipality of Aristotelis',N'ΔΗΜΟΣ ΑΡΙΣΤΟΤΕΛΗ-MUNICIPALITY OF ARISTOTELIS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL527','1303','no',N'ΔΗΜΟΣ ΚΑΣΣΑΝΔΡΑΣ-Municipality of Kassandra',N'ΔΗΜΟΣ ΚΑΣΣΑΝΔΡΑΣ-MUNICIPALITY OF KASSANDRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL527','1304','no',N'ΔΗΜΟΣ ΝΕΑΣ ΠΡΟΠΟΝΤΙΔΑΣ-Municipality of Nea Propontida',N'ΔΗΜΟΣ ΝΕΑΣ ΠΡΟΠΟΝΤΙΔΑΣ-MUNICIPALITY OF NEA PROPONTIDA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL527','1305','no',N'ΔΗΜΟΣ ΣΙΘΩΝΙΑΣ-Municipality of Sithonia',N'ΔΗΜΟΣ ΣΙΘΩΝΙΑΣ-MUNICIPALITY OF SITHONIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL531','1401','no',N'ΔΗΜΟΣ ΚΟΖΑΝΗΣ-Municipality of Kozani',N'ΔΗΜΟΣ ΚΟΖΑΝΗΣ-MUNICIPALITY OF KOZANI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL531','1402','no',N'ΔΗΜΟΣ ΒΟΪΟΥ-Municipality of Voio',N'ΔΗΜΟΣ ΒΟΪΟΥ-MUNICIPALITY OF VOIO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL531','1403','no',N'ΔΗΜΟΣ ΕΟΡΔΑΙΑΣ-Municipality of Eordea',N'ΔΗΜΟΣ ΕΟΡΔΑΙΑΣ-MUNICIPALITY OF EORDEA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL531','1404','no',N'ΔΗΜΟΣ ΣΕΡΒΙΩΝ - ΒΕΛΒΕΝΤΟΥ-Municipality of Servia - Velvendos',N'ΔΗΜΟΣ ΣΕΡΒΙΩΝ - ΒΕΛΒΕΝΤΟΥ-MUNICIPALITY OF SERVIA - VELVENDOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL531','1501','no',N'ΔΗΜΟΣ ΓΡΕΒΕΝΩΝ-Municipality of Grevena',N'ΔΗΜΟΣ ΓΡΕΒΕΝΩΝ-MUNICIPALITY OF GREVENA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL531','1502','no',N'ΔΗΜΟΣ ΔΕΣΚΑΤΗΣ-Municipality of Deskati',N'ΔΗΜΟΣ ΔΕΣΚΑΤΗΣ-MUNICIPALITY OF DESKATI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL532','1601','no',N'ΔΗΜΟΣ ΚΑΣΤΟΡΙΑΣ-Municipality of Kastoria',N'ΔΗΜΟΣ ΚΑΣΤΟΡΙΑΣ-MUNICIPALITY OF KASTORIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL532','1602','no',N'ΔΗΜΟΣ ΝΕΣΤΟΡΙΟΥ-Municipality of Nestorio',N'ΔΗΜΟΣ ΝΕΣΤΟΡΙΟΥ-MUNICIPALITY OF NESTORIO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL532','1603','no',N'ΔΗΜΟΣ ΑΡΓΟΥΣ ΟΡΕΣΤΙΚΟΥ-Municipality of Arghos Orestiko',N'ΔΗΜΟΣ ΑΡΓΟΥΣ ΟΡΕΣΤΙΚΟΥ-MUNICIPALITY OF ARGHOS ORESTIKO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL533','1701','no',N'ΔΗΜΟΣ ΦΛΩΡΙΝΑΣ-Municipality of Florina',N'ΔΗΜΟΣ ΦΛΩΡΙΝΑΣ-MUNICIPALITY OF FLORINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL533','1702','no',N'ΔΗΜΟΣ ΑΜΥΝΤΑΙΟΥ-Municipality of Amynteo',N'ΔΗΜΟΣ ΑΜΥΝΤΑΙΟΥ-MUNICIPALITY OF AMYNTEO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL533','1703','no',N'ΔΗΜΟΣ ΠΡΕΣΠΩΝ-Municipality of Prespes',N'ΔΗΜΟΣ ΠΡΕΣΠΩΝ-MUNICIPALITY OF PRESPES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL543','1801','no',N'ΔΗΜΟΣ ΙΩΑΝΝΙΤΩΝ-Municipality of Ioannina',N'ΔΗΜΟΣ ΙΩΑΝΝΙΤΩΝ-MUNICIPALITY OF IOANNINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL543','1802','no',N'ΔΗΜΟΣ ΒΟΡΕΙΩΝ ΤΖΟΥΜΕΡΚΩΝ-Municipality of Voria Tzoumerka',N'ΔΗΜΟΣ ΒΟΡΕΙΩΝ ΤΖΟΥΜΕΡΚΩΝ-MUNICIPALITY OF VORIA TZOUMERKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL543','1803','no',N'ΔΗΜΟΣ ΔΩΔΩΝΗΣ-Municipality of Dodoni',N'ΔΗΜΟΣ ΔΩΔΩΝΗΣ-MUNICIPALITY OF DODONI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL543','1804','no',N'ΔΗΜΟΣ ΖΑΓΟΡΙΟΥ-Municipality of Zagori',N'ΔΗΜΟΣ ΖΑΓΟΡΙΟΥ-MUNICIPALITY OF ZAGORI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL543','1805','no',N'ΔΗΜΟΣ ΖΙΤΣΑΣ-Municipality of Zitsa',N'ΔΗΜΟΣ ΖΙΤΣΑΣ-MUNICIPALITY OF ZITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL543','1806','no',N'ΔΗΜΟΣ ΚΟΝΙΤΣΑΣ-Municipality of Konitsa',N'ΔΗΜΟΣ ΚΟΝΙΤΣΑΣ-MUNICIPALITY OF KONITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL543','1807','no',N'ΔΗΜΟΣ ΜΕΤΣΟΒΟΥ-Municipality of Metsovo',N'ΔΗΜΟΣ ΜΕΤΣΟΒΟΥ-MUNICIPALITY OF METSOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL543','1808','no',N'ΔΗΜΟΣ ΠΩΓΩΝΙΟΥ-Municipality of Pogonio',N'ΔΗΜΟΣ ΠΩΓΩΝΙΟΥ-MUNICIPALITY OF POGONIO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL541','1901','no',N'ΔΗΜΟΣ ΑΡΤΑΙΩΝ-Municipality of Arta',N'ΔΗΜΟΣ ΑΡΤΑΙΩΝ-MUNICIPALITY OF ARTA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL541','1902','no',N'ΔΗΜΟΣ ΓΕΩΡΓΙΟΥ ΚΑΡΑΪΣΚΑΚΗ-Municipality of Georgios Karaiskakis',N'ΔΗΜΟΣ ΓΕΩΡΓΙΟΥ ΚΑΡΑΪΣΚΑΚΗ-MUNICIPALITY OF GEORGIOS KARAISKAKIS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL541','1903','no',N'ΔΗΜΟΣ ΚΕΝΤΡΙΚΩΝ ΤΖΟΥΜΕΡΚΩΝ-Municipality of Kentrika Tzoumerka',N'ΔΗΜΟΣ ΚΕΝΤΡΙΚΩΝ ΤΖΟΥΜΕΡΚΩΝ-MUNICIPALITY OF KENTRIKA TZOUMERKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL541','1904','no',N'ΔΗΜΟΣ ΝΙΚΟΛΑΟΥ ΣΚΟΥΦΑ-Municipality of Nikolaos Skoufas',N'ΔΗΜΟΣ ΝΙΚΟΛΑΟΥ ΣΚΟΥΦΑ-MUNICIPALITY OF NIKOLAOS SKOUFAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL542','2001','no',N'ΔΗΜΟΣ ΗΓΟΥΜΕΝΙΤΣΑΣ-Municipality of Igoumenitsa',N'ΔΗΜΟΣ ΗΓΟΥΜΕΝΙΤΣΑΣ-MUNICIPALITY OF IGOUMENITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL542','2002','no',N'ΔΗΜΟΣ ΣΟΥΛΙΟΥ-Municipality of Souli',N'ΔΗΜΟΣ ΣΟΥΛΙΟΥ-MUNICIPALITY OF SOULI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL542','2003','no',N'ΔΗΜΟΣ ΦΙΛΙΑΤΩΝ-Municipality of Filiates',N'ΔΗΜΟΣ ΦΙΛΙΑΤΩΝ-MUNICIPALITY OF FILIATES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL541','2101','no',N'ΔΗΜΟΣ ΠΡΕΒΕΖΑΣ-Municipality of Preveza',N'ΔΗΜΟΣ ΠΡΕΒΕΖΑΣ-MUNICIPALITY OF PREVEZA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL541','2102','no',N'ΔΗΜΟΣ ΖΗΡΟΥ-Municipality of Ziros',N'ΔΗΜΟΣ ΖΗΡΟΥ-MUNICIPALITY OF ZIROS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL541','2103','no',N'ΔΗΜΟΣ ΠΑΡΓΑΣ-Municipality of Parga',N'ΔΗΜΟΣ ΠΑΡΓΑΣ-MUNICIPALITY OF PARGA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL612','2201','no',N'ΔΗΜΟΣ ΛΑΡΙΣΑΙΩΝ-Municipality of Larissa',N'ΔΗΜΟΣ ΛΑΡΙΣΑΙΩΝ-MUNICIPALITY OF LARISSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL612','2202','no',N'ΔΗΜΟΣ ΑΓΙΑΣ-Municipality of Aghia',N'ΔΗΜΟΣ ΑΓΙΑΣ-MUNICIPALITY OF AGHIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL612','2203','no',N'ΔΗΜΟΣ ΕΛΑΣΣΟΝΑΣ-Municipality of Elassona',N'ΔΗΜΟΣ ΕΛΑΣΣΟΝΑΣ-MUNICIPALITY OF ELASSONA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL612','2204','no',N'ΔΗΜΟΣ ΚΙΛΕΛΕΡ-Municipality of Kileler',N'ΔΗΜΟΣ ΚΙΛΕΛΕΡ-MUNICIPALITY OF KILELER');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL612','2205','no',N'ΔΗΜΟΣ ΤΕΜΠΩΝ-Municipality of Tempi',N'ΔΗΜΟΣ ΤΕΜΠΩΝ-MUNICIPALITY OF TEMPI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL612','2206','no',N'ΔΗΜΟΣ ΤΥΡΝΑΒΟΥ-Municipality of Tyrnavos',N'ΔΗΜΟΣ ΤΥΡΝΑΒΟΥ-MUNICIPALITY OF TYRNAVOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL612','2207','no',N'ΔΗΜΟΣ ΦΑΡΣΑΛΩΝ-Municipality of Farsala',N'ΔΗΜΟΣ ΦΑΡΣΑΛΩΝ-MUNICIPALITY OF FARSALA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL611','2301','no',N'ΔΗΜΟΣ ΚΑΡΔΙΤΣΑΣ-Municipality of Karditsa',N'ΔΗΜΟΣ ΚΑΡΔΙΤΣΑΣ-MUNICIPALITY OF KARDITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL611','2302','no',N'ΔΗΜΟΣ ΑΡΓΙΘΕΑΣ-Municipality of Argithea',N'ΔΗΜΟΣ ΑΡΓΙΘΕΑΣ-MUNICIPALITY OF ARGITHEA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL611','2303','no',N'ΔΗΜΟΣ ΛΙΜΝΗΣ ΠΛΑΣΤΗΡΑ-Municipality of Limni Plastira',N'ΔΗΜΟΣ ΛΙΜΝΗΣ ΠΛΑΣΤΗΡΑ-MUNICIPALITY OF LIMNI PLASTIRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL611','2304','no',N'ΔΗΜΟΣ ΜΟΥΖΑΚΙΟΥ-Municipality of Mouzaki',N'ΔΗΜΟΣ ΜΟΥΖΑΚΙΟΥ-MUNICIPALITY OF MOUZAKI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL611','2305','no',N'ΔΗΜΟΣ ΠΑΛΑΜΑ-Municipality of Palamas',N'ΔΗΜΟΣ ΠΑΛΑΜΑ-MUNICIPALITY OF PALAMAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL611','2306','no',N'ΔΗΜΟΣ ΣΟΦΑΔΩΝ-Municipality of Sofades',N'ΔΗΜΟΣ ΣΟΦΑΔΩΝ-MUNICIPALITY OF SOFADES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL613','2401','no',N'ΔΗΜΟΣ ΒΟΛΟΥ-Municipality of Volos',N'ΔΗΜΟΣ ΒΟΛΟΥ-MUNICIPALITY OF VOLOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL613','2402','no',N'ΔΗΜΟΣ ΑΛΜΥΡΟΥ-Municipality of Almyros',N'ΔΗΜΟΣ ΑΛΜΥΡΟΥ-MUNICIPALITY OF ALMYROS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL613','2403','no',N'ΔΗΜΟΣ ΖΑΓΟΡΑΣ - ΜΟΥΡΕΣΙΟΥ-Municipality of Zagora - Mouressio',N'ΔΗΜΟΣ ΖΑΓΟΡΑΣ - ΜΟΥΡΕΣΙΟΥ-MUNICIPALITY OF ZAGORA - MOURESSIO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL613','2404','no',N'ΔΗΜΟΣ ΝΟΤΙΟΥ ΠΗΛΙΟΥ-Municipality of Notio Pelio',N'ΔΗΜΟΣ ΝΟΤΙΟΥ ΠΗΛΙΟΥ-MUNICIPALITY OF NOTIO PELIO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL613','2405','no',N'ΔΗΜΟΣ ΡΗΓΑ ΦΕΡΑΙΟΥ-Municipality of Rigas Fereos',N'ΔΗΜΟΣ ΡΗΓΑ ΦΕΡΑΙΟΥ-MUNICIPALITY OF RIGAS FEREOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL613','2501','no',N'ΔΗΜΟΣ ΣΚΙΑΘΟΥ-Municipality of Skiathos',N'ΔΗΜΟΣ ΣΚΙΑΘΟΥ-MUNICIPALITY OF SKIATHOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL613','2502','no',N'ΔΗΜΟΣ ΑΛΟΝΝΗΣΟΥ-Municipality of Alonnissos',N'ΔΗΜΟΣ ΑΛΟΝΝΗΣΟΥ-MUNICIPALITY OF ALONNISSOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL613','2503','no',N'ΔΗΜΟΣ ΣΚΟΠΕΛΟΥ-Municipality of Skopelos',N'ΔΗΜΟΣ ΣΚΟΠΕΛΟΥ-MUNICIPALITY OF SKOPELOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL611','2601','no',N'ΔΗΜΟΣ ΤΡΙΚΚΑΙΩΝ-Municipality of Trikala',N'ΔΗΜΟΣ ΤΡΙΚΚΑΙΩΝ-MUNICIPALITY OF TRIKALA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL611','2602','no',N'ΔΗΜΟΣ ΚΑΛΑΜΠΑΚΑΣ-Municipality of Kalabaka',N'ΔΗΜΟΣ ΚΑΛΑΜΠΑΚΑΣ-MUNICIPALITY OF KALABAKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL611','2603','no',N'ΔΗΜΟΣ ΠΥΛΗΣ-Municipality of Pyli',N'ΔΗΜΟΣ ΠΥΛΗΣ-MUNICIPALITY OF PYLI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL611','2604','no',N'ΔΗΜΟΣ ΦΑΡΚΑΔΟΝΑΣ-Municipality of Farkadona',N'ΔΗΜΟΣ ΦΑΡΚΑΔΟΝΑΣ-MUNICIPALITY OF FARKADONA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL644','2701','no',N'ΔΗΜΟΣ ΛΑΜΙΕΩΝ-Municipality of Lamia',N'ΔΗΜΟΣ ΛΑΜΙΕΩΝ-MUNICIPALITY OF LAMIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL644','2702','no',N'ΔΗΜΟΣ ΑΜΦΙΚΛΕΙΑΣ - ΕΛΑΤΕΙΑΣ-Municipality of Amfiklia - Elatia',N'ΔΗΜΟΣ ΑΜΦΙΚΛΕΙΑΣ - ΕΛΑΤΕΙΑΣ-MUNICIPALITY OF AMFIKLIA - ELATIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL644','2703','no',N'ΔΗΜΟΣ ΔΟΜΟΚΟΥ-Municipality of Domokos',N'ΔΗΜΟΣ ΔΟΜΟΚΟΥ-MUNICIPALITY OF DOMOKOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL644','2704','no',N'ΔΗΜΟΣ ΛΟΚΡΩΝ-Municipality of Lokri',N'ΔΗΜΟΣ ΛΟΚΡΩΝ-MUNICIPALITY OF LOKRI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL644','2705','no',N'ΔΗΜΟΣ ΜΑΚΡΑΚΩΜΗΣ-Municipality of Makrakomi',N'ΔΗΜΟΣ ΜΑΚΡΑΚΩΜΗΣ-MUNICIPALITY OF MAKRAKOMI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL644','2706','no',N'ΔΗΜΟΣ ΜΩΛΟΥ - ΑΓ. ΚΩΝΣΤΑΝΤΙΝΟΥ-Municipality of Molos - Aghios Konstantinos',N'ΔΗΜΟΣ ΜΩΛΟΥ - ΑΓ. ΚΩΝΣΤΑΝΤΙΝΟΥ-MUNICIPALITY OF MOLOS - AGHIOS KONSTANTINOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL644','2707','no',N'ΔΗΜΟΣ ΣΤΥΛΙΔΑΣ-Municipality of Stylida',N'ΔΗΜΟΣ ΣΤΥΛΙΔΑΣ-MUNICIPALITY OF STYLIDA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL641','2801','no',N'ΔΗΜΟΣ ΛΕΒΑΔΕΩΝ-Municipality of Levadia',N'ΔΗΜΟΣ ΛΕΒΑΔΕΩΝ-MUNICIPALITY OF LEVADIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL641','2802','no',N'ΔΗΜΟΣ ΑΛΙΑΡΤΟΥ-ΘΕΣΠΙΕΩΝ-Municipality of Aliartos - Thespies',N'ΔΗΜΟΣ ΑΛΙΑΡΤΟΥ-ΘΕΣΠΙΕΩΝ-MUNICIPALITY OF ALIARTOS - THESPIES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL641','2803','no',N'ΔΗΜΟΣ ΔΙΣΤΟΜΟΥ-ΑΡΑΧΟΒΑΣ - ΑΝΤΙΚΥΡΑΣ-Municipality of Distomo - Arachova - Antikyra',N'ΔΗΜΟΣ ΔΙΣΤΟΜΟΥ-ΑΡΑΧΟΒΑΣ - ΑΝΤΙΚΥΡΑΣ-MUNICIPALITY OF DISTOMO - ARACHOVA - ANTIKYRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL641','2804','no',N'ΔΗΜΟΣ ΘΗΒΑΙΩΝ-Municipality of Thiva',N'ΔΗΜΟΣ ΘΗΒΑΙΩΝ-MUNICIPALITY OF THIVA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL641','2805','no',N'ΔΗΜΟΣ ΟΡΧΟΜΕΝΟΥ-Municipality of Orchomenos',N'ΔΗΜΟΣ ΟΡΧΟΜΕΝΟΥ-MUNICIPALITY OF ORCHOMENOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL641','2806','no',N'ΔΗΜΟΣ ΤΑΝΑΓΡΑΣ-Municipality of Tanagra',N'ΔΗΜΟΣ ΤΑΝΑΓΡΑΣ-MUNICIPALITY OF TANAGRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL642','2901','no',N'ΔΗΜΟΣ ΧΑΛΚΙΔΕΩΝ-Municipality of Chalkida',N'ΔΗΜΟΣ ΧΑΛΚΙΔΕΩΝ-MUNICIPALITY OF CHALKIDA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL642','2902','no',N'ΔΗΜΟΣ ΔΙΡΦΥΩΝ - ΜΕΣΣΑΠΙΩΝ-Municipality of Dirfys - Messapia',N'ΔΗΜΟΣ ΔΙΡΦΥΩΝ - ΜΕΣΣΑΠΙΩΝ-MUNICIPALITY OF DIRFYS - MESSAPIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL642','2903','no',N'ΔΗΜΟΣ ΕΡΕΤΡΙΑΣ-Municipality of Eretria',N'ΔΗΜΟΣ ΕΡΕΤΡΙΑΣ-MUNICIPALITY OF ERETRIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL642','2904','no',N'ΔΗΜΟΣ ΙΣΤΙΑΙΑΣ - ΑΙΔΗΨΟΥ-Municipality of Istiea - Aedipsos',N'ΔΗΜΟΣ ΙΣΤΙΑΙΑΣ - ΑΙΔΗΨΟΥ-MUNICIPALITY OF ISTIEA - AEDIPSOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL642','2905','no',N'ΔΗΜΟΣ ΚΑΡΥΣΤΟΥ-Municipality of Karystos',N'ΔΗΜΟΣ ΚΑΡΥΣΤΟΥ-MUNICIPALITY OF KARYSTOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL642','2906','no',N'ΔΗΜΟΣ ΚΥΜΗΣ - ΑΛΙΒΕΡΙΟΥ-Municipality of Kymi - Aliveri',N'ΔΗΜΟΣ ΚΥΜΗΣ - ΑΛΙΒΕΡΙΟΥ-MUNICIPALITY OF KYMI - ALIVERI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL642','2907','no',N'ΔΗΜΟΣ ΜΑΝΤΟΥΔΙΟΥ - ΛΙΜΝΗΣ - ΑΓΙΑΣ ΑΝΝΑΣ-Municipality of Mantoudi - Limni - Aghia Anna',N'ΔΗΜΟΣ ΜΑΝΤΟΥΔΙΟΥ - ΛΙΜΝΗΣ - ΑΓΙΑΣ ΑΝΝΑΣ-MUNICIPALITY OF MANTOUDI - LIMNI - AGHIA ANNA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL642','2908','no',N'ΔΗΜΟΣ ΣΚΥΡΟΥ-Municipality of Skyros',N'ΔΗΜΟΣ ΣΚΥΡΟΥ-MUNICIPALITY OF SKYROS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL643','3001','no',N'ΔΗΜΟΣ ΚΑΡΠΕΝΗΣΙΟΥ-Municipality of Karpenissi',N'ΔΗΜΟΣ ΚΑΡΠΕΝΗΣΙΟΥ-MUNICIPALITY OF KARPENISSI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL643','3002','no',N'ΔΗΜΟΣ ΑΓΡΑΦΩΝ-Municipality of Agrafa',N'ΔΗΜΟΣ ΑΓΡΑΦΩΝ-MUNICIPALITY OF AGRAFA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL645','3101','no',N'ΔΗΜΟΣ ΔΕΛΦΩΝ-Municipality of Delfi',N'ΔΗΜΟΣ ΔΕΛΦΩΝ-MUNICIPALITY OF DELFI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL645','3102','no',N'ΔΗΜΟΣ ΔΩΡΙΔΟΣ-Municipality of Doris',N'ΔΗΜΟΣ ΔΩΡΙΔΟΣ-MUNICIPALITY OF DORIS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL622','3201','no',N'ΔΗΜΟΣ ΚΕΡΚΥΡΑΣ-Municipality of Kerkyra',N'ΔΗΜΟΣ ΚΕΡΚΥΡΑΣ-MUNICIPALITY OF KERKYRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL622','3202','no',N'ΔΗΜΟΣ ΠΑΞΩΝ-Municipality of Paxi',N'ΔΗΜΟΣ ΠΑΞΩΝ-MUNICIPALITY OF PAXI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL621','3301','no',N'ΔΗΜΟΣ ΖΑΚΥΝΘΟΥ-Municipality of Zakynthos',N'ΔΗΜΟΣ ΖΑΚΥΝΘΟΥ-MUNICIPALITY OF ZAKYNTHOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL623','3401','no',N'ΔΗΜΟΣ ΙΘΑΚΗΣ-Municipality of Ithaki',N'ΔΗΜΟΣ ΙΘΑΚΗΣ-MUNICIPALITY OF ITHAKI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL623','3501','no',N'ΔΗΜΟΣ ΚΕΦΑΛΛΟΝΙΑΣ-Municipality of Kefalonia',N'ΔΗΜΟΣ ΚΕΦΑΛΛΟΝΙΑΣ-MUNICIPALITY OF KEFALONIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL624','3601','no',N'ΔΗΜΟΣ ΛΕΥΚΑΔΑΣ-Municipality of Lefkada',N'ΔΗΜΟΣ ΛΕΥΚΑΔΑΣ-MUNICIPALITY OF LEFKADA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL624','3602','no',N'ΔΗΜΟΣ ΜΕΓΑΝΗΣΙΟΥ-Municipality of Meganissi',N'ΔΗΜΟΣ ΜΕΓΑΝΗΣΙΟΥ-MUNICIPALITY OF MEGANISSI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL632','3701','no',N'ΔΗΜΟΣ ΠΑΤΡΕΩΝ-Municipality of Patra',N'ΔΗΜΟΣ ΠΑΤΡΕΩΝ-MUNICIPALITY OF PATRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL632','3702','no',N'ΔΗΜΟΣ ΑΙΓΙΑΛΕΙΑΣ-Municipality of Aegialia',N'ΔΗΜΟΣ ΑΙΓΙΑΛΕΙΑΣ-MUNICIPALITY OF AEGIALIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL632','3703','no',N'ΔΗΜΟΣ ΔΥΤΙΚΗΣ ΑΧΑΙΑΣ-Municipality of Dytiki Achaia',N'ΔΗΜΟΣ ΔΥΤΙΚΗΣ ΑΧΑΙΑΣ-MUNICIPALITY OF DYTIKI ACHAIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL632','3704','no',N'ΔΗΜΟΣ ΕΡΥΜΑΝΘΟΥ-Municipality of Erymanthos',N'ΔΗΜΟΣ ΕΡΥΜΑΝΘΟΥ-MUNICIPALITY OF ERYMANTHOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL632','3705','no',N'ΔΗΜΟΣ ΚΑΛΑΒΡΥΤΩΝ-Municipality of Kalavryta',N'ΔΗΜΟΣ ΚΑΛΑΒΡΥΤΩΝ-MUNICIPALITY OF KALAVRYTA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL631','3801','no',N'ΔΗΜΟΣ ΙΕΡΑΣ ΠΟΛΗΣ ΜΕΣΟΛΟΓΓΙΟΥ-Municipality of Iera Poli Messologhiou ',N'ΔΗΜΟΣ ΙΕΡΑΣ ΠΟΛΗΣ ΜΕΣΟΛΟΓΓΙΟΥ-MUNICIPALITY OF IERA POLI MESSOLOGHIOU ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL631','3802','no',N'ΔΗΜΟΣ ΑΚΤΙΟΥ - ΒΟΝΙΤΣΑΣ-Municipality of Aktio - Vonitsa',N'ΔΗΜΟΣ ΑΚΤΙΟΥ - ΒΟΝΙΤΣΑΣ-MUNICIPALITY OF AKTIO - VONITSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL631','3803','no',N'ΔΗΜΟΣ ΑΓΡΙΝΙΟΥ-Municipality of Agrinio',N'ΔΗΜΟΣ ΑΓΡΙΝΙΟΥ-MUNICIPALITY OF AGRINIO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL631','3804','no',N'ΔΗΜΟΣ ΑΜΦΙΛΟΧΙΑΣ-Municipality of Amfilochia',N'ΔΗΜΟΣ ΑΜΦΙΛΟΧΙΑΣ-MUNICIPALITY OF AMFILOCHIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL631','3805','no',N'ΔΗΜΟΣ ΘΕΡΜΟΥ-Municipality of Thermo',N'ΔΗΜΟΣ ΘΕΡΜΟΥ-MUNICIPALITY OF THERMO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL631','3806','no',N'ΔΗΜΟΣ ΝΑΥΠΑΚΤΙΑΣ-Municipality of Nafpaktia',N'ΔΗΜΟΣ ΝΑΥΠΑΚΤΙΑΣ-MUNICIPALITY OF NAFPAKTIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL631','3807','no',N'ΔΗΜΟΣ ΞΗΡΟΜΕΡΟΥ-Municipality of Xiromero',N'ΔΗΜΟΣ ΞΗΡΟΜΕΡΟΥ-MUNICIPALITY OF XIROMERO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL633','3901','no',N'ΔΗΜΟΣ ΠΥΡΓΟΥ-Municipality of Pyrgos',N'ΔΗΜΟΣ ΠΥΡΓΟΥ-MUNICIPALITY OF PYRGOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL633','3902','no',N'ΔΗΜΟΣ ΉΛΙΔΑΣ-Municipality of Ilida',N'ΔΗΜΟΣ ΉΛΙΔΑΣ-MUNICIPALITY OF ILIDA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL633','3903','no',N'ΔΗΜΟΣ ΑΝΔΡΑΒΙΔΑΣ - ΚΥΛΛΗΝΗΣ-Municipality of Andravida - Kyllini',N'ΔΗΜΟΣ ΑΝΔΡΑΒΙΔΑΣ - ΚΥΛΛΗΝΗΣ-MUNICIPALITY OF ANDRAVIDA - KYLLINI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL633','3904','no',N'ΔΗΜΟΣ ΑΝΔΡΙΤΣΑΙΝΑΣ - ΚΡΕΣΤΕΝΩΝ-Municipality of Andritsena - Krestena',N'ΔΗΜΟΣ ΑΝΔΡΙΤΣΑΙΝΑΣ - ΚΡΕΣΤΕΝΩΝ-MUNICIPALITY OF ANDRITSENA - KRESTENA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL633','3905','no',N'ΔΗΜΟΣ ΑΡΧΑΙΑΣ ΟΛΥΜΠΙΑΣ-Municipality of Olympia',N'ΔΗΜΟΣ ΑΡΧΑΙΑΣ ΟΛΥΜΠΙΑΣ-MUNICIPALITY OF OLYMPIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL633','3906','no',N'ΔΗΜΟΣ ΖΑΧΑΡΩΣ-Municipality of Zacharo',N'ΔΗΜΟΣ ΖΑΧΑΡΩΣ-MUNICIPALITY OF ZACHARO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL633','3907','no',N'ΔΗΜΟΣ ΠΗΝΕΙΟΥ-Municipality of Pinios',N'ΔΗΜΟΣ ΠΗΝΕΙΟΥ-MUNICIPALITY OF PINIOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL651','4001','no',N'ΔΗΜΟΣ ΤΡΙΠΟΛΗΣ-Municipality of Tripoli',N'ΔΗΜΟΣ ΤΡΙΠΟΛΗΣ-MUNICIPALITY OF TRIPOLI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL651','4002','no',N'ΔΗΜΟΣ ΒΟΡΕΙΑΣ ΚΥΝΟΥΡΙΑΣ-Municipality of Voria Kynouria',N'ΔΗΜΟΣ ΒΟΡΕΙΑΣ ΚΥΝΟΥΡΙΑΣ-MUNICIPALITY OF VORIA KYNOURIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL651','4003','no',N'ΔΗΜΟΣ ΓΟΡΤΥΝΙΑΣ-Municipality of Gortynia',N'ΔΗΜΟΣ ΓΟΡΤΥΝΙΑΣ-MUNICIPALITY OF GORTYNIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL651','4004','no',N'ΔΗΜΟΣ ΜΕΓΑΛΟΠΟΛΗΣ-Municipality of Megalopoli',N'ΔΗΜΟΣ ΜΕΓΑΛΟΠΟΛΗΣ-MUNICIPALITY OF MEGALOPOLI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL651','4005','no',N'ΔΗΜΟΣ ΝΟΤΙΑΣ ΚΥΝΟΥΡΙΑΣ-Municipality of Notia Kynouria',N'ΔΗΜΟΣ ΝΟΤΙΑΣ ΚΥΝΟΥΡΙΑΣ-MUNICIPALITY OF NOTIA KYNOURIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL651','4101','no',N'ΔΗΜΟΣ ΝΑΥΠΛΙΕΩΝ-Municipality of Nafplio',N'ΔΗΜΟΣ ΝΑΥΠΛΙΕΩΝ-MUNICIPALITY OF NAFPLIO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL651','4102','no',N'ΔΗΜΟΣ ΆΡΓΟΥΣ - ΜΥΚΗΝΩΝ-Municipality of Argos - Mykines',N'ΔΗΜΟΣ ΆΡΓΟΥΣ - ΜΥΚΗΝΩΝ-MUNICIPALITY OF ARGOS - MYKINES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL651','4103','no',N'ΔΗΜΟΣ ΕΠΙΔΑΥΡΟΥ-Municipality of Epidavros',N'ΔΗΜΟΣ ΕΠΙΔΑΥΡΟΥ-MUNICIPALITY OF EPIDAVROS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL651','4104','no',N'ΔΗΜΟΣ ΕΡΜΙΟΝΙΔΑΣ-Municipality of Ermionida',N'ΔΗΜΟΣ ΕΡΜΙΟΝΙΔΑΣ-MUNICIPALITY OF ERMIONIDA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL652','4201','no',N'ΔΗΜΟΣ ΚΟΡΙΝΘΙΩΝ-Municipality of Korinthos',N'ΔΗΜΟΣ ΚΟΡΙΝΘΙΩΝ-MUNICIPALITY OF KORINTHOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL652','4202','no',N'ΔΗΜΟΣ ΒΕΛΟΥ - ΒΟΧΑΣ-Municipality of Velo - Vocha',N'ΔΗΜΟΣ ΒΕΛΟΥ - ΒΟΧΑΣ-MUNICIPALITY OF VELO - VOCHA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL652','4203','no',N'ΔΗΜΟΣ ΛΟΥΤΡΑΚΙΟΥ-ΠΕΡΑΧΩΡΑΣ-ΑΓ. ΘΕΟΔΩΡΩΝ-Municipality of Loutraki - Perachora - Aghii Theodori',N'ΔΗΜΟΣ ΛΟΥΤΡΑΚΙΟΥ-ΠΕΡΑΧΩΡΑΣ-ΑΓ. ΘΕΟΔΩΡΩΝ-MUNICIPALITY OF LOUTRAKI - PERACHORA - AGHII THEODORI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL652','4204','no',N'ΔΗΜΟΣ ΝΕΜΕΑΣ-Municipality of Nemea',N'ΔΗΜΟΣ ΝΕΜΕΑΣ-MUNICIPALITY OF NEMEA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL652','4205','no',N'ΔΗΜΟΣ ΞΥΛΟΚΑΣΤΡΟΥ - ΕΥΡΩΣΤΙΝΗΣ-Municipality of Xylokastro - Evrostina',N'ΔΗΜΟΣ ΞΥΛΟΚΑΣΤΡΟΥ - ΕΥΡΩΣΤΙΝΗΣ-MUNICIPALITY OF XYLOKASTRO - EVROSTINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL652','4206','no',N'ΔΗΜΟΣ ΣΙΚΥΩΝΙΩΝ-Municipality of Sikyon',N'ΔΗΜΟΣ ΣΙΚΥΩΝΙΩΝ-MUNICIPALITY OF SIKYON');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL653','4301','no',N'ΔΗΜΟΣ ΣΠΑΡΤΗΣ-Municipality of Sparti',N'ΔΗΜΟΣ ΣΠΑΡΤΗΣ-MUNICIPALITY OF SPARTI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL653','4302','no',N'ΔΗΜΟΣ ΑΝΑΤΟΛΙΚΗΣ ΜΑΝΗΣ-Municipality of Anatoliki Mani',N'ΔΗΜΟΣ ΑΝΑΤΟΛΙΚΗΣ ΜΑΝΗΣ-MUNICIPALITY OF ANATOLIKI MANI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL653','4303','no',N'ΔΗΜΟΣ ΕΛΑΦΟΝΗΣΟΥ-Municipality of Elafonissos',N'ΔΗΜΟΣ ΕΛΑΦΟΝΗΣΟΥ-MUNICIPALITY OF ELAFONISSOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL653','4304','no',N'ΔΗΜΟΣ ΕΥΡΩΤΑ-Municipality of Evrotas',N'ΔΗΜΟΣ ΕΥΡΩΤΑ-MUNICIPALITY OF EVROTAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL653','4305','no',N'ΔΗΜΟΣ ΜΟΝΕΜΒΑΣΙΑΣ-Municipality of Monemvassia',N'ΔΗΜΟΣ ΜΟΝΕΜΒΑΣΙΑΣ-MUNICIPALITY OF MONEMVASSIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL653','4401','no',N'ΔΗΜΟΣ ΚΑΛΑΜΑΤΑΣ-Municipality of Kalamata',N'ΔΗΜΟΣ ΚΑΛΑΜΑΤΑΣ-MUNICIPALITY OF KALAMATA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL653','4402','no',N'ΔΗΜΟΣ ΔΥΤΙΚΗΣ ΜΑΝΗΣ-Municipality of Dytiki Mani',N'ΔΗΜΟΣ ΔΥΤΙΚΗΣ ΜΑΝΗΣ-MUNICIPALITY OF DYTIKI MANI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL653','4403','no',N'ΔΗΜΟΣ ΜΕΣΣΗΝΗΣ-Municipality of Messini',N'ΔΗΜΟΣ ΜΕΣΣΗΝΗΣ-MUNICIPALITY OF MESSINI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL653','4404','no',N'ΔΗΜΟΣ ΟΙΧΑΛΙΑΣ-Municipality of Ichalia',N'ΔΗΜΟΣ ΟΙΧΑΛΙΑΣ-MUNICIPALITY OF ICHALIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL653','4405','no',N'ΔΗΜΟΣ ΠΥΛΟΥ - ΝΕΣΤΟΡΟΣ-Municipality of Pylos - Nestor',N'ΔΗΜΟΣ ΠΥΛΟΥ - ΝΕΣΤΟΡΟΣ-MUNICIPALITY OF PYLOS - NESTOR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL653','4406','no',N'ΔΗΜΟΣ ΤΡΙΦΥΛΙΑΣ-Municipality of Trifylia',N'ΔΗΜΟΣ ΤΡΙΦΥΛΙΑΣ-MUNICIPALITY OF TRIFYLIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL303','4501','no',N'ΔΗΜΟΣ ΑΘΗΝΑΙΩΝ-Municipality of Athens',N'ΔΗΜΟΣ ΑΘΗΝΑΙΩΝ-MUNICIPALITY OF ATHENS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL303','4502','no',N'ΔΗΜΟΣ ΒΥΡΩΝΟΣ-Municipality of Vyron',N'ΔΗΜΟΣ ΒΥΡΩΝΟΣ-MUNICIPALITY OF VYRON');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL303','4503','no',N'ΔΗΜΟΣ ΓΑΛΑΤΣΙΟΥ-Municipality of Galatsi',N'ΔΗΜΟΣ ΓΑΛΑΤΣΙΟΥ-MUNICIPALITY OF GALATSI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL303','4504','no',N'ΔΗΜΟΣ ΔΑΦΝΗΣ - ΥΜΗΤΤΟΥ-Municipality of Dafni - Ymittos',N'ΔΗΜΟΣ ΔΑΦΝΗΣ - ΥΜΗΤΤΟΥ-MUNICIPALITY OF DAFNI - YMITTOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL303','4505','no',N'ΔΗΜΟΣ ΖΩΓΡΑΦΟΥ-Municipality of Zografos',N'ΔΗΜΟΣ ΖΩΓΡΑΦΟΥ-MUNICIPALITY OF ZOGRAFOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL303','4506','no',N'ΔΗΜΟΣ ΗΛΙΟΥΠΟΛΕΩΣ-Municipality of Ilioupoli',N'ΔΗΜΟΣ ΗΛΙΟΥΠΟΛΕΩΣ-MUNICIPALITY OF ILIOUPOLI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL303','4507','no',N'ΔΗΜΟΣ ΚΑΙΣΑΡΙΑΝΗΣ-Municipality of Kessariani',N'ΔΗΜΟΣ ΚΑΙΣΑΡΙΑΝΗΣ-MUNICIPALITY OF KESSARIANI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL303','4508','no',N'ΔΗΜΟΣ ΝΕΑΣ ΦΙΛΑΔΕΛΦΕΙΑΣ - ΝΕΑΣ ΧΑΛΚΗΔΟΝΑΣ-Municipality of Nea Philadelfia - Nea Chalkidona',N'ΔΗΜΟΣ ΝΕΑΣ ΦΙΛΑΔΕΛΦΕΙΑΣ - ΝΕΑΣ ΧΑΛΚΗΔΟΝΑΣ-MUNICIPALITY OF NEA PHILADELFIA - NEA CHALKIDONA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL301','4601','no',N'ΔΗΜΟΣ ΑΜΑΡΟΥΣΙΟΥ-Municipality of Amaroussio',N'ΔΗΜΟΣ ΑΜΑΡΟΥΣΙΟΥ-MUNICIPALITY OF AMAROUSSIO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL301','4602','no',N'ΔΗΜΟΣ ΑΓΙΑΣ ΠΑΡΑΣΚΕΥΗΣ-Municipality of Aghia Paraskevi',N'ΔΗΜΟΣ ΑΓΙΑΣ ΠΑΡΑΣΚΕΥΗΣ-MUNICIPALITY OF AGHIA PARASKEVI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL301','4603','no',N'ΔΗΜΟΣ ΒΡΙΛΗΣΣΙΩΝ-Municipality of Vrilissia',N'ΔΗΜΟΣ ΒΡΙΛΗΣΣΙΩΝ-MUNICIPALITY OF VRILISSIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL301','4604','no',N'ΔΗΜΟΣ ΗΡΑΚΛΕΙΟΥ ΑΤΤΙΚΗΣ-Municipality of Iraklio',N'ΔΗΜΟΣ ΗΡΑΚΛΕΙΟΥ ΑΤΤΙΚΗΣ-MUNICIPALITY OF IRAKLIO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL301','4605','no',N'ΔΗΜΟΣ ΚΗΦΙΣΙΑΣ-Municipality of Kifissia',N'ΔΗΜΟΣ ΚΗΦΙΣΙΑΣ-MUNICIPALITY OF KIFISSIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL301','4606','no',N'ΔΗΜΟΣ ΛΥΚΟΒΡΥΣΗΣ - ΠΕΥΚΗΣ-Municipality of Lykovryssi - Pefki',N'ΔΗΜΟΣ ΛΥΚΟΒΡΥΣΗΣ - ΠΕΥΚΗΣ-MUNICIPALITY OF LYKOVRYSSI - PEFKI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL301','4607','no',N'ΔΗΜΟΣ ΜΕΤΑΜΟΡΦΩΣΕΩΣ-Municipality of Metamorfossi',N'ΔΗΜΟΣ ΜΕΤΑΜΟΡΦΩΣΕΩΣ-MUNICIPALITY OF METAMORFOSSI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL301','4608','no',N'ΔΗΜΟΣ ΝΕΑΣ ΙΩΝΙΑΣ-Municipality of Nea Ionia',N'ΔΗΜΟΣ ΝΕΑΣ ΙΩΝΙΑΣ-MUNICIPALITY OF NEA IONIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL301','4609','no',N'ΔΗΜΟΣ ΠΑΠΑΓΟΥ - ΧΟΛΑΡΓΟΥ-Municipality of Papagos - Cholargos',N'ΔΗΜΟΣ ΠΑΠΑΓΟΥ - ΧΟΛΑΡΓΟΥ-MUNICIPALITY OF PAPAGOS - CHOLARGOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL301','4610','no',N'ΔΗΜΟΣ ΠΕΝΤΕΛΗΣ-Municipality of Penteli',N'ΔΗΜΟΣ ΠΕΝΤΕΛΗΣ-MUNICIPALITY OF PENTELI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL301','4611','no',N'ΔΗΜΟΣ ΦΙΛΟΘΕΗΣ - ΨΥΧΙΚΟΥ-Municipality of Filothei - Psychiko',N'ΔΗΜΟΣ ΦΙΛΟΘΕΗΣ - ΨΥΧΙΚΟΥ-MUNICIPALITY OF FILOTHEI - PSYCHIKO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL301','4612','no',N'ΔΗΜΟΣ ΧΑΛΑΝΔΡΙΟΥ-Municipality of Chalandri',N'ΔΗΜΟΣ ΧΑΛΑΝΔΡΙΟΥ-MUNICIPALITY OF CHALANDRI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL302','4701','no',N'ΔΗΜΟΣ ΠΕΡΙΣΤΕΡΙΟΥ-Municipality of Peristeri',N'ΔΗΜΟΣ ΠΕΡΙΣΤΕΡΙΟΥ-MUNICIPALITY OF PERISTERI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL302','4702','no',N'ΔΗΜΟΣ ΑΓΙΑΣ ΒΑΡΒΑΡΑΣ-Municipality of Aghia Varvara',N'ΔΗΜΟΣ ΑΓΙΑΣ ΒΑΡΒΑΡΑΣ-MUNICIPALITY OF AGHIA VARVARA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL302','4703','no',N'ΔΗΜΟΣ ΑΓΙΩΝ ΑΝΑΡΓΥΡΩΝ - ΚΑΜΑΤΕΡΟΥ-Municipality of Aghii Anargyri - Kamatero',N'ΔΗΜΟΣ ΑΓΙΩΝ ΑΝΑΡΓΥΡΩΝ - ΚΑΜΑΤΕΡΟΥ-MUNICIPALITY OF AGHII ANARGYRI - KAMATERO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL302','4704','no',N'ΔΗΜΟΣ ΑΙΓΑΛΕΩ-Municipality of Aegaleo',N'ΔΗΜΟΣ ΑΙΓΑΛΕΩ-MUNICIPALITY OF AEGALEO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL302','4705','no',N'ΔΗΜΟΣ ΙΛΙΟΥ-Municipality of Ilio',N'ΔΗΜΟΣ ΙΛΙΟΥ-MUNICIPALITY OF ILIO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL302','4706','no',N'ΔΗΜΟΣ ΠΕΤΡΟΥΠΟΛΕΩΣ-Municipality of Petroupoli',N'ΔΗΜΟΣ ΠΕΤΡΟΥΠΟΛΕΩΣ-MUNICIPALITY OF PETROUPOLI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL302','4707','no',N'ΔΗΜΟΣ ΧΑΪΔΑΡΙΟΥ-Municipality of Chaidari',N'ΔΗΜΟΣ ΧΑΪΔΑΡΙΟΥ-MUNICIPALITY OF CHAIDARI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL304','4801','no',N'ΔΗΜΟΣ ΚΑΛΛΙΘΕΑΣ-Municipality of Kallithea',N'ΔΗΜΟΣ ΚΑΛΛΙΘΕΑΣ-MUNICIPALITY OF KALLITHEA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL304','4802','no',N'ΔΗΜΟΣ ΑΓΙΟΥ ΔΗΜΗΤΡΙΟΥ-Municipality of Aghios Dimitrios',N'ΔΗΜΟΣ ΑΓΙΟΥ ΔΗΜΗΤΡΙΟΥ-MUNICIPALITY OF AGHIOS DIMITRIOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL304','4803','no',N'ΔΗΜΟΣ ΑΛΙΜΟΥ-Municipality of Alimos',N'ΔΗΜΟΣ ΑΛΙΜΟΥ-MUNICIPALITY OF ALIMOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL304','4804','no',N'ΔΗΜΟΣ ΓΛΥΦΑΔΑΣ-Municipality of Glyfada',N'ΔΗΜΟΣ ΓΛΥΦΑΔΑΣ-MUNICIPALITY OF GLYFADA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL304','4805','no',N'ΔΗΜΟΣ ΕΛΛΗΝΙΚΟΥ - ΑΡΓΥΡΟΥΠΟΛΗΣ-Municipality of Elliniko - Argyroupoli',N'ΔΗΜΟΣ ΕΛΛΗΝΙΚΟΥ - ΑΡΓΥΡΟΥΠΟΛΗΣ-MUNICIPALITY OF ELLINIKO - ARGYROUPOLI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL304','4806','no',N'ΔΗΜΟΣ ΜΟΣΧΑΤΟΥ - ΤΑΥΡΟΥ-Municipality of Moschato - Tavros',N'ΔΗΜΟΣ ΜΟΣΧΑΤΟΥ - ΤΑΥΡΟΥ-MUNICIPALITY OF MOSCHATO - TAVROS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL304','4807','no',N'ΔΗΜΟΣ ΝΕΑΣ ΣΜΥΡΝΗΣ-Municipality of Nea Smyrni',N'ΔΗΜΟΣ ΝΕΑΣ ΣΜΥΡΝΗΣ-MUNICIPALITY OF NEA SMYRNI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL304','4808','no',N'ΔΗΜΟΣ ΠΑΛΑΙΟΥ ΦΑΛΗΡΟΥ-Municipality of Paleo Faliro',N'ΔΗΜΟΣ ΠΑΛΑΙΟΥ ΦΑΛΗΡΟΥ-MUNICIPALITY OF PALEO FALIRO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL305','4901','no',N'ΔΗΜΟΣ ΑΧΑΡΝΩΝ-Municipality of Acharnes',N'ΔΗΜΟΣ ΑΧΑΡΝΩΝ-MUNICIPALITY OF ACHARNES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL305','4902','no',N'ΔΗΜΟΣ ΒΑΡΗΣ - ΒΟΥΛΑΣ - ΒΟΥΛΙΑΓΜΕΝΗΣ-Municipality of Vari - Voula - Vouliagmeni',N'ΔΗΜΟΣ ΒΑΡΗΣ - ΒΟΥΛΑΣ - ΒΟΥΛΙΑΓΜΕΝΗΣ-MUNICIPALITY OF VARI - VOULA - VOULIAGMENI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL305','4903','no',N'ΔΗΜΟΣ ΔΙΟΝΥΣΟΥ-Municipality of Dionyssos',N'ΔΗΜΟΣ ΔΙΟΝΥΣΟΥ-MUNICIPALITY OF DIONYSSOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL305','4904','no',N'ΔΗΜΟΣ ΚΡΩΠΙΑΣ-Municipality of Koropi',N'ΔΗΜΟΣ ΚΡΩΠΙΑΣ-MUNICIPALITY OF KOROPI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL305','4905','no',N'ΔΗΜΟΣ ΛΑΥΡΕΩΤΙΚΗΣ-Municipality of Lavrio',N'ΔΗΜΟΣ ΛΑΥΡΕΩΤΙΚΗΣ-MUNICIPALITY OF LAVRIO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL305','4906','no',N'ΔΗΜΟΣ ΜΑΡΑΘΩΝΟΣ-Municipality of Marathon',N'ΔΗΜΟΣ ΜΑΡΑΘΩΝΟΣ-MUNICIPALITY OF MARATHON');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL305','4907','no',N'ΔΗΜΟΣ ΜΑΡΚΟΠΟΥΛΟΥ ΜΕΣΟΓΑΙΑΣ-Municipality of Markopoulo Messogheas',N'ΔΗΜΟΣ ΜΑΡΚΟΠΟΥΛΟΥ ΜΕΣΟΓΑΙΑΣ-MUNICIPALITY OF MARKOPOULO MESSOGHEAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL305','4908','no',N'ΔΗΜΟΣ ΠΑΙΑΝΙΑΣ - ΓΛΥΚΩΝ ΝΕΡΩΝ-Municipality of Peania',N'ΔΗΜΟΣ ΠΑΙΑΝΙΑΣ - ΓΛΥΚΩΝ ΝΕΡΩΝ-MUNICIPALITY OF PEANIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL305','4909','no',N'ΔΗΜΟΣ ΠΑΛΛΗΝΗΣ-Municipality of Pallini',N'ΔΗΜΟΣ ΠΑΛΛΗΝΗΣ-MUNICIPALITY OF PALLINI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL305','4910','no',N'ΔΗΜΟΣ ΡΑΦΗΝΑΣ - ΠΙΚΕΡΜΙΟΥ-Municipality of Rafina - Pikermi',N'ΔΗΜΟΣ ΡΑΦΗΝΑΣ - ΠΙΚΕΡΜΙΟΥ-MUNICIPALITY OF RAFINA - PIKERMI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL305','4911','no',N'ΔΗΜΟΣ ΣΑΡΩΝΙΚΟΥ-Municipality of Saronikos',N'ΔΗΜΟΣ ΣΑΡΩΝΙΚΟΥ-MUNICIPALITY OF SARONIKOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL305','4912','no',N'ΔΗΜΟΣ ΣΠΑΤΩΝ - ΑΡΤΕΜΙΔΟΣ-Municipality of Spata - Artemis',N'ΔΗΜΟΣ ΣΠΑΤΩΝ - ΑΡΤΕΜΙΔΟΣ-MUNICIPALITY OF SPATA - ARTEMIS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL305','4913','no',N'ΔΗΜΟΣ ΩΡΩΠΟΥ-Municipality of Oropos',N'ΔΗΜΟΣ ΩΡΩΠΟΥ-MUNICIPALITY OF OROPOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL306','5001','no',N'ΔΗΜΟΣ ΕΛΕΥΣΙΝΑΣ-Municipality of Elefsina',N'ΔΗΜΟΣ ΕΛΕΥΣΙΝΑΣ-MUNICIPALITY OF ELEFSINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL306','5002','no',N'ΔΗΜΟΣ ΑΣΠΡΟΠΥΡΓΟΥ-Municipality of Aspropyrgos',N'ΔΗΜΟΣ ΑΣΠΡΟΠΥΡΓΟΥ-MUNICIPALITY OF ASPROPYRGOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL306','5003','no',N'ΔΗΜΟΣ ΜΑΝΔΡΑΣ - ΕΙΔΥΛΛΙΑΣ-Municipality of Mandra - Idyllia',N'ΔΗΜΟΣ ΜΑΝΔΡΑΣ - ΕΙΔΥΛΛΙΑΣ-MUNICIPALITY OF MANDRA - IDYLLIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL306','5004','no',N'ΔΗΜΟΣ ΜΕΓΑΡΕΩΝ-Municipality of Megara',N'ΔΗΜΟΣ ΜΕΓΑΡΕΩΝ-MUNICIPALITY OF MEGARA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL306','5005','no',N'ΔΗΜΟΣ ΦΥΛΗΣ-Municipality of Fyli',N'ΔΗΜΟΣ ΦΥΛΗΣ-MUNICIPALITY OF FYLI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL307','5101','no',N'ΔΗΜΟΣ ΠΕΙΡΑΙΩΣ-Municipality of Pireas',N'ΔΗΜΟΣ ΠΕΙΡΑΙΩΣ-MUNICIPALITY OF PIREAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL307','5102','no',N'ΔΗΜΟΣ ΚΕΡΑΤΣΙΝΙΟΥ - ΔΡΑΠΕΤΣΩΝΑΣ-Municipality of Keratsini - Drapetsona',N'ΔΗΜΟΣ ΚΕΡΑΤΣΙΝΙΟΥ - ΔΡΑΠΕΤΣΩΝΑΣ-MUNICIPALITY OF KERATSINI - DRAPETSONA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL307','5103','no',N'ΔΗΜΟΣ ΚΟΡΥΔΑΛΛΟΥ-Municipality of Korydallos',N'ΔΗΜΟΣ ΚΟΡΥΔΑΛΛΟΥ-MUNICIPALITY OF KORYDALLOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL307','5104','no',N'ΔΗΜΟΣ ΝΙΚΑΙΑΣ - ΑΓΙΟΥ ΙΩΑΝΝΗ ΡΕΝΤΗ-Municipality of Nikea - Aghios Ioannis Rentis',N'ΔΗΜΟΣ ΝΙΚΑΙΑΣ - ΑΓΙΟΥ ΙΩΑΝΝΗ ΡΕΝΤΗ-MUNICIPALITY OF NIKEA - AGHIOS IOANNIS RENTIS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL307','5105','no',N'ΔΗΜΟΣ ΠΕΡΑΜΑΤΟΣ-Municipality of Perama',N'ΔΗΜΟΣ ΠΕΡΑΜΑΤΟΣ-MUNICIPALITY OF PERAMA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL307','5201','no',N'ΔΗΜΟΣ ΣΑΛΑΜΙΝΟΣ-Municipality of Salamina',N'ΔΗΜΟΣ ΣΑΛΑΜΙΝΟΣ-MUNICIPALITY OF SALAMINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL307','5202','no',N'ΔΗΜΟΣ ΎΔΡΑΣ-Municipality of Ydra',N'ΔΗΜΟΣ ΎΔΡΑΣ-MUNICIPALITY OF YDRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL307','5203','no',N'ΔΗΜΟΣ ΑΓΚΙΣΤΡΙΟΥ-Municipality of Agistri',N'ΔΗΜΟΣ ΑΓΚΙΣΤΡΙΟΥ-MUNICIPALITY OF AGISTRI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL307','5204','no',N'ΔΗΜΟΣ ΑΙΓΙΝΑΣ-Municipality of Aegina',N'ΔΗΜΟΣ ΑΙΓΙΝΑΣ-MUNICIPALITY OF AEGINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL307','5205','no',N'ΔΗΜΟΣ ΚΥΘΗΡΩΝ-Municipality of Kythira',N'ΔΗΜΟΣ ΚΥΘΗΡΩΝ-MUNICIPALITY OF KYTHIRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL307','5206','no',N'ΔΗΜΟΣ ΠΟΡΟΥ-Municipality of Poros',N'ΔΗΜΟΣ ΠΟΡΟΥ-MUNICIPALITY OF POROS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL307','5207','no',N'ΔΗΜΟΣ ΣΠΕΤΣΩΝ-Municipality of Spetses',N'ΔΗΜΟΣ ΣΠΕΤΣΩΝ-MUNICIPALITY OF SPETSES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL307','5208','no',N'ΔΗΜΟΣ ΤΡΟΙΖΗΝΙΑΣ-ΜΕΘΑΝΩΝ-Municipality of Trizina - Methana',N'ΔΗΜΟΣ ΤΡΟΙΖΗΝΙΑΣ-ΜΕΘΑΝΩΝ-MUNICIPALITY OF TRIZINA - METHANA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL411','5301','no',N'ΔΗΜΟΣ ΛΕΣΒΟΥ-Municipality of Lesvos',N'ΔΗΜΟΣ ΛΕΣΒΟΥ-MUNICIPALITY OF LESVOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL412','5401','no',N'ΔΗΜΟΣ ΙΚΑΡΙΑΣ-Municipality of Ikaria',N'ΔΗΜΟΣ ΙΚΑΡΙΑΣ-MUNICIPALITY OF IKARIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL412','5402','no',N'ΔΗΜΟΣ ΦΟΥΡΝΩΝ ΚΟΡΣΕΩΝ-Municipality of Fourni Korseon',N'ΔΗΜΟΣ ΦΟΥΡΝΩΝ ΚΟΡΣΕΩΝ-MUNICIPALITY OF FOURNI KORSEON');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL411','5501','no',N'ΔΗΜΟΣ ΛΗΜΝΟΥ-Municipality of Limnos',N'ΔΗΜΟΣ ΛΗΜΝΟΥ-MUNICIPALITY OF LIMNOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL411','5502','no',N'ΔΗΜΟΣ ΑΓΙΟΥ ΕΥΣΤΡΑΤΙΟΥ-Municipality of Aghios Efstratios',N'ΔΗΜΟΣ ΑΓΙΟΥ ΕΥΣΤΡΑΤΙΟΥ-MUNICIPALITY OF AGHIOS EFSTRATIOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL412','5601','no',N'ΔΗΜΟΣ ΣΑΜΟΥ-Municipality of Samos',N'ΔΗΜΟΣ ΣΑΜΟΥ-MUNICIPALITY OF SAMOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL413','5701','no',N'ΔΗΜΟΣ ΧΙΟΥ-Municipality of Chios',N'ΔΗΜΟΣ ΧΙΟΥ-MUNICIPALITY OF CHIOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL413','5702','no',N'ΔΗΜΟΣ ΟΙΝΟΥΣΣΩΝ-Municipality of Inousses',N'ΔΗΜΟΣ ΟΙΝΟΥΣΣΩΝ-MUNICIPALITY OF INOUSSES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL413','5703','no',N'ΔΗΜΟΣ ΨΑΡΩΝ-Municipality of Psara',N'ΔΗΜΟΣ ΨΑΡΩΝ-MUNICIPALITY OF PSARA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL422','5801','no',N'ΔΗΜΟΣ ΣΥΡΟΥ - ΕΡΜΟΥΠΟΛΗΣ-Municipality of Syros - Ermoupoli',N'ΔΗΜΟΣ ΣΥΡΟΥ - ΕΡΜΟΥΠΟΛΗΣ-MUNICIPALITY OF SYROS - ERMOUPOLI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL422','5901','no',N'ΔΗΜΟΣ ΆΝΔΡΟΥ-Municipality of Andros',N'ΔΗΜΟΣ ΆΝΔΡΟΥ-MUNICIPALITY OF ANDROS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL422','6001','no',N'ΔΗΜΟΣ ΘΗΡΑΣ-Municipality of Thira',N'ΔΗΜΟΣ ΘΗΡΑΣ-MUNICIPALITY OF THIRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL422','6002','no',N'ΔΗΜΟΣ ΑΝΑΦΗΣ-Municipality of Anafi',N'ΔΗΜΟΣ ΑΝΑΦΗΣ-MUNICIPALITY OF ANAFI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL422','6003','no',N'ΔΗΜΟΣ ΙΗΤΩΝ-Municipality of Ios',N'ΔΗΜΟΣ ΙΗΤΩΝ-MUNICIPALITY OF IOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL422','6004','no',N'ΔΗΜΟΣ ΣΙΚΙΝΟΥ-Municipality of Sikinos',N'ΔΗΜΟΣ ΣΙΚΙΝΟΥ-MUNICIPALITY OF SIKINOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL422','6005','no',N'ΔΗΜΟΣ ΦΟΛΕΓΑΝΔΡΟΥ-Municipality of Folegandros',N'ΔΗΜΟΣ ΦΟΛΕΓΑΝΔΡΟΥ-MUNICIPALITY OF FOLEGANDROS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL421','6101','no',N'ΔΗΜΟΣ ΚΑΛΥΜΝΙΩΝ-Municipality of Kalymnos',N'ΔΗΜΟΣ ΚΑΛΥΜΝΙΩΝ-MUNICIPALITY OF KALYMNOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL421','6102','no',N'ΔΗΜΟΣ ΑΓΑΘΟΝΗΣΙΟΥ-Municipality of Agathonissi',N'ΔΗΜΟΣ ΑΓΑΘΟΝΗΣΙΟΥ-MUNICIPALITY OF AGATHONISSI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL421','6103','no',N'ΔΗΜΟΣ ΑΣΤΥΠΑΛΑΙΑΣ-Municipality of Astypalea',N'ΔΗΜΟΣ ΑΣΤΥΠΑΛΑΙΑΣ-MUNICIPALITY OF ASTYPALEA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL421','6104','no',N'ΔΗΜΟΣ ΛΕΙΨΩΝ-Municipality of Lipsi',N'ΔΗΜΟΣ ΛΕΙΨΩΝ-MUNICIPALITY OF LIPSI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL421','6105','no',N'ΔΗΜΟΣ ΛΕΡΟΥ-Municipality of Leros',N'ΔΗΜΟΣ ΛΕΡΟΥ-MUNICIPALITY OF LEROS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL421','6106','no',N'ΔΗΜΟΣ ΠΑΤΜΟΥ-Municipality of Patmos',N'ΔΗΜΟΣ ΠΑΤΜΟΥ-MUNICIPALITY OF PATMOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL421','6201','no',N'ΔΗΜΟΣ ΚΑΡΠΑΘΟΥ-Municipality of Karpathos',N'ΔΗΜΟΣ ΚΑΡΠΑΘΟΥ-MUNICIPALITY OF KARPATHOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL421','6202','no',N'ΔΗΜΟΣ ΚΑΣΟΥ-Municipality of Kassos',N'ΔΗΜΟΣ ΚΑΣΟΥ-MUNICIPALITY OF KASSOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL422','6301','no',N'ΔΗΜΟΣ ΚΕΑΣ-Municipality of Kea ',N'ΔΗΜΟΣ ΚΕΑΣ-MUNICIPALITY OF KEA ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL422','6302','no',N'ΔΗΜΟΣ ΚΥΘΝΟΥ-Municipality of Kythnos',N'ΔΗΜΟΣ ΚΥΘΝΟΥ-MUNICIPALITY OF KYTHNOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL421','6401','no',N'ΔΗΜΟΣ ΚΩ-Municipality of Kos',N'ΔΗΜΟΣ ΚΩ-MUNICIPALITY OF KOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL421','6402','no',N'ΔΗΜΟΣ ΝΙΣΥΡΟΥ-Municipality of Nissyros',N'ΔΗΜΟΣ ΝΙΣΥΡΟΥ-MUNICIPALITY OF NISSYROS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL422','6501','no',N'ΔΗΜΟΣ ΜΗΛΟΥ-Municipality of Milos',N'ΔΗΜΟΣ ΜΗΛΟΥ-MUNICIPALITY OF MILOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL422','6502','no',N'ΔΗΜΟΣ ΚΙΜΩΛΟΥ-Municipality of Kimolos',N'ΔΗΜΟΣ ΚΙΜΩΛΟΥ-MUNICIPALITY OF KIMOLOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL422','6503','no',N'ΔΗΜΟΣ ΣΕΡΙΦΟΥ-Municipality of Serifos',N'ΔΗΜΟΣ ΣΕΡΙΦΟΥ-MUNICIPALITY OF SERIFOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL422','6504','no',N'ΔΗΜΟΣ ΣΙΦΝΟΥ-Municipality of Sifnos',N'ΔΗΜΟΣ ΣΙΦΝΟΥ-MUNICIPALITY OF SIFNOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL422','6601','no',N'ΔΗΜΟΣ ΜΥΚΟΝΟΥ-Municipality of Mykonos',N'ΔΗΜΟΣ ΜΥΚΟΝΟΥ-MUNICIPALITY OF MYKONOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL422','6701','no',N'ΔΗΜΟΣ ΑΜΟΡΓΟΥ-Municipality of Amorgos',N'ΔΗΜΟΣ ΑΜΟΡΓΟΥ-MUNICIPALITY OF AMORGOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL422','6702','no',N'ΔΗΜΟΣ ΝΑΞΟΥ & ΜΙΚΡΩΝ ΚΥΚΛΑΔΩΝ-Municipality of Naxos - Mikres Kyklades',N'ΔΗΜΟΣ ΝΑΞΟΥ & ΜΙΚΡΩΝ ΚΥΚΛΑΔΩΝ-MUNICIPALITY OF NAXOS - MIKRES KYKLADES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL422','6801','no',N'ΔΗΜΟΣ ΠΑΡΟΥ-Municipality of Paros',N'ΔΗΜΟΣ ΠΑΡΟΥ-MUNICIPALITY OF PAROS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL422','6802','no',N'ΔΗΜΟΣ ΑΝΤΙΠΑΡΟΥ-Municipality of Antiparos',N'ΔΗΜΟΣ ΑΝΤΙΠΑΡΟΥ-MUNICIPALITY OF ANTIPAROS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL421','6901','no',N'ΔΗΜΟΣ ΡΟΔΟΥ-Municipality of Rodos',N'ΔΗΜΟΣ ΡΟΔΟΥ-MUNICIPALITY OF RODOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL421','6902','no',N'ΔΗΜΟΣ ΜΕΓΙΣΤΗΣ-Municipality of Megisti',N'ΔΗΜΟΣ ΜΕΓΙΣΤΗΣ-MUNICIPALITY OF MEGISTI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL421','6903','no',N'ΔΗΜΟΣ ΣΥΜΗΣ-Municipality of Symi',N'ΔΗΜΟΣ ΣΥΜΗΣ-MUNICIPALITY OF SYMI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL421','6904','no',N'ΔΗΜΟΣ ΤΗΛΟΥ-Municipality of Tilos',N'ΔΗΜΟΣ ΤΗΛΟΥ-MUNICIPALITY OF TILOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL421','6905','no',N'ΔΗΜΟΣ ΧΑΛΚΗΣ-Municipality of Chalki',N'ΔΗΜΟΣ ΧΑΛΚΗΣ-MUNICIPALITY OF CHALKI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL422','7001','no',N'ΔΗΜΟΣ ΤΗΝΟΥ-Municipality of Tinos',N'ΔΗΜΟΣ ΤΗΝΟΥ-MUNICIPALITY OF TINOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL431','7101','no',N'ΔΗΜΟΣ ΗΡΑΚΛΕΙΟΥ ΚΡΗΤΗΣ-Municipality of Iraklio',N'ΔΗΜΟΣ ΗΡΑΚΛΕΙΟΥ ΚΡΗΤΗΣ-MUNICIPALITY OF IRAKLIO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL431','7102','no',N'ΔΗΜΟΣ ΑΡΧΑΝΩΝ - ΑΣΤΕΡΟΥΣΙΩΝ-Municipality of Archanes - Asteroussii',N'ΔΗΜΟΣ ΑΡΧΑΝΩΝ - ΑΣΤΕΡΟΥΣΙΩΝ-MUNICIPALITY OF ARCHANES - ASTEROUSSII');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL431','7103','no',N'ΔΗΜΟΣ ΒΙΑΝΝΟΥ-Municipality of Viannos',N'ΔΗΜΟΣ ΒΙΑΝΝΟΥ-MUNICIPALITY OF VIANNOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL431','7104','no',N'ΔΗΜΟΣ ΓΟΡΤΥΝΑΣ-Municipality of Gortyna',N'ΔΗΜΟΣ ΓΟΡΤΥΝΑΣ-MUNICIPALITY OF GORTYNA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL431','7105','no',N'ΔΗΜΟΣ ΜΑΛΕΒΙΖΙΟΥ-Municipality of Malevizi',N'ΔΗΜΟΣ ΜΑΛΕΒΙΖΙΟΥ-MUNICIPALITY OF MALEVIZI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL431','7106','no',N'ΔΗΜΟΣ ΜΙΝΩΑ ΠΕΔΙΑΔΑΣ-Municipality of Minoa Pediadas',N'ΔΗΜΟΣ ΜΙΝΩΑ ΠΕΔΙΑΔΑΣ-MUNICIPALITY OF MINOA PEDIADAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL431','7107','no',N'ΔΗΜΟΣ ΦΑΙΣΤΟΥ-Municipality of Faistos',N'ΔΗΜΟΣ ΦΑΙΣΤΟΥ-MUNICIPALITY OF FAISTOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL431','7108','no',N'ΔΗΜΟΣ ΧΕΡΣΟΝΗΣΟΥ-Municipality of Chersonissos',N'ΔΗΜΟΣ ΧΕΡΣΟΝΗΣΟΥ-MUNICIPALITY OF CHERSONISSOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL432','7201','no',N'ΔΗΜΟΣ ΑΓΙΟΥ ΝΙΚΟΛΑΟΥ-Municipality of Aghios Nikolaos',N'ΔΗΜΟΣ ΑΓΙΟΥ ΝΙΚΟΛΑΟΥ-MUNICIPALITY OF AGHIOS NIKOLAOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL432','7202','no',N'ΔΗΜΟΣ ΙΕΡΑΠΕΤΡΑΣ-Municipality of Ierapetra',N'ΔΗΜΟΣ ΙΕΡΑΠΕΤΡΑΣ-MUNICIPALITY OF IERAPETRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL432','7203','no',N'ΔΗΜΟΣ ΟΡΟΠΕΔΙΟΥ ΛΑΣΙΘΙΟΥ-Municipality of Oropedio Lassithiou',N'ΔΗΜΟΣ ΟΡΟΠΕΔΙΟΥ ΛΑΣΙΘΙΟΥ-MUNICIPALITY OF OROPEDIO LASSITHIOU');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL432','7204','no',N'ΔΗΜΟΣ ΣΗΤΕΙΑΣ-Municipality of Sitia',N'ΔΗΜΟΣ ΣΗΤΕΙΑΣ-MUNICIPALITY OF SITIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL433','7301','no',N'ΔΗΜΟΣ ΡΕΘΥΜΝΗΣ-Municipality of Rethymno',N'ΔΗΜΟΣ ΡΕΘΥΜΝΗΣ-MUNICIPALITY OF RETHYMNO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL433','7302','no',N'ΔΗΜΟΣ ΑΓΙΟΥ ΒΑΣΙΛΕΙΟΥ-Municipality of Aghios Vassilios',N'ΔΗΜΟΣ ΑΓΙΟΥ ΒΑΣΙΛΕΙΟΥ-MUNICIPALITY OF AGHIOS VASSILIOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL433','7303','no',N'ΔΗΜΟΣ ΑΜΑΡΙΟΥ-Municipality of Amari',N'ΔΗΜΟΣ ΑΜΑΡΙΟΥ-MUNICIPALITY OF AMARI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL433','7304','no',N'ΔΗΜΟΣ ΑΝΩΓΕΙΩΝ-Municipality of Anogia',N'ΔΗΜΟΣ ΑΝΩΓΕΙΩΝ-MUNICIPALITY OF ANOGIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL433','7305','no',N'ΔΗΜΟΣ ΜΥΛΟΠΟΤΑΜΟΥ-Municipality of Mylopotamos',N'ΔΗΜΟΣ ΜΥΛΟΠΟΤΑΜΟΥ-MUNICIPALITY OF MYLOPOTAMOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL434','7401','no',N'ΔΗΜΟΣ ΧΑΝΙΩΝ-Municipality of Chania',N'ΔΗΜΟΣ ΧΑΝΙΩΝ-MUNICIPALITY OF CHANIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL434','7402','no',N'ΔΗΜΟΣ ΑΠΟΚΟΡΩΝΟΥ-Municipality of Apokoronas',N'ΔΗΜΟΣ ΑΠΟΚΟΡΩΝΟΥ-MUNICIPALITY OF APOKORONAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL434','7403','no',N'ΔΗΜΟΣ ΓΑΥΔΟΥ-Municipality of Gavdos',N'ΔΗΜΟΣ ΓΑΥΔΟΥ-MUNICIPALITY OF GAVDOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL434','7404','no',N'ΔΗΜΟΣ ΚΑΝΤΑΝΟΥ - ΣΕΛΙΝΟΥ-Municipality of Kandanos - Selinos',N'ΔΗΜΟΣ ΚΑΝΤΑΝΟΥ - ΣΕΛΙΝΟΥ-MUNICIPALITY OF KANDANOS - SELINOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL434','7405','no',N'ΔΗΜΟΣ ΚΙΣΣΑΜΟΥ-Municipality of Kissamos',N'ΔΗΜΟΣ ΚΙΣΣΑΜΟΥ-MUNICIPALITY OF KISSAMOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL434','7406','no',N'ΔΗΜΟΣ ΠΛΑΤΑΝΙΑ-Municipality of Platanias',N'ΔΗΜΟΣ ΠΛΑΤΑΝΙΑ-MUNICIPALITY OF PLATANIAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','EL434','7407','no',N'ΔΗΜΟΣ ΣΦΑΚΙΩΝ-Municipality of Sfakia',N'ΔΗΜΟΣ ΣΦΑΚΙΩΝ-MUNICIPALITY OF SFAKIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('EL','ELZZZ','9901','no',N'ΑΓΙΟ ΟΡΟΣ (ΑΥΤΟΔΙΟΙΚΗΤΟ)-Aghio Oros',N'ΑΓΙΟ ΟΡΟΣ (ΑΥΤΟΔΙΟΙΚΗΤΟ)-AGHIO OROS');
