INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','19','no',N'Andrijaševci',N'ANDRIJAŠEVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','27','no',N'Antunovac',N'ANTUNOVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','35','no',N'Babina greda',N'BABINA GREDA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','43','no',N'Bakar',N'BAKAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','51','no',N'Bale - valle',N'BALE - VALLE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','60','no',N'Barban',N'BARBAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04D','78','no',N'Barilović',N'BARILOVIĆ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','86','no',N'Baška',N'BAŠKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','94','no',N'Baška voda',N'BAŠKA VODA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','108','no',N'Bebrina',N'BEBRINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','116','no',N'Bedekovčina',N'BEDEKOVČINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','5509','no',N'Bedenica',N'BEDENICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','124','no',N'Bednja',N'BEDNJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','132','no',N'Beli manastir',N'BELI MANASTIR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','159','no',N'Belica',N'BELICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','167','no',N'Belišće',N'BELIŠĆE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','175','no',N'Benkovac',N'BENKOVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','183','no',N'Berek',N'BEREK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','191','no',N'Beretinec',N'BERETINEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','205','no',N'Bibinje',N'BIBINJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR034','6211','no',N'Bilice',N'BILICE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','213','no',N'Bilje',N'BILJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','221','no',N'Biograd na moru',N'BIOGRAD NA MORU');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR034','3107','no',N'Biskupija',N'BISKUPIJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','5479','no',N'Bistra',N'BISTRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','230','no',N'Bizovac',N'BIZOVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','248','no',N'Bjelovar',N'BJELOVAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR037','256','no',N'Blato',N'BLATO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','264','no',N'Bogdanovci',N'BOGDANOVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','272','no',N'Bol',N'BOL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','299','no',N'Borovo',N'BOROVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04D','302','no',N'Bosiljevo',N'BOSILJEVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','329','no',N'Bošnjaci',N'BOŠNJACI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','337','no',N'Brckovljani',N'BRCKOVLJANI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','345','no',N'Brdovec',N'BRDOVEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','779','no',N'Brela',N'BRELA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR049','353','no',N'Brestovac',N'BRESTOVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','361','no',N'Breznica',N'BREZNICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','1511','no',N'Breznički hum',N'BREZNIČKI HUM');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR032','370','no',N'Brinje',N'BRINJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','388','no',N'Brod moravice',N'BROD MORAVICE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','396','no',N'Brodski stupnik',N'BRODSKI STUPNIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','400','no',N'Brtonigla - verteneglio',N'BRTONIGLA - VERTENEGLIO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','418','no',N'Budinščina',N'BUDINŠČINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','6912','no',N'Buje - buie',N'BUJE - BUIE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','5673','no',N'Bukovlje',N'BUKOVLJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','434','no',N'Buzet',N'BUZET');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','558','no',N'Čabar',N'ČABAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR048','566','no',N'Čačinci',N'ČAČINCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR048','574','no',N'Čađavica',N'ČAĐAVICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR049','582','no',N'Čaglin',N'ČAGLIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','604','no',N'Čakovec',N'ČAKOVEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','612','no',N'Čavle',N'ČAVLE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','639','no',N'Čazma',N'ČAZMA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','647','no',N'Čeminac',N'ČEMINAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','655','no',N'Čepin',N'ČEPIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','442','no',N'Cerna',N'CERNA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','469','no',N'Cernik',N'CERNIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','477','no',N'Cerovlje',N'CEROVLJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','485','no',N'Cestica',N'CESTICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04D','493','no',N'Cetingrad',N'CETINGRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','507','no',N'Cista provo',N'CISTA PROVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR034','515','no',N'Civljane',N'CIVLJANE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','523','no',N'Cres',N'CRES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','531','no',N'Crikvenica',N'CRIKVENICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR048','540','no',N'Crnac',N'CRNAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','1031','no',N'Đakovo',N'ĐAKOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','663','no',N'Darda',N'DARDA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','671','no',N'Daruvar',N'DARUVAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','680','no',N'Davor',N'DAVOR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','6033','no',N'Dekanovec',N'DEKANOVEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','1040','no',N'Đelekovec',N'ĐELEKOVEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','698','no',N'Delnice',N'DELNICE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','701','no',N'Desinić',N'DESINIĆ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','710','no',N'Dežanovac',N'DEŽANOVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','728','no',N'Dicmo',N'DICMO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','744','no',N'Dobrinj',N'DOBRINJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','752','no',N'Domašinec',N'DOMAŠINEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','787','no',N'Donja dubrava',N'DONJA DUBRAVA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','5762','no',N'Donja motičina',N'DONJA MOTIČINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','795','no',N'Donja stubica',N'DONJA STUBICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','809','no',N'Donja voća',N'DONJA VOĆA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','817','no',N'Donji andrijevci',N'DONJI ANDRIJEVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','825','no',N'Donji kraljevec',N'DONJI KRALJEVEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04E','833','no',N'Donji kukuruzari',N'DONJI KUKURUZARI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR032','841','no',N'Donji lapac',N'DONJI LAPAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','868','no',N'Donji miholjac',N'DONJI MIHOLJAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','892','no',N'Donji vidovec',N'DONJI VIDOVEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','5681','no',N'Dragalić',N'DRAGALIĆ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04D','906','no',N'Draganić',N'DRAGANIĆ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','914','no',N'Draž',N'DRAŽ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','949','no',N'Drenje',N'DRENJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','922','no',N'Drenovci',N'DRENOVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR034','957','no',N'Drniš',N'DRNIŠ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','965','no',N'Drnje',N'DRNJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','973','no',N'Dubrava',N'DUBRAVA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','5495','no',N'Dubravica',N'DUBRAVICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR037','5983','no',N'Dubrovačko primorje',N'DUBROVAČKO PRIMORJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR037','981','no',N'Dubrovnik',N'DUBROVNIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04D','990','no',N'Duga resa',N'DUGA RESA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','1007','no',N'Dugi rat',N'DUGI RAT');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','1015','no',N'Dugo selo',N'DUGO SELO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','5851','no',N'Dugopolje',N'DUGOPOLJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','1058','no',N'Đulovac',N'ĐULOVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','1066','no',N'Đurđenovac',N'ĐURĐENOVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','1074','no',N'Đurđevac',N'ĐURĐEVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','1082','no',N'Đurmanec',N'ĐURMANEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04E','1023','no',N'Dvor',N'DVOR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','1104','no',N'Erdut',N'ERDUT');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','1112','no',N'Ernestinovo',N'ERNESTINOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR034','1139','no',N'Ervenik',N'ERVENIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','1147','no',N'Farkaševac',N'FARKAŠEVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','6190','no',N'Fažana - fasana',N'FAŽANA - FASANA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','1155','no',N'Ferdinandovac',N'FERDINANDOVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','1163','no',N'Feričanci',N'FERIČANCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','6297','no',N'Funtana - fontane',N'FUNTANA - FONTANE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','1171','no',N'Fužine',N'FUŽINE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','5711','no',N'Galovac',N'GALOVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','1180','no',N'Garčin',N'GARČIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','1198','no',N'Garešnica',N'GAREŠNICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04D','1201','no',N'Generalski stol',N'GENERALSKI STOL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04E','1210','no',N'Glina',N'GLINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','1228','no',N'Gola',N'GOLA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','1236','no',N'Goričan',N'GORIČAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','1244','no',N'Gorjani',N'GORJANI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','6181','no',N'Gornja rijeka',N'GORNJA RIJEKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','1252','no',N'Gornja stubica',N'GORNJA STUBICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','5690','no',N'Gornja vrba',N'GORNJA VRBA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','1279','no',N'Gornji bogićevci',N'GORNJI BOGIĆEVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','1295','no',N'Gornji kneginec',N'GORNJI KNEGINEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','6041','no',N'Gornji mihaljevec',N'GORNJI MIHALJEVEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR032','1309','no',N'Gospić',N'GOSPIĆ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','1317','no',N'Gračac',N'GRAČAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','1325','no',N'Gračišće',N'GRAČIŠĆE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR041','1333','no',N'Grad zagreb',N'GRAD ZAGREB');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','1341','no',N'Gradac',N'GRADAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','1350','no',N'Gradec',N'GRADEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR048','1368','no',N'Gradina',N'GRADINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','1376','no',N'Gradište',N'GRADIŠTE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','1384','no',N'Grožnjan - grisignana',N'GROŽNJAN - GRISIGNANA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','1392','no',N'Grubišno polje',N'GRUBIŠNO POLJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','1406','no',N'Gundinci',N'GUNDINCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','1414','no',N'Gunja',N'GUNJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04E','5100','no',N'Gvozd',N'GVOZD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','1449','no',N'Hercegovac',N'HERCEGOVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','1457','no',N'Hlebine',N'HLEBINE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','1465','no',N'Hrašćina',N'HRAŠĆINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','1481','no',N'Hrvace',N'HRVACE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04E','1490','no',N'Hrvatska dubica',N'HRVATSKA DUBICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04E','1503','no',N'Hrvatska kostajnica',N'HRVATSKA KOSTAJNICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','1520','no',N'Hum na sutli',N'HUM NA SUTLI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','1538','no',N'Hvar',N'HVAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','1546','no',N'Ilok',N'ILOK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','1554','no',N'Imotski',N'IMOTSKI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','1562','no',N'Ivanec',N'IVANEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','1589','no',N'Ivanić-grad',N'IVANIĆ-GRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','1597','no',N'Ivankovo',N'IVANKOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','1619','no',N'Ivanska',N'IVANSKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','6092','no',N'Jagodnjak',N'JAGODNJAK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','1635','no',N'Jakovlje',N'JAKOVLJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR049','1643','no',N'Jakšić',N'JAKŠIĆ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','1651','no',N'Jalžabet',N'JALŽABET');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR037','5991','no',N'Janjina',N'JANJINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','1660','no',N'Jarmina',N'JARMINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','1678','no',N'Jasenice',N'JASENICE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04E','1686','no',N'Jasenovac',N'JASENOVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','1694','no',N'Jastrebarsko',N'JASTREBARSKO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','1708','no',N'Jelenje',N'JELENJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','1716','no',N'Jelsa',N'JELSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','5525','no',N'Jesenje',N'JESENJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04D','1724','no',N'Josipdol',N'JOSIPDOL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','1732','no',N'Kali',N'KALI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','5592','no',N'Kalinovac',N'KALINOVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','5606','no',N'Kalnik',N'KALNIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04D','6238','no',N'Kamanje',N'KAMANJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','1759','no',N'Kanfanar',N'KANFANAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','1767','no',N'Kapela',N'KAPELA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR049','1775','no',N'Kaptol',N'KAPTOL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR032','1783','no',N'Karlobag',N'KARLOBAG');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04D','1791','no',N'Karlovac',N'KARLOVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','5967','no',N'Karojba',N'KAROJBA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','1805','no',N'Kastav',N'KASTAV');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','1813','no',N'Kaštela',N'KAŠTELA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','5975','no',N'Kaštelir-labinci - castelliere-s. Domenica',N'KAŠTELIR-LABINCI - CASTELLIERE-S. DOMENICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR034','1830','no',N'Kijevo',N'KIJEVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR034','1848','no',N'Kistanje',N'KISTANJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','1856','no',N'Klakar',N'KLAKAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','1864','no',N'Klana',N'KLANA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','1872','no',N'Klanjec',N'KLANJEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','1899','no',N'Klenovnik',N'KLENOVNIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','1902','no',N'Klinča sela',N'KLINČA SELA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','1929','no',N'Klis',N'KLIS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','1937','no',N'Kloštar ivanić',N'KLOŠTAR IVANIĆ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','1945','no',N'Kloštar podravski',N'KLOŠTAR PODRAVSKI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','1953','no',N'Kneževi vinogradi',N'KNEŽEVI VINOGRADI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR034','1961','no',N'Knin',N'KNIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','6220','no',N'Kolan',N'KOLAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','1970','no',N'Komiža',N'KOMIŽA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR037','1988','no',N'Konavle',N'KONAVLE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','1996','no',N'Končanica',N'KONČANICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','2003','no',N'Konjščina',N'KONJŠČINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','2011','no',N'Koprivnica',N'KOPRIVNICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','2020','no',N'Koprivnički bregi',N'KOPRIVNIČKI BREGI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','2038','no',N'Koprivnički ivanec',N'KOPRIVNIČKI IVANEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR037','2046','no',N'Korčula',N'KORČULA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','2054','no',N'Koška',N'KOŠKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','5380','no',N'Kostrena',N'KOSTRENA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','2062','no',N'Kotoriba',N'KOTORIBA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','2089','no',N'Kraljevec na sutli',N'KRALJEVEC NA SUTLI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','2097','no',N'Kraljevica',N'KRALJEVICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','2119','no',N'Krapina',N'KRAPINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','2127','no',N'Krapinske toplice',N'KRAPINSKE TOPLICE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','5339','no',N'Krašić',N'KRAŠIĆ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','5452','no',N'Kravarsko',N'KRAVARSKO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','2135','no',N'Križ',N'KRIŽ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','2143','no',N'Križevci',N'KRIŽEVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','2151','no',N'Krk',N'KRK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04D','2160','no',N'Krnjak',N'KRNJAK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','2178','no',N'Kršan',N'KRŠAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','5720','no',N'Kukljica',N'KUKLJICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR037','2194','no',N'Kula norinska',N'KULA NORINSKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','5533','no',N'Kumrovec',N'KUMROVEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04E','2208','no',N'Kutina',N'KUTINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR049','2216','no',N'Kutjevo',N'KUTJEVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','2224','no',N'Labin',N'LABIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','2232','no',N'Lanišće',N'LANIŠĆE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04D','2259','no',N'Lasinja',N'LASINJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR037','2267','no',N'Lastovo',N'LASTOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','5860','no',N'Lećevica',N'LEĆEVICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','2275','no',N'Legrad',N'LEGRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04E','2283','no',N'Lekenik',N'LEKENIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','2291','no',N'Lepoglava',N'LEPOGLAVA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','2305','no',N'Levanjska varoš',N'LEVANJSKA VAROŠ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR049','2313','no',N'Lipik',N'LIPIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04E','2321','no',N'Lipovljani',N'LIPOVLJANI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','2348','no',N'Lišane ostrovičke',N'LIŠANE OSTROVIČKE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','2356','no',N'Ližnjan - lisignano',N'LIŽNJAN - LISIGNANO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','2470','no',N'Ljubešćica',N'LJUBEŠĆICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','2364','no',N'Lobor',N'LOBOR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','2372','no',N'Lokve',N'LOKVE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','5878','no',N'Lokvičići',N'LOKVIČIĆI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','6246','no',N'Lopar',N'LOPAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','2399','no',N'Lovas',N'LOVAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR032','2402','no',N'Lovinac',N'LOVINAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','2429','no',N'Lovran',N'LOVRAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','2437','no',N'Lovreć',N'LOVREĆ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','2445','no',N'Ludbreg',N'LUDBREG');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','5487','no',N'Luka',N'LUKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR048','2453','no',N'Lukač',N'LUKAČ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR037','6009','no',N'Lumbarda',N'LUMBARDA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','2461','no',N'Lupoglav',N'LUPOGLAV');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','2488','no',N'Mače',N'MAČE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','5789','no',N'Magadenovac',N'MAGADENOVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04E','5550','no',N'Majur',N'MAJUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','2496','no',N'Makarska',N'MAKARSKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','2500','no',N'Mala subotica',N'MALA SUBOTICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','2518','no',N'Mali bukovec',N'MALI BUKOVEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','2526','no',N'Mali lošinj',N'MALI LOŠINJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','2534','no',N'Malinska-dubašnica',N'MALINSKA-DUBAŠNICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','2542','no',N'Marčana',N'MARČANA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','2569','no',N'Marija bistrica',N'MARIJA BISTRICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','5398','no',N'Marija gorica',N'MARIJA GORICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','2577','no',N'Marijanci',N'MARIJANCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','2585','no',N'Marina',N'MARINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','6106','no',N'Markušica',N'MARKUŠICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','850','no',N'Martijanec',N'MARTIJANEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04E','2593','no',N'Martinska ves',N'MARTINSKA VES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','2607','no',N'Maruševec',N'MARUŠEVEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','2615','no',N'Matulji',N'MATULJI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','2631','no',N'Medulin',N'MEDULIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR037','2640','no',N'Metković',N'METKOVIĆ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','2658','no',N'Mihovljan',N'MIHOVLJAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR048','2666','no',N'Mikleuš',N'MIKLEUŠ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','2674','no',N'Milna',N'MILNA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR037','2682','no',N'Mljet',N'MLJET');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','2704','no',N'Molve',N'MOLVE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','2739','no',N'Mošćenička draga',N'MOŠĆENIČKA DRAGA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','2747','no',N'Motovun - montona',N'MOTOVUN - MONTONA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','2755','no',N'Mrkopalj',N'MRKOPALJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','876','no',N'Muć',N'MUĆ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','2763','no',N'Mursko središće',N'MURSKO SREDIŠĆE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR034','6173','no',N'Murter - kornati',N'MURTER - KORNATI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','2780','no',N'Našice',N'NAŠICE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','2798','no',N'Nedelišće',N'NEDELIŠĆE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','6122','no',N'Negoslavci',N'NEGOSLAVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','2801','no',N'Nerežišća',N'NEREŽIŠĆA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04D','2810','no',N'Netretić',N'NETRETIĆ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','2950','no',N'Nijemci',N'NIJEMCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','2828','no',N'Nin',N'NIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR048','2836','no',N'Nova bukovica',N'NOVA BUKOVICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','2844','no',N'Nova gradiška',N'NOVA GRADIŠKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','2852','no',N'Nova kapela',N'NOVA KAPELA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','2879','no',N'Nova rača',N'NOVA RAČA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR032','2887','no',N'Novalja',N'NOVALJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','5541','no',N'Novi golubovec',N'NOVI GOLUBOVEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','2895','no',N'Novi marof',N'NOVI MAROF');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','2909','no',N'Novi vinodolski',N'NOVI VINODOLSKI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','5371','no',N'Novigrad',N'NOVIGRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','2925','no',N'Novigrad - cittanova',N'NOVIGRAD - CITTANOVA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','2917','no',N'Novigrad podravski',N'NOVIGRAD PODRAVSKI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','5614','no',N'Novo virje',N'NOVO VIRJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04E','2933','no',N'Novska',N'NOVSKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','2941','no',N'Nuštar',N'NUŠTAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','2986','no',N'Obrovac',N'OBROVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04D','2976','no',N'Ogulin',N'OGULIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','5886','no',N'Okrug',N'OKRUG');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','2992','no',N'Okučani',N'OKUČANI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','3000','no',N'Omiš',N'OMIŠ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','3018','no',N'Omišalj',N'OMIŠALJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','3026','no',N'Opatija',N'OPATIJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','3034','no',N'Oprisavci',N'OPRISAVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','3042','no',N'Oprtalj - portole',N'OPRTALJ - PORTOLE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR037','3069','no',N'Opuzen',N'OPUZEN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR048','3077','no',N'Orahovica',N'ORAHOVICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR037','3085','no',N'Orebić',N'OREBIĆ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','6050','no',N'Orehovica',N'OREHOVICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','3093','no',N'Oriovac',N'ORIOVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','5428','no',N'Orle',N'ORLE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','3115','no',N'Oroslavje',N'OROSLAVJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','3123','no',N'Osijek',N'OSIJEK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR032','3131','no',N'Otočac',N'OTOČAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','3140','no',N'Otok (Splitsko-dalmatinska županija)',N'OTOK (SPLITSKO-DALMATINSKA ŽUPANIJA)');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','5355','no',N'Otok (Vukovarsko-srijemska županija)',N'OTOK (VUKOVARSKO-SRIJEMSKA ŽUPANIJA)');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04D','3158','no',N'Ozalj',N'OZALJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','3166','no',N'Pag',N'PAG');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','3174','no',N'Pakoštane',N'PAKOŠTANE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR049','3182','no',N'Pakrac',N'PAKRAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','3204','no',N'Pašman',N'PAŠMAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','3212','no',N'Pazin',N'PAZIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR032','3239','no',N'Perušić',N'PERUŠIĆ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','3247','no',N'Peteranec',N'PETERANEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','3255','no',N'Petlovac',N'PETLOVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','3263','no',N'Petrijanec',N'PETRIJANEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','3271','no',N'Petrijevci',N'PETRIJEVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04E','3280','no',N'Petrinja',N'PETRINJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','3298','no',N'Petrovsko',N'PETROVSKO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','3301','no',N'Pićan',N'PIĆAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR034','5819','no',N'Pirovac',N'PIROVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','3310','no',N'Pisarovina',N'PISAROVINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR048','3328','no',N'Pitomača',N'PITOMAČA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04D','3336','no',N'Plaški',N'PLAŠKI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR049','3344','no',N'Pleternica',N'PLETERNICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR032','4553','no',N'Plitvička jezera',N'PLITVIČKA JEZERA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR037','3352','no',N'Ploče',N'PLOČE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','3379','no',N'Podbablje',N'PODBABLJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','3387','no',N'Podcrkavlje',N'PODCRKAVLJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','3395','no',N'Podgora',N'PODGORA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','3409','no',N'Podgorač',N'PODGORAČ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','2712','no',N'Podravska moslavina',N'PODRAVSKA MOSLAVINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','6165','no',N'Podravske sesvete',N'PODRAVSKE SESVETE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','3417','no',N'Podstrana',N'PODSTRANA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','3425','no',N'Podturen',N'PODTUREN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR037','3433','no',N'Pojezerje',N'POJEZERJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','5444','no',N'Pokupsko',N'POKUPSKO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','3441','no',N'Polača',N'POLAČA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','3450','no',N'Poličnik',N'POLIČNIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','3468','no',N'Popovac',N'POPOVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04E','3476','no',N'Popovača',N'POPOVAČA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','3484','no',N'Poreč - parenzo',N'POREČ - PARENZO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','3492','no',N'Posedarje',N'POSEDARJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','3506','no',N'Postira',N'POSTIRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','5738','no',N'Povljana',N'POVLJANA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR049','3514','no',N'Požega',N'POŽEGA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','3522','no',N'Pregrada',N'PREGRADA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','3549','no',N'Preko',N'PREKO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','3557','no',N'Prelog',N'PRELOG');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','3565','no',N'Preseka',N'PRESEKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','5894','no',N'Prgomet',N'PRGOMET');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','6203','no',N'Pribislavec',N'PRIBISLAVEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','5908','no',N'Primorski dolac',N'PRIMORSKI DOLAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR034','3573','no',N'Primošten',N'PRIMOŠTEN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','5746','no',N'Privlaka (Zadarska županija)',N'PRIVLAKA (ZADARSKA ŽUPANIJA)');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','5835','no',N'Privlaka (Vukovarsko-srijemska županija)',N'PRIVLAKA (VUKOVARSKO-SRIJEMSKA ŽUPANIJA)');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','884','no',N'Proložac',N'PROLOŽAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR034','2984','no',N'Promina',N'PROMINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','3581','no',N'Pučišća',N'PUČIŠĆA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','3590','no',N'Pula - pola',N'PULA - POLA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','3603','no',N'Punat',N'PUNAT');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','3611','no',N'Punitovci',N'PUNITOVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','3620','no',N'Pušća',N'PUŠĆA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','3638','no',N'Rab',N'RAB');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','3646','no',N'Radoboj',N'RADOBOJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','5363','no',N'Rakovec',N'RAKOVEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04D','3654','no',N'Rakovica',N'RAKOVICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','3689','no',N'Raša',N'RAŠA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','3662','no',N'Rasinja',N'RASINJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','3697','no',N'Ravna gora',N'RAVNA GORA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','3719','no',N'Ražanac',N'RAŽANAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','3727','no',N'Rešetari',N'REŠETARI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04D','5568','no',N'Ribnik',N'RIBNIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','3735','no',N'Rijeka',N'RIJEKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR034','5827','no',N'Rogoznica',N'ROGOZNICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','3743','no',N'Rovinj - rovigno',N'ROVINJ - ROVIGNO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','3751','no',N'Rovišće',N'ROVIŠĆE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','3760','no',N'Rugvica',N'RUGVICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','5916','no',N'Runovići',N'RUNOVIĆI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR034','3778','no',N'Ružić',N'RUŽIĆ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04D','3786','no',N'Saborsko',N'SABORSKO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','3794','no',N'Sali',N'SALI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','3808','no',N'Samobor',N'SAMOBOR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','5649','no',N'Šandrovac',N'ŠANDROVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','3816','no',N'Satnica đakovačka',N'SATNICA ĐAKOVAČKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','3824','no',N'Seget',N'SEGET');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','3832','no',N'Selca',N'SELCA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','3859','no',N'Selnica',N'SELNICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','3867','no',N'Semeljci',N'SEMELJCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR032','3875','no',N'Senj',N'SENJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','6084','no',N'Šenkovec',N'ŠENKOVEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','4430','no',N'Šestanovac',N'ŠESTANOVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','5622','no',N'Severin',N'SEVERIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR034','4448','no',N'Šibenik',N'ŠIBENIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','3883','no',N'Sibinj',N'SIBINJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','5703','no',N'Sikirevci',N'SIKIREVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','3981','no',N'Sinj',N'SINJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','3905','no',N'Sirač',N'SIRAČ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04E','3913','no',N'Sisak',N'SISAK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','4456','no',N'Škabrnja',N'ŠKABRNJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','3930','no',N'Skrad',N'SKRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR034','3984','no',N'Skradin',N'SKRADIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR048','3956','no',N'Slatina',N'SLATINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','3964','no',N'Slavonski brod',N'SLAVONSKI BROD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','3972','no',N'Slavonski šamac',N'SLAVONSKI ŠAMAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR037','3999','no',N'Slivno',N'SLIVNO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04D','4006','no',N'Slunj',N'SLUNJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR037','4022','no',N'Smokvica',N'SMOKVICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','6149','no',N'Šodolovci',N'ŠODOLOVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','4057','no',N'Sokolovac',N'SOKOLOVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','4065','no',N'Solin',N'SOLIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','4472','no',N'Šolta',N'ŠOLTA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR048','4073','no',N'Sopje',N'SOPJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR048','4499','no',N'Špišić bukovica',N'ŠPIŠIĆ BUKOVICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','4090','no',N'Split',N'SPLIT');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','4103','no',N'Sračinec',N'SRAČINEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','4111','no',N'Stankovci',N'STANKOVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','4120','no',N'Stara gradiška',N'STARA GRADIŠKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','4138','no',N'Stari grad',N'STARI GRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','4146','no',N'Stari jankovci',N'STARI JANKOVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','4154','no',N'Stari mikanovci',N'STARI MIKANOVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','4162','no',N'Starigrad',N'STARIGRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','4189','no',N'Staro petrovo selo',N'STARO PETROVO SELO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','4502','no',N'Štefanje',N'ŠTEFANJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','6289','no',N'Štitar',N'ŠTITAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR037','4197','no',N'Ston',N'STON');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','6068','no',N'Strahoninec',N'STRAHONINEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','4529','no',N'Štrigova',N'ŠTRIGOVA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','4219','no',N'Strizivojna',N'STRIZIVOJNA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','4227','no',N'Stubičke toplice',N'STUBIČKE TOPLICE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','5517','no',N'Stupnik',N'STUPNIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','4235','no',N'Sućuraj',N'SUĆURAJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR048','4243','no',N'Suhopolje',N'SUHOPOLJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','4251','no',N'Sukošan',N'SUKOŠAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04E','4260','no',N'Sunja',N'SUNJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','4278','no',N'Supetar',N'SUPETAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','5924','no',N'Sutivan',N'SUTIVAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','6076','no',N'Sveta marija',N'SVETA MARIJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','4324','no',N'Sveta Nedelja (Istarska županija)',N'SVETA NEDELJA (ISTARSKA ŽUPANIJA)');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','4367','no',N'Sveta Nedelja (Zagrebačka županija)',N'SVETA NEDELJA (ZAGREBAČKA ŽUPANIJA)');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','4375','no',N'Sveti đurđ',N'SVETI ĐURĐ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','4286','no',N'Sveti filip i jakov',N'SVETI FILIP I JAKOV');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','4383','no',N'Sveti ilija',N'SVETI ILIJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','4391','no',N'Sveti ivan žabno',N'SVETI IVAN ŽABNO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','4294','no',N'Sveti ivan zelina',N'SVETI IVAN ZELINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','4405','no',N'Sveti juraj na bregu',N'SVETI JURAJ NA BREGU');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','4308','no',N'Sveti križ začretje',N'SVETI KRIŽ ZAČRETJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','4316','no',N'Sveti lovreč',N'SVETI LOVREČ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','4413','no',N'Sveti martin na muri',N'SVETI MARTIN NA MURI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','4421','no',N'Sveti petar orehovec',N'SVETI PETAR OREHOVEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','4332','no',N'Sveti petar u šumi',N'SVETI PETAR U ŠUMI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','4359','no',N'Svetvinčenat',N'SVETVINČENAT');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','6319','no',N'Tar-vabriga - torre-abrega',N'TAR-VABRIGA - TORRE-ABREGA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','4537','no',N'Tinjan',N'TINJAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR034','4545','no',N'Tisno',N'TISNO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','5754','no',N'Tkon',N'TKON');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','4561','no',N'Tompojevci',N'TOMPOJEVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04E','4570','no',N'Topusko',N'TOPUSKO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','4588','no',N'Tordinci',N'TORDINCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04D','5576','no',N'Tounj',N'TOUNJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','4596','no',N'Tovarnik',N'TOVARNIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR034','6262','no',N'Tribunj',N'TRIBUNJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','4600','no',N'Trilj',N'TRILJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','4618','no',N'Trnava',N'TRNAVA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','4626','no',N'Trnovec bartolovečki',N'TRNOVEC BARTOLOVEČKI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','4634','no',N'Trogir',N'TROGIR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR037','6017','no',N'Trpanj',N'TRPANJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','4642','no',N'Trpinja',N'TRPINJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','5932','no',N'Tučepi',N'TUČEPI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','4669','no',N'Tuhelj',N'TUHELJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR032','4677','no',N'Udbina',N'UDBINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','4685','no',N'Umag - umago',N'UMAG - UMAGO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR034','4693','no',N'Unešić',N'UNEŠIĆ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','4715','no',N'Valpovo',N'VALPOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','4723','no',N'Varaždin',N'VARAŽDIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','4731','no',N'Varaždinske toplice',N'VARAŽDINSKE TOPLICE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR037','4740','no',N'Vela luka',N'VELA LUKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR049','4758','no',N'Velika',N'VELIKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','5410','no',N'Velika gorica',N'VELIKA GORICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','4766','no',N'Velika kopanica',N'VELIKA KOPANICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04E','4774','no',N'Velika ludina',N'VELIKA LUDINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','4782','no',N'Velika pisanica',N'VELIKA PISANICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','5657','no',N'Velika trnovitica',N'VELIKA TRNOVITICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','5584','no',N'Veliki bukovec',N'VELIKI BUKOVEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','4804','no',N'Veliki grđevac',N'VELIKI GRĐEVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','4812','no',N'Veliko trgovišće',N'VELIKO TRGOVIŠĆE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','4839','no',N'Veliko trojstvo',N'VELIKO TROJSTVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','4847','no',N'Vidovec',N'VIDOVEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','4855','no',N'Viljevo',N'VILJEVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','4863','no',N'Vinica',N'VINICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','4871','no',N'Vinkovci',N'VINKOVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','4880','no',N'Vinodolska općina',N'VINODOLSKA OPĆINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','4898','no',N'Vir',N'VIR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR045','4901','no',N'Virje',N'VIRJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR048','4910','no',N'Virovitica',N'VIROVITICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','4928','no',N'Vis',N'VIS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','4944','no',N'Viškovci',N'VIŠKOVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','4952','no',N'Viškovo',N'VIŠKOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','4979','no',N'Višnjan - visignano',N'VIŠNJAN - VISIGNANO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR044','4936','no',N'Visoko',N'VISOKO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','4987','no',N'Vižinada - visinada',N'VIŽINADA - VISINADA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','5797','no',N'Vladislavci',N'VLADISLAVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR048','4995','no',N'Voćin',N'VOĆIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR034','5002','no',N'Vodice',N'VODICE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','5843','no',N'Vođinci',N'VOĐINCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','5029','no',N'Vodnjan - dignano',N'VODNJAN - DIGNANO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04D','5037','no',N'Vojnić',N'VOJNIĆ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR046','5045','no',N'Vratišinec',N'VRATIŠINEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','5053','no',N'Vrbanja',N'VRBANJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','5061','no',N'Vrbje',N'VRBJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','5070','no',N'Vrbnik',N'VRBNIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','5088','no',N'Vrbovec',N'VRBOVEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR031','5096','no',N'Vrbovsko',N'VRBOVSKO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','5118','no',N'Vrgorac',N'VRGORAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR032','5126','no',N'Vrhovine',N'VRHOVINE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','5134','no',N'Vrlika',N'VRLIKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04A','5142','no',N'Vrpolje',N'VRPOLJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','5169','no',N'Vrsar - orsera',N'VRSAR - ORSERA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','6254','no',N'Vrsi',N'VRSI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04B','5177','no',N'Vuka',N'VUKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','5185','no',N'Vukovar',N'VUKOVAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','5193','no',N'Zabok',N'ZABOK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','5207','no',N'Zadar',N'ZADAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','5959','no',N'Zadvarje',N'ZADVARJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','5215','no',N'Zagorska sela',N'ZAGORSKA SELA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','5223','no',N'Zagvozd',N'ZAGVOZD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04D','5304','no',N'Žakanje',N'ŽAKANJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','5435','no',N'Zaprešić',N'ZAPREŠIĆ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR037','5231','no',N'Zažablje',N'ZAŽABLJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR048','5240','no',N'Zdenci',N'ZDENCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR033','5258','no',N'Zemunik donji',N'ZEMUNIK DONJI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','5266','no',N'Zlatar',N'ZLATAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR043','5274','no',N'Zlatar bistrica',N'ZLATAR BISTRICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR035','5282','no',N'Zmijavci',N'ZMIJAVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR036','5312','no',N'Žminj',N'ŽMINJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR047','5665','no',N'Zrinski topolovac',N'ZRINSKI TOPOLOVAC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR042','5401','no',N'Žumberak',N'ŽUMBERAK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR037','6025','no',N'Župa dubrovačka',N'ŽUPA DUBROVAČKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('HR','HR04C','5347','no',N'Županja',N'ŽUPANJA');
