INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','01','no',N'Carlow',N'CARLOW');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','01','no',N'Carlow B',N'CARLOW B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','01','no',N'Carlow C',N'CARLOW C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','01','no',N'Carlow D',N'CARLOW D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','01','no',N'Cavan',N'CAVAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','01','no',N'Cavan B',N'CAVAN B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','01','no',N'Cavan C',N'CAVAN C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','01','no',N'Cavan D',N'CAVAN D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE023','01','no',N'Clare',N'CLARE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE023','01','no',N'Clare B',N'CLARE B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE023','01','no',N'Clare C',N'CLARE C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE023','01','no',N'Clare D',N'CLARE D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE025','01','no',N'Cork City',N'CORK CITY');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE025','01','no',N'Cork City B',N'CORK CITY B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE025','01','no',N'Cork City C',N'CORK CITY C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE025','01','no',N'Cork City D',N'CORK CITY D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE025','02','no',N'Cork County',N'CORK COUNTY');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE025','02','no',N'Cork County B',N'CORK COUNTY B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE025','02','no',N'Cork County C',N'CORK COUNTY C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE025','02','no',N'Cork County D',N'CORK COUNTY D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','02','no',N'Donegal',N'DONEGAL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','02','no',N'Donegal B',N'DONEGAL B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','02','no',N'Donegal C',N'DONEGAL C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','02','no',N'Donegal D',N'DONEGAL D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE021','01','no',N'Dublin City',N'DUBLIN CITY');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE021','01','no',N'Dublin City B',N'DUBLIN CITY B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE021','01','no',N'Dublin City C',N'DUBLIN CITY C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE021','01','no',N'Dublin City D',N'DUBLIN CITY D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE021','02','no',N'Dún Laoighaire - Rathdown',N'DÚN LAOIGHAIRE - RATHDOWN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE021','02','no',N'Dún Laoighaire - Rathdown B',N'DÚN LAOIGHAIRE - RATHDOWN B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE021','02','no',N'Dún Laoighaire - Rathdown C',N'DÚN LAOIGHAIRE - RATHDOWN C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE021','02','no',N'Dún Laoighaire - Rathdown D',N'DÚN LAOIGHAIRE - RATHDOWN D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE021','03','no',N'Fingal',N'FINGAL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE021','03','no',N'Fingal B',N'FINGAL B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE021','03','no',N'Fingal C',N'FINGAL C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE021','03','no',N'Fingal D',N'FINGAL D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE013','01','no',N'Galway City',N'GALWAY CITY');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE013','01','no',N'Galway City B',N'GALWAY CITY B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE013','01','no',N'Galway City C',N'GALWAY CITY C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE013','01','no',N'Galway City D',N'GALWAY CITY D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE013','02','no',N'Galway County',N'GALWAY COUNTY');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE013','02','no',N'Galway County B',N'GALWAY COUNTY B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE013','02','no',N'Galway County C',N'GALWAY COUNTY C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE013','02','no',N'Galway County D',N'GALWAY COUNTY D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE025','03','no',N'Kerry',N'KERRY');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE025','03','no',N'Kerry B',N'KERRY B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE025','03','no',N'Kerry C',N'KERRY C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE025','03','no',N'Kerry D',N'KERRY D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE022','01','no',N'Kildare',N'KILDARE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE022','01','no',N'Kildare B',N'KILDARE B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE022','01','no',N'Kildare C',N'KILDARE C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE022','01','no',N'Kildare D',N'KILDARE D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','02','no',N'Kilkenny',N'KILKENNY');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','02','no',N'Kilkenny B',N'KILKENNY B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','02','no',N'Kilkenny C',N'KILKENNY C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','02','no',N'Kilkenny D',N'KILKENNY D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE012','01','no',N'Laois',N'LAOIS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE012','01','no',N'Laois B',N'LAOIS B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE012','01','no',N'Laois C',N'LAOIS C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE012','01','no',N'Laois D',N'LAOIS D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','03','no',N'Leitrim',N'LEITRIM');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','03','no',N'Leitrim B',N'LEITRIM B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','03','no',N'Leitrim C',N'LEITRIM C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','03','no',N'Leitrim D',N'LEITRIM D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE023','02','no',N'Limerick City',N'LIMERICK CITY');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE023','02','no',N'Limerick City B',N'LIMERICK CITY B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE023','02','no',N'Limerick City C',N'LIMERICK CITY C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE023','02','no',N'Limerick City D',N'LIMERICK CITY D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE023','03','no',N'Limerick County',N'LIMERICK COUNTY');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE023','03','no',N'Limerick County B',N'LIMERICK COUNTY B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE023','03','no',N'Limerick County C',N'LIMERICK COUNTY C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE023','03','no',N'Limerick County D',N'LIMERICK COUNTY D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE012','02','no',N'Longford',N'LONGFORD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE012','02','no',N'Longford B',N'LONGFORD B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE012','02','no',N'Longford C',N'LONGFORD C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE012','02','no',N'Longford D',N'LONGFORD D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','04','no',N'Louth',N'LOUTH');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','04','no',N'Louth B',N'LOUTH B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','04','no',N'Louth C',N'LOUTH C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','04','no',N'Louth D',N'LOUTH D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE013','03','no',N'Mayo',N'MAYO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE013','03','no',N'Mayo B',N'MAYO B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE013','03','no',N'Mayo C',N'MAYO C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE013','03','no',N'Mayo D',N'MAYO D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE022','02','no',N'Meath',N'MEATH');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE022','02','no',N'Meath B',N'MEATH B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE022','02','no',N'Meath C',N'MEATH C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE022','02','no',N'Meath D',N'MEATH D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','05','no',N'Monaghan',N'MONAGHAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','05','no',N'Monaghan B',N'MONAGHAN B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','05','no',N'Monaghan C',N'MONAGHAN C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','05','no',N'Monaghan D',N'MONAGHAN D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE023','04','no',N'North Tipperary',N'NORTH TIPPERARY');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE023','04','no',N'North Tipperary B',N'NORTH TIPPERARY B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE023','04','no',N'North Tipperary C',N'NORTH TIPPERARY C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE023','04','no',N'North Tipperary D',N'NORTH TIPPERARY D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE012','03','no',N'Offaly',N'OFFALY');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE012','03','no',N'Offaly B',N'OFFALY B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE012','03','no',N'Offaly C',N'OFFALY C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE012','03','no',N'Offaly D',N'OFFALY D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE013','04','no',N'Roscommon',N'ROSCOMMON');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE013','04','no',N'Roscommon B',N'ROSCOMMON B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE013','04','no',N'Roscommon C',N'ROSCOMMON C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE013','04','no',N'Roscommon D',N'ROSCOMMON D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','06','no',N'Sligo ',N'SLIGO ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','06','no',N'Sligo  B',N'SLIGO  B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','06','no',N'Sligo  C',N'SLIGO  C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE011','06','no',N'Sligo  D',N'SLIGO  D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE021','04','no',N'South Dublin',N'SOUTH DUBLIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE021','04','no',N'South Dublin B',N'SOUTH DUBLIN B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE021','04','no',N'South Dublin C',N'SOUTH DUBLIN C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE021','04','no',N'South Dublin D',N'SOUTH DUBLIN D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','03','no',N'South Tipperary',N'SOUTH TIPPERARY');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','03','no',N'South Tipperary B',N'SOUTH TIPPERARY B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','03','no',N'South Tipperary C',N'SOUTH TIPPERARY C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','03','no',N'South Tipperary D',N'SOUTH TIPPERARY D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','04','no',N'Waterford City',N'WATERFORD CITY');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','04','no',N'Waterford City B',N'WATERFORD CITY B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','04','no',N'Waterford City C',N'WATERFORD CITY C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','04','no',N'Waterford City D',N'WATERFORD CITY D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','05','no',N'Waterford County',N'WATERFORD COUNTY');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','05','no',N'Waterford County B',N'WATERFORD COUNTY B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','05','no',N'Waterford County C',N'WATERFORD COUNTY C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','05','no',N'Waterford County D',N'WATERFORD COUNTY D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE012','04','no',N'Westmeath',N'WESTMEATH');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE012','04','no',N'Westmeath B',N'WESTMEATH B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE012','04','no',N'Westmeath C',N'WESTMEATH C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE012','04','no',N'Westmeath D',N'WESTMEATH D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','06','no',N'Wexford',N'WEXFORD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','06','no',N'Wexford B',N'WEXFORD B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','06','no',N'Wexford C',N'WEXFORD C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE024','06','no',N'Wexford D',N'WEXFORD D');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE022','03','no',N'Wicklow',N'WICKLOW');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE022','03','no',N'Wicklow B',N'WICKLOW B');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE022','03','no',N'Wicklow C',N'WICKLOW C');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IE','IE022','03','no',N'Wicklow D',N'WICKLOW D');
