INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS001','0','no',N'Reykjavíkurborg',N'REYKJAVÍKURBORG');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS001','1000','no',N'Kópavogsbær',N'KÓPAVOGSBÆR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS001','1100','no',N'Seltjarnarneskaupstaður',N'SELTJARNARNESKAUPSTAÐUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS001','1300','no',N'Garðabær',N'GARÐABÆR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS001','1400','no',N'Hafnarfjarðarkaupstaður',N'HAFNARFJARÐARKAUPSTAÐUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS001','1604','no',N'Mosfellsbær',N'MOSFELLSBÆR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS001','1606','no',N'Kjósarhreppur',N'KJÓSARHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','2000','no',N'Reykjanesbær',N'REYKJANESBÆR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','2300','no',N'Grindavíkurbær',N'GRINDAVÍKURBÆR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','2503','no',N'Sandgerðisbær',N'SANDGERÐISBÆR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','2504','no',N'Sveitarfélagið Garður',N'SVEITARFÉLAGIÐ GARÐUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','2506','no',N'Sveitarfélagið Vogar',N'SVEITARFÉLAGIÐ VOGAR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','3000','no',N'Akraneskaupstaður',N'AKRANESKAUPSTAÐUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','3506','no',N'Skorradalshreppur',N'SKORRADALSHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','3511','no',N'Hvalfjarðarsveit',N'HVALFJARÐARSVEIT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','3609','no',N'Borgarbyggð',N'BORGARBYGGÐ');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','3709','no',N'Grundarfjarðarbær',N'GRUNDARFJARÐARBÆR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','3710','no',N'Helgafellssveit',N'HELGAFELLSSVEIT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','3711','no',N'Stykkishólmsbær',N'STYKKISHÓLMSBÆR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','3713','no',N'Eyja- og Miklaholtshreppur',N'EYJA- OG MIKLAHOLTSHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','3714','no',N'Snæfellsbær',N'SNÆFELLSBÆR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','3811','no',N'Dalabyggð',N'DALABYGGÐ');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','4100','no',N'Bolungarvíkurkaupstaður',N'BOLUNGARVÍKURKAUPSTAÐUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','4200','no',N'Ísafjarðarbær',N'ÍSAFJARÐARBÆR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','4502','no',N'Reykhólahreppur',N'REYKHÓLAHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','4604','no',N'Tálknafjarðarhreppur',N'TÁLKNAFJARÐARHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','4607','no',N'Vesturbyggð',N'VESTURBYGGÐ');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','4803','no',N'Súðavíkurhreppur',N'SÚÐAVÍKURHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','4901','no',N'Árneshreppur',N'ÁRNESHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','4902','no',N'Kaldrananeshreppur',N'KALDRANANESHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','4911','no',N'Strandabyggð',N'STRANDABYGGÐ');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','5200','no',N'Sveitarfélagið Skagafjörður',N'SVEITARFÉLAGIÐ SKAGAFJÖRÐUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','5508','no',N'Húnaþing vestra',N'HÚNAÞING VESTRA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','5604','no',N'Blönduósbær',N'BLÖNDUÓSBÆR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','5609','no',N'Sveitarfélagið Skagaströnd',N'SVEITARFÉLAGIÐ SKAGASTRÖND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','5611','no',N'Skagabyggð',N'SKAGABYGGÐ');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','5612','no',N'Húnavatnshreppur',N'HÚNAVATNSHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','5706','no',N'Akrahreppur',N'AKRAHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6000','no',N'Akureyrarkaupstaður',N'AKUREYRARKAUPSTAÐUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6100','no',N'Norðurþing',N'NORÐURÞING');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6250','no',N'Fjallabyggð',N'FJALLABYGGÐ');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6400','no',N'Dalvíkurbyggð',N'DALVÍKURBYGGÐ');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6513','no',N'Eyjafjarðarsveit',N'EYJAFJARÐARSVEIT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6515','no',N'Hörgársveit',N'HÖRGÁRSVEIT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6601','no',N'Svalbarðsstrandarhreppur',N'SVALBARÐSSTRANDARHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6602','no',N'Grýtubakkahreppur',N'GRÝTUBAKKAHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6607','no',N'Skútustaðahreppur',N'SKÚTUSTAÐAHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6611','no',N'Tjörneshreppur',N'TJÖRNESHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6612','no',N'Þingeyjarsveit',N'ÞINGEYJARSVEIT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6706','no',N'Svalbarðshreppur',N'SVALBARÐSHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6709','no',N'Langanesbyggð',N'LANGANESBYGGÐ');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','7000','no',N'Seyðisfjarðarkaupstaður',N'SEYÐISFJARÐARKAUPSTAÐUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','7300','no',N'Fjarðabyggð',N'FJARÐABYGGÐ');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','7502','no',N'Vopnafjarðarhreppur',N'VOPNAFJARÐARHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','7505','no',N'Fljótsdalshreppur',N'FLJÓTSDALSHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','7509','no',N'Borgarfjarðarhreppur',N'BORGARFJARÐARHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','7613','no',N'Breiðdalshreppur',N'BREIÐDALSHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','7617','no',N'Djúpavogshreppur',N'DJÚPAVOGSHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','7620','no',N'Fljótsdalshérað',N'FLJÓTSDALSHÉRAÐ');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','7708','no',N'Sveitarfélagið Hornafjörður',N'SVEITARFÉLAGIÐ HORNAFJÖRÐUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8000','no',N'Vestmannaeyjabær',N'VESTMANNAEYJABÆR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8200','no',N'Sveitarfélagið Árborg',N'SVEITARFÉLAGIÐ ÁRBORG');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8508','no',N'Mýrdalshreppur',N'MÝRDALSHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8509','no',N'Skaftárhreppur',N'SKAFTÁRHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8610','no',N'Ásahreppur',N'ÁSAHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8613','no',N'Rangárþing eystra',N'RANGÁRÞING EYSTRA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8614','no',N'Rangárþing ytra',N'RANGÁRÞING YTRA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8710','no',N'Hrunamannahreppur',N'HRUNAMANNAHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8716','no',N'Hveragerðisbær',N'HVERAGERÐISBÆR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8717','no',N'Sveitarfélagið Ölfus',N'SVEITARFÉLAGIÐ ÖLFUS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8719','no',N'Grímsnes- og Grafningshreppur',N'GRÍMSNES- OG GRAFNINGSHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8720','no',N'Skeiða- og Gnúpverjahreppur',N'SKEIÐA- OG GNÚPVERJAHREPPUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8721','no',N'Bláskógabyggð',N'BLÁSKÓGABYGGÐ');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8722','no',N'Flóahreppur',N'FLÓAHREPPUR');
