INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS001','0','no',N'Reykjavik',N'REYKJAVIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS001','1000','no',N'Kopavogur',N'KOPAVOGUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS001','1100','no',N'Seltjarnarnes',N'SELTJARNARNES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS001','1300','no',N'Gardabaer',N'GARDABAER');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS001','1400','no',N'Hafnarfjordur',N'HAFNARFJORDUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS001','1604','no',N'Mosfellsbaer',N'MOSFELLSBAER');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS001','1606','no',N'Kjosarhreppur',N'KJOSARHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','2000','no',N'Reykjanesbaer',N'REYKJANESBAER');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','2300','no',N'Grindavikurbaer',N'GRINDAVIKURBAER');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','2503','no',N'Sandgerdi',N'SANDGERDI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','2504','no',N'Sveitarfelagid Gardur',N'SVEITARFELAGID GARDUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','2506','no',N'Sveitarfelagid Vogar',N'SVEITARFELAGID VOGAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','3000','no',N'Akranes',N'AKRANES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','3506','no',N'Skorradalshreppur',N'SKORRADALSHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','3511','no',N'Hvalfjardarsveit',N'HVALFJARDARSVEIT');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','3609','no',N'Borgarbyggd',N'BORGARBYGGD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','3709','no',N'Grundarfjardarbaer',N'GRUNDARFJARDARBAER');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','3710','no',N'Helgafellssveit',N'HELGAFELLSSVEIT');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','3711','no',N'Stykkisholmur',N'STYKKISHOLMUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','3713','no',N'Eyja- og Miklaholtshreppur',N'EYJA- OG MIKLAHOLTSHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','3714','no',N'Snaefellsbaer',N'SNAEFELLSBAER');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','3811','no',N'Dalabyggd',N'DALABYGGD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','4100','no',N'Bolungarvik',N'BOLUNGARVIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','4200','no',N'Isafjardarbaer',N'ISAFJARDARBAER');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','4502','no',N'Reykholahreppur',N'REYKHOLAHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','4604','no',N'Talknafjardarhreppur',N'TALKNAFJARDARHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','4607','no',N'Vesturbyggd',N'VESTURBYGGD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','4803','no',N'Sudavikurhreppur',N'SUDAVIKURHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','4901','no',N'Arneshreppur',N'ARNESHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','4902','no',N'Kaldrananeshreppur',N'KALDRANANESHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','4911','no',N'Strandabyggd',N'STRANDABYGGD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','5200','no',N'Sveitarfelagid Skagafjordur',N'SVEITARFELAGID SKAGAFJORDUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','5508','no',N'Hunathing vestra',N'HUNATHING VESTRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','5604','no',N'Blonduossbaer',N'BLONDUOSSBAER');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','5609','no',N'Sveitarfelagid Skagastrond',N'SVEITARFELAGID SKAGASTROND');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','5611','no',N'Skagabyggd',N'SKAGABYGGD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','5612','no',N'Hunavatnshreppur',N'HUNAVATNSHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','5706','no',N'Akrahreppur',N'AKRAHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6000','no',N'Akureyri',N'AKUREYRI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6100','no',N'Nordurthing',N'NORDURTHING');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6250','no',N'Fjallabyggd',N'FJALLABYGGD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6400','no',N'Dalvikurbyggd',N'DALVIKURBYGGD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6513','no',N'Eyjafjardarsveit',N'EYJAFJARDARSVEIT');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6515','no',N'Horgarsveit',N'HORGARSVEIT');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6601','no',N'Svalbardsstrandarhreppur',N'SVALBARDSSTRANDARHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6602','no',N'Grytubakkahreppur',N'GRYTUBAKKAHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6607','no',N'Skutustadahreppur',N'SKUTUSTADAHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6611','no',N'Tjorneshreppur',N'TJORNESHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6612','no',N'Thingeyjarsveit',N'THINGEYJARSVEIT');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6706','no',N'Svalbardshreppur',N'SVALBARDSHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','6709','no',N'Langanesbyggd',N'LANGANESBYGGD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','7000','no',N'Seydisfjordur',N'SEYDISFJORDUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','7300','no',N'Fjardabyggd',N'FJARDABYGGD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','7502','no',N'Vopnafjardarhreppur',N'VOPNAFJARDARHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','7505','no',N'Fljotsdalshreppur',N'FLJOTSDALSHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','7509','no',N'Borgarfjardarhreppur',N'BORGARFJARDARHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','7613','no',N'Breiddalshreppur',N'BREIDDALSHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','7617','no',N'Djupavogshreppur',N'DJUPAVOGSHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','7620','no',N'Fljotsdalsherad',N'FLJOTSDALSHERAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','7708','no',N'Sveitarfelagid Hornafjordur',N'SVEITARFELAGID HORNAFJORDUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8000','no',N'Vestmannaeyjar',N'VESTMANNAEYJAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8200','no',N'Sveitarfelagid Arborg',N'SVEITARFELAGID ARBORG');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8508','no',N'Myrdalshreppur',N'MYRDALSHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8509','no',N'Skaftarhreppur',N'SKAFTARHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8610','no',N'Asahreppur',N'ASAHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8613','no',N'Rangarthing eystra',N'RANGARTHING EYSTRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8614','no',N'Rangarthing ytra',N'RANGARTHING YTRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8710','no',N'Hrunamannahreppur',N'HRUNAMANNAHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8716','no',N'Hveragerdi',N'HVERAGERDI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8717','no',N'Sveitarfelagid Olfus',N'SVEITARFELAGID OLFUS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8719','no',N'Grimsnes- og Grafningshreppur',N'GRIMSNES- OG GRAFNINGSHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8720','no',N'Skeida- og Gnupverjahreppur',N'SKEIDA- OG GNUPVERJAHREPPUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8721','no',N'Blaskogabyggd',N'BLASKOGABYGGD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('IS','IS002','8722','no',N'Floahreppur',N'FLOAHREPPUR');
