INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT006','3200','no',N'Akmenės r. sav.',N'AKMENĖS R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT001','1100','no',N'Alytaus m. sav.',N'ALYTAUS M. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT001','3300','no',N'Alytaus r. sav.',N'ALYTAUS R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT009','3400','no',N'Anykščių r. sav.',N'ANYKŠČIŲ R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT002','1200','no',N'Birštono sav.',N'BIRŠTONO SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT005','3600','no',N'Biržų r. sav.',N'BIRŽŲ R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT001','1500','no',N'Druskininkų sav.',N'DRUSKININKŲ SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT00A','4200','no',N'Elektrėnų sav.',N'ELEKTRĖNŲ SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT009','4500','no',N'Ignalinos r. sav.',N'IGNALINOS R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT002','4600','no',N'Jonavos r. sav.',N'JONAVOS R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT006','4700','no',N'Joniškio r. sav.',N'JONIŠKIO R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT007','9400','no',N'Jurbarko r. sav.',N'JURBARKO R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT002','4900','no',N'Kaišiadorių r. sav.',N'KAIŠIADORIŲ R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT004','4800','no',N'Kalvarijos sav.',N'KALVARIJOS SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT002','1900','no',N'Kauno m. sav.',N'KAUNO M. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT002','5200','no',N'Kauno r. sav.',N'KAUNO R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT004','5800','no',N'Kazlų Rūdos sav.',N'KAZLŲ RŪDOS SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT002','5300','no',N'Kėdainių r. sav.',N'KĖDAINIŲ R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT006','5400','no',N'Kelmės r. sav.',N'KELMĖS R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT003','2100','no',N'Klaipėdos m. sav.',N'KLAIPĖDOS M. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT003','5500','no',N'Klaipėdos r. sav.',N'KLAIPĖDOS R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT003','5600','no',N'Kretingos r. sav.',N'KRETINGOS R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT005','5700','no',N'Kupiškio r. sav.',N'KUPIŠKIO R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT001','5900','no',N'Lazdijų r. sav.',N'LAZDIJŲ R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT004','1800','no',N'Marijampolės sav.',N'MARIJAMPOLĖS SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT008','6100','no',N'Mažeikių r. sav.',N'MAŽEIKIŲ R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT009','6200','no',N'Molėtų r. sav.',N'MOLĖTŲ R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT003','2300','no',N'Neringos sav.',N'NERINGOS SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT007','6300','no',N'Pagėgių sav.',N'PAGĖGIŲ SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT006','6500','no',N'Pakruojo r. sav.',N'PAKRUOJO R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT003','2500','no',N'Palangos m. sav.',N'PALANGOS M. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT005','2700','no',N'Panevėžio m. sav.',N'PANEVĖŽIO M. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT005','6600','no',N'Panevėžio r. sav.',N'PANEVĖŽIO R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT005','6700','no',N'Pasvalio r. sav.',N'PASVALIO R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT008','6800','no',N'Plungės r. sav.',N'PLUNGĖS R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT002','6900','no',N'Prienų r. sav.',N'PRIENŲ R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT006','7100','no',N'Radviliškio r. sav.',N'RADVILIŠKIO R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT002','7200','no',N'Raseinių r. sav.',N'RASEINIŲ R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT008','7400','no',N'Rietavo sav.',N'RIETAVO SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT005','7300','no',N'Rokiškio r. sav.',N'ROKIŠKIO R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT004','8400','no',N'Šakių r. sav.',N'ŠAKIŲ R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT00A','8500','no',N'Šalčininkų r. sav.',N'ŠALČININKŲ R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT006','2900','no',N'Šiaulių m. sav.',N'ŠIAULIŲ M. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT006','9100','no',N'Šiaulių r. sav.',N'ŠIAULIŲ R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT007','8700','no',N'Šilalės r. sav.',N'ŠILALĖS R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT003','8800','no',N'Šilutės r. sav.',N'ŠILUTĖS R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT00A','8900','no',N'Širvintų r. sav.',N'ŠIRVINTŲ R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT003','7500','no',N'Skuodo r. sav.',N'SKUODO R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT00A','8600','no',N'Švenčionių r. sav.',N'ŠVENČIONIŲ R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT007','7700','no',N'Tauragės r. sav.',N'TAURAGĖS R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT008','7800','no',N'Telšių r. sav.',N'TELŠIŲ R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT00A','7900','no',N'Trakų r. sav.',N'TRAKŲ R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT00A','8100','no',N'Ukmergės r. sav.',N'UKMERGĖS R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT009','8200','no',N'Utenos r. sav.',N'UTENOS R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT001','3800','no',N'Varėnos r. sav.',N'VARĖNOS R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT004','3900','no',N'Vilkaviškio r. sav.',N'VILKAVIŠKIO R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT00A','1300','no',N'Vilniaus m. sav.',N'VILNIAUS M. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT00A','4100','no',N'Vilniaus r. sav.',N'VILNIAUS R. SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT009','3000','no',N'Visagino sav.',N'VISAGINO SAV.');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT009','4300','no',N'Zarasų r. sav.',N'ZARASŲ R. SAV.');
