INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT006','3200','no',N'Akmenės rajono savivaldybė',N'AKMENĖS RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT001','1100','no',N'Alytaus miesto savivaldybė',N'ALYTAUS MIESTO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT001','3300','no',N'Alytaus rajono savivaldybė',N'ALYTAUS RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT009','3400','no',N'Anykščių rajono savivaldybė',N'ANYKŠČIŲ RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT002','1200','no',N'Birštono savivaldybė',N'BIRŠTONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT005','3600','no',N'Biržų rajono savivaldybė',N'BIRŽŲ RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT001','1500','no',N'Druskininkų savivaldybė',N'DRUSKININKŲ SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT00A','4200','no',N'Elektrėnų savivaldybė',N'ELEKTRĖNŲ SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT009','4500','no',N'Ignalinos rajono savivaldybė',N'IGNALINOS RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT002','4600','no',N'Jonavos rajono savivaldybė',N'JONAVOS RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT006','4700','no',N'Joniškio rajono savivaldybė',N'JONIŠKIO RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT007','9400','no',N'Jurbarko rajono savivaldybė',N'JURBARKO RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT002','4900','no',N'Kaišiadorių rajono savivaldybė',N'KAIŠIADORIŲ RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT004','4800','no',N'Kalvarijos savivaldybė',N'KALVARIJOS SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT002','1900','no',N'Kauno miesto savivaldybė',N'KAUNO MIESTO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT002','5200','no',N'Kauno rajono savivaldybė',N'KAUNO RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT004','5800','no',N'Kazlų Rūdos savivaldybė',N'KAZLŲ RŪDOS SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT002','5300','no',N'Kėdainių rajono savivaldybė',N'KĖDAINIŲ RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT006','5400','no',N'Kelmės rajono savivaldybė',N'KELMĖS RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT003','2100','no',N'Klaipėdos miesto savivaldybė',N'KLAIPĖDOS MIESTO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT003','5500','no',N'Klaipėdos rajono savivaldybė',N'KLAIPĖDOS RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT003','5600','no',N'Kretingos rajono savivaldybė',N'KRETINGOS RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT005','5700','no',N'Kupiškio rajono savivaldybė',N'KUPIŠKIO RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT001','5900','no',N'Lazdijų rajono savivaldybė',N'LAZDIJŲ RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT004','1800','no',N'Marijampolės savivaldybė',N'MARIJAMPOLĖS SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT008','6100','no',N'Mažeikių rajono savivaldybė',N'MAŽEIKIŲ RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT009','6200','no',N'Molėtų rajono savivaldybė',N'MOLĖTŲ RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT003','2300','no',N'Neringos savivaldybė',N'NERINGOS SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT007','6300','no',N'Pagėgių savivaldybė',N'PAGĖGIŲ SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT006','6500','no',N'Pakruojo rajono savivaldybė',N'PAKRUOJO RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT003','2500','no',N'Palangos miesto savivaldybė',N'PALANGOS MIESTO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT005','2700','no',N'Panevėžio miesto savivaldybė',N'PANEVĖŽIO MIESTO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT005','6600','no',N'Panevėžio rajono savivaldybė',N'PANEVĖŽIO RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT005','6700','no',N'Pasvalio rajono savivaldybė',N'PASVALIO RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT008','6800','no',N'Plungės rajono savivaldybė',N'PLUNGĖS RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT002','6900','no',N'Prienų rajono savivaldybė',N'PRIENŲ RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT006','7100','no',N'Radviliškio rajono savivaldybė',N'RADVILIŠKIO RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT002','7200','no',N'Raseinių rajono savivaldybė',N'RASEINIŲ RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT008','7400','no',N'Rietavo savivaldybė',N'RIETAVO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT005','7300','no',N'Rokiškio rajono savivaldybė',N'ROKIŠKIO RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT004','8400','no',N'Šakių rajono savivaldybė',N'ŠAKIŲ RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT00A','8500','no',N'Šalčininkų rajono savivaldybė',N'ŠALČININKŲ RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT006','2900','no',N'Šiaulių miesto savivaldybė',N'ŠIAULIŲ MIESTO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT006','9100','no',N'Šiaulių rajono savivaldybė',N'ŠIAULIŲ RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT007','8700','no',N'Šilalės rajono savivaldybė',N'ŠILALĖS RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT003','8800','no',N'Šilutės rajono savivaldybė',N'ŠILUTĖS RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT00A','8900','no',N'Širvintų rajono savivaldybė',N'ŠIRVINTŲ RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT003','7500','no',N'Skuodo rajono savivaldybė',N'SKUODO RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT00A','8600','no',N'Švenčionių rajono savivaldybė',N'ŠVENČIONIŲ RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT007','7700','no',N'Tauragės rajono savivaldybė',N'TAURAGĖS RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT008','7800','no',N'Telšių rajono savivaldybė',N'TELŠIŲ RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT00A','7900','no',N'Trakų rajono savivaldybė',N'TRAKŲ RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT00A','8100','no',N'Ukmergės rajono savivaldybė',N'UKMERGĖS RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT009','8200','no',N'Utenos rajono savivaldybė',N'UTENOS RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT001','3800','no',N'Varėnos rajono savivaldybė',N'VARĖNOS RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT004','3900','no',N'Vilkaviškio rajono savivaldybė',N'VILKAVIŠKIO RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT00A','1300','no',N'Vilniaus miesto savivaldybė',N'VILNIAUS MIESTO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT00A','4100','no',N'Vilniaus rajono savivaldybė',N'VILNIAUS RAJONO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT009','3000','no',N'Visagino savivaldybė',N'VISAGINO SAVIVALDYBĖ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('LT','LT009','4300','no',N'Zarasų rajono savivaldybė',N'ZARASŲ RAJONO SAVIVALDYBĖ');
