INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01101','no',N'Citta'' Umilissima',N'CITTA'' UMILISSIMA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01103','no',N'Citta'' Vittoriosa',N'CITTA'' VITTORIOSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01104','no',N'Citta'' Invicta',N'CITTA'' INVICTA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01105','no',N'Citta'' Cospicua',N'CITTA'' COSPICUA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01108','no',N'Citta'' Hompesch',N'CITTA'' HOMPESCH');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01117','no',N'Fgura',N'FGURA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01118','no',N'Floriana',N'FLORIANA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01129','no',N'Kalkara',N'KALKARA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01133','no',N'Luqa',N'LUQA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01134','no',N'Marsa',N'MARSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01145','no',N'Paola',N'PAOLA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01157','no',N'Santa Luċija',N'SANTA LUĊIJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01162','no',N'Tarxien',N'TARXIEN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01165','no',N'Xgħajra',N'XGĦAJRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01206','no',N'Citta'' Pinto',N'CITTA'' PINTO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01214','no',N'Birkirkara',N'BIRKIRKARA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01221','no',N'Gżira',N'GŻIRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01227','no',N'Ħamrun',N'ĦAMRUN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01241','no',N'Msida',N'MSIDA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01246','no',N'Pembroke',N'PEMBROKE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01247','no',N'Pieta''',N'PIETA''');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01252','no',N'San Ġiljan',N'SAN ĠILJAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01253','no',N'San Ġwann',N'SAN ĠWANN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01258','no',N'Santa Venera',N'SANTA VENERA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01259','no',N'Sliema',N'SLIEMA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01260','no',N'Swieqi',N'SWIEQI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01261','no',N'Ta'' Xbiex',N'TA'' XBIEX');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01310','no',N'Citta'' Beland',N'CITTA'' BELAND');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01315','no',N'Birżebbuġa',N'BIRŻEBBUĠA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01320','no',N'Gudja',N'GUDJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01326','no',N'Għaxaq',N'GĦAXAQ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01331','no',N'Kirkop',N'KIRKOP');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01335','no',N'Marsaskala',N'MARSASKALA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01336','no',N'Marsaxlokk',N'MARSAXLOKK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01340','no',N'Mqabba',N'MQABBA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01349','no',N'Qrendi',N'QRENDI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01351','no',N'Safi',N'SAFI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01367','no',N'Żurrieq',N'ŻURRIEQ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01402','no',N'Citta'' Notabile',N'CITTA'' NOTABILE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01407','no',N'Citta'' Rohan',N'CITTA'' ROHAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01409','no',N'Citta'' Ferdinand',N'CITTA'' FERDINAND');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01412','no',N'Attard',N'ATTARD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01413','no',N'Balzan',N'BALZAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01416','no',N'Dingli',N'DINGLI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01428','no',N'Iklin',N'IKLIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01432','no',N'Lija',N'LIJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01450','no',N'Rabat (Malta)',N'RABAT (MALTA)');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01468','no',N'Mtarfa',N'MTARFA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01524','no',N'Għargħur',N'GĦARGĦUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01537','no',N'Mellieħa',N'MELLIEĦA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01538','no',N'Mġarr',N'MĠARR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01539','no',N'Mosta',N'MOSTA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01544','no',N'Naxxar',N'NAXXAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01555','no',N'San Pawl Il-Baħar',N'SAN PAWL IL-BAĦAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02611','no',N'Citta'' Victoria',N'CITTA'' VICTORIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02619','no',N'Fontana',N'FONTANA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02622','no',N'Għajnsielem and Comino',N'GĦAJNSIELEM AND COMINO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02623','no',N'Għarb',N'GĦARB');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02625','no',N'Għasri',N'GĦASRI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02630','no',N'Kerċem',N'KERĊEM');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02642','no',N'Munxar',N'MUNXAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02643','no',N'Nadur',N'NADUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02648','no',N'Qala',N'QALA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02654','no',N'San Lawrenz',N'SAN LAWRENZ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02656','no',N'Sannat',N'SANNAT');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02663','no',N'Xagħra',N'XAGĦRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02664','no',N'Xewkija',N'XEWKIJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02666','no',N'Żebbuġ (Gozo)',N'ŻEBBUĠ (GOZO)');
