INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01101','no',N'Valletta',N'VALLETTA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01103','no',N'Birgu',N'BIRGU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01104','no',N'L-Isla',N'L-ISLA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01105','no',N'Bormla',N'BORMLA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01108','no',N'Ħaż-Żabbar',N'ĦAŻ-ŻABBAR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01117','no',N'Il-Fgura',N'IL-FGURA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01118','no',N'Il-Furjana',N'IL-FURJANA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01129','no',N'Il-Kalkara',N'IL-KALKARA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01133','no',N'Ħal Luqa',N'ĦAL LUQA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01134','no',N'Il-Marsa',N'IL-MARSA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01145','no',N'Paola',N'PAOLA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01157','no',N'Santa Luċija',N'SANTA LUĊIJA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01162','no',N'Ħal Tarxien',N'ĦAL TARXIEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01165','no',N'Ix-Xgħajra',N'IX-XGĦAJRA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01206','no',N'Ħal Qormi',N'ĦAL QORMI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01214','no',N'Birkirkara',N'BIRKIRKARA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01221','no',N'Il-Gżira',N'IL-GŻIRA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01227','no',N'Il-Ħamrun',N'IL-ĦAMRUN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01241','no',N'L-Imsida',N'L-IMSIDA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01246','no',N'Pembroke',N'PEMBROKE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01247','no',N'Tal-Pieta''',N'TAL-PIETA''');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01252','no',N'San Ġiljan',N'SAN ĠILJAN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01253','no',N'San Ġwann',N'SAN ĠWANN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01258','no',N'Santa Venera',N'SANTA VENERA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01259','no',N'Tas-Sliema',N'TAS-SLIEMA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01260','no',N'Is-Swieqi',N'IS-SWIEQI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01261','no',N'Ta'' Xbiex',N'TA'' XBIEX');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01310','no',N'Iż-Żejtun',N'IŻ-ŻEJTUN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01315','no',N'Birżebbuġa',N'BIRŻEBBUĠA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01320','no',N'Il-Gudja',N'IL-GUDJA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01326','no',N'Ħal Għaxaq',N'ĦAL GĦAXAQ');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01331','no',N'Ħal Kirkop',N'ĦAL KIRKOP');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01335','no',N'Marsaskala',N'MARSASKALA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01336','no',N'Marsaxlokk',N'MARSAXLOKK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01340','no',N'L-Imqabba',N'L-IMQABBA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01349','no',N'Il-Qrendi',N'IL-QRENDI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01351','no',N'Ħal Safi',N'ĦAL SAFI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01367','no',N'Iż-Żurrieq',N'IŻ-ŻURRIEQ');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01402','no',N'L-Imdina',N'L-IMDINA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01407','no',N'Ħaż-Żebbuġ',N'ĦAŻ-ŻEBBUĠ');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01409','no',N'Is-Siġġiewi',N'IS-SIĠĠIEWI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01412','no',N'Ħ''Attard',N'Ħ''ATTARD');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01413','no',N'Ħal Balzan',N'ĦAL BALZAN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01416','no',N'Ħad-Dingli',N'ĦAD-DINGLI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01428','no',N'L-Iklin',N'L-IKLIN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01432','no',N'Ħal Lija',N'ĦAL LIJA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01450','no',N'Ir-Rabat',N'IR-RABAT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01468','no',N'L-Imtarfa',N'L-IMTARFA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01524','no',N'Ħal Għargħur',N'ĦAL GĦARGĦUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01537','no',N'Il-Mellieħa',N'IL-MELLIEĦA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01538','no',N'L-Imġarr',N'L-IMĠARR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01539','no',N'Il-Mosta',N'IL-MOSTA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01544','no',N'In-Naxxar',N'IN-NAXXAR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT001','MT01555','no',N'San Pawl Il-Baħar',N'SAN PAWL IL-BAĦAR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02611','no',N'Ir-Rabat, Għawdex',N'IR-RABAT, GĦAWDEX');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02619','no',N'Il-Fontana',N'IL-FONTANA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02622','no',N'Għajnsielem and Comino',N'GĦAJNSIELEM AND COMINO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02623','no',N'L-Għarb',N'L-GĦARB');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02625','no',N'L-Għasri',N'L-GĦASRI');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02630','no',N'Ta'' Kerċem',N'TA'' KERĊEM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02642','no',N'Il-Munxar',N'IL-MUNXAR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02643','no',N'In-Nadur',N'IN-NADUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02648','no',N'Il-Qala',N'IL-QALA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02654','no',N'San Lawrenz',N'SAN LAWRENZ');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02656','no',N'Ta'' Sannat',N'TA'' SANNAT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02663','no',N'Ix-Xagħra',N'IX-XAGĦRA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02664','no',N'Ix-Xewkija',N'IX-XEWKIJA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('MT','MT002','MT02666','no',N'Iż-Żebbuġ',N'IŻ-ŻEBBUĠ');
