INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL112','GM0003','no',N'Appingedam',N'APPINGEDAM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL113','GM0005','no',N'Bedum',N'BEDUM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL113','GM0009','no',N'Ten Boer',N'TEN BOER');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL112','GM0010','no',N'Delfzijl',N'DELFZIJL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL113','GM0014','no',N'Groningen',N'GRONINGEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL113','GM0015','no',N'Grootegast',N'GROOTEGAST');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL113','GM0017','no',N'Haren',N'HAREN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL113','GM0022','no',N'Leek',N'LEEK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL112','GM0024','no',N'Loppersum',N'LOPPERSUM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL113','GM0025','no',N'Marum',N'MARUM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL230','GM0034','no',N'Almere',N'ALMERE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL111','GM0037','no',N'Stadskanaal',N'STADSKANAAL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL111','GM0047','no',N'Veendam',N'VEENDAM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL230','GM0050','no',N'Zeewolde',N'ZEEWOLDE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL113','GM0053','no',N'Winsum',N'WINSUM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL113','GM0056','no',N'Zuidhorn',N'ZUIDHORN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL121','GM0058','no',N'Dongeradeel',N'DONGERADEEL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL121','GM0059','no',N'Achtkarspelen',N'ACHTKARSPELEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL121','GM0060','no',N'Ameland',N'AMELAND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL121','GM0072','no',N'Harlingen',N'HARLINGEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL123','GM0074','no',N'Heerenveen',N'HEERENVEEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL121','GM0079','no',N'Kollumerland en Nieuwkruisland',N'KOLLUMERLAND EN NIEUWKRUISLAND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL121','GM0080','no',N'Leeuwarden',N'LEEUWARDEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL123','GM0085','no',N'Ooststellingwerf',N'OOSTSTELLINGWERF');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL123','GM0086','no',N'Opsterland',N'OPSTERLAND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL121','GM0088','no',N'Schiermonnikoog',N'SCHIERMONNIKOOG');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL123','GM0090','no',N'Smallingerland',N'SMALLINGERLAND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL121','GM0093','no',N'Terschelling',N'TERSCHELLING');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL121','GM0096','no',N'Vlieland',N'VLIELAND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL123','GM0098','no',N'Weststellingwerf',N'WESTSTELLINGWERF');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL131','GM0106','no',N'Assen',N'ASSEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL132','GM0109','no',N'Coevorden',N'COEVORDEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL132','GM0114','no',N'Emmen',N'EMMEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL133','GM0118','no',N'Hoogeveen',N'HOOGEVEEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL133','GM0119','no',N'Meppel',N'MEPPEL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL213','GM0141','no',N'Almelo',N'ALMELO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL213','GM0147','no',N'Borne',N'BORNE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL211','GM0148','no',N'Dalfsen',N'DALFSEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL212','GM0150','no',N'Deventer',N'DEVENTER');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL213','GM0153','no',N'Enschede',N'ENSCHEDE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL213','GM0158','no',N'Haaksbergen',N'HAAKSBERGEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL211','GM0160','no',N'Hardenberg',N'HARDENBERG');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL213','GM0163','no',N'Hellendoorn',N'HELLENDOORN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL213','GM0164','no',N'Hengelo',N'HENGELO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL211','GM0166','no',N'Kampen',N'KAMPEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL213','GM0168','no',N'Losser',N'LOSSER');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL230','GM0171','no',N'Noordoostpolder',N'NOORDOOSTPOLDER');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL213','GM0173','no',N'Oldenzaal',N'OLDENZAAL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL211','GM0175','no',N'Ommen',N'OMMEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL212','GM0177','no',N'Raalte',N'RAALTE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL211','GM0180','no',N'Staphorst',N'STAPHORST');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL213','GM0183','no',N'Tubbergen',N'TUBBERGEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL230','GM0184','no',N'Urk',N'URK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL213','GM0189','no',N'Wierden',N'WIERDEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL211','GM0193','no',N'Zwolle',N'ZWOLLE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL225','GM0197','no',N'Aalten',N'AALTEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL221','GM0200','no',N'Apeldoorn',N'APELDOORN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL226','GM0202','no',N'Arnhem',N'ARNHEM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL221','GM0203','no',N'Barneveld',N'BARNEVELD');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL226','GM0209','no',N'Beuningen',N'BEUNINGEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL225','GM0213','no',N'Brummen',N'BRUMMEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL224','GM0214','no',N'Buren',N'BUREN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL224','GM0216','no',N'Culemborg',N'CULEMBORG');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL226','GM0221','no',N'Doesburg',N'DOESBURG');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL225','GM0222','no',N'Doetinchem',N'DOETINCHEM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL226','GM0225','no',N'Druten',N'DRUTEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL226','GM0226','no',N'Duiven',N'DUIVEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL221','GM0228','no',N'Ede',N'EDE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL221','GM0230','no',N'Elburg',N'ELBURG');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL221','GM0232','no',N'Epe',N'EPE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL221','GM0233','no',N'Ermelo',N'ERMELO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL224','GM0236','no',N'Geldermalsen',N'GELDERMALSEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL221','GM0243','no',N'Harderwijk',N'HARDERWIJK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL221','GM0244','no',N'Hattem',N'HATTEM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL221','GM0246','no',N'Heerde',N'HEERDE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL226','GM0252','no',N'Heumen',N'HEUMEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL225','GM0262','no',N'Lochem',N'LOCHEM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL224','GM0263','no',N'Maasdriel',N'MAASDRIEL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL221','GM0267','no',N'Nijkerk',N'NIJKERK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL226','GM0268','no',N'Nijmegen',N'NIJMEGEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL221','GM0269','no',N'Oldebroek',N'OLDEBROEK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL221','GM0273','no',N'Putten',N'PUTTEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL226','GM0274','no',N'Renkum',N'RENKUM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL226','GM0275','no',N'Rheden',N'RHEDEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL226','GM0277','no',N'Rozendaal',N'ROZENDAAL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL221','GM0279','no',N'Scherpenzeel',N'SCHERPENZEEL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL224','GM0281','no',N'Tiel',N'TIEL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL221','GM0285','no',N'Voorst',N'VOORST');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL221','GM0289','no',N'Wageningen',N'WAGENINGEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL226','GM0293','no',N'Westervoort',N'WESTERVOORT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL225','GM0294','no',N'Winterswijk',N'WINTERSWIJK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL226','GM0296','no',N'Wijchen',N'WIJCHEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL224','GM0297','no',N'Zaltbommel',N'ZALTBOMMEL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL226','GM0299','no',N'Zevenaar',N'ZEVENAAR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL225','GM0301','no',N'Zutphen',N'ZUTPHEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL221','GM0302','no',N'Nunspeet',N'NUNSPEET');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL230','GM0303','no',N'Dronten',N'DRONTEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL224','GM0304','no',N'Neerijnen',N'NEERIJNEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0307','no',N'Amersfoort',N'AMERSFOORT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0308','no',N'Baarn',N'BAARN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0310','no',N'De Bilt',N'DE BILT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0312','no',N'Bunnik',N'BUNNIK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0313','no',N'Bunschoten',N'BUNSCHOTEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0317','no',N'Eemnes',N'EEMNES');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0321','no',N'Houten',N'HOUTEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0327','no',N'Leusden',N'LEUSDEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0331','no',N'Lopik',N'LOPIK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0335','no',N'Montfoort',N'MONTFOORT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0339','no',N'Renswoude',N'RENSWOUDE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0340','no',N'Rhenen',N'RHENEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0342','no',N'Soest',N'SOEST');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0344','no',N'Utrecht',N'UTRECHT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0345','no',N'Veenendaal',N'VEENENDAAL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0351','no',N'Woudenberg',N'WOUDENBERG');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0352','no',N'Wijk bij Duurstede',N'WIJK BIJ DUURSTEDE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0353','no',N'IJsselstein',N'IJSSELSTEIN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0355','no',N'Zeist',N'ZEIST');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0356','no',N'Nieuwegein',N'NIEUWEGEIN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL326','GM0358','no',N'Aalsmeer',N'AALSMEER');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL322','GM0361','no',N'Alkmaar',N'ALKMAAR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL326','GM0362','no',N'Amstelveen',N'AMSTELVEEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL326','GM0363','no',N'Amsterdam',N'AMSTERDAM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL326','GM0370','no',N'Beemster',N'BEEMSTER');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL322','GM0373','no',N'Bergen (NH.)',N'BERGEN (NH.)');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL323','GM0375','no',N'Beverwijk',N'BEVERWIJK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL327','GM0376','no',N'Blaricum',N'BLARICUM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL324','GM0377','no',N'Bloemendaal',N'BLOEMENDAAL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL323','GM0383','no',N'Castricum',N'CASTRICUM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL326','GM0384','no',N'Diemen',N'DIEMEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL326','GM0385','no',N'Edam-Volendam',N'EDAM-VOLENDAM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL321','GM0388','no',N'Enkhuizen',N'ENKHUIZEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL324','GM0392','no',N'Haarlem',N'HAARLEM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL324','GM0393','no',N'Haarlemmerliede en Spaarnwoude',N'HAARLEMMERLIEDE EN SPAARNWOUDE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL326','GM0394','no',N'Haarlemmermeer',N'HAARLEMMERMEER');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL323','GM0396','no',N'Heemskerk',N'HEEMSKERK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL324','GM0397','no',N'Heemstede',N'HEEMSTEDE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL322','GM0398','no',N'Heerhugowaard',N'HEERHUGOWAARD');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL322','GM0399','no',N'Heiloo',N'HEILOO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL321','GM0400','no',N'Den Helder',N'DEN HELDER');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL327','GM0402','no',N'Hilversum',N'HILVERSUM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL321','GM0405','no',N'Hoorn',N'HOORN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL327','GM0406','no',N'Huizen',N'HUIZEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL326','GM0415','no',N'Landsmeer',N'LANDSMEER');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL322','GM0416','no',N'Langedijk',N'LANGEDIJK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL327','GM0417','no',N'Laren',N'LAREN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL321','GM0420','no',N'Medemblik',N'MEDEMBLIK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL326','GM0431','no',N'Oostzaan',N'OOSTZAAN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL321','GM0432','no',N'Opmeer',N'OPMEER');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL326','GM0437','no',N'Ouder-Amstel',N'OUDER-AMSTEL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL326','GM0439','no',N'Purmerend',N'PURMEREND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL321','GM0441','no',N'Schagen',N'SCHAGEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL321','GM0448','no',N'Texel',N'TEXEL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL323','GM0450','no',N'Uitgeest',N'UITGEEST');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL326','GM0451','no',N'Uithoorn',N'UITHOORN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL323','GM0453','no',N'Velsen',N'VELSEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL327','GM0457','no',N'Weesp',N'WEESP');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL324','GM0473','no',N'Zandvoort',N'ZANDVOORT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL325','GM0479','no',N'Zaanstad',N'ZAANSTAD');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL33A','GM0482','no',N'Alblasserdam',N'ALBLASSERDAM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL338','GM0484','no',N'Alphen aan den Rijn',N'ALPHEN AAN DEN RIJN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL339','GM0489','no',N'Barendrecht',N'BARENDRECHT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL321','GM0498','no',N'Drechterland',N'DRECHTERLAND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL339','GM0501','no',N'Brielle',N'BRIELLE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL339','GM0502','no',N'Capelle aan den IJssel',N'CAPELLE AAN DEN IJSSEL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL333','GM0503','no',N'Delft',N'DELFT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL33A','GM0505','no',N'Dordrecht',N'DORDRECHT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL33A','GM0512','no',N'Gorinchem',N'GORINCHEM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL338','GM0513','no',N'Gouda',N'GOUDA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL332','GM0518','no',N'''s-Gravenhage',N'''S-GRAVENHAGE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL33A','GM0523','no',N'Hardinxveld-Giessendam',N'HARDINXVELD-GIESSENDAM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL339','GM0530','no',N'Hellevoetsluis',N'HELLEVOETSLUIS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL33A','GM0531','no',N'Hendrik-Ido-Ambacht',N'HENDRIK-IDO-AMBACHT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL321','GM0532','no',N'Stede Broec',N'STEDE BROEC');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL337','GM0534','no',N'Hillegom',N'HILLEGOM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL337','GM0537','no',N'Katwijk',N'KATWIJK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL339','GM0542','no',N'Krimpen aan den IJssel',N'KRIMPEN AAN DEN IJSSEL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL33A','GM0545','no',N'Leerdam',N'LEERDAM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL337','GM0546','no',N'Leiden',N'LEIDEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL337','GM0547','no',N'Leiderdorp',N'LEIDERDORP');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL337','GM0553','no',N'Lisse',N'LISSE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL339','GM0556','no',N'Maassluis',N'MAASSLUIS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL338','GM0569','no',N'Nieuwkoop',N'NIEUWKOOP');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL337','GM0575','no',N'Noordwijk',N'NOORDWIJK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL337','GM0576','no',N'Noordwijkerhout',N'NOORDWIJKERHOUT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL337','GM0579','no',N'Oegstgeest',N'OEGSTGEEST');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL339','GM0584','no',N'Oud-Beijerland',N'OUD-BEIJERLAND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL339','GM0585','no',N'Binnenmaas',N'BINNENMAAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL339','GM0588','no',N'Korendijk',N'KORENDIJK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0589','no',N'Oudewater',N'OUDEWATER');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL33A','GM0590','no',N'Papendrecht',N'PAPENDRECHT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL339','GM0597','no',N'Ridderkerk',N'RIDDERKERK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL339','GM0599','no',N'Rotterdam',N'ROTTERDAM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL332','GM0603','no',N'Rijswijk',N'RIJSWIJK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL339','GM0606','no',N'Schiedam',N'SCHIEDAM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL33A','GM0610','no',N'Sliedrecht',N'SLIEDRECHT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL339','GM0611','no',N'Cromstrijen',N'CROMSTRIJEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL339','GM0613','no',N'Albrandswaard',N'ALBRANDSWAARD');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL339','GM0614','no',N'Westvoorne',N'WESTVOORNE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL339','GM0617','no',N'Strijen',N'STRIJEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0620','no',N'Vianen',N'VIANEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL339','GM0622','no',N'Vlaardingen',N'VLAARDINGEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL337','GM0626','no',N'Voorschoten',N'VOORSCHOTEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL338','GM0627','no',N'Waddinxveen',N'WADDINXVEEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL332','GM0629','no',N'Wassenaar',N'WASSENAAR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0632','no',N'Woerden',N'WOERDEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL332','GM0637','no',N'Zoetermeer',N'ZOETERMEER');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL337','GM0638','no',N'Zoeterwoude',N'ZOETERWOUDE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL33A','GM0642','no',N'Zwijndrecht',N'ZWIJNDRECHT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL342','GM0654','no',N'Borsele',N'BORSELE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL342','GM0664','no',N'Goes',N'GOES');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL224','GM0668','no',N'West Maas en Waal',N'WEST MAAS EN WAAL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL341','GM0677','no',N'Hulst',N'HULST');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL342','GM0678','no',N'Kapelle',N'KAPELLE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL342','GM0687','no',N'Middelburg',N'MIDDELBURG');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL33A','GM0689','no',N'Giessenlanden',N'GIESSENLANDEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL342','GM0703','no',N'Reimerswaal',N'REIMERSWAAL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL33A','GM0707','no',N'Zederik',N'ZEDERIK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL341','GM0715','no',N'Terneuzen',N'TERNEUZEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL342','GM0716','no',N'Tholen',N'THOLEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL342','GM0717','no',N'Veere',N'VEERE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL342','GM0718','no',N'Vlissingen',N'VLISSINGEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL224','GM0733','no',N'Lingewaal',N'LINGEWAAL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM0736','no',N'De Ronde Venen',N'DE RONDE VENEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL121','GM0737','no',N'Tytsjerksteradiel',N'TYTSJERKSTERADIEL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL412','GM0738','no',N'Aalburg',N'AALBURG');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL414','GM0743','no',N'Asten',N'ASTEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL412','GM0744','no',N'Baarle-Nassau',N'BAARLE-NASSAU');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL411','GM0748','no',N'Bergen op Zoom',N'BERGEN OP ZOOM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL414','GM0753','no',N'Best',N'BEST');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL413','GM0755','no',N'Boekel',N'BOEKEL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL413','GM0756','no',N'Boxmeer',N'BOXMEER');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL413','GM0757','no',N'Boxtel',N'BOXTEL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL411','GM0758','no',N'Breda',N'BREDA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL414','GM0762','no',N'Deurne',N'DEURNE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL111','GM0765','no',N'Pekela',N'PEKELA');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL412','GM0766','no',N'Dongen',N'DONGEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL414','GM0770','no',N'Eersel',N'EERSEL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL414','GM0772','no',N'Eindhoven',N'EINDHOVEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL411','GM0777','no',N'Etten-Leur',N'ETTEN-LEUR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL411','GM0779','no',N'Geertruidenberg',N'GEERTRUIDENBERG');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL412','GM0784','no',N'Gilze en Rijen',N'GILZE EN RIJEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL412','GM0785','no',N'Goirle',N'GOIRLE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL413','GM0786','no',N'Grave',N'GRAVE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL413','GM0788','no',N'Haaren',N'HAAREN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL414','GM0794','no',N'Helmond',N'HELMOND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL413','GM0796','no',N'''s-Hertogenbosch',N'''S-HERTOGENBOSCH');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL413','GM0797','no',N'Heusden',N'HEUSDEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL412','GM0798','no',N'Hilvarenbeek',N'HILVARENBEEK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL412','GM0809','no',N'Loon op Zand',N'LOON OP ZAND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL413','GM0815','no',N'Mill en Sint Hubert',N'MILL EN SINT HUBERT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL414','GM0820','no',N'Nuenen, Gerwen en Nederwetten',N'NUENEN, GERWEN EN NEDERWETTEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL414','GM0823','no',N'Oirschot',N'OIRSCHOT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL412','GM0824','no',N'Oisterwijk',N'OISTERWIJK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL411','GM0826','no',N'Oosterhout',N'OOSTERHOUT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL413','GM0828','no',N'Oss',N'OSS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL411','GM0840','no',N'Rucphen',N'RUCPHEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL413','GM0845','no',N'Sint-Michielsgestel',N'SINT-MICHIELSGESTEL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL414','GM0847','no',N'Someren',N'SOMEREN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL414','GM0848','no',N'Son en Breugel',N'SON EN BREUGEL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL411','GM0851','no',N'Steenbergen',N'STEENBERGEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL326','GM0852','no',N'Waterland',N'WATERLAND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL412','GM0855','no',N'Tilburg',N'TILBURG');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL413','GM0856','no',N'Uden',N'UDEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL414','GM0858','no',N'Valkenswaard',N'VALKENSWAARD');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL414','GM0861','no',N'Veldhoven',N'VELDHOVEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL413','GM0865','no',N'Vught',N'VUGHT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL414','GM0866','no',N'Waalre',N'WAALRE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL412','GM0867','no',N'Waalwijk',N'WAALWIJK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL412','GM0870','no',N'Werkendam',N'WERKENDAM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL411','GM0873','no',N'Woensdrecht',N'WOENSDRECHT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL412','GM0874','no',N'Woudrichem',N'WOUDRICHEM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL411','GM0879','no',N'Zundert',N'ZUNDERT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL325','GM0880','no',N'Wormerland',N'WORMERLAND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL423','GM0881','no',N'Onderbanken',N'ONDERBANKEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL423','GM0882','no',N'Landgraaf',N'LANDGRAAF');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL423','GM0888','no',N'Beek',N'BEEK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL421','GM0889','no',N'Beesel',N'BEESEL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL421','GM0893','no',N'Bergen (L.)',N'BERGEN (L.)');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL423','GM0899','no',N'Brunssum',N'BRUNSSUM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL421','GM0907','no',N'Gennep',N'GENNEP');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL423','GM0917','no',N'Heerlen',N'HEERLEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL423','GM0928','no',N'Kerkrade',N'KERKRADE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL423','GM0935','no',N'Maastricht',N'MAASTRICHT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL423','GM0938','no',N'Meerssen',N'MEERSSEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL421','GM0944','no',N'Mook en Middelaar',N'MOOK EN MIDDELAAR');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL422','GM0946','no',N'Nederweert',N'NEDERWEERT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL423','GM0951','no',N'Nuth',N'NUTH');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL422','GM0957','no',N'Roermond',N'ROERMOND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL423','GM0962','no',N'Schinnen',N'SCHINNEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL423','GM0965','no',N'Simpelveld',N'SIMPELVELD');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL423','GM0971','no',N'Stein',N'STEIN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL423','GM0981','no',N'Vaals',N'VAALS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL421','GM0983','no',N'Venlo',N'VENLO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL421','GM0984','no',N'Venray',N'VENRAY');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL423','GM0986','no',N'Voerendaal',N'VOERENDAAL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL422','GM0988','no',N'Weert',N'WEERT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL423','GM0994','no',N'Valkenburg aan de Geul',N'VALKENBURG AAN DE GEUL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL230','GM0995','no',N'Lelystad',N'LELYSTAD');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL421','GM1507','no',N'Horst aan de Maas',N'HORST AAN DE MAAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL225','GM1509','no',N'Oude IJsselstreek',N'OUDE IJSSELSTREEK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL337','GM1525','no',N'Teylingen',N'TEYLINGEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM1581','no',N'Utrechtse Heuvelrug',N'UTRECHTSE HEUVELRUG');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL225','GM1586','no',N'Oost Gelre',N'OOST GELRE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL321','GM1598','no',N'Koggenland',N'KOGGENLAND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL339','GM1621','no',N'Lansingerland',N'LANSINGERLAND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL422','GM1640','no',N'Leudal',N'LEUDAL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL422','GM1641','no',N'Maasgouw',N'MAASGOUW');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL113','GM1651','no',N'Eemsmond',N'EEMSMOND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL414','GM1652','no',N'Gemert-Bakel',N'GEMERT-BAKEL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL411','GM1655','no',N'Halderberge',N'HALDERBERGE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL414','GM1658','no',N'Heeze-Leende',N'HEEZE-LEENDE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL414','GM1659','no',N'Laarbeek',N'LAARBEEK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL113','GM1663','no',N'De Marne',N'DE MARNE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL414','GM1667','no',N'Reusel-De Mierden',N'REUSEL-DE MIERDEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL422','GM1669','no',N'Roerdalen',N'ROERDALEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL411','GM1674','no',N'Roosendaal',N'ROOSENDAAL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL342','GM1676','no',N'Schouwen-Duiveland',N'SCHOUWEN-DUIVELAND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL131','GM1680','no',N'Aa en Hunze',N'AA EN HUNZE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL132','GM1681','no',N'Borger-Odoorn',N'BORGER-ODOORN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL413','GM1684','no',N'Cuijk',N'CUIJK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL413','GM1685','no',N'Landerd',N'LANDERD');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL133','GM1690','no',N'De Wolden',N'DE WOLDEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL342','GM1695','no',N'Noord-Beveland',N'NOORD-BEVELAND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL327','GM1696','no',N'Wijdemeren',N'WIJDEMEREN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL131','GM1699','no',N'Noordenveld',N'NOORDENVELD');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL213','GM1700','no',N'Twenterand',N'TWENTERAND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL133','GM1701','no',N'Westerveld',N'WESTERVELD');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL413','GM1702','no',N'Sint Anthonis',N'SINT ANTHONIS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL226','GM1705','no',N'Lingewaard',N'LINGEWAARD');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL414','GM1706','no',N'Cranendonck',N'CRANENDONCK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL211','GM1708','no',N'Steenwijkerland',N'STEENWIJKERLAND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL411','GM1709','no',N'Moerdijk',N'MOERDIJK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL422','GM1711','no',N'Echt-Susteren',N'ECHT-SUSTEREN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL341','GM1714','no',N'Sluis',N'SLUIS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL411','GM1719','no',N'Drimmelen',N'DRIMMELEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL413','GM1721','no',N'Bernheze',N'BERNHEZE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL121','GM1722','no',N'Ferwerderadiel',N'FERWERDERADIEL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL412','GM1723','no',N'Alphen-Chaam',N'ALPHEN-CHAAM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL414','GM1724','no',N'Bergeijk',N'BERGEIJK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL414','GM1728','no',N'Bladel',N'BLADEL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL423','GM1729','no',N'Gulpen-Wittem',N'GULPEN-WITTEM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL131','GM1730','no',N'Tynaarlo',N'TYNAARLO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL131','GM1731','no',N'Midden-Drenthe',N'MIDDEN-DRENTHE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL226','GM1734','no',N'Overbetuwe',N'OVERBETUWE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL213','GM1735','no',N'Hof van Twente',N'HOF VAN TWENTE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL224','GM1740','no',N'Neder-Betuwe',N'NEDER-BETUWE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL213','GM1742','no',N'Rijssen-Holten',N'RIJSSEN-HOLTEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL414','GM1771','no',N'Geldrop-Mierlo',N'GELDROP-MIERLO');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL212','GM1773','no',N'Olst-Wijhe',N'OLST-WIJHE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL213','GM1774','no',N'Dinkelland',N'DINKELLAND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL333','GM1783','no',N'Westland',N'WESTLAND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL333','GM1842','no',N'Midden-Delfland',N'MIDDEN-DELFLAND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL225','GM1859','no',N'Berkelland',N'BERKELLAND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL225','GM1876','no',N'Bronckhorst',N'BRONCKHORST');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL423','GM1883','no',N'Sittard-Geleen',N'SITTARD-GELEEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL337','GM1884','no',N'Kaag en Braassem',N'KAAG EN BRAASSEM');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL121','GM1891','no',N'Dantumadiel',N'DANTUMADIEL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL339','GM1892','no',N'Zuidplas',N'ZUIDPLAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL421','GM1894','no',N'Peel en Maas',N'PEEL EN MAAS');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL111','GM1895','no',N'Oldambt',N'OLDAMBT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL211','GM1896','no',N'Zwartewaterland',N'ZWARTEWATERLAND');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL122','GM1900','no',N'Súdwest-Fryslân',N'SÚDWEST-FRYSLÂN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL338','GM1901','no',N'Bodegraven-Reeuwijk',N'BODEGRAVEN-REEUWIJK');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL423','GM1903','no',N'Eijsden-Margraten',N'EIJSDEN-MARGRATEN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL310','GM1904','no',N'Stichtse Vecht',N'STICHTSE VECHT');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL321','GM1911','no',N'Hollands Kroon',N'HOLLANDS KROON');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL332','GM1916','no',N'Leidschendam-Voorburg',N'LEIDSCHENDAM-VOORBURG');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL339','GM1924','no',N'Goeree-Overflakkee',N'GOEREE-OVERFLAKKEE');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL332','GM1926','no',N'Pijnacker-Nootdorp',N'PIJNACKER-NOOTDORP');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL33A','GM1927','no',N'Molenwaard',N'MOLENWAARD');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL339','GM1930','no',N'Nissewaard',N'NISSEWAARD');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL339','GM1931','no',N'Krimpenerwaard',N'KRIMPENERWAARD');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL123','GM1940','no',N'De Fryske Marren',N'DE FRYSKE MARREN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL327','GM1942','no',N'Gooise Meren',N'GOOISE MEREN');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL226','GM1945','no',N'Berg en Dal',N'BERG EN DAL');
INSERT INTO laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('NL','NL225','GM1955','no',N'Montferland',N'MONTFERLAND');
