INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16D','101','no',N'ÁGUEDA',N'ÁGUEDA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16D','102','no',N'ALBERGARIA-A-VELHA',N'ALBERGARIA-A-VELHA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16D','103','no',N'ANADIA',N'ANADIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11A','104','no',N'AROUCA',N'AROUCA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16D','105','no',N'AVEIRO',N'AVEIRO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11C','106','no',N'CASTELO DE PAIVA',N'CASTELO DE PAIVA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11A','107','no',N'ESPINHO',N'ESPINHO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16D','108','no',N'ESTARREJA',N'ESTARREJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11A','109','no',N'SANTA MARIA DA FEIRA',N'SANTA MARIA DA FEIRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16D','110','no',N'ÍLHAVO',N'ÍLHAVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16E','111','no',N'MEALHADA',N'MEALHADA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16D','112','no',N'MURTOSA',N'MURTOSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11A','113','no',N'OLIVEIRA DE AZEMÉIS',N'OLIVEIRA DE AZEMÉIS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16D','114','no',N'OLIVEIRA DO BAIRRO',N'OLIVEIRA DO BAIRRO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16D','115','no',N'OVAR',N'OVAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11A','116','no',N'SÃO JOÃO DA MADEIRA',N'SÃO JOÃO DA MADEIRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16D','117','no',N'SEVER DO VOUGA',N'SEVER DO VOUGA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16D','118','no',N'VAGOS',N'VAGOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11A','119','no',N'VALE DE CAMBRA',N'VALE DE CAMBRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT184','201','no',N'ALJUSTREL',N'ALJUSTREL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT184','202','no',N'ALMODÔVAR',N'ALMODÔVAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT184','203','no',N'ALVITO',N'ALVITO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT184','204','no',N'BARRANCOS',N'BARRANCOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT184','205','no',N'BEJA',N'BEJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT184','206','no',N'CASTRO VERDE',N'CASTRO VERDE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT184','207','no',N'CUBA',N'CUBA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT184','208','no',N'FERREIRA DO ALENTEJO',N'FERREIRA DO ALENTEJO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT184','209','no',N'MÉRTOLA',N'MÉRTOLA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT184','210','no',N'MOURA',N'MOURA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT181','211','no',N'ODEMIRA',N'ODEMIRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT184','212','no',N'OURIQUE',N'OURIQUE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT184','213','no',N'SERPA',N'SERPA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT184','214','no',N'VIDIGUEIRA',N'VIDIGUEIRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT112','301','no',N'AMARES',N'AMARES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT112','302','no',N'BARCELOS',N'BARCELOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT112','303','no',N'BRAGA',N'BRAGA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT119','304','no',N'CABECEIRAS DE BASTO',N'CABECEIRAS DE BASTO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11C','305','no',N'CELORICO DE BASTO',N'CELORICO DE BASTO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT112','306','no',N'ESPOSENDE',N'ESPOSENDE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT119','307','no',N'FAFE',N'FAFE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT119','308','no',N'GUIMARÃES',N'GUIMARÃES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT119','309','no',N'PÓVOA DE LANHOSO',N'PÓVOA DE LANHOSO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT112','310','no',N'TERRAS DE BOURO',N'TERRAS DE BOURO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT119','311','no',N'VIEIRA DO MINHO',N'VIEIRA DO MINHO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT119','312','no',N'VILA NOVA DE FAMALICÃO',N'VILA NOVA DE FAMALICÃO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT112','313','no',N'VILA VERDE',N'VILA VERDE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT119','314','no',N'VIZELA',N'VIZELA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11E','401','no',N'ALFÂNDEGA DA FÉ',N'ALFÂNDEGA DA FÉ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11E','402','no',N'BRAGANÇA',N'BRAGANÇA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11D','403','no',N'CARRAZEDA DE ANSIÃES',N'CARRAZEDA DE ANSIÃES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11D','404','no',N'FREIXO DE ESPADA À CINTA',N'FREIXO DE ESPADA À CINTA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11E','405','no',N'MACEDO DE CAVALEIROS',N'MACEDO DE CAVALEIROS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11E','406','no',N'MIRANDA DO DOURO',N'MIRANDA DO DOURO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11E','407','no',N'MIRANDELA',N'MIRANDELA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11E','408','no',N'MOGADOURO',N'MOGADOURO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11D','409','no',N'TORRE DE MONCORVO',N'TORRE DE MONCORVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11E','410','no',N'VILA FLOR',N'VILA FLOR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11E','411','no',N'VIMIOSO',N'VIMIOSO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11E','412','no',N'VINHAIS',N'VINHAIS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16H','501','no',N'BELMONTE',N'BELMONTE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16H','502','no',N'CASTELO BRANCO',N'CASTELO BRANCO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16H','503','no',N'COVILHÃ',N'COVILHÃ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16H','504','no',N'FUNDÃO',N'FUNDÃO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16H','505','no',N'IDANHA-A-NOVA',N'IDANHA-A-NOVA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16H','506','no',N'OLEIROS',N'OLEIROS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16H','507','no',N'PENAMACOR',N'PENAMACOR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16H','508','no',N'PROENÇA-A-NOVA',N'PROENÇA-A-NOVA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16H','509','no',N'SERTÃ',N'SERTÃ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16H','510','no',N'VILA DE REI',N'VILA DE REI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16H','511','no',N'VILA VELHA DE RÓDÃO',N'VILA VELHA DE RÓDÃO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16E','601','no',N'ARGANIL',N'ARGANIL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16E','602','no',N'CANTANHEDE',N'CANTANHEDE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16E','603','no',N'COIMBRA',N'COIMBRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16E','604','no',N'CONDEIXA-A-NOVA',N'CONDEIXA-A-NOVA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16E','605','no',N'FIGUEIRA DA FOZ',N'FIGUEIRA DA FOZ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16E','606','no',N'GÓIS',N'GÓIS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16E','607','no',N'LOUSÃ',N'LOUSÃ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16E','608','no',N'MIRA',N'MIRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16E','609','no',N'MIRANDA DO CORVO',N'MIRANDA DO CORVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16E','610','no',N'MONTEMOR-O-VELHO',N'MONTEMOR-O-VELHO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16E','611','no',N'OLIVEIRA DO HOSPITAL',N'OLIVEIRA DO HOSPITAL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16E','612','no',N'PAMPILHOSA DA SERRA',N'PAMPILHOSA DA SERRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16E','613','no',N'PENACOVA',N'PENACOVA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16E','614','no',N'PENELA',N'PENELA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16E','615','no',N'SOURE',N'SOURE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16E','616','no',N'TÁBUA',N'TÁBUA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16E','617','no',N'VILA NOVA DE POIARES',N'VILA NOVA DE POIARES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT187','701','no',N'ALANDROAL',N'ALANDROAL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT187','702','no',N'ARRAIOLOS',N'ARRAIOLOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT187','703','no',N'BORBA',N'BORBA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT187','704','no',N'ESTREMOZ',N'ESTREMOZ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT187','705','no',N'ÉVORA',N'ÉVORA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT187','706','no',N'MONTEMOR-O-NOVO',N'MONTEMOR-O-NOVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT187','707','no',N'MORA',N'MORA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT187','708','no',N'MOURÃO',N'MOURÃO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT187','709','no',N'PORTEL',N'PORTEL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT187','710','no',N'REDONDO',N'REDONDO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT187','711','no',N'REGUENGOS DE MONSARAZ',N'REGUENGOS DE MONSARAZ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT187','712','no',N'VENDAS NOVAS',N'VENDAS NOVAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT187','713','no',N'VIANA DO ALENTEJO',N'VIANA DO ALENTEJO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT187','714','no',N'VILA VIÇOSA',N'VILA VIÇOSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT150','801','no',N'ALBUFEIRA',N'ALBUFEIRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT150','802','no',N'ALCOUTIM',N'ALCOUTIM');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT150','803','no',N'ALJEZUR',N'ALJEZUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT150','804','no',N'CASTRO MARIM',N'CASTRO MARIM');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT150','805','no',N'FARO',N'FARO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT150','806','no',N'LAGOA (ALGARVE)',N'LAGOA (ALGARVE)');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT150','807','no',N'LAGOS',N'LAGOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT150','808','no',N'LOULÉ',N'LOULÉ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT150','809','no',N'MONCHIQUE',N'MONCHIQUE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT150','810','no',N'OLHÃO',N'OLHÃO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT150','811','no',N'PORTIMÃO',N'PORTIMÃO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT150','812','no',N'SÃO BRÁS DE ALPORTEL',N'SÃO BRÁS DE ALPORTEL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT150','813','no',N'SILVES',N'SILVES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT150','814','no',N'TAVIRA',N'TAVIRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT150','815','no',N'VILA DO BISPO',N'VILA DO BISPO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT150','816','no',N'VILA REAL DE SANTO ANTÓNIO',N'VILA REAL DE SANTO ANTÓNIO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16G','901','no',N'AGUIAR DA BEIRA',N'AGUIAR DA BEIRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16J','902','no',N'ALMEIDA',N'ALMEIDA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16J','903','no',N'CELORICO DA BEIRA',N'CELORICO DA BEIRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16J','904','no',N'FIGUEIRA DE CASTELO RODRIGO',N'FIGUEIRA DE CASTELO RODRIGO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16J','905','no',N'FORNOS DE ALGODRES',N'FORNOS DE ALGODRES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16J','906','no',N'GOUVEIA',N'GOUVEIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16J','907','no',N'GUARDA',N'GUARDA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16J','908','no',N'MANTEIGAS',N'MANTEIGAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16J','909','no',N'MÊDA',N'MÊDA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16J','910','no',N'PINHEL',N'PINHEL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16J','911','no',N'SABUGAL',N'SABUGAL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16J','912','no',N'SEIA',N'SEIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16J','913','no',N'TRANCOSO',N'TRANCOSO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11D','914','no',N'VILA NOVA DE FOZ CÔA',N'VILA NOVA DE FOZ CÔA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16B','1001','no',N'ALCOBAÇA',N'ALCOBAÇA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16F','1002','no',N'ALVAIÁZERE',N'ALVAIÁZERE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16F','1003','no',N'ANSIÃO',N'ANSIÃO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16F','1004','no',N'BATALHA',N'BATALHA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16B','1005','no',N'BOMBARRAL',N'BOMBARRAL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16B','1006','no',N'CALDAS DA RAINHA',N'CALDAS DA RAINHA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16F','1007','no',N'CASTANHEIRA DE PÊRA',N'CASTANHEIRA DE PÊRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16F','1008','no',N'FIGUEIRÓ DOS VINHOS',N'FIGUEIRÓ DOS VINHOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16F','1009','no',N'LEIRIA',N'LEIRIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16F','1010','no',N'MARINHA GRANDE',N'MARINHA GRANDE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16B','1011','no',N'NAZARÉ',N'NAZARÉ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16B','1012','no',N'ÓBIDOS',N'ÓBIDOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16F','1013','no',N'PEDRÓGÃO GRANDE',N'PEDRÓGÃO GRANDE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16B','1014','no',N'PENICHE',N'PENICHE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16F','1015','no',N'POMBAL',N'POMBAL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16F','1016','no',N'PORTO DE MÓS',N'PORTO DE MÓS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16B','1101','no',N'ALENQUER',N'ALENQUER');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16B','1102','no',N'ARRUDA DOS VINHOS',N'ARRUDA DOS VINHOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT185','1103','no',N'AZAMBUJA',N'AZAMBUJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16B','1104','no',N'CADAVAL',N'CADAVAL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT170','1105','no',N'CASCAIS',N'CASCAIS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT170','1106','no',N'LISBOA',N'LISBOA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT170','1107','no',N'LOURES',N'LOURES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16B','1108','no',N'LOURINHÃ',N'LOURINHÃ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT170','1109','no',N'MAFRA',N'MAFRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT170','1110','no',N'OEIRAS',N'OEIRAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT170','1111','no',N'SINTRA',N'SINTRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16B','1112','no',N'SOBRAL DE MONTE AGRAÇO',N'SOBRAL DE MONTE AGRAÇO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16B','1113','no',N'TORRES VEDRAS',N'TORRES VEDRAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT170','1114','no',N'VILA FRANCA DE XIRA',N'VILA FRANCA DE XIRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT170','1115','no',N'AMADORA',N'AMADORA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT170','1116','no',N'ODIVELAS',N'ODIVELAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT186','1201','no',N'ALTER DO CHÃO',N'ALTER DO CHÃO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT186','1202','no',N'ARRONCHES',N'ARRONCHES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT186','1203','no',N'AVIS',N'AVIS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT186','1204','no',N'CAMPO MAIOR',N'CAMPO MAIOR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT186','1205','no',N'CASTELO DE VIDE',N'CASTELO DE VIDE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT186','1206','no',N'CRATO',N'CRATO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT186','1207','no',N'ELVAS',N'ELVAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT186','1208','no',N'FRONTEIRA',N'FRONTEIRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT186','1209','no',N'GAVIÃO',N'GAVIÃO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT186','1210','no',N'MARVÃO',N'MARVÃO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT186','1211','no',N'MONFORTE',N'MONFORTE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT186','1212','no',N'NISA',N'NISA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT186','1213','no',N'PONTE DE SOR',N'PONTE DE SOR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT186','1214','no',N'PORTALEGRE',N'PORTALEGRE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT186','1215','no',N'SOUSEL',N'SOUSEL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11C','1301','no',N'AMARANTE',N'AMARANTE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11C','1302','no',N'BAIÃO',N'BAIÃO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11C','1303','no',N'FELGUEIRAS',N'FELGUEIRAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11A','1304','no',N'GONDOMAR',N'GONDOMAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11C','1305','no',N'LOUSADA',N'LOUSADA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11A','1306','no',N'MAIA',N'MAIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11C','1307','no',N'MARCO DE CANAVESES',N'MARCO DE CANAVESES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11A','1308','no',N'MATOSINHOS',N'MATOSINHOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11C','1309','no',N'PAÇOS DE FERREIRA',N'PAÇOS DE FERREIRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11A','1310','no',N'PAREDES',N'PAREDES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11C','1311','no',N'PENAFIEL',N'PENAFIEL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11A','1312','no',N'PORTO',N'PORTO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11A','1313','no',N'PÓVOA DE VARZIM',N'PÓVOA DE VARZIM');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11A','1314','no',N'SANTO TIRSO',N'SANTO TIRSO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11A','1315','no',N'VALONGO',N'VALONGO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11A','1316','no',N'VILA DO CONDE',N'VILA DO CONDE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11A','1317','no',N'VILA NOVA DE GAIA',N'VILA NOVA DE GAIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11A','1318','no',N'TROFA',N'TROFA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16I','1401','no',N'ABRANTES',N'ABRANTES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16I','1402','no',N'ALCANENA',N'ALCANENA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT185','1403','no',N'ALMEIRIM',N'ALMEIRIM');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT185','1404','no',N'ALPIARÇA',N'ALPIARÇA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT185','1405','no',N'BENAVENTE',N'BENAVENTE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT185','1406','no',N'CARTAXO',N'CARTAXO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT185','1407','no',N'CHAMUSCA',N'CHAMUSCA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16I','1408','no',N'CONSTÂNCIA',N'CONSTÂNCIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT185','1409','no',N'CORUCHE',N'CORUCHE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16I','1410','no',N'ENTRONCAMENTO',N'ENTRONCAMENTO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16I','1411','no',N'FERREIRA DO ZÊZERE',N'FERREIRA DO ZÊZERE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT185','1412','no',N'GOLEGÃ',N'GOLEGÃ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16H','1413','no',N'MAÇÃO',N'MAÇÃO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT185','1414','no',N'RIO MAIOR',N'RIO MAIOR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT185','1415','no',N'SALVATERRA DE MAGOS',N'SALVATERRA DE MAGOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT185','1416','no',N'SANTARÉM',N'SANTARÉM');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16I','1417','no',N'SARDOAL',N'SARDOAL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16I','1418','no',N'TOMAR',N'TOMAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16I','1419','no',N'TORRES NOVAS',N'TORRES NOVAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16I','1420','no',N'VILA NOVA DA BARQUINHA',N'VILA NOVA DA BARQUINHA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16I','1421','no',N'OURÉM',N'OURÉM');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT181','1501','no',N'ALCÁCER DO SAL',N'ALCÁCER DO SAL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT170','1502','no',N'ALCOCHETE',N'ALCOCHETE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT170','1503','no',N'ALMADA',N'ALMADA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT170','1504','no',N'BARREIRO',N'BARREIRO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT181','1505','no',N'GRÂNDOLA',N'GRÂNDOLA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT170','1506','no',N'MOITA',N'MOITA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT170','1507','no',N'MONTIJO',N'MONTIJO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT170','1508','no',N'PALMELA',N'PALMELA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT181','1509','no',N'SANTIAGO DO CACÉM',N'SANTIAGO DO CACÉM');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT170','1510','no',N'SEIXAL',N'SEIXAL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT170','1511','no',N'SESIMBRA',N'SESIMBRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT170','1512','no',N'SETÚBAL',N'SETÚBAL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT181','1513','no',N'SINES',N'SINES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT111','1601','no',N'ARCOS DE VALDEVEZ',N'ARCOS DE VALDEVEZ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT111','1602','no',N'CAMINHA',N'CAMINHA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT111','1603','no',N'MELGAÇO',N'MELGAÇO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT111','1604','no',N'MONÇÃO',N'MONÇÃO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT111','1605','no',N'PAREDES DE COURA',N'PAREDES DE COURA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT111','1606','no',N'PONTE DA BARCA',N'PONTE DA BARCA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT111','1607','no',N'PONTE DE LIMA',N'PONTE DE LIMA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT111','1608','no',N'VALENÇA',N'VALENÇA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT111','1609','no',N'VIANA DO CASTELO',N'VIANA DO CASTELO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT111','1610','no',N'VILA NOVA DE CERVEIRA',N'VILA NOVA DE CERVEIRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11D','1701','no',N'ALIJÓ',N'ALIJÓ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11B','1702','no',N'BOTICAS',N'BOTICAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11B','1703','no',N'CHAVES',N'CHAVES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11D','1704','no',N'MESÃO FRIO',N'MESÃO FRIO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT119','1705','no',N'MONDIM DE BASTO',N'MONDIM DE BASTO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11B','1706','no',N'MONTALEGRE',N'MONTALEGRE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11D','1707','no',N'MURÇA',N'MURÇA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11D','1708','no',N'PESO DA RÉGUA',N'PESO DA RÉGUA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11B','1709','no',N'RIBEIRA DE PENA',N'RIBEIRA DE PENA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11D','1710','no',N'SABROSA',N'SABROSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11D','1711','no',N'SANTA MARTA DE PENAGUIÃO',N'SANTA MARTA DE PENAGUIÃO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11B','1712','no',N'VALPAÇOS',N'VALPAÇOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11B','1713','no',N'VILA POUCA DE AGUIAR',N'VILA POUCA DE AGUIAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11D','1714','no',N'VILA REAL',N'VILA REAL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11D','1801','no',N'ARMAMAR',N'ARMAMAR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16G','1802','no',N'CARREGAL DO SAL',N'CARREGAL DO SAL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16G','1803','no',N'CASTRO DAIRE',N'CASTRO DAIRE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11C','1804','no',N'CINFÃES',N'CINFÃES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11D','1805','no',N'LAMEGO',N'LAMEGO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16G','1806','no',N'MANGUALDE',N'MANGUALDE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11D','1807','no',N'MOIMENTA DA BEIRA',N'MOIMENTA DA BEIRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16G','1808','no',N'MORTÁGUA',N'MORTÁGUA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16G','1809','no',N'NELAS',N'NELAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16G','1810','no',N'OLIVEIRA DE FRADES',N'OLIVEIRA DE FRADES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16G','1811','no',N'PENALVA DO CASTELO',N'PENALVA DO CASTELO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11D','1812','no',N'PENEDONO',N'PENEDONO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11C','1813','no',N'RESENDE',N'RESENDE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16G','1814','no',N'SANTA COMBA DÃO',N'SANTA COMBA DÃO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16G','1815','no',N'SÃO JOÃO DA PESQUEIRA',N'SÃO JOÃO DA PESQUEIRA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16G','1816','no',N'SÃO PEDRO DO SUL',N'SÃO PEDRO DO SUL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16G','1817','no',N'SÁTÃO',N'SÁTÃO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11D','1818','no',N'SERNANCELHE',N'SERNANCELHE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11D','1819','no',N'TABUAÇO',N'TABUAÇO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT11D','1820','no',N'TAROUCA',N'TAROUCA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16G','1821','no',N'TONDELA',N'TONDELA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16G','1822','no',N'VILA NOVA DE PAIVA',N'VILA NOVA DE PAIVA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16G','1823','no',N'VISEU',N'VISEU');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT16G','1824','no',N'VOUZELA',N'VOUZELA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT300','3101','no',N'CALHETA (MADEIRA)',N'CALHETA (MADEIRA)');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT300','3102','no',N'CÂMARA DE LOBOS',N'CÂMARA DE LOBOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT300','3103','no',N'FUNCHAL',N'FUNCHAL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT300','3104','no',N'MACHICO',N'MACHICO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT300','3105','no',N'PONTA DO SOL',N'PONTA DO SOL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT300','3106','no',N'PORTO MONIZ',N'PORTO MONIZ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT300','3107','no',N'RIBEIRA BRAVA',N'RIBEIRA BRAVA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT300','3108','no',N'SANTA CRUZ',N'SANTA CRUZ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT300','3109','no',N'SANTANA',N'SANTANA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT300','3110','no',N'SÃO VICENTE',N'SÃO VICENTE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT300','3201','no',N'PORTO SANTO',N'PORTO SANTO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT200','4101','no',N'VILA DO PORTO',N'VILA DO PORTO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT200','4201','no',N'LAGOA (SÃO MIGUEL)',N'LAGOA (SÃO MIGUEL)');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT200','4202','no',N'NORDESTE',N'NORDESTE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT200','4203','no',N'PONTA DELGADA',N'PONTA DELGADA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT200','4204','no',N'POVOAÇÃO',N'POVOAÇÃO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT200','4205','no',N'RIBEIRA GRANDE',N'RIBEIRA GRANDE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT200','4206','no',N'VILA FRANCA DO CAMPO',N'VILA FRANCA DO CAMPO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT200','4301','no',N'ANGRA DO HEROÍSMO',N'ANGRA DO HEROÍSMO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT200','4302','no',N'PRAIA DA VITÓRIA',N'PRAIA DA VITÓRIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT200','4401','no',N'SANTA CRUZ DA GRACIOSA',N'SANTA CRUZ DA GRACIOSA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT200','4501','no',N'CALHETA (SÃO JORGE)',N'CALHETA (SÃO JORGE)');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT200','4502','no',N'VELAS',N'VELAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT200','4601','no',N'LAJES DO PICO',N'LAJES DO PICO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT200','4602','no',N'MADALENA',N'MADALENA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT200','4603','no',N'SÃO ROQUE DO PICO',N'SÃO ROQUE DO PICO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT200','4701','no',N'HORTA',N'HORTA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT200','4801','no',N'LAJES DAS FLORES',N'LAJES DAS FLORES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT200','4802','no',N'SANTA CRUZ DAS FLORES',N'SANTA CRUZ DAS FLORES');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('PT','PT200','4901','no',N'CORVO',N'CORVO');
