INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI043','1','no',N'Ajdovščina',N'AJDOVŠČINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','2','no',N'Beltinci',N'BELTINCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI042','3','no',N'Bled',N'BLED');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI042','4','no',N'Bohinj',N'BOHINJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','5','no',N'Borovnica',N'BOROVNICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI043','6','no',N'Bovec',N'BOVEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI043','7','no',N'Brda',N'BRDA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','8','no',N'Brezovica',N'BREZOVICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI036','9','no',N'Brežice',N'BREŽICE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','10','no',N'Tišina',N'TIŠINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','11','no',N'Celje',N'CELJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI042','12','no',N'Cerklje na Gorenjskem',N'CERKLJE NA GORENJSKEM');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI038','13','no',N'Cerknica',N'CERKNICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI043','14','no',N'Cerkno',N'CERKNO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','15','no',N'Črenšovci',N'ČRENŠOVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI033','16','no',N'Črna na Koroškem',N'ČRNA NA KOROŠKEM');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI037','17','no',N'Črnomelj',N'ČRNOMELJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','18','no',N'Destrnik',N'DESTRNIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI044','19','no',N'Divača',N'DIVAČA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','20','no',N'Dobrepolje',N'DOBREPOLJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','21','no',N'Dobrova - Polhov Gradec',N'DOBROVA - POLHOV GRADEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','22','no',N'Dol pri Ljubljani',N'DOL PRI LJUBLJANI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','23','no',N'Domžale',N'DOMŽALE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','24','no',N'Dornava',N'DORNAVA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI033','25','no',N'Dravograd',N'DRAVOGRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','26','no',N'Duplek',N'DUPLEK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI042','27','no',N'Gorenja vas - Poljane',N'GORENJA VAS - POLJANE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','28','no',N'Gorišnica',N'GORIŠNICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','29','no',N'Gornja Radgona',N'GORNJA RADGONA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','30','no',N'Gornji Grad',N'GORNJI GRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','31','no',N'Gornji Petrovci',N'GORNJI PETROVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','32','no',N'Grosuplje',N'GROSUPLJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','33','no',N'Šalovci',N'ŠALOVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI035','34','no',N'Hrastnik',N'HRASTNIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI044','35','no',N'Hrpelje - Kozina',N'HRPELJE - KOZINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI043','36','no',N'Idrija',N'IDRIJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','37','no',N'Ig',N'IG');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI038','38','no',N'Ilirska Bistrica',N'ILIRSKA BISTRICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','39','no',N'Ivančna Gorica',N'IVANČNA GORICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI044','40','no',N'Izola/Isola',N'IZOLA/ISOLA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI042','41','no',N'Jesenice',N'JESENICE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','42','no',N'Juršinci',N'JURŠINCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','43','no',N'Kamnik',N'KAMNIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI043','44','no',N'Kanal',N'KANAL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','45','no',N'Kidričevo',N'KIDRIČEVO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI043','46','no',N'Kobarid',N'KOBARID');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','47','no',N'Kobilje',N'KOBILJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI037','48','no',N'Kočevje',N'KOČEVJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI044','49','no',N'Komen',N'KOMEN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI044','50','no',N'Koper/Capodistria',N'KOPER/CAPODISTRIA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','51','no',N'Kozje',N'KOZJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI042','52','no',N'Kranj',N'KRANJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI042','53','no',N'Kranjska Gora',N'KRANJSKA GORA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI036','54','no',N'Krško',N'KRŠKO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','55','no',N'Kungota',N'KUNGOTA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','56','no',N'Kuzma',N'KUZMA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','57','no',N'Laško',N'LAŠKO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','58','no',N'Lenart',N'LENART');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','59','no',N'Lendava/Lendva',N'LENDAVA/LENDVA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI035','60','no',N'Litija',N'LITIJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','61','no',N'Ljubljana',N'LJUBLJANA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','62','no',N'Ljubno',N'LJUBNO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','63','no',N'Ljutomer',N'LJUTOMER');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','64','no',N'Logatec',N'LOGATEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI038','65','no',N'Loška dolina',N'LOŠKA DOLINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI037','66','no',N'Loški Potok',N'LOŠKI POTOK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','67','no',N'Luče',N'LUČE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','68','no',N'Lukovica',N'LUKOVICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','69','no',N'Majšperk',N'MAJŠPERK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','70','no',N'Maribor',N'MARIBOR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','71','no',N'Medvode',N'MEDVODE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','72','no',N'Mengeš',N'MENGEŠ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI037','73','no',N'Metlika',N'METLIKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI033','74','no',N'Mežica',N'MEŽICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI043','75','no',N'Miren - Kostanjevica',N'MIREN - KOSTANJEVICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI033','76','no',N'Mislinja',N'MISLINJA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','77','no',N'Moravče',N'MORAVČE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','78','no',N'Moravske Toplice',N'MORAVSKE TOPLICE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','79','no',N'Mozirje',N'MOZIRJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','80','no',N'Murska Sobota',N'MURSKA SOBOTA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI033','81','no',N'Muta',N'MUTA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI042','82','no',N'Naklo',N'NAKLO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','83','no',N'Nazarje',N'NAZARJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI043','84','no',N'Nova Gorica',N'NOVA GORICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI037','85','no',N'Novo mesto',N'NOVO MESTO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','86','no',N'Odranci',N'ODRANCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','87','no',N'Ormož',N'ORMOŽ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI037','88','no',N'Osilnica',N'OSILNICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','89','no',N'Pesnica',N'PESNICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI044','90','no',N'Piran/Pirano',N'PIRAN/PIRANO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI038','91','no',N'Pivka',N'PIVKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','92','no',N'Podčetrtek',N'PODČETRTEK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI033','93','no',N'Podvelka',N'PODVELKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI038','94','no',N'Postojna',N'POSTOJNA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI042','95','no',N'Preddvor',N'PREDDVOR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','96','no',N'Ptuj',N'PTUJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','97','no',N'Puconci',N'PUCONCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','98','no',N'Rače - Fram',N'RAČE - FRAM');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI036','99','no',N'Radeče',N'RADEČE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','100','no',N'Radenci',N'RADENCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI033','101','no',N'Radlje ob Dravi',N'RADLJE OB DRAVI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI042','102','no',N'Radovljica',N'RADOVLJICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI033','103','no',N'Ravne na Koroškem',N'RAVNE NA KOROŠKEM');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI037','104','no',N'Ribnica',N'RIBNICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','105','no',N'Rogašovci',N'ROGAŠOVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','106','no',N'Rogaška Slatina',N'ROGAŠKA SLATINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','107','no',N'Rogatec',N'ROGATEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','108','no',N'Ruše',N'RUŠE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI037','109','no',N'Semič',N'SEMIČ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI036','110','no',N'Sevnica',N'SEVNICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI044','111','no',N'Sežana',N'SEŽANA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI033','112','no',N'Slovenj Gradec',N'SLOVENJ GRADEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','113','no',N'Slovenska Bistrica',N'SLOVENSKA BISTRICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','114','no',N'Slovenske Konjice',N'SLOVENSKE KONJICE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','115','no',N'Starše',N'STARŠE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','116','no',N'Sveti Jurij ob Ščavnici',N'SVETI JURIJ OB ŠČAVNICI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI042','117','no',N'Šenčur',N'ŠENČUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','118','no',N'Šentilj',N'ŠENTILJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI037','119','no',N'Šentjernej',N'ŠENTJERNEJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','120','no',N'Šentjur',N'ŠENTJUR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI037','121','no',N'Škocjan',N'ŠKOCJAN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI042','122','no',N'Škofja Loka',N'ŠKOFJA LOKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','123','no',N'Škofljica',N'ŠKOFLJICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','124','no',N'Šmarje pri Jelšah',N'ŠMARJE PRI JELŠAH');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','125','no',N'Šmartno ob Paki',N'ŠMARTNO OB PAKI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','126','no',N'Šoštanj',N'ŠOŠTANJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','127','no',N'Štore',N'ŠTORE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI043','128','no',N'Tolmin',N'TOLMIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI035','129','no',N'Trbovlje',N'TRBOVLJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI037','130','no',N'Trebnje',N'TREBNJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI042','131','no',N'Tržič',N'TRŽIČ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','132','no',N'Turnišče',N'TURNIŠČE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','133','no',N'Velenje',N'VELENJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','134','no',N'Velike Lašče',N'VELIKE LAŠČE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','135','no',N'Videm',N'VIDEM');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI043','136','no',N'Vipava',N'VIPAVA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','137','no',N'Vitanje',N'VITANJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','138','no',N'Vodice',N'VODICE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','139','no',N'Vojnik',N'VOJNIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','140','no',N'Vrhnika',N'VRHNIKA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI033','141','no',N'Vuzenica',N'VUZENICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI035','142','no',N'Zagorje ob Savi',N'ZAGORJE OB SAVI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','143','no',N'Zavrč',N'ZAVRČ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','144','no',N'Zreče',N'ZREČE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI042','146','no',N'Železniki',N'ŽELEZNIKI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI042','147','no',N'Žiri',N'ŽIRI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','148','no',N'Benedikt',N'BENEDIKT');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI036','149','no',N'Bistrica ob Sotli',N'BISTRICA OB SOTLI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI038','150','no',N'Bloke',N'BLOKE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','151','no',N'Braslovče',N'BRASLOVČE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','152','no',N'Cankova',N'CANKOVA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','153','no',N'Cerkvenjak',N'CERKVENJAK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','154','no',N'Dobje',N'DOBJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','155','no',N'Dobrna',N'DOBRNA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','156','no',N'Dobrovnik/Dobronak',N'DOBROVNIK/DOBRONAK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI037','157','no',N'Dolenjske Toplice',N'DOLENJSKE TOPLICE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','158','no',N'Grad',N'GRAD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','159','no',N'Hajdina',N'HAJDINA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','160','no',N'Hoče - Slivnica',N'HOČE - SLIVNICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','161','no',N'Hodoš/Hodos',N'HODOŠ/HODOS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','162','no',N'Horjul',N'HORJUL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI042','163','no',N'Jezersko',N'JEZERSKO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','164','no',N'Komenda',N'KOMENDA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI037','165','no',N'Kostel',N'KOSTEL');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','166','no',N'Križevci',N'KRIŽEVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','167','no',N'Lovrenc na Pohorju',N'LOVRENC NA POHORJU');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','168','no',N'Markovci',N'MARKOVCI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','169','no',N'Miklavž na Dravskem polju',N'MIKLAVŽ NA DRAVSKEM POLJU');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI037','170','no',N'Mirna Peč',N'MIRNA PEČ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','171','no',N'Oplotnica',N'OPLOTNICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','172','no',N'Podlehnik',N'PODLEHNIK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','173','no',N'Polzela',N'POLZELA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','174','no',N'Prebold',N'PREBOLD');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI033','175','no',N'Prevalje',N'PREVALJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','176','no',N'Razkrižje',N'RAZKRIŽJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI033','177','no',N'Ribnica na Pohorju',N'RIBNICA NA POHORJU');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','178','no',N'Selnica ob Dravi',N'SELNICA OB DRAVI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI037','179','no',N'Sodražica',N'SODRAŽICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','180','no',N'Solčava',N'SOLČAVA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','181','no',N'Sveta Ana',N'SVETA ANA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','182','no',N'Sveti Andraž v Slov. goricah',N'SVETI ANDRAŽ V SLOV. GORICAH');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI043','183','no',N'Šempeter - Vrtojba',N'ŠEMPETER - VRTOJBA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','184','no',N'Tabor',N'TABOR');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','185','no',N'Trnovska vas',N'TRNOVSKA VAS');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','186','no',N'Trzin',N'TRZIN');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','187','no',N'Velika Polana',N'VELIKA POLANA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','188','no',N'Veržej',N'VERŽEJ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','189','no',N'Vransko',N'VRANSKO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','190','no',N'Žalec',N'ŽALEC');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','191','no',N'Žetale',N'ŽETALE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI042','192','no',N'Žirovnica',N'ŽIROVNICA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI037','193','no',N'Žužemberk',N'ŽUŽEMBERK');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','194','no',N'Šmartno pri Litiji',N'ŠMARTNO PRI LITIJI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI031','195','no',N'Apače',N'APAČE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','196','no',N'Cirkulane',N'CIRKULANE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI036','197','no',N'Kostanjevica na Krki',N'KOSTANJEVICA NA KRKI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','198','no',N'Makole',N'MAKOLE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI037','199','no',N'Mokronog - Trebelno',N'MOKRONOG - TREBELNO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','200','no',N'Poljčane',N'POLJČANE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI043','201','no',N'Renče - Vogrsko',N'RENČE - VOGRSKO');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','202','no',N'Središče ob Dravi',N'SREDIŠČE OB DRAVI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI037','203','no',N'Straža',N'STRAŽA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','204','no',N'Sveta Trojica v Slov. goricah',N'SVETA TROJICA V SLOV. GORICAH');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','205','no',N'Sveti Tomaž',N'SVETI TOMAŽ');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI037','206','no',N'Šmarješke Toplice',N'ŠMARJEŠKE TOPLICE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI042','207','no',N'Gorje',N'GORJE');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI041','208','no',N'Log - Dragomer',N'LOG - DRAGOMER');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI034','209','no',N'Rečica ob Savinji',N'REČICA OB SAVINJI');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI032','210','no',N'Sveti Jurij v Slov. goricah',N'SVETI JURIJ V SLOV. GORICAH');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI037','211','no',N'Šentrupert',N'ŠENTRUPERT');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI037','212','no',N'Mirna',N'MIRNA');
INSERT INTO dbo.laus (country_code,nuts3,lau1,_change,name1,name2) VALUES ('SI','SI044','213','no',N'Ankaran/Ancarano',N'ANKARAN/ANCARANO');
