DROP TABLE SEC_USERS_T IF EXISTS;
DROP TABLE SEC_USER_ROLES_T IF EXISTS;
DROP TABLE SEC_ROLES_T IF EXISTS;
DROP TABLE SEC_ROLE_RIGHTS_T IF EXISTS;
DROP TABLE SEC_RIGHTS_T IF EXISTS;

CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(38), PRIMARY KEY (SEQ_NAME));
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 50);


CREATE TABLE SEC_USERS_T (PER_ID INTEGER NOT NULL, USERID VARCHAR(20), PRIMARY KEY (PER_ID));
CREATE TABLE SEC_ROLES_T (ROLE_ID INTEGER NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ROLE_ID));
CREATE TABLE SEC_RIGHTS_T (RIGHT_ID INTEGER NOT NULL, NAME VARCHAR(255), PRIMARY KEY (RIGHT_ID));
CREATE TABLE SEC_USER_ROLES_T (PER_ID INTEGER NOT NULL, ROLE_ID INTEGER NOT NULL);
CREATE TABLE SEC_ROLE_RIGHTS_T (ROLE_ID INTEGER NOT NULL, RIGHT_ID INTEGER NOT NULL);

INSERT INTO SEC_USERS_T VALUES (152488, 'roelsgr');
INSERT INTO SEC_ROLES_T VALUES (1, 'ADMIN');
INSERT INTO SEC_RIGHTS_T VALUES (1, 'right.connect');
INSERT INTO SEC_ROLE_RIGHTS_T VALUES (1, 1);
INSERT INTO SEC_USER_ROLES_T VALUES (152488, 1);

