package abac.budgetary_commitment_level2.service.es.async.v1;

import abac.budgetary_commitment_level2.v1.*;
import abac.message.v1.BusinessRuleMessageResponseType;
import abac.messagefault.v1.FaultMessage;
import abac.posting_criteria.v1.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-07-28T12:43:17.370+02:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/v1", name = "BudgetaryCommitmentLevel2Port")
@XmlSeeAlso({abac.ares_document.v1.ObjectFactory.class, abac.br.v1.ObjectFactory.class, abac.complex_type.v1.ObjectFactory.class, ObjectFactory.class, abac.organisation.v1.ObjectFactory.class, abac.local_abac_document_detail.v1.ObjectFactory.class, abac.responsible_user.v1.ObjectFactory.class, abac.external_criteria.v1.ObjectFactory.class, abac.posting_criteria_link.v1.ObjectFactory.class, abac.workflow_object.v1.ObjectFactory.class, abac.currency.v1.ObjectFactory.class, abac.external_criteria_code.v1.ObjectFactory.class, abac.wbs.v1.ObjectFactory.class, abac.organisational_group.v1.ObjectFactory.class, abac.performance_guarantee_indicator.v1.ObjectFactory.class, abac.supporting_document.v1.ObjectFactory.class, abac.workflow.v1.ObjectFactory.class, abac.local_abac_document.v1.ObjectFactory.class, abac.central_reference.v1.ObjectFactory.class, abac.abac_object.v1.ObjectFactory.class, abac.message.v1.ObjectFactory.class, abac.budgetary_commitment_level2.v1.ObjectFactory.class, abac.contractor_reference.v1.ObjectFactory.class, abac.scanned_document.v1.ObjectFactory.class, abac.external_criteria_type.v1.ObjectFactory.class, abac.associated_country.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BudgetaryCommitmentLevel2Port {

    @WebMethod(operationName = "delete_responsible_user", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/delete_responsible_user/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2DeleteResponsibleUserResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType deleteResponsibleUser(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2DeleteResponsibleUserRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2DeleteResponsibleUserRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "create_associated_country", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/create_associated_country/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2CreateAssociatedCountryResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType createAssociatedCountry(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2CreateAssociatedCountryRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2CreateAssociatedCountryRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "create_envelope_link", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/create_envelope_link/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2CreateEnvelopeLinkResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType createEnvelopeLink(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2CreateEnvelopeLinkRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2CreateEnvelopeLinkRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "create_scanned_document", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/create_scanned_document/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2CreateScannedDocumentResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType createScannedDocument(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2CreateScannedDocumentRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2CreateScannedDocumentRequestType parameters
    ) throws FaultMessage;

    @WebMethod(action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/create/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2CreateResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType create(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2CreateRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2CreateRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "create_posting_criteria_link", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/create_posting_criteria_link/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2CreatePostingCriteriaLinkResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType createPostingCriteriaLink(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2CreatePostingCriteriaLinkRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2CreatePostingCriteriaLinkRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "create_ares_document", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/create_ares_document/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2CreateAresDocumentResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType createAresDocument(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2CreateAresDocumentRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2CreateAresDocumentRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "delete_associated_country", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/delete_associated_country/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2DeleteAssociatedCountryResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType deleteAssociatedCountry(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2DeleteAssociatedCountryRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2DeleteAssociatedCountryRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "modify_associated_country", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/modify_associated_country/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2ModifyAssociatedCountryResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType modifyAssociatedCountry(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2ModifyAssociatedCountryRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2ModifyAssociatedCountryRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "give_visa", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/give_visa/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2GiveVisaResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType giveVisa(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2GiveVisaRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2GiveVisaRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "modify_position", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/modify_position/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2ModifyPositionResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType modifyPosition(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2ModifyPositionRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2ModifyPositionRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "modify_posting_criteria_link", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/modify_posting_criteria_link/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2ModifyPostingCriteriaLinkResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType modifyPostingCriteriaLink(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2ModifyPostingCriteriaLinkRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2ModifyPostingCriteriaLinkRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "create_supporting_document", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/create_supporting_document/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2CreateSupportingDocumentResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType createSupportingDocument(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2CreateSupportingDocumentRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2CreateSupportingDocumentRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "modify_par", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/modify_par/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2ModifyPARResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType modifyPar(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2ModifyPARRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2ModifyPARRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "create_wbs", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/create_wbs/v1")
    public void createWbs(
            @WebParam(partName = "parameters", mode = WebParam.Mode.INOUT, name = "BudgetaryCommitmentLevel2CreateWbsRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    javax.xml.ws.Holder<BudgetaryCommitmentLevel2CreateWbsRequestType> parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "modify_envelope_link", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/modify_envelope_link/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2ModifyEnvelopeLinkResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType modifyEnvelopeLink(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2ModifyEnvelopeLinkRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2ModifyEnvelopeLinkRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "modify_wbs", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/modify_wbs/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2ModifyWbsResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType modifyWbs(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2ModifyWbsRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2ModifyWbsRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "create_supporting_document_folder", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/create_supporting_document_folder/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2CreateSupportingDocumentFolderResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType createSupportingDocumentFolder(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2CreateSupportingDocumentFolderRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2CreateSupportingDocumentFolderRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "create_position", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/create_position/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2CreatePositionResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType createPosition(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2CreatePositionRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2CreatePositionRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "create_contractor_reference", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/create_contractor_reference/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2CreateContractorReferenceResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType createContractorReference(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2CreateContractorReferenceRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2CreateContractorReferenceRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "modify_supporting_document", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/modify_supporting_document/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2ModifySupportingDocumentResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType modifySupportingDocument(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2ModifySupportingDocumentRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2ModifySupportingDocumentRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "create_responsible_user", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/create_responsible_user/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2CreateResponsibleUserResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType createResponsibleUser(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2CreateResponsibleUserRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2CreateResponsibleUserRequestType parameters
    ) throws FaultMessage;

    @WebMethod(action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/modify/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2ModifyResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType modify(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2ModifyRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2ModifyRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "create_envelope_link_associated_country", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/create_envelope_link_associated_country/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2CreateEnvelopeLinkAssociatedCountryResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType createEnvelopeLinkAssociatedCountry(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2CreateEnvelopeLinkAssociatedCountryRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2CreateEnvelopeLinkAssociatedCountryRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "modify_contractor_reference", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/modify_contractor_reference/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2ModifyContractorReferenceResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType modifyContractorReference(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2ModifyContractorReferenceRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2ModifyContractorReferenceRequestType parameters
    ) throws FaultMessage;

    @WebMethod(operationName = "modify_supporting_document_folder", action = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/service/es/async/modify_supporting_document_folder/v1")
    @WebResult(name = "BudgetaryCommitmentLevel2ModifySupportingDocumentFolderResponse", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1", partName = "parameters")
    public BusinessRuleMessageResponseType modifySupportingDocumentFolder(
            @WebParam(partName = "parameters", name = "BudgetaryCommitmentLevel2ModifySupportingDocumentFolderRequest", targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level2/v1")
                    BudgetaryCommitmentLevel2ModifySupportingDocumentFolderRequestType parameters
    ) throws FaultMessage;
}
