package eu.europa.ec.budg.abac.budgetary_commitment_level1.service.es.sync.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-12T13:33:14.168+02:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "BudgetaryCommitmentLevel1", 
                  //wsdlLocation = "file:/C:/Users/lviverof/Documents/test2/src/main/java/BUDG_BudgetaryCommitmentLevel1_ES_Sync_1.wsdl",
                  //wsdlLocation = "http://wlts0275.cc.cec.eu.int:1043/wifi4eu-financial/wsdl/BUDG_BudgetaryCommitmentLevel1_ES_Sync_1.wsdl",
                  wsdlLocation = "http://localhost:7001/wifi4eu-financial/wsdl/BUDG_BudgetaryCommitmentLevel1_ES_Sync_1.wsdl",
                  targetNamespace = "http://www.ec.europa.eu/budg/abac/budgetary_commitment_level1/service/es/sync/v1") 
public class BudgetaryCommitmentLevel1 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.ec.europa.eu/budg/abac/budgetary_commitment_level1/service/es/sync/v1", "BudgetaryCommitmentLevel1");
    public final static QName BudgetaryCommitmentLevel1SOAP = new QName("http://www.ec.europa.eu/budg/abac/budgetary_commitment_level1/service/es/sync/v1", "BudgetaryCommitmentLevel1SOAP");
    static {
        URL url = null;
        try {
            //url = new URL("file:/C:/Users/lviverof/Documents/test2/src/main/java/BUDG_BudgetaryCommitmentLevel1_ES_Sync_1.wsdl");
            //url = new URL("http://wlts0275.cc.cec.eu.int:1043/wifi4eu-financial/wsdl/BUDG_BudgetaryCommitmentLevel1_ES_Sync_1.wsdl");
            url = new URL("http://localhost:7001/wifi4eu-financial/wsdl/BUDG_BudgetaryCommitmentLevel1_ES_Sync_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BudgetaryCommitmentLevel1.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "BUDG_BudgetaryCommitmentLevel1_ES_Sync_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BudgetaryCommitmentLevel1(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BudgetaryCommitmentLevel1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BudgetaryCommitmentLevel1() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BudgetaryCommitmentLevel1(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BudgetaryCommitmentLevel1(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BudgetaryCommitmentLevel1(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns BudgetaryCommitmentLevel1Port
     */
    @WebEndpoint(name = "BudgetaryCommitmentLevel1SOAP")
    public BudgetaryCommitmentLevel1Port getBudgetaryCommitmentLevel1SOAP() {
        return super.getPort(BudgetaryCommitmentLevel1SOAP, BudgetaryCommitmentLevel1Port.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BudgetaryCommitmentLevel1Port
     */
    @WebEndpoint(name = "BudgetaryCommitmentLevel1SOAP")
    public BudgetaryCommitmentLevel1Port getBudgetaryCommitmentLevel1SOAP(WebServiceFeature... features) {
        return super.getPort(BudgetaryCommitmentLevel1SOAP, BudgetaryCommitmentLevel1Port.class, features);
    }

}
